### ISSUE TITLE
ldap duplicate key value

### ISSUE THREAD

**Issue by q16marvin** [goauthentik/authentik#10026]
**Describe the bug**
after update to version 2024.4.2 i got on every sync many of this configuration erros:

Failed to create user: duplicate key value violates unique constraint "authentik_core_user_username_key" DETAIL: Key (username)=(jdoes) already exists. To merge new user with existing user, set the user's Attribute 'ldap_uniq' to 'S-1-5-21-1920821311-3523207831-4185578861-1186' 

**To Reproduce**
rollback to 2024.4.1 and its fine again

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: docker

i have no idea what im doing wrong.

**Comment by rfpg1** [comment]
Hello,

Did you mange to fix this? Having the same issue
