### ISSUE TITLE
AzureAD OAuth Source - Profile URL Reset

### ISSUE THREAD

**Issue by ghost** [goauthentik/authentik#10020]
**Describe the bug**
The profile URL on the `AzureAD` OAuth Source on Federation and Social login keeps resetting.

Manually set this to `https://graph.microsoft.com/v1.0/me` and a few hours later it will set itself to the value of `https://graph.microsoft.com/oidc/userinfo`

This then gives my users the error
```
Request to authenticate with AzureAD has been denied. Please authenticate with the source you've previously signed up with.
```

Setting the profile URL back to `https://graph.microsoft.com/v1.0/me` allows for authentication to continue

**To Reproduce**

1. Go to Federation and Social Login, create an AzureAD OAuth Source with a profile URL of `https://graph.microsoft.com/v1.0/me` (the default). Set user matching to mode to "Link to a user with an identical email address. Can have security implications when a source doesn't have a valid email address
2. Wait a couple of hours (less than 12 hours)
3. Try to log in to Authentik using AzureAD as a connected source and receive `Request to authenticate with AzureAD has been denied. Please authenticate with the source you've previously signed up with.`
4. Set profile URL in OAuth source back to `https://graph.microsoft.com/v1.0/me` and sucessfully complete login flow.

**Expected behavior**
Profile URL to stay as inputted value.

**Screenshots**
![AzureAD0](https://github.com/goauthentik/authentik/assets/102985498/6f3418d7-4acd-47b7-8aef-747ff2859b4e)
![AzureAD1](https://github.com/goauthentik/authentik/assets/102985498/ac666e35-65ad-4e52-bcf7-26b369f9e8a0)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: helm

**Comment by martinadamsUL** [comment]
After some debugging, it looks like it's the `well-known` URL that's resetting this back to `https://graph.microsoft.com/oidc/userinfo` as this is what's in the OIDC response on Microsoft's end.

When using `https://graph.microsoft.com/oidc/userinfo` and trying to match on email, I will get the `use the login method you previously used to signup` message (or something to that effect).

I guess I'm hoping authentik can fully support the information given in the `https://graph.microsoft.com/oidc/userinfo` url - but for now I'm going to leave the `well-known` URL blank and hope my `Profile URL` stays `https://graph.microsoft.com/v1.0/me`

**Comment by bsirayne** [comment]
+1 on this issue. I'm also going to remove the well-known URL as a temp workaround while I do some more research.

**Comment by mauznk** [comment]
+1 for the issue. My collegue had the same issue on 2024.4.2. My instance is running on 2024.2.2 and dont have the issue.
We upgraded now to 2024.6.0 to test is the issue perists

**Comment by martinadamsUL** [comment]
FWIW, if it makes any difference, in my URLs on my AzureAD social profiles have `\common\` replaced with `\<my tenant ID>\`

**Comment by martinadamsUL** [comment]
Bump

**Comment by Matt-CyberGuy** [comment]
Bump... looks like i just posted about this issue a few days ago
https://github.com/goauthentik/authentik/issues/16486

**Comment by infactai** [comment]
bump. Same issue. I had my install working by changing Profile URL to
`https://graph.microsoft.com/v1.0/me` from
`https://graph.microsoft.com/oidc/userinfo`

But after 24 hours, my profile URL got reset back to
`https://graph.microsoft.com/oidc/userinfo`

And it no longer works

---

Question to others with this problem for debugging:

**ARE YOU USING SINGLE OR MULTI-TENANT**

For me it's single tenant. I haven't attempted multi

---
The actual issue I think most people are having, is that 
https://graph.microsoft.com/oidc/userinfo

Does not return email address of the users.

I don't know why. And I haven't debugged this.

Personally I check the returned email address and then accept/deny authorization.

---

**Temporary FIX**

`Leave the OIDC Well-known URL: field blank`

---

Authentik Version: 2025.10.2

I'm also using single tenant in Azure.

So all my URLs have been replaced by tenant specific URLs.

```
Authorization URL:
https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/authorize

Access Token URL:
https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/token

Profile URL:
https://graph.microsoft.com/v1.0/me

OIDC Well-known URL:
https://login.microsoftonline.com/$TENANT_ID/v2.0/.well-known/openid-configuration

OIDC JWKS URL:
https://login.microsoftonline.com/$TENANT_ID/discovery/v2.0/keys
```

---

Related Issues:
* https://github.com/goauthentik/authentik/issues/11746
* https://github.com/goauthentik/authentik/issues/16486
* https://github.com/goauthentik/authentik/issues/10829

Maybe related:
* https://github.com/goauthentik/authentik/pull/8147
* https://github.com/goauthentik/authentik/issues/8342
* https://github.com/goauthentik/authentik/issues/8131
* https://github.com/goauthentik/authentik/issues/7972

**Comment by Matt-CyberGuy** [comment]
Leave the `OIDC Well-known URL:` field blank... it contains the data that's auto setting your fields to Microsoft's default OpenID settings... not sure which thread that got answered on for me, but forgot to come back here and post the solution

**Comment by infactai** [comment]
> Leave the `OIDC Well-known URL:` field blank... it contains the data that's auto setting your fields to Microsoft's default OpenID settings... not sure which thread that got answered on for me, but forgot to come back here and post the solution

I'll give this a go and see if it resolves the issue.

Do you think this is a "bug" or "just how it works"

Seems very confusing for end users to need all these work arounds. I'm not familiar enough with Azure, so it's unclear to me.

**Comment by Matt-CyberGuy** [comment]
> Do you think this is a "bug" or "just how it works"

🤷🏻‍♂️ no idea... I just know one day our login address started changing and causing problems for non domain users needing to authenticate

It might've been a bug that the `Well-known URL` wasn't auto setting the other fields and they fixed it, which broke our setups ;)

**Comment by dewi-tik** [comment]
It is the well known URL causing this reset issue. That's why the provider no longer auto sets this URL:

<img width="863" height="534" alt="Image" src="https://github.com/user-attachments/assets/dd7c2c08-c637-4123-bf59-8dc2c23f26a2" />
