### ISSUE TITLE
[Guacamole] Rejected OpenID Token

### ISSUE THREAD

**Issue by CrazyWolf13** [goauthentik/authentik#10126]
**Describe the bug**
Hi
I've set upt TOPT on my guacamole account.

Then I've setup Authentik auth, while disabling TOPT, this works fine.

After enabling TOPT again, and logging in, I get first redirected to authentik, log in, weirdly get a TOPT request, I enter the code, I get an error:

```
Jun 16 22:22:48 guacamole tomcat9[188]: 22:22:48.150 [http-nio-8080-exec-8] INFO  o.a.g.r.auth.AuthenticationService - User "XXXX" successfully authenticated from [192.168.1.200, 10.10.20.13].
Jun 16 22:22:53 guacamole tomcat9[188]: 22:22:53.477 [http-nio-8080-exec-10] INFO  o.a.g.a.o.t.TokenValidationService - Rejected OpenID token with invalid/old nonce.
```

**To Reproduce**

1. Enable Authentik loging method on guacamole
2. Also enable TOPT, so when not using authentik, I can still sign in with TOPT and user/password, as failproof.
3. End up in an auth loop or auth error.

**Expected behavior**
Well I expect not to get a rejected OpenID Token.

**Screenshots**
![grafik](https://github.com/goauthentik/authentik/assets/96661824/4f4018cd-6208-4d03-b709-1d071b10e655)
![grafik](https://github.com/goauthentik/authentik/assets/96661824/fa9d8120-db2b-4fc4-8016-b7a4e81242e4)

**Logs**
```
Jun 16 22:22:48 guacamole tomcat9[188]: 22:22:48.150 [http-nio-8080-exec-8] INFO  o.a.g.r.auth.AuthenticationService - User "XXXX" successfully authenticated from [192.168.1.200, 10.10.20.13].
Jun 16 22:22:53 guacamole tomcat9[188]: 22:22:53.477 [http-nio-8080-exec-10] INFO  o.a.g.a.o.t.TokenValidationService - Rejected OpenID token with invalid/old nonce.
```

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.4.2](https://goauthentik.io/docs/releases/2024.4)
-   Deployment: [Docker-Compose]

**Comment by CrazyWolf13** [comment]
Was indeed an upstream issue on Guacamole -> https://issues.apache.org/jira/browse/GUACAMOLE-1780

**Comment by Christopher87R** [comment]
I'm using version 1.6.0 and Authentik version 2026.02, and I'm experiencing exactly the problem described here.

TokenValidationService - Rejected OpenID token with invalid/old nonce.

The OTP setup isn't working; I then manually set it to “confirmed”—the secret matches.

The local user account works, as does creating new users and activating their OTP.
