### ISSUE TITLE
Make semicolon separation optional

### ISSUE THREAD

**Issue by Lokkenum** [goauthentik/authentik#10299]
Hello there!

According to official documentation:
https://docs.goauthentik.io/docs/providers/ldap/#bind-modes
> For code-based authenticators, the code must be given as part of the bind password, separated by a semicolon. For example for the password example-password and the code 123456, the input must be example-password;123456.

What is the reason and purpose for semicolon separation? 
I'm getting a ton of negative feedback from users especially from notebooks and mobile devices who are forgetting to add semicolon. 

How to get rid of this requirement or make this optional?
Should be a quick fix/feature. 

Thank you!

**Comment by BeryJu** [comment]
Before we introduced the option to make support for MFA in LDAP a toggle that can be enabled, having the semicolon required was part of the detection for MFA codes

**Comment by Lokkenum** [comment]
> Before we introduced the option to make support for MFA in LDAP a toggle that can be enabled, having the semicolon required was part of the detection for MFA codes

Strange requirement. 
What will happen if user password contains semicolon like in this `example;password;123456` ?
Why just not to parse last 6-8 digit's from password string?

**Comment by BeryJu** [comment]
The reason this initially required a semicolon is that when the option wasn't present we would use the last semicolon of the entered password to determine if there was a code present. With just TOTP we can obviously just detect the last 6/8 numbers but static tokens may also be used which can have different lengths and are alphanumeric.

As the flow execution is dynamic and the outpost doesn't know which stage will come next, we can't dynamically split the entered password apart, as we don't know if the current flow will contain an MFA stage or not. With the static separator, this behaviour is correct in most cases
