### ISSUE TITLE
Oauth Authentication stopped working after host migration

### ISSUE THREAD

**Issue by Jdplays** [goauthentik/authentik#10297]
I am trying to migrate my portainer, traefik and authentik instances to another host. I have got them over and running. I copied their data folders over to the new machine and mounted them to their containers, so they are set up exactly the same as before. Traefik seems to work fine and is proxying different things. I can log in to portainer locally and use it. Authentik is also working and i can log in with the same use i did before and i can even use the forward proxy to protect some services with middleware with traefik.

But for some reason any app that uses authentik Oauth doesnt work anymore. I usually log into portainer with Oauth through authentik. Now when i click the button, it does redirect me to authentik which tells me to sign in to view portainer. When i do that everything is successful and it redirects me to portainer. The portainer loads for about a minute and then says it cannot sign in. The docker logs for portainer print this out:

HTTP error | error=Unauthorized msg="A valid authorisation token is missing

I still have the other machine on while i migrate everything else over, so i tore down the authentik containers on the new host and spun them back up on the old host, once dns had been fixed, i tried portainer again. This time it fully logs in. But when i switch it back to the new host, it stops working again

Does anyone know what might be wrong or if there is a propper way to to migrate authentik without having to just copy/paste the mounted data folders.
Thanks!

**Comment by Jdplays** [comment]
So a bit of an update. When i route it through the old instance of traefik, it works file. So it seems like the actual authentik instance is fine. But its just weird that on the new instance, only the Oauth doesnt work. Is there something i am missing?

**Comment by kdoberitz** [comment]
@Jdplays Have you ever found a solution for this? It seems that I ran into the same issue.

**Comment by Jdplays** [comment]
Hey, @kdoberitz, so this was a few months ago and i kind of forget my exact fix. But if i remember correctly, it was something to do with docker networks that the containers were on. I was trying to set up extra VLAN's on my new server. So Authentik was on a different docker VLAN network to Portainer. 

The fix was that whatever docker networks Portainer (or any other OAuth service) was using, Authentik also had to be on those networks. So now my Authentik instance has ip's on a few different VLAN's. This only matters for the Authentik Server container

Also remember to have both services on your Traefik network. In my case "proxy".

It has been a while, so i might have missed a few things, but i think that was roughly the issue and the solution.

**Comment by kdoberitz** [comment]
Hi @Jdplays thanks for your feedback. So if I understand this correctly it is necessary to put the relevant containers on a second shared docker network? The "traefik"/"proxy" network alone is not enough? That can't be right? Maybe I have to look somewhere else.

**Comment by Jdplays** [comment]
Hey @kdoberitz, 

Well no, it was just that i was moving some of my containers to different VLAN's which meant i had to add them to separate docker networks. That is what caused the issue. The only fixes i found were to either add the authentik container to those same networks or just remove those networks all together. 

I dont know if this was the right fix, but it worked for me...
