### ISSUE TITLE
LDAP Property Mappings not propagated to LDAP Outpost

### ISSUE THREAD

**Issue by mpaluch92** [goauthentik/authentik#10347]
**Describe the bug**
LDAP Property Mappings (for example to set the object field `givenname` based on the `request.user.name` field) are not set in the LDAP Outpost.

**To Reproduce**
1. Go to `Customization` -> `Property Mappings` and create a `LDAP Property Mapping`. For example:
    - Name: `extract_last_name`
    - Object field: `sn`
    - Expression: 
       ```python
        def get_last_name():
                name_parts = request.user.name.split()
                if len(name_parts) > 1:
                    return name_parts[-1]
                else:
                    return "N/A"

        return {"sn": get_last_name()}
       ```
    
2. Perform a query using `ldapsearch`. 
3. See that the object field `sn` is not updated using the LDAP Property Mapping. However, testing the LDAP Property Mapping via GUI yields the correct value for the object field `sn`.

**Expected behavior**
When defining LDAP Property Mappings, the LDAP Outpost should show the LDAP Property Mappings as well.

**Version and Deployment (please complete the following information):**
-   authentik version: 2024.6.0
-   Deployment: docker-compose

**Additional context**
The integration docs for Snipe-IT also tell us to define [LDAP Property Mappings](https://docs.goauthentik.io/integrations/services/snipe-it/#authentik-property-mapping) for LDAP-Synchronization to work in Snipe-IT. However, I am currently stuck at this progress and cannot integrate my users into Snipe-IT.

**Comment by BeryJu** [comment]
I dont know how this slipped past the review, but LDAP Property mappings have never been used in conjunction with the LDAP provider and will also for the foreseeable future not supported

**Comment by mpaluch92** [comment]
Thank you for your response @BeryJu . Then there is absolutely no way to add/overwrite returned fields by the LDAP Provider? 😢

**Comment by sln-guy** [comment]
Is there anyone pass to pass given name and an As LDAP attributes for the LDAP providers. 

Some implementations require this. 

For example Unifi UID and directory integration.

**Comment by xpufx** [comment]
> Is there anyone pass to pass given name and an As LDAP attributes for the LDAP providers.
> 
> Some implementations require this.
> 
> For example Unifi UID and directory integration.

If you add custom properties in the user edit page (bottom box that takes json/yaml) they will be served as LDAP properties as well.
