### ISSUE TITLE
How can I enforce rules on usernames?

### ISSUE THREAD

**Issue by KiARC** [goauthentik/authentik#10446]
**Describe your question/**
Mastodon usernames cannot accept certain characters. In OIDC this seems to mean that if the OIDC provider returns a username with disallowed characters, things break. Is there a way to enforce rules via regex or some other method to ensure that usernames match a given schema (for example, "May only contain `[A-Za-z0-9_]`")? My goal is something akin to password validation where it displays error text to the user that says "Usernames may only contain the following characters: ..."

**Relevant info**
As mentioned above, my instance is being used as an SSO provider, and one of the clients is a Mastodon instance using OIDC.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.0
-   Deployment: docker compose (this probably isn't relevant)

**Comment by BeryJu** [comment]
You can either do this with an expression policy using https://docs.goauthentik.io/docs/providers/property-mappings/expression#regex_matchvalue-any-regex-str---bool used in a prompt stage (to disallow certain characters from being used when users sign up) or in a property mapping (if you want to replace characters when federating users)

**Comment by KiARC** [comment]
Got it. Thanks so much!
