### ISSUE TITLE
Tenant not correctly loaded for subdomains

### ISSUE THREAD

**Issue by asifbacchus** [goauthentik/authentik#1044]
**Describe your question/**
Trying to set a custom logo and title using environment variables
AUTHENTIK_AUTHENTIK__BRANDING_TITLE="myDomain"
AUTHENTIK_AUTHENTIK__BRANDING_LOGO="/media/branding/myDomain_logo.svg"

**Relevant infos**
I am bind-mounting the relevant file to the media directory in the server and worker containers:

```ini
volumes:
  - /var/authentik/media:/media
```

on the host, the bind-mounted directory tree with UID/GID:

```bash
[16:06] root@citadel:/etc/authentik# tree -ug /var/authentik/
/var/authentik/
├── [1000     1000    ]  backups
├── [1000     1000    ]  custom-templates
└── [1000     1000    ]  media
    └── [1000     1000    ]  branding
        └── [1000     1000    ]  BacchusGroup_ID.svg

4 directories, 1 file
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10538275/122478297-6612af80-cf86-11eb-8e05-7451f5e7e844.png)

**Logs**
Not sure if the log would be helpful here, but I can provide it upon request.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.6.1-rc5
 - Deployment: docker-compose

**Additional context**
I could bind-mount the desired files over the static assets, but that doesn't seem like the "right" way to do it. Also, is there a way to customize the login page also? I would think that the same logo svg should be used in both places?

Thanks for any help or insights. Great program, definitely donating to help you keep developing if I can get this issue and a few more minor ones ironed out so I can replace Keycloak.

**Comment by BeryJu** [comment]
Hi, starting with 2021.6, branding is no longer configured via environment variables, but rather via Tenants, which you can find in the sidebar under Resources.

**Comment by asifbacchus** [comment]
Ah, cool, found it. However, it is still *not* applying my settings. I've cleared all my caches and upstream caches too. The default logo and title are still present.

For reference, authentik is running on 'auth.bacchus.cloud' and I would like to use my logo so users know they are logging into our group of sites. These are the settings I've used in authentik:
![image](https://user-images.githubusercontent.com/10538275/122625314-c591bd80-d061-11eb-84c3-c045c0a520fb.png)

Also, no matter how many times I try to change things, I cannot get it to list this tenant as default:
![image](https://user-images.githubusercontent.com/10538275/122625245-764b8d00-d061-11eb-9fed-d319195b05c3.png)

Volumes are mapped as in the initial post. I've done a `docker-compose down && docker-compose up -d` a few times to no effect. Is there something else I need to do for it to read and apply my settings?

Thanks.

**Comment by BeryJu** [comment]
Setting the default flag was indeed not working correctly, but thats fixed for the next release.

Can you open the browser developer console and have a look at the console? That will include whichever tenant is active currently.

**Comment by asifbacchus** [comment]
Thanks very much for getting back to me, very much appreciated!

I'm assuming you mean the GET request `https://auth.bacchus.cloud/api/v2beta/core/tenants/current/`, is that right? The `matched_domain` lists *fallback*. Is there something not being passed correctly to authentik and that's why it's using the internal defaults?  Perhaps my proxy configuration would help? I'm using nginx in front of authentik and proxying according to the documentation:

```nginx
map $http_upgrade $connection_upgrade {
    default    upgrade;
    ''             close;
}

server {
    listen 443 http2 ssl;
    listen [::]:443 http2 ssl;

    server_name auth.bacchus.cloud;

    # link certificates and apply ssl configuration (external configuration file)
    include /etc/nginx/snippets/ssl/identitySvc_certs.conf

    # upstream servers
    set $upstream_authentik https://127.0.0.1:9443;

    # location blocks
    location / {
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_pass $upstream_authentik;
    }

    # include externally linked error pages
    include /etc/nginx/snippets/errorpages.conf;
}
```

Did I misunderstand your question and am looking at the entirely wrong place?

**Comment by BeryJu** [comment]
Thanks for the info, that was exactly what I was asking for. While looking through the code, I did notice a logic error, so this is indeed a confirmed bug. For now set the domain in the tenant to the full domain of your authentik instance.

**Comment by asifbacchus** [comment]
Perfect, seems to be working with the full domain set. Are there any guidelines on logo sizes? I am providing an SVG (viewport 1000x1000) but it is currently way too big on the login screen and really tiny in the sidebar. I am assuming this is because the logo is assumed to be wider than tall. Is there a preferred size/ratio?

On a side note: Your response speed and willingness to respond is amazing! Thank you very much!

**Comment by BeryJu** [comment]
> Perfect, seems to be working with the full domain set. Are there any guidelines on logo sizes? I am providing an SVG (viewport 1000x1000) but it is currently way too big on the login screen and really tiny in the sidebar. I am assuming this is because the logo is assumed to be wider than tall. Is there a preferred size/ratio?

In the sidebar it's shown as ~270x40 ish, on the flow executor as 560 x whatever height, so just scale your logo to 560 height with the correct ratio and it should fit perfectly

> On a side note: Your response speed and willingness to respond is amazing! Thank you very much!

Cheers!
