### ISSUE TITLE
Redirect failing on initial login

### ISSUE THREAD

**Issue by ShrinivasKR** [goauthentik/authentik#10486]
**Describe the bug**

Redirect to webapp is failing after authentik auth. If I reload the page on the initial error, I get more error details.
However, if I then paste the webapp URL into the browser and try again, it successfully lets me through.

**To Reproduce**

1. Go to any webapp which uses authentik for auth
2. Login with Authentik
'Something went wrong! Please try again later.
Request ID

fc0a15dfeab64ff4ba68e4d1c0162d99'
5. Reload.
6. See error shown in the browser stack trace file

**Expected behavior**

Auth to successfully redirect to webapp without errors

**Screenshots**
<img width="503" alt="image" src="https://github.com/user-attachments/assets/d07d3490-1d3f-46ed-b895-b81072166582">

<img width="826" alt="image" src="https://github.com/user-attachments/assets/8c2ac449-251b-44cd-bb8b-bcaee4e39d9b">

**Logs**
Output of docker-compose logs or kubectl logs respectively
[authentik-postgres_logs.txt](https://github.com/user-attachments/files/16200638/authentik-postgres_logs.txt)
[Browser error Stacktrace.txt](https://github.com/user-attachments/files/16200640/Browser.error.Stacktrace.txt)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: portainer stack on Synology NAS

**Additional context**
Started happening fairly recently. Previously been using authentik for a while without issues.

**Comment by ShrinivasKR** [comment]
Rolled authentik server and worker back to version [2024.4.3] to test, and this issue does not appear.
This must be due to a newly introduced change.

I would love for this issue to be fixed, or for instructions on what changes need to be made on configs to work successfully with the latest version.

**Comment by hycday** [comment]
using version 2024.6.1 and i have an endless loop after login (was able to log in few times but then not anymore), unsure if related, would be happy to share details if needed (unsure what is needed).
