### ISSUE TITLE
LDAP STARTTLS issues and sync reporting

### ISSUE THREAD

**Issue by asifbacchus** [goauthentik/authentik#1049]
**Describe the bug**
I'm using the LDAP source to read my openLDAP server and retrieve users and groups. Working perfectly *if* I choose to connect via ldaps://. Connecting via STARTTLS and standard ldap:// does not work. My openLDAP reports "TLS required" so it seems that authentik is not doing STARTTLS properly. I can confirm that my openLDAP is working otherwise, so it is not an issue on that end as far as I can tell. I can manually connect with openssl with STARTTLS just fine.

I don't mind connecting via LDAPS directly, it is workable. However, while everything syncs ok, the Sync status always shows "Not synced yet." If manually run a sync, it will report the proper status and show success but, if I logout of authentik and then log back in, it will again show "Not synced yet." which is confusing.

As an aside, what is the sync interval and is there a way to change it? Also, since passwords are overwritten by a sync, can we just prevent users synced via LDAP from changing their passwords in the first place?

**Logs**
Let me know what kind of test you want run and I'll provide the logs.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.6.1
 - Deployment: docker-compose

Thanks!

**Comment by BeryJu** [comment]
> My openLDAP reports "TLS required"

This is currently not checked explicitly (and I'm not quite sure how the ldap3 library handles this), but as long as you check the StartTLS checkbox in the webinterface, it should do an explicit starttls after connecting and before binding.

> I don't mind connecting via LDAPS directly, it is workable. However, while everything syncs ok, the Sync status always shows "Not synced yet." If manually run a sync, it will report the proper status and show success but, if I logout of authentik and then log back in, it will again show "Not synced yet." which is confusing.

This is interesting, the sync status is "saved" as a System task, which are also saved in Redis, I would've expected some inconsistency with the state in the UI but it should not be affected by logging out and back in again.

> As an aside, what is the sync interval and is there a way to change it? 

The Sync currently runs once every 60 minutes, and is currently not changeable. You can however re-trigger it at any time by going to Monitor -> System Tasks and hitting retry on the sync task.

> Also, since passwords are overwritten by a sync, can we just prevent users synced via LDAP from changing their passwords in the first place?

Passwords are *not* overwritten by a sync. Because the passwords in LDAP aren't stored in plaintext (as they should), authentik can't read them. This means, that every LDAP User, upon their first login in authentik, will attempt to be bound to the LDAP Server. If that is successful, the password will be hashed and saved in authentik's database. When password writeback is on, this will also be written back to the LDAP Server. When the regular scheduled LDAP Sync happens, authentik checks the `pwdLastSet` attribute, to check if the LDAP password has been set since the last time authentik synced, and authentik will delete the locally stored password.

**Comment by asifbacchus** [comment]
> 
> > My openLDAP reports "TLS required"
> 
> This is currently not checked explicitly (and I'm not quite sure how the ldap3 library handles this), but as long as you check the StartTLS checkbox in the webinterface, it should do an explicit starttls after connecting and before binding.

This does not seem to be the case. However, I do not think it is unique to authentik. I know I and many others have this issue with Keycloak also (which is Java as opposed to python). Like I said, not really a big deal and very well could be an upstream python issue I know you'd have no control over. Might be worth mentioning in the docs if others are having this issue.

> > ...while everything syncs ok, the Sync status always shows "Not synced yet." If manually run a sync, it will report the proper status and show success but, if I logout of authentik and then log back in, it will again show "Not synced yet." which is confusing.
> 
> This is interesting, the sync status is "saved" as a System task, which are also saved in Redis, I would've expected some inconsistency with the state in the UI but it should not be affected by logging out and back in again.
> 

No idea on this one, perhaps I'll keep an eye on it and try to discern some pattern.

> > As an aside, what is the sync interval and is there a way to change it?
> 
> The Sync currently runs once every 60 minutes, and is currently not changeable. You can however re-trigger it at any time by going to Monitor -> System Tasks and hitting retry on the sync task.
> 

Quite acceptable. Being able to control the sync period would be nice feature, but definitely not a deal-breaker for me. Thanks for the info!

> > Also, since passwords are overwritten by a sync, can we just prevent users synced via LDAP from changing their passwords in the first place?
> 
> Passwords are _not_ overwritten by a sync. Because the passwords in LDAP aren't stored in plaintext (as they should), authentik can't read them. This means, that every LDAP User, upon their first login in authentik, will attempt to be bound to the LDAP Server. If that is successful, the password will be hashed and saved in authentik's database. When password writeback is on, this will also be written back to the LDAP Server. When the regular scheduled LDAP Sync happens, authentik checks the `pwdLastSet` attribute, to check if the LDAP password has been set since the last time authentik synced, and authentik will delete the locally stored password.

Great explanation, thanks! Makes this much clearer. There is, however, a small issue and this is why I thought things were being overwritten: If I log in as a user synced from LDAP that works fine. Then, I change my password and logout. LDAP writeback is *not* enabled. Immediately following this (i.e. no time to sync or anything) I can then use *both* the LDAP password or the newly changed password which I assume is hashed in authentik's database. When I triggered a manual sync, it seems only the LDAP password is accepted again.

I know this is an edge case, but may I suggest it might just be easier to always check LDAP users against LDAP and if and only if communication is not possible then read the local hash?

Thanks for taking the time and for the very detailed responses!

**Comment by BeryJu** [comment]
About the StartTLS, I have no idea what causes that either (and I don't currently have an OpenLDAP Setup to test against/to write docs for, since I don't really have a usecase for it, and every OpenLDAP instance can be completely unique from the next)

The other issue with both passwords working is I think a simple order issue. Because the Password stage has both backends set (default since 2021.6), it'll try both the Database and LDAP. However, if only LDAP succeeds, the other password you set in authentik shouldn't work anymore.

**Comment by asifbacchus** [comment]
If you ever need access to an LDAP instance for testing, just let me know and I'm happy to provide a test one for you! However, your point is well taken that there is no 'standard' setup.

Regarding the ordering issue: I think this could be significant. Consider the following:

LDAP password: 'pass1' set on January 1
authentik password: 'pass2' set on March 1

It is possible now for both to work since using 'pass2' would always fail the LDAP check but would always pass the authentik check. And, since the `pwdLastSet` property is *older*, authentik would not update the password on sync. Is this right? Am I overlooking something here? If this is the case, I would suggest that there be an *option* to simply disallow updating the authentik password if LDAP is being used. That way, LDAP is the one source and if it's down then authentication is simply not possible. I think that's reasonable, but that is just my opinion. I do not know what others would think of that.

**Comment by BeryJu** [comment]
> If you ever need access to an LDAP instance for testing, just let me know and I'm happy to provide a test one for you! However, your point is well taken that there is no 'standard' setup.
> 
If you can package your setup with some generic data into a docker container, I'll add some integration tests for it.

> Regarding the ordering issue: I think this could be significant. Consider the following:
> 
> LDAP password: 'pass1' set on January 1
> authentik password: 'pass2' set on March 1
> 
> It is possible now for both to work since using 'pass2' would always fail the LDAP check but would always pass the authentik check. And, since the `pwdLastSet` property is _older_, authentik would not update the password on sync. Is this right? Am I overlooking something here? If this is the case, I would suggest that there be an _option_ to simply disallow updating the authentik password if LDAP is being used. That way, LDAP is the one source and if it's down then authentication is simply not possible. I think that's reasonable, but that is just my opinion. I do not know what others would think of that.

Yes, that is exactly how authentik would behave with default settings. However, you can change this, simply by editing the password stage and only selecting the LDAP backend, which would accomplish exactly what you suggest.

**Comment by asifbacchus** [comment]
I didn't realize I could configure that... yes, that solves my problem perfectly, thanks!

Regarding the LDAP container: I actually use a semi-automated LDAP setup that is configurable via environment variables and auto-detects certificates, etc. I can do a quick write-up and supply some dummy data in an LDIF that can be imported. Would that help? You can then test integration with/without TLS or with/without anonymous browsing, etc via quick environment variables and restarting the container. I'll shoot you a PM with details maybe in a few days when I have some extra time so we don't clutter clutter this issue thread.

I'll close this also, I think you've resolved the issue quite nicely :-)

**Comment by BeryJu** [comment]
> Regarding the LDAP container: I actually use a semi-automated LDAP setup that is configurable via environment variables and auto-detects certificates, etc. I can do a quick write-up and supply some dummy data in an LDIF that can be imported. Would that help? You can then test integration with/without TLS or with/without anonymous browsing, etc via quick environment variables and restarting the container. I'll shoot you a PM with details maybe in a few days when I have some extra time so we don't clutter clutter this issue thread.

Yeah that would be quite lovely, best to just create another issue with the details as enhancement, then I can add the Integration tests. Depending on how much logic goes on in the containers, I can also create a repo under the goauthentik org to store that in, if you want to to of course.

**Comment by lsowen** [comment]
Sorry to resurrect this old issue, but I was having a similar issue.  With `StartTLS` checked, I was getting errors from my OpenLDAP server.  Disabling `starttls` and the sync started working.  I think the issue with the following code:

https://github.com/goauthentik/authentik/blob/cdf88e44770d5359f5bce945d59cfb852d83fa8b/authentik/sources/ldap/models.py#L138-L142

This binds _before_ starting the TLS connection.  I think it should start the TLS connection and _then_ bind?
