### ISSUE TITLE
UI is messed up when forcing light mode with system set to dark mode

### ISSUE THREAD

**Issue by Djeex** [goauthentik/authentik#10502]
**Describe the bug**
Since I upgraded authentik from 2024.2.3 to 2024.6.1 :
Given my OS theme is set on Dark
When I force light theme through user/group/brand settings
Then the UI is messed up with some mixed and light theme and dark theme css.

**To Reproduce**

1. Set your OS to dark mode
2. In authentik, force light theme, editing user or group or brand attributs with :

```yaml
settings:
  theme:
    base: light
```
3. Proceed, then refresh with CTRL+F5 (clear cache)

=> The UI is messed up with some mixed dark and light CSS.

**Expected behavior**
Only light mode css should be applied.

**Screenshots**

![Capture d'écran 2024-07-15 173307](https://github.com/user-attachments/assets/b50707ba-a85c-4b9c-bcfb-bce6ba9ac441)
![Capture d'écran 2024-07-15 172956](https://github.com/user-attachments/assets/88dee536-8e32-4a0d-8aa1-dcd2bceb818b)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: docker compose

**Additional context**
None custom css is set.

**Comment by mahula** [comment]
Related to #7016: Where exactly should `settings.theme.base:` beconfigured and is this the rigth parameter to globally set the theme's color mode?

**Comment by Djeex** [comment]
Seems OK since 2024.6.3 release
