### ISSUE TITLE
Authentik occasionally times out

### ISSUE THREAD

**Issue by asturriff** [goauthentik/authentik#10526]
**Describe your question/**
This might be related to issue #3153: I am noticing that applications protected by Authentik via forward auth tend to time out and refuse to load every once in a while. During those periods, Authentik itself is inaccessible. If an Authentik session is open, any action taking during those blips results in a spinning waiting circle. I have been unable to find anything unusual in the logs except for timeouts.

**Relevant info**
Observed on Navidrome (both web player and using the SubSonic API to play via Strawberry), Traefik (dashboard).

**Screenshots**
N/A

**Logs**
Not sure what would help troubleshooting this - let me know what logs to attach and I'll get them.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1 behind Traefik v3
-   Deployment: docker-compose

**Comment by asturriff** [comment]
Noise, my problem was a misconfiguration I finally found. Not Authentik-related despite what it looked like.

**Comment by forgo** [comment]
> Noise, my problem was a misconfiguration I finally found. Not Authentik-related despite what it looked like.

@asturriff would you be willing to recall what your misconfiguration issue was? I'm in a similar situation and seeking out things I haven't thought of.
