### ISSUE TITLE
Discord docs expression policy doubt

### ISSUE THREAD

**Issue by bot37** [goauthentik/authentik#10555]
[goauthentik/authentik/blob/main/website/docs/sources/discord/index.md](https://github.com/goauthentik/authentik/blob/main/website/docs/sources/discord/index.md)

Hello! This line in the documentation seems counter-intuitive. Why does it return `True` instead of `False`? Thanks!

`if context['source'].provider_type != "discord":
    return True`

**Comment by Keyinator** [comment]
The stages these policies are applied to are usually used for multiple sources.

Returning false would result in other sources not working for any stage having this expression policy bound.
Returning true will "skip" this policy for non-discord related sources.
