### ISSUE TITLE
Can't create new application

### ISSUE THREAD

**Issue by DaveTSG** [goauthentik/authentik#10577]
I initially posted this [as a comment on another issue I created](https://github.com/goauthentik/authentik/discussions/10576), but I realise it might be a completely different issue, so I am posting it here as a new issue.

Somewhat related to the OP issue, I've tried to go ahead with setting up Netbird as well. I used Authentik's application creation wizard to create an OAuth2 application and provider. However, when clicking the submit button to actually create it, I received a fairly vague error message:

`Authentik was unable to save this application:
There was an error in the application.

Review the application.`

Clicking "Review the application" takes you back to step 1 of the wizard, with the options I filled in the first time around still present (e.g. the name and slug are still there).

It's not obvious what the problem is at this stage.

I found [this troubleshooting guide](https://docs.goauthentik.io/docs/troubleshooting/forward_auth/general). 

I did both adding `AUTHENTIK_LOG_LEVEL=trace` to my .env file and setting `log_level: trace` in the proxy outpost (just in case that revealed issues with both).

Nothing obvious is to be found in the log files for the four Authentik services. (Searching each log file for "ERR", for instance, finds nothing)

That troubleshooting guide also suggests that I ensure /outpost.goauthentik.io is accessible.

I ran curl -v https://authentik.domain.com/outpost.goauthentik.io/ping

"A correct setup should contain output looking like this:"

```
[...]
< HTTP/2 204
[...]
```

...in my case, I saw `< HTTP/2 404`.

...and if I load https://authentik.domain.com/outpost.goauthentik.io/ping in a web browser, I get an [Authentik-branded "not found" page](https://www.dropbox.com/scl/fi/qb5rt2qdtdn13n8iy1s08/auth-notfound.png?rlkey=ci0ajfjei7g5vv9cz8b8339q0&dl=0).

I'm not sure if that not working correctly has anything to do with either the issue in the OP or this new issue I'm detailing in this comment, but I thought I ought to include it here in case it helps anyone diagnose the issues...

Any ideas, please?

_Originally posted by @DaveTSG in https://github.com/goauthentik/authentik/discussions/10576#discussioncomment-10121403_

**Comment by DaveTSG** [comment]
...this issue magically solved itself, which is worrying.

**Comment by Schachte** [comment]
Running into the same problem.

**Comment by 0xff8** [comment]
Same problem when creating `ldap` provider for an application.
