### ISSUE TITLE
Safari Fonts 404

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#1057]
**Describe the bug**
While trying to debug weird behaviour in Authentik/Organizr in Safari on iOS, I tried to access authentik using Safari (14.1.1) in a macOS VM. There, I noticed that Safari attempts to load a bunch of fonts which do not appear to exist.

**To Reproduce**
1. Open Authentik in Safari
2. Open Console

**Expected behavior**

**Screenshots**
![fonts-404](https://user-images.githubusercontent.com/17555261/122739694-8347c680-d283-11eb-9478-32ec3919ccdd.png)

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.6.1
 - Deployment: docker

**Additional context**
Despite the errors, the interface looks normal and seems to function fine.
There are some fonts which are loaded successfully, but they have a different path:
`/static/dist/assets/fonts/RedHatText/RedHatText-Regular.woff`
`/static/dist/assets/fonts/RedHatDisplay/RedHatDisplay-Medium.woff`
`/static/dist/assets/fonts/RedHatText/RedHatText-Medium.woff`
When using Firefox, these fonts are also loaded.

**Comment by BeryJu** [comment]
I've noticed this behaviour in the past too, seems like

a) Chrome and firefox optimise which fonts are actually needed, and only load those, while safari loads all fonts, and
b) for some reason the paths are interpreted incorrectly, as those fonts should be loaded from /static/dist/ too

**Comment by jr0dd** [comment]
Has anyone found a workaround for this?
