### ISSUE TITLE
Recovery link points to wrong host when generated via XHR API call

### ISSUE THREAD

**Issue by duhast** [goauthentik/authentik#10589]
**Describe the bug**
When `POST /core/users/{id}/recovery_email/` API call is made from a SPA with XHR, the link included in the email has hostname of SPA and not the host where Authentik is running.

**To Reproduce**

Given that Authentik is running on `sso.example.com` domain.

1. Create a simple Single Page JS App which calls the `recovery_email` API
2. Run SPA locally on port 4200
3. Trigger recovery email from SPA
4. Open the delivered email
5. Note the wrong hostname in the link

**Expected behavior**
The link should point to the hostname running Authentik

**Screenshots**

![image](https://github.com/user-attachments/assets/062562d8-53c6-4705-b76c-0f2ec761e85a)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4
-   Deployment: AWS ECS

**Additional context**

The problem seems to be caused by `request.build_absolute_uri` call in `_create_recovery_link` function [here](https://github.com/goauthentik/authentik/blob/version-2024.6/authentik/core/api/users.py#L459). 

`build_absolute_uri` uses hostname from HTTP request headers which are set to the SPA hostname by the browser. However in this case the `build_absolute_uri` call should be modified in the way it uses Authentik hostname from it's settings.

The current workaround is to use reverse-proxy for API calls and configure it to rewrite `Host` and `X-Forwarded-Host` header.

**Comment by duhast** [comment]
Hello @BeryJu !
Any idea on whether this could be fixed anytime soon?

**Comment by BeryJu** [comment]
This is currently intended behaviour as authentik does not know it's own URL (at least not on a static level, it's not stored in the database). Hence we use `build_absolute_uri`. We could most likely fallback to Brand at some place (also it's possible to create a custom email template that uses your domain statically)
