### ISSUE TITLE
Using expression policies to simulate a backend login

### ISSUE THREAD

**Issue by RikuXan** [goauthentik/authentik#10594]
**Describe your question**
I am using a forward auth (single application) provider to add an authentication process to my router's UI. While the authentication works, the fact that the router UI does not support HTTP basic auth or anything similiar requires me to authenticate twice, once via SSO and then again via the local router login (which cannot be disabled).

I have found that using something like an expression policy would allow me to write custom Python code and therefore be able to *simulate* the router UI login (simple HTTP POST request that returns a session cookie). However, I am unclear on how I would

1. Access the router UI credentials that are saved as attributes on a designated group
2. Return the session cookie so that it can be picked up by the NGINX executing the authentication flow

Are these things possible via expression policies or should I look at something different for my problem?

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: helm on k3s
-   Ingress-NGINX initiating the forward auth

**Comment by BeryJu** [comment]
You could do that from within a scope mapping bound to the provider and then return data like this https://docs.goauthentik.io/docs/providers/proxy/custom_headers

**Comment by RikuXan** [comment]
I have also experimented a bit with custom headers and created a setup where a hardcoded session token value associated with a group works to remove the second login from the authentication flow. What I'm still missing is when actually simulating the login, how I would transfer the session token to e.g. a property mapping.

Should I write the whole login inside the property mapper, or is there a way to transfer data from an expression policy into the property mapper (e.g. via some shared object with enough lifetime)?

**Comment by RikuXan** [comment]
This might be useful not only for my specific modem UI use case, but for every forward auth application that requires an easily simulated login and uses a session token afterwards. Following are the customizations I made:

Ingress Annotations (NGINX, Embedded Outpost):
```
nginx.ingress.kubernetes.io/auth-url: >-
  http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
nginx.ingress.kubernetes.io/auth-signin: >-
  https://modem.company/outpost.goauthentik.io/start?rd=$escaped_request_uri
nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-modem-session
nginx.ingress.kubernetes.io/auth-snippet: |
  proxy_set_header X-Forwarded-Host $http_host;
nginx.ingress.kubernetes.io/configuration-snippet: |
  auth_request_set $modem_session $upstream_http_x_modem_session;
  proxy_set_header Cookie "SESSION_ID_VIGOR=$modem_session; Path=/";
```

Custom Property Mapping (Scope name: `ak_proxy`):
```
from base64 import b64encode

modem_username = user.group_attributes().get('MODEM_USERNAME', '')
modem_password = user.group_attributes().get('MODEM_PASSWORD', '')

login_request = requests.post('http://modem.url/cgi-bin/wlogin.cgi', data={
  'aa': b64encode(modem_username.encode()),
  'ab': b64encode(modem_password.encode()),
  'sFormAuthStr': '000000000000000'
  }, allow_redirects=False)

modem_session_token = ''
if 'SESSION_ID_VIGOR' in login_request.cookies:
  modem_session_token = login_request.cookies['SESSION_ID_VIGOR']

return {
  "ak_proxy": {
    "user_attributes": {
      "additionalHeaders": {
        "X-Modem-Session": modem_session_token
      }
    }
  }
}
```

My user is in a group that supplies the credentials in `MODEM_USERNAME` and `MODEM_PASSWORD`. The Application and Provider are set up just as in the documentation with the only exception of the provider having the property mapping scope added under *Advanced protocol settings* > *Additional scopes*.
