### ISSUE TITLE
User can escalate his priviledges 

### ISSUE THREAD

**Issue by NikJen26** [goauthentik/authentik#10600]
**Describe the bug**
A User with the following permissions is able to assign itself to the admin group an gain admin privileges. 
![image](https://github.com/user-attachments/assets/fb3a1a9f-b4b4-47fd-97d6-4c99b5ba9c56)

**To Reproduce**

Create a normal user without any group assignments.
Assign the permissions above to the new user
Login as said user
Add yourself to the admin group

**Expected behavior**
A user that is not in the admin group already should not be able to assign people to this group. 

**Screenshots**
![image](https://github.com/user-attachments/assets/7a29d2a6-a872-48a4-b751-8facf886b822)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
That is the intended functionality of giving the global "add user to group" permission. This can be restricted by only giving that permission on specific groups.

We're planning to add some UI elements in the future that point out permissions that should be assigned with caution

**Comment by NikJen26** [comment]
Where can I restrict the available groups?
