### ISSUE TITLE
Why are notifcations pure JSON?

### ISSUE THREAD

**Issue by pittbull** [goauthentik/authentik#10654]
**Describe your question/**
Why are local and webhook notifications json objects, as this makes the content hard to decode?

**Relevant info**
Running Authentik 2024.6.1 on Unraid and everything works as expected.

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.1
-   Deployment: docker on Unraid (Docker version 24.0.9, build 2936816)

**Additional context**
I just recently found Authentk and thanks to Cooptonian on Youtube I now have it up and running, and fully functional for my small setup. What I am noticing is that due to the json format of the notifications it makes it hard to read them. I am also experimenting with Ntfy, but it seems the json object is just passed on to that service as well - making it equally hard to read. Is there some thing I am missing as to how this is supposed to work perhaps?

**Comment by LeonMusCoden** [comment]
What's the issue with JSON? I'm also running Ntfy.sh, and adapted the code authentik uses for Slack / Discord:

```py
fields = [
  {
    "title": "Severity",
    "value": notification.severity
  }
]
if notification.event:
  if notification.event.user:
    fields.append({
      "title": "User",
      "value": str(notification.event.user.get("username"))
    })
  for key, value in notification.event.context.items():
    if not isinstance(value, str):
      continue
    fields.append({"title": key[:256], "value": value[:1024]})
    
formatted_string = "\n".join(f"**{field['title']}**: {field['value']}" for field in fields) + "\n"

body = {
  "topic": "authentik",
  "title": notification.body.split(":")[0],
  "markdown": True,
  "tags": ["lock", "warning"],
  "message": formatted_string,
  "actions": [{"action": "view", "label": "Admin panel", "url": "https://auth.domain.com"}],
  "icon": "https://auth.domain.com/media/homelab-logo-small.png"
}

return body
```

I use this webhook mapping in a generic webhook notification transport with the url set to `https://ntfy.domain.com?auth=[code]`.

**Comment by pittbull** [comment]
Thank you so much @LeonMusCoden - for pointing me in the right direction. As is most often the case I had misread the documentation and failed to understand that I had to create the full json-object in the mapping.

Your code worked perfectly and I am now getting proper notifications 💯

**Comment by pittbull** [comment]
Quick question on your code: How could I add authentication to this (either basic (user+pass), or bearer token)?

**Comment by LeonMusCoden** [comment]
I’m setting a token in the url (see above)

**Comment by clemcer** [comment]
but don't you have to specify the topic that ntfy should use somewhere?
I can not get it to work unfortunately.
