### ISSUE TITLE
Stable Proxy Docker Image Mixup

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#1066]
**Describe the bug**
It looks like the "stable" authentik-proxy image actually contains the main authentik-server instead of the proxy outpost.
[DockerHub](https://hub.docker.com/layers/beryju/authentik-proxy/stable/images/sha256-2a38b43dbf89448f66238b9060a2fd42ca9bef1227dc6ec821eaed03c132a683?context=explore)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.6.1
 - Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/blob/version/2021.6.1/.github/workflows/release.yml#L94 Yeah checks out, I've since changed the CI to not-double build the images, so with 2021.6.2 this should be fixed (2021.6.2 should be out later today)

**Comment by BeryJu** [comment]
I just fixed it manually for the 2021.6.1 images, so :stable on both dockerhub and ghcr is correct now
