### ISSUE TITLE
Login Window Flow Stuck in Light Mode

### ISSUE THREAD

**Issue by kmendell** [goauthentik/authentik#10709]
**Describe the bug**
After the latest 2024.6.2 update the login page box is stuck in light mode even if dark mode is forced. 

**To Reproduce**

Upgrade to latest version 
Open in private window and go to authentik login page. 

**Expected behavior**
Login Windows Respects theme preference. 

**Screenshots**
<img width="610" alt="image" src="https://github.com/user-attachments/assets/6c963cff-52da-4a90-b8f0-3271007a997d">

**Logs**
Output of docker-compose logs or kubectl logs respectively

Logs dont show anything that i can see but i can upload them if needed. 

-   authentik version: 2024.6.2
-   Deployment: helm

**Comment by StizLor** [comment]
i can confirm this issue.

Environment:
- authentik: 2024.6.2
- Deployment: Docker
  - Docker version 27.1.1, build 6312585
  - Docker Compose version v2.29.0

**Comment by ChrisSlashNull** [comment]
Same issue for me after the update yesterday.

**Comment by pgodzwa** [comment]
+1, same issue after update

**Comment by adyfoot** [comment]
Came here to raise this exact same bug.  Happened after the recent update.

**Comment by caloc-nz** [comment]
Same issue tonight after updating to 2024.6.2

**Comment by geoffreyjt** [comment]
hello, same for me

**Comment by BeryJu** [comment]
this is fixed by #10721, you can switch to the image `ghcr.io/goauthentik/dev-server:gh-version-2024.6` temporarily, we'll release a bugfix release shortly
