### ISSUE TITLE
Question regarding Policies and regex_match

### ISSUE THREAD

**Issue by scheibling** [goauthentik/authentik#1073]
**Describe your question/**
So, I have a question regarding regex_match in policies. I'm trying to create a regex match for a certain domain for a registration flow, and have the following code for this: 

```python
if regex_match(request.user.email, '@sometenant.*'):
  return True
else:
  ak_message("You need an email on one of the sometenant-domains to register")
  return False
```

When I run the above code, I get an inverted match (e.g. email@sometenant.com returns false + message, email@otherdomain returns true). Is the matching inverted for the regex_match, returning false when it finds a match and true when not? Or is the small-ish logical part of my brain shorting out completely and I'm missing something?

The same happens when i just return regex_match without the message.

Edit: disregard that request.user.email isn't the correct one for actually verifying an email in the registration flow, I'm only using the test function for now

**Relevant infos**
Version 2021.6.1

**Comment by BeryJu** [comment]
Hi, I just checked checked the expression and indeed, the result for `regex_match` is currently inverted. For now you can just negate it, but it'll be fixed in 2021.6.3

**Comment by scheibling** [comment]
Ah, so I'm not going insane, that's comforting to hear 😄 

Thanks a lot for all of this, you've made a fantastic piece of software!

**Comment by BeryJu** [comment]
Cheers, I'm gonna close the issue when I have a (tested) fix committed.
