### ISSUE TITLE
Quesion : Can roles only be used with a single group ?

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [goauthentik/authentik#10752]
**Describe your question**
Can roles only be assigned to a single group?

**Relevant info**
Authentik version: 2024.6.2

**Additional context**
I have created a role with specific permissions to manage membership. I would like to assign this role to several groups. While it works as expected when assigned to one group, it fails when I attempt to assign it to another group, returning the error **Roles can only be used with a single group.**

Is this behavior by design?

My use case involves reusing a role across multiple groups to define group membership managers. It would be very useful to be able to assign the same role to different groups.

**Comment by BeryJu** [comment]
For now that is indeed a limitation, which definitely reduces the functionality of roles somewhat. This is due to some database design limitations and will hopefully be improved in the future.

**Comment by marcportabellaclotet-mt** [comment]
Thanks for the fast response.
Closing the ticket.

**Comment by marcportabellaclotet-mt** [comment]
@BeryJu 

I would like to kindly inquire whether there are plans in the future roadmap to support attaching a single Role to multiple Groups. In many organizations, defining membership rules can become simpler and less error-prone if one Role can be shared across several Groups, rather than having to duplicate similar Roles for each Group.
This enhancement could: 
- Reduce configuration duplication when the same permission set applies to multiple teams or contexts.
- Simplify maintenance: updating one Role would automatically affect all associated Groups.
- Improve clarity for membership managers by centralizing related permissions.

Thanks

**Comment by marcportabellaclotet-mt** [comment]
@BeryJu is this in authentik roadmap?
It would be great to have this feature, to make rbac easier.
Thanks

**Comment by FisherMS** [comment]
Has this feature been implemented?

**Comment by BeryJu** [comment]
With 2025.12 (out soon :tm:) you will be able to re-use roles with multiple groups
