### ISSUE TITLE
Return a list of allowed scopes

### ISSUE THREAD

**Issue by evo01** [goauthentik/authentik#10769]
**Describe your question/**
Hi!  I want to be able to return a list of the allowed (not just requested scopes) in the access token.   

I have setup the application so that only certain scopes are selected for client credential flow, but when I get the access token, I am looking for the list of allowed scopes, and not just the list of scopes that were requested.  How can I modify the property mappings to return the list of allowed scopes (or filter out the list of scopes from the token request that are not allowed.  

I tried using `token.scope` but it just returns the scopes I requested.

I tried looking through the documentation and issues here and I have not been able to find a good example.  Any help would be appreciated.

**Relevant info**
Current version

**Comment by BeryJu** [comment]
You can get access to the provider in the property mapping context via `request.context['provider']`, from which you can list all the scope names by using `ScopeMapping.objects.filter(provider=request.context['provider']).values_list("scope_name", flat=True)` (and add `from authentik.providers.oauth2.models import ScopeMapping` at the top.
