### ISSUE TITLE
Login windows background color white-out

### ISSUE THREAD

**Issue by jamesngob** [goauthentik/authentik#10778]
**Describe the bug**
After update to 2024.6.2, the back ground color of the login windows completely white-out, cover up the white text in it (The welcome title)

**To Reproduce**
update to version 2024.6.2

**Expected behavior**
Should remain the color of choice, e.g. black?

**Screenshots**
![Capture](https://github.com/user-attachments/assets/820297ee-fbd2-4d55-8928-f630f73ab225)

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2024.6.2]
-   Deployment: [docker-compose]

**Comment by sahara101** [comment]
same issue here
