### ISSUE TITLE
Cannot figure out 'banning'

### ISSUE THREAD

**Issue by asifbacchus** [goauthentik/authentik#1079]
**Describe your question/**
I would like to ban users/ip addresses after a certain amount of attempts. This is mainly to stop random bots/scripts from trying to guess login information and loading my server. I have read the other posts but cannot figure out what I'm doing wrong.

**Relevant infos & screenshots**
Let's work with just banning based on multiple attempts with the same username. I'll ignore IP banning for now.

**Create policy**
1) Create a reputation policy to check usernames against a threshold.
![image](https://user-images.githubusercontent.com/10538275/123522505-de5e2c80-d67a-11eb-9228-4de486c7a898.png)

**Create stages**
1) Create a unified username and password identification stage. It seems like the default setup where username and password are separate allows for unlimited username guesses with no way to prevent it. So let's unify them in an identification stage which I have called *bg-authentication-identification*
![image](https://user-images.githubusercontent.com/10538275/123522354-f84b3f80-d679-11eb-94a9-37aedcc6eb32.png)

2) Create a deny stage to cancel the flow if the username is banned. I called it *Cancel current flow*.

**Create flow**
1) Create an authentication flow called *bg-default-authentication-flow*:
![image](https://user-images.githubusercontent.com/10538275/123522422-5d9f3080-d67a-11eb-9c9c-7975d293a068.png)
2) Set this as the default flow for the tenant so it will be used.

**Stage bindings**
**Stages**
![image](https://user-images.githubusercontent.com/10538275/123522525-fc2b9180-d67a-11eb-895b-1f53b3175ce5.png)

Order 10: *bg-authentication-identification*
![image](https://user-images.githubusercontent.com/10538275/123522559-29783f80-d67b-11eb-9411-551a693c52c2.png)

Order 15: *Cancel current flow*
![image](https://user-images.githubusercontent.com/10538275/123522578-43198700-d67b-11eb-9d35-8914637c79e7.png)
Policy binding:
![image](https://user-images.githubusercontent.com/10538275/123522587-5cbace80-d67b-11eb-9c91-0c1f6d117421.png)

Order 100: *default-authentication-login*
![image](https://user-images.githubusercontent.com/10538275/123522601-73612580-d67b-11eb-8e49-1c9f4c4b74d8.png)

**Policy/Group/User Bindings**
NONE

**Flow Overview**
![image](https://user-images.githubusercontent.com/10538275/123522632-a6a3b480-d67b-11eb-8003-070214c588ed.png)

**Logs**
I can't see anything in the logs of note, even in debug. Authentik documents that it is applying a *-1* to reputation and that is also reflected correctly when directly querying redis. I can provide whatever log you would like, just let me know what tests to run.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.6.2
 - Deployment: docker-compose

**Additional context**
The flow correctly refuses to authenticate incorrect usernames and/or passwords, however, it will continue running authentication attempts infinitely. Even when redis shows the username is at -25, the flow does not hit the cancellation rule. I have tried inverting the match in case I'm not understanding the reputation policy threshold correctly but that had no effect either.

Obviously I'm not understanding something major here, but I cannot figure out what is wrong. Any help appreciated. Sorry for the very long post!

**Comment by BeryJu** [comment]
Hi, thanks for the very detailed explanation of what you want and what you're doing, much appreciated!

A couple of things:

- To use the deny stage in this way, it has to be bound *before* the identification stage, as the user never gets past the identification stage, thus never reaching the next stage.
- You can use a separated identification and password stage, when using a setup as above.
- The reputation policy *passes* when the current score is *above* the threshold, and doesn't pass when its equal or below. (I'll add a notice about that to the Reputation Policy form). This means that in your setup, you actually want to check the `Negate` checkbox in your Policy binding.

**Comment by asifbacchus** [comment]
Thanks for the quick reply! Good to know about the ordering issue, I have resolved that. Also, I had a feeling about that *negate*, nice to confirm.

After making the suggested changes, I just get an instant *Request has been denied.* when loading the login page. Doesn't matter what I do.
![image](https://user-images.githubusercontent.com/10538275/123527217-cb5b5480-d69a-11eb-9728-a4ee1a735fca.png)

```
server_1       | {"event": "/api/v2beta/core/tenants/current/", "host": "50.66.148.168", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "request_id": "89c6e3ce0b94411fbfd9f64fa2d024f2", "runtime": 315, "scheme": "https", "size": 0.064, "status": 200, "timestamp": "2021-06-26T22:16:19.516246"}
server_1       | {"event": "f(exec): No active Plan found, initiating planner", "flow_slug": "bg-default-authentication-flow", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.flows.views", "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "timestamp": "2021-06-26T22:16:19.544754"}
server_1       | {"event": "f(plan): starting planning process", "flow": "<Flow: Flow bg-default-authentication-flow (bg-default-authentication-flow)>", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.flows.planner", "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "timestamp": "2021-06-26T22:16:19.546424"}
server_1       | {"event": "/api/v2beta/root/config/", "host": "50.66.148.168", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "request_id": "c4685e17762148dba4ec57607dcbe7ce", "runtime": 154, "scheme": "https", "size": 0.113, "status": 200, "timestamp": "2021-06-26T22:16:19.565397"}
server_1       | {"event": "f(plan): taking plan from cache", "flow": "<Flow: Flow bg-default-authentication-flow (bg-default-authentication-flow)>", "host": "auth.bacchus.cloud", "key": "flow_b6cd80c1-facd-4a87-a835-dad1647dd6a4#None", "level": "debug", "logger": "authentik.flows.planner", "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "timestamp": "2021-06-26T22:16:19.586191"}
server_1       | {"event":"/static/dist/assets/icons/icon.png?v=2021.6.2","level":"info","method":"GET","remote":"50.66.148.168","timestamp":"2021-06-26T22:16:19Z","took":497682}
server_1       | {"event": "f(plan_inst): stage has marker", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.flows.planner", "marker": "ReevaluateMarker(binding=<FlowStageBinding: Flow-stage binding #0 to Flow bg-default-authentication-flow (bg-default-authentication-flow)>, user=<django.contrib.auth.models.AnonymousUser object at 0x7fb6b9bf6850>)", "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "stage": "<DenyStage: Stage Cancel current flow>", "timestamp": "2021-06-26T22:16:19.588740"}
server_1       | {"binding": "<PolicyBinding: Binding from Flow-stage binding #0 to Flow bg-default-authentication-flow (bg-default-authentication-flow) #1 to Policy prevent bruteforce username>", "event": "P_ENG: Evaluating policy", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.policies.engine", "pid": 20, "request": "<PolicyRequest user=AnonymousUser obj=Flow-stage binding #0 to Flow bg-default-authentication-flow (bg-default-authentication-flow) http_request=<ASGIRequest: GET '/api/v2beta/flows/executor/bg-default-authentication-flow/?query=next%3D%252F'>>", "request_id": "fb8444a77b8540d7bde9448217cb68ba", "timestamp": "2021-06-26T22:16:19.648632"}
server_1       | {"binding": "<PolicyBinding: Binding from Flow-stage binding #0 to Flow bg-default-authentication-flow (bg-default-authentication-flow) #1 to Policy prevent bruteforce username>", "event": "P_ENG: Starting Process", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.policies.engine", "pid": 20, "request": "<PolicyRequest user=AnonymousUser obj=Flow-stage binding #0 to Flow bg-default-authentication-flow (bg-default-authentication-flow) http_request=<ASGIRequest: GET '/api/v2beta/flows/executor/bg-default-authentication-flow/?query=next%3D%252F'>>", "request_id": "fb8444a77b8540d7bde9448217cb68ba", "timestamp": "2021-06-26T22:16:19.683362"}
server_1       | {"event": "P_ENG(proc): Running policy", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.policies.process", "pid": 20, "policy": "<ReputationPolicy: prevent bruteforce username>", "process": "PolicyProcess", "request_id": "fb8444a77b8540d7bde9448217cb68ba", "timestamp": "2021-06-26T22:16:19.684920", "user": "<django.contrib.auth.models.AnonymousUser object at 0x7fb6b9bf6850>"}
server_1       | {"event": "Score for Username", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.policies.reputation.models", "passing": false, "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "score": 0, "timestamp": "2021-06-26T22:16:19.686060", "username": ""}
server_1       | {"event": "P_ENG(proc): finished and cached ", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.policies.process", "passing": true, "pid": 20, "policy": "<ReputationPolicy: prevent bruteforce username>", "process": "PolicyProcess", "request_id": "fb8444a77b8540d7bde9448217cb68ba", "result": "<PolicyResult passing=True>", "timestamp": "2021-06-26T22:16:19.687317", "user": "<django.contrib.auth.models.AnonymousUser object at 0x7fb6b9bf6850>"}
server_1       | {"current_stage": "<DenyStage: Stage Cancel current flow>", "event": "f(exec): Current stage", "flow_slug": "bg-default-authentication-flow", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.flows.views", "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "timestamp": "2021-06-26T22:16:19.693300"}
server_1       | {"event": "f(exec): Passing GET", "flow_slug": "bg-default-authentication-flow", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.flows.views", "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "stage": "<DenyStage: Stage Cancel current flow>", "timestamp": "2021-06-26T22:16:19.694520", "view_class": "authentik.stages.deny.stage.DenyStageView"}
server_1       | {"event": "f(exec): Stage invalid", "flow_slug": "bg-default-authentication-flow", "host": "auth.bacchus.cloud", "level": "debug", "logger": "authentik.flows.views", "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "timestamp": "2021-06-26T22:16:19.694907"}
server_1       | {"event": "/api/v2beta/flows/executor/bg-default-authentication-flow/?query=next%3D%252F", "host": "50.66.148.168", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "fb8444a77b8540d7bde9448217cb68ba", "runtime": 230, "scheme": "https", "size": 0.045, "status": 200, "timestamp": "2021-06-26T22:16:19.704808"}
```

I don't know if I'm reading the logs correctly, but it seems like it is rejecting the anonymous user before a username has even been entered?

I'm not sure, but perhaps the problem may be that my settings are not being properly set. There are several times where if I re-check a setting (say 'negate') it will appear checked off and then the next time I open the binding properties it is un-checked. If I reload the page, maybe it will be correct maybe other settings will be blank. So, in essence, I can't be sure what is actually be saved and applied. Is this cached somewhere? Is there a way I can verify the *actual* settings? Any reason this would be happening?

**Comment by BeryJu** [comment]
Yeah so what you're suspecting is happening, thats a point I missed when testing this setup earlier. I'll have to some other way to accomplish this "banning" of users.

The checked/unchecked thing can happen sometimes when the state in the UI doesn't match whats stored on the server, normally the Forms should be reloaded when they are opened. On which form are you experiencing this issue?

Regardless, after a reload of the page, it should be correct.

**Comment by asifbacchus** [comment]
*forms*
It happens for me when moving quickly between flows and stages and then between stages and policies. You are correct though, a reload seems to mostly fix the issue.

*banning*
I did a full wipe of all volumes and restarted from scratch just to be sure. Still no luck -- is there another way you recommend I ban users or will this have to a future feature/enhancement?

Thanks again for getting back to me.

**Comment by BeryJu** [comment]
For the forms, I need to add some sort of overlay on the form when stuff is still loading, thats a bit of bigger change and will probably be in 2021.7

For banning, I want to add a flag in the flow stage binding, that configures how the flow should behave when an invalid response was sent, i.e. an invalid username. Currently, this is always passed back to the stage to decide, but you will be able to say "continue" and in this case it'll jump to the deny stage.

This feature shouldn't be too complicated, I'll try and get it in for 2021.6.3

**Comment by BeryJu** [comment]
Right @asifbacchus , you can now configure what the flow executor does when a stage gets an invalid response. To implement the "banning", you'd add a deny stage as first stage, with a re-evaluate reputation policy. Then add your identification stage as next stage, and set the invalid response action to `restart_with_context`. This will cause an invalid username to restart the flow (invisible to the user), keep the context (so the reputation policy checks the correct username), and when the threshold is passed, just show a deny stage.

**Comment by asifbacchus** [comment]
Very cool -- I will test this out hopefully sometime soon and let you know!
