### ISSUE TITLE
Theming issue - Multiple Browsers

### ISSUE THREAD

**Issue by DcryptedCA** [goauthentik/authentik#10800]
**Describe the bug**
Colors are off at login, cannot find solution. Previous related bug reports are closed.

**To Reproduce**
Go to login.

**Expected behavior**
Unreadable in Edge/Firefox at login. 

**Screenshots**
Edge:
![image](https://github.com/user-attachments/assets/743197f9-827e-4c8b-bb3b-5e273f1942ef)
Firefox (Dark Theme) on PC OR Android:
![image](https://github.com/user-attachments/assets/507e768a-0c16-4f83-bad0-6147b1168d13)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.6.2]
-   Deployment: Docker - Unraid

**Additional context**
Added  -> 
```
settings:
  theme:
    base: dark

```
To Brands/Attributes , but didn't resolve.

**Comment by BeryJu** [comment]
This is fixed in 2024.6.3

**Comment by DcryptedCA** [comment]
Updated. Confirmed fixed.
