### ISSUE TITLE
PEAP support

### ISSUE THREAD

**Issue by tbbkitty** [goauthentik/authentik#10816]
**Is your feature request related to a problem? Please describe.**
Kind of, there are some insecurity implications of sending password over plain text using PAP for network authentication.

**Describe the solution you'd like**
Option to use PEAP for radius authentication. Perhaps using the exisitng certificate store in authentik to provide a root CA?

**Describe alternatives you've considered**
Keeping my Windows enviroment alive :(

**Additional context**
N/A

**Comment by BeryJu** [comment]
see https://github.com/goauthentik/authentik/issues/5328#issuecomment-1631314781
