### ISSUE TITLE
Authentik Radius authentification for Omada OC200 embedded in TP-Link Router ER7212PC

### ISSUE THREAD

**Issue by samirdawaliby** [goauthentik/authentik#10824]
I am trying to integrate RADIUS authentication with my OC200 Omada controller, which is embedded inside an ER7212PC router. My Authentik instance is running on a VPS with a public IP. I am encountering issues with the RADIUS setup and need assistance in resolving them.

Configuration Details:
Authentik Identity Provider: Installed on a VPS with a public IP and a domain name URL (https;//authentik.caplogy.com).
I created a group and assigned a user to that group.
Router CIDR: 90.0.0.0/8 (public), 192.168.99.0/24 (local area network)
Omada Controller: OC200 embedded in ER7212PC router
RADIUS Provider Configuration: Followed the instructions from [https://docs.goauthentik.io/docs/providers/radius/](url)

I've seen another post related to this issue [https://github.com/goauthentik/authentik/issues/6243#issuecomment-1634050498] regarding routers requiring some extra attributes to actually work, which isn't provided by the current RADIUS outpost.

- Follow the [Generic LDAP](https://goauthentik.io/docs/providers/ldap/generic_setup) guide and make a 'radius-authentication-flow` if you don't want to do anything fancy
- Create a Radius Provider (see radius-provider screenshot), specifying the radius flow created. Take note of the shared key.
- Create a Application that uses the Provider
- Create a Radius Outpost and make sure the Provider is selected.

On the router side, i provide the RADIUS server IP as the IP of my Authentik VPS with port 1812 (see docker container ls screenshot), and i copied correctly the shared key that was provided as part of the Authentik Provider setup (see router-screenshot). 

Please see attached the below screenshots of my configuration, can you please help me finding what am i doing wrong?

![radius_application](https://github.com/user-attachments/assets/808c1a1b-a9d8-4c55-a8d2-dcd5b0b46fef)
![radius_authentication_flow](https://github.com/user-attachments/assets/959e1564-cf2a-4f9d-89a9-6fa8c2070776)
![radius_outpost](https://github.com/user-attachments/assets/6e126ec8-8b7c-4b10-be34-9dda67a72c15)
![radius_provider](https://github.com/user-attachments/assets/51733ffa-a762-4e0e-919f-40e7d20e0936)
![router-radius-config](https://github.com/user-attachments/assets/d80e382e-64b9-429b-8bbf-d3860ea3e4d1)
![docker-container-ls](https://github.com/user-attachments/assets/f5b35cee-cf56-4e63-95ea-96b388fed022)
![docker-radius-logs](https://github.com/user-attachments/assets/e5803763-a62c-406c-bcfb-ab2cdd2fd598)

**Comment by BeryJu** [comment]
See https://github.com/goauthentik/authentik/issues/5328#issuecomment-1631314781
