### ISSUE TITLE
Event matcher policy: Documentation is inconsistent with behaviour

### ISSUE THREAD

**Issue by lkbrdrstr** [goauthentik/authentik#10883]
**Describe the bug**
We want to be notified when a user is deleted and for this we need to check that several conditions are true. [The documentation](https://docs.goauthentik.io/docs/events/notifications) says, an event has to match all configured fields. This would work for us. [The Code](https://github.com/goauthentik/authentik/blob/5c46de39ec582eff322156545c2d97aad81614c7/authentik/policies/event_matcher/models.py#L111) only checks if _any_ of the matches pass.

<img width="781" alt="Bildschirmfoto 2024-08-12 um 19 14 15" src="https://github.com/user-attachments/assets/085a3c68-4f32-44f0-9728-54d23e7082f7">
<img width="428" alt="Bildschirmfoto 2024-08-12 um 19 14 29" src="https://github.com/user-attachments/assets/136188a5-84aa-481e-8eb1-c0670b1808ca">

It would be helpful, if the code could be changed to match the documentation and not the other way around :)

**Comment by BeryJu** [comment]
The code is slightly incorrect on this one, it should check that _all_ fields that have a value set in the policy to be true, but skip the fields that were left empty in the policy.
