### ISSUE TITLE
 missing space in the German representation of the Email prompt in application login flow

### ISSUE THREAD

**Issue by motey** [goauthentik/authentik#10892]
**Describe the bug**
A missing space in the German representation of the Email/username prompt of the application login flow

**To Reproduce**

1. Switch your browser to german language
2. Try to login in any authentik application, without being logged in to authentik

**Expected behavior**
Having the app name seperated from the rest of the text with a space.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/777fd636-a15a-4ee9-b308-db347f3e3e99)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.3 + 2024.6.0
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
translation changes are made here https://explore.transifex.com/authentik/authentik/ and are automatically merged into authentik

**Comment by laest** [comment]
Since this does not seem to be resolved yet, I would like to get my handy on that. I‘m new to transifex so I created a new account. I then applied to join the authentik project. Is this the correct way to contribute to the german translation?
