### ISSUE TITLE
SCIM source - property mappings  cannot be linked to scim source

### ISSUE THREAD

**Issue by aichert** [goauthentik/authentik#10904]
**Describe your question/**
We tested the new SCIM Source Feature you implemented, to compare it with other IDPs.
There we noticed a mismatch of your documentation and the current SCIM Source UI dialog.

In the SCIM Source dialog, there is no possibility to link a property mapping to.
We are aware of your statement that SCIM Source is currently a technical preview.

So our question is, is this expected behavior or is this planed for a future release?
If this is a bug, we are glad to help.

**Screenshots**
SCIM Source
![image](https://github.com/user-attachments/assets/013b0c82-fe46-4af1-809a-21278a8aad25)
vs
SCIM Provider
![image](https://github.com/user-attachments/assets/e30b4b69-497e-4f14-a026-6d8b5948a762)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.3
-   Deployment: docker-compose

**Additional context**
N/A

**Comment by BeryJu** [comment]
SCIM source property mappings will be available with 2024.8 which will be released later this month

**Comment by aichert** [comment]
Many Thanks for your fast reply!
we will check out the beta for this feature.
