### ISSUE TITLE
SCIM Group Delete is not synced

### ISSUE THREAD

**Issue by Ednn0nd1au** [goauthentik/authentik#10937]
**Describe the bug**
The delete function of Provisioned Groups under "SCIM Provider" is just delete the group fron the future provision list, but will not delete this group from application side.

Only delete function in group can result in application side group deletion.

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.6.3]
-   Deployment: [e.g. docker-compose]

**Comment by BeryJu** [comment]
Deleting the provisioned group in authentik purposefully only removes the connection between the group in authentik and the group in the remote application; this needs to be clarified in the UI and in the docs.

I have not seen the stacktrace you posted above, which SCIM application is this configured with?
