### ISSUE TITLE
Add pt_BR to locale options

### ISSUE THREAD

**Issue by wagoid** [goauthentik/authentik#10936]
In my deployment, I'm updating the things I can with portuguese translations (like prompts and emails), but that doesn't cover everything.

I started translating some strings in Transifex, and will keep adding more translations with time. Would it be possible to add `pt_BR` to the target locales config and sync with the suggested translations that we have for this language?

**Comment by BeryJu** [comment]
The translations will automatically be merged into authentik once they reach 100% on transifex, at which point they will also be shown as an option in the user interface. Thanks for helping translate authentik!

**Comment by wagoid** [comment]
Good to know, thanks! I'll keep working on them to hit 100%

**Comment by Jeremiegmoore** [comment]
> In my deployment, I'm updating the things I can with portuguese translations (like prompts and emails), but that doesn't cover everything.
> 
> I started translating some strings in Transifex, and will keep adding more translations with time. Would it be possible to add `pt_BR` to the target locales config and sync with the suggested translations that we have for this language?
