### ISSUE TITLE
After succesfull login Authentik redirects to base url without subpath and query args

### ISSUE THREAD

**Issue by kzvdar42** [goauthentik/authentik#10938]
**Describe the bug**
For example:
1. I go to `https://work.home/test-path/?arg=1`
2. It redirects me to authentik, I log in
3. Authentik redirects me to `https://work.home` without subpath and query arguments

**To Reproduce**

1. Setup authentik and app behind nginx (standalone) using configs from authentic docs
2. Setup Forward Auth (single application) Proxy Provider for the app
3. Try to login to app from subpath/with query arguments

**Expected behavior**
After successful login authentik should redirect back to the original requested uri

**Logs**
Don't know which logs should I add here, will add some if requested

**Version and Deployment:**
-   authentik version: [2024.6.3]
-   Deployment: [docker-compose (portainer)]
All nginx configs are default configs from the docs

**Comment by mrcheap1984** [comment]
I'm getting a similar bug, launching the app from authentik fails the first time in a new tab, but if I close and open a new tab it launches with no issues.
Watching with interest.

**Comment by chahmedejaz** [comment]
Hi @BeryJu - I'd love to work on this issue, can you please assign it to me? Thanks.

**Comment by swjcarter** [comment]
Sounds like the same thing I just asked in the Q&A.  First click takes you to root, 2nd click works as expected.

**Comment by swjcarter** [comment]
Hopefully this is a fairly easy fix.

**Comment by swjcarter** [comment]
Happens also with 2024.6.4

**Comment by swjcarter** [comment]
Thank you @beryJu !!!
