### ISSUE TITLE
If multiple hardware keys are added, all are shown durign authentication flow

### ISSUE THREAD

**Issue by schemen** [goauthentik/authentik#1096]
**Describe the bug**
As title.

Once you add multiple keys (For example yubikey) there are multiple identical options for each key. It is also not clear which prompt is for which key.

![image](https://user-images.githubusercontent.com/5279155/124026678-46ea3800-d9f2-11eb-9bf6-46953937fa79.png)

**To Reproduce**
1. Add more than one hardware key
2. Enable multiple factor in you flow
4. See behavior

**Expected behavior**
I expect to have a single authenticator prompt and authentik figuring out which key I used.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.6.3
 - Deployment: Kubernetes

**Comment by GeorgeGedox** [comment]
Still an issue in 2021.7?

**Comment by BadAtIrcBots** [comment]
Issue present on 2021.8.1-rc1 and 2021.7 for me.

My issue is that I end up with two authenticators, one will work with the newer key but neither work for the key enrolled first. I get "Assertion failed." in the JSON response when using the original key on either authenticator on the login page.

**Comment by BeryJu** [comment]
Interesting, which keys are you using?

**Comment by BadAtIrcBots** [comment]
> 
> 
> Interesting, which keys are you using?

YubiKey 5 NFC

**Comment by BeryJu** [comment]
@BadAtIrcBots the bug you ran into is fixed with this commit as well
