### ISSUE TITLE
Welcome to authentik! Request has been denied. Flow does not apply to current user.

### ISSUE THREAD

**Issue by Chrisj76au** [goauthentik/authentik#11019]
**Describe the bug**
I've had authentik setup for a about 2 week now and then it stopped working a few days ago kept saying my password was incorrect. I tried ak create_recovery_key 10 akadmin to get the recovery link and that would not work.  So I ended up blowing it all away and starting again half way through the initial-setup it failed and would not let me in I kept getting the login page the admin account would not work as I had not gotten a change to enter a password.

So again deleted the local data store - docker composed down and tried again to get the same issue again this time I got to enter my email and password then press submit and now I keep getting 

Request has been denied. Flow does not apply to current user.

**To Reproduce**

same behaviour in chrome and edge normal and private mode
1. Go to https://authentik.<mydomain>:1443/if/flow/initial-setup/ I've tried non http with the port 80 same thing
2. See error

**Expected behavior**
 it's meant to log me into the dashboad
[authentik_postgresql_logs.txt](https://github.com/user-attachments/files/16706152/authentik_postgresql_logs.txt)
[authentik_server_logs.txt](https://github.com/user-attachments/files/16706153/authentik_server_logs.txt)
[authentik_worker_logs.txt](https://github.com/user-attachments/files/16706154/authentik_worker_logs.txt)
![2024-08-22 16_10_30-Window](https://github.com/user-attachments/assets/8659ef9c-cc1f-45f3-8089-64856441b3a2)

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
-   Deployment: [e.g. docker-compose, helm]

**Additional context**

Any help in why this has happened would be greatful

**Comment by Chrisj76au** [comment]
found the issue - I had 2 dns entries - I restored the old DB and used the recovery key and it let me back in again

**Comment by Chrisj76au** [comment]
resolved per above

**Comment by jluizpjr** [comment]
I had the same issue after destroying the containers, deleting the images, reinstalling and even rebooting my workstation. I solved by clearing the browser cache...
