### ISSUE TITLE
Application icon issues - various

### ISSUE THREAD

**Issue by boomam** [goauthentik/authentik#11029]
**Describe the bug**
When uploading icons to a given application, authentik confirms a successful upload, however when looking at the icon on either the portal page or the admin console, i get a missing icon, icon, along with 'Application' being listed.

This occurs whether using a k8s pvc, mounting `/media` (and confirming the files are indeed writing to the pv), along with when  the storage backend is set to S3/Minio, where the same occurs (files write, etc.).

In addition, the 'clear icon' toggle appears to do nothing whatsoever.
When replacing the icon with a new upload, previous icon does not remove from the storage location, either.

**To Reproduce**

Admin GUI->Applications->Edit

**Expected behavior**
1. Icons to show.
2. The 'clear icon' toggle working.
3. Old icons to be deleted from storage.

**Screenshots**
![2024-08-22 15_12_24-Applications - Admin - authentik home](https://github.com/user-attachments/assets/84b04e33-a1e8-4540-887d-b1df3f2ea744)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.4
-   Deployment: helm

**Additional context**
This also occurred with 2024.6.3 and 2024.6.0

**Comment by EAnsy** [comment]
#11176
