### ISSUE TITLE
Ldap outpost crashing at  startup.

### ISSUE THREAD

**Issue by Spacelord09** [goauthentik/authentik#1105]
**Describe the bug**
I've created a ldap outpost with docker and its crashing on every startup.

**Expected behavior**
I'm expecting a working outpost that is not restarting always.

**Screenshots**
![This should be a screenshot ;D](https://spacecdn.de/img/2021/07/04/2021-07-04_18-23-23-356c63d0-15ef-4f21-a63b-b2f3ced26ef0.png)

**Logs**
Look above.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.6.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
In the current version this happens on the initial creation of the outpost, as the service account thats created doesn't have the required permissions. To quickly work around the issue, just save the outpost again.

**Comment by Spacelord09** [comment]
The creation is working now and its displaying after the reation stats about the outpost. But some moments later the stats are gone and I'm getting still this error:
```{"error":"failed to run initial refresh: no ldap provider defined","event":"Failed to run server","level":"panic","timestamp":"2021-07-06T17:01:16Z"}```

**Comment by Spacelord09** [comment]
I also tried to include the ldap outpost in the docker-compose file. Same issues:
```goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00015a700, 0x0, 0xc0000262a0, 0x14)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc00015a700, 0x0, 0xc000571ed8, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x86
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:331
main.main()
	/go/src/goauthentik.io/outpost/cmd/ldap/server.go:57 +0x439
{"buildHash":"tagged","event":"Starting authentik outpost","level":"info","timestamp":"2021-07-06T17:24:13Z","version":"2021.6.4"}
{"error":"failed to run initial refresh: no ldap provider defined","event":"Failed to run server","level":"panic","timestamp":"2021-07-06T17:24:15Z"}
panic: (*logrus.Entry) 0xc000364150

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0003640e0, 0x0, 0xc00009c228, 0x14)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc0003640e0, 0x0, 0xc000377ed8, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x86
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:331
main.main()
	/go/src/goauthentik.io/outpost/cmd/ldap/server.go:57 +0x439```

**Comment by Spacelord09** [comment]
Nevermind... It's working now.
I've forgotten to create an app..

**Comment by Spacelord09** [comment]
Now I'm getting:
```
ldapsearch -x -h 127.0.0.1 -p 389 -D 'CN=akadmin,OU=users,DC=BUSINESS,DC=io' -w 'PASSWORD'  -b 'ou=users,DC=ldap,DC=BUSINESS,DC=io' '(objectClass=user)'
```

Response:
```
ldap_bind: Insufficient access (50)
```

I've added a group called "ldapadm" for ldap search queries. And akadmin is part of it.

**Comment by Spacelord09** [comment]
Nevermind again.. ;D
The default auth flow was selected..
