### ISSUE TITLE
Is it possible to modify a provider's endpoint urls?

### ISSUE THREAD

**Issue by Bauers-Lab-Jared** [goauthentik/authentik#11101]
**Describe your question/**
I am connecting a server application called Octoplant to an Authentik OIDC provider. Octoplant does not use discovery through the .well-known url. When I paste in the endpoint urls, it strips off the trailing '/' and tells me that they should not have trailing '/'s.

This of course becomes a problem when trying to authenticate, because the issuer url doesn't match. (differing by only the trailing '/')

I haven't been able to find any mention of how to configure the endpoint urls for a provider. Is this possible?

**Relevant info**
The Authentik installation has been working with no issues. I have other OIDC applications functioning just fine. (They use discovery)

With the end application claiming that the urls should not end with '/', I have been reading through the spec.
[OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation)
Section 4.3 Mentions that "The issuer value returned MUST be identical to the Issuer URL that was used as the prefix to /.well-known/openid-configuration to retrieve the configuration information."

This does seem to imply that the issuer url can't end in a '/' because that would yield the config information url:
https://auth.example.com/application/o/octoplant//.well-known/openid-configuration

I am not really sure what to do with that information, but it would be helpful if I could remove the trailing '/' on the endpoint urls, atleast on the one provider.

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.4
-   Deployment: dedicated VM

**Additional context**

**Comment by BeryJu** [comment]
It is not possible to change the the URLs of the oauth2 provider. One setting that might help in this case especially as the application does not use discovery is to set the "Issuer mode" to global, which sets `iss` to `https://authentik.tld`, which should be accepted by the application

**Comment by Bauers-Lab-Jared** [comment]
Ok, thanks. I will try that.

**Comment by Bauers-Lab-Jared** [comment]
Unfortunately, the end application doesn't seem to be able to handle that. It produces some internal errors that are not very helpful.

I will just see if I can get them to use discovery or simply stop changing my provided configuration.

Thanks.
