### ISSUE TITLE
Stuck at Loading Screen (disallowed MIME type)

### ISSUE THREAD

**Issue by obadaahmar** [goauthentik/authentik#11117]
**Describe the bug**
Hi, I've recently have been having issues logging to any application that authentication is handelled with Authentik (no matter if it is OIDC or Proxy Authentication)
Authentik started hanging at the Loading Screen and would work after a couple of refreshes but now it won't work at all.

No indication in the logs something is wrong, however the only thing I noticed in the browser console log is down below.

**To Reproduce**

Go to app.domain.tld, redirect for authentication, hangs on "Loading" with multiple console messages saying loading failed for module (See below log)

**Expected behavior**
Successful authentication and redirection.

**Screenshots**
<img width="1918" alt="Screenshot 2024-08-29 163639" src="https://github.com/user-attachments/assets/dfc3772d-9d64-484d-ba04-c0b81cc9f246">

**Logs**
Browser Console log:
```
Loading failed for the module with source “https://auth.domain.tld/static/dist/flow/chunk-FP52VTUN.js”.
Loading module from “https://auth.domain.tld/static/dist/flow/chunk-FP52VTUN.js” was blocked because of a disallowed MIME type (“text/html”).

```
No Authentik logs indicated failed authentication.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.6.4
-   Deployment: Docker in Unraid

**Additional context**
I use Nginx Proxy Manager for my reverse proxy needs, below is the only configuration added for Authentik:
```
proxy_set_header X-Real-IP $remote_addr;
```

**Comment by BeryJu** [comment]
I'm suspecting this is a cache issue, try clearing the cache in your browser (and if enabled the cache in your NPM, and in Cloudflare if you're using that).

**Comment by obadaahmar** [comment]
That worked! thanks for your help @BeryJu !
Attaching some images of how I disabled caching in Cloudflare and NPM for future reference if anyone has the same issue:
![cloudflare](https://github.com/user-attachments/assets/ab26a03e-c31d-499c-aa84-0fdc96d2807a)
![npm](https://github.com/user-attachments/assets/452cd25f-86ba-4233-9e7a-1fddb0a436ec)
