### ISSUE TITLE
Proxy provider - Forward-auth (domain level) - how to logout?

### ISSUE THREAD

**Issue by MagicianTM** [goauthentik/authentik#1113]
I have correctly setup the proxy provider for forward-authentication at domain level (I'm using Traefik). So, accessing one site configured behind it redirects me to the Authentik login page. When successfully authenticated, I'm then redirect to the site I was trying to access.

After this flow, 2 cookies (domain level) have been created:
- authentik_proxy_0
- authentik_proxy_1

![image](https://user-images.githubusercontent.com/80957265/124593012-6bb13600-de5e-11eb-9d7b-ac328f21c3cb.png)

But now, I wonder how I can logout from it.
I was expecting that going onto the Authentik panel for my currently logged in user, then logout, would clean up my cookies used for forward authentication. But it only cleans the session cookie.

So, for the sites for which I configured the forward-authentication, I cannot logout easily. I have to delete by myself the 2 cookies that were set up.

Am I missing something ?

NB: the cookie domain configured at my proxy provider is `domain.com` (and my authentik host is at `authentik.domain.com`)
And I can see in Firefox that the 2 mentioned cookies above are on domain `.domain.com`.

I also tried to use the end-session url for the application used for this forward-auth (ie: `https://authentik.domain.com/application/o/<application-slug>/end-session/`). But it doesn't make any difference.

**Comment by BeryJu** [comment]
Hi, so to log out with the proxy provider, you can navigate to `proxy-auth-domain.foo.tld/akprox/sign_out`, this will clear the cookies for the proxy provider and then redirect you to the end-session URL from authentik, where you can then fully log out.

**Comment by MagicianTM** [comment]
Thanks for the quick response. It does exactly what I expected.

**Comment by BeryJu** [comment]
Also added a small notice in the docs for the future

**Comment by ksaadDE** [comment]
https://github.com/goauthentik/authentik/discussions/9737

**Comment by vgdh** [comment]
> Hi, so to log out with the proxy provider, you can navigate to `proxy-auth-domain.foo.tld/akprox/sign_out`, this will clear the cookies for the proxy provider and then redirect you to the end-session URL from authentik, where you can then fully log out.

Hi @BeryJu. 
I've tied:
```
authentik.mydomain.com/akprox/sign_out
authentik.mydomain.com/outpost.goauthentik.io/sign_out

myapp.mydomain.com/akprox/sign_out
myapp.mydomain.com/outpost.goauthentik.io/sign_out
```
nothing from above works

but i can finish one session with (on authentik subdomain only)
```
authentik.mydomain.com/application/o/my-app-slug-name/end-session/
```

Do you know how to sing out from all apps?
