### ISSUE TITLE
[2024.8.0] No Applications Listed in Create/Edit Outpost Dialog

### ISSUE THREAD

**Issue by SirWobbyTheFirst** [goauthentik/authentik#11182]
**Describe the bug**

In the newest 2024.8 and the subsequent 7637abb beta that fixes #11171. Authentik is no longer showing the applications configured for deploying an Outpost. In addition, any existing outpost such as the standard Authentik outpost that is created on installation, is also unable to be configured with newer applications and the existing applications do not show for the outpost. See the images below.

**To Reproduce**

1. Upgrade to build 7637abb via the Beta Upgrade instructions listed in #11171.
2. Login to Authentik.
3. Go to Applications > Outposts.
4. Click Create.

**Expected behavior**

A list of applications that can be added to the outpost on the left hand side and a list of already configured for the outpost on the right side.

**Screenshots**

![image](https://github.com/user-attachments/assets/e27d1ded-6655-4d7b-a2e3-19427b071060)
![image](https://github.com/user-attachments/assets/9cbbe4ab-aa33-4703-8d3a-dca33f568261)
![image](https://github.com/user-attachments/assets/8a3363c3-a584-44d2-a16f-22e9936679b5)
![image](https://github.com/user-attachments/assets/7b86daf1-71a3-41bb-82c5-f222d35c94bf)

**Logs**
Output of docker-compose logs or kubectl logs respectively

Text File Attached
[Docker Compose Log.txt](https://github.com/user-attachments/files/16853456/Docker.Compose.Log.txt)

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]: 2024.8 (Build 7637abb)
-   Deployment: [e.g. docker-compose, helm] docker-compose

**Additional context**

I initially upgraded from 2024.6.4 to 2024.8.0 however this failed with the issue seen in #11171, I then tried reverting back to 2024.6.4 which booted successfully but the LDAP source was broken, I then upgraded to 2024.8.0 (Build 7637abb) per the instructions in the bug report and it booted successfully and all functionality seemed to be working, but then logging in about 4 hours afterwards (Now) yielded a problem with the LDAP Outpost which I assumed was due to it being built on 2024.6.4 still. I then opened the LDAP Outpost and just clicked Update and the container always showed a yellow unhealthy warning in Portainer. I then deleted the LDAP Outpost and was unable to recreate it due to the missing applications.

**Comment by BeryJu** [comment]
see https://github.com/goauthentik/authentik/pull/11173, use ghcr.io/goauthentik/dev-server:gh-version-2024.8

**Comment by andreasrevdal** [comment]
When using the dev-server none of my outposts works anymore, they keep restarting with log:

> {"error":"no ldap provider defined","event":"Failed to run server","level":"panic","timestamp":"2024-09-04T14:27:34Z"}

**Comment by heavymp** [comment]
Hi,
i still have this same issue with version 2024.8.1. I am unable to add any apps (either manually created or from docker integration) to default outpost, or create a new outpost in the GUI
![image](https://github.com/user-attachments/assets/72056d4b-11ac-4967-be09-7578af75dcf4)
![image](https://github.com/user-attachments/assets/b0220f56-d9ee-4ff2-97a9-90c1bde5c7a6)
![image](https://github.com/user-attachments/assets/d8aaba33-e781-4e4c-91b6-ffd42f9bffc5)

**Comment by qdrddr** [comment]
Same with integration: Kubernetes, the list is empty. my version is 2024.12.2
