### ISSUE TITLE
Write changed user data from OIDC federation

### ISSUE THREAD

**Issue by tbbkitty** [goauthentik/authentik#11199]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
If a user has changed in the federated OIDC client the changes should be reflected in authentik. Names and email changed should be reflected in authentik..

However passwords should act the way they already do and should not be synced.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by BeryJu** [comment]
With the OAuth Source Property mappings added in 2024.8 and #11702 added in 2024.10 this is possible (but not configured by default). You can add a user_write stage to the source's authentication flow (with the default flow you need to change the user_login stage to a later order) and the user will be updated with the data from the OIDC source.

**Comment by tbbkitty** [comment]
Yes this now seems to work similar to what we wanted.
