### ISSUE TITLE
Can't not create any providers

### ISSUE THREAD

**Issue by bdorr1105** [goauthentik/authentik#11190]
**Describe the bug**
I am unable to create any additional providers. When I got to add and click finish, it is like I am not clicking anything at all. I tried to add a proxy provider and it did not work or let me add one

**To Reproduce**

1. Go to the Admin Interface
2. Click on Applications
3. Scroll down to Providers, try to create a proxy provider, fill in required info and hit Finish. Nothing will happen

**Expected behavior**
It actually adds the new provider I created

**Screenshots**
![Screenshot 2024-09-04 005348](https://github.com/user-attachments/assets/9e2ff9c3-7e34-4054-a536-9ddf9139d220)

**Logs**
No Logs to show

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.0
-   Deployment: docker compose

**Additional context**
This has never happened to me before. This all started because my oAuth setup stopped working and then all of a sudden, I modified a proxy provider I wasn't using and then it was not redirecting to the right url, Authentik was passing the internal IP. Only since I updated to 2024.8.0 did this start happening. This ruined access to my git, I had to do crazy work arounds

**Comment by coworkers-de** [comment]
Think its related to #11179

**Comment by f0o** [comment]
I can fully reproduce this; Chrome/Firefox console dumps this:

```
ak-dual-select.ts:118 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at h.willUpdate (ak-dual-select.ts:118:55)
    at h.performUpdate (reactive-element.ts:1439:14)
    at h.scheduleUpdate (reactive-element.ts:1338:25)
    at h._$ET (reactive-element.ts:1310:25)

ak-dual-select.ts:284 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at h.render (ak-dual-select.ts:284:40)
    at h.update (lit-element.ts:158:24)
    at h.performUpdate (reactive-element.ts:1441:14)
    at h.scheduleUpdate (reactive-element.ts:1338:25)
    at h._$ET (reactive-element.ts:1310:25)
﻿
```

**Comment by HelloDimension** [comment]
same issue... i was so happy to get this up... now I'm here.

**Comment by vianney35** [comment]
same here with fresh install

**Comment by finkerle** [comment]
same here

**Comment by BeryJu** [comment]
Fixed by https://github.com/goauthentik/authentik/pull/11203; if anyone is still experiencing this please open a new issue
