### ISSUE TITLE
Reworked prompt stage seems not functional

### ISSUE THREAD

**Issue by balderekjk** [goauthentik/authentik#11209]
**Describe the bug**

Reworked prompt stage seems not functional.

**To Reproduce**

1. Go to Stages > Click Edit icon on row of existing Prompt Stage
2. Available Fields read "[object Object]"; Selected Fields read a single alphanumeric character i.e. "1", "d", etc.
3. Click "Update"
4. See error: "_ is not a valid UUID", where underscore represents alphanumeric character.

**Expected behavior**

1. Available Fields and Selected Fields display list of field names and/or keys.
2. Clicking Update works. It sends the UUID correctly.

**Screenshots**

![prompt_bug](https://github.com/user-attachments/assets/b7ec8bd7-474b-4141-a830-d65d0713d17b)

**Version and Deployment (please complete the following information):**

-   authentik version 2024.8.0, through Apptainer instances

**Comment by BeryJu** [comment]
see https://github.com/goauthentik/authentik/pull/11203, this will be fixed with 2024.8.1
