### ISSUE TITLE
Bug in "Passsword Change Prompt"

### ISSUE THREAD

**Issue by fstracke** [goauthentik/authentik#11205]
**Describe the bug**
After a fresh installation of authentik 2024.8.0, when I want to configure the default-password-change-prompt stage to include a password complexity restriction, the Items in the selection lists are not correctly displayed. See the attached screenshot:

**To Reproduce**

1. Start with a fresh authentik compose-based installation
2. Click on 'Flows and Stages' > 'Stages'
3. Select 'default-password-change-prompt'

**Expected behavior**
Display the objects in the selection lists correctly. Do not thorw an error when saving the configuration without any changes.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/e12c9a99-e174-44cf-9e6f-acc76edf57ab)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.0
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
Fixed by https://github.com/goauthentik/authentik/pull/11203, use ghcr.io/goauthentik/dev-server:gh-version-2024.8
