### ISSUE TITLE
Empty application list in LDAP outpost creation

### ISSUE THREAD

**Issue by dstronaut** [goauthentik/authentik#11201]
**Describe the bug**
When creating new LDAP outpost, the available applications list is empty.
I have created application with LDAP provider, but I can't create outpost for it.

**To Reproduce**

1. Create application with LDAP provider 
2. Go to Applications/Outposts
3. Click Create

**Expected behavior**
I expect to see my previously created application with LDAP provider.

**Screenshots**

![image](https://github.com/user-attachments/assets/49f7a377-02a1-4d92-acfd-d976053ffac7)

**Logs**
There are no specific logs when opening the "Create Outpost" modal.

**Version and Deployment:**

-   authentik version: 2024.8.0
-   Deployment: docker-compose

**Additional context:**
I was able to create the outpost by sending POST request via browser developer tools with provider's PK typed by hand and in "Update Outpost" I see my application (and it works). So, probably it is a UI issue.

![image](https://github.com/user-attachments/assets/b6986394-d2fc-4381-9b2f-c6ad6a15ff64)

**Comment by BeryJu** [comment]
See https://github.com/goauthentik/authentik/issues/11182#issuecomment-2327204647

**Comment by qdrddr** [comment]
Can you please help to understand steps you have taken for the workaround @dstronaut via browser developer tools?
