### ISSUE TITLE
**Describe your question/**

### ISSUE THREAD

**Issue by gschenk68** [goauthentik/authentik#11210]
**Describe your question/**
I successfully installed anuthentik on synology nas and initialized it, but "Internal Server Error" appeared.

**Relevant info**
image: ghcr.io/goauthentik/server:2024.2.2
synology nas(DS918+) :DSM 7.2.1-69057 Update 4

**Screenshots**
![截屏2024-03-30 07 18 32](https://github.com/goauthentik/authentik/assets/9693302/76daa2e6-f133-464b-935d-3138c6fd4953)

**Logs**
[logs.zip](https://github.com/goauthentik/authentik/files/14809132/logs.zip)

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.2.2]
-   Deployment: [docker-compose]

**Additional context**
none

_Originally posted by @ainp in https://github.com/goauthentik/authentik/issues/9078_

**Comment by BeryJu** [comment]
See https://github.com/goauthentik/authentik/issues/9078#issuecomment-2305189702
