### ISSUE TITLE
Permission "Search full LDAP directory" seems always granted

### ISSUE THREAD

**Issue by Doridian** [goauthentik/authentik#11215]
**Describe the bug**

I can restrict access to the LDAP directory in general via policy. However, even a test user I have created which has no special permissions can search every user in the LDAP directory.

**To Reproduce**

Set up the LDAP outpost as described here: https://docs.goauthentik.io/docs/providers/ldap/ (and: https://docs.goauthentik.io/docs/providers/ldap/generic_setup )

Create an "Internal" user, and give it a test password, do not give the user any permissions.

Run (replacing the placeholders) `ldapsearch -W -H ldap://authentik.local -D 'cn=testuser,ou=users,dc=authentik,dc=local' -b 'ou=users,dc=authentik,dc=local'`

**Expected behavior**

Only users granted the `Search full LDAP directory`  should be able to see users but themselves.

As outlined here: https://docs.goauthentik.io/docs/providers/ldap/#searching--search-modes

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.08
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
I'm assuming the internal user you created was also not part of any group? (and as such was not a superuser)
