### ISSUE TITLE
Applications URL of forwardauth provider now with X-authentik-auth-callback

### ISSUE THREAD

**Issue by ffritsche** [goauthentik/authentik#11234]
**Describe the bug**
All application links in the user dashboard that uses a forward auth(single App) provider now looks like this.
https://app.domain.tld/?X-authentik-auth-callback=true

I use traefik as reverse proxy with the middleware from the documentation (https://docs.goauthentik.io/docs/providers/proxy/server_traefik)

Most applications run in errors with this GET parameter.

**To Reproduce**

1. Create a forward auth(single app) provider
2. Create a app with this provider
3. Go to the user dashboard

**Expected behavior**
Use the provides "External host" url without this parameter

**Version and Deployment (please complete the following information):**
Docker-Compose
image: ghcr.io/goauthentik/dev-server:gh-version-2024.8 (https://github.com/goauthentik/authentik/commit/fadeaef4c65f9226325adcce1121fb7e31a237c3)

**Comment by EAnsy** [comment]
The same issue after update to 2024.8.
Not only _traefik_, but clear application proxy too (I use for _Swagger-UI_).
Workaround is to fill optional (usually empty) field _Launch URL_ with correct Application URL.

**Comment by tscibilia** [comment]
Is this in release 2024.8.1? or a future patch?
I updated, but I'm still seeing the wrong proxy provider url

**Comment by elriti** [comment]
> Is this in release 2024.8.1? or a future patch? I updated, but I'm still seeing the wrong proxy provider url

in the next release mate

**Comment by levi-jcbs** [comment]
Is there a workaround right now? (Yes, my bad), but this broke production for me.

**Comment by levi-jcbs** [comment]
Another workaround is to override the Launch URL in `Applications` > `Edit` > `UI Settings`.
