### ISSUE TITLE
API browser not available

### ISSUE THREAD

**Issue by atrauzzi** [goauthentik/authentik#11233]
**Describe the bug**
When I try to navigate to the API browser [as per instructions](https://docs.goauthentik.io/developer-docs/api/), I end up getting a not found screen:

![image](https://github.com/user-attachments/assets/2ca6e6dd-ff92-4dff-bd63-8cff86e68d3c)
_(ignore the SSL error, just a self-signed cert)_

**Version and Deployment (please complete the following information):**

-   authentik version: `2024.8.0`
-   podman

**Additional context**

I've got nginx in front of it, though it's a very basic reverse proxy setup locally on my workstation.  Authentik otherwise seems to work great:

```
server {
        listen 443 ssl;
        server_name ~^auth(\..*)?\.localdev\.com$;

        location @websocket {
            proxy_pass http://authentik:8079;
        }

        location / {
            proxy_read_timeout 30s;
            proxy_http_version 1.1;
            proxy_redirect off;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_pass http://authentik:8079;
        }
    }
```

**Comment by BeryJu** [comment]
The url you're accessing is missing a trailing slash.

**Comment by BeryJu** [comment]
The API browser is documented [here](https://docs.goauthentik.io/docs/developer-docs/api/) with a trailing slash and the link in the authentik frontend goes to the correct URL with a trailing slash too
