### ISSUE TITLE
Weird Fields displaying in Stage-specific settings and Policies selected

### ISSUE THREAD

**Issue by EAnsy** [goauthentik/authentik#11240]
**Describe the bug**
_Stage-specific settings_ looks weird in _Fields_ and especially _Selected Fields_ (item values selected).
Can't recognize and verify what exactly selected there. The same for _Validation Policies_ selected (_Available_ looks good though).

**To Reproduce**

1. Go to Admin console.
2. Click on _Flows and Stages_, then _Stages_.
3. Open one of stages (f.e. _default-user-settings_) for edit.

**Expected behavior**
Correctly displayed _Fields_. List of _Selected Fields_ with item names according to _Fields_ already selected.

**Screenshots**
![image](https://github.com/user-attachments/assets/5fa1c3f9-fd95-49ec-acae-be0041328f26)

**Logs**
Not available.

**Version and Deployment:**

-   _authentik_ version: **2024.8**
-   Deployment: **docker-compose, k8s** (both)

**Additional context**
IMHO the issue raised after upgrade from 2024.6.4.

**Comment by Subkrys** [comment]
Same issue here since upgrade from 2024.6.4 to 2024.8


<img width="543" alt="firefox_YXsWWLqSgi" src="https://github.com/user-attachments/assets/280a7da6-1bda-48dc-9410-3e4704e95b4b">

**Comment by Simon-CR** [comment]
same issue here, same behaviour from upgrade and from fresh clean install

**Comment by kevinkellner** [comment]
Same issue as  #11237

**Comment by BeryJu** [comment]
This is fixed by 2024.8.1 which was released earlier today.
