### ISSUE TITLE
2024.8.0: Unable to create new notification rule

### ISSUE THREAD

**Issue by abol01** [goauthentik/authentik#11261]
**Describe the bug**
Attempting to create a new notification rule does not bring up the Transports table.

**To Reproduce**

1. Click on Events > Notification Rules
2. Click create
3. Name the notification rule'
4. Note that no UI for entering the Transports is presented.
5. Click 'Create' and get no errors or rule is created

**Expected behavior**
I would expect the UI to show the available Transports table, and the rule to be created successfully.
**Screenshots**
![image](https://github.com/user-attachments/assets/3f6930e5-10b7-48c5-8a07-4f71724b655a)

**Logs**
Nothing apparent in the logs.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.0
-   Deployment: docker-compose

**Additional context**

**Comment by devra1** [comment]
This is well documented in #11179

**Comment by devra1** [comment]
Probably same problem as #11179

**Comment by BeryJu** [comment]
This is fixed by 2024.8.1 which was released earlier today.
