### ISSUE TITLE
Unable to create new Proxy Provider

### ISSUE THREAD

**Issue by egergo** [goauthentik/authentik#11263]
**Describe the bug**
Clicking on "Finish" after filling out the form for a new "Forward auth" Provider does not finish the process without giving any feedback.

**To Reproduce**

1. Go to Providers
2. Click Create
3. Select Proxy Provider
4. Click Next
5. Specify Name, Authentication flow and Authorization flow
6. Select Forward auth tab
7. Specify External host
8. Click Finish

**Expected behavior**
The dialog should disappear with the new Provider created.

**Screenshots**
![Capture](https://github.com/user-attachments/assets/79aafcac-8421-4076-aca0-e5f00e10fc23)

**Logs**
Browser Console (Google Chrome Version 128.0.6613.84 (Official Build) (64-bit)) logs :
![Capture2](https://github.com/user-attachments/assets/be22225e-cfe3-4a7c-98e6-3320aa31ac23)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.0
-   Deployment: docker-compose

**Additional context**
N/A

**Comment by Adevill20** [comment]
I have the same problem with the same deployment as OP

**Comment by BeryJu** [comment]
2024.8.1 is released now which fixes this fully
