### ISSUE TITLE
[2024.8.1] Blank Web Page After Upgrade

### ISSUE THREAD

**Issue by SirWobbyTheFirst** [goauthentik/authentik#11282]
**Describe the bug**

After doing a controlled upgrade from 2024.6.4 to 2024.8 and then to 2024.8.1, I am now greeted with a blank web page and none of the flows load. The only part of the website that loads is the 404 not found page. The upgrade from 2024.6.4 to 2024.8.0 went fine but the app still stated there was an update available, so I modified the docker-compose.yml file so that the image says:

${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.8.1}

instead of the same line but with -2024.8.0 at the end.

**To Reproduce**

1. Upgrade from 2024.6.4 to 2024.8.0
2. Login and observe the update checker state that 2024.8.1 is available.
3. Update the docker-compose.yml file image property for server and worker to use -2024.8.1 instead of 2024.8.0
4. Boot up and observe a blank web page.

**Expected behavior**

It just works.

**Screenshots**

![image](https://github.com/user-attachments/assets/7f42d877-2ea8-4bd6-b12b-643d8a309b33)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.1
-   Deployment: docker-compose

**Additional context**

I needed to update the property mappings to revert to the original values after the upgrade minced them.

**Comment by BeryJu** [comment]
Clear your browser cache/any WAF you might be using. We're using versioned javascript files that include the version so this shouldn't happen ideally

**Comment by SirWobbyTheFirst** [comment]
This has worked, in conjunction with doing a straight upgrade from 2024.6.4 to 2024.8.1 and I am now successfully on the latest version.

Please don't release another version for little while. 🥲
