### ISSUE TITLE
Bulk delete users with ak shell?

### ISSUE THREAD

**Issue by GD-Dal** [goauthentik/authentik#11296]
Hi 
I wanted to import users from a specific group in Active Directory, but I apparently got the filter wrong. So I ended up imported the entire directory with 16 000 users..
So I want to delete them, but the GUI only lets med delete 20 at a time.
But I read something about ak shell? 
But (as usual with Authentik, unfortunately) it's not well documented.
Can someone help me out with the syntax for that command?

All AD users are in Root/Active Directory Users

Thanks

**Comment by boesr** [comment]
Had the same problem. I am not sure about ak shell, but you can use the database to delete it. The corresponding table is `authentik.public.authentik_core_user` and you can filter by path

**Comment by BeryJu** [comment]
You can delete users in the shell by running `User.objects.filter(username="foo").delete()`, see https://authentik-source-docs.netlify.app/authentik/core/models#User for all the fields and https://docs.djangoproject.com/en/5.1/ref/models/querysets/#id4 for how filtering works
