### ISSUE TITLE
Read-only text prompt is unreadable in dark theme

### ISSUE THREAD

**Issue by danclay** [goauthentik/authentik#11314]
**Describe the bug**
When in dark theme, the read-only text prompt has a white background with white text. The editable field is fine. Light theme is also fine.

**To Reproduce**

1. Set one text prompt to read-only and one to editable
2. Place these in a stage and flow

**Expected behavior**
A readable field which is lightly discolored to indicate the read-only state

**Screenshots**
Below "Username" is read-only and "Name" is editable
![image](https://github.com/user-attachments/assets/fbd6214f-6978-4dc2-897d-ce2b3b422cd0)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.1
-   Deployment: docker-compose

**Comment by balderekjk** [comment]
That's strange... I don't have that issue in light or dark mode. Are you sure you don't have some custom css applied to it?

**Comment by danclay** [comment]
Looks like this is in a recently merged PR #11271 with a fix, didn't see it in search before. I'll close it
