### ISSUE TITLE
SAML Source Group mapping misbehaviour

### ISSUE THREAD

**Issue by Garfunkl** [goauthentik/authentik#11343]
**Describe the bug**
Probable misbehaving SAML Source Property Mapping for groups

**To Reproduce**
Create Property mapping for groups like this: 
`return {
  'groups': properties.get('memberof', [])
}`

Testing in the Property mapping with the following returns the group name correctly
context:
`{
  "properties": {
    "memberOf": [
      "grp1",
      "grp2"
    ]
  }
}
`
Result:
`{
    "groups": [
        "grp1",
        "grp2"
    ]
}`
Adding it to the saml attribute mapping my test user doesn't join grp1 or 2 but the following groups:
g, p, r, 1
it looks like it interprets the first group as a list of chars and it completely ignores the grp 2 for me. 

**Expected behavior**
User joins grp 1 and grp2

**Screenshots**
Already removed the groups, but can reproduce if needed

**Version and Deployment:**

-   authentik version: 2024.8.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
We weren't able to reproduce this when testing with 1 or multiple groups. Could you use a browser plugin like https://chromewebstore.google.com/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace and capture the raw XML of the SAML request/response and post it here? (Please do censor any kind of personal data before posting it here)

**Comment by Garfunkl** [comment]
I tried to recreate the issue, but it looks like it is working now. Thanks for your help.

**Comment by Garfunkl** [comment]
I tried to recreate the issue, but it looks like it is working now. Thanks for your help.
