### ISSUE TITLE
Webhook Mapping : missing form

### ISSUE THREAD

**Issue by kashikoy** [goauthentik/authentik#11345]
**Describe the bug**
The Webhook Mapping form is missing.

**To Reproduce**

1. Go to 'Customization > Property Mappings'
2. Click on 'Create'
3. Scroll down to 'Webhook Mapping'
4. Click on 'Next'
5. See error

**Expected behavior**
I should have a form with 2 fields : name and expression.

**Screenshots**
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/c91d0381-c42b-4a28-81ee-3c6639d6b3fc">

**Logs**
{"auth_via": "session", "domain_url": "authentik.mydomain.fr", "event": "/api/v3/propertymappings/all/types/", "host": "authentik.mydomain.fr", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 29412, "remote": "192.168.1.2", "request_id": "5f90c7516d824216bc32a50a5400d78a", "runtime": 173, "schema_name": "public", "scheme": "https", "status": 200, "timestamp": "2024-09-11T16:16:21.825521", "user": "adminuser", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"}
{"auth_via": "session", "domain_url": "authentik.mydomain.fr", "event": "/api/v3/propertymappings/all/?managed__isnull=true&ordering=name&page=1&page_size=20&search=", "host": "authentik.mydomain.fr", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 29412, "remote": "192.168.1.2", "request_id": "b1c2c8e4042248a9b048c46718fbac68", "runtime": 205, "schema_name": "public", "scheme": "https", "status": 200, "timestamp": "2024-09-11T16:16:22.285844", "user": "adminuser", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"}
{"auth_via": "session", "domain_url": "authentik.mydomain.fr", "event": "/api/v3/propertymappings/all/types/", "host": "authentik.mydomain.fr", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 39670, "remote": "192.168.1.2", "request_id": "67a521787cf94898a1c91cc56900bff6", "runtime": 742, "schema_name": "public", "scheme": "https", "status": 200, "timestamp": "2024-09-11T16:16:22.891277", "user": "adminuser", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"}
{"auth_via": "session", "domain_url": "authentik.mydomain.fr", "event": "/api/v3/propertymappings/all/?managed__isnull=true&ordering=name&page=1&page_size=20&search=", "host": "authentik.mydomain.fr", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 39670, "remote": "192.168.1.2", "request_id": "3190f15b6e1240c1837673054f18b3a2", "runtime": 118, "schema_name": "public", "scheme": "https", "status": 200, "timestamp": "2024-09-11T16:16:23.081692", "user": "adminuser", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"}
{"auth_via": "session", "domain_url": "authentik.mydomain.fr", "event": "/api/v3/propertymappings/all/types/", "host": "authentik.mydomain.fr", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 39670, "remote": "192.168.1.2", "request_id": "f1de06c96f064e998db2ed3cd6876663", "runtime": 77, "schema_name": "public", "scheme": "https", "status": 200, "timestamp": "2024-09-11T16:16:23.362762", "user": "adminuser", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"}

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.1
-   Deployment: docker-compose

**Additional context**
No.

**Comment by git-day** [comment]
@kashikoy i can confirm the same bug in my instance using the same version.

**Comment by balderekjk** [comment]
Same here.

**Comment by xiaoxi240** [comment]
me too

**Comment by mike6626** [comment]
Can confirm as well
