### ISSUE TITLE
session-end screen doesn't follow settings.theme.base

### ISSUE THREAD

**Issue by levi-jcbs** [goauthentik/authentik#11376]
**Describe the bug**
When I set `settings.theme.base: light` in a brand but the browser is set to dark-theme, authentik does not use the configured light-theme but the browser preferred dark-theme in the session-end screen. This only happens in the session-end screen, everywhere else it's working correctly.

**To Reproduce**

1. Set `settings.theme.base: light` in your current brand
2. Set your browser to dark theme
3. Log out of Application
4. Authentik will use the browser-preferred theme (dark) instead of the configured (light) theme

**Expected behavior**
If `settings.theme.base` is set in the brand's attributes, authentik should follow it everywhere.

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.8.1](https://goauthentik.io/docs/releases/2024.8)
-   Deployment: podman, on the basis of docker-compose

**Comment by BeryJu** [comment]
This is changed with 2024.10 where the session-end page is now also a flow that adheres to the theme
