### ISSUE TITLE
Internal users with social login

### ISSUE THREAD

**Issue by Rdeisenroth** [goauthentik/authentik#11386]
**Describe your question/**
The new 2024.8 update requires internal users for user interface, but what about social login like Google or GitHub? If i have a user that logs in with github and i want them to be able to view the user interface, how would i do that? The release notes state that you can update existing users with `ak change_user_type --all --type internal` but i need this to work when registering users as well

**Relevant info**
happens since 2024.8

**Screenshots**
![image](https://github.com/user-attachments/assets/9926d32d-5da7-457a-baa9-5df36b5977d0)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.1
-   Deployment: docker-compose

**Comment by Rdeisenroth** [comment]
I'd also prefer the option to allow external users to see the dashboard, as the classification into internal and external users was very useful

**Comment by BeryJu** [comment]
you can change the default user type for federation in the user_write stage that's used in the enrollment flow

for separating the users you can use the user path attribute

**Comment by Rdeisenroth** [comment]
Thanks, this works.

**Comment by S33G** [comment]
FYI for future people who come across this post

`https://{{ hostname }}/if/admin/#/flow/stages`
