### ISSUE TITLE
[2024.8.2] (Still) No Applications Listed in Create/Edit Outpost Dialog

### ISSUE THREAD

**Issue by heavymp** [goauthentik/authentik#11384]
**Describe the bug**
Pretty much the same as [11182](https://github.com/goauthentik/authentik/issues/11182). I am unable to get any Apps to show up under the default outpost, or create a new outpost because no apps are available. Also, no apps are shown on the non-admin page for the admin user (not sure if this is a bug)

**To Reproduce**

I have tried 2024.8.2, 2024.8.1, and 2024.8.0 and even though the issues were reported as fixed I am still encountering them.

Try adding apps to the outpost or creating a new outpost.  It is impossible since no apps appear in the list (with or without docker integration). Apps with Providers are set up.

**Expected behavior**
Expect to be able to add apps to outpost 

**Screenshots**
![image](https://github.com/user-attachments/assets/648d1ebe-2b0e-49bf-9d45-3caf1ff4205e)
![image](https://github.com/user-attachments/assets/93351b1a-52c9-4afb-b210-9446b72c771a)
![image](https://github.com/user-attachments/assets/f2814feb-c404-47a4-885b-f2e13d2573ee)
![image](https://github.com/user-attachments/assets/e43074fc-fea2-46d2-890d-43c6cf6e8218)
![image](https://github.com/user-attachments/assets/8380c348-2312-407a-8f3e-532036fd6587)
![image](https://github.com/user-attachments/assets/3de73ae4-c7d6-4fc1-9eb8-2a1d72170cc0)
![image](https://github.com/user-attachments/assets/0b553b1d-5d7c-48c4-900b-9b85ddf95782)

**Logs**
I could not find anything relevant in any log

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.2 (and 2024.8.x)
-   Deployment: docker-compose(portainer stack)

**Additional context**

Probably unrelated but I have also noticed that the docker outpost integration state is always unhealthy when I open/refresh the page, but it works when clicking the refresh button on the page (not browser refresh)

**Comment by heavymp** [comment]
tried ghcr.io/goauthentik/dev-server:gh-version-2024.8 but the problem persists

**Comment by BeryJu** [comment]
Are there any error messages in the browser's developer console?

**Comment by heavymp** [comment]
> Are there any error messages in the browser's developer console?

I have done another fresh install of 2024.8.2. Now Proxy Outpost shows Proxy Provider/app and LDAP Outpost shows LDAP Provider/app in the list. Oauth2/OpenID does not show up in any Outpost, but this may be a misconfiguration on my end. I think it may have been a bug combined with  user error, and when the bug was fixed, only user error remained.

**Comment by rissson** [comment]
You don't need an outpost for oauth2/openid, only for Proxy/Radius/LDAP/RAC. Closing as this appears to be fixed
