### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [goauthentik/authentik#11433]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Authentik application as shown [here](https://elest.io/open-source/authentik). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by fheisler** [comment]
Thanks, we'll look into this and see if it makes sense as an option to highlight for our users! I don't think it belongs in our README at this time.

**Comment by kaiwalyakoparkar** [comment]
I understand, let me know where I can make the addition and I will be happy to do that :)
