### ISSUE TITLE
@

### ISSUE THREAD

**Issue by macOSdmgdaemons** [goauthentik/authentik#11466]
**Describe the idea**

A clear concise description of the idea you want to implement

You're also free to work on existing GitHub issues, whether they be feature requests or bugs, just link the existing GitHub issue here.

If you want to help working on this idea or want to contribute in any other way, react to this issue with a :rocket:

**Comment by CrazyWolf13** [comment]
@authentik-db-cooper @kensternberg-authentik @BeryJu  Guess this can be closed as spam.
