### ISSUE TITLE
Ui

### ISSUE THREAD

**Issue by macOSdmgdaemons** [goauthentik/authentik#11465]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request@unlimited here.
- - [ ] ##[/grook ]()@![image](https://github.com/user-attachments/assets/7e4236cb-aa66-4fc5-8f1a-b37670f612b8)__

**Comment by CrazyWolf13** [comment]
@authentik-db-cooper @kensternberg-authentik @BeryJu  Guess this can be closed as spam.
