### ISSUE TITLE
"Search full LDAP directory" doesn't actually work

### ISSUE THREAD

**Issue by Banh-Canh** [goauthentik/authentik#11548]
**Describe the bug**
"Search full LDAP directory" doesn't actually work.

**To Reproduce**

Add "Search full LDAP directory" permission to a freshly created user/serviceaccount. Then run the query:
```bash
ldapsearch -x -H ldap://<outpost-ldap>:389 -D 'cn=ldapbind,ou=users,DC=ldap,DC=goauthentik,DC=io'  -w 'xxx'  -b 'OU=users,DC=ldap,DC=goauthentik,DC=io' '(objectClass=user)
```
It only returns the binduser.
If I ran the same command after I gave superuser permission to the bind user, it just work and i get the whole directory of users.

**Expected behavior**
I should get the whole directory of user with this permission without superuser rights.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.3
-   Deployment: helm

**Comment by shawnbonifas** [comment]
I'm having the same issue here.  I only just today set up the LDAP application, outpost, provider, flows, etc. so I don't know if it was working previously.  If I use the akadmin account I can search for users and see all of them.  Using the service account I created it can only find itself and the groups it's a member of.  I have tried giving it superuser permission, all LDAP permissions, and all permissions to users the user search still only returns the bind user.  I'm also using 2024.8.3, deployed using the helm template.

**Comment by DrMax1** [comment]
Same issue here. Using the "Search full LDAP directory" permission to the bind user makes the query only return the bind user itself.
After adding the bind user to the superuser group it returns all users in the current authentik instance.

Running 2024.8.3 with docker-compose

**Comment by BeryJu** [comment]
@DrMax1 @shawnbonifas @Banh-Canh are you assigning the search full LDAP directory to the service user within a single provider or globally?

Also try restarting the LDAP outpost after the permissions are assigned, this might be a caching part (it shouldn't but just to rule it out)

**Comment by DrMax1** [comment]
> @DrMax1 @shawnbonifas @Banh-Canh are you assigning the search full LDAP directory to the service user within a single provider or globally?
> 
> Also try restarting the LDAP outpost after the permissions are assigned, this might be a caching part (it shouldn't but just to rule it out)

@BeryJu I am assigning the permission to the service user globally:

![grafik](https://github.com/user-attachments/assets/385dded4-5c6a-4353-ae55-6f964da756cc)

I restarted the LDAP outpost and also set the provider to direct binding and querying to avoid caching issues. 

I also tried downgrading to Version 2024.8.2 but the issue persists.

**Comment by francescor** [comment]
These are the relative commits https://github.com/goauthentik/authentik/pull/10639 

maybe we can solve this by working with  roles?

**Comment by DrMax1** [comment]
> These are the relative commits #10639
> 
> maybe we can solve this by working with roles?

Do you mean creating a role, assigning the "Search full LDAP directory" permission to said role, assigning this role to a group and then adding the relevant service users?

I tried it and it doesn't work either unfortunately. I think there must be an issue with the the permission in the authorization code.

**Comment by francescor** [comment]
I've figured out how to allow a user, in the context of this issue, to "Search full LDAP directory" without the need to make it a superuser (so without make it member of ` authentik Admins`):   as stated in the first comment in https://github.com/goauthentik/authentik/pull/10639 we need to use `object permissions` and not `global permissions` as we all did so far :( 

So you need to have this

![image](https://github.com/user-attachments/assets/1e667009-c105-471a-a441-70ec1f495a18)

which can be accomplish by Application/Provider/Ldap Permissions TAB,  then Assign new User

![image](https://github.com/user-attachments/assets/2d12e2d6-3180-42c3-a7d7-588a098ef35d)


this way we have:

![image](https://github.com/user-attachments/assets/ba1dce09-07c6-47c1-b11e-f60b05c1545b)


Et voilà

**Comment by francescor** [comment]
so I guess this issue can be easily solved just with few words in documentation

**Comment by perrze** [comment]
> I've figured out how to allow a user, in the context of this issue, to "Search full LDAP directory" without the need to make it a superuser (so without make it member of ` authentik Admins`): as stated in the first comment in #10639 we need to use `object permissions` and not `global permissions` as we all did so far :(
> 
> So you need to have this
> 
> ![image](https://private-user-images.githubusercontent.com/424577/378881384-1e667009-c105-471a-a441-70ec1f495a18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTk1NjAsIm5iZiI6MTcyOTc1OTI2MCwicGF0aCI6Ii80MjQ1NzcvMzc4ODgxMzg0LTFlNjY3MDA5LWMxMDUtNDcxYS1hNDQxLTcwZWMxZjQ5NWExOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwODQxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjM5ZGJlNzhjZDVkYzUxNmU5MzFjZWU5OGEzMzJhNWNlODYxMmVmMzMzNDVhZDAzYThiZTcxZmU2NjA5YjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tUp5M5fKm_SQPpHyvEbO8NX81HQcN0Co9_vT4JVG9jY)
> 
> which can be accomplish by Application/Provider/Ldap Permissions TAB, then Assign new User
> 
> ![image](https://private-user-images.githubusercontent.com/424577/378882867-2d12e2d6-3180-42c3-a7d7-588a098ef35d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTk1NjAsIm5iZiI6MTcyOTc1OTI2MCwicGF0aCI6Ii80MjQ1NzcvMzc4ODgyODY3LTJkMTJlMmQ2LTMxODAtNDJjMy1hN2Q3LTU4OGEwOThlZjM1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwODQxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Njc3NTJhYmYwZmZhYTE4ODBlOWQzNjNiNzc0YmRhZmM3ZTFmYzY5MjNlMjdlYmMwYjBlNjg4MjZlNzg0NTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CSl8BknvGoddATUIzeVfBihz-O1ws9UAV6W9ztpBYj8)
> 
> this way we have:
> 
> ![image](https://private-user-images.githubusercontent.com/424577/378882533-ba1dce09-07c6-47c1-b11e-f60b05c1545b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTk1NjAsIm5iZiI6MTcyOTc1OTI2MCwicGF0aCI6Ii80MjQ1NzcvMzc4ODgyNTMzLWJhMWRjZTA5LTA3YzYtNDdjMS1iMTFlLWY2MGIwNWMxNTQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwODQxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDVhYTYyYjM1Y2FmMzJiM2NlZjM3MDg3ZmU3YjYwYzZmZjk2MGFkNGNlN2MyZWVjZTI5MjM5Yjg0MTQyODMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9kzaRkzhGwGK81IZ-9-QoslJjPQRTeAM3YhVTct0JDA)
> 
> Et voilà

When you added the permission, did you need to restart the outpost container ? Because on my instance it was the only way that the permissions would be applied.

**Comment by francescor** [comment]
> When you added the permission, did you need to restart the outpost container ? Because on my instance it was the only way that the permissions would be applied.

no,  but you must be aware of the CACHE which I kept disable till I solve all setup

![image](https://github.com/user-attachments/assets/0d094f83-df05-4736-8f5e-5eb6a8e4f439)

so, with a restart you probably flush caches

**Comment by luckylinux** [comment]
This was driving me crazy on 2025.12.4 🤯.

Setting the Cache to `Direct binding` for both `Bind mode` and `Search mode`, followed by a Restart of the Docker Container for the LDAP Outpost, finally let OPNSense authenticate with the Service Account 👍.

Unfortunately this was not mentioned anywhere in the Tutorial 😕:
https://integrations.goauthentik.io/networking/opnsense/

Maybe as @perrze and @francescor mentioned restarting the Container for the LDAP Outpost might be sufficient.

But as @francescor also mentioned, we must be aware of the Cache Setting.

Old Issue, but still relevant I would say, at least in Terms of (lack of) Documentation.
