### ISSUE TITLE
Default LDAP Outpost does not properly handle all incoming traffic

### ISSUE THREAD

**Issue by Starz0r** [goauthentik/authentik#1161]
I originally tried to debug this issue in the chat room, but were unable to nail down the issue. Decided that this bug should be properly documented for the future in case it's ran into again or solved, this ticket can exist on the status of the bug.

Currently, if you set up an LDAP Outpost on Kubernetes with the default settings, expose it through the Ingress and  Cloud Load Balancer, attempting to authenticate through it will fail.

1. Setup Authentik on Kubernetes via Helm or otherwise.
2. Create an LDAP Outpost with the default settings.
3. Attempt to connect to the outpost via ApacheDS or any other standards compliant client.

Authentication should succeed under normal circumstances (Correct Base DN, Correct Password, etc...).

This error message shows up in the logs when trying to connect normally, or perform a simple bind. Nothing appears to show up if trying to connect without TLS, so I will assume it simply isn't supported. However, this message also shows up when trying to connect with TLS, but if you do not perform a simple bind, it appears that the outpost will send a message back, allowing the client to connect, despite the error message saying the packets do not look like a TLS handshake.
```
2021/07/20 06:53:56 handleConnection ber.ReadPacket ERROR: tls: first record does not look like a TLS handshake
```

 - authentik version: git-master-89fafff0af
 - Deployment: helm

**Comment by BeryJu** [comment]
Hi, could you maybe run `tcpdump` while connecting to the LDAP Outpost? Ideally for both a plain bind and an SSL bind (plain binds are fully supported, on port 389).

Also you said you were running on Digital Ocean, using their Loadbalancers, right? What settings are you using for that? I'd like to try and re-create that setup to debug the issue.

**Comment by Starz0r** [comment]
Just connect while running `tcpdump`? No fancy flags needed?

Default settings on the DigitalOcean load balancer, with the exception that the Proxy Protocol is enabled.

**Comment by BeryJu** [comment]
Yeah just connect with tcpdump running, and save it to a pcap file to upload somewhere.

**Comment by BeryJu** [comment]
So, the proxy protocol is indeed the troublemaker here. I'll have a look if its possible to implement this

**Comment by Starz0r** [comment]
@BeryJu Huh? That's interesting, it shouldn't be if you are using TCP Services to strip it out?
```yml
  '389': 'default/ldap:389:PROXY-V1:'
```
At least I thought this would stand to mean: Match where service `ldap` in `default` namespace, on port `389`, unwrap `PROXY-V1` into `Bare TCP Packets`. Maybe my assumption is wrong?

**Comment by Starz0r** [comment]
After disabling the Proxy Protocol on the LB for a quick test, it does indeed seem to be the troublemaker. I have no clue why this would be the case since, I assumed it would be stripped out by the time it reaches the Pod, but it isn't, which makes no sense.

**Comment by BeryJu** [comment]
Thats what I thought too, but it works with proxy disabled and doesn't with it enabled.

In the packet dump I created, you can see the LDAP packets, but I don't see anything about the proxy protocol, no idea if wireshark simply can't show it or there's something else wrong.

**Comment by BeryJu** [comment]
With the changes from the last commit I was successfully able to connect to LDAP with the PROXY protocol enabled.

I think the authentik LDAP Server might be the only one that supports the PROXY protocol 😄
