### ISSUE TITLE
Traefik/Authentik Video - accessing authentik over http rather than https

### ISSUE THREAD

**Issue by HeneryH** [goauthentik/authentik#11661]
**Describe your question/**
I noticed early in my testing that I could only access Authentik using its https port (7443 in my case since 8443 was taken by Portainer). Port 7000 (to keep with the 7xxx theme being Authentik) didn't connect. It was no problem in my early testing as the internally signed certificate gave me a sense of progress.

COMPOSE_PORT_HTTP=7080
COMPOSE_PORT_HTTPS=7443

But now I am trying to use Traefik's LE certs which will then route to the http port of Authentic, which doesn't work form me.

Have you ever seen Authentik fail to accept http connection requests before? Maybe some setting to allow less secure? I used the two port settings and env variables to set them. My https works but no my http:

>   server:
>     image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.8.3}
>     container_name: authentik-server
>     restart: unless-stopped
>     command: server
>     environment:
>       AUTHENTIK_REDIS__HOST: redis
>       AUTHENTIK_POSTGRESQL__HOST: postgresql
>       AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
>       AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
>       AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
>       AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?error}
>     volumes:
>       - ./media:/media
>       - ./custom-templates:/templates
> x    env_file:
> x      - .env
>     ports:
>       - "${COMPOSE_PORT_HTTP:-9000}:9000"
>       - "${COMPOSE_PORT_HTTPS:-9443}:9443"
>     labels:
>       traefik.enable: true
>       traefik.http.routers.server.rule: Host(`auth.my_domain.com`)
>       traefik.http.routers.server.entrypoints: websecure
>       traefik.http.services.server.loadbalancer.server.port: 7000
>       traefik.http.routers.server.tls: true
>       traefik.http.routers.server.tls.certresolver: production
>     depends_on:
>       - postgresql
>       - redis

**Relevant info**
Uhg, how do you format yaml code so that it shows well here in posts?  My formatting attempts have not worked.

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
-   Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by HeneryH** [comment]
Temporarily closing while I investigate more.

**Comment by mdeanda** [comment]
Having the same issue temporarily while its being investigated:

![Image](https://github.com/user-attachments/assets/90d6d001-f3f9-45b0-bede-b660f21cb80d)

I'm running it via docker and behind NPM proxy.
