### ISSUE TITLE
Application authorization `permission denied` shows the wrong background image

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [goauthentik/authentik#11666]
**Describe the bug**
Application `permission denied` shows the wrong background image.

**To Reproduce**

1. Create and bind a policy to an application.
2. Go to the application from an external link / URL typing.
3. Login with a user that doesn't have access.

**Expected behavior**
I see the background from `default-provider-authorization-implicit-consent` (or any other customizable flow)

<img width="1135" alt="Screenshot 2024-10-13 at 12 56 33 AM" src="https://github.com/user-attachments/assets/bc66ca9b-c075-433a-a641-b649d0083b93">

**Actual**
I see the default authentik `flow_background` background.

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/1086e685-edb3-41ff-8fc8-92377b2c6787">

**Version and Deployment (please complete the following information):**
- authentik version: 2024.8.3
- Deployment: docker-compose
- URL: `https://mysever.url/application/o/authorize/...`

**Comment by lokas88** [comment]
Also having the same issue despite changing my aithentication flows. Is this a bug or does something else need to be configured?

**Comment by mehdimansouriut** [comment]
same error here

**Comment by dewi-tik** [comment]
This should be fixed in the next update. See PR #13079

**Comment by jimbytes** [comment]
Hi,
this still happening in version 2025.10 for me.
