### ISSUE TITLE
"Get started" Button link faulty

### ISSUE THREAD

**Issue by sandboxcode** [goauthentik/authentik#11667]
**Describe the bug**
Button onClick link on is not valid at https://docs.goauthentik.io/docs/installation/. 
I'm sorry, if this is not the right place for bugs for the homepage / documentation.

<img width="539" alt="image" src="https://github.com/user-attachments/assets/f79007db-86b9-40df-9b7e-16123efca0ed">

**To Reproduce**

1. Go to https://goauthentik.io/
2. Click on 'Get started'
4. See error (https://docs.goauthentik.io/docs/installation/)

**Expected behavior**
On button click should either lead to https://docs.goauthentik.io/docs/ or https://docs.goauthentik.io/docs/install-config/install/docker-compose

**Screenshots**
See before

**Logs**
None

**Comment by BeryJu** [comment]
this is fixed now

**Comment by sandboxcode** [comment]
Top, auch danke für die schnelle Rückmeldung @BeryJu !
