### ISSUE TITLE
Bug: Get Started Button

### ISSUE THREAD

**Issue by scheibling** [goauthentik/authentik#11675]
**Describe the bug**
Couldn't find a specific repo for the website (goauthentik.io), the "Get Started" button on frontpage redirects to https://docs.goauthentik.io/docs/installation/ instead of https://docs.goauthentik.io/docs/install-config/ which seems to be the new link

**To Reproduce**

1. Go to https://goauthentik.io
2. Click on 'Get Started'
3. See error 
4. Open Github Issue
5. Fetch coffee

**Expected behavior**
The button leads to the https://docs.goauthentik.io/docs/install-config/ page

**Screenshots**
![image](https://github.com/user-attachments/assets/f4968afc-e89d-4623-a54f-98fb58f260d5)
![image](https://github.com/user-attachments/assets/acf0045e-37a4-497c-b050-19958630d3e9)
![image](https://github.com/user-attachments/assets/7145568d-1c1c-4818-a940-4bb62011e8f4)

**Logs**
-

**Version and Deployment (please complete the following information):**
- goauthentik.io version 2024.10.14:11:18:40

**Comment by BeryJu** [comment]
Fixed, thanks!
