### ISSUE TITLE
Authentik Automaticaly logout when Login

### ISSUE THREAD

**Issue by itsmejomijohn** [goauthentik/authentik#11713]
**Describe the bug**
Authentik Automaticaly logout when Login. i am using docker to host authentik. first time everything is working fine, but when i restarted the server and try to login to authentik, it is suddenly logout automaticaly. i tried with three diffrent servers all the time the same issue is occured, some time after login, showing error like failed to fetch objects, failed to fetch data are showing, some times workers are showing error

**To Reproduce**

1. Go to 'Login Screen'
2. Authenticate
3. then automatcialy authentik os logout

**Expected behavior**
sudden logout after login, some time showing error like "failed to fetch objects", "failed to fetch data", and sometime workers shoeing error

**Screenshots**
![Screenshot 2024-10-17 232823](https://github.com/user-attachments/assets/ddd7edba-bcf5-4094-9d68-66cc77f0c70f)
![Screenshot 2024-10-17 232854](https://github.com/user-attachments/assets/76c06655-2fe3-4d51-9d0e-0afc23783107)
![Screenshot 2024-10-17 232921](https://github.com/user-attachments/assets/d1dedbad-8b72-49fd-a355-aafe2b819a04)
![Screenshot 2024-10-17 232948](https://github.com/user-attachments/assets/e6cf6e12-4a47-482f-a26d-4da37d6cdbd1)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.3
-   Deployment: docker-compose

**Comment by MattiaPun** [comment]
@itsmejomijohn have you found a fix for it? I seem to be having the same issue

**Comment by rissson** [comment]
Someone in a different issue said that this might be caused by faulty connectivity to redis.

**Comment by theMaxtor** [comment]
Same issue here and I could not find anything related in the logs

**Comment by itsmejomijohn** [comment]
@theMaxtor please share your docker compose file
