### ISSUE TITLE
Password field is auto-selected on login flow

### ISSUE THREAD

**Issue by MrMeeb** [goauthentik/authentik#11745]
**Describe the bug**
When loading a login flow that shows both a username and password field, on page load the password field is auto-selected:

I believe this happened somewhere after 2024.8 - I noticed it when upgrading to 2024.8.2.

Looking at the HTML, I noticed that the `ak-stage-password-input` field has `autofocus` added to it. I guess this is what's causing the behaviour:

```html
<form class="pf-c-form">
                    <!--?lit$426086962$--><p>
                              <!--?lit$426086962$-->Login to continue to Grafana.
                          </p>
                    <!--?lit$426086962$--><!--?lit$426086962$-->
            <ak-form-element required="" class="pf-c-form__group" label="Email or Username" theme="dark">
                <input name="uidField" autofocus="" autocomplete="username" class="pf-c-form-control" required="" aria-invalid="false" type="text" placeholder="Email or Username">
            </ak-form-element>
            <!--?lit$426086962$-->
                      <ak-flow-input-password inputid="ak-stage-identification-password" required="" class="pf-c-form__group" label="Password" prefill=""><!----> <ak-form-element required="" class="pf-c-form__group" label="Password" theme="dark">
            <div class="pf-c-input-group">
                <!--?lit$426086962$--><input id="ak-stage-password-input" type="password" name="password" placeholder="Please enter your password" autofocus="" autocomplete="current-password" class="pf-c-form-control" required="">
                <!--?lit$426086962$-->
            </div>
        </ak-form-element></ak-flow-input-password>
                  
            <!--?lit$426086962$-->
            <div class="pf-c-form__group pf-m-action">
                <button type="submit" class="pf-c-button pf-m-primary pf-m-block">
                    <!--?lit$426086962$-->Log in
                </button>
            </div>
            <!--?lit$426086962$--><!--?-->
                    <!--?lit$426086962$-->
                </form>
```

**To Reproduce**

1. Setup the default-authentication-identification stage to use default-authentication-password as a Password stage
2. Launch the default-authentication-flow
3. Obseve that the password field is pre-selected, not the username field.

**Expected behavior**
I would expect the username field to be auto-selected since it's the first field in the form

**Screenshots**
![image](https://github.com/user-attachments/assets/f1983c72-4f5c-48b6-b2e8-f7f277ba4086)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.3
-   Deployment: docker-compose

**Additional context**
I am running a `custom.css`, but it does nothing to the form boxes, and the issue is still present after removing it.

**Comment by BeryJu** [comment]
this was fixed by #10593
