### ISSUE TITLE
LDAP Source with Active Directory produces configuration_error events

### ISSUE THREAD

**Issue by B4dM4n** [goauthentik/authentik#11763]
**Describe your question**

I'm trying to setup an LDAP Source connected to Active directory based on the official [documentation](https://docs.goauthentik.io/docs/users-sources/sources/directory-sync/active-directory/). 
The connection to the AD server is established correctly and users are being created in authentik. 

But group synchronization produces `configuration_error` events and emails for each AD group:

```json
{
    "dn": "CN=Domain Users,CN=Users,DC=corp,DC=example,DC=com",
    "source": {
        "pk": "fb2f699533ce47e8ad64b4b3fcb23c2c",
        "app": "authentik_sources_ldap",
        "name": "corp.example.com",
        "model_name": "ldapsource"
    },
    "message": "Failed to create group: Group() got unexpected keyword arguments: 'username', 'path', 'email' To merge new group with existing group, set the groups's Attribute 'ldap_uniq' to 'S-1-5-21-123456789-123456789-123456789-123'"
}
```

I tried to remove these unexpected attributes with the following property mapping, but the error is still the same:
```python
return {
  "username": None,
  "email": None,
  "path": None,
}
```

In an attempt to find a solution, I patched the `GroupLDAPSynchronizer` and removed the fields by hand. 
```patch
diff --git a/authentik/sources/ldap/sync/groups.py b/authentik/sources/ldap/sync/groups.py
index ae972b605..9fe969f44 100644
--- a/authentik/sources/ldap/sync/groups.py
+++ b/authentik/sources/ldap/sync/groups.py
@@ -82,6 +82,12 @@ class GroupLDAPSynchronizer(BaseLDAPSynchronizer):
                 # Special check for `users` field, as this is an M2M relation, and cannot be sync'd
                 if "users" in defaults:
                     del defaults["users"]
+                if "username" in defaults:
+                    del defaults["username"]
+                if "path" in defaults:
+                    del defaults["path"]
+                if "email" in defaults:
+                    del defaults["email"]
                 ak_group, created = Group.update_or_create_attributes(
                     {
                         f"attributes__{LDAP_UNIQUENESS}": uniq,
```

This fixed the issue and the groups where successfully created.

So my question is, why didn't the property mapping remove the fields?
Based on the [documentation](https://docs.goauthentik.io/docs/users-sources/sources/property-mappings/#:~:text=If%20a%20property%20mapping%20sets%20one%20attribute%20to%20None%2C%20that%20attribute%20is%20then%20discarded.) (and source code), I would expect the fields to be removed when set to `None`.

Is there another way to remove theses unwanted fields?

**Screenshots**

LDAP Source configuration:
![LDAP Source configuration](https://github.com/user-attachments/assets/3abdff3e-d623-40e0-bff5-41d48103296f)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.3
-   Deployment: docker-compose

**Additional context**

AD is a Windows Server 2016

**Comment by LargoUsagi** [comment]
I can also confirm this behavior, Fresh install of 2024.8.3 via helm in k8s v1.30.4+rke2r1

**Comment by slrz** [comment]
Pretty sure this is due to having configured user-specific property mappings for groups, in particular those that return `username`, `path` and `email` properties (which are not suitable for groups).

**Comment by LargoUsagi** [comment]
Yeah for me, it was different fields, but updating the group mapping to this resolved my issues.
![image](https://github.com/user-attachments/assets/a7c1cbb7-76df-4e87-ae55-bf5cb077c00c)

**Comment by LargoUsagi** [comment]
@B4dM4n See my post above and check if changing to that fixes your issues.

**Comment by lsjostro** [comment]
@LargoUsagi good catch! works in our env! ✨

**Comment by B4dM4n** [comment]
I can't believe I missed the default mappings that added these fields.

Removing them also fixed the problem for me.

Thanks for the help.

**Comment by sunmetis** [comment]
Hi :) working on this over 2 days ... Cannot sync groups . Did as shown above . Nothing to do . Need you guys ..
