### ISSUE TITLE
Error - SAML payload is missing

### ISSUE THREAD

**Issue by 0xff8** [goauthentik/authentik#11859]
**Describe your question/**
I run into a problem when configuring SAML auth for hubspot. Whenever I attempt to test setup in HubSpot settings - I see the error: `Saml payload is missing` . I assume the problem is on my side (may be ingress or misconfiguration of authentik), but I need someone to help me. The authentik is installed via helm. 
I have attached the web requests on the client and on the server. They look the same to me. 

**Relevant info**
I use authentik 2024.8.3 installed on k8s with helm chart. 

**Screenshots**
Screenshot of the request in the browser:
<img width="557" alt="image" src="https://github.com/user-attachments/assets/e0ba0cce-23dd-4055-ab10-1788550ceef1">
<img width="956" alt="Bildschirmfoto 2024-10-30 um 12 15 31" src="https://github.com/user-attachments/assets/1cfd93f2-1ecc-46cd-bc79-e852bf74dec4">
<img width="741" alt="Bildschirmfoto 2024-10-30 um 12 07 58" src="https://github.com/user-attachments/assets/df30dd1f-a155-4b06-8974-251257e30020">

**Logs**
```
{"auth_via": "session", "domain_url": "authentik.XXXXX", "event": "SAML payload missing", "host": "authentik.dmz.comforte.cloud", "level": "info", "logger": "authentik.providers.saml.views.sso", "pid": 42, "request_id": "b3abf22ce8ee45fb874ce0bbd03cc174", "schema_name": "public", "timestamp": "2024-10-30T10:46:58.157195"}
{"auth_via": "session", "domain_url": "authentik.XXXXXX", "event": "/application/saml/hubspot/sso/binding/post/?SAMLRequest=jZJbbxoxEIX%2FysrvXnsvQLBYKhp6WYkCCrQPfamM7QSrXtv1eNO0v75moRJRlaivZ3yO5zuaGfDOeLbo49HeqR%2B9gpg9dcYCGwYN6oNljoMGZnmngEXBdotPK1bmlPngohPOoCvL6w4OoELUzqKsXTZos3632nxo19%2FooZ5WlFa4qOkI1%2BpmiqdVKXFZCTE%2BFJLeTEYo%2B6ICJG%2BDUlQKAOhVayFyG5NEyxoXFFd0X1BWj9lo8hVly8SjLY%2BD6xijB0YIT7DKRv09l93vXLju3oWocmFcLwn33mgxOMiJhxz7A3gXCYAjB22ltg%2FEO4gEZdsL%2F9uz%2FDr6xQvs436%2FxdvNbo%2Byxd86bp2FvlNhp8KjFurz3epqXa%2FzyxKnZYlxD9ripJLH4rwiF%2FDGJwZuWtnUtByPpxM0n51mbGgpzP8%2FbFD%2BiZuR67TZ%2BWrWCbJdbl0q7Ff23oWOx5c7KPJiULTE98NTpjquzULKoABSF8a4n7dB8agaFEOvUEbm52%2Bf3%2Bf8Dw%3D%3D&RelayState=%7B%22loginEmail%22%3A%22s.lomakov%40comforte.com%22%2C%22loginType%22%3A%22CONFIRMATION%22%2C%22redirect%22%3A%22https%3A%2F%2Fapp.hubspot.com%2Fsettings-sso-confirm%3FportalId%3D4026697%22%2C%22destinationPortalId%22%3Anull%2C%22rememberLogin%22%3Afalse%2C%22clientType%22%3A%22HUBSPOT%22%7D", "host": "authentik.XXXXX", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 42, "remote": "172.16.127.66", "request_id": "b3abf22ce8ee45fb874ce0bbd03cc174", "runtime": 117, "schema_name": "public", "scheme": "https", "status": 400, "timestamp": "2024-10-30T10:46:58.251631", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0"}
```
**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.3
-   Deployment: helm

**Additional context**

**Comment by 0xff8** [comment]
Problem was solved.

**Comment by jamie-dit** [comment]
Hey @0xff8, How did you manage to fix this? Currently facing this issue and I've spent all week trying to fix it.

Version:  2024.10.4

Thanks

**Comment by andrewjhayes** [comment]
@jamie-dit  Did you ever figure this out? I am using POST binding and SHA-256 just like Hubspot recommends, but I am getting the Bad Request on verification still.

**Comment by andrewjhayes** [comment]
@jamie-dit I figured it out. I am going to post here in case you or anyone else need it:

=== Configuring Authentik for HubSpot ===

Authentik Config:
ACS URL: https://api.hubspot.com/login-api/v1/saml/acs?portalId=<hubspot-account-id>
Issuer: https://<authentik_domain>/source/saml/<hubspot_slug>/
SP Binding: POST
Audience: https://api.hubspot.com/login-api/v1/saml/login?portalId=<hubspot-account-id>

Signing Cert: <your-authentik-cert>
Sign assertions: Enabled
Sign responses: Enabled
NameID Propery Mapping: Email
Digest algo: SHA256
Signature algo: RSA-SHA256

Download the metadata and make the following transformations:

1. Delete SingleLogoutService.
2. Delete any NameIDFormat except for emailAddress.
3. HERE'S the real trick: Copy the Location attribute from the REDIRECT element. Paste it into the Location attribute on the POST binding element. Delete the REDIRECT element.

Upload the metadata and test. This is work.


Here's why this works: HubSpot requires HTTP-POST as their SAML binding, but it then responds with Redirect. Some SSO providers use the same URL scheme for both redirect and post on the IDP side, HubSpot makes the assumption that's the case with every IDP, but it is incorrect.
