### ISSUE TITLE
Error Redirect URI after update from 2024.10.2 to 2024.10.3

### ISSUE THREAD

**Issue by mathieuruellan** [goauthentik/authentik#12137]
**Describe the bug**
I've just updated. Now when i access to a protected website, i've got this error:

![image](https://github.com/user-attachments/assets/72db286c-f506-4d1a-8185-a526fbeaeb30)

I've changed anything in parameters, only the docker tag version. 

Logs:
`
{"auth_via": "session", "domain_url": "authentik.breizh-biniou.fr", "event": "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).", "host": "authentik.breizh-biniou.fr", "level": "warning", "logger": "authentik.providers.oauth2.views.authorize", "pid": 195, "request_id": "2a66ed5bdc304321a8270fc976449d3b", "schema_name": "public", "timestamp": "2024-11-21T18:01:08.062042"}`

**Comment by mathieuruellan** [comment]
duplicated with: https://github.com/goauthentik/authentik/issues/12136

**Comment by BeryJu** [comment]
duplicate of #12135
