### ISSUE TITLE
Bug in the Redirect URIs/Origins field box

### ISSUE THREAD

**Issue by Marcus1Pierce** [goauthentik/authentik#12155]
**Describe the bug**
"There is a bug when trying to edit the domain in Redirect URIs/Origins. Once the URIs are entered, the box disappears.

**To Reproduce**

1. Go to 'Admin Interface'
2. Click on 'Applications > Providers'
3. Edit any 'Providers'
4. Enter the URIs in the 'Redirect URIs/Origins' section.
5. After that, click enter or update, and the URIs will disappear.

**Expected behavior**
The URIs are saved as entered.

**Screenshot**
Enter the URIs here.
![1](https://github.com/user-attachments/assets/e55aac1b-de94-493f-be06-a305443df248)

And after clicking enter, update, or Add entry, the box disappears and the URIs are not saved. Some of my Providers also suddenly disappear from the Providers/URIs column.
![2](https://github.com/user-attachments/assets/36d89395-1a9c-4437-81b9-0a5950f3f418)

**Logs**

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.6
-   Deployment: docker-compose

**Additional context**

**Comment by tobias-urdin** [comment]
Same here.

**Comment by Marcus1Pierce** [comment]
@tobias-urdin well, no luck for me. I realized this bug after I upgraded to 2024.8.6. I've tried several browsers, but it's still the same.

**Comment by francescor** [comment]
same for us

we are stuck!

**Comment by francescor** [comment]
our issue was that this morning we upgrade to 2024.10.4 from 2024.10.3

We've read release notes
https://docs.goauthentik.io/docs/releases/2024.10#fixed-in-2024104

and since it is only talking about bug issue (plus is a minor upgrade), we did not check functionality extensively.

But apparently the new Redirect/Uri otion was set to Strict (while we where using a regexp), so it broke applications.

We've fixed it by changing the combo to "Regexp"

**Comment by francescor** [comment]
@Marcus1Pierce we had the same your behaviour when we reverted back from 2024.10.3 to  2024.10.4 

then we went back to  2024.10.4 and we where able to add (and save) the content

**Comment by Marcus1Pierce** [comment]
There is a new update on 2024.8.6, and now I can add new URIs in that field box again.

**Comment by rknightion** [comment]
This just happened again for us! - latest update switched everything from regex back to strict again :(
