### ISSUE TITLE
Error trying to impersonate

### ISSUE THREAD

**Issue by MelvinCou** [goauthentik/authentik#12163]
**Describe the bug**
There is a error when I try to impersonate. Last time I tryied was probebly in 2024.08 version and it worked perfectly.

**To Reproduce**

1. Go to Admin interface > Directory > Users
2. Click on 'impersonate' on any user
3. See error

**Expected behavior**
No error.

**Screenshots**

![image](https://github.com/user-attachments/assets/9ac8c966-2474-46e9-bb08-b8cb94037413)

```
RequiredError: Required parameter requestParameters.impersonationRequest was null or undefined when calling coreUsersImpersonateCreate
```

**Logs**
No logs, no http request.  
Error is in the frontend.  

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.10.4
-   Deployment: docker-compose

**Comment by joestump** [comment]
Just ran into this myself. 

```
RequiredError: Required parameter requestParameters.impersonationRequest was null or undefined when calling coreUsersImpersonateCreate.
```

**Comment by Yaya48** [comment]
Same here

**Comment by Retract1822** [comment]
Same. I can confirm it was working in 2024.10.2

**Comment by Whidix** [comment]
Same here

**Comment by Videothek** [comment]
Same here

**Comment by djooberlee** [comment]
Same

on version 2024.10.2 impersonate works as it should,
but on versions 2024.10.3 and 2024.10.4 it doesn't

**Comment by mike-jl** [comment]
Is there a workaround for the time being?

**Comment by BeryJu** [comment]
@mike-jl you can use ghcr.io/goauthentik/dev-server:gh-version-2024.10
