### ISSUE TITLE
impersonationRequest undefined when starting impersonation

### ISSUE THREAD

**Issue by sleepy-nols** [goauthentik/authentik#12187]
**Describe the bug**
Authentik is giving an error when trying to impersonate an user.
```
RequiredError: Required parameter requestParameters.impersonationRequest was null or undefined when calling coreUsersImpersonateCreate.
```

**To Reproduce**
1. Go to `users`
2. Click on `impersonate` on a user

**Expected behavior**
Impersonation successfully starts

**Screenshots**
n/a

**Logs**
nothing is logged when pressing the button

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2024.10.4]
-   Deployment: docker-compose

**Additional context**
n/a

**Comment by justinpretorius** [comment]
also seeing this on 2023.10.4

**Comment by MelvinCou** [comment]
Duplicate of #12163

Fixed in #12184

I am waiting for a new release before closing my issue.

**Comment by jamie-dit** [comment]
Issue still happening on 2024.10.4

**Comment by sleepy-nols** [comment]
will be fixed in the next release, see above

**Comment by sleepy-nols** [comment]
24.10.5 is out, which fixes this issue
