### ISSUE TITLE
fix ULA range not in AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS by default

### ISSUE THREAD

**Issue by BPplays** [goauthentik/authentik#12193]
according to [the docs](https://version-2023-6.goauthentik.io/docs/installation/configuration#listen-setting) fc00::/7 is not in AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS by default i feel like it should because all types of local ipv4 addresses except 100.64.0.0/10 are included

**Comment by BeryJu** [comment]
makes sense to me but it's been a while since I've done anything ipv6 related, thoughts @rissson?

**Comment by rissson** [comment]
The thing is the ULA config is not included for the same reason 100.64/10 isn't. You might encounter those subnets outside your local network, or at least it's more likely than those from RFC1918. You also probably don't want to authorize the whole of fc00::/7, but only the relevant /48 or /64. As this option is configurable, I don't think we should add that subnet.

**Comment by BPplays** [comment]
@rissson then maybe a better solution is putting more notes about it in the docs,
like [the documentation on reverse proxies](https://docs.goauthentik.io/docs/install-config/reverse-proxy) doesn't even mention it even though it'll cause all client IPs to be wrong

**Comment by rissson** [comment]
Agreed

**Comment by rissson** [comment]
If you want to open a PR, feel free to, otherwise I'll probably get around to this next week
