### ISSUE TITLE
Can't copy AUTHENTIK_TOKEN from Outpost Deployment Info

### ISSUE THREAD

**Issue by abmurksi** [goauthentik/authentik#1219]
**Describe the bug**
I want to craete a manual outpost proxy deployment and need the AUTHENTIK_TOKEN to set in the Outpost Proxy.
When viewing the deployment info and clicking on "Click to copy token" I get this error-message:

"TypeError: e.json is not a function"

and no Token is copied to the clipboard and I see no other way to get the necessary token.

**To Reproduce**
I deployed Authentik on Hashicorp Nomad with multiple nodes, therefore I need to deploy a manual Outpost. As this is within an isolated network, no TLS is used, HTTP only.
I am following the *arr Provider Tutorial from here: https://goauthentik.io/docs/integrations/services/sonarr/index

1. Create new Outpost Type Proxy, Insecure True, No service connection
2. View Deployment Info
3. Click "Click to copy token"
4. See Error Message: TypeError: e.json is not a function

Same error also appears when trying to copy the token from Identity&Cryptography - Tokens

**Expected behavior**
The token is copied to the clipboard (or any other way to get the token)

**Logs**
DOCKER:
{"event": "/api/v2beta/core/tokens/ak-outpost-dc4bbdaa-170f-4e3b-aed8-a53730325161-api/view_key/", "host": "192.168.1.205", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 29, "request_id": "fc09e0c62f4a47ab85b7567eb828d6fd", "runtime": 42, "scheme": "http", "size": 0.066, "status": 200, "timestamp": "2021-08-04T09:11:37.460206"}

Browser Console (Firefox 90.0.2, 64bit, Linux Mint - 1.0):
Error: Please use $(ref:runtime.getURL). backgroundLogic.js:25
    getExtensionInfo moz-extension://d5da3f7d-30d7-48bc-ae57-bed548637633/js/background/backgroundLogic.js:25

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.7.2
 - Deployment: Hashicorp Nomad (with Docker)

**Comment by owenfiscus** [comment]
Not an issue in Chrome for me, only in Safari

**Comment by enicck** [comment]
Does **not** work for me neither in Chrome, nor Firefox, nor Safari. 
So there is basically no way to get your outpost token on a Mac.
Steps to reproduce are the same as in the original report. 

System: macos Monterey 12.0.1

Firefox (v 93.0 and v 94.0.1): 
`Uncaught (in promise) TypeError: t.json is not a function`

Chrome (v 96.0.4664.55):
`Uncaught (in promise) TypeError: t.json is not a function`

Safari (v 15.1 (17612.2.9.1.20)):
`TypeError: undefined is not an object (evaluating 'navigator.clipboard.write')`

**Comment by BeryJu** [comment]
@enicck Which version authentik are you running? The safari bug should be fixed by now (you should at least get the same error on all platforms)

**Comment by enicck** [comment]
I'm using 2021.10.4 but changing the image tag in docker-compose to "latest" fixed the issue. 
Thank you!

**Comment by BeryJu** [comment]
Interesting, seeing as the :latest tag is 2021.10.4, so I suspect something old was cached.

Re API: indeed you can do that, you can also open `/api/v3/` to get a full API browser

**Comment by Angstroem** [comment]
I've run into the same issue with the copy button, when pressed it just does not copy anything into the clipboard. But i managed to get the key manually from this API: `api/v3/core/tokens/ak-outpost-<outpost-id-here>-api/view_key/`. 

The ID of the outpost can be read from the list of tokens at `api/v3/core/tokens/

**Comment by ZaxLofful** [comment]
I also have this issue, I will try and use the location mentioned in the comment above to get my token
