### ISSUE TITLE
Cannot change user details

### ISSUE THREAD

**Issue by AminSaqi** [goauthentik/authentik#1227]
**Describe the bug**
Logged-in users can't change their user details. An empty error message appears on attempting to update.

![error](https://user-images.githubusercontent.com/39796124/128349660-a8ac6afa-b4d6-491b-9e0c-e40b8b00c788.jpg)

**To Reproduce**
1. Sign in to authentik with a user.
2. Go to `/if/admin/#/user;page-details`.
3. Try to update user details.
4. You'll see an error like the above screenshot.

**Expected behavior**
User should be able to update his/her info.

**Logs**
There is NO log in events page or notification sidebar.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.7.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Can you check in the browser console if there are any errors in there?

**Comment by AminSaqi** [comment]
Yes. A `403 Forbidden` on `PUT /api/v2beta/core/users/<id>/` and a `Promise` error.

![error1](https://user-images.githubusercontent.com/39796124/128350886-7a41b878-0116-4cf9-b53a-3b7f1b84aa6d.jpg)

**Comment by RixzZ** [comment]
Seems like is still happening. I'm currently on 2021.8.3 (clean install) and have the same exact error.

**Comment by BeryJu** [comment]
@RixzZ can you post a Screenshot of your browser console? I'm not able to reproduce it

**Comment by RixzZ** [comment]
@BeryJu Of course. Looking at it now, is not exactly like the screenshot before, but occurs when doing the same as OP.

FYI I'm trying to change the username and name of the 'akadmin' user. I don't know if that matters.

![Screenshot from 2021-09-02 18-17-02](https://user-images.githubusercontent.com/1339272/131880287-80092913-e678-48fc-b940-85d793283b10.png)

**Comment by RixzZ** [comment]
Sorry for the trouble, it was a problem on my setup.

Authentik is behind Traefik in my setup, where I had set referrerPolicy to 'no-referer'. I saw another section giving an error with 'CSRF Failed: Referer checking failed - no Referer.' on details. After fixing that, this also was resolved.
