### ISSUE TITLE
`CONN_MAX_AGE` should default to 0 when pgBouncer is enabled

### ISSUE THREAD

**Issue by fullykubed** [goauthentik/authentik#12278]
**Describe the bug**

Adding pgBouncer as a proxy between Authentik and PostgreSQL make it significantly cheaper to open new db connections.

However, Authentik's current behavior is to make connections persistent rather than ephemeral when PgBouncer is enabled. See [code](https://github.com/goauthentik/authentik/blob/104e70c38385b411bc6e4ed538825ded7801f6a9/authentik/root/settings.py#L310).

It should be the opposite. Use short-lived connections when pgBouncer is enabled and use long-lived connections when pgBouncer is not used. Otherwise the entire point of using pgBouncer is defeated.

Moreover, the current settings will cause issues with the out-of-the-box pgBouncer settings as reported previously:

- #9152
- #10159 

**To Reproduce**

N / A

**Expected behavior**

The linked line shold be:

```python
DATABASES["default"]["CONN_MAX_AGE"] = 0
```

as connections should be short-lived when pgBoucner is enabled.

Additionally, I'd recommend making the default (non pgBouncer behavior) the following:

```python
DATABASES["default"]["CONN_MAX_AGE"] = None
```

**Screenshots**

N/A

**Logs**

N/A

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]: 2024.10.4

**Additional context**
N/A

**Comment by cardboardpig** [comment]
+1, Just upgraded my lab Authentik to 2024.10.5 but noticed the pgbouncer issue still exists.

**Comment by rissson** [comment]
In the long term we'll probably deprecate `USE_PGBOUNCER` and `USE_PGPOOL` and just expose django settings to users.

**Comment by fullykubed** [comment]
That makes sense, but I believe the "bug" is that the default behavior sould be to use persistent connections. Users should then have the ability to disable persistent connections if using an external connection pooler like pgbouncer.

The current behavior is the opposite.
