### ISSUE TITLE
core_users_recovery_email_create 405 method not allowed

### ISSUE THREAD

**Issue by sburk** [goauthentik/authentik#12429]
**Describe the bug**
API usage core_users_recovery_email_create returns a 405 method not allowed 

**To Reproduce**

connect to your authentik api by bearer token 
<your instance url>/api/v3/core/users/<id>/recovery_email/?email_stage=<your-email-stage>

**Expected behavior**
204 (email successfully sent)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.10.5
-   Deployment: docker (portainer stack)

**Additional context**
if relevant: authentik is running behind a traefik reverse proxy
other api requests are successfull

**Comment by sburk** [comment]
not according to the api documentation (https://docs.goauthentik.io/docs/developer-docs/api/reference/core-users-recovery-email-create) the response header says 
Allow: GET, HEAD, OPTIONS
API documentation says POST

**Comment by BeryJu** [comment]
405 in this case is usually caused by an exception somewhere, could you post the logs of the authentik server container?

**Comment by sburk** [comment]
Of course. Thank you in advance.
![grafik](https://github.com/user-attachments/assets/7d4f7771-095f-4d52-8434-397efe833085)

by the way: when i check with postman i get a Allow: POST, OPTION response on /users/recovery_email
but when i add ?email_stage 405 is returned with Allow: GET, HEAD, OPTIONS in header

**Comment by BeryJu** [comment]
is there anything in the logs above the two lines you sent?

**Comment by sburk** [comment]
> is there anything in the logs above the two lines you sent?

Only the first line (403) again and again (which i have ignored yet). it is produces every 3-4 seconds

**Comment by sburk** [comment]
I'm so sorry. Sending it with network detection from the web gui told me that the expected string for email_stage is the id of the stage, not the clear name. Maybe the api documentation could show that. tank you for your quick response!
