### ISSUE TITLE
Outpost deployed via docker compose - AUTHENTIK_HOST needs a trailing slash in 2024.12

### ISSUE THREAD

**Issue by Heavensong89** [goauthentik/authentik#12430]
**Describe the bug**
In 2024.10 (and prior versions), the URL used in the `AUTHENTIK_HOST` variable did not need a trailing slash - i.e. http://authentik:9000, https://authentik.domain.tld - this also matches the documentation. In 2024.12, "ws" is being appended to the URL without a trailing slash, and so I had to add the trailing slash to the URL set in the environment variable.

Docs need to be amended to show a required trailing slash, or logic added to check for the presence of one.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.12
-   Deployment: docker-compose

**Logs when no trailing slash added to the URL set by `AUTHENTIK_HOST`**

![image](https://github.com/user-attachments/assets/0b8bd7e8-5e0d-4008-8b1c-da5c38603142)

**Comment by OddMagnet** [comment]
Same thing for me, glad to see that I didn't f* something up :D
(commenting so I get notifications about the resolution - i.e. if slash in config needs to stay or can be removed again in future)

**Comment by MineTech13** [comment]
same here soo +1 from me and also confirmed working with trailing slash

**Comment by mwullink** [comment]
Apache Iceberg 1.8.0 also not working anymore because it strips the trailing slash and Authentic return http 405 when the slash is missing.

**Comment by JoeriHermans** [comment]
Indeed, same behaviour in `expo-auth-session`. Although, I believe it might be `okhttp` doing some URL normalization somewhere downstream since the OIDC discovery endpoint correctly provides the token URL _with_ a trailing slash.
