### ISSUE TITLE
How limit OAuth provider to a group?

### ISSUE THREAD

**Issue by MagicianTM** [goauthentik/authentik#1249]
Hello,

Is it possible to limit an OAuth provider to some groups? What I want to achieve is:
- in my LDAP, some users are member of group MYAPP. The LDAP groups are correctly synched into Authentik, and users are correctly linked to them.
- I created a OAuth provider for an application for which only users member of group MYAPP can have access to.

From the documentation, I understood that the application (in the Authentik terminology) is where the access control is made ... based on policies. And that's where I'm stuck. What should I create as flow/stages/policies to achieve my goal ?

It is maybe a simple stuff. But I must admit I really don't see how to make it :/

**Comment by BeryJu** [comment]
Hi, I fully agree that its not 100% clear.

When you click on an application, and then the `Policy / Group / User Bindings` Tab, you can add a binding for a group. This will grant access to anyone in the selected group.

**Comment by MagicianTM** [comment]
I knew it was simple ... I just never thought about going on the application directly (I always went into the "edit" of the application).
Many thanks (once again) for that quick reply. I really appreciate your support and your application !
