### ISSUE TITLE
Unable to successfully integrate with Traefik forward auth

### ISSUE THREAD

**Issue by SSS475** [goauthentik/authentik#1359]
**Describe the bug**
When using an outpost/proxy instance with Traefik the auth process fails when the outpost fails to redeem the Oauth2 ticket.

**To Reproduce**
When navigating a browser to a whoami service host behind Traefik on a separate VM:
* correctly redirected to the authentik outpost
* correctly redirected to the authentik host
* sign in successfully
* correctly redirected to the authentik outpost
* Receive `500: Internal Server Error` page

**Expected behavior**
The outpost should be able to redeem the code and set a cookie and correctly redirect back to the whoami service

**Screenshots**
No screenshots, but configuration is as follows

Outpost Configuration with provider `********DomainProxyProvider`
```
log_level: info
authentik_host: https://authentik.*****.test:9443/
docker_network: null
kubernetes_replicas: 1
kubernetes_namespace: default
object_naming_template: ak-outpost-%(name)s
authentik_host_insecure: true
error_reporting_enabled: true
kubernetes_service_type: ClusterIP
error_reporting_environment: customer
kubernetes_disabled_components: []
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
```
And environment variables in docker-compose
```
    environment:
      AUTHENTIK_HOST: https://authentik.*****.test:9443
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: ****** (copied from deployment info)
```

**Logs**
Log from the authentik outpost
```
{"event":"Error redeeming code during OAuth2 callback: token exchange: Post \"https://authentik.*****.test:9443/application/o/token/\": x509: certificate is valid for *, not authentik.*****.test","level":"error","logger":"authentik.outpost.proxy","provider":"********DomainProxyProvider","timestamp":"2021-09-07T15:23:50Z"}
```

Note: Produces slightly different error when using IP Address instead of DNS
```
{"event":"Error redeeming code during OAuth2 callback: token exchange: Post \"https://***.***.***.***:9443/application/o/token/\": x509: cannot validate certificate for ***.***.***.*** because it doesn't contain any IP SANs","level":"error","logger":"authentik.outpost.proxy","provider":"********DomainProxyProvider","timestamp":"2021-09-02T14:10:29Z"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.8.4
 - Deployment: docker-compose(both Authentik server and the outpost on separate VMs)

**Additional context**
Two Arch Linux VMs
1. Service host, has a Domain routed to it, using Docker to host multiple services revrese proxied with Traefik.  And using the docker-compose file from the docs to host the authentik proxy/outpost and a whoami service. 
2. Authentik host, has a DNS name routed to it(not in the domain as the service host), using Docker to host the Authentik platform with the prvoided example docker-compose file

It appears based on the code that it generates the Self-Signed certificate every time it starts the main server.  There does not appear to be configuration for using another certificate, nor configuration to set Subject Alternative Names on the Self Signed certificate.  Either the configurations need to be added and passed through or the outpost needs to carry the configuration for the web client that it used to retrieve the instance information(which used the environment variable to correctly mark SkipVerify on the TLS connection) to also SkipVerify during Oauth2 code redemption.

**Comment by BeryJu** [comment]
Yeah so the `_insecure` should in theory prevent this, however since the core of the Proxy provider is still based on oauth2_proxy, it currently doesn't. Theres already https://github.com/goauthentik/authentik/issues/1330 open (for one of the next versions) to rewrite the proxy, which will also fix this issue.

Currently the only way to make that work is with either HTTP or a valid certificate via a reverse-proxy

**Comment by SSS475** [comment]
Would you accept a PR to add the config for Subject Alternative Names so that could be configured and passed into the crypto Generate Self Signed Certificate function?

**Comment by BeryJu** [comment]
The Crypto generate-self-signed function can already do SAN, just the in-memory, self-signed certificate generated on startup has a static name. I don't think it makes sense to make that configurable, as 99% of people are going to use a reverse-proxy anyways.

**Comment by SSS475** [comment]
Ok.  I wanted to check if that met your vision before, thank you.
