### ISSUE TITLE
Hide disabled authenticator sections on profile

### ISSUE THREAD

**Issue by RixzZ** [goauthentik/authentik#1360]
**Is your feature request related to a problem? Please describe.**
If you delete the Flow called 'default-authenticator-*-setup', you effectively disable that function, since the option to configure them doesn't appear in the sections that ther user have on the profile, but the sections doesn't disappear.

**Describe the solution you'd like**
The sections 'WebAuthn Authenticator Setup Stage', 'Static Authenticator Stage' and 'TOTP Authenticator Setup Stage' should disappear when there is no Flow that covers that function.

You might have the case where you want some of those feature only for some user groups, so maybe the section should disappear too when the group doesn't have access to the flow (with a Group Policy).

**Describe alternatives you've considered**
I can leave them disabled, but is confusing having those sections empty.

**Additional context**
N/A

**Comment by BeryJu** [comment]
Hi,

the sections that are shown on the user settings are controlled by which stages exist, so to remove the UI completely you can just delete the satge.

**Comment by RixzZ** [comment]
Oh, never mind then. Thanks.
