### ISSUE TITLE
Allow custom access token validity 

### ISSUE THREAD

**Issue by adepto-io** [goauthentik/authentik#1369]
**Is your feature request related to a problem? Please describe.**
Currently token expiration seems to be applied to refresh, id and access tokens when setting the token validity.

**Describe the solution you'd like**
Limit the risk of leaked access tokens by allowing it's expiration to be set separately. I'd prefer short-lived access tokens and long-lived refresh tokens.

**Comment by BeryJu** [comment]
You can configure the `Access code validity` in the OAuth2 Provider form, which is used for authorization codes. The token validity field is used by refresh tokens, and also id_tokens when using an implicit flow.

**Comment by adepto-io** [comment]
I'm using AppAuth for Android and can confirm that I'm using 'code' as the response type. Shouldn't that mean that an implicit flow isn't used?  Moreover, I'm not handling implicit flows in my code at all.

**Comment by BeryJu** [comment]
I'm not 100% sure, but do you have to set a client secret with AppAuth? I would assume not, since that can easily be extracted by decompiling the APK. Hence it would probably be an implicit flow.

**Comment by adepto-io** [comment]
Your assumption is correct, no client secret is needed.

**Comment by BeryJu** [comment]
@adepto-io I switched to using the access token validity for all tokens generated during the authorization endpoint
