### ISSUE TITLE
Support for Gotify as notification transport

### ISSUE THREAD

**Issue by Leosirth** [goauthentik/authentik#1383]
Hi,

I would love to have [Gotify](https://gotify.net/) supported as transport for notifications in Authentik.

Trying to use the generic webhook doesn't work (probably for schema differences) resulting in:

`400 Client Error: Bad Request for url: https://gotify.domain/message?token=<redacted>`

If you think this can be implemented, here can be found how to push messages to Gotify:
https://gotify.net/docs/pushmsg

And here the api-doc:
https://gotify.net/api-docs#/message/createMessage

Thanks for this awesome project!!!

**Comment by BeryJu** [comment]
Hey @Leosirth, instead of adding specific support for any further providers, I added support to use property mappings to customise the request payload

**Comment by Leosirth** [comment]
This is even better, thank you for your support and this fast implementation!

**Comment by LeVraiRoiDHyrule** [comment]
> This is even better, thank you for your support and this fast implementation!

Hi, I'm a begginer with Authentik and I'm trying to have my notifications on Gotify too. Could you explain how you did it ?

Thanks and have a great day

**Comment by Leosirth** [comment]
> > This is even better, thank you for your support and this fast implementation!
> 
> Hi, I'm a begginer with Authentik and I'm trying to have my notifications on Gotify too. Could you explain how you did it ?
> 
> Thanks and have a great day

Hi,

you need to create a "Property Mapping" and use it on your "Notification Transport".
For the mapping this is how I configured it:

```
return {
  "message": notification.body,
  "priority": 5,
  "title": notification.event.action
}
```

Regards,
