### ISSUE TITLE
Unable to copy App Password from Service Account

### ISSUE THREAD

**Issue by jeremywillans** [goauthentik/authentik#1390]
**Describe the bug**
Unable to copy App Password from Service Account.

> SyntaxError: JSON.parse: unexpected character at line 4 column 1 of the JSON data

**To Reproduce**
1. Create Service Account
2. Navigate to Tokens and App Passwords
3. Click Copy next to Service Account App Password
4. Error displayed

**Expected behavior**
Password is copied to Clipboard

**Screenshots**
<img width="640" alt="image" src="https://user-images.githubusercontent.com/31495062/133185430-f673619f-e0f8-4519-b40a-3da2f998ed13.png">

**Logs**
```
{"event": "/api/v3/core/tokens/service-account-service.ldap-password/view_key/", "host": "192.168.0.72", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "xxxx", "runtime": 1666, "scheme": "https", "size": 0.064, "status": 404, "timestamp": "2021-09-14T02:35:52.827783"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.8.5
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Hi, I've not been able to reproduce this, could you open the Developer tools in your browser, click on the copy button and check the network requests? I'm curious what the response contains, since it should either be JSON or a 404

**Comment by jeremywillans** [comment]
@BeryJu, Can you try with a period/dot in the Service Account name? If i don't have one, then it does work as expected.
