### ISSUE TITLE
Duo 2FA example flow

### ISSUE THREAD

**Issue by LefflerMediaLLC** [goauthentik/authentik#1402]
Any chance you could provide a Duo 2FA example flow please?

Thanks,
Nick

**Comment by BeryJu** [comment]
Hi, you can follow the same principle as is used for the default TOTP flows:

- create a Duo Authenticator stage
- create a new Flow with designation of configuration
- bind the duo stage to the created flow
- modify the stage to select the above created flow for configuration

Then you can open the user settings and Duo will show up in the sidebar.

**Comment by 12nick12** [comment]
Is there a way to support Duo 2FA and/or normal TOTP? I have some users that have Duo and others that don't. I tried modifying the default-authentication-flow-mfa and enabled the Duo device type. 

What I was thinking was try Duo and if that (or user doesn't exsist) doesn't work then go to normal TOTP.
