### ISSUE TITLE
SoftTimeLimitExceeded while running task "Synchronization of an LDAP Source"

### ISSUE THREAD

**Issue by asteven** [goauthentik/authentik#1411]
**Describe the bug**
Given an LDAP source with 10s of thousands of users the synchronization task aborts with SoftTimeLimitExceeded.

**To Reproduce**
1. Configre a LDAP source with 10s of thousands of users
2. Wait
3. See error

**Expected behavior**
The synchronization completes independent of the size of the LDAP source.

**Logs**
```js
{"event": "Task authentik.sources.ldap.tasks.ldap_sync[7a422515-4d28-48c4-8624-b18f00d47abe] raised unexpected: SoftTimeLimitExceeded()", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/celery/app/trace.py\", line 450, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/celery/app/trace.py\", line 731, in __protected_call__\n    return self.run(*args, **kwargs)\n  File \"/authentik/sources/ldap/tasks.py\", line 42, in ldap_sync\n    count = sync_inst.sync()\n  File \"/authentik/sources/ldap/sync/users.py\", line 42, in sync\n    defaults = self.build_user_properties(user_dn, **attributes)\n  File \"/authentik/sources/ldap/sync/base.py\", line 53, in build_user_properties\n    return self._build_object_properties(user_dn, self._source.property_mappings, **kwargs)\n  File \"/authentik/sources/ldap/sync/base.py\", line 70, in _build_object_properties\n    value = mapping.evaluate(user=None, request=None, ldap=kwargs, dn=object_dn)\n  File \"/authentik/core/models.py\", line 484, in evaluate\n    evaluator.set_context(user, request, self, **kwargs)\n  File \"/authentik/core/expression.py\", line 25, in set_context\n    req = PolicyRequest(user=get_anonymous_user())\n  File \"/usr/local/lib/python3.9/site-packages/guardian/utils.py\", line 34, in get_anonymous_user\n    return User.objects.get(**lookup)\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/query.py\", line 431, in get\n    num = len(clone)\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/query.py\", line 262, in __len__\n    self._fetch_all()\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/query.py\", line 1324, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/query.py\", line 51, in __iter__\n    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py\", line 1162, in execute_sql\n    sql, params = self.as_sql()\n  File \"/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py\", line 543, in as_sql\n    for _, (s_sql, s_params), alias in self.select + extra_select:\n  File \"/usr/local/lib/python3.9/site-packages/billiard/pool.py\", line 229, in soft_timeout_sighandler\n    raise SoftTimeLimitExceeded()\nbilliard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()", "level": "error", "logger": "celery.app.trace", "timestamp": 1631831495.6161473}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.8.4
 - Deployment: helm

**Comment by asteven** [comment]
I guess the time limit for the ldap synchronization should be configurable per LDAP source.
Alternatively/additionally it may make sense to run dedicated tasks for syncing users, groups and memberships independently.

**Comment by BeryJu** [comment]
Thanks for reporting the issue, I never tested with that many user but the error makes sense. I also like the suggestion of running each sync component in its own task.

**Comment by asteven** [comment]
So looking through the authentik source and celery docs for a few minutes I guess this would be an action plan:
- add a new optional field 'timeout' to the LDAP Source Form/Model
- refactor sources/ldap/tasks.py to run tasks with explicit [soft and hard limits](https://docs.celeryproject.org/en/stable/userguide/workers.html#time-limits) based on the 'timeout' field
- refactor sources/ldap/tasks.py to handle the SoftTimeLimitExceeded Exception to properly log the failure instead of failing with a stacktrace
- refactor sources/ldap/tasks.py to run individual tasks for syncing users, groups and memberships while again respecting the 'timeout' field

**Comment by asteven** [comment]
JFTR: it successfully synced about 12000 users before failing. Groups and memberships are not synced at all.

**Comment by asteven** [comment]
BTW: pretty amazing project you created here. As in freakin' amazing!
The UI is super snappy and like a fresh breeze to use.
Makes me hate the proprietary tool they pushed on us at work even more (if that's even possible ;-)

**Comment by BeryJu** [comment]
While the configurable timeout makes sense, it would require a custom interval too (since currently that is hardcoded to once an hour). Sadly that is not easily changeable since I'm not using the celery-django integration to store schedules in the database.

I've increased the internal to once every 2 hours, with a timeout of 2 hours per component.

**Comment by asteven** [comment]
Some company somewhere in the world:

> employee> boss, we have a problem, our identity provider stopped syncing from ldap
> boss> sugar. Ok, time to put that 10k$ support contract to good use
> boss> go and tell the vendor to fix it
> employee> okay, what's the phone number and email again?
> boss> don't know, you should have it
> employee some hours later> found it, opened a support case
> boss 2 weeks later> hey, what's going on with that ldap syncing issue
> employee> still no answer from the vendor
> boss> WHAT! what do we pay those 10k$ per month for????
> employee> I don't know.

A different company somewhere else:

> employee> boss, we have a problem, our identity provider stopped syncing from ldap
> boss> that's that awesome Open Source solution you proposed?
> employee> yes!
> employee> I already opened an issue on github
> boss> ok, great. Now we'll just have to wait.
> employee> no. The developer responded after 15 minutes
> employee> and fixed the problem after 50
> boss> Gee, I'm glad we didn't go for that $proprietary solution they wanted to push on us
> employee> Me to!
