### ISSUE TITLE
Unable to sync LDAP groups

### ISSUE THREAD

**Issue by ramon-roca** [goauthentik/authentik#1413]
**Describe your question/**
Trying to sync our LDAP, but no groups get synced. I would appreciate help on diagnose....

**Relevant infos**
seems we have a groups like described at #528 
ldif group example:
```
# LDIF Export for cn=testgroup,o=glirusers,dc=guifi,dc=net
# Server: guifi·net Users (ldaps://ldap.guifi.net)
# Search Scope: base
# Search Filter: (objectClass=*)
# Total Entries: 1
#
# Version: 1.2.2

version: 1

# Entry 1: cn=testgroup,o=glirusers,dc=guifi,dc=net
dn: cn=testgroup,o=glirusers,dc=guifi,dc=net
cn: testgroup
member: uid=test.user,o=glirusers,dc=guifi,dc=net
member: uid=user.test,o=glirusers,dc=guifi,dc=net
objectclass: groupOfNames
```

**Screenshots**
getting this sync output for this LDAP source:
```
Last sync: 18/9/2021, 6:00:04

Synced 157 objects from UserLDAPSynchronizer
Synced 0 objects from GroupLDAPSynchronizer
Synced 0 objects from MembershipLDAPSynchronizer
```

**Version and Deployment (please complete the following information):**
 - authentik version: [2021.9.1-rc2]
 - Deployment: [1.26.0, build d4451659 on Ubuntu 20.04]

**Additional context**
Group object filter set to **(objectclass=groupOfNames)**
Group membership field set to **member**

**Comment by BeryJu** [comment]
Hi, can you check the logs of your worker container to see if there are any warnings? It looks like no groups are created at all so either something happens during the query or there is another reason why the groups can't be created.

**Comment by ramon-roca** [comment]
found where was the problem: at the LDAP Source, advanced options, we'd "**uid**" as "**Object uniqueness field**", while it had to be "entryUUID".
now all desired groups get synched.
thanks!
