### ISSUE TITLE
Traefik forward-auth questions

### ISSUE THREAD

**Issue by zmiguel** [goauthentik/authentik#1422]
**Describe your question**
I'm trying to replace Authelia with Authentik, for forward auth with Traefik

**Relevant infos**
Using Traefik 2.5.2, authentik 2021.9.1-rc3

**Version and Deployment:**
 - authentik version: 2021.9.1-rc3
 - Deployment: docker-compose

**Additional context**
I've setup everything according to the installation guide in the docs. It works, I can access it and create things in authentik.

My problem is that I'm also running portainer, and I have portainer's port 9000 mapped. Every time I try to create an outpost it tries to map port 9000 to itself, why? You can just expose the port and everything would work fine. why are you forcing me to port-map port 9000? If I want it to be accessed outside my network it will go through traefik.

I could not find any way to stop the outpost from force mapping the port. I just want it to expose it, not map it.

2nd question:

If I understood the docs correctly I need to create a provider for traefik, and then multiple apps for all the services I want protected by authentik, and then assign them to the outpost. Is that correct?

I'm sorry if I'm misunderstanding how this is supposed to work, but I'm having some trouble understanding the terminology page, as some components don't seem to be linked, like the flows to policies or apps

**Comment by BeryJu** [comment]
Hi,

for the first question, you don't need to create an outpost, you can use the embedded outpost, which shares ports with the authentik server. Alternatively, you can also manually create an outpost, where you can fully control everything

for the second question, it depends.

You can either do domain-level auth, where you only create a single provider & application, but you can't do access control for different subdomains. 
Or you do app-level auth, where you have to create an application & provider per subdomain, but you can do proper access control with that.

**Comment by Akruidenberg** [comment]
Is it possible to provide some compose examples to use Traefik with the embedded outpost/proxy?

**Comment by BeryJu** [comment]
@zmiguel for the first question, that will be an option in 2021.9.4
@Akruidenberg it works pretty much identical to the external outpost
