### ISSUE TITLE
ldap group membership not updated

### ISSUE THREAD

**Issue by asteven** [goauthentik/authentik#1436]
**Is your feature request related to a problem? Please describe.**
The ldap syncing code assumes group membership is based on DN.
In our ldap tree this is unfortunately not the case. Instead the group membership is based on CN.
So while users and groups are synced, the group memberships are not established in authentik's database.

**Describe the solution you'd like**
I need the 'group membership field' to be matched against the CN of a user instead of it's fully qualified DN.

**Additional context**
Example pseudo ldif for groups:
```
dn: cn=group-1,ou=groups,o=example,c=ch
objectClass: posixGroup
cn: group-1
memberUid: user-1
memberUid: user-2
memberUid: user-3

dn: cn=group-2,ou=groups,o=example,c=ch
objectClass: posixGroup
cn: group-2
memberUid: user-1
memberUid: user-2
```
And for users:

```
dn: cn=user-1,ou=users,o=example,c=ch
objectClass: posixAccount
cn: user-1
ou: group-1
ou: group-2

dn: cn=user-2,ou=users,o=example,c=ch
objectClass: posixAccount
cn: user-2
ou: group-1
ou: group-2

dn: cn=user-3,ou=users,o=example,c=ch
objectClass: posixAccount
cn: user-3
ou: group-1
```

If think for the current authentik sync code to work the groups would have to look like this:
```
dn: cn=group-1,ou=groups,o=example,c=ch
objectClass: posixGroup
cn: group-1
memberUid: user-1,ou=users,o=example,c=ch
memberUid: user-2,ou=users,o=example,c=ch
memberUid: user-3,ou=users,o=example,c=ch

dn: cn=group-2,ou=groups,o=example,c=ch
objectClass: posixGroup
cn: group-2
memberUid: user-1,ou=users,o=example,c=ch
memberUid: user-2,ou=users,o=example,c=ch
```

But changing this is beyond my control.

This is the OpenLDAP directory tree of a large University. I'm not sure if this setup and therefor also the problem is common or unique to our deployment.

I guess for the membership mapping to work I'd need the code that authentik uses to lookup group memberships in ./authentik/sources/ldap/sync/membership.py to look something like this:

```
LDAP_UNIQUENESS = "ldap_uniq"

            users = User.objects.filter(
                Q(**{f"attributes__{LDAP_UNIQUENESS}__in": members})
                | Q(
                    **{
                        f"attributes__{LDAP_UNIQUENESS}__isnull": True,
                        "ak_groups__in": [ak_group],
                    }
                )
            )

```

Instead of the current:

```
LDAP_DISTINGUISHED_NAME = "distinguishedName"

            users = User.objects.filter(
                Q(**{f"attributes__{LDAP_DISTINGUISHED_NAME}__in": members})
                | Q(
                    **{
                        f"attributes__{LDAP_DISTINGUISHED_NAME}__isnull": True,
                        "ak_groups__in": [ak_group],
                    }
                )
            )

```

I'm happy to provide a PR after discussing the right approach on how to make this configurable.

**Comment by asteven** [comment]
Would you accept a PR with something like the code in this branch?
https://github.com/asteven/authentik/tree/issue-1436

**Comment by asteven** [comment]
Reading up on the topic it seems this is basically a question of which LDAP objectClass is used for managing group memberships (e.g. posixGroup with the attribute 'memberUid' vs groupOfNames with the attribute 'member')

Some information on the topic:
https://unofficialaciguide.com/2019/07/31/ldap-schemas-for-aci-administrators-rfc2307-vs-rfc2307bis/


Here's how some software handles these differences:

### sssd
If ldap_schema is set to rfc2307bis only the member attribute is considered and the value is assumed to be the FDN

### OwnCloud
https://doc.owncloud.com/server/next/admin_manual/configuration/user/user_auth_ldap.html
- member with FDN for Active Directory or for objectclass groupOfNames groups
- memberUid with RDN for objectclass posixGroup groups
- uniqueMember with FDN for objectclass groupOfUniqueNames groups


A pragmatic solution might be to just handle the membership resolution based on RDN if the 'Group membership field' is set to 'memberUid' and use the FDN (as it is now) in any other case.

**Comment by asteven** [comment]
So in the meantime I have 2 branches that solve this problem for me:

https://github.com/asteven/authentik/tree/issue-1436
New checkbox in the ldap source plus changes in membership sync code to use RDN instead of FDN to assing group members.

https://github.com/asteven/authentik/tree/memberUid-rdn
Use RDN if the 'Group membership field' is 'memberUid', use FDN otherwise.

I guess the second is somewhat to magic.

@BeryJu Any preference?

**Comment by BeryJu** [comment]
Sorry for taking so long to answer this issue, I'm partial to https://github.com/asteven/authentik/tree/memberUid-rdn. I prefer not having to add another field to the already (imo) too large LDAP form. As long as the special logic for this value is documented it should be fine imo.
