### ISSUE TITLE
Token validity not respected?

### ISSUE THREAD

**Issue by lue30499** [goauthentik/authentik#1462]
_OS version = Ubuntu LXC 20.04.3 LTS
Docker version = 20.10.7
Authentik Version = 2021.9.2_

Hello,

When setting up a proxy provider I configured a Token validity of 20 minutes.

<img width="1105" alt="Screen Shot 2021-09-25 at 4 54 12 pm" src="https://user-images.githubusercontent.com/63104612/134762460-e83d0d53-430f-469e-9b80-030ec55e3e1c.png">

If I browse to the domain it loads a login and it redirects to the backend, all good.
But when I log out of authentik then browse back to the domain it doesn't redirect to a login page. Even if I wait after 20 minutes. So I checked the cookie expiry time and it shows a month later? Is this correct?

<img width="453" alt="Screen Shot 2021-09-25 at 4 53 06 pm" src="https://user-images.githubusercontent.com/63104612/134762480-883285b2-0090-4bc4-84eb-c006caa43928.png">

This may just be me not understanding what "Token validity" means. How do I get the domain to redirect to the login page after a sign out (or respecting a timeout) when going back to a previously signed in proxy provider?

Regards,
Lue.

**Comment by BeryJu** [comment]
Hi, thanks for the report!

Your inderstanding is indeed correct. The implementation is flawed in that the OAuth JWT token is valid for that amount of time, but the outpost's session length isn't controlled with that setting *yet*
