### ISSUE TITLE
Unable to reset password from "Admin Interface"

### ISSUE THREAD

**Issue by lue30499** [goauthentik/authentik#1472]
_OS version = Ubuntu LXC 20.04.3 LTS
Docker version = 20.10.7
Authentik Version = 2021.9.2_

Hello,

When logged into a admin account and looking at users in the "Admin Interface" -> "Identity & Cryptography" -> "Users"
When click on the user then click "Reset Password" it shows an error " ! {"link":""} "

<img width="1680" alt="Screen Shot 2021-09-26 at 4 20 49 pm" src="https://user-images.githubusercontent.com/63104612/134796144-c9a9b9b0-154a-4a21-a966-66762bf18330.png">

Why is this? Is this a permission issue? It's a fresh install with only one provider setup.

If I impersonate the user then go to Gear then "Password, 2FA, etc" and change the user there, it works.

Regards,
Lue.

**Comment by BeryJu** [comment]
Cheers for reporting this.

The reason why it doesn't work is because to create a recovery link, your current tenant needs to have a Recovery flow configured. This is because otherwise authentik wouldn't know what flow to use.
