### ISSUE TITLE
Unable to activate user

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1491]
**Describe the bug**
Unable to activate user via user panel in Admin console

**To Reproduce**
1. Try to create an user with an email entrollment.
2. Have it create a new user via user-write stage.
3. Try to activate the said user in Authentik admin panel.

**Expected behavior**
I would have expected it to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/135183971-915f177b-074f-4711-9fed-312db6b12704.png)

**Logs**
```
{"event": "Bad Request: /api/v3/core/users/12/", "level": "warning", "logger": "django.request", "timestamp": 1632876107.8054774}
{"event": "/api/v3/core/users/12/", "host": "<snip>, "level": "info", "logger": "authentik.asgi", "method": "PATCH", "pid": 27, "request_id": "acf96c3c3fd148a9a60edc10752b12f3", "runtime": 41, "scheme": "https", "size": 0.06, "status": 400, "timestamp": "2021-09-29T00:41:47.806012", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.50 Safari/537.36 Edg/94.0.992.23"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.3
 - Deployment: Docker containers via Ansible

**Additional context**
May be related, but the email-verify stage doesn't work properly either to my knowledge.
I'm kryptonian on the Discord.

**Comment by BeryJu** [comment]
Hi, does the user you're toggling the status of have a username and a name?

**Comment by samip5** [comment]
> Hi, does the user you're toggling the status of have a username and a name?

It doesn't have a name.

**Comment by BeryJu** [comment]
yeah that will have caused the issue, fixed in the commit above
