### ISSUE TITLE
Access 'dn' in OpenLDAP property mapper

### ISSUE THREAD

**Issue by stacab** [goauthentik/authentik#1496]
**Is your feature request related to a problem? Please describe.**
I need to access LDAP group attribute `dn` as a property mapping

**Describe the solution you'd like**
AFAIK, only fields that are accessible using `ldap` object are listed [here](https://goauthentik.io/docs/providers/ldap). `dn` is not among them and I need to access it. Adding `dn` to list of attribute (and even more generic solution to be able to retrieve any attribute) available in `ldap` object would be cool.

**Describe alternatives you've considered**
There's no alternative since I did not found a way to get whole group's `dn` using already existing properties.

**Additional context**

**Comment by tigattack** [comment]
+1, it would be helpful to access deez names from LDAP.

**Comment by BeryJu** [comment]
The fields listed https://goauthentik.io/docs/providers/ldap are for the LDAP *provider*, which would make authentik offer an LDAP Server. For OpenLDAP integration you need an LDAP Source, where you can access the `dn` variable in the context of the Property Mapping

**Comment by stacab** [comment]
Hi @BeryJu 

Ah, yes, sorry for the mistake, I've mixed provider and source. However, are you sure that `dn` is accessible in Property Mapping? When create Property Mapping with expression
```python
return ldap.get("dn")
```
or 
```python
return ldap.get("DN")
```
I get `None`.

This Property Mapping is used in Group Property Mappings in LDAP Source configuration

**Comment by BeryJu** [comment]
Try doing just `return dn`, the `dn` variable gets set outside of the `ldap` object.

**Comment by stacab** [comment]
It works, thank you for your help.
