### ISSUE TITLE
Guide on creating bearer tokens for API access

### ISSUE THREAD

**Issue by AminSaqi** [goauthentik/authentik#1498]
**Describe your question/**
I don't know how I should create an Authorization token for my API client.

I created the client with OpenAPI generator, and now I have to create a token to be passed as a Bearer token. I created an API Access token from `User Settings > Tokens and App passwords`, but it has a close expiration date.

So what should I do to seamlessly authorize my client to the authentik server?

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.8.4
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Hi, in 8.x token creation is a bit limited. You can set the `goauthentik.io/user/token-expires` attribute your user to false, and that will allow you to generate a token without expiration. On 9.x this is easier, as a superuser you can just create a token and fully configure it from the API/Web UI

**Comment by AminSaqi** [comment]
Thank you.
