### ISSUE TITLE
Not able to sync changes back to LDAP source

### ISSUE THREAD

**Issue by ramon-roca** [goauthentik/authentik#1512]
**Describe your question**
Changes to users/groups at authentik that come from OpenLDAP, are never synched back to the LDAP source

**Relevant infos**
OpenLDAP syncs users to authentik as described in #1413
Users, groups and group memberships get filled succesfully at authentik.
However getting thowsands of notifications complaining on "configuration error"/"duplicate keys", one for every single user, like this:

`Configuration error
` 
```
Failed to create user: duplicate key value violates unique constraint "authentik_core_user_username_key"
DETAIL:  Key (username)=(john.doe) already exists.
 To merge new user with existing user, set the user's Attribute 'ldap_uniq' to 'f22138f0-0992-103b-9a7d-89eac14e7073'
```
So takes every user as a duplicated to be merged, while actually is not another user, but the existing one.

**Version and Deployment (please complete the following information):**

authentik version: [2021.9.4]

**Comment by BeryJu** [comment]
Hi, authentik doesn't currently support writing changes back to LDAP, besides the password. While it could be added in theory, it would require a large set of new Property Mappings that worked in reverse to map authentik data to LDAP

**Comment by ramon-roca** [comment]
oops! sorry for missing that.
We were thinking on using authentik also for enrollment, but might be a bit more difficult without writing back to the OpenLDAP... but as a workaround maybe we could run a custom API for that.... 

Or even better, try to use the provider feature as LDAP so authentik becomes the primary LDAP and use the one-way synch for migrating the original.

And what about the notification messages? We can ignore it? There is any way to get rid of them?

**Comment by BeryJu** [comment]
Either one would work, yeah. I'm not saying it'll never be added, there's currently no plans to do so.

For the other error, have you checked the `ldap_uniq` attribute of the affected users? If they match and new notification are still generated, please open a separate issue.
