### ISSUE TITLE
schemas.goauthentik.io is no longer online

### ISSUE THREAD

**Issue by fariszr** [goauthentik/authentik#1515]
Hi thanks for the awesome project!

https://schemas.goauthentik.io is used in a lot of providers examples, yet the subdomain seems to not have any dns records ?

i can't continue setting up authentik since the domain is essential for nextcloud and other apps to work.

**Comment by BeryJu** [comment]
Yes, the domain is just used as a unique Identifier for the schemas. It doesn't have any A Records on purpose. Other schemas like `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` don't return anything either, as the URI is just a unique identifier for the SAML Request/Response
