### ISSUE TITLE
Users synced from Active Directory get synced in status "inactive"

### ISSUE THREAD

**Issue by AndreasUfert** [goauthentik/authentik#1525]
**Describe the bug**
After setting up a new instance of Authentik I've just added an LDAP source that syncs users and groups (both filtered) from Active Directory into Authentik. The sync job successfully synced all users and groups, membership is synced correctly as well.
However, all users are synced into Authentik as being "inactive" and therefore aren't able to login until explicitly activated by an Authentik admin.

**To Reproduce**
1. Create LDAP source as given here: https://goauthentik.io/docs/integrations/sources/active-directory/index
2. Trigger sync of this newly created source
3. Verify users, groups and memberships are synced correctly
4. See that all users have been created in an "inactive" state

**Expected behavior**
Users should be active after sync. At least the state should be set according to a particular LDAP attribute or group membership.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6349253/135819558-5dcae802-e734-4971-8d2f-7813247276d9.png)
![grafik](https://user-images.githubusercontent.com/6349253/135819604-c81bf66a-a5a1-4b9e-9737-de5ce7516911.png)
![grafik](https://user-images.githubusercontent.com/6349253/135819630-cbb1c61a-db91-4941-91d9-29990c6d2625.png)
![grafik](https://user-images.githubusercontent.com/6349253/135819641-c9fdfa5f-a23d-40f8-96bb-f460982fac48.png)
![grafik](https://user-images.githubusercontent.com/6349253/135819667-dd3f2fde-891c-4bf3-810d-c54a029af5f3.png)

**Logs**
```
server_1      | {"event": "/api/v3/events/notifications/?ordering=-created&page_size=1&seen=false", "host": "10.180.43.80", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "bd8d5a0031e3462eb69342fd89e65afb", "runtime": 119, "scheme": "https", "size": 0.024, "status": 200, "timestamp": "2021-10-04T08:37:13.001858", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"}
server_1      | {"event": "/api/v3/events/notifications/?ordering=-created&page_size=1&seen=false", "host": "10.180.43.80", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "c55cb3a8c0cd41f99277b7aaab5cd08e", "runtime": 119, "scheme": "https", "size": 0.025, "status": 200, "timestamp": "2021-10-04T08:37:13.054903", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"}
server_1      | {"event": "/api/v3/events/notifications/?ordering=-created&page_size=1&seen=false", "host": "10.180.43.80", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "6fb6923121ed4f998cddfbd5402480c9", "runtime": 119, "scheme": "https", "size": 0.027, "status": 200, "timestamp": "2021-10-04T08:37:13.106986", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.4
 - Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
Thanks for reporting this, its already fixed on master https://github.com/goauthentik/authentik/commit/8dd77793a0f64f6ca41cbf1a3d33f01be54d25df, I'll release 9.5 later today
