### ISSUE TITLE
Email template for account confirm seems to output wrong message to user

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1538]
**Describe the bug**
It seems that when one sets the email stage to use the "Confirm Account" template, the stage itself still says "check your emails for a password reset link".

**To Reproduce**
1. Use the default enrollment flow with email confirm and make sure the email stage is set to use Account confirm template.
2. Enroll an user
4. See incorrect message

**Expected behavior**
The message would say something about confirming the account and not password reset.

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/135977111-7eb63066-00b4-4fc9-8fe5-6a1752e7d7e6.png)

**Version and Deployment (please complete the following information):**
- authentik version: 2021.9.3 (commit hash e085968)
- Deployment: Ansible with Docker containers

**Comment by BeryJu** [comment]
So the message is currently hardcoded in the frontend, regardless of what email is being sent. I've just changed the message to be a bit more generic

**Comment by samip5** [comment]
> So the message is currently hardcoded in the frontend, regardless of what email is being sent. I've just changed the message to be a bit more generic

Why is it harcoded?
