### ISSUE TITLE
Login page reloads continuously in Safari (mobile and desktop) starting in 2021.9.6

### ISSUE THREAD

**Issue by rmitchellscott** [goauthentik/authentik#1578]
**Describe the bug**
Starting in 2021.9.6, the login page continuously reloads in both mobile and desktop Safari.

**To Reproduce**
1. Browse to authentik in Safari
2. Observe continuous page reloads

**Expected behavior**
Login page loads once

**Comment by danhawkes** [comment]
This may be the same issue: https://github.com/goauthentik/authentik/issues/1565

**Comment by BeryJu** [comment]
Seems to be caused by the same issue, testing on 9.7 loop reloads in safari, while Master doesn't. I'll release 9.8 in a bit with that commit backported
