### ISSUE TITLE
Timing between the client and server

### ISSUE THREAD

**Issue by firestrife23** [goauthentik/authentik#1594]
**Describe your question**
Admin UI's Server Status widget is showing a message: "Server and client are further than 5 seconds apart."

Does this have to do with container's time zone or the timing for 2FA?

If it's related to the 2FA timing, I suggest adding the same feature as Authenlia's fix for NTP (see [here](https://www.authelia.com/docs/configuration/ntp.html) and [here](https://www.authelia.com/docs/configuration/one-time-password.html) for more details) 

**Relevant infos**
- Ubuntu 18.04 LTS
- Docker CE 20.10.9

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.8
 - Deployment: docker-compose

**Additional context**
Authentication via Oauth2 and Proxy is working fine, no issues though.

**Comment by BeryJu** [comment]
Hi, the difference is calculated between the server's container time and the browser time. It's only important for 2FA and a few couple other things I'm forgetting

**Comment by mooglestiltzkin** [comment]
> > Hi, the difference is calculated between the server's container time and the browser time. It's only important for 2FA and a few couple other things I'm forgetting
> 
> So what are we supposed to do to fix this warning? I looked for a way to change the container time however the docs mention that the container should be in UTC. Obviously my browser is not in UTC as I don't live in UTC. Is the warning just always supposed to be there?

i would like to know as well. does it resolve on it's own or what exactly are we suppose to do here?

my desktop and the docker compose timezones are set to the same so not sure what else i can do at this point.

**Comment by BeryJu** [comment]
The warning has nothing to do with timezones (the check compares the unix timestamp which is always UTC), and it's only a warning on purpose as in most cases nothing too bad will happen from it, however having such a time difference can cause issues especially with TOTP. The recommended troubleshooting for it is to ensure both server and client are using NTP, are in sync and ideally using the same NTP servers

**Comment by firestrife23** [comment]
I was able to solve this by merging the NTP information with the DHCP server, which is then distributed to all the network devices. I use Opnsense for this one.

**Comment by l4rm4nd** [comment]
Fixed the issue by manually syncing the Windows clients to the default time server at `time.windows.com`. After a refresh of the Authentik admin UI, no issues or warnings were shown anymore.

It was basically the client being a few seconds behind.

**Comment by Fabioamd87** [comment]
I've found that NTP was not configured on worker node, only control plane.
Setting it also on the worker node, where the pod is running, solved the issue.
