### ISSUE TITLE
User UI broken on mobile but Admin UI is fine on 2021.9.8

### ISSUE THREAD

**Issue by RXWatcher** [goauthentik/authentik#1610]
**Describe the bug**
User UI broken on mobile but Admin UI is fine on 2021.9.8

**To Reproduce**
On your mobile device, connect into your authentik and you'll see the user ui is messed up, select the admin button and it's fine.

**Expected behavior**
The user UI should be usable when on mobile.

**Screenshots**
![Screenshot_20211013-084049](https://user-images.githubusercontent.com/14085001/137092294-b16d2bbc-e4bc-482b-9507-d163c093e3d8.jpg)

![Screenshot_20211013-084058](https://user-images.githubusercontent.com/14085001/137092303-23456692-112a-42c2-8b16-78f349228c1b.jpg)

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.8
 - Deployment: docker-compose using traefik.

**Comment by BeryJu** [comment]
after the initial changes it looks like this 
![image](https://user-images.githubusercontent.com/1932513/137106657-24785060-91d8-47b4-a22f-e287b0642f77.png)

the settings are still a bit scuffed, but I think they're usable for now 
![image](https://user-images.githubusercontent.com/1932513/137106727-19739c4d-5afc-4324-bcf3-ca035fa5252c.png)
