### ISSUE TITLE
Example for how to use authentik to allow OIDC into k8s-dashboard

### ISSUE THREAD

**Issue by ahgraber** [goauthentik/authentik#1626]
**Is your feature request related to a problem? Please describe.**
Based on what I can see, Authentik has all of the requirements to act as an IDP/OAUTH provider against my k3s/k8s cluster, specifically to allow logins into k8s-dashboard.  However, as a relative noob, I'm having trouble understanding both the Authentik docs and k8s-dashboard docs and understanding how to integrate both to log into the dashboard

**Describe the solution you'd like**
I'd love to see a clear example (blog post, documentation, or example markdown file) of how to use Authentic as an OAuth provider to k8s dashboard (or the k8s cluster api-server more generally)

**Describe alternatives you've considered**
It seems that Dex has plugins that can do this, but I didn't want to have to install Authentik and Dex (and I'm also unsure what the differences or overlap is between Authentik and Dex)

Thanks for considering this!

**Comment by BeryJu** [comment]
Hi,

I don't think you can directly use the k8s dashboard with OIDC, as it doesn't natively support it. You can use the k8s dashboard behind the authentik proxy to get an SSO-experience, however you still need a K8s token to authenticate to the Dashboard.

I'd suggest looking at Rancher (even though it is much larger and more complex) for a full SSO solution
