### ISSUE TITLE
Changes in property mappings revert to defaults after updates

### ISSUE THREAD

**Issue by AminSaqi** [goauthentik/authentik#1628]
**Describe the bug**
In `Property Mappings`, I append a line in `authentik default OAuth Mapping: OpenID 'profile'` Epression to get user attributes:

`"attributes": request.user.attributes,`

So the complete expression is as the following:

```
return {
    # Because authentik only saves the user's full name, and has no concept of first and last names,
    # the full name is used as given name.
    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(" ")`
    "name": request.user.name,
    "given_name": request.user.name,
    "family_name": "",
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    # groups is not part of the official userinfo schema, but is a quasi-standard
    "groups": [group.name for group in request.user.ak_groups.all()],
    "attributes": request.user.attributes,
}
```

However, after each system update, or even sometimes occasionally, the expression reverts to its default - i.e. without my appended line.

The latest update I performed was from 2021.8.4 to 2021.9.8 and the appended line disappeared. I added it again, and today I had bug reports from some of my users about their user accounts. I checked the expression and I saw it was reverted to the default again.

**To Reproduce**
1. Change the default expression of `authentik default OAuth Mapping: OpenID 'profile'` property mapping and save it.
2. Update the authentic to a newer version.
3. Check the changed property mapping expression.
4. You see that your changes are gone.

I actually appended this line to the expression:

`"attributes": request.user.attributes,`

**Expected behavior**
Any change in property mapping expressions must persist during system updates or any other operations.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.9.8
 - Deployment: docker-compose

**Additional context**
I also see this problem sometimes without doing any intentional operations (e.g. updates).

**Comment by BeryJu** [comment]
Hi, this is intended. All property mappings with the `authentik default` prefix are "managed" by authentik itself and will periodically be reset to a constant state (This is so when for example a core field changes, I can push an updated default that will actually be applied to all users). In future versions, this will be indicated better to the user.

The "proper" way for this is to create a Custom mapping and just copy the expression and scope, and update the reference in your provider.
