### ISSUE TITLE
Provide some documentation for using Organizr with Authentik LDAP outpost

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#1665]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I´m new to LDAP and wants to connect Organizr to the Authentik LDAP Outpost. 

**Describe alternatives you've considered**
Need some information for this first.

**Additional context**

![Screenshot_20211022_151901](https://user-images.githubusercontent.com/18529293/138460376-7dd5d7a2-ff56-4a7b-bab0-a5a290f93507.png)

If you need more information, let me know!

Thanks in advance.

**Comment by Akruidenberg** [comment]
Tested. Still not working

**Comment by dstengele** [comment]
@Akruidenberg Is this running in a container itself? The LDAP outpost exposes LDAP on the standard ports 389 and 636, can you try using that?

**Comment by unixfy** [comment]
> The LDAP outpost exposes LDAP on the standard ports 389 and 636, can you try using that?

This is incorrect, the LDAP outpost exposes LDAP and LDAPS on ports 3389 and 6636 respectively. See how the port mapping works [here](https://goauthentik.io/docs/outposts/manual-deploy-docker-compose). 

@Akruidenberg Can you tell us what error you're getting from Organizr and any relevant logs from the LDAP outpost? I tried the instructions eglia provided and was able to get it working.

**Comment by dstengele** [comment]
@unixfy That's why I was aksing whether Organizr is running in a container. The Outpost is exposed on the Standard LDAP Ports _on the host_. So, to access it from outside, you would need to use those.

**Comment by unixfy** [comment]
@dstengele Ahh, understood. Sorry!

**Comment by barrelltitor** [comment]
> Something like this should work: ![image](https://user-images.githubusercontent.com/17555261/139012225-fa34d3a3-4258-48f1-8915-23abac2b153d.png)
> 
> No guarantees it will work, since I'm using the "auth proxy" functionality of organizr with the authentik proxy instead. This gives me true SSO on organizr.

How do you have the auth proxy setup? I can't seem to get it working

**Comment by ados8** [comment]
Also unable to get Organizr to SSO with Authentik.
I have just come from Authelia and never could get it working on that either.
Access to the page is fine its the login screen instead of signing the user in.
I have the proxy forward setup and Organizr using auth proxy but has never worked. 😥
