### ISSUE TITLE
Invitation links are still actives even if they have expired

### ISSUE THREAD

**Issue by Valefoth** [goauthentik/authentik#1720]
**Describe the bug**
Invitation links are still actives even if they have expired. 
They don't appear in the invitation page because they seem expired, but I can enroll as much as I want.
They are silently actives.

**To Reproduce**
1. Create an invitation with single use attribute
2. Use the link with the invitation to enroll
3. Create a new user
4. Reuse the same link
5. Create a new user
**Expected behavior**
After the user is created using the invitation link, the invitation link must not work if it's expired.

**Screenshots**
No invitations
![image](https://user-images.githubusercontent.com/38225543/139931063-e98b33b7-a197-40ed-a17b-745db46c659a.png)

But I can still enroll with my previous link
![image](https://user-images.githubusercontent.com/38225543/139932769-2eb26f8d-358a-414f-b248-c791a54fbf01.png)

**Logs**
{"event": "/if/flow/default-source-enrollment/?itoken=8e3931bf-3b5e-4da4-a5ee-xxxxxxxxxxxx", "host": "192.xxx.xxx.xxx", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 25, "request_id": "67f43cd5254241059d5c8157f5a27332", "runtime": 1926, "scheme": "https", "size": 0.025, "status": 200, "timestamp": "2021-11-02T19:25:09.780250", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"}

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.1
 - Deployment: helm
 - Chart version : 4.0.0

**Comment by BeryJu** [comment]
I'm not able to reproduce this, imported https://goauthentik.io/docs/flow/examples `Enrollment (2 Stage)​`, added an invitation stage with order 1 and ` Continue flow without invitation` disabled, and created a single-use invitation.

Afterwards I opened the URL in incognito, enrolled a new user, and retired the URL, which only gave me an error

**Comment by Valefoth** [comment]
Ok so it's not working out of the box, we need a bit of configuration. But I think invitations should not work without an invitation stage in the flow. Is this possible by default to check if flow has invitation stage before creating an invitation link or something like that ?

**Comment by BeryJu** [comment]
> Ok so it's not working out of the box, we need a bit of configuration. But I think invitations should not work without an invitation stage in the flow. Is this possible by default to check if flow has invitation stage before creating an invitation link or something like that ?

I decided to just show it more clearly for the admin when they need to add an invitation stage, and also prevent admins from copying links that won't work as expected.
