### ISSUE TITLE
Allow Proxy outpost to receive HTTP Basic auth

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1745]
**Describe the bug**
I'm trying to protect tvheadend instance with Authentik, but some endpoints of that require logging in via Basic Auth to Authentik, not to the application itself which seems is not what the "basic auth" option in provider does.

**To Reproduce**
1. Deploy Authentik
2. Deploy tvheadend with noacl argument.
3. Setup provider and app for single app in Authentik with basic auth ticked.
4. Setup Traefik ForwardAuth
5. Try to use VLC to stream media from tvheadend or see headers with Postman.
6. See that there is absolutely no Authorization header which needs to exist

**Expected behavior**
I would have expected there to be an Authorization header before logging into Authentik rather than after logging-in. Kinda defeats the purpose.

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/140673370-ecbd37b3-86d9-467b-998c-c900ffa03cb2.png)

**Logs**
```
{"event":"/akprox/auth/traefik","host":"172.18.0.4:44410","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"livetv","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.27 Safari/537.36 Edg/96.0.1054.8","request_username":"sm@<snip>","runtime":"0.179","size":0,"status":0,"timestamp":"2021-11-08T02:01:01Z","upstream":"","vhost":"tv.<snip>.fi"}
{"event":"hello'd","level":"trace","logger":"authentik.outpost.ak-api-controller","loop":"ws-health","timestamp":"2021-11-08T02:01:07Z"}
{"event":"passing to application mux","host":"tv.<snip>.fi","level":"trace","logger":"authentik.outpost.proxyv2","timestamp":"2021-11-08T02:01:08Z"}
{"event":"setting http basic auth","level":"trace","logger":"authentik.outpost.proxy.bundle","provider":"livetv","timestamp":"2021-11-08T02:01:08Z","username":"sm@<snip>"}
{"event":"/akprox/start","host":"172.18.0.4:44494","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"livetv","request_protocol":"HTTP/1.1","request_useragent":"VLC/3.0.16 LibVLC/3.0.16","runtime":"0.147","size":303,"status":302,"timestamp":"2021-11-08T02:09:21Z","upstream":"","vhost":"tv.<snip>.fi"}
{"event":"passing to application mux","host":"tv.<snip>.fi","level":"trace","logger":"authentik.outpost.proxyv2","timestamp":"2021-11-08T02:09:22Z"}
{"event":"Redirecting to login","level":"debug","logger":"authentik.outpost.proxy.bundle","provider":"livetv","timestamp":"2021-11-08T02:09:22Z","url":"https://tv.samip.fi/akprox/start"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.2
 - Deployment: main server in Kubernetes, seperate outpost on Docker compose

**Additional context**

**Comment by BeryJu** [comment]
I'm not 100% sure what I want to do with this, it would be pretty easy to add an endpoint which can accept basic auth, use the same FlowExecutor as LDAP does, and then returns a session token based on the same claims. I'm not sure if every request to the outpost should accept basic auth and trigger this, since due to the way the FlowExecutor works it could be somewhat slow.

**Comment by AlphaJack** [comment]
Another use case could be an uptime monitoring system that needs to check a protected location, for instance creating a dedicated user for Uptime-Kuma.

**Comment by samip5** [comment]
@BeryJu Any chance of getting this implemented?

**Comment by weikinhuang** [comment]
this would also be very useful for api requests to backend apps via curl to accept a username:app_password or bearer jwt
