### ISSUE TITLE
Custom scope `additionalHeaders` do not show up in forward auth headers

### ISSUE THREAD

**Issue by gabe565** [goauthentik/authentik#1762]
**Describe the bug**
6036d883924ea9fb65fcce9a8e85ebd17325c79d added support for proxy scopes, but headers do not populate when a scope adds `additionalHeaders` to a forward auth provider.

**To Reproduce**
1. Create a scope mapping that adds an entry to the additional headers:
```
return {
  "ak_proxy": {
    "user_attributes": {
      "additionalHeaders": {
        "X-Test-Header": "Test"
      }
    }
  }
}
```
2. Enable the scope on a forward auth proxy provider
3. Access `/akprox/auth?nginx`
4. Response headers do not contain `X-Test-Header`

**Expected behavior**
`X-Test-Header` should be populated in the provider response.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.3
 - Deployment: Helm

**Additional context**
To create the scope, I referenced https://github.com/goauthentik/authentik/issues/1255#issuecomment-955792280.

Also, I have used `additionalHeaders` in user attributes, so I know they typically work and that there isn't a proxy issue preventing them from populating.

**Comment by BeryJu** [comment]
Which scope name did you give the custom scope? I just tried this setup and it worked fine (allthough not using forward auth, but the main logic to get the headers is the same)

The scope name needs to be `ak_proxy` since the proxy only requests the scopes `openid email profile ak_proxy`

**Comment by gabe565** [comment]
Thanks for the reply! I must have misunderstood what enabling a scope on a provider does. Changing the scope name to `ak_proxy` does populate the correct header! Closing this issue.

**Comment by BeryJu** [comment]
> Thanks for the reply! I must have misunderstood what enabling a scope on a provider does. Changing the scope name to `ak_proxy` does populate the correct header! Closing this issue.

Good point, its not really documented anywhere, I'll see if I can make it so the outpost requests all the scopes that have been assigned to it.

**Comment by gabe565** [comment]
That sounds good. My goal here is to add a header that only shows up for a specific proxy and differs per-user. I'm pre-configuring an API key for [Shlink](https://shlink.io/) by adding the key to each user's Authentik attributes, then filling that in when a user requests [`servers.json`](https://shlink.io/documentation/shlink-web-client/pre-configuring-servers/#pre-configuring-servers).

After changing the scope's name to `ak_proxy`, it shows up for every proxy provider just like when I had the header configured in each user's attributes. It would be amazing if the outpost could request the scopes that have been assigned to the provider like you mentioned above.

**Comment by BeryJu** [comment]
> After changing the scope's name to `ak_proxy`, it shows up for every proxy provider just like when I had the header configured in each user's attributes. It would be amazing if the outpost could request the scopes that have been assigned to the provider like you mentioned above.

It should only show up for the providers where you select your custom property mapping, but yes the dynamic requestsed scopes will be in 10.4
