### ISSUE TITLE
POST /api/v3/flows/executor/login/ (OPNsense: LDAP fails on accounts with DUO)

### ISSUE THREAD

**Issue by JosephKav** [goauthentik/authentik#1774]
**Describe the bug**
LDAP seems to fail on Authentik accounts with DUO auth added. Following the steps for a new user (without DUO) works as expected

**To Reproduce**
1. Add Authentik LDAP to OPNsense
2. Use the tester with Authentik creds
3. Gives 'Authentication failed. ldap_error: Invalid credentials' + 9x 'General system exception' in Authentik's event logs

**Expected behavior**
- Display success and give the LDAP users details.

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 272, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 81, in post
    if not challenge.is_valid():
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 478, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/authentik/stages/authenticator_validate/stage.py", line 64, in validate_duo
    return validate_challenge_duo(duo, self.stage.request, self.stage.get_pending_user())
  File "/authentik/stages/authenticator_validate/challenge.py", line 120, in validate_challenge_duo
    device = get_object_or_404(DuoDevice, pk=device_pk)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 78, in get_object_or_404
    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)
No DuoDevice matches the given query.
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2021.10.3
- Deployment: docker-compose

**Comment by BeryJu** [comment]
Are you using Duo authenticators?

Also could you post a screenshot or an export of the flow you're using?

**Comment by JosephKav** [comment]
I have DUO auth on the account that fails this
![image](https://user-images.githubusercontent.com/4267227/141295445-2a308a0d-2b94-40aa-b5bd-792db5f71167.png)

**Comment by BeryJu** [comment]
Can you post a screenshot of the flow you're using with the LDAP Provider?

**Comment by JosephKav** [comment]
![image](https://user-images.githubusercontent.com/4267227/141299603-32dae186-f0e7-4a7f-9023-f6108fbf0e7e.png)
I see the problem now. LDAP is using this flow, and this flow wants MFA. Since MFA breaks LDAP, I'd need a flow without MFA. Is it possible to just disable MFA on a flow for LDAP? Otherwise, I'd just need to duplicate this flow and remove MFA

**Comment by BeryJu** [comment]
MFA shouldn't break on LDAP, as long as you're using Duo

**Comment by JosephKav** [comment]
So is the issue possibly in Authentik's handling of DUO auth on LDAP?

**Comment by JosephKav** [comment]
Hmm, I just made another flow and bound it to the LDAP provider, but no luck. Seems to be the same error
![image](https://user-images.githubusercontent.com/4267227/141302416-c62e32e2-6a15-45d0-adfe-587f83239936.png)

```
Context
{
    "geo": {
        "lat": 51.5646,
        "city": "Ilford",
        "long": 0.0898,
        "country": "GB",
        "continent": "EU"
    },
    "message": "Traceback (most recent call last):\n  File \"/authentik/flows/views/executor.py\", line 272, in post\n    stage_response = self.current_stage_view.post(request, *args, **kwargs)\n  File \"/authentik/flows/stage.py\", line 81, in post\n    if not challenge.is_valid():\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py\", line 220, in is_valid\n    self._validated_data = self.run_validation(self.initial_data)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py\", line 419, in run_validation\n    value = self.to_internal_value(data)\n  File \"/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py\", line 478, in to_internal_value\n    validated_value = validate_method(validated_value)\n  File \"/authentik/stages/authenticator_validate/stage.py\", line 64, in validate_duo\n    return validate_challenge_duo(duo, self.stage.request, self.stage.get_pending_user())\n  File \"/authentik/stages/authenticator_validate/challenge.py\", line 120, in validate_challenge_duo\n    device = get_object_or_404(DuoDevice, pk=device_pk)\n  File \"/usr/local/lib/python3.9/site-packages/django/shortcuts.py\", line 78, in get_object_or_404\n    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)\nNo DuoDevice matches the given query.",
    "http_request": {
        "args": {
            "query": "goauthentik.io%2Foutpost%2Fldap=true"
        },
        "path": "/api/v3/flows/executor/login/",
        "method": "POST"
    }
}
User
{
    "pk": 2,
    "email": "",
    "username": "AnonymousUser"
}
```

**Comment by BeryJu** [comment]
Are you sure the LDAP Outpost updated correctly? In the logs its still saying flow with the slug `login` is used

**Comment by JosephKav** [comment]
Ah yeah. Maybe I didn't wait long enough after changing the provider's flow. I just went to the edit again and clicked save, then tried the OPNsense tester again and it worked. The OPNsense tester now gives `User: josephkav authenticated successfully.`

**Comment by eglia** [comment]
I see the same behaviour with TOTP 2FA. I created a special login flow without 2FA for LDAP, I thought that's how it's supposed to work...

**Comment by BeryJu** [comment]
@JosephKav could you test the latest Outpost image `goauthentik.io/dev-ldap:gh-master` ? that should fix the Duo Issue (not tested yet since I still cant access my duo account)

@eglia are you also getting an error? MFA with LDAP itself is only supported, but only with Duo

**Comment by JosephKav** [comment]
> @JosephKav could you test the latest Outpost image `goauthentik.io/dev-ldap:gh-master` ? that should fix the Duo Issue (not tested yet since I still cant access my duo account)
> 
> @eglia are you also getting an error? MFA with LDAP itself is only supported, but only with Duo

Yeah sure. Can I deploy that version with the Web UI?

**Comment by BeryJu** [comment]
You can just use the beta instructions and substitute gh-next for gh-master https://goauthentik.io/docs/installation/beta

**Comment by JosephKav** [comment]
On gh-master, it no longer errors, but a login fails with 'Wrong username or password.' and the tester fails with
```
The following input errors were detected:
    Authentication failed.
    error: User DN not found
```
Logs show a login to the service account

**Comment by BeryJu** [comment]
🤔

**Comment by BeryJu** [comment]
@JosephKav can you check the logs of both outpost and main server? I just got access to duo back, and was able to successfully authenticate into LDAP with the default flow

**Comment by JosephKav** [comment]
```
Nov 11 22:01:43 authentik Authentik-Server[801]: {"current_stage": "<AuthenticatorValidateStage: Stage authentication-flow-mfa>", "event": "f(exec): Current stage", "flow_slug": "login", "host": "authentik.company", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 27, "request_id": "14d9aa3d407543929c90ae88c2f1a445", "timestamp": "2021-11-11T22:01:43.274630"}
Nov 11 22:01:43 authentik Authentik-Server[801]: {"event": "f(exec): Passing GET", "flow_slug": "login", "host": "authentik.company", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 27, "request_id": "14d9aa3d407543929c90ae88c2f1a445", "stage": "<AuthenticatorValidateStage: Stage authentication-flow-mfa>", "timestamp": "2021-11-11T22:01:43.276008", "view_class": "authentik.stages.authenticator_validate.stage.AuthenticatorValidateStageView"}
Nov 11 22:01:43 authentik Authentik-Server[801]: {"devices": "<generator object devices_for_user at 0x7f24bbc092e0>", "event": "Got devices for user", "host": "authentik.company", "level": "debug", "logger": "authentik.stages.authenticator_validate.stage", "pid": 27, "request_id": "14d9aa3d407543929c90ae88c2f1a445", "timestamp": "2021-11-11T22:01:43.277064"}
Nov 11 22:01:43 authentik Authentik-Server[801]: {"event": "Authenticator not configured, skipping stage", "host": "authentik.company", "level": "debug", "logger": "authentik.stages.authenticator_validate.stage", "pid": 27, "request_id": "14d9aa3d407543929c90ae88c2f1a445", "timestamp": "2021-11-11T22:01:43.290718"}
Nov 11 22:01:43 authentik Authentik-Server[801]: {"event": "f(exec): Stage ok", "flow_slug": "login", "host": "authentik.company", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 27, "request_id": "14d9aa3d407543929c90ae88c2f1a445", "stage_class": "authentik.stages.authenticator_validate.stage.AuthenticatorValidateStageView", "timestamp": "2021-11-11T22:01:43.292253"}
Nov 11 22:01:43 authentik Authentik-Server[801]: {"event": "f(exec): Continuing with next stage", "flow_slug": "login", "host": "authentik.company", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 27, "remaining": 1, "request_id": "14d9aa3d407543929c90ae88c2f1a445", "timestamp": "2021-11-11T22:01:43.294838"}
Nov 11 22:01:43 authentik Authentik-Server[801]: {"event": "/api/v3/flows/executor/login/?query=goauthentik.io%252Foutpost%252Fldap%3Dtrue", "host": "172.17.0.2", "level": "info", "location": "/api/v3/flows/executor/login/?query=goauthentik.io%252Foutpost%252Fldap%3Dtrue", "logger": "authentik.asgi", "method": "GET", "pid": 27, "request_id": "14d9aa3d407543929c90ae88c2f1a445", "runtime": 0, "scheme": "https", "size": 0.137, "status": 302, "timestamp": "2021-11-11T22:01:43.304929", "user": "", "user_agent": "authentik-outpost@2021.10.3 (build=00324f922d1c913087b6a4352eef6733c72572ed)"}
```

THere's more but this looks like it's the MFA bit. No clue why it's not `Authenticator not configured, skippng stage` or `/api/v3/flows/executor/login/?query=goauthentik.io%252Foutpost%252Fldap%3Dtrue"`

**Comment by BeryJu** [comment]
it'll say `Authenticator not configured, skippng stage` since the default mfa validator stage doesn't allow Duo Devices, since Duo devices need extra setup. If you enable that it should work.

**Comment by JosephKav** [comment]
Enable what? `Duo Authenticators` is already in my `Device Classes` for `authentication-flow-mfa`
![Screenshot from 2021-11-11 22-28-36](https://user-images.githubusercontent.com/4267227/141378229-919573d0-db05-42e1-8aa4-94a071d03497.png)

**Comment by bbrendon** [comment]
@JosephKav  are you getting the same stack trace as you were initially? I was just working on this with Active Directory and was getting a stack trace. Unfortunately I deleted the setup before I found this issue along with the stack trace but the final error was not the one you have listed.
