### ISSUE TITLE
How to stop users from changing their own usernames?

### ISSUE THREAD

**Issue by redstonedesigner** [goauthentik/authentik#1789]
**Describe your question/**
A clear and concise description of what you're trying to do.

I'm trying to deploy Authentik in an environment, however we do not want our users to be able to change their own usernames.

**Relevant infos**
i.e. Version of other software you're using, specifics of your setup

Authentik Source: Authentik Built-In
Admins should still be able to change usernames both through the UI and Admin API, however we would like to disable username changes for the end user.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.4
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Check the attributes on this page: https://goauthentik.io/docs/user-group/user

They can be set on groups so you don't have to add them to each individual user.

**Comment by redstonedesigner** [comment]
For most environments, this would not be the desired behaviour.  Would it be possible to consider changing the default implementation to deny username changes?
This is because most websites will validate against a username or email address, and therefore a user changing their information may inadvertently result in loss of access to services.

**Comment by BeryJu** [comment]
This is going to be configurable in the next version.
