### ISSUE TITLE
Login page customization

### ISSUE THREAD

**Issue by klejejs** [goauthentik/authentik#1790]
**Describe your question**
Is there an option to customize login page, e.g. hiding Authentik logo, link to docs page? No offence, it looks great, I just don't want everyone knowing that I am running Authentik as auth option when they open the page, as I feel it would make my server safer from people trying to hack it.

**Version and Deployment (please complete the following information):**
 - authentik version:  2021.10.4
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Hi,  the logo can be customised using Tenants, in the Admin interface sidebar. The links can also be configured, however currently only via config file. Starting in 2021.10.5 you will be able to use JSON strings as environment variable values to configure those too.

**Comment by klejejs** [comment]
Thanks very much for your response! Is there any place where this is documented more than in docs page [here](https://goauthentik.io/docs/tenants#branding)?

**Comment by BeryJu** [comment]
It's not, no

**Comment by klejejs** [comment]
Thank you! One last question - do you think it would make sense to allow this to be configurable too, or would you want to keep it for "advertizing" purposes?
https://github.com/goauthentik/authentik/blob/e587c53e185c3c49d02fc577c92df6db0a581939/web/src/flows/FlowExecutor.ts#L406-L415

**Comment by BeryJu** [comment]
That's exactly the reason why that part is static, yeah
