### ISSUE TITLE
Send email again in recovery flow doesn't work

### ISSUE THREAD

**Issue by rizwan95** [goauthentik/authentik#1791]
**Describe the bug**
In the recovery flow, when the user selects "Send email again." option, it doesn't work and throws the following UI error.
`No variant of ChallengeTypes exists with 'component=undefined'`

**To Reproduce**
1. Go to login page
2. Try to recover your account
3. Enter your email address and hit send email
4. Now, hit "Send email again." option

**Expected behavior**
Second time the email should have been triggered but it throws an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/10910174/141684442-b75d993c-621c-44be-8727-14ad31e16ed2.png)

**Logs**

`
{"challenge": "EmailChallengeResponse(None, data={'component': 'ak-stage-email'}, stage=<authentik.stages.email.stage.EmailStageView object>):\n    component = CharField(default='ak-stage-email')", "event": "Challenge Fail", "host": "auth.mydomain.com", "level": "warning", "logger": "authentik.flows.stage", "pid": 19, "request_id": "490ee8d0f5014fabbbc780b330efda10", "timestamp": "2021-11-14T14:10:49.196972"}

{"binding": "<FlowStageBinding: Flow-stage binding 20 to Flow Default recovery flow (default-recovery-flow)>", "errors": {"response_errors": {"non_field_errors": [{"string": ["This field may not be blank."]}]}}, "event": "f(ch): invalid challenge response", "host": "auth.mydomain.com", "level": "warning", "logger": "authentik.flows.stage", "pid": 20, "request_id": "bc6e4026496443bba45ac9cac46ddae8", "stage_view": "<authentik.stages.email.stage.EmailStageView object at 0x7f6d7c646190>", "timestamp": "2021-11-14T14:06:53.902370"}
`

**Comment by mmospanenko** [comment]
got the same issue (2024.6.4), added flow using guide https://www.youtube.com/watch?v=NKJkYz0BIlA
but after click on recovery (sending new password) have message`No variant of ChallengeTypes exists with 'component=undefined'`
