### ISSUE TITLE
Verification certificate not working in Nextcloud with SAML authentication 

### ISSUE THREAD

**Issue by immortaly007** [goauthentik/authentik#1795]
**Describe your question/**
Over the weekend, I've started configuring Authentik. One of the apps with which I wish to authentik is NextCloud. To do this, I'm following the instructions on: https://goauthentik.io/docs/integrations/services/nextcloud/index/
However, after completing everything, Authentik gives the error `Verification Certificate configured, but request is not signed.` when trying to log in.

**Relevant infos**
Both Authentik and Nextcloud are running on the same physical machine using docker containers. Traefik is used as the reverse proxy, so that auth.mydomain.com is serving Authentik 2021.10.4 (based on the official docker-compose file), and nextcloud.mydomain.com is serving Nextcloud 22.1.1. 

**Screenshots**
The error message:
![image](https://user-images.githubusercontent.com/5663691/141794203-e8edec8d-f1da-424b-90d9-558d14444f88.png)

Authentik provider config:
![image](https://user-images.githubusercontent.com/5663691/141795196-4d6186e8-43fe-49a6-8cff-cb93d40a44c0.png)

Authentik Application config:
![image](https://user-images.githubusercontent.com/5663691/141795572-dca546af-7744-4693-bdde-b1a3850b400c.png)

Nextcloud config:
![image](https://user-images.githubusercontent.com/5663691/141795408-609324af-206f-4c81-87a3-0d342f63f664.png)

**Logs**
```
{
    "message": "Verification Certificate configured, but request is not signed.",
    "provider": {
        "pk": 1,
        "app": "authentik_providers_saml",
        "name": "Nextcloud SAML",
        "model_name": "samlprovider"
    }
}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.4
 - Deployment: docker-compose
 
**Additional context:**
I noticed that sometimes, instead of the "Verification Certificate configured, but request is not signed." error, Nextcloud gives the error: `Account not provisioned. Your account is not provisioned, access to this service is thus not possible`. Not sure when I get into which situation.

**Comment by BeryJu** [comment]
In the documentation it says to select the *Signing Keypair* but in your screenshot both keypairs are selected.

**Comment by rperpe** [comment]
@immortaly007 Were you able to resolve your issue? If OIDC instead of SAML is an acceptable alternative for you I could provide a running configuration example.

**Comment by incoggnito** [comment]
Same issue here, is there any solution yet?

**Comment by ikogan** [comment]
You actually _can_ select both key pairs I believe, but the certificates need to be different. You need to generate _one_ certificate for Nextcloud to use, and place it in the "Service Provider Data" that you don't have expanded up there and then add that certificate to Authentik, selecting it in "Verification Certificate".

Put another way: the "Verification Certificate" is the one Nextcloud uses to sign things and Authentik verifies and the "Signing Certificate" is the one Authentik uses to sign things and Nextcloud verifies.
