### ISSUE TITLE
Unable to assign same LDAP provider to multiple applications

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1818]
**Describe the bug**
Unable to assign same LDAP provider to multiple applications due to Authentik expecting it to be unique

**To Reproduce**
1. Create LDAP provider
2. Create multiple applications
3. Try to set all of the applications to the LDAP provider
4. See it fail due to not being unique

**Expected behavior**
I would have expected to be able to assign same LDAP provider to multiple apps

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/142723989-0828ec35-1cef-46b5-89d7-afafe0d03978.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.4
 - Deployment: Helm via GitOps (Flux)

**Comment by BeryJu** [comment]
This is the intended design currently, there is a 1:1 relationship for application to provider. Changing this would be a pretty big undertaking, and it is on the roadmap for "eventually", but currently you need to create an application for each provider, and then select each application in the outpost.
