### ISSUE TITLE
Docs for OnlyOffice integration

### ISSUE THREAD

**Issue by ArjonBu** [goauthentik/authentik#1820]
Would it be possible to add documentation for [OnlyOffice](https://helpcenter.onlyoffice.com/administration/control-panel-sso-description.aspx) SAML integration? 

I can provide access to my OnlyOffice instance if necessary.

**Comment by ArjonBu** [comment]
@BeryJu thank you for the quick docs. Unfortunately I am getting the below error: 

```
{"message":"parseLoginResponse failed ERR_EMPTY_ASSERTION","level":"error"}
{"message":"onLoginResponse ERR_EMPTY_ASSERTION","level":"error"}
```

Maybe there is something missing from the docs?

**Comment by BeryJu** [comment]
Can you post your OnlyOffice settings? Did you set the signing certificate on the Provider as described?

**Comment by ArjonBu** [comment]
@BeryJu Yes, the signing certificate is set. It's the default one. Also it was imported successfully to Onlyoffice using the metadata import. https://imgur.com/a/xY5rhmz

**Comment by BeryJu** [comment]
Make sure the user you're using in authentik has a Name and Email set, as this is required by onlyoffice

**Comment by ArjonBu** [comment]
The user has a username, name and email. (it's not assigned to any group though but that shouldn't matter)

**Comment by ArjonBu** [comment]
@BeryJu any idea what could be the issue? I have been trying a lot of things to make it work but no luck

**Comment by BeryJu** [comment]
I've not been able to reproduce the error you're running into, can you try logging in with https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace?hl=en ?

**Comment by ArjonBu** [comment]
@BeryJu I think it might be my Nginx reverse proxy in front of the application. I opened an issue [here](https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/134). Linking it just in case other people have the same issue. 

Thank you for your support!

**Comment by BeryJu** [comment]
Could be the case, I was always testing directly against the container without any reverse proxy
