### ISSUE TITLE
Choose which authenticator to set up

### ISSUE THREAD

**Issue by WebDesignerlol** [goauthentik/authentik#1843]
**Describe the solution you'd like**
Upon login or enrollment, I would love to have a feature to enable a choice of which authentication method the user would like to configure, prior to triggering a flow such as WebAuthn  or TOTP.

**Describe alternatives you've considered**
I have considered using a flow that fails and then on failure continuing to the next flow, however, this doesn't seem to work (or I am doing it wrong, but I have scoured through documentation and find it). There is an option for "On Restart" but all options involve failing or triggering a configuration flow. I can only make flows restart or retry. I would like to continue without restarting a flow, or alternatively offer a way to select an authenticator to setup without forcing one immediately. As I understand, this may? be possible with the user prompts section, however, the usage of it is not too clear to me as an end user. If it is possible, perhaps clarifying the exact usage in better terms may be beneficial.

**Comment by BeryJu** [comment]
This is a good point/question, currently you could create a flow with a prompt stage for example and based off of that allow the user to enroll themselves, but its not ideal.

I'm not sure how this would be best solved, probably an `authenticator_setup` stage with prompts the user.

However that would cause issues when redirecting to the next, actual setup stage, and the user decides to go back, as thats not currently possible.

The other option would be to merge all `authenticator_` stages into the `authenticator_setup` stage, and do it all internally. I was trying to get around this, the stages are all separated on purpose.
