### ISSUE TITLE
[Question] About forward auth with Traefik

### ISSUE THREAD

**Issue by JokerQyou** [goauthentik/authentik#1850]
**Describe your question/**

My case is rather simple:

- I have multiple apps (let's simplify to 2 apps) that needs to be protected. They are accessible via subdomains like `app1.domain.tld`.
- I have authentik running at a standalone subdomain `auth.domain.tld`.
- Internally authentik and these 2 apps are using traefik to do routing. They are connected to the same network as traefik.

**Relevant infos**

- I configured the embedded outpost with a `Proxy` provider. The details:
  - Proxy provider config:
    - Authorization flow: `default-provider-authorization-explicit-consent`
    - External host: `https://auth.domain.tld`. Because I have multiple apps on different subdomains, I left the default value here (same as authentik host).
    - Cookie domain is left empty.
    - Token validity: `hours=48`
  - I also created an application to use the proxy provider. I have not set its UI settings (launch URL, etc.).
  - Embedded outpost config:
    - Type: `Proxy`
    - Applications: I selected the application paired with the proxy provider.
    - Configuration: I changed `authentik_host` to `auth.domain.tld`, and everything else remain unchanged.

**Screenshots**

Sorry but there is no screenshot.

**Logs**

Here's  the authentik server log. I've censored some private information.

<details>
<pre><code>authentik-server_1       | {"event":"passing to single app mux","host":"app1.domain.tld","level":"warning","logger":"authentik.outpost.proxyv2","timestamp":"2021-11-28T07:07:57Z"}
authentik-server_1       | {"event":"/akprox/auth/traefik","host":"<HOST>","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"SSO-Proxy","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36","runtime":"2.736","size":74,"status":307,"timestamp":"2021-11-28T07:07:57Z","upstream":"","vhost":"app1.domain.tld"}
authentik-server_1       | {"event":"/akprox/start","host":"<HOST>","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"SSO-Proxy","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36","request_username":"USER@domain.tld","runtime":"1.476","size":287,"status":302,"timestamp":"2021-11-28T07:07:57Z","upstream":"","vhost":"auth.domain.tld"}
authentik-server_1       | {"event": "/application/o/authorize/?client_id=JIdl7PiflfrADZEpm4MKsxnic9vj39GtFo8Na76h&redirect_uri=https%3A%2F%2Fauth.domain.tld%2Fakprox%2Fcallback&response_type=code&scope=ak_proxy+profile+openid+email&state=5IFR45lflkryEOoinjy1KsVLXbfHo1n1O9Sqt%2B8JU3M", "host": "172.68.144.62", "level": "info", "location": "/if/flow/default-provider-authorization-explicit-consent/?client_id=JIdl7PiflfrADZEpm4MKsxnic9vj39GtFo8Na76h&redirect_uri=https%3A%2F%2Fauth.domain.tld%2Fakprox%2Fcallback&response_type=code&scope=ak_proxy+profile+openid+email&state=5IFR45lflkryEOoinjy1KsVLXbfHo1n1O9Sqt%2B8JU3M", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "b197a6de0aa8449faa10c0c32ca09a96", "runtime": 0, "scheme": "https", "size": 0.106, "status": 302, "timestamp": "2021-11-28T07:07:58.349293", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/if/flow/default-provider-authorization-explicit-consent/?client_id=JIdl7PiflfrADZEpm4MKsxnic9vj39GtFo8Na76h&redirect_uri=https%3A%2F%2Fauth.domain.tld%2Fakprox%2Fcallback&response_type=code&scope=ak_proxy+profile+openid+email&state=5IFR45lflkryEOoinjy1KsVLXbfHo1n1O9Sqt%2B8JU3M", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "5b6aef009fa54ddfbf1861b2849dfcaf", "runtime": 1869, "scheme": "https", "size": 0.035, "status": 200, "timestamp": "2021-11-28T07:07:59.320085", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event":"/static/dist/poly.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:07:59Z","took":41557996}
authentik-server_1       | {"event":"/static/dist/flow/locale-en-346a0654.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:07:59Z","took":3802210}
authentik-server_1       | {"event":"/static/dist/flow/FlowInterface.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:00Z","took":20886865}
authentik-server_1       | {"event":"/static/dist/flow/locale-pseudo-LOCALE-e04f7e5d.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:00Z","took":43520592}
authentik-server_1       | {"event":"/static/dist/flow/api-8bcafd64.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:00Z","took":125236625}
authentik-server_1       | {"event": "/api/v3/root/config/", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "fa27379b66a84cb59b1635e5b46567f5", "runtime": 260, "scheme": "https", "size": 0.101, "status": 200, "timestamp": "2021-11-28T07:08:00.152753", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/api/v3/core/tenants/current/", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19, "request_id": "6b7ce7e5610547ce82b8fc77cd52a0b1", "runtime": 474, "scheme": "https", "size": 0.119, "status": 200, "timestamp": "2021-11-28T07:08:00.171102", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event":"/static/dist/flow/vendor-f146a7d1.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:00Z","took":203021670}
authentik-server_1       | {"event":"/static/dist/flow/locale-fr_FR-5c6930b4.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:00Z","took":9332224}
authentik-server_1       | {"event": "/api/v3/flows/executor/default-provider-authorization-explicit-consent/?query=client_id%3DJIdl7PiflfrADZEpm4MKsxnic9vj39GtFo8Na76h%26redirect_uri%3Dhttps%253A%252F%252Fauth.domain.tld%252Fakprox%252Fcallback%26response_type%3Dcode%26scope%3Dak_proxy%2Bprofile%2Bopenid%2Bemail%26state%3D5IFR45lflkryEOoinjy1KsVLXbfHo1n1O9Sqt%252B8JU3M", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19, "request_id": "8937fbbf55024640bf2520f7d1850ed9", "runtime": 536, "scheme": "https", "size": 0.05, "status": 200, "timestamp": "2021-11-28T07:08:00.429482", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/api/v3/flows/executor/default-provider-authorization-explicit-consent/?query=client_id%3DJIdl7PiflfrADZEpm4MKsxnic9vj39GtFo8Na76h%26redirect_uri%3Dhttps%253A%252F%252Fauth.domain.tld%252Fakprox%252Fcallback%26response_type%3Dcode%26scope%3Dak_proxy%2Bprofile%2Bopenid%2Bemail%26state%3D5IFR45lflkryEOoinjy1KsVLXbfHo1n1O9Sqt%252B8JU3M", "host": "172.68.144.62", "level": "info", "location": "/api/v3/flows/executor/default-provider-authorization-explicit-consent/?query=client_id%3DJIdl7PiflfrADZEpm4MKsxnic9vj39GtFo8Na76h%26redirect_uri%3Dhttps%253A%252F%252Fauth.domain.tld%252Fakprox%252Fcallback%26response_type%3Dcode%26scope%3Dak_proxy%2Bprofile%2Bopenid%2Bemail%26state%3D5IFR45lflkryEOoinjy1KsVLXbfHo1n1O9Sqt%252B8JU3M", "logger": "authentik.asgi", "method": "POST", "pid": 19, "request_id": "65abdbff2a754659bbd2ef59b6a1828b", "runtime": 0, "scheme": "https", "size": 0.076, "status": 302, "timestamp": "2021-11-28T07:08:02.459853", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/api/v3/flows/executor/default-provider-authorization-explicit-consent/?query=client_id%3DJIdl7PiflfrADZEpm4MKsxnic9vj39GtFo8Na76h%26redirect_uri%3Dhttps%253A%252F%252Fauth.domain.tld%252Fakprox%252Fcallback%26response_type%3Dcode%26scope%3Dak_proxy%2Bprofile%2Bopenid%2Bemail%26state%3D5IFR45lflkryEOoinjy1KsVLXbfHo1n1O9Sqt%252B8JU3M", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19, "request_id": "480e7bcb958e4958b83d18a536f017ec", "runtime": 195, "scheme": "https", "size": 0.348, "status": 200, "timestamp": "2021-11-28T07:08:03.216975", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/application/o/token/", "host": "127.0.0.1", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 19, "request_id": "a6dbedb9baac40548ea78f90ce74339c", "runtime": 1919, "scheme": "http", "size": 0.115, "status": 200, "timestamp": "2021-11-28T07:08:03.747376", "user": "", "user_agent": "authentik-outpost@2021.10.4 (build=tagged) (provider=SSO-Proxy)"}
authentik-server_1       | {"event":"/akprox/callback?code=3f3123216a8c49d5b997e83a5f7bcef8\u0026state=5IFR45lflkryEOoinjy1KsVLXbfHo1n1O9Sqt%2B8JU3M","host":"<HOST>","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"SSO-Proxy","request_protocol":"HTTP/1.1","request_useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36","runtime":"123.244","size":48,"status":302,"timestamp":"2021-11-28T07:08:03Z","upstream":"","vhost":"auth.domain.tld"}
authentik-server_1       | {"event": "/", "host": "172.68.144.62", "level": "info", "location": "/if/user/", "logger": "authentik.asgi", "method": "GET", "pid": 19, "request_id": "e327f96e704c43b9aef45c87aeffd1ed", "runtime": 0, "scheme": "https", "size": 0.024, "status": 302, "timestamp": "2021-11-28T07:08:04.172322", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/-/health/live/", "host": "127.0.0.1", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19, "request_id": "4fbca5525a0045c1942bece4d9de9d3f", "runtime": 0, "scheme": "http", "size": 0.018, "status": 204, "timestamp": "2021-11-28T07:08:04.273547", "user": "", "user_agent": "goauthentik.io go proxy healthcheck"}
authentik-server_1       | {"event": "/if/user/", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19, "request_id": "818477c443e7461780041a314d43f9c8", "runtime": 1735, "scheme": "https", "size": 0.027, "status": 200, "timestamp": "2021-11-28T07:08:04.596064", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event":"/static/dist/poly.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:05Z","took":24250335}
authentik-server_1       | {"event":"/static/dist/user/UserInterface.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:05Z","took":11466269}
authentik-server_1       | {"event":"/static/dist/user/locale-pseudo-LOCALE-e04f7e5d.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:05Z","took":8012667}
authentik-server_1       | {"event":"/static/dist/user/locale-en-346a0654.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:05Z","took":8281441}
authentik-server_1       | {"event":"/static/dist/user/locale-fr_FR-5c6930b4.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:05Z","took":31865756}
authentik-server_1       | {"event":"/static/dist/user/api-842805f4.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:05Z","took":35127481}
authentik-server_1       | {"event": "/api/v3/core/tenants/current/", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19, "request_id": "7e8b78bf827d41f9adbfde03db43b2b3", "runtime": 474, "scheme": "https", "size": 0.059, "status": 200, "timestamp": "2021-11-28T07:08:05.267028", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/api/v3/core/users/me/", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "84703a76089749feb63b9af2333eb23d", "runtime": 379, "scheme": "https", "size": 0.076, "status": 200, "timestamp": "2021-11-28T07:08:05.287485", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/api/v3/root/config/", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "f2005506408b4495bb1b27f285edbd64", "runtime": 260, "scheme": "https", "size": 0.099, "status": 200, "timestamp": "2021-11-28T07:08:05.310773", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/api/v3/events/notifications/?ordering=-created&page_size=1&seen=false", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "3b4d4eb3e9df47d89fdf369a9403380b", "runtime": 1313, "scheme": "https", "size": 0.149, "status": 200, "timestamp": "2021-11-28T07:08:05.361430", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event":"/static/dist/user/vendor-220d23a0.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"<HOST>","timestamp":"2021-11-28T07:08:05Z","took":179053481}
authentik-server_1       | {"event": "/api/v3/events/notifications/?ordering=-created&seen=false", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 20, "request_id": "8ae6fcc8906a4e178bbe38eabc08f690", "runtime": 1313, "scheme": "https", "size": 0.078, "status": 200, "timestamp": "2021-11-28T07:08:05.889670", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
authentik-server_1       | {"event": "/api/v3/core/applications/", "host": "172.68.144.62", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 19, "request_id": "d458cbe27b094880a4950d7c700ede4c", "runtime": 898, "scheme": "https", "size": 0.09, "status": 200, "timestamp": "2021-11-28T07:08:05.914554", "user": "<USER>", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36"}
</code></pre>
</details>

**Version and Deployment (please complete the following information):**

 - authentik version: `2021.10.4`
 - Deployment: `docker-compose`

**Additional context**

I think I end up with the same issue as [ahgraber](https://github.com/goauthentik/authentik/issues/1626#issuecomment-949976316) , that is:

- My authentik instance runs at `auth.domain.tld`
- My app runs at `app1.domain.tld`
- When I visit `app1.domain.tld`, traefik redirects me to `auth.domain.tld/akprox/start`, and I can login and authorize the app.
- But after the authorization, it then redirect me to `auth.domain.tld` instead of `app1.domain.tld`.
- If I manually visit `app1.domain.tld`, it redirects me again to `auth.domain.tld/akprox/start` to start over the authorization.

**Comment by BeryJu** [comment]
Can you post your traefik config?

**Comment by JokerQyou** [comment]
```yaml
services:
  auth-server:
    ...
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.authentik.loadbalancer.server.scheme=http"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
      - "traefik.http.routers.authentik.rule=Host(`auth.domain.tld`)"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.routers.authentik.tls.certResolver=le-prod"
      - "traefik.http.routers.authentik.entrypoints=websecure" # 443
      - "traefik.http.routers.authentik.service=authentik"
      - "traefik.http.middlewares.authentik.forwardauth.address=http://auth-server:9000/akprox/auth/traefik"
      - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=Set-Cookie,^X-authentik-"
  httpbin:
    image: kennethreitz/httpbin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpbin.rule=Host(`app1.domain.tld`)"
      - "traefik.http.routers.httpbin.entrypoints=websecure" # 443
      - "traefik.http.routers.httpbin.tls=true"
      - "traefik.http.routers.httpbin.tls.certResolver=le-prod"
      - "traefik.http.routers.httpbin.middlewares=authentik@docker"
```

Actually they are in different docker-compose projects, but all connected with the same traefik network so no problem communicating with each other.

**Comment by BeryJu** [comment]
Can you try setting the cookie domain to `domain.tld`?

**Comment by JokerQyou** [comment]
I think I've tested with cookie domain set to `domain.tld` and it resulted in an infinite redirecting. For now I've stopped my instance, I'll test again during the weekend.

**Comment by muspelheim** [comment]
@JokerQyou any news?

**Comment by JokerQyou** [comment]
I've tried the latest version and setting cookie domain to `domain.tld` indeed works now.
