### ISSUE TITLE
Can we override `context['redirect']` for oauth redirect-url value?

### ISSUE THREAD

**Issue by Bhautik0110** [goauthentik/authentik#1862]
**Describe your question/**
I had created `signin` flow, and in I last login step I added `redirect` policy. For the direct users, It redirects but I want to OAuth user should be redirected to OAuth flow specified `Redirect URL not policy specified URL. Is there any way to do this?

My other question Is `context[application]` variable determine flow is initiated by application? 

Thanks you.

**Comment by BeryJu** [comment]
> **Describe your question/** I had created `signin` flow, and in I last login step I added `redirect` policy. For the direct users, It redirects but I want to OAuth user should be redirected to OAuth flow specified `Redirect URL not policy specified URL. Is there any way to do this?

You can just redirect to `/source/oauth/login/<source slug/`

> 
> My other question Is `context[application]` variable determine flow is initiated by application?
> 

Yes, `context['application']` is set by the providers when the respective flow is initiated.
