### ISSUE TITLE
Support for Passwordless Authentication (FIDO2/WebAuthn)

### ISSUE THREAD

**Issue by mirisbowring** [goauthentik/authentik#1863]
**Is your feature request related to a problem? Please describe.**
I am using a password protected Yubikey as MFA. When Logging in, I have to type in my Username, my Passwort -> Login, then, i have to touch the yubikey, enter passphrase, touch it again and am logged in.

**Describe the solution you'd like**
I imagin a passwordless webauthn flow:
Enter username -> Login -> enter Yubikey passphrase -> touch yubikey -> success

**Comment by BeryJu** [comment]
You can do this by removing the password stage from the default authenticaiton flow, then you'll only be prompted for your yubikey. If you have users that do still have a password you can create a policy that optionally shows the password stage, based on the user having webauthn devices. The policy would look something like this

```python
from authentik.stages.authenticator_webauthn.models import WebAuthnDevice
return WebAuthnDevice.objects.filter(user=request.user, active=True).exists()
```

**Comment by mirisbowring** [comment]
Well, that makes sense! Great tool with much capabilities!

Thank you!

**Comment by daniele-athome** [comment]
Now documented here: https://goauthentik.io/docs/flow/stages/password/#passwordless-login
