### ISSUE TITLE
FR: Weekly/monthly statistics of users enrolled

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1867]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to get statistics information about users enrolled by week/month/year. 

**Describe the solution you'd like**
Promeutheus scrape endpoint, or some other way to get the data or visualize it.

**Describe alternatives you've considered**
N/A

**Additional context**
Matrix Synapse user statistics

**Comment by BeryJu** [comment]
There already is a Prometheus endpoint on `:9300/metrics`, you can set `prometheus.serviceMonitor.create` on the helm chart to create a Service Monitor, and then you can query it like `avg by (namespace) (authentik_models{app="authentik_core",model_name="user"})`

**Comment by samip5** [comment]
When not running in k8s?

**Comment by BeryJu** [comment]
On docker compose you can still prometheus scrape on port 9300.

I'd also like to add more charts into authentik itself, and this would be a prime candidate. Any other metrics you would find interesting?

**Comment by samip5** [comment]
> On docker compose you can still prometheus scrape on port 9300.
> 
> I'd also like to add more charts into authentik itself, and this would be a prime candidate. Any other metrics you would find interesting?

The only other metric that I can think of, is perfomance related but I'm not sure if those are doable. Like I would like to know if I might need 2nd worker and things like that.

**Comment by BeryJu** [comment]
Oh, you mean percentual usage of the worker? That should be doable since it runs maximum 3 tasks at once(see https://github.com/goauthentik/authentik/blob/master/lifecycle/ak#L70). I dont think most installs need more than one worker but it would be interesting to see.

**Comment by samip5** [comment]
Something like that yes, but as well as any other perfomance metrics.
