### ISSUE TITLE
Canonical ID field for SerializerModel

### ISSUE THREAD

**Issue by thinkwelltwd** [goauthentik/authentik#1869]
First of all, I'm completely impressed with what I see in authentik! Thanks so much for the project. I've written a Django-based SSO service for our company and I'm evaluating authentik as a possible replacement.

**Is your feature request related to a problem? Please describe.**

The slogan "The authentication glue you need" really fits my problem space. In our company we do a lot of API-based synchronization of records between disparate systems, such as from ERP -> mail servers -> network appliances -> MDM device management, tied together via SSO. 

One essential element of glue between these systems is what we call a Canonical ID - a UUID that represents that Record across the every system wherein it's found.

**Describe the solution you'd like**

Add one UUID field to SerializerModel, UserModel and GroupModel, like so:

```python
class SerializerModel(models.Model):
    """Base Abstract Model which has a serializer"""

    cid = models.UUIDField(db_index=True, unique=True, default=uuid4)
```

**Additional context**

With a design like this, the `cid` field becomes a "primary key" field for the record, wherever it's found. But it's more flexible than using the actual database primary key, because the value can be updated to harmonize records between the SSO server and client servers.

The API could also be extended to lookup all records by the `cid`, but that would be significantly more work.

Are you open to further discussion or PRs along these lines?

**Comment by BeryJu** [comment]
While I see your usecase and see how this `cid` would solve the issue, I think this is solveable via User/Group attributes, which can store arbitrariy data and can be filtered. 

Besides User and Group, what other models would you use this for? Currently only User and Group have attribute fields, as I haven't seen a reason to add them to other fields.

**Comment by thinkwelltwd** [comment]
> I think this is solveable via User/Group attributes,

I hadn't thought of the `attributes` field. Perhaps that would work, though a key disadvantage is that JSON and unique constraints don't mix so very well.

> what other models would you use this for?

For sure the Provider model, and for possible convenience, the Application model.  Would you be accept a PR to that effect?

**Comment by BeryJu** [comment]
I'd prefer adding `attributes` to more objects as its less specific, and while I do agree on the uniqueness issues, I still think its the generally easiest solution. I dont think that any integration using these fields would constantly write to them, so it should be fine if the uniqueness is checked after writing.

**Comment by BeryJu** [comment]
What you can also do is use the `managed` field that a bunch of objects already have. This field is used by authentik to track which objects are managed by itself and not created by the user, but as long as you don't use `goauthentik.io` in your value you'll be fine.
