### ISSUE TITLE
iOS SDK for logging in with authentik

### ISSUE THREAD

**Issue by rizwan95** [goauthentik/authentik#1881]
**Describe your question/**
In Apple devices, there is an option for providing native Apple sign-in. So does Authentik work with native Apple sign-in without using the standard browser-based flows?

I have seen Auth0 do it. For reference -> https://auth0.com/docs/connections/social/apple-native

**Comment by samip5** [comment]
Hmm, how does that differ from the browser flow?

**Comment by rizwan95** [comment]
In native Sign in, Apple handles the authentication part from the native app itself. After successful login, it returns certain variables (mentioning them below). 

`open class ASAuthorizationAppleIDCredential : NSObject, ASAuthorizationCredential {

    
    /** @abstract An opaque user ID associated with the AppleID used for the sign in. This identifier will be stable across the 'developer team', it can later be used as an input to @see ASAuthorizationRequest to request user contact information.
    
     The identifier will remain stable as long as the user is connected with the requesting client.  The value may change upon user disconnecting from the identity provider.
     */
    open var user: String { get }

    
    /** @abstract A copy of the state value that was passed to ASAuthorizationRequest.
     */
    open var state: String? { get }

    
    /** @abstract This value will contain a list of scopes for which the user provided authorization.  These may contain a subset of the requested scopes on @see ASAuthorizationAppleIDRequest.  The application should query this value to identify which scopes were returned as it maybe different from ones requested.
     */
    open var authorizedScopes: [ASAuthorization.Scope] { get }

    
    /** @abstract A short-lived, one-time valid token that provides proof of authorization to the server component of the app. The authorization code is bound to the specific transaction using the state attribute passed in the authorization request. The server component of the app can validate the code using Apple’s identity service endpoint provided for this purpose.
     */
    open var authorizationCode: Data? { get }

    
    /** @abstract A JSON Web Token (JWT) used to communicate information about the identity of the user in a secure way to the app. The ID token will contain the following information: Issuer Identifier, Subject Identifier, Audience, Expiry Time and Issuance Time signed by Apple's identity service.
     */
    open var identityToken: Data? { get }

    
    /** @abstract An optional email shared by the user.  This field is populated with a value that the user authorized.
     */
    open var email: String? { get }

    
    /** @abstract An optional full name shared by the user.  This field is populated with a value that the user authorized.
     */
    open var fullName: PersonNameComponents? { get }

    
    /** @abstract Check this property for a hint as to whether the current user is a "real user".  @see ASUserDetectionStatus for guidelines on handling each status
     */
    open var realUserStatus: ASUserDetectionStatus { get }
}
`
[Official documentation ](https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple)

**Comment by BeryJu** [comment]
So the first link you posted leads me to believe you mean this? https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js (or rather https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple), I'm not sure if there are any differences compared to just using the current flow

**Comment by BeryJu** [comment]
So the main difference using this approach is that users on Safari get a native UI instead of a web-based authentication flow, when the user is using anything else it falls back to the default flow. @rizwan95 Please test this new flow using gh-master docker images.

**Comment by rizwan95** [comment]
@BeryJu  I will check and revert back to you

**Comment by rizwan95** [comment]
@BeryJu What you are referring to is correct and authentik works well with it. There is an another way to use Apple sign-in using native UI, without using the Safari itself. There will be a button which says signin with apple and upon successful authorization, the apple server gives us authcode and other details. I suppose we have to exchange that with the authentik server. Is my thought process right? Or wrong? 
(Attaching the screenshot for your reference. )
![IMG_517FC38EA905-1](https://user-images.githubusercontent.com/10910174/146665531-8648dae5-23e2-4d5e-ba3f-f4fd386ad05a.jpeg)

(Upon tapping the button, it will ask for FaceID/ Touch ID/ password without redirecting to Safari itself.)

**Comment by BeryJu** [comment]
I'm not sure this is something authentik can do, not without a fully custom iOS element and a custom library. I dont have the experience or resources to work on this personally, so I'll set this as pr_wanted.

**Comment by BeryJu** [comment]
Signing into an iOS app with authentik is possible using a WKWebkitView, we might consider creating a dedicated an SDK for this in the future
