### ISSUE TITLE
Error with Okta when calling /v1/userinfo endpoint

### ISSUE THREAD

**Issue by patoarvizu** [goauthentik/authentik#1910]
**Describe the bug**
I have configured Okta as a source and set up an enrollment flow specific for it. When I go through that enrollment flow it redirects me to Okta, I successfully authenticate against Okta, but then I get redirected back to the `default-authentication-flow`.

If I look at the server logs, I see something like:
```
{"event": "Unable to fetch user profile", "exc": "HTTPError('400 Client Error: Bad Request for url: https://my.okta.domain/oauth2/<okta-auth-server-id>/v1/userinfo?access_token=<okta-jwt-token>')", "host": "domain.tld", "level": "warning", "logger": "authentik.sources.oauth.clients.base", "pid": 20, "request_id": "...", "timestamp": "..."}
```

Then if I  `curl` that url with `-I`, one of the response headers has something like this `error="invalid_request", error_description="The access token cannot be presented in a query string."`.

**To Reproduce**
1. Set up Authentik on Kubernetes with the Helm chart and go through the initialization flow.
2. Have an Okta Dev account or get a [free one](https://developer.okta.com/signup/).
3. Get an Authentik token and an Okta one to set things up with Terraform. Attaching a snippet below of some Terraform code with the setup necessary.
4. Go to https://domain.tld/if/flow/okta-enrollment-flow/
5. Authenticate with Okta. You'll be redirected to Authentik with no obvious error.
6. Check the logs of the server pod, e.g. `kubectl -n authentik logs authentik-server-abcd-1234`. You should see a message saying something along the lines of `Unable to fetch user profile`.

Terraform snippet (partial, relevant parts)

```
resource authentik_source_oauth okta {
  name                = "okta"
  slug                = "okta"
  enrollment_flow     = authentik_flow.okta_enrollment.uuid
  provider_type   = "openidconnect"
  user_matching_mode = "email_deny"
  consumer_key    = okta_app_oauth.authentik.client_id
  consumer_secret = okta_app_oauth.authentik.client_secret
  authorization_url = format("%s/v1/authorize", okta_auth_server.authentik.issuer)
  access_token_url = format("%s/v1/token", okta_auth_server.authentik.issuer)
  profile_url = format("%s/v1/userinfo", okta_auth_server.authentik.issuer)
}

resource okta_auth_server authentik {
  audiences   = ["authentik"]
  name        = "authentik"
  description = "authentik"
}

resource okta_auth_server_claim groups {
  auth_server_id    = okta_auth_server.authentik.id
  name              = "groups"
  value             = ".*"
  value_type        = "GROUPS"
  claim_type        = "IDENTITY"
  group_filter_type = "REGEX"
}

resource okta_auth_server_policy authentik {
  auth_server_id   = okta_auth_server.authentik.id
  name             = "authentik"
  description      = "authentik"
  priority         = 1
  client_whitelist = [okta_app_oauth.authentik.client_id]
}

resource okta_auth_server_policy_rule authentik {
  auth_server_id       = okta_auth_server.authentik.id
  policy_id            = okta_auth_server_policy.authentik.id
  name                 = "Default"
  priority             = 1
  grant_type_whitelist = ["authorization_code", "implicit", "client_credentials"]
  scope_whitelist      = ["*"]
}

resource okta_app_oauth authentik {
  label       = "authentik"
  type        = "web"
  omit_secret = false
  redirect_uris = [
    "https://domain.tld/source/oauth/callback/okta/",
  ]
  response_types = ["code", "id_token", "token"]
  grant_types    = ["authorization_code", "implicit", "client_credentials"]
}
```

**Expected behavior**
The user can enroll through Okta and can log in successfully

**Screenshots**
N/A

**Logs**
The only relevant log line I could find was:
```
{"event": "Unable to fetch user profile", "exc": "HTTPError('400 Client Error: Bad Request for url: https://my.okta.domain/oauth2/<okta-auth-server-id>/v1/userinfo?access_token=<okta-jwt-token>')", "host": "domain.tld", "level": "warning", "logger": "authentik.sources.oauth.clients.base", "pid": 20, "request_id": "...", "timestamp": "..."}
```

By the way, it just feels like a security liability to put the url with the access token in clear text in the logs, so that probably also needs to be addressed.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.4
 - Chart version: 4.0.3
 - Terraform provider version: 2021.10.3
 - Deployment: Kubernetes (1.19)

**Additional context**
* Relevant Discord [thread](https://discord.com/channels/809154715984199690/809154716507963434/885939279681962045).

**Comment by BeryJu** [comment]
after a little bit of looking I actually noticed that Azure AD actually has the same "quirk", so I was just able to re-use this.

Can you test this with the master version (pretty much equal to 2021.12.1-rc4):

Add this to your .env file

```
AUTHENTIK_IMAGE=goauthentik.io/dev-server
AUTHENTIK_TAG=gh-master
AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE=goauthentik.io/dev-%(type)s:gh-master
```

**Comment by patoarvizu** [comment]
Is that repository public? I get the following error when I update the `Deployment` objects (both worker and server).

```
Failed to pull image "goauthentik.io/dev-server:gh-master": rpc error: code = Unknown desc = failed to pull and unpack image "goauthentik.io/dev-server:gh-master": failed to resolve reference "goauthentik.io/dev-server:gh-master": failed to authorize: failed to fetch anonymous token: unexpected status: 400 Bad Request
```

For what it's worth, I'm running this on a `arm64` machines (it's a Raspberry Pi Kubernetes cluster), so maybe there are no `arm64` images published yet?

**Comment by BeryJu** [comment]
Interesting, I've not seen that error before, but indeed, dev images are only built for amd64 to save time during CI.

I'll bring out 12.1-rc5 later, that'll have an arm64 image that you can test with

**Comment by BeryJu** [comment]
Works with 12.1-rc5

**Comment by patoarvizu** [comment]
I tried with `2021.12.1-rc5` and also with `2021.12.2` but I still see the error:

```
{"event": "Unable to fetch user profile", "exc": "HTTPError('400 Client Error: Bad Request for url: https://dev-367300.okta.com/oauth2/<auth-server-id>/v1/userinfo?access_token=<access-token>')", "host": "domain.tld", "level": "warning", "logger": "authentik.sources.oauth.clients.base", "pid": 21, "request_id": "99e7e31777444b40b06dd322a02430c8", "timestamp": "2021-12-18T23:32:09.361656"}
{"event": "/source/oauth/callback/okta/?code=<code>&state=<state>", "host": "domain.tld", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "10.42.2.0", "request_id": "99e7e31777444b40b06dd322a02430c8", "runtime": 659, "scheme": "https", "status": 302, "timestamp": "2021-12-18T23:32:09.383381", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36"}
```

**Comment by BeryJu** [comment]
Be sure to switch the source to use the Okta type instead of generic OpenID

**Comment by patoarvizu** [comment]
Ah alright, I'll give that a try and report back.

**Comment by patoarvizu** [comment]
Ah it looks like this works, or at least I'm no longer getting that error. I still cannot seem to be able to do what I want to do but I think it must be some misconfiguration. I think we can consider this officially closed.
