### ISSUE TITLE
Refresh token is revoked when Access token validity's is expired

### ISSUE THREAD

**Issue by rizwan95** [goauthentik/authentik#1911]
**Describe the bug**
There are two options in Authentik. One is we can set the expiry for the access tokens and the other for refresh tokens and the id tokens. When the Access token validity is expired, it automatically revokes the refresh token, which shouldn't happen. 

**To Reproduce**
1. Go to providers
2. Set the access token validity
3. Try to get a new access token after the expiry 
4. The error Refresh token is revoked is thrown.

**Logs**
`{"event": "Refresh token is revoked", "host": "auth.domain", "level": "warning", "logger": "authentik.providers.oauth2.views.token", "pid": 20, "request_id": "<reqId>", "timestamp": "2021-12-13T03:07:09.069038", "token": "<mytoken>"}`

**Comment by BeryJu** [comment]
How are you calling the token endpoint? I did some testing and everything worked as expected;

- Do the browser flow to get an authorization code
- Call /o/token/ with grant_type=authorization_code to convert that code to a refresh token
- Then with that refresh token you can call /userinfo
- Call /o/token with grant_type=refresh_token and the refresh token from above gives you a new fresh token, and revokes the old one

**Comment by rizwan95** [comment]
The refresh token gets refreshed now. I am not sure what was the problem before.
Now, even though I have set the expiry to like 50 seconds, the access token doesn't get expired.

**Comment by BeryJu** [comment]
Expired model cleanup only runs every 5 minutes, now with this commit there is an additonal check for that.

**Comment by rizwan95** [comment]
> Expired model cleanup only runs every 5 minutes, now with this commit there is an additonal check for that.

Thank you very much @BeryJu
