### ISSUE TITLE
Authentik admin interface allows deleting logged in user

### ISSUE THREAD

**Issue by xpufx** [goauthentik/authentik#1937]
**Describe the bug**
GUI allows deleting the user that is currently logged in. (I tested with an administrator level user)

**To Reproduce**
Go to users, search for the user already logged in as. Delete.

**Expected behavior**
There should be a warning or it should be disallowed. If it is allowed, user should be logged out.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.4
 - Deployment: docker

**Additional context**

I haven't tried to delete the last remaining admin user but it seems like it would be possible.

**Comment by compgeniuses** [comment]
I have accidentally deleted the administrative loggein user in version 2024.2.2 and now not sure how to login

**Comment by rissson** [comment]
> I have accidentally deleted the administrative loggein user in version 2024.2.2 and now not sure how to login

You'll need https://docs.goauthentik.io/docs/troubleshooting/login, but prior to that, run `create_admin_group --user your_username`
