### ISSUE TITLE
Skip path regex

### ISSUE THREAD

**Issue by rxbn** [goauthentik/authentik#1955]
**Describe your question**
I don't understand how skip path regex in proxy providers work.

Let's say I have an app running on app1.example.com.

I configured a forward auth on domain level.

How can I exclude `app1.example.com/ping` from forward auth? I have tried all kinds of different regex, but none of them worked.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.4
 - Deployment: helm

**Comment by BeryJu** [comment]
Currently, the regex is checked against the URL path, even on domain-level auth. I'll change this to match against the entire URL with domain mode.
