### ISSUE TITLE
Authentik not redirecting to source application after signup

### ISSUE THREAD

**Issue by rizwan95** [goauthentik/authentik#1960]
**Describe the bug**
When a user goes into the default-enrollment-flow, and after completing the signup, the user is not being redirected to the source application because there is no callback URL present in the default-enrollment-flow. 

**To Reproduce**
1. Login using the default-authentication-flow
2. Click on sign-up which will in-turn call the deafult-enrollment-flow
3. After signup, authentik will not redirect back to the source application because of the missing callback URL

**Expected behavior**
1. After signup, authentik should redirect back to the source application depending upon the callback URL.

**Version and Deployment (please complete the following information):**
 - authentik version:  2021.12.2
 - Deployment: docker-compose

**Comment by muspelheim** [comment]
Same

**Comment by rizwan95** [comment]
@BeryJu can you please share your thoughts on this?

**Comment by nlahmi** [comment]
Same

**Comment by Thulkash** [comment]
Same
