### ISSUE TITLE
Docs for oauth end session is incorrect

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#1961]
**Describe the bug**
The URL for signout via oauth is not `/application/o/<application slug>/session-end/`, like it is on most docs.
Rather it seems to be `https://authentik.company/if/session-end/<application-slug>/`

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.2
 - Deployment: Ansible

**Comment by BeryJu** [comment]
`/application/o/<application slug>/session-end/` is correct, the URL just currently redirects to `/if/session-end/`. This hasn't been updated in the docs on purpose, as in the future there might be some OAuth-specific logic in the redirect.

**Comment by samip5** [comment]
> `/application/o/<application slug>/session-end/` is correct, the URL just currently redirects to `/if/session-end/`. This hasn't been updated in the docs on purpose, as in the future there might be some OAuth-specific logic in the redirect.

For me, with Grafana, that URL will yeld not found error on Authentik.

**Comment by BeryJu** [comment]
Which URL are you getting redirected to? When using an invalid application slug you'll still get redirected, just the actual end-session view will 404 since the application does not exist.

**Comment by samip5** [comment]
Ah, probably just a mistype as I had forgotten the `/application/` from the start of the URL.
