### ISSUE TITLE
Regex still not work for me

### ISSUE THREAD

**Issue by rxbn** [goauthentik/authentik#1970]
**Describe your question**
Thanks for implementing my suggestion. However, I can't make regex work. I want to disable authentication for `app1.example.com/ping`, but `^https://app1\.example\.com/ping$` doesn't work.
What would the correct regex be in that case?

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.2
 - Deployment: helm

**Comment by BeryJu** [comment]
Are you using the embedded outpost? In the external outposts, you can set `log_level: trace`, restart the container and then it will log what URLs it is matching against

**Comment by rxbn** [comment]
I'm using the embedded outpost.

**Comment by BeryJu** [comment]
Can you try running the beta version (see https://goauthentik.io/docs/installation/beta) and then set your log level to trace?

That should show you what is being compared.

**Comment by rxbn** [comment]
```
Failed to pull image "goauthentik.io/dev-server:gh-next": rpc error: code = Unknown desc = failed to pull and unpack image "goauthentik.io/dev-server:gh-next": failed to resolve reference "goauthentik.io/dev-server:gh-next": failed to authorize: failed to fetch anonymous token: unexpected status: 400 Bad Request
```

**Comment by BeryJu** [comment]
since all the intermitten issues with the docker proxy, I've reverted all docs to use GHCR directly. Please check the beta docs again.

**Comment by rxbn** [comment]
Now it's running again, however, if I configure `log_level: trace` on the embedded outpost, I don't see any trace logs. Where should the logs be? In the server or worker pod?

**Comment by BeryJu** [comment]
For the embedded outpost the log from the config has priority, so you need to change your helm release to use trace.

**Comment by rxbn** [comment]
Which helm value would that be? Setting `authentik.log_level` to `trace` doesn't work.

**Comment by rxbn** [comment]
Now I have logs!

```
{"event":"Matching URL against allow list","level":"trace","logger":"authentik.outpost.proxy.bundle","provider":"Traefik Forward Auth","regex":"^https://traefik\\.local\\.example\\.com/ping$","timestamp":"2021-12-21T14:38:32Z","url":"https:///akprox/auth/traefik"}
{"event":"Redirecting to login","level":"debug","logger":"authentik.outpost.proxy.bundle","provider":"Traefik Forward Auth","timestamp":"2021-12-21T14:38:32Z","url":"https://auth.example.com/akprox/start"}
```

The URl I cURLed was `https://traefik.local.example.com/ping`

**Comment by BeryJu** [comment]
oh, duh. Now I know what the issue is.

**Comment by BeryJu** [comment]
@rxbn can you delete your authentik pods to try the latest build?

**Comment by rxbn** [comment]
I already did (watched the build) and now it works! Amazing :) Thanks a lot!
