### ISSUE TITLE
Keep getting logged out after closing Safari

### ISSUE THREAD

**Issue by rxbn** [goauthentik/authentik#1971]
**Describe the bug**
If I quit Safari completely after logging in, I have to re-login every single time. Is there no "keep signed in" checkbox?

**To Reproduce**
1. Login to authentik in Safari (macOS/iOS/iPad OS)
2. Quit the app (close from multitasking on iOS/iPad OS or CMD+Q on macOS)
3. Open authentik - you are now logged out and have to login again

**Expected behavior**
Keep login ever if browser was closed completely.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.2
 - Deployment: helm

**Additional context**
The issue does not exist on Firefox on Mac.

**Comment by BeryJu** [comment]
Can you check if your user_login stage has a session expiry set? https://goauthentik.io/docs/flow/stages/user_login

**Comment by rxbn** [comment]
It was set to seconds=0, I now changed it to days=30 and now the issue has been resolved :) Thanks a lot!!!!
Happy holidays :)
