### ISSUE TITLE
[2021.12.2] Getting null response from Post in OIDC

### ISSUE THREAD

**Issue by Typositoire** [goauthentik/authentik#1977]
**Describe the bug**
Currently upgrading to 2021.12.2 I get this with vault OIDC on the UI, using CLI it works. 2021.10.4 doesn't have this issue.

`Cannot read properties of null (reading 'postMessage')`

**To Reproduce**
1. Setup OIDC provider for vault
2. Login to vault UI with oidc
4. See `Cannot read properties of null (reading 'postMessage')` in newly opened window.

**Expected behavior**
Authentication works

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.2
 - Deployment: docker-compose

**Additional context**
Authentication works as expected, the payload is just not correctly returned to Vault. My other apps works correctly.
![image](https://user-images.githubusercontent.com/721017/146966174-17aa70b7-2d4c-4daf-8d45-2ca29a10acf2.png)

**Comment by Typositoire** [comment]
And correct workflow using `2021.10.4`
![image](https://user-images.githubusercontent.com/721017/146966409-d1194de2-cebb-4fbc-b07b-fdf1c9af5463.png)

**Comment by BeryJu** [comment]
I've actually had this same issue, thought it was caused by a vault update I did at the same time, but no, it was actually caused by django 4.0
