### ISSUE TITLE
Can't use Provider twice in Applications

### ISSUE THREAD

**Issue by klatka** [goauthentik/authentik#2022]
**Describe the bug**
I set up a forwardAuth (domain level) proxy provider.
I have multiple applications which are using the forwardAuth middleware in traefik to authenticate with Authentik.
These Apps should be listed under Applications in Authentik but the Provider field must be unique so I am not able to create them.

**To Reproduce**
1. Create Provider
2. Set created Provider in App1
3. Set created Provider in App2
4. Can't save: `This field must be unique.` - Provider field

**Expected behavior**
Multiple applications with one Provider.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.4
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
This is by design, a provider can currently only be used by one application. For this usecase with domain auth, you can create multiple Applications without any provider and just set the Launch URL and they will behave the same.

**Comment by klatka** [comment]
Thank you for your support. If I do so, I can not set provider in the Outpost because there is only a list of Applications that is empty (because no App is using forwardAuth provider). If I visit the URL of one of these apps I get this:

```
{
	"Message": "no app for hostname",
	"Host": "iam.example.com",
	"Detail": "Check the outpost settings and make sure 'iam.example.com' is included."
}
```

**Comment by BeryJu** [comment]
Yeah with just a lunch URL you cant use them with an outpost, but you also don't need to. With just launch URL the entry would essentially just be a bookmark.

For the error, what are your provider settings for the forward auth?

**Comment by klatka** [comment]
```
Name: forwardAuth
Authorization flow: implicit-consent
Mode: Forward auth (domain level)
Authentication URL: https://authentik.example.com
Cookie domain: example.com
Token validity: hours=24

Advanced protocol settings unchanged
```

**Comment by bcg62** [comment]
I have a single domain level forward auth provider setup, and then multiple applications with only launch url configured and no provider selected. Getting:

Permission denied

Request has been denied.

after login attempting to access any of the applications.

**Comment by Termibg22** [comment]
Same problem here. I don't understand this behaviour, if we create a domain provider is because we have multiple applications and want to proxy them with the authentik outpost,.

**Comment by moshin34** [comment]
Yes, here I am a few years later.   Also confused. 

It says in the UI

Use this provider with nginx's auth_request or traefik's forwardAuth. Only a single provider is required per root domain. You can't do per-application authorization, but you don't have to create a provider for each application.

But I cannot add an app to the outpost without linking to a provider.
And I cannot add more than one app to a provider

So it would seem I do need to create a provider for each application

I must be very wrong about something here.    Guidance would be appreciated.   Thanks for all that you do

**Comment by agusdmb** [comment]
> But I cannot add an app to the outpost without linking to a provider. And I cannot add more than one app to a provider
> 
> So it would seem I do need to create a provider for each application

same here.. i have been reading and trying things out for hours now without luck

**Comment by BeryJu** [comment]
The phrasing in that is a unclear; with `but you don't have to create a provider for each application` it doesn't mean in authentik; when you have a domain-level forward auth application/provider setup with an outpost, you do not create anything for the applications you run on that domain, application in this case not referring to applications in authentik

You can still create an application in authentik for users to launch a URL and that does not require a provider nor an outpost
