### ISSUE TITLE
Feature request: additional OAuth federation scopes

### ISSUE THREAD

**Issue by kylesferrazza** [goauthentik/authentik#2047]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to authenticate users only if they are members of a particular GitHub.com organization.

**Describe the solution you'd like**
In the GitHub federation settings, I'd like to be able to provide additional OAuth scopes to request for the user during sign-in, so I can request `read:org`.
I would then create a custom Policy to match against a user's org list to allow/deny them access.

**Describe alternatives you've considered**
If GitHub provided a means to set a default scope for an OAuth app, I could set `read:org` there, but it doesn't.

**Additional context**
Some of the other providers have hardcoded scopes:
https://github.com/goauthentik/authentik/blob/07b001bc2bed5f7e02d4f0096ed45286526aeb9a/authentik/sources/oauth/types/facebook.py#L17
https://github.com/goauthentik/authentik/blob/07b001bc2bed5f7e02d4f0096ed45286526aeb9a/authentik/sources/oauth/types/discord.py#L14

I'd like some option in the federation settings to be able to add additional scopes to the request, which would presumably set up scopes like above, but provided by the user.

**Comment by kylesferrazza** [comment]
idea: once this is implemented, a new built-in policy type for GitHub org membership could be implemented as well to make it easy to support this use-case in the future

**Comment by kylesferrazza** [comment]
Even easier, this line:

https://github.com/goauthentik/authentik/blob/8560c7150a97a1349d4b943da3a256571465dc14/authentik/sources/oauth/clients/base.py#L72

could be fixed to properly parse the url and add parameters to it.


That way, I could just add `?scope=read:org` to the end of my authorization url.

**Comment by BeryJu** [comment]
@kylesferrazza I've added an additional scopes field, I chose to not rework the URL concatination since it would have to properly merge scopes aswell, so I felt like an additional field is easier.

For the policy, I'd prefer not adding a new type, but you should be able to check the user's organisations using an expression policy. I'll do some testing with that and add docs for it.

**Comment by kylesferrazza** [comment]
Thanks very much -- this looks great. Looking forward to those docs!

**Comment by anuj-modi** [comment]
We were using a version based on master and realized you have marked extra scopes as required. This should be optional as it is not applicable to some Oauth providers.

**Comment by BeryJu** [comment]
@anuj-modi Cheers, this will be fixed in the latest build
