### ISSUE TITLE
Two default tenants crash authentik server

### ISSUE THREAD

**Issue by panos-indev** [goauthentik/authentik#2059]
**Describe the bug**
I tried to add one more tenant and I marked as a default without unmarking the pre-made one, just to see what would happen. My actual end-goal would be to be able to create a tenant and mark it as default through terraform, but for this i will create a feature request on the respective repo. Immediately after creating the tenant, authentik crashed and keeps crashing. Now the only way i can think of to recover authentik, is to manually try to change the default flag on the DB.

Note: I hadn't chose any flows when I created the tenant

**To Reproduce**
1. Go to System -> Tenants
2. Click on 'Create'
3. Fill in the required fields
4. Mark tenant as default
5. Authentik crashes and then keeps crashing

**Expected behavior**
I guess that authentik should either throw in error that a tenant is already marked as default and not let you create the new tenant or ask you if you want to unmark the other tenant and mark the new one.

**Logs**
{"event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 27, "remote": "127.0.0.1", "request_id": "eb16b68395e84507835fb87aeffbbf8e", "runtime": 416, "scheme": "http", "status": 204, "timestamp": "2022-01-04T10:06:45.262477", "user": "", "user_agent": "goauthentik.io go proxy healthcheck"}
{"event":"backend is alive, backing off with healthchecks","level":"info","logger":"authentik.router.unicorn","timestamp":"2022-01-04T10:06:45Z"}
{"auth_via": "secret_key", "event": "/api/v3/outposts/instances/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 26, "remote": "127.0.0.1", "request_id": "5c9f7d48a11f48cc98d3f0c7021456f1", "runtime": 499, "scheme": "http", "status": 200, "timestamp": "2022-01-04T10:06:45.764555", "user": "ak-outpost-f60278f23c2e41a6a21b096fa3d2bf47", "user_agent": "authentik-outpost@2021.12.4 (build=tagged)"}
{"auth_via": "secret_key", "event": "/api/v3/root/config/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 26, "remote": "127.0.0.1", "request_id": "90661fdcbe2b4a26a6c733bf52b8c8fa", "runtime": 51, "scheme": "http", "status": 200, "timestamp": "2022-01-04T10:06:45.817920", "user": "ak-outpost-f60278f23c2e41a6a21b096fa3d2bf47", "user_agent": "authentik-outpost@2021.12.4 (build=tagged)"}
{"event":"Starting Tenant TLS Checker","level":"info","logger":"authentik.router.tenant_tls","timestamp":"2022-01-04T10:06:45Z"}
{"event":"updating tenant certificates","level":"info","logger":"authentik.router.tenant_tls","timestamp":"2022-01-04T10:06:45Z"}
{"auth_via": "secret_key", "event": "/api/v3/core/tenants/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 26, "remote": "127.0.0.1", "request_id": "4a1278e05d774956b2ab192e4f5c72d7", "runtime": 30, "scheme": "http", "status": 200, "timestamp": "2022-01-04T10:06:45.955995", "user": "ak-outpost-f60278f23c2e41a6a21b096fa3d2bf47", "user_agent": "authentik-outpost@2021.12.4 (build=tagged)"}
{"auth_via": "secret_key", "event": "/api/v3/outposts/instances/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 27, "remote": "127.0.0.1", "request_id": "13671f10e6d5457b9ee8b5dc72bc02be", "runtime": 50, "scheme": "http", "status": 200, "timestamp": "2022-01-04T10:06:46.051511", "user": "ak-outpost-f60278f23c2e41a6a21b096fa3d2bf47", "user_agent": "authentik-outpost@2021.12.4 (build=tagged)"}
{"event":"Starting authentik outpost","hash":"tagged","level":"info","logger":"authentik.outpost","timestamp":"2022-01-04T10:06:46Z","version":"2021.12.4"}
{"auth_via": "secret_key", "event": "/api/v3/outposts/proxy/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 27, "remote": "127.0.0.1", "request_id": "d164fd0d6b7243909a20d6d470bfed2c", "runtime": 28, "scheme": "http", "status": 200, "timestamp": "2022-01-04T10:06:46.081983", "user": "ak-outpost-f60278f23c2e41a6a21b096fa3d2bf47", "user_agent": "authentik-outpost@2021.12.4 (build=tagged)"}
{"event":"updating tenant certificates","level":"info","logger":"authentik.router.tenant_tls","timestamp":"2022-01-04T10:06:46Z"}
{"auth_via": "secret_key", "event": "/api/v3/core/tenants/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 27, "remote": "127.0.0.1", "request_id": "18a095ec23764a329e7cabdc8bcb7a2f", "runtime": 29, "scheme": "http", "status": 200, "timestamp": "2022-01-04T10:06:46.113442", "user": "ak-outpost-f60278f23c2e41a6a21b096fa3d2bf47", "user_agent": "authentik-outpost@2021.12.4 (build=tagged)"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdb30aa]

goroutine 107 [running]:
goauthentik.io/internal/web/tenant_tls.(*Watcher).Check(0xc0004bc280)
	/work/internal/web/tenant_tls/tenant_tls.go:55 +0x3aa
main.attemptProxyStart.func1()
	/work/cmd/server/main.go:120 +0x1d
goauthentik.io/internal/outpost/ak.(*APIController).OnRefresh(0xc00000c1e0)
	/work/internal/outpost/ak/api.go:163 +0x57a
goauthentik.io/internal/outpost/ak.(*APIController).startIntervalUpdater(0xc00000c1e0)
	/work/internal/outpost/ak/api_ws.go:199 +0x19d
goauthentik.io/internal/outpost/ak.(*APIController).StartBackgorundTasks.func3()
	/work/internal/outpost/ak/api.go:186 +0x65
created by goauthentik.io/internal/outpost/ak.(*APIController).StartBackgorundTasks
	/work/internal/outpost/ak/api.go:184 +0x397

**Version and Deployment:**
 - authentik version: 2021.12.4
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Interesting, that panic should definitely not happen, and I think its also fixed on gh-master.

Otherwise to remove the other tenant, you can do this

```
docker-compose exec server ak shell
```

Then in the python shell, run

```python
from authentik.tenants.models import *
Tenant.objects.filter(domain="your.domain").delete()
```
