### ISSUE TITLE
Kubernetes app stuck at "authentik starting..."

### ISSUE THREAD

**Issue by FrankelJb** [goauthentik/authentik#2061]
**Describe your question/**
I have deployed Authentik on my k3s cluster, ingress is Traefik, using the helm chart. I created the Traefik middleware and attached it to an app's Ingress. I then created a Proxy Provider using ForwardAuth and created an app and added it to the Provider. However, when I try and navigate to my app, I can only see "authentik starting..." and the browser console shows "502 - Bad Gateway"

**Relevant infos**
There is no information in the logs to explain the 502 errors.
The Embedded Outpost is unhealthy and shows "Not available" (screenshot below).
I've set the log level to "debug" in the helm chart and on the Outpost.
The logs only show "proxy not running".

**Screenshots**
![Screenshot_2022-01-04-51_925x127](https://user-images.githubusercontent.com/3724809/148099889-1a00092b-dc82-4735-9f8e-c476b4ec0f1c.png)

**Logs**
```
{"event":"proxy not running","level":"warning","logger":"authentik.router","timestamp":"2022-01-04T17:33:41Z"}
{"event":"proxy not running","level":"warning","logger":"authentik.router","timestamp":"2022-01-04T17:33:42Z"}
{"event":"proxy not running","level":"warning","logger":"authentik.router","timestamp":"2022-01-04T17:33:42Z"}
``

**Version and Deployment (please complete the following information):**
 - authentik version:  2021.12.4
 - Deployment: helm

**Comment by BeryJu** [comment]
Could you check in the logs right as authentik is starting, if there are any bugs?

**Comment by FrankelJb** [comment]
User error once again. I'd typed `flase` instead of `false` in the `error_reporting.enabled` field.

Question is resolved. Thanks!
