### ISSUE TITLE
Restoring from backup insufficient database permissions

### ISSUE THREAD

**Issue by coolguy1771** [goauthentik/authentik#2072]
**Describe the bug**
While trying to restore from a backup I encounter this error `psql (err): ERROR:  permission denied for table pg_database`

**To Reproduce**
1. Try to restore postgres backup

**Expected behavior**
The backup being restored

**Screenshots**

<img width="1063" alt="Restore Failure" src="https://user-images.githubusercontent.com/45468117/148449818-3bac4f61-3498-4a9b-bf81-a0ba9ffb5950.png">

**Logs**

`{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1641502129.464127, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1641502129.4648137, "count": 55}
{"event": "Bootstrap completed", "level": "info", "logger": "bootstrap"}
{"event": "Ensuring no one can connect to the database", "level": "info", "logger": "bootstrap"}
psql (err): ERROR:  permission denied for table pg_database
command terminated with exit code 1`

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.4
 - Deployment: Helm [My Deployment](https://github.com/coolguy1771/k3s/blob/main/cluster/apps/auth/authentik/helm-release.yaml)

**Comment by BeryJu** [comment]
With the `ak restore` command you don't need the `-i` flag, just the filename.

But also, the restore procedure has been changed to fully re-create the database, which seems to be causing an error here. To use the old method, you can run `ak dbrestore -i $file.sql` (that command *does* require the `-i` flag)

**Comment by coolguy1771** [comment]
Even running it without the `-I` flag it still spits out the same error

**Comment by BeryJu** [comment]
Have you tried the other restore command?

**Comment by coolguy1771** [comment]
I can't actually because authentik controls my access to Minio

**Comment by coolguy1771** [comment]
Both commands still fail, although for different reasons. The newer command (```kubectl exec -n auth -it deployment/authentik-worker -c authentik --  ak restore```)  returns 
```psql (err): ERROR:  permission denied for table pg_database```. The older command returns ```Error running:  psql --dbname=postgresql://authentik:U4bQx2XtQTN5E545zZXiNHicYzn3NL3YLNN6@authentik-postgresql:5432/authentik --set ON_ERROR_STOP=on --single-transaction authentik
ERROR:  index "authentik_flows_flowstagebinding_flow_id_9a4d9b07" does not exist``` which makes me thing there's just a small issue the the restore process

**Comment by rizwan95** [comment]
Yes there is a problem with restoring the backups 

I am getting these error logs

`{"event": "restoring database", "level": "info", "logger": "bootstrap"}
restore (err): {"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1643529740.0922697, "file": "/authentik/lib/default.yml"}
restore (err): {"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1643529740.0929472, "count": 15}
restore (err): {"event": "Booting authentik", "level": "info", "logger": "authentik.root.settings", "timestamp": 1643529740.833501, "version": "2022.1.1"}
restore (err): {"event": "Failed to load GeoIP database", "exc": "FileNotFoundError(2, 'No such file or directory')", "level": "warning", "logger": "authentik.events.geo", "pid": 65, "timestamp": "2022-01-30T08:02:21.586012"}
restore (err): {"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 65, "task_id": "b9330e9e-7fd5-40c8-b634-833f10c65a9f", "task_name": "authentik.admin.tasks.clear_update_notifications", "timestamp": "2022-01-30T08:02:21.892700"}
restore (err): {"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 65, "task_id": "bc011b6f-df73-4203-b3c6-beab4d406490", "task_name": "authentik.outposts.tasks.outpost_local_connection", "timestamp": "2022-01-30T08:02:21.991328"}
restore (err): {"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 65, "task_id": "fed9a752-68ca-43bf-a6d8-c5152715abfb", "task_name": "authentik.outposts.tasks.outpost_controller_all", "timestamp": "2022-01-30T08:02:21.994272"}
restore (err): {"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 65, "task_id": "9660e5fd-32c1-4ea3-9abc-b98e625222b7", "task_name": "authentik.managed.tasks.managed_reconcile", "timestamp": "2022-01-30T08:02:22.142793"}
`

It is just stuck after this forever.

**Comment by AminSaqi** [comment]
So how we can restore?

I'm getting this error:

`ERROR:  index "authentik_flows_flowstagebinding_flow_id_9a4d9b07" does not exist`
