### ISSUE TITLE
Arm64 docker image gives error from python about how it doesn't have libpq version 10 or above, despite having said version

### ISSUE THREAD

**Issue by Rojikku** [goauthentik/authentik#2078]
**Describe the bug**
After upgrading the container image in my helm chart, I received the following error:  
`{"event": "PostgreSQL Connection failed, retrying... (SCRAM authentication requires libpq version 10 or above\n)", "level": "info", "logger": "__main__", "timestamp": 1641567838.4143062}`  
No amount of time waited resolves this error. Downgrading fixes the problem instantly.

**To Reproduce**
1. Upgrade container image in helm chart
2. Spammed by above error

**Expected behavior**
The image to container to PostgreSQL and continue working

**Screenshots**

**Logs**
`{"event": "PostgreSQL Connection failed, retrying... (SCRAM authentication requires libpq version 10 or above\n)", "level": "info", "logger": "__main__", "timestamp": 1641567838.4143062}`

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.5
 - Deployment: Helm

**Additional context**
Basing this off of: https://stackoverflow.com/questions/62807717/how-can-i-solve-postgresql-scram-authentifcation-problem

The fact the previous container version works fine, and that attempting an uninstall and reinstall doesn't fix the issue, indicates to me that this is likely a bug with the container image.

EDIT:
It is deduced below that the issue stems from the image running on arm64.

**Comment by BeryJu** [comment]
Interesting, which postgres version are you running?

**Comment by BeryJu** [comment]
Also checking the 12.5 image, libpq 13.5 is installed
![image](https://user-images.githubusercontent.com/1932513/148571421-66cf948b-90d5-4e20-93f9-d257bf6df5a7.png)

**Comment by Rojikku** [comment]
Postgre version: docker.io/library/postgres:14.1
I'm deploying it through kubegres.
I would assume the issue isn't my postgres install itself considering reverting fixes the issue, but I'm not sure what else it could be.

**Comment by BeryJu** [comment]
libpq is the same so it must be something different. Docker image didn't change either. What you can try is run a shell in a container and try to connect to your postgres with psql. Then we should at least see if its a container or application problem.

![image](https://user-images.githubusercontent.com/1932513/148572568-823dbe66-80a3-4d06-b7c6-6f87a0e479e4.png)

**Comment by BeryJu** [comment]
No worries, seems like pq is not at fault. Can your try python manage.py and see if that throws any errors? I'll do some testing with Postgres 14 later

**Comment by Rojikku** [comment]
```
authentik@authentik-server-5fb4bf476d-jbr88:/$ python manage.py
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1641572722.9408305, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1641572722.9431, "count": 40}
{"event": "Booting authentik", "level": "info", "logger": "authentik.root.settings", "timestamp": 1641572727.2705407, "version": "2021.12.5"}
{"event": "Failed to load GeoIP database", "exc": "FileNotFoundError(2, 'No such file or directory')", "level": "warning", "logger": "authentik.events.geo", "pid": 16, "timestamp": "2022-01-07T16:25:30.444381"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 16, "task_id": "32737f46-ef12-487a-93f9-105392203029", "task_name": "authentik.admin.tasks.clear_update_notifications", "timestamp": "2022-01-07T16:25:32.431762"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 16, "task_id": "210d5234-9274-46d7-afdf-524c0fb6a722", "task_name": "authentik.outposts.tasks.outpost_local_connection", "timestamp": "2022-01-07T16:25:33.051491"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 16, "task_id": "28425adf-660c-40b7-bb7f-bfdd60f10201", "task_name": "authentik.outposts.tasks.outpost_controller_all", "timestamp": "2022-01-07T16:25:33.061441"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.169515", "type": "authentik.sources.oauth.types.apple"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.174307", "type": "authentik.sources.oauth.types.azure_ad"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.178224", "type": "authentik.sources.oauth.types.discord"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.188043", "type": "authentik.sources.oauth.types.facebook"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.192012", "type": "authentik.sources.oauth.types.github"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.196058", "type": "authentik.sources.oauth.types.google"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.200161", "type": "authentik.sources.oauth.types.oidc"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.204081", "type": "authentik.sources.oauth.types.okta"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.208545", "type": "authentik.sources.oauth.types.reddit"}
{"event": "Loaded OAuth Source Type", "level": "debug", "logger": "authentik.sources.oauth.apps", "pid": 16, "timestamp": "2022-01-07T16:25:33.212158", "type": "authentik.sources.oauth.types.twitter"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 230, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 211, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 199, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/authentik/stages/email/apps.py", line 23, in ready
    self.validate_stage_templates()
  File "/authentik/stages/email/apps.py", line 32, in validate_stage_templates
    for stage in EmailStage.objects.all():
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/site-packages/model_utils/managers.py", line 38, in __iter__
    yield from iter
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1200, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 270, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 246, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 229, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 230, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 211, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 199, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above
```

It does, in fact, throw errors.

**Comment by BeryJu** [comment]
Right in that case it's probably cause py psycopg2 being built with a different libpq.

**Comment by BeryJu** [comment]
So I'm successfully able to 12.5 with postgres:14 with default settings

**Comment by BeryJu** [comment]
Just for the record, the issue seems to be somewhat related to ARM64, not sure yet if thats caused by the authentik server image or postgres image

**Comment by Rojikku** [comment]
Finally rebuilt my cluster after some storage issues. Currently both those pods are running off of an amd64 node, since that's where they got assigned, and I'm having no issues with 2021.12.5. Likely the issue resides in the authentik server image as my postgres image stayed on the same node the entire time.
The issue is not version specific between 12.4 and 12.5, as you have deduced.

**Comment by anagno** [comment]
When I deployed the helm chart in a rasbperry pi cluster, I had the same error with PostgreSQL 14.1 and version 2021.12.5 (i.e. `PostgreSQL Connection failed, retrying... (SCRAM authentication requires libpq version 10 or above\n)` )

I did not use the integrated bitnami helm chart, because the bitnami chart does not provide support for arm64.

But the error does not occur with the `postgres:13.5-bullseye`. Maybe some defaults change between the postgresql versions (?!).

**Comment by KBurgTech** [comment]
Hey,
I ran into the same issue when using my own PostgreSQL 14.2 DB and was able to fix it by doing this:
1. Edit your postgresql.conf (e.g.: /etc/postgresql/14/main/postgresql.conf) and set `password_encryption = md5` (should be line 96)
3. Restart database
4. Reset password for authentik user

After that it works like a charm! Hope this helps someone!

**Comment by phyber** [comment]
Poking this issue to reopen it since it’s still an issue.

**Comment by sr258** [comment]
@BeryJu I'm seeing the same error when trying authentic 2022.12.0 with Postgres 15 with Docker Compose on my Macbook M1: `PostgreSQL connection failed, retrying... (SCRAM authentication requires libpq version 10 or above\n)`

It looks like this is caused by a bug in the ARM version of the Python Debian base image. It might be resolved by using a different package for psycopg2: https://stackoverflow.com/a/73656296/3324376 I've tried replacing `psycopg2-binary` with `psycopg2` in `pyproject.toml`, but then I get `ModuleNotFoundError: No module named 'psycopg2'` when starting the application inside the newly built container. I've also tried downgrading the Debian version in the Dockerfile to buster, but the error persists.

**Comment by luisnabais** [comment]
I have the same exact error. I'm already running Postgres 15.1 in a Raspberry Pi 4 (ARM64) and now running ghcr.io/goauthentik/server:2022.12.0 with Docker Compose.
The error I have is both in server and worker:
{"event": "PostgreSQL connection failed, retrying... (SCRAM authentication requires libpq version 10 or above\n)", "level": "info", "logger": "authentik.lib.config", "timestamp": 1672404885.720217}`

**Comment by DanyloMikula** [comment]
Hi,
I have the same issue, any updates?

ARM64 k3s cluster
Postgres 15.2

**Comment by solo-daemon** [comment]
Faced the same while working with django had to build the django image for platform linux/amd64
