### ISSUE TITLE
Outpost can't handle multiple domain-level forward auth proxies

### ISSUE THREAD

**Issue by Rojikku** [goauthentik/authentik#2079]
**Describe the bug**
If multiple domain-level forward auth proxies are enabled in the outpost, every subdomain, but not the root domain, of those proxies, gives the error `"Message": "no app for hostname",` for those subdomains.

**To Reproduce**
1. Setup a working domain-level forward auth
2. Verify it works as expected
3. Setup a second domain-level forward auth, exactly the same, but on a different sub domain (In my case, I have mon and r, for two different stacks I want different permissions on).
4. Verify the two root domains, r.example.com, and mon.example.com, work as expected
5. Going to any of the subdomains on either domain, including the previously working one, produces error above.
6. Limiting outpost to just one of these domains instantly fixes the issue.

**Expected behavior**
I expect both domain-level auths to work.

**Logs**
Likely not needed but available on request.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.4 and 2021.12.5
 - Deployment: Helm

**Additional context**
I am using traefik with middleware. Likely shouldn't matter as I am clearly being correctly forwarded.

**Comment by Akruidenberg** [comment]
Same issue for me.

**Comment by BeryJu** [comment]
@Rojikku @Akruidenberg can you try this on the latest `gh-master` build? If that build breaks anything you can revert to the latest `gh-next`.

**Comment by Akruidenberg** [comment]
Maybe I have some time by the end of this week.

**Comment by Rojikku** [comment]
@BeryJu This works beautifully! Please let me know when it is officially released so that I can switch back to using a stable version. Quite happy with this, thank you.
