### ISSUE TITLE
Configuration Flow option is not present for WebAuthn setup stages

### ISSUE THREAD

**Issue by Maffsie** [goauthentik/authentik#2084]
**Describe the bug**
When creating a WebAuthn Setup stage, the "Configuration flow" option is not present, meaning a user cannot set up the authenticator without some manual SQL being run.

**To Reproduce**
1. Delete the default-authenticator-webauthn-setup stage and flow
2. Create a new WebAuthn Authenticator Setup Stage stage
3. Create a new Stage Configuration flow
4. Bind the stage created in step 2
5. Click "Edit Stage"
6. Observe that the "Configuration flow" setting is not present.

**Expected behavior**
The "Configuration flow" setting should be present and able to be changed.

**Screenshots**
![Screenshot of a TOTP setup stage allowing the configuration flow to be set](https://user-images.githubusercontent.com/68005/148807988-9ac3e269-e789-4d5d-91ac-0ec69daefce7.png)
![Screenshot of a WebAuthn setup stage which does not have a configuration flow setting](https://user-images.githubusercontent.com/68005/148808124-1df76f7c-c0f4-48c7-a708-d4c77075adf0.png)

**Logs**
No relevant logs available

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.5
 - Deployment: docker-compose

**Additional context**
I was able to work around the issue by manually going into Postgres and querying for my flow ID using `select flow_uuid from authentik_flows_flow where name='gate-setup-mfa-webauthn';` and then updating the relevant stage with `update authentik_stages_authenticator_webauthn_authenticatewebauthXXXX set configure_flow_id='[The UUID from before]';`

Thank you for providing such a nice software package - i've now completely migrated away from Keycloak!

**Comment by BeryJu** [comment]
I must've forgotten to add this field when initially migrating to the SPA. Just FYI, you could've changed the flow via API since the field is in there, just not show. Navigate to `/api/v3/` to get to the API Browser
