### ISSUE TITLE
Passwordless flows don't function in production, but work fine when testing.

### ISSUE THREAD

**Issue by xcsdm** [goauthentik/authentik#2090]
**Describe the bug**
When using the Passwordless flow option in the Identification stage, users are told their key is unknown.  The error varies by platform.  When using the standard user/password/authenticator flow, they key works correctly for MFA.

**To Reproduce**
1.  Create a new Passwordless flow with 2 stages.  First, an Authenticator stage with WebAuthN enabled.  Second, a user login stage.
2.  Specify this Passwordless flow in the Identification stage options of your main authentication flow.
3.  Attempt to login using the "Security Key" link.

NOTE:  Adding an Identification stage before the Authenticator stage in the Passwordless flow allows it to work, but the user has to enter their username or e-mail address.

**Expected behavior**
A user, once selecting the Security Key option, should be able to enter their device pin, and be authenticated.

**Screenshots**
![image](https://user-images.githubusercontent.com/5168223/149203723-696c9782-e229-4829-bfd1-7e5d3e7f386b.png)
![image](https://user-images.githubusercontent.com/5168223/149203824-d88b7759-eead-4914-a304-92a0dd8652de.png)
![image](https://user-images.githubusercontent.com/5168223/149203930-49517619-3814-4587-a3ca-6262e3bbe3a3.png)

**Logs**
Failures are not logged.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.5
 - Deployment: docker-compose

**Additional context**
Test the flows within the Admin interface with or without the Inspector works as expected.  When deployed into production, the flow fails as described.

**Comment by xcsdm** [comment]
I was able to make it work.

I had to boot Kali Live CD, and register my WebAuthN device using the Chromium browser.  My normal is Windows/Firefox.

After registering my Yubikey with that setup, it works on Windows also.

https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Resident_Keys.html

**Comment by BeryJu** [comment]
In the latest beta, you can adjust more options for WebAuthn keys, can you try that? @xcsdm
