### ISSUE TITLE
Too many backups

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#2093]
**Describe the bug**
I noticed that my disk space was filling up, and saw that the authentik backups use a huge amount of disk space (>500GB).
When looking at the files, it seems that since version 2021.12.5, authentik creates a backup every minute from 1 to 2 am, so 60 backups per day.

**To Reproduce**
1. Look in the backup folder

**Expected behavior**
Authentik should make less backups :)

**Screenshots**

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.5
 - Deployment: docker-compose

**Additional context**
I also have a lot of old backups from previous versions, it seems the cleanup (i.e. keep only the last 10 as described in the docs) is not working properly.

**Comment by BeryJu** [comment]
The bug of creating way too many backups is fixed in the latest beta, and it should keep 30 backups
