### ISSUE TITLE
LDAP Provider with TOTP

### ISSUE THREAD

**Issue by guyguy333** [goauthentik/authentik#2094]
**Is your feature request related to a problem? Please describe.**

Some services are not supporting SAML, OAuth2, .. and only work with LDAP. However, MFA is currently not supported with LDAP Provider.

**Describe the solution you'd like**

Documentation says: 

> The only limitation is that currently only identification and password stages are supported, due to how LDAP works.

As a first implementation, it would be great to support TOTP : https://github.com/openldap/openldap/blob/master/contrib/slapd-modules/passwd/totp/slapo-totp.5

What about asking user to set password + TOTP in the password field ?  (Facebook used this solution few years ago with macOS integration.). It seems there is a password scheme for this solution: {TOTP1ANDPW}, {TOTP256ANDPW}, or {TOTP512ANDPW}

Another solution could be a one time password for LDAP Provider when user has MFA and so regular password must be denied.

**Describe alternatives you've considered**

No solution I'm aware of.

**Additional context**

**Comment by BeryJu** [comment]
I've been meaning to add support for this using some sort of separate like `|` or `;`, have not gotten around to it yet since I want to do some general cleanup in the authenticator validation stage before I add this.

**Comment by itxworks** [comment]
Hello, 
this would be the feature I was searching for - if for example  a 6-digit length of the TOTP is set - the password part would be thereafter ... similar like PrivacyIDEA 

[https://privacyidea.readthedocs.io/en/latest/webui/token_details.html?highlight=pin#set-pin](https://privacyidea.readthedocs.io/en/latest/webui/token_details.html?highlight=pin#set-pin)
[https://privacyidea.readthedocs.io/en/latest/_images/token-detail.png](https://privacyidea.readthedocs.io/en/latest/_images/token-detail.png)

thx

**Comment by hamptonmoore** [comment]
Any update on this? A separator would be a nice feature to have

**Comment by jacksgt** [comment]
Alternatively, it would be nice if the MFA stage can be skipped in the LDAP authentication flow.
Is this possible?

**Comment by BeryJu** [comment]
This will be possible in 2023.1

**Comment by AxokGit** [comment]
I setup LDAP Provider and enabled TOTP but cannot connect like you said (PASSWORD;123456). Without TOTP configured it works. What do I need to check ?
