### ISSUE TITLE
User write stages save changes when testing flows

### ISSUE THREAD

**Issue by sdimovv** [goauthentik/authentik#2105]
**Describe the bug**
In my specific case `akadmin` password was changed while testing the `default-password-change` flow.

**To Reproduce**
1. Go to flows
2. Open the `default-password-change` flow
3. Execute the flow (either `Normal` or `With Inspector`)
4. Go through the flow (remember the password you set!)
5. Logout
6. Log back in with the set password (old one does not work)

**Expected behavior**
When testing flows, user write stages must not save any changes.

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.5
 - Deployment: docker-compose

**Additional context**
N/A

**Comment by BeryJu** [comment]
This is expected behaviour currently, allthough not clearly communicated to the end user.

In the future a FlowPlan might have a "dry-run" flag to accomplish this
