### ISSUE TITLE
Proxy Redirect to Original URL

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#2109]
**Describe the bug**
When accessing an URL behind an authentik proxy provider, after authentication, the browser is redirect to the external host of the provider and not the original url. So the redirection goes like this:
- **app.domain/foo**
- app.domain/akprox/start
- authentik.domain/application/o/authorize/[...]
- authentik.domain/if/flow/[...]
- app.domain/akprox/callback
- **app.domain**

**To Reproduce**
1. Create a proxy provider (proxy, not forward auth)
2. Access a subfolder of the application associated with the provider
3. Get redirect to the root of the application

**Expected behavior**
The proxy should redirect to the original URL.

**Screenshots**

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.5
 - Deployment: docker-compose
 - embedded proxy outpost

**Additional context**
I have some applications where the main functionality is accessible in a subfolder (e.g. /web). With the current behaviour of authentik, I have to open the link to the application twice (once to authenticate and once to access the application in the subfolder) to reach the application.

**Comment by eglia** [comment]
I just wanted to say I really appreciate your work. Thanks a lot!
I have never seen a project where bugs are regularly fixed within hours of them being reported.

**Comment by szadan51** [comment]
Hi!
I have the same issue, even though it's completed. My use case might differ a bit. I'm using Guacamole behind Authentik and if i try to pass the direct client url the same thing happens. Maybe the issue is that for guacamole there is a # character in the URL. Can you guys help me figure it out?
