### ISSUE TITLE
Docs for checking discord guild membership

### ISSUE THREAD

**Issue by kylesferrazza** [goauthentik/authentik#2111]
Similar to the recently-added github org membership docs, Discord guild membership docs might be helpful for users.

I implemented this by first requesting the `guilds` scope from Discord, and then using the following expression policy:

```python
# Guild ID can be obtained by turning on discord developer options and then right clicking on a guild icon and choosing Copy ID.
accepted_guild_id = "111111111111111111"

connection = context['goauthentik.io/sources/connection']
access_token = connection.access_token

guilds = requests.get(
    "https://discord.com/api/users/@me/guilds",
    headers={
        "Authorization": "Bearer " + access_token
    }
).json()

user_matched = any(guild['id'] == accepted_guild_id for guild in guilds)

if not user_matched:
    ak_message("User is not member of the Discord guild.")

return user_matched
```

**Comment by kylesferrazza** [comment]
I can copy and change the docs already added to the GitHub provider and open a PR, if you'd like?

**Comment by rems25000** [comment]
> > Hi, can you tell me how you did it?
> 
> https://gitlab.com/kylesferrazza/authentik-config/-/blob/main/mydiscord.tf

Thank you for your quick response, I looked at the file, it looks like a complete config. but it is a .tk file. I looked in the docker I find no tk file to import it. and manually by interpreting the code to the GUI. I'm tearing my hair out.
can you tell me more about importing this config?

**Comment by kylesferrazza** [comment]
> can you tell me more about importing this config?

This is a [Terraform](https://www.terraform.io/) config to automate setting up Authentik using the [Authentik provider](https://registry.terraform.io/providers/goauthentik/authentik/latest) for Terraform. You can either set up a Terraform project yourself and use a `.tf` file similar to mine, or just look at my file to see how I set everything up and try to replicate manually.

**Comment by rems25000** [comment]
Ok great, I got it
I installed terraform (thank you for letting me know about this solution which will greatly facilitate things in the future).
I added the following provider.
Last question where should I put the configuration you kindly gave me?
`terraform {
  required_providers {
    authentik = {
      source = "goauthentik/authentik"
      version = "2023.2.1"
    }
  }
}

provider "authentik" {

##HERE ??
}`
