### ISSUE TITLE
Creating an Expression Policy is not possible

### ISSUE THREAD

**Issue by leon1995** [goauthentik/authentik#2119]
**Describe the bug**
When creating an Expression Policy, I am not able to write text into the expression

**To Reproduce**
1. Go to Policies
2. Click on Create Expression Policy

**Expected behavior**
I expect that it is possible to write an expression in the expression field

**Screenshots**
[screenshot](https://ibb.co/8cjrDjQ)

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.5
 - Deployment: docker-compose

**Comment by leon1995** [comment]
I just noticed, that this also applies to the attributes field when creating a group. I tried it with two different browsers.
Am I missing something?

**Comment by BeryJu** [comment]
This is a known (and fixed in the beta) bug in firefox, which browsers did you try?

**Comment by leon1995** [comment]
I also tried safari

**Comment by BeryJu** [comment]
Safari is also known to be cause issues due to apple being so slow with adding support for web features; the modal works in chrome/etc and in the beta also on firefox (probably also safari)

**Comment by leon1995** [comment]
okay thanks! then I´ll wait or use the beta
