### ISSUE TITLE
LDAP Server (outpost): cannot browse LDAP tree from root.

### ISSUE THREAD

**Issue by xpufx** [goauthentik/authentik#2120]
When connecting to the ldap server with a client none of the children of the root CN=authentik... is accessible. Clients provide different errors:
- ldapadmin.org client "LDAP error: Operations Error!"
- Apache Directory Studio: 

>  "Error while opening connection
>  Missing schema location in RootDSE, using default schema.
> Missing schema location in RootDSE, using default schema."

The issue seems to be the RootDSE missing (i don't know what that means) and client falling back to a default DSE.

Connecting to children (CN=user, CN=groups) works but the error messages are still there.

**Comment by BeryJu** [comment]
@ikogan can probably help a little better for this, I haven't really looked into how the LDAP Search works after their rewrite

**Comment by xpufx** [comment]
Come to think of it. You have authentik.io/xxxx object classes. They would not be installed on a standard client. That might be what it's talking about.

**Comment by ikogan** [comment]
@xpufx I believe you're absolutely right. Authentik doesn't currently expose the Root DSE. I don't believe it's ever had that functionality, yet. Currently, you should be able to see:

- Your Base DN (`DC=authentik,DC=company`) for example.
- The containers for users (`OU=users,DC=authentik,DC=company`), groups (`OU=groups,DC=authentik,DC=company`), and virtualgroups (`OU=virtual-groups,DC=authentik,DC=company).
- Objects directly underneath those OUs.

I 100% agree with you that it would be great if a real root DSE was implemented. Right now, we take a shortcut by simply responding with the Base DN object when you ask for the Root DSE (note that Authentik was doing this already before the search changes).

You should be able to browse the whole tree by supplying a Base DN equal to what you setup in your LDAP Provider, and connecting as any user that is in the group set in the "Search group" field of the provider.

If your client absolutely demands the schemas be there...it might have trouble browsing. Apache Directory Studio pukes the error you mentioned but can still browse the tree.

We could maybe make these clients happy by just adding a `subschemaSubentry` attribute to the Base DN? I'm honestly not sure what the correct way to do this is, maybe I/We should grab a beer or 12 and read [RFC4512](https://datatracker.ietf.org/doc/html/rfc4512)...

You can see the code for the base entry here: https://github.com/goauthentik/authentik/blob/master/internal/outpost/ldap/instance.go#L96

**Comment by xpufx** [comment]
@ikogan thanks. Do you mean that if my BaseDN is "cn=authentik,dc=company,dc=com" I should be able to browse it now and see cn=users cn=groups,cn=virtualgroups with the current way authentik ldap outpost works? I can see the contents of users and groups if I set my basedn to them while connecting but now if I set it to cn=authentik,dc=company,dc=com . All i see is the basedn itself with no children and basically no operations can be done on that single root.

**Comment by ikogan** [comment]
Which client are you using?

**Comment by xpufx** [comment]
Apache DS and ldapadmin.

**Comment by ikogan** [comment]
Make sure you don't have "Get base DNs from Root DSE" checked in your connection settings and set your Base DN manually. Also, this would be weird if it impacted anything, but can you try an outpost with a Base DN that _only_ has domain components (so only DC= attributes, no CN=).

If you select your Base DN after loading it, what do you see as `namingContexts`?

**Comment by xpufx** [comment]
Setting the outpost's base dn to dc=domain,dc=com produces the same result. I can see the basedn itself with no children. My outpost version is 2021.12.4 (i thought it was 12.5 which rest of my setup is.) I upgraded to 12.5. Same result.   I **can** "Go To DN" if I manually enter children DNs.

Here's the ldif for the root object (domain sanitized).

> version: 1
> 
> dn: DC=DOMAIN,DC=com
> objectClass: domain
> objectClass: top
> distinguishedName: DC=DOMAIN,DC=com
> namingContexts: DC=DOMAIN,DC=com
> namingContexts: ou=groups,dc=DOMAIN,DC=com
> namingContexts: ou=users,dc=DOMAIN,DC=com
> namingContexts: ou=virtual-groups,dc=DOMAIN,DC=com
> supportedLDAPVersion: 3
> vendorName: goauthentik.io
> vendorVersion: authentik LDAP Outpost Version 2021.12.5 (build tagged)

**Comment by xpufx** [comment]
Talking to ikogan we've determined that the issue in the title was caused by case-sensitivity mismatch between the BASE DN in provider settings and client Bind DN. Closing.

**Comment by ikogan** [comment]
I'll try and get a patch out for it soon.
