### ISSUE TITLE
Twilio Setup Error

### ISSUE THREAD

**Issue by firestrife23** [goauthentik/authentik#2127]
**Describe the bug**
Cannot setup SMS authenticator due to "This field may not be blank" message... but it's not blank

**Screenshots**
![Imgur](https://i.imgur.com/RoNGhwx.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.1
 - Deployment: docker-compose

**Comment by ConsoleCriminal** [comment]
What actually works:
* Memorize the order of the fields
* Switch to another provider
* Fill in the fields
* Switch back
* Hit save

(Still doesn't work for me, but it safes then......)
