### ISSUE TITLE
Forward auth proxy with docker and traefik: Missing path in traefik configuration?

### ISSUE THREAD

**Issue by agrimpelhuber** [goauthentik/authentik#2128]
**Describe your question**

Trying to use forward auth proxy with Traefik in a Docker environment. Everything works according to he [documentation](https://goauthentik.io/docs/providers/proxy/forward_auth), including the automatic deployment of the docker-based proxy container and its configuration in Traefik.

However, shouldn't the proxy be configured with a router rule that includes a host and a path "/akproxy" part as in the example for manual configurations?

`traefik.http.routers.authentik.rule: Host('auth.app.company') && PathPrefix('/akprox/')`

Apparently, the automatic setup only sets up a rule for the host

`traefik.http.routers.authentik.rule: Host('auth.app.company')`

Since my whole authentik installation resides unter 'auth.app.company', it can't be reached after the proxy container is up, because the proxy's router precedes that one for Authentik in the Traefik configuration.

I tried to move the proxy to something like 'login.app.company' to avoid these conflicts, but in this case, Traefik will not be able to provide the proper Let's Encrypt certificate for 'login.app.company', because it would need additional labels like `      - "traefik.http.routers.my-outpost.tls.certresolver=myresolver"` in the docker configuration.

Im not entirely sure, but I guess adding `&& PathPrefix('/akprox/')` to the automatic docker configuration might do the trick. [Here?](https://github.com/goauthentik/authentik/blob/aea1736f7024a39a7268bcf7d0adb26591f0d26b/authentik/providers/proxy/controllers/docker.py#L29)

**Relevant infos**
Hopefully all provided above

**Screenshots**
n/a

**Logs**
n/a

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.1
 - Deployment: docker-compose
 - Traefik 2.5.7

**Additional context**
n/a

**Comment by BeryJu** [comment]
Fixed both, you can now add custom labels to docker containers and i also added the path

**Comment by agrimpelhuber** [comment]
First of all: Wow, that was quick! Do you ever sleep? ;-) I was so thrilled that I immediately pulled the changes.

However, sorry to report that Traefik throws an error:

``error while parsing rule Host(`auth.app.company`) && PathPrefix('/akprox'): 1:46: illegal rune literal``

Looks as if Traefik can't cope with single quotes instead of backticks in [this line](https://github.com/goauthentik/authentik/blob/42f5cf8c93ff5325c871a1a949cafb099edbc7eb/authentik/providers/proxy/controllers/docker.py#L31). Probably my fault, because in my report, I used single quotes to get around the limitations of md in y initial report. Sorry!

**Comment by BeryJu** [comment]
my fault as well for not testing, no worries though @agrimpelhuber 22.1.3 will probably be out soon since there's some other things to fix
