### ISSUE TITLE
Can I get password from LDAP output?

### ISSUE THREAD

**Issue by tomcsi** [goauthentik/authentik#2142]
**Describe your question/**
I would like to create freeradius server with ldap based authentik. I created the ldap outpost, and connect it, but I cannot get password from it. Possible get from ldap outpost the user's password?

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.2
 - Deployment: helm

**Comment by BeryJu** [comment]
authentik does not save the plain text password of users. This could technically be done using user attributes, but I'd recommend against that, since the data is not encrypted on disk. This is one of the main reasons why there's no native RADIUS support.
