### ISSUE TITLE
Locale Auto-detect don't work

### ISSUE THREAD

**Issue by Izanagi52** [goauthentik/authentik#2178]
**Describe the bug**
My browser language (Firefox and Edge Chromium) is set to French and Authentik language in user page is set to Auto-detect.
But Authentik is displayed in English.
(I haven't check with other language)

**To Reproduce**
1. Open Authentik in a browser set in french
2. If not, set Authentik language in Auto-detect
3. Authentik displayed in English

**Expected behavior**
Authentik displayed in correct language.

**Screenshots**
![Capture d’écran 2022-01-28 101138](https://user-images.githubusercontent.com/21294450/151521211-dcc9c3f8-8e3f-48ad-aef9-b1167d908693.png)
![Capture d’écran 2022-01-28 101203](https://user-images.githubusercontent.com/21294450/151521226-44588f81-72f0-4102-8280-adeea26b0a67.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.3
 - docker-compose

**Comment by BeryJu** [comment]
Could you check the browser developer console, you should see a message like `authentik/locale: No locale for 'en-GB', falling back to en`, could you post that?

**Comment by Izanagi52** [comment]
`authentik/locale: No locale for 'fr', falling back to en`
(Same message for Firefox and Edge)

**Comment by BeryJu** [comment]
@Izanagi52 can you test with the latest gh-master build? Instructions are here https://goauthentik.io/docs/installation/beta, just use gh-master instead of gh-next

**Comment by Izanagi52** [comment]
I think I can't...
I run Authentik on Ubuntu for ARM64 (RPi4), and I think this image aren't make for ARM, I have this error on server and worker:
`standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by BeryJu** [comment]
oh yeah the dev images aren't built for arm64 just to make the CI pipeline shorter

**Comment by BeryJu** [comment]
@Izanagi52 can you try with 2022.1.4?

**Comment by Izanagi52** [comment]
Perfect, it works! It was fast ^^

Thank you !
