### ISSUE TITLE
Redirect prompt with new applications. Prior apps created with 2021.12 are working fine.

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#2181]
**Describe your question/**
Every time a new provider is created, i´m getting a redirecting dialog.

**Relevant info's**

Every time a new provider is created, I'm getting a redirect prompt. After re-login the prompt is shown again. This is only with new created applications/providers. Existing providers are working fine. The problem exist with Oauth2 and traefik forrward auth single domains. Is this normal?

**Screenshots**
**![afbeelding](https://user-images.githubusercontent.com/18529293/151659050-d8b85838-101b-4e87-a66a-755b2323f8dd.png)**

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.3
 - Deployment: Docker Compose

**Comment by djeclemen** [comment]
Check your provider - Authorization flow - looks like you selected explicit consent instead of implicit consent

**Comment by Akruidenberg** [comment]
Strange. Looks like the default is changed. Dit not have this in the past. Thanks @djeclemen. Closed
