### ISSUE TITLE
Fastapi Integration

### ISSUE THREAD

**Issue by incoggnito** [goauthentik/authentik#2198]
**Describe your question/**
Is there any fastapi integration guide?

**Relevant infos**
https://fastapi.tiangolo.com/external-links/

**Additional context**
I've trouble implementing the correct oauth_scheme.

**Comment by devcomputer** [comment]
Docs on FastAPI integration would still be great.
this guy made a video:
https://www.youtube.com/watch?v=EB3sEQguEbI
