### ISSUE TITLE
HTTP ERROR 431 after new-years-update and a few days

### ISSUE THREAD

**Issue by theoneandonly-vector** [goauthentik/authentik#2199]
**To Reproduce**
Setup Authentik as a protective reverse-proxy for Uptime-Kuma according to this guide:
https://goauthentik.io/integrations/services/uptime-kuma/
use Uptime-Kuma on Release 2021.12.5 successfully for about 18 days.
update authentik to v 2022.1.2 or 2022.1.3
use uptime-kuma as usual.
wait 2-3 days
then access protected part of uptime-kuma "/dashboard" -> it stops working with the HTTP ERROR 431.
then remove all site-date from browser and access non-protected part of uptime-kuma "/status" -> works..
then access protected part of uptime-kuma "/dashboard" again -> it stops working with the HTTP ERROR 431.

I can reproduce this issue by restoring a version where it works even with the latest release (2022.1.3) and wait without changing anything at all and it will stop working.

**Expected behavior**
I don't get "HTTP ERROR 431" when accessing Uptime Kuma.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.3
 - Deployment: docker-compose
 - nginx/1.21.6 as a reverse-proxy

**Additional context**
I already tried adding extremely high values for allowed header size in my nginx-reverse-proxy

when I shut down Uptime Kuma I just get "504 Gateway Time-out" -error message from nginx.
when Uptime-Kuma is up I get the "HTTP ERROR 431" directl yin the browser (doesn't display this as a nginx-error).

my nginx-config:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name sso.mydomain.tld;
    location / {
        return 301 https://$host$request_uri;
    }
    location /.well-known/acme-challenge/ {
    root /var/www/certbot;
}
}
server {
    # Server config
    listen 443 ssl http2;
    server_name sso.mydomain.tld;
    # SSL Certs
    ssl_certificate /etc/letsencrypt/live/mydomain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.tld/privkey.pem;
    # SSL Parameter
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    # Proxy site
    location / {
        proxy_pass http://server:9000;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```

I also already tried with this in my location-block:
large_client_header_buffers 4 512k;
proxy_busy_buffers_size 512k;
proxy_buffers 4 512k;
proxy_buffer_size 256k;

and seperately:
proxy_buffering off;

nothing worked so far.

**Comment by BeryJu** [comment]
So are you using the proxy provider in authentik proxy mode? Since there's no forward auth in your config I assume so? Also can you post a screenshot of the error message?

**Comment by theoneandonly-vector** [comment]
yes I only use "proxy mode" no "Forward Auth" and then I just select which part should be restricted and disable uptime-kumas own authentication-page, as described in the docs: https://goauthentik.io/integrations/services/uptime-kuma/

Screenshot:
![image](https://user-images.githubusercontent.com/10380051/151850637-348e7521-85eb-436c-ac8b-eaf7d55440d0.png)

**Comment by BeryJu** [comment]
So I just tried this setup with NPM (Browser -> NPM -> authentik -> Uptime Kuma), and it works fine. It generated this config for uptime kuma:

```
server {
  set $forward_scheme http;
  set $server         "uk.10.120.20.57.nip.io";
  set $port           9000;

  listen 80;
listen [::]:80;


  server_name uk.10.120.20.57.nip.io;

  access_log /data/logs/proxy-host-1_access.log proxy;
  error_log /data/logs/proxy-host-1_error.log warn;

  location / {
    # Proxy!
    set              $targetUri $forward_scheme://$server:$port$request_uri;
    add_header       X-Served-By $host;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_pass       $targetUri;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}

```

Could you post your nginx config for uptime kuma too

**Comment by theoneandonly-vector** [comment]
there is no nginx-config for uptime kuma @my setup.

**Comment by BeryJu** [comment]
But your nginx config only has a single `server_name` entry so it would only route requests to sss.domain

**Comment by theoneandonly-vector** [comment]
it only has a single server_name but smh this is "working" everywhere I tried..

**Comment by BeryJu** [comment]
How many groups is your user in  in authentik? This causes the size of the JWT header to vary, which mostly causes the 431. Also I'm pretty certain that the 431 is *not* caused by nginx, since nginx should return its custom error page. 

Could you try running uptime kuma with this command? `node --max-http-header-size=16384 server/server.js`

**Comment by theoneandonly-vector** [comment]
I run:
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma node --max-http-header-size=16384 server/server.js

also results in "HTTP ERROR 431"

the user is in 7 groups.
but what I also just noticed is that the user has about "283" times the first and lastname (actually every user has this smh).
they are synched using LDAP.

while distinguishedName and ldap_uniq is there "only" once.

**Comment by BeryJu** [comment]
Can you try accessing uptime kuma after removing those attributes?

Also which LDAP Server are you syncing from?

**Comment by theoneandonly-vector** [comment]
yes.. removing these fixes it.

I use Univention (OpenLDAP not samba)

The Last and Firstname look like this:
LastName:
  - myLastname
  - myLastname
  - myLastname

the other attributes are only using the first line.

**Comment by BeryJu** [comment]
So the reason why this happens is because LDAP property mappings for anything starting with `attributes`, arrays are interpreted as-is, because there are valid usecases to map an entire array into an attribute.

I think I'll change the default OpenLDAP mappings to flatten those fields instead of taking them as is.

**Comment by theoneandonly-vector** [comment]
thx

**Comment by theoneandonly-vector** [comment]
@BeryJu 
the latest update (2022.1.4) isn't fixing it. I removed all Entrys of Last and Firstname of one user and did a mnual resync -> updated the user correctly with one entry for each attribute. then I synched again and got a 2nd entry on both.

**Comment by BeryJu** [comment]
Please open a new issue for that as its not really related to this.
