### ISSUE TITLE
Problem while synching users from OpenLDAP (on Univention UCS)

### ISSUE THREAD

**Issue by theoneandonly-vector** [goauthentik/authentik#2211]
**Describe the bug**

The Last and Firstname have multiple entries, the other attributes are correctly only using the first line:
```
LastName:
  - testsso
  - testsso
  - testsso
  - testsso
ldap_uniq: S-1-5-21-3838167704-4242945314-4055385577-1162
first_name:
  - testsso
  - testsso
  - testsso
  - testsso
distinguishedName: uid=testsso,cn=users,dc=mydomain,dc=tld
```

**To Reproduce**
1. setup LDAP-Sync in Authentik with OpenLDAP-part of Univention UCS
2. synch LDAP-users more than once

**Expected behavior**
users get synched normally, without adding a new LastName & first_name on each synch.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.4
 - Deployment: docker-compose

**Additional context**
I use Univention (OpenLDAP not samba)

**Comment by BeryJu** [comment]
Can you post your LDAP config too?

**Comment by theoneandonly-vector** [comment]
![image](https://user-images.githubusercontent.com/10380051/152158079-a15b96ac-6804-4ff7-8c37-c20c61ccdf65.png)
![image](https://user-images.githubusercontent.com/10380051/152158181-a6a02607-29c6-4ef9-b363-190e39d3543c.png)
![image](https://user-images.githubusercontent.com/10380051/152158229-1ab29601-f4b5-4dde-baea-0a2a8ae1db1e.png)
I used "sambaSID" as the Object uniqueness field because I smh didn't find a value for users and groups.. they seem to have a seperate unique-ID attribute.

**Comment by Devou987** [comment]
I just checked and I'm also having the same problem.

**Comment by theoneandonly-vector** [comment]
anything else I can do to help? :)

**Comment by BeryJu** [comment]
I finally got UCS to allow for an LDAP bind, what does your custom property mapping for firstname and lastname look like? @theoneandonly-vector

**Comment by theoneandonly-vector** [comment]
if you are talking about this:
![Screenshot_20220212-225015](https://user-images.githubusercontent.com/10380051/153729609-e11dd57e-adf7-440a-a133-5fff658b75ec.jpg)

I didn't change it.
