### ISSUE TITLE
OAuth2 Property Mappings are missing from docs

### ISSUE THREAD

**Issue by jaller94** [goauthentik/authentik#2223]
**Describe your question/**
What Property Mappings does authentik provide for OAuth2 and which scopes do they require?

**Relevant infos**
* [ ] The link Property Mappings on the page "OAuth2 Provider" 404s.
   * https://goauthentik.io/docs/providers/oauth2 
* [ ] The page Property Mappings doesn't list OAuth2 mappings.
   * Property Mappings: https://goauthentik.io/docs/property-mappings/#scope-mapping

**Comment by xpufx** [comment]
The oauth2 page loads fine now. Sometimes the documentation site glitches after changes are pushed from github. It must have been that.

On my system the default scopes for oauth are email, openid and profile. A new one seems to be added to pass the username to the outposts. You can see your own settings at /if/admin/#/core/property-mappings if you unclick the Hide Managed mappings box at the top.
