### ISSUE TITLE
Internet Explorer Compatiblilty

### ISSUE THREAD

**Issue by bbrendon** [goauthentik/authentik#2230]
We have an ERP app that is basically a wrapper to Internet Explorer. The app supports SAML but apparently authentik doesn't support IE so when authenticating, I get a "Loading" screen. The App has official support for ADFS/Azure which does seem to support IE.

Is there a way to dumb down the HTML in authentik to make it more compatible?

Screenshot below.

![image](https://user-images.githubusercontent.com/6364477/152489027-aed611a4-6724-4e3c-b834-805ce24cf2c9.png)

**Comment by samip5** [comment]
That might actually just be React not supporting IE, and frankly that's quite not fun to support to my knowledge. :/

**Comment by BeryJu** [comment]
Due to the web technologies we use and the effort required to keep supporting IE, we won't be implementing this.
