### ISSUE TITLE
Forward proxy (single app) instructions for k8s nginx ingress result in 500 error

### ISSUE THREAD

**Issue by speedst3r** [goauthentik/authentik#2235]
**Describe the bug**
Running nginx-ingress-controller 1.1.1 on Microk8s 1.23.3, the instructions to set the host header in the auth-snippet result in a 500 error. Debugging on the controller reveals that two Host headers are being sent: the domain Authentik is hosted under and the header set in the snippet. As Authentik does not receive the application domain, it returns a 400 error to the ingress controller, which in turn returns a 500 to the client.

My understanding of the ingress controller is that this is how it builds the external auth configuration via it's template. This is the resulting location section in the controller's nginx.conf:

```
location = /_external-auth-Lw-Prefix {
                        internal;

                        # ngx_auth_request module overrides variables in the parent request,
                        # therefore we have to explicitly set this variable again so that when the parent request
                        # resumes it has the correct value set for this variable so that Lua can pick backend correctly
                        set $proxy_upstream_name "default-app-3000";

                        proxy_pass_request_body     off;
                        proxy_set_header            Content-Length          "";
                        proxy_set_header            X-Forwarded-Proto       "";
                        proxy_set_header            X-Request-ID            $req_id;

                        proxy_set_header            Host                    authentik.mydomain;
                        proxy_set_header            X-Original-URL          $scheme://$http_host$request_uri;
                        proxy_set_header            X-Original-Method       $request_method;
                        proxy_set_header            X-Sent-From             "nginx-ingress-controller";
                        proxy_set_header            X-Real-IP               $remote_addr;

                        proxy_set_header            X-Forwarded-For        $remote_addr;

                        proxy_set_header            X-Auth-Request-Redirect $request_uri;

                        proxy_buffering                         off;

                        proxy_buffer_size                       4k;
                        proxy_buffers                           4 4k;
                        proxy_request_buffering                 on;
                        proxy_http_version                      1.1;

                        proxy_ssl_server_name       on;
                        proxy_pass_request_headers  on;

                        client_max_body_size        1m;

                        # Pass the extracted client certificate to the auth provider

                        proxy_set_header Host $host;

                        set $target https://authentik.mydomain/akprox/auth/nginx;
                        proxy_pass $target;
                }
```

**To Reproduce**
1. Create provider and application and configure the ingress as per provider instructions
2. Attempt to access application
3. error!

**Expected behavior**
Redirection to Authentik, access the application on successful auth

**Logs**

```
{"event":"no app for hostname","host":"authentik.mydomain","level":"warning","logger":"authentik.outpost.proxyv2","timestamp":"2022-02-05T12:13:07Z"}
{"event":"no app for hostname","host":"authentik.mydomain","level":"warning","logger":"authentik.outpost.proxyv2","timestamp":"2022-02-05T12:13:07Z"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.4
 - Deployment: helm

**Additional context**
Configuring the auth-url and auth-signin to use the application's domain (as the /akprox path is automatically configured to the embedded outpost) results in a successful flow.

**Comment by BeryJu** [comment]
@speedst3r I've just updated the docs, using the internal address for authentication requests and using the external URL for signing in, please check if this works with your setup too

**Comment by BeryJu** [comment]
@speedst3r with this updated documentation and multiple application it correctly routes to the correct application
