### ISSUE TITLE
Restrict Self Service

### ISSUE THREAD

**Issue by lucasra1** [goauthentik/authentik#2246]
**Is your feature request related to a problem? Please describe.**
I'm using authentik for our company. I even use it for our email server as authentication over the ldap outpost. Now I want to restrict the self-service, so the users can't change their email.

**Describe the solution you'd like**
Some method to restrict self-service. Doesnt have to be complex. Just to disable email changing for example.

**Describe alternatives you've considered**
Nothing, I have to trust the employees, so they dont change their data

**Comment by BeryJu** [comment]
See https://goauthentik.io/docs/user-group/user#goauthentikiousercan-change-email, you can set that attribute on a group that all the users can be added to.

**Comment by lucasra1** [comment]
Exactly what i searched for. Thank you!

This issue can be closed then, I guess...

**Comment by septatrix** [comment]
@BeryJu The link you posted does not work anymore. Searching in the current docs for similar terms also does not yield any results about the attribute. There is `AUTHENTIK_DEFAULT_USER_CHANGE_NAME` in the config section (which I at first confused with settings for the default user, i.e. akadmin) but the attributes on users are not explained. They also still seem to exist at least somewhere in the codebase:

https://github.com/goauthentik/authentik/blob/2fb8d4b410660081a65d0490c40274a2ca7ad9b1/authentik/core/models.py#L45-L47

Are there any up-to-date docs on these attributes? Authentik is really great but I think documentation is the only thing which I regularly find to be a bit lacking.

**Comment by mxctx-jake** [comment]
See this page for the latest documentation https://goauthentik.io/docs/user-group-role/user/user_ref#goauthentikiousercan-change-email

**Comment by Mrs-Feathers** [comment]
sorry for posting, but this is the same issue i was looking up so best not to make a duplicated issue..

the link provided lists urls as the attributes. how am i to use those?

this?
{
goauthentik.io/user/can-change-name: false
}

this one?
{
USER_ATTRIBUTE_CHANGE_USERNAME: false
}

or this one?
{
can-change-name: false
}

its confusing being that theres no example on the page...

**Comment by l4rm4nd** [comment]
We've created a custom policy for that at `Customizations > Policies`.

The policy is named `default-user-settings-authorization` and allows changing the username, e-mail and name only, if the user has the specific rights via attributes. 

Here is the py expression for the policy:

````
from authentik.core.models import (
    USER_ATTRIBUTE_CHANGE_EMAIL,
    USER_ATTRIBUTE_CHANGE_NAME,
    USER_ATTRIBUTE_CHANGE_USERNAME
)
prompt_data = request.context.get("prompt_data")

if not request.user.group_attributes(request.http_request).get(
    USER_ATTRIBUTE_CHANGE_EMAIL, request.http_request.tenant.default_user_change_email
):
    if prompt_data.get("email") != request.user.email:
        ak_message("Not allowed to change email address.")
        return False

if not request.user.group_attributes(request.http_request).get(
    USER_ATTRIBUTE_CHANGE_NAME, request.http_request.tenant.default_user_change_name
):
    if prompt_data.get("name") != request.user.name:
        ak_message("Not allowed to change name.")
        return False

if not request.user.group_attributes(request.http_request).get(
    USER_ATTRIBUTE_CHANGE_USERNAME, request.http_request.tenant.default_user_change_username
):
    if prompt_data.get("username") != request.user.username:
        ak_message("Not allowed to change username.")
        return False

return True
````

![image](https://github.com/user-attachments/assets/eb40806c-830b-4598-91d4-92d93e5ff604)

If you have users that should be allowed to change such fields, add the corresponding permission at the user's attribute field as admin. Just browse Directory > Users. Select your user, hit edit and add the following at the attributes section:

````
goauthentik.io/user/can-change-name: true
goauthentik.io/user/can-change-username: true
goauthentik.io/user/can-change-email: true
````

![image](https://github.com/user-attachments/assets/dfe1c3b7-5a60-43f3-bbd4-cfda5e3d1349)
