### ISSUE TITLE
Custom social login source icon

### ISSUE THREAD

**Issue by deluxghost** [goauthentik/authentik#2281]
**Is your feature request related to a problem? Please describe.**
I use multiple generic OIDC login sources, and it's hard to recognize for the first time without the full name display
I didn't find an option for this, if there is, tell me please

**Describe the solution you'd like**
Just like custom app icons, allow us to custom social login icons

**Describe alternatives you've considered**
Not yet

**Additional context**
No

**Comment by rafaribe** [comment]
Is there any progress in this issue? I tried to find the source code that would allow me to change it to something custom but cannot find it. Can you @BeryJu point me to the right direction? Thank you.

**Comment by LeehamElectronics** [comment]
Would like to see this integrated also.
