### ISSUE TITLE
Proxy: Host Header Set to Internal Host

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#2284]
**Describe the bug**
Since 2022.1.5, the "Host" header of a proxy provider is set to the internal URL. Previously it was set to the external URL (or kept from the original request). This causes issue with some of my proxied applications which then redirect based on this header to an internal URL which is not accessible by the client.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.5
 - Deployment: docker-compose
 - Provider: Embeded Proxy Provider (not forward)

**Additional context**

**Comment by BeryJu** [comment]
So this is actually how it should've worked all along, and when I added the fix I didn't consider that it could very well break usecases where another reverse proxy is behind the proxy provider that switches based on the header. I feel bad unitentionally introducing/fixing this in a patch release, I'll add a notice to the release notes.

I'm not sure if it makes sense to cut an entire release just to roll this back in a patch release only to re-introduce it in the next monthly version though

**Comment by BeryJu** [comment]
Actually I decided to add `X-Forwarded-Host`, which can be easily configured in nginx/etc if they're behind the proxy, and those are probably the main usecase that are affected by this

**Comment by eglia** [comment]
Thanks for your reply.
I already suspected that this was an intentional change, and maybe this is the "proper" way to handle it.
However, it leaves me with a bit of a problem with two of my apps, [fava](https://github.com/beancount/fava) and [bazarr ](https://github.com/morpheus65535/bazarr). They both work by sending a 302 redirect when accessing the base url.

My setup looks like this:

|| Nginx Proxy Manager -> | Authentik -> | App |
|--|--------------|-----------|------------|
|URL| app.mydomain.com | authentik.internal | app.internal |

Nginx Proxy Manager sets the Host header to the external URL (app.mydomain.com), which is used by authentik to differentiate between the applications (I assume). Authentik then sets the Host header to the internal URL (app.internal).
When accessing the external URL by a client (app.mydomain.com), the app then responds with a 302 redirect to app.internal/something.
The app is not a reverse proxy, but seems to use the host header for routing.

The easy solution for my usecase would be if I could specify the Host header being sent by authentik (either explicitly or select between internal/external URL), or if authentik would rewrite the location header, similar to the nginx [proxy_redirect](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect) directive.
If this is not possible, the workaround seems to be to set the "proxy_redirect" directive in nginx proxy manager. This is however not so nice, since I then have to specify the internal URL of the app in two places (authentik and nginx proxy manager).

PS: Most of my apps work fine with the change, so I wouldn't say that authentik is doing it wrong. But at least for fava, [the developer considers this to be the responsibility of the reverse proxy](https://github.com/beancount/fava/issues/1354).
PPS: The  X-Forwarded-Host seems not to be used by those apps.

**Comment by Cookie-Monster-Coder** [comment]
Why is this closed when the problem still exist?

**Comment by yusf** [comment]
You ever got anywhere with authentik+fava?

**Comment by eglia** [comment]
I actually switched for forward auth in the meantime, so this issue no longer affects me. But I think it should be solved anyway.

**Comment by ConnorEMacLean** [comment]
> I actually switched for forward auth in the meantime, so this issue no longer affects me. But I think it should be solved anyway.

Egila I believe I am running into the same problem you are describing with "gaps" I see you mention adding the proxy_redirect directive within NPM. I was wondering if you could share an example of what that might look like. 

Fairly new to all this and I am using the vanilla NPM setup given to you with Authentik so a bit unsure of where/exactly how to forward the additional proxy_redirect line.

Or if the forward auth switch you mention above I'm not exactly sure what you meant here either. Thanks in advanced for any guidance you can provide and apologizes for the beginner questions!

**Comment by iwantdat** [comment]
Hey I'm also experiencing this issue using NPM with radarr and prowlarr forwarding tho authentik. I am getting redirected to the internal IP address. Everything was working correctly previously.

@eglia would you mind providing where you can add the line of code for the fix at NPM? Or explain how you fixed the issue using Forward Auth?

@beryju would you be able to let us know how to fix the issue if not?

Sorry to bring up and older topic, I searched all around and could only find this thread on the issue.

**Comment by arodriguez401** [comment]
is there an update on this issue. I am also having this issue

**Comment by Mrs-Feathers** [comment]
i'm also having this issue

**Comment by Mrs-Feathers** [comment]
i understand this is how its supposed to work but i dont understand how i'm supposed to get around this issue. do i need to set X-Forwarded-Host or change something in the config authentik generates for me?
