### ISSUE TITLE
SMS token does only work as long it's the only enrolled MFA Device

### ISSUE THREAD

**Issue by itxworks** [goauthentik/authentik#2290]
SMS tokens are only sent if the SMS device is the only registered device for that user

If an additional device is enrolled, the user never receives the SMS token.

After removing all other devices from the User account, SMS tokens will be sent again.

   - Authentic version: 2022.1.5
   - Deployment: docker-compose

**Comment by rinky-dinky** [comment]
Noticed this same issue on 2022.2.1, exactly as you described.
