### ISSUE TITLE
Generate invitation links automatically using a dedicated flow

### ISSUE THREAD

**Issue by mvnmgrx** [goauthentik/authentik#2311]
Is there any way to create a dedicated flow that generates user invitation links?

In my deployment i want to generate the users by myself. I am currently doing that by creating an invitation for every user with the `username` and `name` fields set manually.

A more automated approach would be nice for this. For example a flow for administrators, that queries for the new user's name and username (maybe with a prompt stage) and generates a invitation link in exchance that i can then forward to the new user. Or does the API provide functionality for that so that i can build something like this outside of Authentik?

**Comment by samip5** [comment]
> Is there any way to create a dedicated flow that generates user invitation links?
> 
> In my deployment i want to generate the users by myself. I am currently doing that by creating an invitation for every user with the `username` and `name` fields set manually.
> 
> A more automated approach would be nice for this. For example a flow for administrators, that queries for the new user's name and username (maybe with a prompt stage) and generates a invitation link in exchance that i can then forward to the new user. Or does the API provide functionality for that so that i can build something like this outside of Authentik?

The API already provides such functionality.

Example of a maubot plugin:
```py
import uuid
from typing import Type
from mautrix.util.config import BaseProxyConfig, ConfigUpdateHelper
from maubot import Plugin, MessageEvent
from maubot.handlers import command
import aiohttp
import arrow


class Config(BaseProxyConfig):
    def do_update(self, helper: ConfigUpdateHelper) -> None:
        helper.copy("command_prefix")
        helper.copy("authentik_base_url")
        helper.copy("authentik_api_token")
        helper.copy("authentik_flow")


class Authentik(Plugin):
    async def start(self) -> None:
        await super().start()
        self.config.load_and_update()

    @classmethod
    def get_config_class(cls) -> Type[BaseProxyConfig]:
        return Config

    def get_command_name(self) -> str:
        return self.config["command_prefix"]

    @command.new(name=get_command_name, aliases="invite")
    async def invite(self, evt: MessageEvent):
        if evt.room_id == "<snip>":
            token_expire = arrow.utcnow().shift(weeks=+1).format('YYYY-MM-DDTHH:MM:SSZ')
            url = "api/v3/stages/invitation/invitations/"
            id = uuid.uuid4()
            data = {
                "expires": f"{token_expire}",
                "single_use": True
            }

            async with aiohttp.ClientSession() as session:
                headers = {
                    "Authorization": f"Bearer {self.config['authentik_api_token']}",
                    "Accept": "application/json",
                    "Content-Type": "application/json"
                }
                async with session.post(f"{self.config['authentik_base_url']}/{url}", json=data, headers=headers) as resp:
                    if resp.status == 201:
                        response_data = await resp.json()
                        expires = response_data["expires"]
                        pk = response_data["pk"]
                        await evt.reply(f"Invite created. It expires at: {expires}. URL: <{self.config['authentik_base_url']}"
                                        f"/if/flow/{self.config['authentik_flow']}/?itoken={pk}>")
                    else:
                        await evt.reply(f"Recieved an error from API, {resp.status}")
        else:
            await evt.reply("You're not authorized to use this command.")
```

**Comment by mvnmgrx** [comment]
Thanks for this snippet! I will try this out once i got some spare time, but it seems to do exactly what i want. 

If i'm interpreting this correctly it should be possible to append a username and name to the data like so:?
```python
data = {
  "expires": f"{token_expire}",
  "single_use": True,
  "username": "myUsername",
  "name": "Name Surname"
}
```
I'll post an update here if i get around to testing this.

**Comment by samip5** [comment]
> Thanks for this snippet! I will try this out once i got some spare time, but it seems to do exactly what i want.
> 
> If i'm interpreting this correctly it should be possible to append a username and name to the data like so:?
> 
> ```python
> data = {
>   "expires": f"{token_expire}",
>   "single_use": True,
>   "username": "myUsername",
>   "name": "Name Surname"
> }
> ```
> 
> I'll post an update here if i get around to testing this.

Well, not really but the api spec is available at https://authentik.company/api/v3
