### ISSUE TITLE
Question: How to obtain user profile information with OAuth2

### ISSUE THREAD

**Issue by ikarstein** [goauthentik/authentik#2329]
Hi,

I use Authentik 2022.2 with ASP.NET Core .net 6.

Here is my "startup" code:

```
        services.AddAuthentication(options =>
        {
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        })
        .AddCookie(options =>
        {
            options.LoginPath = "/signin";
            options.LogoutPath = "/signout";
        })
        .AddOAuth("Authentik", options =>
        {
            options.AuthorizationEndpoint = "https://auth.example.com/application/o/authorize/";
            options.TokenEndpoint = "https://auth.example.com/application/o/token/";
            options.UserInformationEndpoint = "https://auth.example.com/application/o/userinfo/";
            options.ClientId = "1111111111111111111111111111111111111111";
            options.ClientSecret = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
            options.CallbackPath = "/signin-authentik";
            options.ClaimsIssuer = "Authentik";
            options.Scope.Add("email");
            options.Scope.Add("openid");
            options.Scope.Add("profile");
        });
```

I'm not able to figure out how to get name, email, username. I tried to add property mappings but I do not understand that feature. 

Any suggestions?

Thanks!

Regards
Ingo

**Comment by BeryJu** [comment]
With your code, they should all be accessible with the userinfo endpoint. In the provider, just select the default scopes for email, openid and profile.

Also, the issuer is not correct in your code, it should be `https://auth.example.com/application/o/<app slug>/`.

**Comment by ikarstein** [comment]
Hi @BeryJu, thank you very much! - I recently finished working on a demo with another identity provider. Now I will implement this also for Authentik and post the code here when it works. - I learned that it needs a second step when the ticket is returned from the identity provider.... I will follow up.

**Comment by ikarstein** [comment]
When I read ("GET") the user info endpoint (https://example.com/application/o/userinfo) with the created access_token in the Authorization HTTP header then I get an "Unauthorized" error response.

**Comment by BeryJu** [comment]
You need to convert the access token to a refresh token via the Token endpoint, with that token you can access the userinfo endpoint. Otherwise you can also JWT-decode the access token, which will include most things too.

**Comment by osnipezzini** [comment]
were you able to use it successfully on NET 6?
