### ISSUE TITLE
Unable to use SAML 2.0 provider with SonarQube

### ISSUE THREAD

**Issue by beniwtv** [goauthentik/authentik#2336]
**Describe the bug**
So this is a weird problem. We're successfully using Authentik with GitLab using the SAML redirect binding. We're now trying to also add SonarQube, but SonarQube claims to not receive a valid response.

The SAML login URL in SonarQube is set to 'https://sso.mycompany.com/application/saml/Sonar/sso/binding/redirect/'. This seems right, as Sonar uses a HTTP redirect SAMLRequest. If we change that to '/post/', Authentik complains that there is no request body, as Sonar only sends the HTTP GET parameter.

Weirdly though, Sonar generates the following SAMLRequest:

`<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_046c27c0-ebfc-45f5-b3e5-f30e856a98ac" Version="2.0" IssueInstant="2022-02-17T12:01:56Z" Destination="https://sso.mycompany.com/application/saml/Sonar/sso/binding/redirect/" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://sonar.mycompany.com/oauth2/callback/saml">
   <saml:Issuer>sonarqube</saml:Issuer>
   <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" AllowCreate="true" />
</samlp:AuthnRequest>`

To me, this seems to indicate Sonar wants the response as POST? Authentik however gives a redirect response. I found no concrete information if this is valid in SAML, only that mixed redirect/POST is possible.

**To Reproduce**
1. Configure SAML 2.0 provider for SonarQube in Authentik
2. Configure SAML URL in SonarQube
3. Try to log in
4. See error in SonarQube's web.log 

**Expected behavior**
Log-in succeeding

**Logs**

Sonar:

`2022.02.17 13:01:57 DEBUG web[AX8HaG3XXX][c.o.saml2.util.Util] Load XML error: Content is not allowed in prolog.
org.xml.sax.SAXParseException: Content is not allowed in prolog.
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at com.onelogin.saml2.util.Util.parseXML(Util.java:389)
        at com.onelogin.saml2.util.Util.convertStringToDocument(Util.java:336)
        at com.onelogin.saml2.util.Util.loadXML(Util.java:167)
        at com.onelogin.saml2.authn.SamlResponse.loadXmlFromBase64(SamlResponse.java:128)
        at com.onelogin.saml2.authn.SamlResponse.<init>(SamlResponse.java:109)
        at com.onelogin.saml2.Auth.processResponse(Auth.java:663)
        at com.onelogin.saml2.Auth.processResponse(Auth.java:699)
        at org.sonar.auth.saml.SamlIdentityProvider.processResponse(SamlIdentityProvider.java:149)
        at org.sonar.auth.saml.SamlIdentityProvider.callback(SamlIdentityProvider.java:119)`

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.5
 - Deployment: docker-compose

**Additional context**
Not sure if this is an Authentik bug or SonarQube bug.

**Comment by BeryJu** [comment]
I assume you imported the authentik SAML Metadata into SonarQube? The metadata specifies both post and redirect endpoints, but with no preference, so SonarQube probably chooses the first one. You can manually edit the metadata to remove the redirect entry and test with that.

**Comment by beniwtv** [comment]
There isn't really any importer, just some settings to fill out, including the IdP URL (which is set to the redirect endpoint). But that works, as far as I can see. Only the response from Authentik to SonarQube not (after logging in to Authentik).

**Comment by beniwtv** [comment]
Doh! I failed to see the option "Service Provider Binding *" in the provider settings over and over. Problem solved.

**Comment by lfdominguez** [comment]
Please @beniwtv can you tell me how you configure that SAML options, because i recevie this:

![image](https://user-images.githubusercontent.com/5604131/190861956-70673eaf-c02b-408c-8604-ba395881f015.png)

and logs from sonar:
```
[Fatal Error] :1:1: Content is not allowed in prolog.
2022.09.17 14:23:21 WARN  web[AYNL0nhcQXsYodQIAABV][o.s.s.a.AuthenticationError] Fail to callback authentication with 'saml'
java.lang.IllegalStateException: Fail to process response
	at org.sonar.auth.saml.SamlIdentityProvider.processResponse(SamlIdentityProvider.java:151)
	at org.sonar.auth.saml.SamlIdentityProvider.callback(SamlIdentityProvider.java:119)
	at org.sonar.server.authentication.OAuth2CallbackFilter.handleOAuth2Provider(OAuth2CallbackFilter.java:92)
	at org.sonar.server.authentication.OAuth2CallbackFilter.handleProvider(OAuth2CallbackFilter.java:75)
	at org.sonar.server.authentication.OAuth2CallbackFilter.doFilter(OAuth2CallbackFilter.java:68)
	......
```

**Comment by beniwtv** [comment]
@lfdominguez There is the option "Service Provider Binding" in the OAuth provider settings, that has to be changed for Sonar.

**Comment by RogerSik** [comment]
@beniwtv can you provide a full tutorial howto setup sonarqube with authentik?

**Comment by beniwtv** [comment]
@RogerSik There isn't much else to do besides what the Sonar page already documents, except making sure the binding is set correctly in Authentik to "POST" instead of "REDIRECT". 

Is there anything in particular you have issues with?

**Comment by lfdominguez** [comment]
> @RogerSik There isn't much else to do besides what the Sonar page already documents, except making sure the binding is set correctly in Authentik to "POST" instead of "REDIRECT".
> 
> Is there anything in particular you have issues with?

Already set that, my comment https://github.com/goauthentik/authentik/issues/2336#issuecomment-1250081079 has already the POST set on SonarQube config.
