### ISSUE TITLE
Background field for flows always prepended with /media when saving

### ISSUE THREAD

**Issue by ground7** [goauthentik/authentik#2337]
**Describe the bug**
When saving a flow, '/media' will be prepended to the background path when saving. On subsequent saves, it'll keep adding /media so you'll end up with '/media/media/images/background.svg' etc. This happens with terraform too.

**To Reproduce**
1. Go to a flow
2. Add a background under media
3. Save and close
4. Reopen and see extra /media

**Expected behavior**
Just use the path I put in.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.2.1
 - Deployment: helm

**Comment by BeryJu** [comment]
This is somewhat intended, when the authentik-server container does not have a mount on /media, it'll show this text field, but it is intended to be used with absolute URLs. If you've mounted single files under /media, you can use the absolute URL to reference them (https://authentik.something.tld/media/your-file.png)
