### ISSUE TITLE
Unauthenticated URL syntax query

### ISSUE THREAD

**Issue by LaRenard** [goauthentik/authentik#2393]
Hi,

Simple question and hopefully I'm just being daft but when working with a domain level forward auth provider is there a specific syntax that I should be using for the `unauthenticated url` field other than standard regex?

**Context**:
I have a domain level provider and I've added an unauthenticated url regex for a healthcheck: `https://health.domain.tld/ping/*`

I want to maintain authentication on the web portion which still works but when I try to curl against the healthcheck url (which is the same as above but with a UUID where the wildcard is) I get back a redirect for Authentik:

`<a href="https://auth.domain.tld/outpost.goauthentik.io/start">Temporary Redirect</a>.`

**Relevant infos**

- I was using Authentik "2022.1.3" but updated to "2022.2.1" in case it had a fix but sadly not.
- This configuration is setup in Kubernetes (k3s) and the version is v1.21.3+k3s1 and uses Traefik forward-auth to Authentik.
- Hardware wise its built on Raspberry Pi 4 so the arm64 iamge is being used (I tried to test gh-next but I got an error about the image compatibility with the Pi so reverted to latest stable image above).
 

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.2.1
 - Deployment: helm

Thanks
La

**Comment by BeryJu** [comment]
Could you set the log level to trace? (See https://goauthentik.io/docs/installation/configuration#authentik_log_level) With that it'll log whats being checked against what regex

**Comment by LaRenard** [comment]
Thanks for the response, 
I've enabled trace and for my curl commands I dont actually see any reference to the URL I have curled: https://pastebin.com/Mr9rv6MA

I thought it may be something to do with curl but I tried opening the same URL via Firefox and get redirected to Authentik for login: https://pastebin.com/eBdzcW0x and again I cant see any mention of the URL I'm trying to get to.

**Comment by BeryJu** [comment]
Line 101-109:

```
{
    "event": "Matching URL against allow list",
    "level": "trace",
    "logger": "authentik.outpost.proxyv2.application",
    "name": "*.domain.tld",
    "regex": "https://auth.domain.tld",
    "timestamp": "2022-02-26T18:34:07Z",
    "url": "https://auth.domain.tld"
}
```

this should match, let me look into that

**Comment by LaRenard** [comment]
awesome thank you, re-ran the curl command as it looks like my pastebin didnt have the regex but the curl also returned the same format so it is consistent across both:

```
{
    "event": "Matching URL against allow list",
    "level": "trace",
    "logger": "authentik.outpost.proxyv2.application",
    "name": "*.domain.tld",
    "regex": "https://auth.domain.tld",
    "timestamp": "2022-02-26T23:42:26Z",
    "url": "https://auth.auth.domain.tld"
}
```
