### ISSUE TITLE
ldap_bind: Insufficient access (50) after changing the provider base DN

### ISSUE THREAD

**Issue by AlphaJack** [goauthentik/authentik#2436]
**Describe the bug**
I'm unable to access to Authentik LDAP interface after having changed the base DN.  
I've already tried deleting and recreating

- dedicated group for search (LDAP group, which has Admins as parent)
- dedicated user part of the group (ldapuser)
- provider (LDAP provider)
- outpost (authentik LDAP outpost)

Also restarting and recreating these elements from a new container doesn't fix the issue.  
If I misspell the password the error is different (ldap_bind: Invalid credentials (49)), so I am certain that the error is not caused by wrong  credentials.  
Also generating an app-specific token as the user doesn't fix the issue.  

**To Reproduce**
1. Create a LDAP provider, assign it to an app, create and configure a LDAP outspot, check that it works
2. Change the base DN of the provider
3. Now I cannot login anymore with either ldapuser (part of LDAP group) or akadmin (part of Admins, the parent group)

**Expected behavior**
I can bind as I did before

**Logs**
```
Mar 05 18:03:45 hostname authentik-ldap[862546]: {"event":"Starting authentik outpost","hash":"tagged","level":"info","logger":"authentik.outpost","timestamp":"2022-03-05T17:03:45Z","version":"2022.2.1"}                                                                                                                                        
Mar 05 18:03:45 hostname authentik-ldap[862546]: {"event":"initialised memory searcher","level":"info","logger":"authentik.outpost.ldap.searcher.memory","timestamp":"2022-03-05T17:03:45Z"}
Mar 05 18:03:45 hostname authentik-ldap[862546]: {"event":"initialised direct binder","level":"info","logger":"authentik.outpost.ldap.binder.direct","timestamp":"2022-03-05T17:03:45Z"}
Mar 05 18:03:45 hostname authentik-ldap[862546]: {"event":"Update providers","level":"info","logger":"authentik.outpost.ldap","timestamp":"2022-03-05T17:03:45Z"}
Mar 05 18:08:45 hostname authentik-ldap[862546]: {"event":"Starting authentik outpost","hash":"tagged","level":"info","logger":"authentik.outpost","timestamp":"2022-03-05T17:08:45Z","version":"2022.2.1"}
Mar 05 18:08:45 hostname authentik-ldap[862546]: {"event":"initialised memory searcher","level":"info","logger":"authentik.outpost.ldap.searcher.memory","timestamp":"2022-03-05T17:08:45Z"}
Mar 05 18:08:45 hostname authentik-ldap[862546]: {"event":"initialised direct binder","level":"info","logger":"authentik.outpost.ldap.binder.direct","timestamp":"2022-03-05T17:08:45Z"}
Mar 05 18:10:04 hostname authentik-ldap[862546]: {"bindDN":"cn=ldapuser,ou=users,dc=ldap,dc=example,dc=org","client":"10.0.2.100","event":"Access denied for user","flow":"default-authentication-flow","level":"info","requestId":"b7b1eee7-98a3-4594-9270-e303936a5c4b","timestamp":"2022-03-05T17:10:04Z"}
Mar 05 18:10:04 hostname authentik-ldap[862546]: {"bindDN":"cn=ldapuser,ou=users,dc=ldap,dc=example,dc=org","client":"10.0.2.100","event":"Access denied for user","level":"info","requestId":"b7b1eee7-98a3-4594-9270-e303936a5c4b","timestamp":"2022-03-05T17:10:04Z"}
Mar 05 18:10:04 hostname authentik-ldap[862546]: {"bindDN":"cn=ldapuser,ou=users,dc=ldap,dc=example,dc=org","client":"10.0.2.100","event":"Bind request","level":"info","requestId":"b7b1eee7-98a3-4594-9270-e303936a5c4b","timestamp":"2022-03-05T17:10:04Z","took-ms":1549}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.2.0
 - Deployment: podman

**Comment by ikogan** [comment]
What were the old and new DNs? Is there a case difference?

**Comment by AlphaJack** [comment]
I turned `dc=ldapprovider,dc=example,dc=org` into `dc=ldap,dc=example,dc=org`

**Comment by ikogan** [comment]
Are you using a docker or kubernetes based outpost?

**Comment by AlphaJack** [comment]
Docker, its env file looks like this:

```ini
AUTHENTIK_DEBUG=true
AUTHENTIK_HOST=https://127.0.0.1:9443
# insecure because the host is using a self signed certificate
AUTHENTIK_INSECURE=true
AUTHENTIK_TOKEN=XXXXXX
```

The connection seems to work because by entering a wrong password I get another error

**Comment by ikogan** [comment]
Sorry, just getting back around to this. Does your `default-authentication-flow` have any stages besides `default-authentication-identification` and `default-authentication-login`?

**Comment by AlphaJack** [comment]
Switching to a new flow also used for web login seems to solve the error 50.   
If I want my services to use a dedicated user just to do LDAP searches, I need to add this user to the list of allowed ones in the application configuration page, otherwise it returns error 50.
