### ISSUE TITLE
Stage to redirect to another flow

### ISSUE THREAD

**Issue by sevmonster** [goauthentik/authentik#2438]
**Is your feature request related to a problem? Please describe.**
Now that I will be able to handle password resets, user info updates, etc. in a more sane way with authentik thanks to https://github.com/goauthentik/authentik/pull/2397, I am implementing flows for them. While testing, I noticed that a user can still get to a recovery flow even if they are already signed in. Since recovery flows are designed for unauthenticated/unidentified users to recover their account as far as I know, it would be good UX to redirect the user to the appropriate flow for authenticated users that matches the same functionality as the recovery flow. I do not believe there is currently a way to do this.

**Describe the solution you'd like**
Add a stage to redirect the user to another flow. For my use case, policies could be used to check if the user is authenticated to activate the redirect.
This proposed stage could have configuration to pass the current context, or the ability to return to the calling flow after the called flow completes. Aside from my use case, this would also allow nested, reusable flows for complicated deployments to help cut down on redundancy, though this is just a hypothetical and not related to my use case.

**Describe alternatives you've considered**
Use deny stage if the user is authenticated, or implement the simple and complex recovery flows in one flow and use policies to only show specific stages depending on authentication state. The former is not user friendly and the latter is unnecessarily complex in my opinion.

**Comment by BeryJu** [comment]
should be closed by #3192
