### ISSUE TITLE
Allow specifying alternate email attribute for email stage

### ISSUE THREAD

**Issue by sevmonster** [goauthentik/authentik#2445]
**Is your feature request related to a problem? Please describe.**
In order to allow users to complete a recovery flow involving email verification when their primary email address is itself locked behind authentik, it is required to send the password reset email to their personal/backup email address. This could be facilitated by adding allowing the target email address to be pointed to another user attribute in the email stage.

**Describe the solution you'd like**
Add email attribute field in email stage to send email to.

**Describe alternatives you've considered**
Use policy to write secondary email attribute to primary email attribute, run email verification stage, and then change it back—but this may result in their email being misconfigured if the flow does not complete.

**Comment by BeryJu** [comment]
Starting with 2022.3.1 you can use custom flows for user settings, in which you can also add custom prompts to write another email address as attribute and then use that in flows.

**Comment by sevmonster** [comment]
> another email address as attribute and then use that in flows.

That's the problem, such an attribute cannot be specified in email stages. The stage will always send email to the user's email attribute. For an example of my use-case, I want one of those new custom fields to be used as the target email address in the email stage, but in all other places I want the user's normal email attribute to be used.

**Comment by BeryJu** [comment]
oh my bad, I misunderstood

**Comment by BeryJu** [comment]
So currently to workaround this, you could set `request.context["pending_user"].email = "another email"` in a policy prior to the email stage, but I'll change it so if there is an email field in the context (not the prompt context), that will override the user's email.
