### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by deathbybandaid** [goauthentik/authentik#2460]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to see authentik be able to be load balanced for high availability.
I'd like to be able to run a secondary authentik server that synchronizes with a primary authentik server.

**Describe alternatives you've considered**
N/A

**Additional context**
I run 2 clustered proxmox nodes seperate from the rest of my proxmox cluster. This 2-node cluster is responsible for all DNS and Identity Management containers/VMs. This consists of unbound, pi-hole, freeipa, windows AD, and in the future authentik.
The services I run on these machines is setup, so one could be down, and my wife wouldn't notice any downtime for dns or auth for anything. Having High Availability for authentik would mean that I could ensure access to services.

I'm also testing out authentik on my homelab prior to possibly implementing at my workplace.

**Comment by BeryJu** [comment]
authentik by itself is stateless and you can run as many instances of the server and worker container as you need for your load. 

Because authentik's origin as a web-primary application, it uses PostgreSQL and Redis, and those can also be ran in HA, but this is outside the scope of authentik. Both the default setups with docker-compose and Kubernetes are simply basic deployments aimed at most smaller scale deployments.

**Comment by deathbybandaid** [comment]
So you're saying I could theoretically run 2 machines with postgres and redis replicated. and each machine would run the Authentik Server and Authentik Worker. This would allow me to achieve a working high availability? Maybe use syncthing for uploaded images?

**Comment by BeryJu** [comment]
Yes. You can probably get away with one worker as they are not 100% required for the normal operation, a missing worker will only cause emails and notifications to not be delivered.

For file uploads, you can just run nginx/any other webserver, remove the `/media` mount from authentik and then you can just input the URL of the file you want.

**Comment by deathbybandaid** [comment]
Thanks for this info, this project will be a fun little distraction!
