### ISSUE TITLE
Amazon business SSO

### ISSUE THREAD

**Issue by dorianim** [goauthentik/authentik#2462]
**Describe your question/**
I' trying to get authentik working as an amazon business identity provider, but I always get an error stating that assertions could not be parsed

**Relevant infos**
Amazon setup guide:
https://www.amazon.de/ab/sso/setup-guide

**Screenshots**
![image](https://user-images.githubusercontent.com/30153207/157630139-156eca8f-de71-4b10-b9b6-b7f15c297e70.png)
![image](https://user-images.githubusercontent.com/30153207/157630218-aed57e4d-2698-43cf-92d3-3c7e6eea17c6.png)
- UniqeID: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
- E-mail: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
- Full Name: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name

**Logs**
![image](https://user-images.githubusercontent.com/30153207/157630468-bb8ef4b3-2851-4491-b410-a6cb21fcdf39.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.2.1
 - Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
I havent tested this yet, but make sure to *not* enable encryption as authentik doesn't currently support encrypted SAML Assertions

**Comment by dorianim** [comment]
Ah, that's good to know, not sure if it is possible to disable it on Amazons side, tough.

**Comment by dorianim** [comment]
I'd still love so see this being resolved, not sure how I can help, though.

**Comment by BeryJu** [comment]
So I got this to work, the important steps are:

- Don't enable encrypted assertions on Amazon's side
- The SAML Signing certificate (which is required) needs to have a Subject-alternate-name set, which the default authentik certificate did not, so I generated a new one (any domain seems to work, having a SAN of `goauthentik.io` when testing on `localhost` works
- Enable the default mappings in authentik
- Create the provider with a Post binding
- Configure the mappings on amazon's side like this 
![image](https://user-images.githubusercontent.com/1932513/169716324-769e834e-c5dd-4e90-a8fc-bd83b959543c.png)
