### ISSUE TITLE
Throwing an error while search user by `uid`

### ISSUE THREAD

**Issue by Bhautik0110** [goauthentik/authentik#2480]
**Describe the bug**
When we try to get the user by `uid` (`GET /api/v3/core/users`), it throws an error `Cannot resolve keyword 'uid' into field`.
Here is below full error message.
```json
{"event": "Internal Server Error: /api/v3/core/users/", "exc_info": ["<class 'django.core.exceptions.FieldError'>", "FieldError(\"Cannot resolve keyword 'uid' into field. Choices are: ak_groups, attributes, authenticatedsession, authorizationcode, date_joined, duodevice, email, first_name, groups, id, invitation, is_active, last_login, last_name, name, notification, password, password_change_date, policybinding, refreshtoken, smsdevice, sources, staticdevice, totpdevice, user_permissions, userconsent, username, userobjectpermission, usersourceconnection, uuid, webauthndevice\")", "<traceback object at 0x7feb8c48a200>"], "level": "error", "logger": "django.request", "timestamp": 1647249464.0813763}
```

**To Reproduce**
1. Search user by `uid` using API or in the dashboard. It shows an error.

**Expected behavior**
- It should return user.

**Screenshots**
![image](https://user-images.githubusercontent.com/76986554/158142191-c0381157-06a8-465b-a92c-04ca44751232.png)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version: `2022.3.1`

**Comment by Bhautik0110** [comment]
Mentioned Issue: https://github.com/goauthentik/authentik/issues/2428
But this is search using `uuid`, We want to search using the `uid` (Which is returned in the response). How can (https://github.com/goauthentik/authentik/commit/54f170650a8216d71c1b3fe581408cef77b06d63) solution fixed that issue?

**Comment by BeryJu** [comment]
the `uid` field is not stored in the database, hence it can't be searched by. The commit above is a quick fix to prevent the search from erroring. 

eventually I plan on merging the uuid and uid fields but that is a bigger task
