### ISSUE TITLE
Error on Policy/User/Group Binding creation

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#2496]
**Describe the bug**
I can only create User Policy bindings, it looks like the User field is required. If i try to add an Policy Binding i get the error message "Invalid pk "0" - object does not exist." in the user tab

**To Reproduce**
1. Go to an Application
2. Click on Policy/User/Group Bindings
3. Click on Create Binding
4. Select a Policy
5. Click on Create

**Expected behavior**
Policy binding gets created

**Screenshots**
![image](https://user-images.githubusercontent.com/31854409/158489776-af4e7811-de38-4eeb-a182-b8903f1ffdc4.png)
![image](https://user-images.githubusercontent.com/31854409/158489786-d71d6d06-73e9-431d-a320-2dab917b2065.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.2
 - Deployment: helm

**Comment by Cookie-Monster-Coder** [comment]
+1 I get the error "Bad Request"

**Comment by masonh** [comment]
Related to #2469 (not a duplicate, though)

**Comment by benedikt-bartscher** [comment]
Thanks for your quick response & fix!

**Comment by BeryJu** [comment]
Since many people are running into this, this is fixed in the beta https://goauthentik.io/docs/installation/beta and you'll be able to upgrade easily to 2022.3.3 when it comes out in a couple days.
