### ISSUE TITLE
E-Mail Validation only works in same browser session

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#2507]
**Describe the bug**
If i open the E-Mail Validation Link from another device/browser/session i get "Request has been denied. Unknown error". However many users will try to validate E-Mail using their phone.

**To Reproduce**
1. Create an Invitation flow with E-Mail Validation
2. Create an Invitation Link
3. Fill out the Invitation from
4. Open E-Mail Validation Link from another browser/session/device

**Expected behavior**
E-Mail gets validated and Flow continues on one of the sessions.

**Screenshots**
![image](https://user-images.githubusercontent.com/31854409/158598567-12073945-fd4c-4d38-9193-4dba669ff9aa.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.2
 - Deployment: helm/k8

**Comment by rizwan95** [comment]
I suppose this could help 
https://github.com/goauthentik/authentik/issues/1801
https://github.com/goauthentik/authentik/commit/67113591049ec406d2ab60e52c9efd6fb139ec38
