### ISSUE TITLE
Inconsistent indentation in expression editor

### ISSUE THREAD

**Issue by ikogan** [goauthentik/authentik#2520]
**Describe the bug**
When typing out expressions in the web UI's expression editor, the _tab_ key inserts a tab character and the
tabstop seems to be set to a width of 4 characters. When using auto-indentation, it indents with 2 space characters.

**To Reproduce**
1. Create a new object in the web UI that has an expression editor field.
2. Create some sort of a block, for example: `request.context['prompt_data']['attributes'] = {}`
3. Position your cursor inside of the `{}`. Push enter twice to create a blank line.
4. Navigate to the blank line and push _tab_.
5. Type out a map like `'sshPublicKey': prompt_data.get('attributes.sshPublicKey'),`
6. Push enter.

Notice that the cursor is now indented 2 spaces, not the single tabstop on he previous line.

**Expected behavior**
The indentation created when pushing the _tab_ key is identical to the indentation created when
auto-indenting.

**Screenshots**
![Screenshot-20220317120507-661x102](https://user-images.githubusercontent.com/1840337/158842940-00a72431-56fe-439b-9327-de5306ea9185.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.2
 - Deployment: helm

**Comment by BeryJu** [comment]
Fixed by https://github.com/goauthentik/authentik/commit/79ad356d90b10047a422c52fb11ccb665fdad804
