### ISSUE TITLE
Additional prompt field types

### ISSUE THREAD

**Issue by ikogan** [goauthentik/authentik#2521]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Some additional field types would make the user experience nicer and allow for new possibilities, in particular:

- List with options for checkboxes, dropdown, radio buttons, or a static list (`ul` or `ol`) that looks nice.
- Long text (textarea).

**Describe alternatives you've considered**
For the static list, I used a placeholder expression to generate a comma separated list.

**Additional context**
The list options are particularly useful when you really need to limit the user's choices. For example, I would like my users to be able to choose their login shell between `/bin/zsh` and `/bin/bash` but not any arbitrary path. For SSH keys, the single line text field creates some usability challenges.

**Comment by sevmonster** [comment]
After recreating my recovery flow, I now have a need for a dropdown, combobox, or similar, so that users can pick what MFA they want to recover with. I currently use strings emitted with a policy as well.
