### ISSUE TITLE
LDAP search with direct querying causes a nil pointer dereference

### ISSUE THREAD

**Issue by sebastian-kuebeck** [goauthentik/authentik#2526]
**Describe the bug**
An LDAP search causes a nil pointer dereference resulting in LDAP Result Code 1 "Operations Error" when using
"Direct Querying" in the LDAP provider

**To Reproduce**
1. Go to 'LDAP provider
2. Change "search mode" to "Direct querying..."
3. Make Ldap Request

```
ldapsearch -x -h 127.0.0.1 -p 389 -D 'cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io' -w 'vxRRhdA7GEmZE8Crh9ZzqcN9wGgXScJ/4C8QyYDrCXoAfe7J' -b 'dc=ldap,dc=goauthentik,dc=io' '(objectClass=user)'
```

5. See error

```
# search result
search: 2
result: 1 Operations error
```

**Expected behavior**
The LDAP request was taken from the documentation and should not cause an error

**Logs**
authentik_ldap_1  | {"bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"192.168.16.1","event":"User has access","level":"info","requestId":"0c1290be-c16f-4769-a71d-b6a341b7f494","timestamp":"2022-03-18T09:01:50Z"}
authentik_ldap_1  | {"bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"192.168.16.1","event":"Allowed access to search","group":"authentik Admins","level":"info","requestId":"0c1290be-c16f-4769-a71d-b6a341b7f494","timestamp":"2022-03-18T09:01:50Z"}
authentik_ldap_1  | {"bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"192.168.16.1","event":"Bind request","level":"info","requestId":"0c1290be-c16f-4769-a71d-b6a341b7f494","timestamp":"2022-03-18T09:01:50Z","took-ms":1426}
authentik_ldap_1  | {"event":"Type can't be mapped to LDAP yet","level":"warning","timestamp":"2022-03-18T09:01:50Z","type":"map[string]interface {}"}
authentik_ldap_1  | {"baseDN":"dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"192.168.16.1","event":"Search request","filter":"(objectClass=user)","level":"info","requestId":"2cf9ea57-bde4-4062-813c-0450e9243af3","scope":"Whole Subtree","timestamp":"2022-03-18T09:01:50Z","took-ms":70}

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.2
 - Deployment: docker-compose

**Additional context**
I run authentik on Docker Desktop 4.5.0 (74594) on MacOS 12.2.0 
I am running the LDAP outpost in a seperate container and the logs provided are from that.

**Comment by BeryJu** [comment]
Do you have any custom user attributes? I can't reproduce this on a stock install, but even with the ` {"event":"Type can't be mapped to LDAP yet","level":"warning","timestamp":"2022-03-18T09:01:50Z","type":"map[string]interface {}"}` log it should still return some results
