### ISSUE TITLE
Testing a Flow renames current User Account (akadmin)

### ISSUE THREAD

**Issue by BobSilent** [goauthentik/authentik#2527]
**Describe the bug**
Testing a flow renames the current logged in user (akadmin) to the tested user

I wanted to test an [Example Flow - Enrollment with email verification](https://goauthentik.io/docs/flow/examples#enrollment-with-email-verification), mainly to check if email configuration is working.

1. Downloaded the [flow](https://goauthentik.io/assets/files/login-2fa-f96da096356fba8779ba578a5353c38d.akflow)
2. Logged in as akadmin
3. In "Flow & Stages" > "Flows" > "Import Flow" > Selected the just downloaded flow
4. Select "Actions" > "Play Button" to run the flow with Inspector
5. In first dialog select a new Username + Password
6. Then add a Name and Email
7. Click Continue, the current logged in akadmin account gets renamed

**Expected behavior**
I read that ["the flow is still executed normally. This means that for example, a user_write stage will actually write user data."](https://goauthentik.io/docs/flow/inspector).
But I would have never assumed that the current admin user gets renamed.
My expectation was I create a new Account.
After Testing I quickly deleted the "newly created account" and deleted (for sure with ignoring the warning: "currently logged in") my only admin account.

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2022.3.2]
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Actually nvm, the API used to start the flow from the view page always includes the current session
