### ISSUE TITLE
Make SENTRY_DSN configurable

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#2533]
Could we add an environment Variable to make SENTRY_DSN in authentik/root/settings.py:359 configurable?

**Comment by BeryJu** [comment]
The main reason why this is not configurable currently is that that the outposts, the web interface and the terraform provider all get their sentry config from the main server, and if that endpoints also needs to serve the DSN it would also be public. And adding authentication for that endpoint would make it almost impossible to use sentry during flows.

For the webinterface there's also additionally the fact that sentry requests are proxied via the main instance (via some Go code actually, to not take up python cpu time), which also checks that the client-side DSN matches the server-side configured one.

**Comment by BeryJu** [comment]
But looking into it, GitLab has a configurable Sentry DSN and that just exposes it everywhere so I guess that's not an issue; I just don't want to make assumptions about how people want to handle their DSNs

**Comment by benedikt-bartscher** [comment]
@BeryJu thanks! I think its pretty normal to expose sentry DSNs.

**Comment by benedikt-bartscher** [comment]
implemented by https://github.com/goauthentik/authentik/pull/4016
