### ISSUE TITLE
Can't do a LDAP search from any account "Insufficient access"

### ISSUE THREAD

**Issue by danaelg** [goauthentik/authentik#2557]
**Describe the bug**
When I'm doing an LDAP search from any user (superadmin or not, service account or not), I got a "*Insufficient access*" error. 

**To Reproduce**
1. Create a LDAP Provider (without search group)
2. Create an application that is link to that provider
3. Create a LDAP Outpost
4. Create a service account
5. Do an LDAP search with that service account :  
  ```
  ldapsearch -h XXX -p 389 -x -D "cn=test,ou=users,DC=ldap,DC=goauthentik,DC=io" -W  -b dc=ldap,dc=goauthentik,dc=io
  ```

**Expected behavior**
We should get a LDAP response

**Logs**
In the ldap outpost logs I can see the following message:
```
{"bindDN":"cn=ldap-bind,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"XXX.XXX.XXX.XXX","event":"Access denied for user","level":"info","requestId":"f1402354-c19b-4d01-9487-61d87a55aa51","timestamp":"2022-03-22T16:43:00Z"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.3
 - Deployment: docker-compose

**Additional context**
The issue appears after the upgrade from 2022.3.2   
I tried to recreate the provider and the outpost.  
I tried with different type of user (superadmin, regular, service account)

**Comment by BeryJu** [comment]
`Access denied for user` is returned when the user attempting to bind to LDAP does not have access to the application which the provider uses

**Comment by danaelg** [comment]
oh ok ! It makes sense as I've been playing with group policy...

I'm sorry for the inconvenience :worried:
