### ISSUE TITLE
Identification Stage with Password stage

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#2561]
When using an Identification Stage with integrated Password stage the password field gets focused by default on page load.
Also there is no option "Failed attempts before cancel" like in normal Password stage.

**Comment by macmoritz** [comment]
![image](https://user-images.githubusercontent.com/49832924/160897030-8e8abbc1-3059-4175-9fa1-42ef94a0d046.png)
Thats weird, both inputs have the autofocus attribute. Only the username field should have it.
[MDN Web Docs: ](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) "If applied to multiple elements the first one will receive focus." - Thats weird v2

**Comment by benedikt-bartscher** [comment]
This issue is not present with "Compatibility mode" turned on
