### ISSUE TITLE
Passwordless WebAuthn Login not working

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#2567]
**Describe the bug**
Passwordless login via WebAuthn fails with 2 different errors in qutebrowser (QtWebEngine) and chromium. WebAuthn as normal 2FA works as expected.

**To Reproduce**
1. Create a user and setup WebAuthn
2. Create a passwordless flow and assign it to the default-auth-flow
3. Try to login passwordless

**Expected behavior**
Get logged in

**Screenshots**
chromium:
![image](https://user-images.githubusercontent.com/31854409/159593262-21b63d98-5670-4f40-acbd-26393133b503.png)
qutebrowser:
![image](https://user-images.githubusercontent.com/31854409/159593304-fd287f9c-107e-4b0d-a41c-2a03c047da2d.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.3
 - Deployment: helm

**Comment by BeryJu** [comment]
Could you get check again with log level set to debug, and check for `Userless flow, getting generic webauthn challenge` in the logs

**Comment by benedikt-bartscher** [comment]
Of course, here are all the logs produced by the flow in debug mode:
```
{"event": "/if/flow/pwless/", "host": "authentik.my.domain", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 25, "remote": "***.***.***.***", "request_id": "2bd6d7dcbf024c3eba2b8579dacf7d30", "runtime": 15, "scheme": "https", "status": 200, "timestamp": "2022-03-23T21:40:36.071540", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"}
{"event": "/api/v3/root/config/", "host": "authentik.my.domain", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 25, "remote": "***.***.***.***", "request_id": "c58028be081846458710dbf2b34178f9", "runtime": 11, "scheme": "https", "status": 200, "timestamp": "2022-03-23T21:40:36.379383", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"}
{"event": "f(exec): Continuing existing plan", "flow_slug": "pwless", "host": "authentik.my.domain", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 25, "request_id": "f23b7ff28cb94b739b7f9fe72b2ccc77", "timestamp": "2022-03-23T21:40:36.726213"}
{"current_stage": "<AuthenticatorValidateStage: Stage WebAuthn>", "event": "f(exec): Current stage", "flow_slug": "pwless", "host": "authentik.my.domain", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 25, "request_id": "f23b7ff28cb94b739b7f9fe72b2ccc77", "timestamp": "2022-03-23T21:40:36.726382"}
{"event": "f(exec): Passing POST", "flow_slug": "pwless", "host": "authentik.my.domain", "level": "debug", "logger": "authentik.flows.views.executor", "pid": 25, "request_id": "f23b7ff28cb94b739b7f9fe72b2ccc77", "stage": "<AuthenticatorValidateStage: Stage WebAuthn>", "timestamp": "2022-03-23T21:40:36.726638", "view_class": "authentik.stages.authenticator_validate.stage.AuthenticatorValidateStageView"}
{"event": "/api/v3/flows/executor/pwless/?query=", "host": "authentik.my.domain", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 25, "remote": "***.***.***.***", "request_id": "f23b7ff28cb94b739b7f9fe72b2ccc77", "runtime": 16, "scheme": "https", "status": 200, "timestamp": "2022-03-23T21:40:36.731767", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"}
```

**Comment by benedikt-bartscher** [comment]
Maybe there is something wrong with my config? I could not find any documentation on pwless login so i am not sure if this is correct:

default-auth-flow
![image](https://user-images.githubusercontent.com/31854409/159802571-e7812cc2-02e0-4a8b-b03d-0ef7c1189933.png)

pwless flow
![image](https://user-images.githubusercontent.com/31854409/159802648-16001fd8-6fee-450e-8f59-1a18783b0a43.png)

webauthn stage of pwless flow:
![image](https://user-images.githubusercontent.com/31854409/159802751-f96c578d-0473-4757-933e-ffe04ff188f1.png)

**Comment by benedikt-bartscher** [comment]
i still did not get passwordless webauthn login to work. @BeryJu did i missconfigure something?

**Comment by kerkmann** [comment]
As far as I can say, it's seems like a client bug. :(
I hope that this bug will be fixed and not be forgotten. :(

**Comment by sevmonster** [comment]
I experience this as well with a YubiKey 5 NFC, under Windows 10 Chromium and Firefox, with authentik [gh-next](https://github.com/goauthentik/authentik/commit/1b6f92026549db9f4450ca0a6c25340f36cb84ff):
![image](https://user-images.githubusercontent.com/16788697/214686922-5985be7a-803e-469b-9b49-673321bcc446.png)
![image](https://user-images.githubusercontent.com/16788697/214687536-f50ef4e9-0213-42a5-8ae2-062e93649e23.png)
MFA (i.e. after identification stage) works fine under both browsers.

I should note I had to enable U2F on the YubiKey, I could not get registration, passwordless, or MFA to work with it disabled. So it appears FIDO2 is not being used?

There are also no resident WebAuthn keys, which would make sense if U2F was used, as Yubico opted to use non-resident keys for their implementation.
```shell
$ ./ykman fido credentials list
Enter your PIN:
# no authentik keys here
```

Also, I will assume that qutebrowser does not properly/fully support WebAuthn? I believe that would be a separate issue.

**Comment by regiolis** [comment]
> I experience this as well with a YubiKey 5 NFC, under Windows 10 Chromium and Firefox, with authentik [gh-next](https://github.com/goauthentik/authentik/commit/1b6f92026549db9f4450ca0a6c25340f36cb84ff): ![image](https://user-images.githubusercontent.com/16788697/214686922-5985be7a-803e-469b-9b49-673321bcc446.png) ![image](https://user-images.githubusercontent.com/16788697/214687536-f50ef4e9-0213-42a5-8ae2-062e93649e23.png) MFA (i.e. after identification stage) works fine under both browsers.
> 
> I should note I had to enable U2F on the YubiKey, I could not get registration, passwordless, or MFA to work with it disabled. So it appears FIDO2 is not being used?
> 
> There are also no resident WebAuthn keys, which would make sense if U2F was used, as Yubico opted to use non-resident keys for their implementation.
> 
> ```shell
> $ ./ykman fido credentials list
> Enter your PIN:
> # no authentik keys here
> ```
> 
> Also, I will assume that qutebrowser does not properly/fully support WebAuthn? I believe that would be a separate issue.

Did you resolved your issue ?
I'm still having trouble logging in with Yubico 5 NFC (webauthn)

**Comment by benedikt-bartscher** [comment]
IIRC for me it started working after reregistering my yubikeys with latest chrome and authentik

**Comment by regiolis** [comment]
Same here
