### ISSUE TITLE
Access token validity does not apply

### ISSUE THREAD

**Issue by patrick-dedication** [goauthentik/authentik#2581]
Our access tokens have the same validity as set in 'Token validity'.
Changing 'Access token validity' to a smaller or larger (just for sake of trying) value has no effect.
What we would like to accomplish is to have access tokens valid for say 15min and the refresh tokens for 1hour.
Having the access token validity bound to the refresh token validity wouldn't be an issue per se, although from time to time Authentik does not accept the refresh token (I guess because it is no longer valid).
The returned error is the following:
```
error: "invalid_grant"
error_description: "The provided authorization grant or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client"
```

**Comment by Dani723** [comment]
I have the same issue. The "exp" field in the Access Token JWT seems to take the value of the "Token validity" and not the "Access Token validity" configuration.
Not sure if I'm missing something or if it is a bug...

**Comment by Zibbp** [comment]
Same issue here. Access token JWT field "exp" is always being set to the refresh token validity.

**Comment by pawel-pacewicz-altium** [comment]
+1 here, similar issue. Reopen?
