### ISSUE TITLE
Redirect URIs/Origins does not accept all paths on a domain

### ISSUE THREAD

**Issue by patrick-dedication** [goauthentik/authentik#2582]
**Describe the bug**
Redirect URIs/Origins does not accept all paths on a domain (i.e. specifying my.domain/*)

**Expected behavior**
Specifying my.domain/* allows a redirect to my.domain/page1

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.1

**Additional context**
Auth0 allows all routes on a domain when specifying my.domain (without /*)

**Comment by BeryJu** [comment]
This is now possible with 2022.5, where you can use any regular expression to validate redirect_uris: https://goauthentik.io/docs/releases/2022.5
