### ISSUE TITLE
Forward auth, auto generated setup code incorrect

### ISSUE THREAD

**Issue by NotShocked** [goauthentik/authentik#2585]
**Describe the bug**
May be under more things as well but this is all I tested.

When using the Proxy Provider, Forward Auth (single), the auto generated Setup section below for Nginx (Proxy manager) does not apply the Outposts scheme or port. Making the generated code not function.

**To Reproduce**
Setup a Forward Auth for a Nginx Proxy manager hosted service and attempt to copy and past in the setup code. It will not function.

**Expected behavior**
Would expect the code to know the port and scheme and have it entered.

**Logs**
No logs as this can just be seen in the UI

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.3
 - Deployment: portainer 

This section of the code is what I am talking about

```
# all requests to /outpost.goauthentik.io must be accessible without authentication
location /outpost.goauthentik.io {
    proxy_pass          192.168.1.1/outpost.goauthentik.io;
    # ensure the host of this vserver matches your external URL you've configured
    # in authentik
    proxy_set_header    Host $host;
    proxy_set_header    X-Original-URL $scheme://$http_host$request_uri;
    add_header          Set-Cookie $auth_cookie;
    auth_request_set    $auth_cookie $upstream_http_set_cookie;
}

```
The "proxy_pass" line should be https://192.168.1.1:9443/outpost.goauthentik.io;
The https and the 9443 are both not generated.

**Comment by e36Alex** [comment]
Hello,

same point at nginx standalone.
