### ISSUE TITLE
Add yubico otp support

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#2590]
Sadly Webauthn does not work with some browsers and everyone hates to type OTP Codes. It would be awesome to add Yubico OTP Support as an alternative 2FA Provider. There is a python package which implements Yubico OTP: https://pypi.org/project/yubico-client/

**Comment by xanderjjj** [comment]
I don't think this is a duplicate of #2251
This is specifically requesting the yubico-otp protocol which would be beneficial over FIDO options as it is clientless.
Currently there is limited support for USB passthrough in virtual desktop environments (especially in Linux), being able to use a clientless option through to a VDI would enable security key 2fa to more users

**Comment by benedikt-bartscher** [comment]
@xanderjjj thanks for pointing that you, you are right. This is not a duplicate of #2251 

@BeryJu could you please reopen this?
