### ISSUE TITLE
One resource server multiple OAuth grants (authorization_code + pkce and client_credentials)

### ISSUE THREAD

**Issue by patrick-dedication** [goauthentik/authentik#2638]
**Describe your question/**
We have an API which we consume with a SPA (using authorization_code).
The API is also consumed by our customers in their backend systems.
We would like to provide our customers with a service account.
1. Is it possible to have a provider which supports both grants?
1. Are there any other suggestions to authenticate/authorize two systems to one resource server?

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.3
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
If the SPA is using an implicit flow, then the provider should be configured for `Public` mode (where no client secret is set), but the client secret is required for client_credentials 

Is there any specific reason to not have two providers/applications?

**Comment by BeryJu** [comment]
> 1. If I get it correct this would break the isolation. A token issued using any provider on that Authentik instance would allow access to all applications who check for the issuer uri of that Authentik instance. At the moment we use one Authentik instance for our dev and test stage, so a Token issued for the dev stage would also work for the test stage.

Indeed it would have the same issuer, but you can create a custom Scope mapping to return additional data, which will be included in the JWT and can be verified

> 2. When providing the jwks endpoint to the resource server we would have to pick from one of the two providers. Is it guaranteed that they return a compatible result?

if they both have the same signing key selected, then the response will be identical

**Comment by BeryJu** [comment]
To amend the response above and give somewhat of a better solution:
This is not directly possible with the current provider architecture, however with multiple applications and provider, and selecting the same signing key in both, the JWT will only differ in issuer, which should still be usable in most cases.
