### ISSUE TITLE
User claims in access_token not included without enabling 'Include claims in id_token'

### ISSUE THREAD

**Issue by patrick-dedication** [goauthentik/authentik#2640]
**Describe the bug**
We have an application with a service account which is not concerned about open_id, only OAuth.
We have a custom claim which we populate through a property mapping.
The claim is added to the access_token only when we enable `Include claims in id_token` for the provider.

**To Reproduce**
1. Create a property mapping
```
return {
  "https://custom/claim": user.attributes.get("custom_claim", ""),
}
```
2. Create a Provider
  - under Scopes enable your property mapping
  - disable `Include claims in id_token`
3. Create an Application
4. Get an access_token including the scope associated with the custom mapping -> the custom claim is missing

**Expected behavior**
The access_token should contain the claim when the scope associated with the mapping is included in the authorize request.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.3
 - Deployment: docker-compose

**Comment by scheibling** [comment]
The access token is for retrieving information from the userinfo endpoint, is the custom claim not available there?

Or do you mean the custom claim should be available when you receive the access token from the authorize endpoint?

The access token itself wouldn't contain any of this information, that would instead be the id_token. Could you elaborate a bit on which parameter in which step of the authentication process doesn't contain the claim as expected?

**Comment by patrick-dedication** [comment]
The access token contains the custom claim, but only when `Include claims in id_token` is enabled.
We need the claim in the access token as the resource server uses this claim for tenant assignment.

**Comment by scheibling** [comment]
Let's start this way, could you provide an overview of the OIDC-authentication flow you're using?
e.g. response_type, response_mode, scope and what the requests/responses look like along the way.

A good tool for this iss SAML-tracer, exists for both Chrome and Firefox.
