### ISSUE TITLE
Running into issues with DUO 2FA

### ISSUE THREAD

**Issue by RoboMagus** [goauthentik/authentik#2666]
**Describe your question**
I'm trying to link an existing authentik user to an existing DUO account.
I've walked through the steps of [the DUO stage docs](https://goauthentik.io/docs/flow/stages/authenticator_duo/). `import_devices` shows succesfull. However, further interaction always results in problems.

**Logs**
I'm a bit reluctant in sharing any logs here as its full of privacy sensitive information...
If there's specific stuff I need to share for additional information, I'll try to sort that out.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.3
 - Deployment: docker-compose

**Additional context**
Immediately after a succesfull enrolment using `import_devices`, I check the enrolment_status of the Authentik API and I get a 405.
When trying to use the DUO 2FA during authorization flow I just get `Whoops! Something went wrong! Please try again later.` much like described in #1371.

Logging at that point in time contains `{"event": "RuntimeError('Received 400 Invalid request parameters (user_id)')" `.

The recent activity under the Duo Dashboard does not show any signs of Authentik interacting with the DUO api.

Any insights in what might be going wrong here?

**Comment by BeryJu** [comment]
Hi, the enrollment_status API can only be used during a flow. I'll add some error handling to make sure this at least doesn't cause any errors.

The actual import does not talk to Duo, it just creates the device in authentik as-is. You should be able to login as the user you're assigning the device to, or impersonate them, and the device should show up in the user interface

**Comment by RoboMagus** [comment]
I still have no clue what was wrong in my setup but after nuking the entire config, updating Authentik to the latest release and starting fresh the Duo integration works like a charm!

Quite strange, but I'm happy its working now.
