### ISSUE TITLE
WebAuthn enrollment failed

### ISSUE THREAD

**Issue by CS-5** [goauthentik/authentik#2672]
**Describe the bug**
Tried to set up Webauthn with a Yubikey. Resulted in a `Registration Failed. Error: Authenticator did not provide a credential public key`. This could very well be an error with how my Yubikey is configured, but I did not want to go down that rabbit hole yet since Webauthn works fine elsewhere (GitHub and Cloudflare, for example).

Note: No events (other than the initial log in) showing up in the Event Log.

**To Reproduce**
1. Sign in to account
2. Go to user settings > MFA Devices
3. Enroll > Security key authenticator 
4. Insert Yubikey with Webauthn configured (works on other sites)
5. Enter Yubikey pin and press button
6. Error

**Expected behavior**
Should enroll the Yubikey as a Webauthn device.

**Screenshots**
![error](https://user-images.githubusercontent.com/9035898/161756034-7f58b7ac-7bb1-4fdb-bc9e-94e45e7cf6e1.png)

**Logs**
``` 
{"event": "registration failed", "exc": "InvalidRegistrationResponse('Authenticator did not provide a credential public key')", "host": "my.domain.com", "level": "warning", "logger": "authentik.stages.authenticator_webauthn.stage", "pid": 138321, "request_id": "7a81a641cffa47a49efb4bb01f228286", "timestamp": "2022-04-05T12:32:49.107114"}
{"event": "/api/v3/flows/executor/default-authenticator-webauthn-setup/?query=next%3D%252Fif%252Fuser%252F%2523%252Fsettings%253Bpage-mfa", "host": "my.domain.com", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 138321, "remote": "123.123.123.123", "request_id": "7a81a641cffa47a49efb4bb01f228286", "runtime": 41, "scheme": "https", "status": 200, "timestamp": "2022-04-05T12:32:49.115910", "user": "cs-5", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.2
 - Deployment: docker-compose

**Comment by dugite-code** [comment]
@CS-5 I had this issue as well. there was another issue opened (can't find it atm) that pointed out that if you use a chomium based browser rather than firefox you should be able to perform the enrollment. After the initial enrollment you can use firefox again.

**Comment by CS-5** [comment]
@dugite-code Interesting, thanks! Looks like this is a bug with FF version 98 (and perhaps lower). I just tried on two different systems with version 99 and it works fine.
