### ISSUE TITLE
Application Policies stopped working

### ISSUE THREAD

**Issue by julianooi** [goauthentik/authentik#2709]
**Describe the bug**
Policy checking for user email not working. When using test in application to check for access, getting the following error
"Object of type City is not JSON serializable"

```
return regex_match(request.user.email, '(.*)@example.com$')
```

The bug results in applications not being visible to users who pass the policy.

**To Reproduce**
1. Create an application
2. Create a policy checking for user email
3. Go to application
4. Check application access
5. Select a user that passes the policy
6. Get error

**Expected behavior**
Users who pass the policy are able to access the application.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.3.3
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Interesting, seems related to GeoIP, could you post the full stacktrace?

**Comment by julianooi** [comment]
Sorry, how do I go about getting the full stack trace? 

Not much info in the server logs.

**Comment by julianooi** [comment]
Issue was resolved by recreating the policy.

But stack trace in case it could be a separate issue.

`Context
{
    "geo": {
        "lat": 1.333,
        "city": "Example",
        "long": 100.233,
        "country": "MY",
        "continent": "AS"
    },
    "message": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/asgiref/sync.py\", line 451, in thread_handler\n    raise exc_info[1]\n  File \"/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py\", line 284, in _get_response_async\n    response = await sync_to_async(\n  File \"/usr/local/lib/python3.10/site-packages/asgiref/sync.py\", line 414, in __call__\n    ret = await asyncio.wait_for(future, timeout=None)\n  File \"/usr/local/lib/python3.10/asyncio/tasks.py\", line 408, in wait_for\n    return await fut\n  File \"/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py\", line 22, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/asgiref/sync.py\", line 455, in thread_handler\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/django/template/response.py\", line 114, in render\n    self.content = self.rendered_content\n  File \"/usr/local/lib/python3.10/site-packages/rest_framework/response.py\", line 70, in rendered_content\n    ret = renderer.render(self.data, accepted_media_type, context)\n  File \"/usr/local/lib/python3.10/site-packages/rest_framework/renderers.py\", line 100, in render\n    ret = json.dumps(\n  File \"/usr/local/lib/python3.10/site-packages/rest_framework/utils/json.py\", line 25, in dumps\n    return json.dumps(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/json/__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n  File \"/usr/local/lib/python3.10/json/encoder.py\", line 199, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/local/lib/python3.10/json/encoder.py\", line 257, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/local/lib/python3.10/site-packages/rest_framework/utils/encoders.py\", line 67, in default\n    return super().default(obj)\n  File \"/usr/local/lib/python3.10/json/encoder.py\", line 179, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nObject of type City is not JSON serializable",
    "http_request": {
        "args": {
            "for_user": "1"
        },
        "path": "/api/v3/core/applications/example/check_access/",
        "method": "GET"
    }
}`

**Comment by BeryJu** [comment]
hey @julianooi could you post the policy you're testing? I havent been able to reproduce this error

**Comment by julianooi** [comment]
I was using the following expression policy. It could just be a bad state or something, cause recreating the policy with the same code seems to fix the issue.

Thank you

`return regex_match(request.user.email, '(.*)@example.com$')`
