### ISSUE TITLE
Go proxy does not respect schemes in config values

### ISSUE THREAD

**Issue by BeryJu** [goauthentik/authentik#2719]
The python config loader accepts both `file://` to load values from files, and `env://` to load from environment variables.

The go config loader needs to work the same

**Comment by grehund** [comment]
My understanding is that we can not use Docker Secrets until this is fixed, correct? 
Is there any way to still maintain secrets when running Authentik on Docker? 
Any idea when this will be resolved? 
I assume the best solution is to use Kubernetes instead, correct?
