### ISSUE TITLE
Truncate or delete some entry of `authentik_events_event`.

### ISSUE THREAD

**Issue by Bhautik0110** [goauthentik/authentik#2723]
### Changes
Currently, I have `71,686` records in `authentik_events_event`, Is that safe to truncate `authentik_events_event` table? I suggest we have cron job or function that remove old records from `authentik_events_event` at specific time.

Thanks.

**Comment by BeryJu** [comment]
In the tenant settings you can configure the default expiry for events, keep in mind that that will only apply to new events.

To cleanup existing elements, you can just truncate the table, there are no foreign keys to anything in the event table

**Comment by Bhautik0110** [comment]
Thanks @BeryJu :smile:

**Comment by jacksgt** [comment]
Hi, I also just came across this issue after my `authentik_events_event` table had grown to 105MB.

> In the tenant settings you can configure the default expiry for events, keep in mind that that will only apply to new events.

I think this should be mentioned somewhere in the docs (and the effect it has on the database / table size).

> To cleanup existing elements, you can just truncate the table, there are no foreign keys to anything in the event table

It seems that in the meantime some foreign keys were introduced ...

```
truncate table "authentik_events_event";
ERROR:  cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "authentik_events_notification" references "authentik_events_event".
```

I managed to clean the table with:

```
truncate table "authentik_events_event" cascade;
```

(it's probably also a good idea to run `VACUUM FULL;` afterwards on the DB).
