### ISSUE TITLE
FR: Support for response_mode: form_post

### ISSUE THREAD

**Issue by scheibling** [goauthentik/authentik#2748]
**Is your feature request related to a problem? Please describe.**
We have a client application that is meant to use Azure as an IDP, and I've managed to customize most of the authentik flow to be able to use Authentik as a provider. The last part of this is that the OpenID Connect/Oauth2-provider currently doesn't support response_mode: form_post, which would be needed for this compatibility.

**Describe the solution you'd like**
Modify the OpenID Connect/Oauth2 provider for use with the response mode form_post

**Additional context**
I think compatibility with applications that are made for Azure authentication would enhance the usability aspect of Authentik a great deal. I'll look into getting a PR together later this week/beginning of next week when I have some spare time, just thought I'd post here as well in case anyone else is interested/working on it/has a solution already.

**Comment by scheibling** [comment]
After looking at it for a bit, would maybe @BeryJu be able to provide a (very brief) representation of how the OIDC-flow, mostly the latter stages moves through the code? 

My thinking at the moment is I'd have to amend the ResponseMode in providers/oauth2/models.py with form_post, modifying OauthFulfillmentStage providers/oauth2/views/authorize.py to check for the response_mode and create a separate view for the "post"-redirect with an auto-submitting form for posting the data back to the RP.

**Comment by BeryJu** [comment]
I think I had a stash somewhere where I basically did that, but you're essentially correct, continue to check the `response_mode` like currently to make sure only valid options allowed.

For the auto-submitting form you can look at the SAML provider which already does this, see https://github.com/goauthentik/authentik/blob/master/authentik/providers/saml/views/flows.py#L86

**Comment by scheibling** [comment]
Fantastic, thanks! I'll try to pull together a PR for this end of this or next week.

**Comment by BeryJu** [comment]
Hi, feel free to already create a PR for this, I think that would be a better context to discuss the actual implementation.

For the redirect part, you can pretty much just copy the SAML part as the OAuth Authorization View is also used within a flow, and the frontend will automatically deal with the rest.

For the other question above, I remember there being some code that deals with the mapping from the nested ?query to make it directly accessible, but I'll need to have another look

**Comment by scheibling** [comment]
The first comment is less relevant now, I've commented out that bit since I moved the responsemode parsing a bit earlier in the process. 

I'll send a pull request later tonight or tomorrow morning!
