### ISSUE TITLE
Connect Nextcloud via LDAP Outpost

### ISSUE THREAD

**Issue by martin-nohava** [goauthentik/authentik#2783]
**Describe your question**
Hi. I would like to connect **Nextcloud** instance to Authentik **via LDAP** Outpost, but I can't figure out any functional configuration. Every time I try to login to Nextcloud with user defined in Authentik I get this error message in Nextcloud:
```
# Message after login attempt with 'martin' username. 
Warning | user_ldap | LDAP Login: Could not get user object for DN cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io. Maybe the LDAP entry has no set display name attribute?
```
Also couldn't find any documentation on this. For Nextcloud only SAML documentation is written as of now.

According to Nextcloud LDAP integration, it seams that Nextcloud can communicate with LDAP Outpost (*screenshot 1*), correctly obtain number of users (*screenshot 2*) and groups (*screenshot 4*), confirm existence of specific users (*screenshot 3*) and so on, but fails to use this information for user login.

Has anyone been able to achieve this type of connection between Authentik and Nextcloud? 
Thank you.

**Relevant infos**
- Nextcloud version: 23.0.3 Hub II
- Deployment: docker-compose

**Screenshots**
![1](https://user-images.githubusercontent.com/57003339/165505118-cc890aed-23f9-493c-aeac-42377f4d27d0.png)
![2](https://user-images.githubusercontent.com/57003339/165505149-58bdf233-3c21-48a8-8933-d6c911f3e54a.png)
![3](https://user-images.githubusercontent.com/57003339/165505167-c80418c2-71fc-410d-97bf-c8a770452ae0.png)
![4](https://user-images.githubusercontent.com/57003339/165505184-de790291-55a5-43bc-8bf5-80bf3c36f66d.png)

**Logs**
Output of docker-compose logs for LDAP Outpost
```
{"baseDN":"ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(&(|(objectclass=user))(displayname=*))","level":"info","requestId":"66ed1073-a605-436d-9b95-f5ebd89eab37","scope":"Whole Subtree","timestamp":"2022-04-27T10:57:35Z","took-ms":0}
{"bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"User has access","level":"info","requestId":"bc6b096c-3f7e-45d0-8f48-07eaf64bf3d6","timestamp":"2022-04-27T10:57:54Z"}
{"bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Allowed access to search","group":"authentik Admins","level":"info","requestId":"bc6b096c-3f7e-45d0-8f48-07eaf64bf3d6","timestamp":"2022-04-27T10:57:54Z"}
{"bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Bind request","level":"info","requestId":"bc6b096c-3f7e-45d0-8f48-07eaf64bf3d6","timestamp":"2022-04-27T10:57:54Z","took-ms":10615}
{"baseDN":"ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(&(|(objectclass=user))(|(cn=martin)))","level":"info","requestId":"c0f4454f-941f-41cb-9096-f7498fee1853","scope":"Whole Subtree","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"ffd34f56-ff83-44ef-b24b-e4b5d1ddafe3","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"d4c49213-275b-4eb5-ae2f-2c394c38bcb3","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"e2d2b213-c30b-41f4-ab17-6a36029a7ec4","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"f8d8377f-ce5d-43dc-af87-4abf983151a8","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"78cf550e-4d83-4b37-8c0e-3b9fded262d9","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"0e7e9648-e340-4fef-aa8c-9bcdaab7dc6a","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"21a5d1b7-a09f-464e-9354-cb510e330e80","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"a8919af7-f53e-40ba-a18a-bccd91dc9093","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"11d9715b-c7f5-4335-a03e-a3adaf69c681","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
{"baseDN":"cn=martin,ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=akadmin,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.19.0.10","event":"Search request","filter":"(objectClass=*)","level":"info","requestId":"8d9dbe5b-1e30-4122-ab34-30fed79ea3c3","scope":"Base Object","timestamp":"2022-04-27T10:57:56Z","took-ms":0}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.4.1
 - Deployment: docker-compose

**Comment by m0rtis0** [comment]
Can confirm this on 2022.7.3. Any Updates on this @BeryJu? Is there some way we can help resolve this?

**Comment by m0rtis0** [comment]
@martin-nohava Fixed with setting:
Advanced -> Displayname Attribute: name
Expert -> Override UUID Detection -> User: uid
Expert -> Clear Username - Ldap Mapping 
WARNING: THIS WILL RESET ALL LDAP USERS (Files and everything else)

**Comment by Waboath** [comment]
Hello, i have the same problem @martin-nohava.
I do not understand the solution @your-sudden-death.
In my authentik i haven't "name" as attribute?
In jellyfin, gitea and jenkins is works. So i don't unterstand the different.

**Comment by a-gerhard** [comment]
This may be connected to #5394

**Comment by diegobrandao** [comment]
I have the same issue, I tried @your-sudden-death solution, but it did not work.
Any news about this problem

**Comment by rissson** [comment]
I'll screen my settings here if it helps.

<img width="822" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/1f9b828c-bb9c-4cab-8dd3-aee94e9b4f88">
<img width="835" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/0055df5c-67be-4872-923d-5be77f23dfaa">
<img width="1236" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/4f8dacc7-5e8b-4334-b3ec-3b15f21255b2">
<img width="1236" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/282148d5-3df3-4c63-9525-21777b935c43">
<img width="1236" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/90564217-192a-4bb3-8e7b-071e7a294fba">
<img width="1236" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/00876b84-a5f8-4cc0-a433-cf7060028357">
<img width="1236" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/bb274d03-faf1-4a49-98a4-a2053e9e12be">
<img width="1236" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/a4d8ec34-4ef8-49d6-92ec-73ce65a306b3">
<img width="1236" alt="image" src="https://github.com/goauthentik/authentik/assets/18313093/9eca981d-f343-44dd-81fc-cf7d1630a7a8">

`mailPrimaryAddress` should be `mail` on a standard authentik install. `nextcloudQuota` is an attribute I add on my users, leave blank if you don't want it. Also, all filters are written by hand, without using nextcloud configuration dialogs.

Closing as it's not an authentik issue.
