### ISSUE TITLE
Integrated Windows Authentication / Kerberos Login

### ISSUE THREAD

**Issue by fl0eb** [goauthentik/authentik#2791]
**Is your feature request related to a problem? Please describe.**
When logging in through Authentik Users need to provide their username and password.

**Describe the solution you'd like**
Implementing Kerberos support in Authentik would enable a seamless login without the need to enter username and password on domain joined computers. 

**Describe alternatives you've considered**
Active Directory Federation Services
Azure AD
PingFederate

**Additional context**
Naturally, Authentik would need to be connected to an Active Directory, Samba or any other directory containing a KDC
Additionally, the DNS of Authentik needs to be registered as a Service Principal Name in the directory.

**Comment by scheibling** [comment]
Doesn't Integrated Windows Authentication still require a Windows-based IIS-server joined to the domain to act as an intermediary for Linux-based systems?

**Comment by flow555** [comment]
I'm not sure about the technical details but PingFederate does support Kerberos authentication and can run on RHEL.
https://docs.pingidentity.com/bundle/pingfederate-102/page/ykt1564003023206.html

**Comment by iYUYUE** [comment]
Will it be possible to do something like the FreeIPA Web UI (/ipa/ui/)? Based on my very limited experience with it, login with Kerberos seems to be tried silently and only refresh the page with a logged-in status on success. https://github.com/freeipa/freeipa/blob/master/install/ui/src/freeipa/widgets/LoginScreen.js#L227-L252

**Comment by CartCaved** [comment]
Hi!

I just deployed Keycloak with Integrated Windows Authentication and had to dive into this topic so I thought I'd share some of what I learned.

First, Integrated Windows Authentication can be done via NTLM or Kerberos, where Kerberos is the preferred approach for Microsoft. The actual authentication is negotiated via something called SPNEGO (Simple and Protected GSSAPI Negotiation Mechanism).

There are [two things](https://www.ibm.com/docs/en/sva/9.0.6?topic=concepts-spnego-protocol-kerberos-authentication) that are needed on the Windows Active Directory side to enable "Integrated Windows Authentication" through Kerberos:
1. Create a [user account in AD](https://social.technet.microsoft.com/wiki/contents/articles/36470.active-directory-using-kerberos-keytabs-to-integrate-non-windows-systems.aspx) that will contain the SPN (Service Principal Name) for the service that needs to use the authentication. It is basically a user account with a pointer back to the DNS name of the service, which allows AD to create a kerberos ticket that the service can use.
2. Generate a ["keytab" file](https://www.ibm.com/docs/en/tfim/6.2.1?topic=authentication-configuring-active-directory-use-spnego) for the service to be able to process the kerberos ticket when it comes.

The keytab file is copied over to the server of the service (authentik). There would need to be an SPNEGO library to use the keytab file to consume requests and consume the kerberos ticket. There is no need to run IIS for this, keycloak, websphere etc. can do it. Microsoft has this [blog-post ](https://social.technet.microsoft.com/wiki/contents/articles/36470.active-directory-using-kerberos-keytabs-to-integrate-non-windows-systems.aspx) about it.

There is also no need for the service to display the HTTP-basic style popup. From [Keycloak](https://www.keycloak.org/docs/latest/server_admin/index.html#_kerberos):

> Keycloak renders the HTML login screen with status 401 and HTTP header WWW-Authenticate: Negotiate
> 
> If the browser has a Kerberos ticket from desktop login, the browser transfers the desktop sign-on information to Keycloak in header Authorization: Negotiate 'spnego-token'. Otherwise, it displays the standard login screen, and the user enters the login credentials.


So the library would be able to tell if there is a ticket and if not, decide to force the issue with a HTTP-style pop-up but can also just redirect to the regular login page (or another flow step as needed).

Don't know if any of this helps, but thought to share. If Kerberos is already working, maybe it's not too far to get Integrated Windows Authentication to work as well. I know that it makes the user experience really convenient.

**Comment by KamistixX** [comment]
Looking forward to seeing this implemented to authenticate seamlessly in an Microsoft Active Directory-based intranet.

**Comment by rogerlawrence79** [comment]
Couldn't and forgive me for my ignorance... Samba provide some level of Windows based authentication.  https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller.  I love where this thread is going and would certainly be useful if exposed in Authentik in some way.

**Comment by CartCaved** [comment]
Hi all -

It seems this is already on the roadmap, as Desktop authentication (planned), for the non-free version of Authentik ([https://goauthentik.io/pricing/](https://goauthentik.io/pricing/)). If that's the cases, I wouldn't expect it to come to the Open Source version very soon.

Open Source Authentik should be able to use another authentication system as an IDP providing SAML or OAuth, such as Keycloak, ADFS, etc. That would require two systems, but all the logic and authorization can be managed through Authentik.

**Comment by scheibling** [comment]
Windows Integrated Login and Desktop Authentication are two separate features as far as I can tell. This thread is more about the integrated/automatic login you get when accessing a website from a computer on an AD-Domain, while the desktop auth seems to be described more as a 2fa/mfa solution for Windows login if I understand that correctly

**Comment by CartCaved** [comment]
I'll guess we'll see down the line.

**Comment by BeGj** [comment]
As long as Kerberos sso is not supported in Autentik we are not able to move from keycloak.

**Comment by amrelsaqqa-vxlabs** [comment]
I am just voting for this feature to be available on the free/open source version of Authentik, hopefully this helps getting this feature among most-wanted ones..

**Comment by bbrendon** [comment]
Hi @amrelsaqqa-vxlabs . You vote by clicking the thumbs up on the first comment. Writing text here to vote is considered spam.

**Comment by BeryJu** [comment]
Kerberos support as a provider is in progress under #6391 

Additionally we're also planning to support this with a Windows Credential Provider in the future

**Comment by PentaPaetzold** [comment]
We are using FreeIPA as AD/KDC and Linux SSSD-freeipa enabled Desktops. klist will show kerberos Tickets after desktop login. The FreeIPA- WebUI is able to do logon without asking for useraccount.

Would that pull https://github.com/goauthentik/authentik/issues/2791#issuecomment-2025763475 enable Authentik to not have the need to re-authenticate in WebUI?

Or is this already possible and that pull is about Authentik beeing able to act as kerberos- kdc?

Would this pull only work with Windows- Clients, or also with FreeIPA and Linux- Desktops?

I now need to decide if i can go with authentik, or if i need to get keycloak running. Would Authentik be possible for me in the moment?

**Comment by Cybernisk** [comment]
I've noticed that 2024.10.0-rc1 has 
>Kerberos source: authentik can now integrate with existing Kerberos environments by allowing users to log in with their Kerberos credentials, SPNEGO or syncing users into authentik.

How is this connected with current ticket?

**Comment by rissson** [comment]
Yeah this should resolve the initial request. #10815

**Comment by PentaPaetzold** [comment]
@rissson  This is great, thank you so much!
Didn't get it working on the first try. Any hidden docs available we can use? Will open a new ticket, if i don't get it working with freeipa/sssd-kerberos

**Comment by rissson** [comment]
Yeah, feel free to open an issue

**Comment by fl0eb** [comment]
@rissson Thanks for implementing this feature!
After a bit of trial and error I managed to get it configured with my Samba (Heimdal) instance.

**Comment by rissson** [comment]
Glad to hear! Let us know if you have any feedback

**Comment by PentaPaetzold** [comment]
@fl0eb Can you tell me, if the useraccounts are synced with kerberos or did you use samba to sync them?

For me, it looks like on freeipa the sync of kerberos is using kadmin- interface, which is not implemented in freeipa, so sync is failing.
When you managed samba- sync to work with kerberos, i wonder if i could also use ldap- sync and kerberos (ldap-sync is working on another version of authentik already).

**Comment by fl0eb** [comment]
@PentaPaetzold I'm using the LDAP Source to sync them
I'm not sure if Samba (with Heimdal) has the administration system integrated, which Authentik needs to sync users.
There is also the possibility to run Samba with MIT Kerberos, maybe the administration system is implemented there.

Since you can map Kerberos Connector to the LDAP synched users, SPNEGO is sufficient for me.

**Comment by fl0eb** [comment]
@PentaPaetzold Don't forget to add the Kerberos Source into your authentication stage
Flows and Stages > Stages > default-authentication-identification > Source settings

Once added you should see the Kerberos Icon under the Username field on the login page.
Clicking on that icon will trigger the Kerberos authentication.

You can see if Kerberos authentication is initiated by opening your browsers dev tools and check for a request like
https://authentik.domain.com/source/kerberos/yourKerberosSourceSlug
which will always return "401 Unauthorized" at first containing the header "www-authenticate: Negotiate"
This means SPNEGO is initiated.

From there on C:\Windows\System32\klist.exe and the Authentik logs should help you drilling down further issues.

**Comment by PentaPaetzold** [comment]
@fl0eb  Thank you very much for your help - you got it! Now it works: it was missing the default-authentication-identification setting while this was not documented (the docs are about the password- stage)

@rissson Thank you. May you add some Doc-related paragraphs to save a lot of time for the users not that familar with kerberos like me.

My struggles were:
1. For FreeIPA- Systems kadmin sync is not working, while all users (even the admin) are not allowed to do anything with the kadmin- interface. Even if they use MIT kerberos as Backend there. Took me a while to understand.

So what you need to do to get SPNEGO working with FreeIPA:
```
ipa host-add authentik.domain.com
ipa service-add HTTP/authentik.domain.com
# (Add admin to be allowed to create/fetch the keytab of HTTP/authentik.domain.com in FreeIPA)
kinit admin
# Create Keytab for service:
ipa-getkeytab -s ipa.domain.com -p HTTP/authentik.domain.com -k /tmp/authentik.keytab
# Get created Keytab without changing it:
# ipa-getkeytab -r -s ipa.domain.com -p HTTP/authentik.domain.com -k /tmp/authentik.keytab
cat /tmp/authentik.keytab | base64
rm /tmp/authentik.keytab
```
Maybe add this to https://docs.goauthentik.io/docs/users-sources/sources/protocols/kerberos/#spnego for FreeIPA- Users?

2. At https://docs.goauthentik.io/docs/users-sources/sources/protocols/kerberos/#password-backend :
It should be mentioned, that the Kerberos sync is optional, not a must and LDAP sync is also enough for making Kerberos/SPNEGO Backend working when the users are having the same username and the "User matching mode" is set.

3. I did not understand what "users that have been linked to this source" means, as i cannot find any setting to link some User to a source. Is there some setting and if yes: where?

4. In the Docs, the password stage is mentioned, but not the authentification- stage, which was the important thing to change, see: Flows and Stages > Stages > default-authentication-identification > Source settings

All in all: Very good work and thank you so much!

**Comment by Marlinc** [comment]
I've been able to successfully get SPNEGO working with Active Directory, however with the current implementation it doesn't yet seem to be possible to fully automatically login with Kerberos.

Am I missing something or does the current implementation only get triggered when pressing the Keycloak button. I was expecting Authentik to always send the `WWW-Authenticate: Negotiate` when enabled to it can immediately react when a client sends the needed ticket info. Should I open a new issue for this?

**Comment by rissson** [comment]
Yes, one still needs to select the source to use. However, in the identification stage of the login flow, you can unselect all user fields and select only the kerberos source to automatically trigger login using that source:

![Image](https://github.com/user-attachments/assets/c40d540e-d040-43ef-adfe-0a355da8ec75)

**Comment by Marlinc** [comment]
Right, yes that I knew already, I was hoping it would still trigger Kerberos even though other methods are also enabled. Basically my hope was it would be possible to use Kerberos automatically when available (based on the `WWW-Authenticate: Negotiate` response from the client) and if not show the regular login screen.
