### ISSUE TITLE
Allow wildcard dns in outposts

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#2799]
Wildcard DNS is required for some applications (for example Gitlab Pages). The default Gitlab Pages installation creates an ingress with a wildcard like *.pages.domain.com. Currently authentik does not allow to create a Proxy Provider with wildcards in the external host field. I think it would be better to input host and protocol in two fields.

**Comment by BeryJu** [comment]
While wildcards are not supported, you can use domain-level forward auth to get the same result: https://docs.goauthentik.io/docs/providers/proxy/forward_auth#domain-level
