### ISSUE TITLE
Authentik-server deployment failed when deployed with Helm

### ISSUE THREAD

**Issue by gitarns** [goauthentik/authentik#2805]
**Describe the bug**
When deploying with helm, the authentik-server pod fails to connect to postgres.

**To Reproduce**
Deploy authentik helm chart with the values.yaml described in the documentation

**Expected behavior**
authentik-server deploys and can connect to postgres.

**Screenshots**

**Logs**
"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1651580148.2378428, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1651580148.239664, "count": 48}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "__main__", "timestamp": 1651580148.2399235}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.100.76.89), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1651580149.2613587}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1651580149.2614348}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.100.76.89), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1651580150.2655954}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1651580150.265673}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.100.76.89), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1651580151.2711055}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1651580151.2712746}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.100.76.89), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1651580152.2776785}

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.4.1
 - Deployment:  helm 2022.4.1

**Additional context**
I checked the env related to postgres password (AUTHENTIK_POSTGRESQL__PASSWORD )in the description of the  authentik-server pod and it matches with the one in the  authentik-server secret with the key  postgresql-password

**Comment by BeryJu** [comment]
This can happen when you reinstall the chart and use the nfs-subdir provisioner in K8s, because that doesn't delete the data when the PVC is deleted.

**Comment by gitarns** [comment]
@BeryJu .You're right. My bad.
