### ISSUE TITLE
authentik-proxy binds localhost in container

### ISSUE THREAD

**Issue by EliRibble** [goauthentik/authentik#2836]
**Describe the bug**
The default behavior of /authentik-proxy within the container image is to bind localhost:8000. When using complex network setups in podman this makes it impossible to forward external requests to that port. This can be fixed by binding 0.0.0.0:8000 within the container.

**To Reproduce**
1. Install podman
3. podman run -p 10000:8000 --net slirp4netns:port_handler=slirp4netns ghcr.io/goauthentik/server:2022.4.1
4. (on the host system) curl -D 127.0.0.1:10000
5. See recv failed.

**Expected behavior**
Output like:

> curl -D - http://127.0.0.1:10000
HTTP/1.1 302 Found
date: Mon, 09 May 2022 22:22:34 GMT
server: uvicorn
content-type: text/html; charset=utf-8
location: /flows/-/default/authentication/?next=/
x-frame-options: DENY
content-length: 0
x-content-type-options: nosniff
referrer-policy: same-origin
x-authentik-id: ae814f4fb54948c09aae3c78fa9a5eef
vary: Cookie

**Version and Deployment (please complete the following information):**
 - authentik version:2022.4.1
 - Deployment: podman

**Additional context**
You can fix this problem yourself with:

podman run -p 10000:8000 --net slirp4netns:port_handler=slirp4netns \
--entrypoint  '["/usr/local/bin/python","/usr/local/bin/gunicorn","-c","./lifecycle/gunicorn.conf.py","authentik.root.asgi:application","-b","0.0.0.0:8000"]' \
 ghcr.io/goauthentik/server:2022.4.1

**Comment by BeryJu** [comment]
This is intended, port 8000 is used to communicate from the proxy to the core. Exposing port 8000 itself will not result in a working authentik install, hence it is only bound to localhost. Please use port 9000 and 9443 as specified in the compose file
