### ISSUE TITLE
Redirect query params invalid

### ISSUE THREAD

**Issue by skapin** [goauthentik/authentik#2853]
**Describe the bug**
The redirect after the /authorize on OAuth is invalid.

URL returned is formed like this:

MY_REDIRECT_URI#access_code=XX& ....

and should/could be 
MY_CALLBACKURL**?**access_code=XX& ....

Trying to pass a MY_REDIRECT_URI endign with "?" doesnt work

![backcall](https://user-images.githubusercontent.com/1846729/167886844-425fd31b-0ae2-4208-94a9-d5251feb0c76.png)

**Comment by skapin** [comment]
github redirect with a "?"

**Comment by BeryJu** [comment]
The format of the callback URL depends on 

- the confidentiality mode of the provider
- the value of the `response_type` parameter.

When the confidentiality is set to public, or response_type is set to `id_token` for example, a redirect URI like this is created. To get a redirect URL with query parameters, use `response_type=code`.
