### ISSUE TITLE
slight UI glitch

### ISSUE THREAD

**Issue by Kudjo-Grand** [goauthentik/authentik#2854]
Seems to be a minor glitch that "cuts off" text when the hamburger menu is open, instead of detecting the edge and moving it to a new line. The same behavior presents itself when you zoom in the browser.

menu closed (looks like you expect):
![image](https://user-images.githubusercontent.com/25695143/167954104-40b31470-fdd7-4468-8ef9-9aeb28b633f3.png)

with menu opened (or zoomed in "too far")
![image](https://user-images.githubusercontent.com/25695143/167954648-595ea472-6bc9-4121-873f-8aa770f4a3c6.png)

Should be pretty simple to correct.

What do you think?

**Comment by kensternberg-authentik** [comment]
This bug was fixed after Pull Request 7883: "[fix overflow glitch on ak-page-header](https://github.com/goauthentik/authentik/pull/7883)."  Thanks for bringing this to our attention, and for your patience.
