### ISSUE TITLE
What is the LDAP group object type?

### ISSUE THREAD

**Issue by pavanfhw** [goauthentik/authentik#2861]
**Describe your question/**
I am using Authentik LDAP outpost. I am configuring LDAP authentication on a service and it has a variable called `AUTH_LDAP_GROUP_TYPE` so it can search groups. I tried using the values from examples configurations and tutorials, but it is not working. And I don't know how to get this information via  CLI like `ldapsearch`.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.4.1
 - Deployment: helm

**Comment by pavanfhw** [comment]
The service is NetBox. Which uses Django Auth LDAP.

The LDAP configuration have the two values:
```
AUTH_LDAP_GROUP_SEARCH_CLASS=""
AUTH_LDAP_GROUP_TYPE=""
```
The LDAP search of a group returns:
```
objectClass: group
objectClass: groupOfUniqueNames
objectClass: goauthentik.io/ldap/group
```
Theses are the classes, I need to know the type
I tried values like `GroupOfUniqueNamesType`, `GroupType` etc

Searching about this it seems the group type is very arbitrary. For example in the stackoverflow link, an answer says that with Open Directory you have to use `PosixGroupType(name_attr='cn')`.

**Comment by BeryJu** [comment]
The LDAP schema of the outpost is roughly based on [RFC-2307Bis](https://ldapwiki.com/wiki/RFC2307Schema). A user's groups are listed as `memberOf` attribute which contains the full DN to the group.

Groups contain a `member` attribute with the Full DN of each user. 

`MemberDNGroupType('member')` should work for your usecase

(I also did just notice a small contradiction, since we use `objectClass: groupOfUniqueNames` but then use the `member` attribute not `uniqueMember` so that should probably be fixed)

**Comment by pavanfhw** [comment]
Using `MemberDNGroupType('member')` causes the error:

```
<class 'django.core.exceptions.ImproperlyConfigured'>

AUTH_LDAP_GROUP_TYPE must be an LDAPGroupType instance.
```

**Comment by pavanfhw** [comment]
@BeryJu what can I do to debbug this?

**Comment by rinseaid** [comment]
@pavanfhw - did you ever get this working? I'm trying to set up AWX which also uses django-auth-ldap and I'm running into the same issue.

**Comment by FelipePavan** [comment]
@rinseaid unfortunately not. We settled for using local auth. For AWX we use SAML, which I recommend

**Comment by rinseaid** [comment]
@FelipePavan thank you - I will try SAML. I might keep messing with LDAP and update here if I figure it out.

**Comment by BeryJu** [comment]
https://django-auth-ldap.readthedocs.io/en/latest/groups.html#finding-groups
