### ISSUE TITLE
Basic authentication, is it possible? 

### ISSUE THREAD

**Issue by yeyeoke** [goauthentik/authentik#2891]
**Describe your question/**
I'm trying to use app password to login to a specific application using an iOS-application. 

Previously using Authelia I used an application called LunaSea, to remotely control a webapplication called Sonarr, hosted on https://sonarr.example.com. 

Authentication in Sonarr is turned off, so the only authentication being done is by Authentic. 

While using Authelia I could set a Custom Header in LunaSea that authorizes the app to reach Sonarr. 

This was done by setting a Custom Header named "Proxy-Authorization" which contained: Basic followed by my username and password encoded in base64. 

Can I do the same, somehow in Authentic while using an app password? 

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.4
 - Deployment: docker-compose,

**Additional context**
Maybe Authelias documentation describes it better than me. Most likely :-) 

https://www.authelia.com/docs/features/single-factor.html

**Comment by BeryJu** [comment]
This is possible with 2023.1, see https://goauthentik.io/docs/providers/proxy/header_authentication
