### ISSUE TITLE
Integration with payment servicers/providers like paypal?

### ISSUE THREAD

**Issue by BrendanGreenlee** [goauthentik/authentik#2892]
Is there a way to integrate payment servicers like Paypal with Authentik? Like, someone would pay for a subscription, then that would trigger a creation of an SSO user tied to their information, then they would use that for logging in. Something like the okta integration with paypal is what I'm looking for: https://www.okta.com/integrations/paypal/

I have not deployed authentik yet, but have done other research short of asking this question!

My question would be answered with:
A link to some kind of integration guide or kit.
An explanation that Authentik relies on APIs and does not have a higher level integration.

Thank you for your time!

**Comment by BehnH** [comment]
Hey @BrendanGreenlee 👋  You would have to write a small script which takes data from a PayPal webhook and then transforms it to an API call for Authentik. Authentik doesn't have this kind of integration support at the moment. 

I'm not sure if @BeryJu has had this requested in the past, but it would be a nice addition to the project roadmap!
Something like [PagerDuty's Event Transformer](https://www.pagerduty.com/docs/guides/custom-event-transformer/) I think would be the best model for this?

**Comment by BeryJu** [comment]
Looking at Okta's integration, it only supports SWA which is basically just a password manager. For the time being there's no plan for an integration.

The idea for an incoming webhook support could be potentially more interesting and we'll put that on our roadmap
