### ISSUE TITLE
Possibly add a "Used/Trusted By […]" section

### ISSUE THREAD

**Issue by joh-klein** [goauthentik/authentik#2933]
We are evaluating different IAM solutions that can be self hosted. 

And we really like what we see with authentik. Our question at this stage is how mature authentik already is.
Please don't understand me wrong here! This is purely based on the lack of knowledge if (and maybe how many) other companies are using authentik successfully in production.

**Comment by BeryJu** [comment]
I added a shoutout section to the readme where people can email us/PR to add themselves

**Comment by fheisler** [comment]
Authentik Security CEO here - closing this as we're now tracking internally as we scale up Enterprise customers and should have some solid testimonials + case studies to share publicly soon!
