### ISSUE TITLE
Create a global token for app Password which works on all users

### ISSUE THREAD

**Issue by theoneandonly-vector** [goauthentik/authentik#2955]
**Is your feature request related to a problem? Please describe.**
the idea is to have a passwordless login (the users don't know hteir real password because it's used behind the scenes..) 

**Describe the solution you'd like**
I would like to make the setup-process easier by giving them all the same initial-Password through this.

**Describe alternatives you've considered**
Create another external provider which will accept the same password on every user, didn't find a solution yet and it would be much easier if it's buitlin.

**Comment by BeryJu** [comment]
This is not something we'll add due to all the security implications this would cause. Depending on the usecase it might be possible to implement this behaviour with policies.
