### ISSUE TITLE
Which URL are used by authentik ?

### ISSUE THREAD

**Issue by danaelg** [goauthentik/authentik#2971]
My authentik instance is behind a firewall and I want to filter http/s requests going outside. I want to know which urls are requested to the internet (I mainly thinking about update check).

To go further, I think we could use this issue to list all the requests that authentik makes and create a sequence diagram of network communications that we could add to the documentation (I'm willing to take care of it).

**Comment by BeryJu** [comment]
https://goauthentik.io/docs/installation/air-gapped

**Comment by danaelg** [comment]
thanks ! didn't search enough :confused:
