### ISSUE TITLE
Cannot se flow background image

### ISSUE THREAD

**Issue by skalahonza** [goauthentik/authentik#2973]
**Describe the bug**
Cannot set background image.

**To Reproduce**
1. Go to '/if/admin/#/flow/flows'
2. Click on 'Update Flow'
3. Scroll down to 'Background'
4. Choose file and press update
5. POST request is sent to api/v3/flows/instances/default-authentication-flow/set_background
6. HTTP STATUS CODE 405 is returned

**Expected behavior**
Can upload custom image and change it.

**Screenshots**
![image](https://user-images.githubusercontent.com/13693312/170819574-22fe1df3-1ee0-4a67-aaf0-9a6322c95b0d.png)

**Logs**
{"event": "Method Not Allowed (POST): /api/v3/flows/instances/default-authentication-flow/set_background/", "level": "warning", "logger": "django.request", "timestamp": 1653730186.6660135}
{"event": "Method Not Allowed: /api/v3/flows/instances/default-authentication-flow/set_background/", "exc_info": ["<class 'PermissionError'>", "PermissionError(13, 'Permission denied')", "<traceback object at 0x7f895ddbc4c0>"], "level": "warning", "logger": "django.request", "timestamp": 1653730186.666223}
{"event": "/api/v3/flows/instances/default-authentication-flow/set_background/", "host": "slp-auth.stg.mild.blue", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 21, "remote": "194.228.59.20", "request_id": "0ea139a2c04348d4992c1f23e40301b7", "runtime": 22, "scheme": "https", "status": 405, "timestamp": "2022-05-28T09:29:46.667129", "user": "akadmin", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"}
{"event": "/-/health/ready/", "host": "localhost:9000", "level": "info", "logger": "authentik.asgi", "method": "HEAD", "pid": 5114, "remote": "127.0.0.1", "request_id": "4e84ef6d26a842e68a527c6f63b75684", "runtime": 10, "scheme": "http", "status": 204, "timestamp": "2022-05-28T0

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.4.1
 - Deployment: docker-compose

**Additional context**
I am trying to do this with super user account.

**Comment by BeryJu** [comment]
https://goauthentik.io/docs/troubleshooting/image_upload

**Comment by skalahonza** [comment]
Thanks. I will try.
