### ISSUE TITLE
minor UI: Table sorting is case sensitive

### ISSUE THREAD

**Issue by BobSilent** [goauthentik/authentik#2989]
Sorting in table should ignore case

![image](https://user-images.githubusercontent.com/13506173/170995906-f10f6ef3-91e4-4e75-af39-9e2733f9c608.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.5.3
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
So turns out this is not quite as easy as it seems. It's easy to apply a `Lower()` function to the query order, but that only works on text based fields. Now that's also easy enough to detect, but there's no easy way to detect the field type for foreign keys or m2m relations.

**Comment by BobSilent** [comment]
I see, so sorting is done already on the backend?

Would it make sense/or is it currently possible to bring the sorting into the frontend?
Just querying the data from backend and let the table do the sorting in frontend, without any further server roundtrip?

For me this is no big deal, it is unnatural for me that sorting is case sensitive, but i think it is no major thing.
I even was not sure if I should write this as Bug or as Feature Request.

**Comment by BeryJu** [comment]
Indeed, the sorting, filtering and pagination is done all server-side, as this yields much better performance with large datasets (and with all the related-key lookups that are done, it makes the performance quite a bit better too)
