### ISSUE TITLE
Authentification on PostgreSQL with TLS client Certificate

### ISSUE THREAD

**Issue by genofire** [goauthentik/authentik#3034]
**Is your feature request related to a problem? Please describe.**
We try to replace password with Clients Certs in ower cluster. 

**Describe the solution you'd like**
Give a Path (and in K8s a secret with contains an cert which would be mounted readonly) 

**Describe alternatives you've considered**
Use a Database connection string, in statt of every part of connection.

**Additional context**

**Comment by BeryJu** [comment]
Since psycopg supports, this can be configured by https://docs.goauthentik.io/docs/installation/configuration#custom-python-settings, for example:

```python
import os

DATABASES = {
    'default': {
        "ENGINE": "authentik.root.db",
        'NAME': '<name>',
        'USER': '<user>',
        'PASSWORD': '<password>',
        'HOST': '<host>',
        'PORT': '25060',   
        'OPTIONS': {
            'sslmode': 'verify-full',
            'sslrootcert': os.path.join(BASE_DIR, 'ca-certificate.crt'),
            'sslcert': os.path.join(BASE_DIR, 'cert.crt'),
            'sslkey': os.path.join(BASE_DIR, 'key.crt'),
        },
    },
}
```
