### ISSUE TITLE
Initial development setup shows errors

### ISSUE THREAD

**Issue by thechubbypanda** [goauthentik/authentik#3040]
**Describe your question**
I've followed the instructions [here](https://goauthentik.io/developer-docs/setup/full-dev-environment) but I'm getting the following errors at the run step.

**Relevant infos**
I'm on Arch Linux, fully up to date and I used the docker images provided in scripts for databases.

**Screenshots**
![image](https://user-images.githubusercontent.com/33595996/172023596-b3b39cef-d7b3-4c95-a8cd-18aaaac935d9.png)

**Logs**
```
2022-06-04T19:49:53.393914 [info     ] /api/v3/outposts/instances/    [authentik.asgi] auth_via=api_token host=localhost:8000 method=GET pid=15171 remote=127.0.0.1 request_id=c0e9c32fec9d4fd28fb3206ed96eb023 runtime=9 scheme=http status=403 user= user_agent=goauthentik.io/outpost/2022.5.3
1654372193.4096622 [warning  ] Forbidden: /api/v3/outposts/instances/ [django.request]
1654372193.4102445 [warning  ] HTTP GET /api/v3/outposts/instances/ 403 [0.04, 127.0.0.1:44732] [django.channels.server]
ERRO[0097] Failed to fetch outpost configuration, retrying in 3 seconds  error="403 Forbidden" logger=authentik.outpost.ak-api-controller
```

**Version and Deployment (please complete the following information):**
 - authentik version: master branch
 - Deployment: [development]

**Comment by BeryJu** [comment]
The docs don't make it particularly clear, but you need also follow the Frontend instructions, as there is no bundled JS included

For that error in the logs, make sure `secret_key` is set in the local.env.yml file, and run `make migrate`

**Comment by thechubbypanda** [comment]
So I've set secret key:
```
(authentik-qIp7baq3-py3.10) [keval@localhost authentik]$ cat local.env.yml
debug: true
postgresql:
    user: postgres

log_level: debug
secret_key: "zi87sehgfzkhcbo97efzuydscisebckzwcnlzxc"
```
And I still get the error above. Do I need the UI stuff even for `make run`?

**Comment by BeryJu** [comment]
Yes you still need to run `make web-watch`, there are no built UI files included

**Comment by thechubbypanda** [comment]
Ok so the UI came up and everything appears to be working (apart from the lack of embedded outpost) however the log:
```
ERRO[0097] Failed to fetch outpost configuration, retrying in 3 seconds  error="403 Forbidden" logger=authentik.outpost.ak-api-controller
```
is still printing repeatedly from the `make run` command. What's that about?
