### ISSUE TITLE
minor UI: Focus on OTP field after entering password

### ISSUE THREAD

**Issue by andrin55** [goauthentik/authentik#3060]
**Describe the bug**
After entering password and pressing enter or using mouse to click "continue" the next OTP field is not in focus.
This requires the user to manually select the OTP field in order to enter the code.

**To Reproduce**
1. Enable "Compatibility mode" in authentication-flow
2. Configure OTP token for a user
3. Login with user

**Expected behavior**
The OTP field should be automatically set in focus after entering password.

**Screenshots**
1. Enter password and press enter:
![image](https://user-images.githubusercontent.com/2856476/172459286-e3954596-25ac-4985-87bd-a3cb127e5a63.png)

2. OTP field not in focus:
![image](https://user-images.githubusercontent.com/2856476/172459313-c74f7bba-c0c6-4885-afc1-15896a1e3865.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.6.1
 - Deployment: docker-compose

**Comment by wociscz** [comment]
2023.10.6 and still the issue persist. I'm just deploying new instance and am heavily testing logs in/out, 2fa and stuff around and this bugging me a lot.

**Comment by snue** [comment]
Our installation shows the same behavior. It's rather annoying and unexpected, since the transition from username to password input does work correctly. Could this issue be re-opened or is there some clear justification for the current behavior?

**Comment by eleith** [comment]
duplicate of #12869

**Comment by disconn3ct** [comment]
This is a duplicate of something that was opened 3 years later?

**Comment by snue** [comment]
> This is a duplicate of something that was opened 3 years later?

Of course, it is rather the other way around ("duplicated by"), but this one was closed as stale years ago, and the other one has an open pull request associated with it. This way there is a formal link between the issues, so I appreciate the mention.
