### ISSUE TITLE
Webauthn not working with M1 Macs

### ISSUE THREAD

**Issue by mtthidoteu** [goauthentik/authentik#3074]
**Describe the bug**
On M1 MacBooks, the Webauthn feature seems to be broken. On iPhones and Intel Macs, however this feature seems to be working on the same instance.

**To Reproduce**
1. Go to ' User Settings'
2. Click on 'MFA '
3. Enroll4. 
4. Presented with error message: Error: Error creating credential: NotAllowedError: This request has been cancelled by the user.5. 
5. Click on 'Register Device' (again)' 
6. Presented with error message: InvalidCharacterError: The string contains invalid characters.7. 

**Expected behavior**
Mac popup 'touch ID' and registering the webauthn

**Screenshots**
<img width="1208" alt="Screenshot 2022-06-10 at 15 52 31" src="https://user-images.githubusercontent.com/66959271/173092281-1649c6e5-8831-4a9a-afb6-f94c4c1394fa.png">
<img width="1208" alt="Screenshot 2022-06-10 at 15 53 03" src="https://user-images.githubusercontent.com/66959271/173092395-6197b888-8b9f-4168-9bb1-84136697ebc2.png">

**Logs**
*Client Logs*
```
[Error] Error: Error creating credential: NotAllowedError: This request has been cancelled by the user.
(anonymous function) — WebAuthnAuthenticatorRegisterStage.ts:67
c — runtime.js:70
(anonymous function) — runtime.js:308
kn — asyncToGenerator.js:17
p — asyncToGenerator.js:32
promiseReactionJob

	(anonymous function) (WebAuthnAuthenticatorRegisterStage-7d94127b.js:1:9455)
	promiseReactionJob
[Debug] authentik/ws: connected to wss://_auth.domain.com_/ws/client/ (FlowInterface.js, line 1)
> Selected Element
< <p class="pf-m-block">…</p>
[Error] InvalidCharacterError: The string contains invalid characters.
atob
a — utils.ts:29
(anonymous function) — WebAuthnAuthenticatorRegisterStage.ts:52:82
c — runtime.js:70
(anonymous function) — runtime.js:308
kn — asyncToGenerator.js:17
i — asyncToGenerator.js:32
(anonymous function) — asyncToGenerator.js:32
Promise
(anonymous function) — asyncToGenerator.js:29
(anonymous function) — WebAuthnAuthenticatorRegisterStage.ts:90
c — runtime.js:70
(anonymous function) — runtime.js:308
kn — asyncToGenerator.js:17
i — asyncToGenerator.js:32
(anonymous function) — asyncToGenerator.js:32
Promise
(anonymous function) — asyncToGenerator.js:29
(anonymous function) — WebAuthnAuthenticatorRegisterStage.ts:130
handleEvent — lit-html.ts:2047

	(anonymous function) (WebAuthnAuthenticatorRegisterStage-7d94127b.js:1:9455)
	promiseReactionJob
```

*Server logs*
_Not applicable (nothing relevant)_, 

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.6.2
 - Deployment: docker-compose

**Additional context**
I remember my bank's website stating they were also having an issue with M1 Macs on their Webauthn.

**Comment by MDXDave** [comment]
Works flawless on my Macbook Air M1 and my Macbook Pro with M1 Max Chip with Brave (Chromium). 🤷‍♂️

What browser you are using?

**Comment by mtthidoteu** [comment]
> Works flawless on my Macbook Air M1 and my Macbook Pro with M1 Max Chip with Brave (Chromium). 🤷‍♂️
> 
> 
> 
> What browser you are using? 

I am using Safari, maybe that's the issue?

**Comment by mtthidoteu** [comment]
Here is an additional debug message I have found from my client console:
`User gesture is not detected. To use the WebAuthn API, call 'navigator.credentials.create' within user activated events.`

**Comment by mtthidoteu** [comment]
All this is using Safari!
Cheers!
