### ISSUE TITLE
[Gitea] Authentication sources with non-lowercase names do not work

### ISSUE THREAD

**Issue by FunctionalHacker** [goauthentik/authentik#3076]
When creating an authentication source from Gitea (OAuth), if one supplies a name with uppercase letters in it, the callback URL returned by Authentik will be all lowercase and thus does not match the authentication source in Gitea.

**Comment by 9p4** [comment]
Tracked the issue down to here

https://github.com/goauthentik/authentik/blob/6d9579d3e65c7dc86804289be297bf508e8f0b1d/authentik/providers/oauth2/views/token.py#L90

**Comment by BeryJu** [comment]
Ah shoot, I completely missed that, that should've been removed during the migration regex for allowed redirect URIs....this also explains the Jenkins issue from above..sigh
