### ISSUE TITLE
default-user-settings-flow does not accept locale

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#3100]
**Describe the bug**
When executing the "default-user-settings-flow" directly from the "Flows" page (not via the user settings page), the locale is not accepted and shows "This field is required".

**To Reproduce**
1. Run the "default-user-settings-flow"
2. Fill all data
3. Click continue

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17555261/173795157-43d20293-bcd5-4ad7-837f-0038143ad11b.png)

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.6.2
 - Deployment: docker-compose

**Additional context**
Also, the fields show the current values in the background in grey if the field is empty. It should be possible to leave a field empty to keep the current value without having to retype it.

**Comment by sevmonster** [comment]
>the fields show the current values in the background in grey if the field is empty. It should be possible to leave a field empty to keep the current value without having to retype it.

IIRC, if the field is set to not required, the value is empty, and there is a placeholder, the value will be set to the placeholder when you submit.

**Comment by derfabianpeter** [comment]
The same behavior applies when using an invitation. The fields are empty, pre-filled with the placeholder defined in the invitation. If you submit the form, validation will fail because of the empty field

<img width="596" alt="Bildschirmfoto 2022-07-23 um 15 24 40" src="https://user-images.githubusercontent.com/7008445/180606971-3bddca66-29e2-4bef-b50c-61eb533c8cf6.png">

**Comment by eglia** [comment]
Issue is still present in 2022.8.2.

**Comment by BeryJu** [comment]
@derfabianpeter what you're describing is separate issue, placeholders are actually placeholders in the flow interface while they set the default value in the user settings interface, which is also not ideal, but lets open a new issue for that
