### ISSUE TITLE
LDAP Requests High Database Usage without reply

### ISSUE THREAD

**Issue by choelzl** [goauthentik/authentik#3111]
**Describe the bug**
When running ldapsearch or using ldap clients it increases the database CPU usage to 100%. And doesn't go down until restarted. I get no reply on the client side. 
When this happens, the front page UI (with my applications) loads forever and never displays any content (probably since database is busy).

**To Reproduce**
1. Setup LDAP (app, provider,outpost)
2. Run a LDAP query via cli or clients
3. Wait forever to get a reply and see CPU usage jump to 100%

**Expected behavior**
Get a reply and see CPU usage return to normal levels

**Screenshots**
![DB CPU Usage](https://user-images.githubusercontent.com/22908981/174281348-3e07fe1b-1822-4d1c-8941-2c980f30dba1.png)
![Loading forever](https://user-images.githubusercontent.com/22908981/174282129-f697a08f-b796-4375-b4cf-4f9a51788177.png)

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.6.2
 - postgresql version: 14
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
What is the LDAP Query you're running?

**Comment by choelzl** [comment]
Query: ldapsearch -x -H ldap://IP:389 -b "dc=ldap,dc=domain,dc=net" -D "cn=myusername,ou=users,dc=ldap,dc=domain,dc=net" -W
LDAP Client: Jellyfin 10.8

**Comment by BeryJu** [comment]
Could you also post the logs of the LDAP Outpost from start to where it stops responding?

**Comment by choelzl** [comment]
> {"event":"Fetched outpost configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","name":"LDAP","timestamp":"2022-06-17T11:38:13Z"}
> {"event":"Fetched global configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-06-17T11:38:13Z"}
> {"event":"HA Reload offset","level":"debug","logger":"authentik.outpost.ak-api-controller","offset":"6s","timestamp":"2022-06-17T11:38:13Z"}
> {"event":"Successfully connected websocket","level":"debug","logger":"authentik.outpost.ak-ws","outpost":"01213740-df76-47a3-a456-9ae1e984c7c5","timestamp":"2022-06-17T11:38:13Z"}
> {"event":"Enabled USR1 hook to reload","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-06-17T11:38:13Z"}
> {"event":"Fetching certificate and private key","level":"info","logger":"authentik.outpost.cryptostore","timestamp":"2022-06-17T11:38:14Z","uuid":"2afb7274-8a56-4579-9b1a-4c6c661cbd9d"}
> {"event":"Fingerprint hasn't changed, not fetching cert","level":"info","logger":"authentik.outpost.cryptostore","timestamp":"2022-06-17T11:38:14Z","uuid":"2afb7274-8a56-4579-9b1a-4c6c661cbd9d"}
> {"event":"initialised memory searcher","level":"info","logger":"authentik.outpost.ldap.searcher.memory","timestamp":"2022-06-17T11:38:14Z"}
> {"count":4,"event":"fetched users","level":"debug","logger":"authentik.outpost.ldap.searcher.memory","page":1,"timestamp":"2022-06-17T11:38:15Z"}
> {"count":7,"event":"fetched groups","level":"debug","logger":"authentik.outpost.ldap.searcher.memory","page":1,"timestamp":"2022-06-17T11:38:15Z"}
> {"event":"initialised direct binder","level":"info","logger":"authentik.outpost.ldap.binder.direct","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"initialised session binder","level":"info","logger":"authentik.outpost.ldap.binder.session","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Update providers","level":"info","logger":"authentik.outpost.ldap","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Starting LDAP SSL server","level":"info","listen":"0.0.0.0:6636","logger":"authentik.outpost.ldap","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Starting WS Handler...","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Starting WS Health notifier...","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Starting Interval updater...","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Running interval update","level":"debug","logger":"authentik.outpost.ak-api-controller","loop":"interval-updater","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Starting periodical timer...","level":"debug","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Starting Metrics server","level":"info","listen":"0.0.0.0:9300","logger":"authentik.outpost.metrics","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Starting LDAP server","level":"info","listen":"0.0.0.0:3389","logger":"authentik.outpost.ldap","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Pre-heating flow cache","flow":"default-authentication-flow","level":"debug","logger":"authentik.outpost.ldap","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Fetched outpost configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","name":"LDAP","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Starting authentik outpost","hash":"tagged","level":"info","logger":"authentik.outpost","timestamp":"2022-06-17T11:38:15Z","version":"2022.6.2"}
> {"event":"Fingerprint hasn't changed, not fetching cert","level":"info","logger":"authentik.outpost.cryptostore","timestamp":"2022-06-17T11:38:15Z","uuid":"2afb7274-8a56-4579-9b1a-4c6c661cbd9d"}
> {"event":"initialised memory searcher","level":"info","logger":"authentik.outpost.ldap.searcher.memory","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"re-initialised session binder","level":"info","logger":"authentik.outpost.ldap.binder.session","timestamp":"2022-06-17T11:38:15Z"}
> {"event":"Update providers","level":"info","logger":"authentik.outpost.ldap","timestamp":"2022-06-17T11:38:15Z"}
> 


Note that if I enter wrong credentials I get this as logs: 

> {"bindDN":"cn=myusername,ou=users,dc=ldap,dc=domain,dc=net","client":"10.10.1.7","event":"Invalid credentials","level":"info","requestId":"3c1a73f2-18f9-424e-a96e-3c410603d33f","timestamp":"2022-06-17T11:39:52Z"}
> {"bindDN":"cn=myusername,ou=users,dc=ldap,dc=domain,dc=net","client":"10.10.1.7","event":"Bind request","level":"info","requestId":"3c1a73f2-18f9-424e-a96e-3c410603d33f","timestamp":"2022-06-17T11:39:52Z","took-ms":595}

**Comment by choelzl** [comment]
Logged into the database to dump the request. This request is created by both the CLI and other clients. This request never terminates and is the origin of this bug

> WITH RECURSIVE parents AS (
>     SELECT authentik_core_group.*, 0 AS relative_depth
>     FROM authentik_core_group
>     WHERE authentik_core_group.group_uuid = '686bc339-ecdc-49f6-bc66-a81896dc91ac'::uuid 
>     UNION ALL
>     SELECT authentik_core_group.*, parents.relative_depth - 1
>     FROM authentik_core_group,parents
>     WHERE authentik_core_group.parent_id = parents.group_uuid
> )
> SELECT group_uuid
> FROM parents
> GROUP BY group_uuid;

**Comment by choelzl** [comment]
The culprit was a loop in the group "parents" configuration. It would be great to add a check to prevent the user by building such recursive cycles (except if its and intended feature and in that case maybe limit the depth of the recursion).
