### ISSUE TITLE
Passing cookies from the policies to the application

### ISSUE THREAD

**Issue by PotentialIngenuity** [goauthentik/authentik#3115]
**Describe your question**
I am trying to set cookies during the policy stage and have them forwarded to the application after sign in. I have the following code that signs into petio with a plex token to then receive a token from petio. This petio token is used in the petio_jwt cookie to tell if a user is logged in.

```
from authentik.sources.plex.models import PlexSourceConnection
import json

connection = PlexSourceConnection.objects.filter(user=request.user).first()
if not connection:
    ak_message("No Plex connection found")
    return True

base_url = "https://petio.tld" # Petio url
end_point= "/api/login/plex_login"

headers = {
    "Content-Type": "application/json",
    "X-Forwarded-For": str(ak_client_ip)
}

data = {
    "token": connection.plex_token
}

response = requests.post(base_url + end_point, headers=headers, data=json.dumps(data))

if (response.status_code == 200):
    
    petio_token = response.json().get('token')
    
    cookie_obj = {
        "domain": base_url,
        "name": "petio_jwt",
        "value": petio_token
    }
    requests.cookies.set(**cookie_obj)

    #ak_message("Cookies: " + json.dumps(requests.cookies.get_dict()))
    ak_message("The request was a success!")
    return True
else:
    message = f"The request failed with: {response.text}"
    ak_message(message)
    return True
```

**Relevant infos**
I have nginx setup to accept single app forward auth. This is passing the authentik_proxy cookie to the app but not a cookie from the policy.

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2022.6.2]
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Cookies can be added to proxy applications, however not directly like this. The property mappings are python and run in the core server, while the outposts are go and don't directly run the property mappings. What you can do instead is this https://goauthentik.io/docs/providers/proxy/custom_headers, and basically just return the `Cookie` or `Set-Cookie` header
