### ISSUE TITLE
Forward Auth returns 500

### ISSUE THREAD

**Issue by clbx** [goauthentik/authentik#3147]
I'm using Authentik 2022.6.2 deployed to kubernetes via the Helm Chart. I'm using nginx-ingress. 

Ive set up a domain level forward auth and when I attempt to navigate to an application, I always get a 500 error in response. 

Ive Created an application which is set to use a Forward Auth Proxy Provider with:
* Authentication URL: ``https://auth.services.<domain>.org``
* Cookie Domain: ``services.<domain>.org``

This creates an ingress for ``https://auth.services.<domain>.org/outpost.goauthentik.io``

This provider is set to use the Embedded Outpost. 

The provider reccomended adding the following annotations to the ingress I want to protect:
```
metadata:
    annotations:
        nginx.ingress.kubernetes.io/auth-url: |-
            http://auth.services.<domain>.org//outpost.goauthentik.io/auth/nginx
        # If you're using domain-level auth, use the authentication URL instead of the application URL
        nginx.ingress.kubernetes.io/auth-signin: |-
            https://auth.services.<domain>.org//outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
```
But that has some weird entries notably the http://https:// in the auth url.

So I added this to my ingress: 

```
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: |-
      https://auth.services.<domain>.org//outpost.goauthentik.io/auth/nginx
    # If you're using domain-level auth, use the authentication URL instead of the application URL
    nginx.ingress.kubernetes.io/auth-signin: |-
      https://auth.services.<domain>.org//outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
      
```

Navigating to the application ``https://dashboard.services.<domain>.com``, returns a 500.

Going to the auth-signin url brings me to a login page.

Going to the auth-url url gives me ``configuration error`` and this shows up in the logs:

```
"message": "Outpost authentik Embedded Outpost (Provider < Provider Name>) failed to detect a forward URL from nginx", "outpost": "authentik Embedded Outpost", "provider": "<Provider Name>", "url": "https:///outpost.goauthentik.io/auth/nginx"}, "event": "Created Event", "host": "localhost:8000", "level": "info", "logger": "authentik.events", "pid": 13336, "request_id": "fa2001f6a37843b2b4573a1727166d64", "timestamp": "2022-06-24T07:32:07.794756", "user": {}}
````

I'm beyond my depth now with how to get this to work, any help would be appreciated!

**Comment by clbx** [comment]
So between talking to some other users and scrouring the nginx logs, I think this is an issue with nginx. 

Whenever I go to the ingress, this shows up in the nginx logs:

```
2022/06/24 23:45:24 [error] 317#317: *48174 auth request unexpected status: 308 while sending to client, client: 10.42.1.1, server: dashboard.services.<domain>.org, request: "GET / HTTP/2.0", host: "dashboard.services.<domain>.org"
```

So nginx is getting the auth request, but something errors out along the way. I'm not sure this is an Authentik issue anymore, so feel free to close it, but if anyone can provide some assistance, I'd really appreciate it!

**Comment by clbx** [comment]
The ``auth-url`` annotation needed to be https. nginx 308 was due to using http.....

**Comment by evulhotdog** [comment]
This also could be a fix, depending on the root cause of the issue: https://github.com/goauthentik/authentik/issues/2180#issuecomment-1754491732

**Comment by Mahadevaswamys1999** [comment]
to resolve the issue you need to add you need to add http://ip-address:9000/outpost.goauthentik.io/auth/traefik instead of http://authentik_server:9000/outpost.goauthentik.io/auth/traefik. the issue will be resolved

**Comment by kbirger** [comment]
For me, the issue was resolved by adding 
```
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
```
to my location block serving the proxy for `/auth/<provider>`. I use nginx, but I am betting it's the same for traefik

```
location = /outpost.goauthentik.io/auth/nginx {
```
My sample config was missing this header. It is actually documented it, but I didn't notice the one line difference.
the `///` in the error is a give-away that something is not being sent. I actually had to look through the source to find where this was happening, and what it was looking for.

https://github.com/goauthentik/authentik/blob/cb906e19131a321cbdee0940e6d9ee11721463eb/internal/outpost/proxyv2/application/mode_forward.go#L31
https://github.com/goauthentik/authentik/blob/main/internal/outpost/proxyv2/application/mode_common.go#L89
https://github.com/goauthentik/authentik/blob/main/internal/outpost/proxyv2/application/mode_common.go#L74
