### ISSUE TITLE
Set default language

### ISSUE THREAD

**Issue by cfoellmann** [goauthentik/authentik#3163]
Is there any way to set the default language for all users?
For us detecting option for the UI language is not working correctly.
Setting the default for all our users to "German" would help a lot.

 - authentik version: 2022.6.3
 - Deployment: docker-compose

**Comment by MDXDave** [comment]
Edit your _Tenant_ (German: Umgebung) and add the following to _Other global settings_ -> _Attributes_:

```
settings:
  locale: de
```

than press Update and refresh the page 😄 

![image](https://user-images.githubusercontent.com/6099976/176227310-83a88f79-af7c-4c88-aa85-ae9c42ea9be0.png)

**Comment by cfoellmann** [comment]
I am not sure I did this right but it does not work.
It should be German for non-logged-in visitors as well, right?

I did add:

```
settings:
  locale: de
```

should it be:

```
{
settings:
  locale: de
}
```

**Comment by BeryJu** [comment]
Currently, the flow interface always auto-detects the locale, there's no way to override it.

**Comment by cfoellmann** [comment]
That is too bad. Since it mis-detects the locale for me all the time.
My windows PC is 100% de_DE on anything and everything. But I get the EN interface autodetected. 😞

**Comment by BeryJu** [comment]
Could you open the browser developer tools and post the debug logs here? Curious why your locale is not detected correctly.

**Comment by cfoellmann** [comment]
Found an issue there.

```
authentik(early): version 2022.6.3, apiBase /api/v3
locale.ts:133 
authentik/locale: No locale for 'de-DE', falling back to en
RouterOutlet.ts:100 
authentik/router: found match  e {route: e, arguments: {…}, fullUrl: '/core/providers/12'}
ws.ts:30 
authentik/ws: connected to wss://sso.domain.com/ws/client/
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/admin/version/
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/core/tenants/current/
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/root/config/
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/core/users/me/
Users.ts:20 
authentik/locale: Activating user's configured locale 'de'
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/events/notifications/?ordering=-created&seen=false&user=8
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/events/notifications/?ordering=-created&page_size=1&seen=false&user=8
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/providers/all/12/
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/providers/oauth2/12/setup_urls/
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/events/events/?action=model_&context_model_app=authentik_providers_oauth2&context_model_name=oauth2provider&context_model_pk=12&ordering=-created&page=1&page_size=20
Config.ts:13 
authentik/api[wus-technik.com]: 200 GET /api/v3/providers/oauth2/12/
ws.ts:34 
authentik/ws: closed ws connection: [object CloseEvent]
ws.ts:45 
authentik/ws: reconnecting ws in 400ms
ws.ts:30 
authentik/ws: connected to wss://sso.domain.com/ws/client/
```

**Comment by cfoellmann** [comment]
It seems that `de-DE` gets detected but authentik expects `de`. Is that a bug?

**Comment by cfoellmann** [comment]
@BeryJu thanks for implementing a fix so fast.
I will be looking forward to the next release

**Comment by wegylexy** [comment]
zh-HK, zh-TW, zh-MO should map to zh-Hant instead of zh-Hans
