### ISSUE TITLE
Proxy forward auth Caddy support & examples

### ISSUE THREAD

**Issue by kaeltis** [goauthentik/authentik#3180]
**Is your feature request related to a problem? Please describe.**
There currently is no official support in authentik's proxy forward auth endpoints and no examples for the caddy webserver and a workaround using the traefik endpoint has to be used. This could break if the traefik endpoint is updated, for example to adapt to changes in traefik.

**Describe the solution you'd like**
I'd love to see official support for caddy's [v2.5.1](https://github.com/caddyserver/caddy/releases/tag/v2.5.1) new [forward_auth](https://caddyserver.com/docs/caddyfile/directives/forward_auth) directive as a proxy forward auth `outpost.goauthentik.io/auth/caddy` endpoint and integration of configuration examples.

This could be modified and should even work with older caddy releases, as forward_auth is just an opinionated overlay for it's [reverse_proxy](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) directive: https://caddyserver.com/docs/caddyfile/directives/forward_auth#expanded-form

**Describe alternatives you've considered**
An alternative to caddy that also includes automatic Let's Encrypt / ACME support would of course be traefik which is already supported in authentik, however for simple or non-docker setups I find caddy preferable due to it's simpler configuration, ease of use as well as integrated support for PHP FastCGI, Fileserver with index and other things.

**Additional context**
Authelia has an existing integration for caddy's forward_auth directive: https://www.authelia.com/integration/proxies/caddy/

Configuration example adapted from the traefik example config using the current authentik workaround (traefik endpoint) for Caddy that's working in my test setup below.

For a local outpost, I replaced `https://outpost.company:9443` using HTTPS with `127.0.0.1:9000` using HTTP.

**As I'm no expert it could probably be improved and I'm not 100% sure about possible security implications, please don't use this for important stuff until someone who knows more about this can verify it's correct and secure!**

```
example.com {
        # always forward outpost path to actual outpost
        reverse_proxy /outpost.goauthentik.io/* https://outpost.company:9443

        # forward authentication to outpost
        forward_auth https://outpost.company:9443 {
                # use the traefik endpoint as a workaround
                uri /outpost.goauthentik.io/auth/traefik

                # capitalization of the headers is important, otherwise they will be empty
                copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version

                # optional, in this config trust all private ranges, should probably be set to the outposts IP
                trusted_proxies private_ranges
        }

        # actual site configuration below, for example
        reverse_proxy localhost:1234
}
```

**Comment by theAlevan** [comment]
I would love this, as I prefer Caddy over Traefik
