### ISSUE TITLE
OIDC: Storing illegal cookie

### ISSUE THREAD

**Issue by Alemiz112** [goauthentik/authentik#3185]
When using OIDC provider with Quarkus (java framework), there is thrown exception doe to invalid cookie being set: `IllegalArgumentException: Cookie value contains an invalid char: \`

I have verified that this is not Quarkus issue by testing with diffrent OIDC providers - Keycloak, Google, GitHub. This issue only occurs when using Authentik.

**To Reproduce**
1. setup OIDC provider & application
2. follow [this tutorial](https://quarkus.io/guides/security-openid-connect-web-authentication) to create demo application
3. configure demo app to use Authentik oidc
4. try to access website

**Version and Deployment:**
 - authentik version: 2022.5.3
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Fixed by the commit above

**Comment by Alemiz112** [comment]
Thanks! 😃
