### ISSUE TITLE
How to get user attributes based on custom LDAP user attributes ?

### ISSUE THREAD

**Issue by andrey-stein** [goauthentik/authentik#3205]
**Describe your question/**
OpenLDAP User. Added custom attributes. For example "homeDirectory". I add to Authentik custom Property Mappings for homeDirectory. Can't get it in list of User attributes in Authentik.

Please, kindly advice how to get custom attributes of OpenLDAP user / group in to federated Authentik  user attributes ??

**Relevant infos**
Release 2022.6.3
Was trying all possible combinations of Property Mappings
return ldap.get('homeDirectory')
return homeDirectory
return ldap.get('homeDirectory')
return list_flatten(ldap.get('homeDirectory'))

**Screenshots**
![image](https://user-images.githubusercontent.com/108661027/177120640-24664989-1fe1-4676-bac7-a7bbd27c2fca.png)

As you can see on a screanshot, no homeDirectory related attribute is added.

**Comment by BeryJu** [comment]
What does the full property Mapping look like? `return ldap.get('homeDirectory')` should be about right. Did you select the property mapping in the LDAP Source?

**Comment by andrey-stein** [comment]
![image](https://user-images.githubusercontent.com/108661027/177300270-3d846012-8e84-43aa-bddf-c68c74c7baaf.png)

**Comment by andrey-stein** [comment]
Yes, I did select Property Mapping in LDAP Source
![image](https://user-images.githubusercontent.com/108661027/177300824-160dd765-9eeb-4ac2-a2a9-552dfbc37b39.png)

Also, if I replace my definition with definition from the pre-defined mappings, then it works,
for example, if I replace
return ldap.get('homeDirectory')
with
return ldap.get('cn'), 
then I'll get new attribute with CN value in it

**Comment by BeryJu** [comment]
you can add something like 
```python
ak_logger.debug(ldap)
```
to see all the fields authentik gets

**Comment by andrey-stein** [comment]
![image](https://user-images.githubusercontent.com/108661027/177349386-6c82ba1d-a184-4314-a96a-59ee46d7ae36.png)

This didn't add any debug output to `docker compose logs -f`

**Comment by BeryJu** [comment]
try
```python
ak_logger.warning(ldap)
```, since with the default log level the debug message won't be printed

**Comment by andrey-stein** [comment]
Great ! Debug info has appeared.
Here is an output after `jq` formating:
![image](https://user-images.githubusercontent.com/108661027/177355434-bbd40b4d-ffb2-49ea-8d55-ec94b976c1a4.png)
So, there is a `homeDirectory` field red by Authentik from OpenLDAP,
 but `return ldap.get('homeDirectory')` doesn't add that to Authentik user attributes .

**Comment by andrey-stein** [comment]
[BeryJu](https://github.com/BeryJu), could you please kindly advise, what directive could be used
instead of `return ldap.get('homeDirectory')` to get `homeDirectory` LDAP user attribute
???

**Comment by BeryJu** [comment]
oh my bad I completely missed that, setting `Object field` to `homeDirectory` is invalid since a user doesnt have that attribute, set it to `attributes.homeDirectory`

**Comment by andrey-stein** [comment]
Great, now it works,
For those who are interested in details, the final format looks like this:
  
  

>> ![image](https://user-images.githubusercontent.com/108661027/178208665-816356c1-95b2-4857-9024-f3ed6a84bc20.png)

  
  
If you want to add debug info to logs, then the format looks like this:  
  
  
>> ![image](https://user-images.githubusercontent.com/108661027/178209678-81b016d1-ce20-410c-8431-591838e1ecd2.png)
