### ISSUE TITLE
Custom Brand/Logo flashes stock Authentik logo when entering Admin Interface

### ISSUE THREAD

**Issue by xcsdm** [goauthentik/authentik#3228]
**Describe the bug**
When using a custom SVG file for a branded logo "/media/mylogo.svg", the logo appears correctly on the User interface, but will flash the stock Authentik logo for a moment before the custom logo appears on the Admin interface.

**To Reproduce**
1. Put a custom SVG file in the media folder
2. Change the logo path in the Tenant settings to this file
3. Refresh the user interface, and confirm the logo is correct.
4. Open the admin interface is see the Authentik logo flash before the custom logo.

**Expected behavior**
Authentik logo should not appear/flash for custom branded tenants

**Screenshots**
I wasn't able to capture this in a good way.

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.7.1 (has happened since at least 2022.5.x)
 - Deployment:  docker-compose

**Comment by tahoward** [comment]
I'm seeing this issue on 2025.2.3. Appears there has been a regression.
