### ISSUE TITLE
Change unprivileged user uid for container

### ISSUE THREAD

**Issue by sevmonster** [goauthentik/authentik#3236]
**Is your feature request related to a problem? Please describe.**
My first user uids begin at 1000, as is the case in many Linux environments. It would be nice to have the ability to set the uid to run as with environment variables for the Docker or Kubernetes container. This would likely necessitate automatically adjusting the internal user uid (and removing other lower numbered uids that might conflict). Projects like [Paperless](https://github.com/paperless-ngx/paperless-ngx/blob/48dfbbebc654464026b0137c635262073c417292/docker/docker-entrypoint.sh#L6)  allow this kind of functionality.

**Describe the solution you'd like**
A new config variable that changes the uid/gid authentik drops privs to.

**Comment by scr4bble** [comment]
Hey, why is this issue closed please? Is there a resolution or any kind of statement why the user/group ID is 1000 and whether it is possible to change it without causing issues?
