### ISSUE TITLE
Authentik, Traefik and Unraid

### ISSUE THREAD

**Issue by Wheels35** [goauthentik/authentik#3253]
So I have been having a bit of an issue trying to get Authentik to work on Unraid with Traefik,
Forgive me if there are anything I missed, Ive been working on this for a week now and am losing my mind on what could be the issues.

There are a couple things I have come across, and I have been trying to follow as many of the different solutions but I cant seem to get completely there.

The end goal is to achieve single app level authentication NOT Domain level, as there are apps I would like to lock down separately, and I dont want to just enable their password portal as that would defeat this purpose.

I am using sub.domain.tld as all my usages, im using auth.domain.tld for Authentik.

First of all, in Authentik, I thought it was supposed to create a Docker Local connection but its showing as 'No integration active", as well as nothing showing up in the Outpost integrations.

Secondly, my current setup works with Domain Level, sort of. 
When going to any of the subdomains it redirects to the login page as expected but then kicks me back to the listing of apps. If i then key in the url sub.domain.tld it works and directs me to their login page. The app that comes up on their just directs to auth.domain.tld so thats useless.

If I switch this existing setup to single app it redirects infinitely upon itself, which I feel is a one of my labels wrong.

I set a traefik label for the middlewares on the docker to authentik@file so it forwards/redirects to authentik
I have set traefik label for forward auth on the dockers as https://auth.domain.com/outpost.goauthentik.io/auth/traefik ( i also removed this to no difference since its already in the middlewares)
I have set traefik priority on the Authentik container itself, and tried setting the priority to 50 on the embedded outpost.
In the embedded outpost i set it to https://auth.domain.com
In the traefik yaml file I use https://auth.domain.com/outpost.goauthentik.io/auth/traefik as the forwardAuth middleware

I am also using cloudflare as my DNS and I have both a cloudflare tunnel proxied as well as a direct subdomain to ip configured to test. I did have https rewrite on for cloudflare but have disabled it for testing purposes.

If there are logs, or screenshots or anything that I can use to help solve this problem that would be greatly appreciated.
Honestly Id really like to figure out single application and even correct domain level proxying on unRaid, so we can help other people out with this.

**Comment by blaine07** [comment]
Did you ever get any help? With the "No Integration" this isn't going to work. I am stuck there too. /var/run/docker.sock doesn't seem to work. not sure what's wrong :-(

**Comment by Selmaks** [comment]
Check if you have set the docker.sock location eg  /var/run/docker.sock

**Comment by obsidiangroup** [comment]
@blaine07 and @Wheels35 Can you provide your docker-compose, and screenshots of your Outpost Integrations config.
