### ISSUE TITLE
Compose-Up Error Related to authentik.Outpost

### ISSUE THREAD

**Issue by adamzvolanek** [goauthentik/authentik#3272]
**Describe the bug**
Upon issuing a compose-up on my docker-compose file (similar to the one provided), I am receiving a repeated stream of the below outpost errors. I have seen a previous issue report on [it](https://github.com/goauthentik/authentik/issues/2453) but don't quite identify the solution. My environment file is located on my [repo](https://github.com/adamzvolanek/DevRack/tree/main/Docker-Compose) to reference. Note there are some bogus values for obvious reasons.

**To Reproduce**
1. Go to my repo and run up the docker-compose with my environment file with respective environment variables updated to meet your servers IP or Docker network.
2. View on Authentik (not Worker) logs.
3. Result will be repeated. 

**Expected behavior**
I expect errors perhaps about my lack of geoIP implementation however not for anything else? Looking for some insight for direction so these logs are not spammed repeatedly without reason. 

**Screenshots**
![image](https://user-images.githubusercontent.com/80661527/179654311-9450d518-2f7b-40fe-ad72-e5cb79a857c0.png)

**Logs**
Repeated as seen below. 
```
{"event": "/api/v3/outposts/instances/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 27, "remote": "127.0.0.1", "request_id": "0c265ddd88174822bd6046aaa91f87b9", "runtime": 18, "scheme": "http", "status": 403, "timestamp": "2022-07-19T02:53:37.914673", "user": "", "user_agent": "goauthentik.io/outpost/2022.7.2"}
{"event": "Forbidden: /api/v3/outposts/instances/", "level": "warning", "logger": "django.request", "timestamp": 1658199217.9152439}
{"error":"403 Forbidden","event":"Failed to fetch outpost configuration, retrying in 3 seconds","level":"error","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-07-19T02:53:37Z"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: beryju/authentik:latest (2022.7.2)
 - Deployment: docker-compose

**Additional context**
I am able to access the initial setup and Authentik webpage. I have not done any work within Authentik itself yet. Waiting to see if I can iron out this docker-compose portion prior to leaving it running. I am not _super_ familiar with all the concepts Authentik provides, but wanting to learn and desire a simple SSO solution for multiple of my other dockers.

**Comment by adamzvolanek** [comment]
I just noticed on the Admin Dashboard that the 'Embedded outpost is not configured properly'. 
![image](https://user-images.githubusercontent.com/80661527/179656413-fc0ccc21-0aa0-4f03-beca-be9b627a326e.png)

I did see if this was a case of [RTFM](https://goauthentik.io/docs/outposts/embedded/) however I do not see the 'fresh install' outpost in my own Authentik... install?

Looking into my own Outposts I see:
![image](https://user-images.githubusercontent.com/80661527/179656487-1f52f80a-bff1-4771-ab99-fa0de4143b75.png)
![image](https://user-images.githubusercontent.com/80661527/179656778-a2589e37-8383-45db-b474-506416b88c69.png)

**Comment by BeryJu** [comment]
Same issue as in https://github.com/goauthentik/authentik/issues/3243, fixed release will be out in a bit, tl;dr restart the worker and the error should stop happening
