### ISSUE TITLE
Leaving Redirect URIs/Origins (RegEx) blank fills in non-regex URI

### ISSUE THREAD

**Issue by davidus05** [goauthentik/authentik#3282]
**Describe the bug**
In versions before authentik 2022.7, leaving Redirect URIs/Origins (RegEx) in provider settings blank, filled in the URI correctly, using RegEx, which was introduced some versions ago. Starting from authentik 2022.7, URI is filled with non-regex, which leads to errors: "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri)"

**To Reproduce**
1. Log in as admin
2. Go to Applications -> Providers
3. Modify an OAuth2/OpenID Provider
4. Clear "Redirect URIs/Origins (Regex)"
5. Let authentik fill it again automatically with logging in into the application
6. You'll see a URI there now, but with non-regex formatting

**Expected behavior**
The URI should be regex formatted

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.7.2
 - Deployment: docker-compose

**Additional context**
Did work in versions before 2022.7

**Comment by senbax** [comment]
Same here

**Comment by BeryJu** [comment]
Starting with 2022.7 if a redirect URL can't be parsed as regex it's compared directly as it was in previous versions, https://github.com/goauthentik/authentik/commit/0cad56ec73044d003b0a88997d337d97747d5918

**Comment by BeryJu** [comment]
It'll try to compare with regex and if the configured redirect_uri is not a valid regex, then it does strict comparison, if it can be interpreted as regex and doesn't match then you'll get the error

**Comment by davidus05** [comment]
It seems to use strict comparison (because it was not automatically regex-formatted) and the URI should definitely match. But the main issue, the automatic URI "detection", is still there and does not work as it did before.
