### ISSUE TITLE
Is there any way to get `access_token` for `google` source?

### ISSUE THREAD

**Issue by Bhautik0110** [goauthentik/authentik#3283]
**Describe your question/**
I added the google source in authentication/enrollment. So users can enroll or existing users can authenticate using their google account. Is that any way to get google provided access token, so I can access the specified scopes.

**Comment by oytuntez** [comment]
I am also trying to find my way around in the codebase to accomplish this. What would be needed for this even if we need to fork? Probably something around here:

https://github.com/goauthentik/authentik/blob/85ebbcfb82ff024a52b54915807f12beaef29cd7/authentik/providers/oauth2/models.py#L314

https://github.com/goauthentik/authentik/blob/85ebbcfb82ff024a52b54915807f12beaef29cd7/authentik/providers/oauth2/api/tokens.py#L19

Any recommendations?

**Comment by BeryJu** [comment]
you can use `request.context["goauthentik.io/sources/connection"].access_token` to get the access token used when logging in with google (or other OAuth sources)

**Comment by oytuntez** [comment]
Great, I will try this asap, thank you @BeryJu. More importantly, is there a generic way to get an access token (possibly already refreshed) for any service that a user has connected? This is the typical use case for integrations, I’m aiming to merge our integrations infrastructure with authentik, this will enable my plan to centralize all authentication tremendously.
