### ISSUE TITLE
"Failed to fetch output configuration, retrying in 3 seconds."

### ISSUE THREAD

**Issue by kyleamielke** [goauthentik/authentik#3287]
**Describe your question/**
A clear and concise description of what you're trying to do.
Attempting to add LDAP outpost. Adding it through either WebUI or Docker I receive the same error.

**Relevant infos**
i.e. Version of other software you're using, specifics of your setup
Most recent version of Authentik, haproxy, ADFS

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

{"error":"Get \"https://iam.xxx.com/api/v3/outposts/instances/\": x509: certificate is valid for *, not iam.xxx.com","event":"Failed to fetch outpost configuration, retrying in 3 seconds","level":"error","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-07-20T06:18:36Z"}
{"error":"Get \"https://iam.xxx.com/api/v3/outposts/instances/\": x509: certificate is valid for *, not iam.xxx.com","event":"Failed to fetch outpost configuration, retrying in 3 seconds","level":"error","logger":"authentik.outpost.ak-api-controller","timestamp":"2022-07-20T06:18:39Z"}

**Version and Deployment (please complete the following information):**
 - authentik version: Most recent
 - Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
set `AUTHENTIK_INSECURE` to `"true"` to accept any certificate

**Comment by atol71** [comment]
Also in outpost advanced config:
`authentik_host_insecure: true`
