### ISSUE TITLE
How to use authentik apis

### ISSUE THREAD

**Issue by amitavaghosh1** [goauthentik/authentik#3290]
The documenation is somewhat not great on how to use the api. 
https://goauthentik.io/api/

Here it says: 
URL: https://goauthentik.io/api/v3/
Authorization: 

but it doesn't way how to get this token. Or maybe I am missing it. 

The other question is where is the controller for POST api/v3/core/users ?

Can you please help?

**Comment by Bhautik0110** [comment]
@amitavaghosh1 You can create an API token at `http://localhost:9000/if/admin/#/core/tokens`.
