### ISSUE TITLE
Readiness probe random fail

### ISSUE THREAD

**Issue by Bhautik0110** [goauthentik/authentik#3292]
**Describe the bug**
Readiness probe random fail below-mentioned log:
```
{"error":"context canceled","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2022-07-20T12:03:50Z"}
```
After some time above-mentioned error disappears and back to the ready state.

**Screenshots**
![image](https://user-images.githubusercontent.com/76986554/179977180-1534ec97-4c67-4b2c-ae3d-0566e2445547.png)
![image](https://user-images.githubusercontent.com/76986554/179979213-1bb1d8d4-f498-4555-ba94-38eafaff2dc2.png)

**Version and Deployment (please complete the following information):**
 - authentik version: `2022.07.02`
 - Deployment: helm

**Additional context**

**Comment by Bhautik0110** [comment]
@BeryJu Why In worker below logs come, When I am creating `client_credentials`?
```
{"binding": "<PolicyBinding: Binding from Notification Rule default-notify-exception #0 to Policy default-match-policy-exception>", "event": "P_ENG: Evaluating policy", "level": "debug", "logger": "authentik.policies.engine", "pid": 17843, "request": "<PolicyRequest user=c9p77ovg8cjesa4bg990 obj=Notification Rule default-notify-exception>", "request_id": "task-4e3b437f49054f5c9a4b381e1c695d16", "timestamp": "2022-07-21T12:06:43.412102"}
{"binding": "<PolicyBinding: Binding from Notification Rule default-notify-exception #0 to Policy default-match-policy-exception>", "event": "P_ENG: Starting Process", "level": "debug", "logger": "authentik.policies.engine", "pid": 17843, "request": "<PolicyRequest user=c9p77ovg8cjesa4bg990 obj=Notification Rule default-notify-exception>", "request_id": "task-4e3b437f49054f5c9a4b381e1c695d16", "timestamp": "2022-07-21T12:06:43.806600"}
{"event": "P_ENG(proc): Running policy", "level": "debug", "logger": "authentik.policies.process", "pid": 17843, "policy": "<EventMatcherPolicy: default-match-policy-exception>", "process": "PolicyProcess", "request_id": "task-4e3b437f49054f5c9a4b381e1c695d16", "timestamp": "2022-07-21T12:06:43.808039", "user": "c9p77ovg8cjesa4bg990"}
{"event": "P_ENG(proc): finished and cached ", "level": "debug", "logger": "authentik.policies.process", "passing": false, "pid": 17843, "policy": "<EventMatcherPolicy: default-match-policy-exception>", "process": "PolicyProcess", "request_id": "task-4e3b437f49054f5c9a4b381e1c695d16", "result": "<PolicyResult passing=False>", "timestamp": "2022-07-21T12:06:43.810718", "user": "c9p77ovg8cjesa4bg990"}
```

**Comment by BeryJu** [comment]
The readiness probe becoming "unready" with timeout messages can happen when the node doesn't have CPU time, as long as it's temporary that's to be expected...

For the worker logs, authenticating with client_credentials creates an even in authentik and the default policies, that are bound to notification rules run, to check if a notification should be sent, also functioning as expected.

**Comment by Bhautik0110** [comment]
@BeryJu above logs are expected?

**Comment by Bhautik0110** [comment]
@BeryJu 
I am using static machine-to-machine authentication, Is that any required thing added that I missing?

**Comment by BeryJu** [comment]
yes the logs are expected, nothing is going wrong
