### ISSUE TITLE
Home Assistant Mobile App UI Issue

### ISSUE THREAD

**Issue by AngellusMortis** [goauthentik/authentik#3304]
**Describe the bug**

The default "stacked" layout does not render right at all on Android (tested on Android 11 and Android 12) when authenticating via the Home Assistant mobile app. 

**To Reproduce**
1. Setup Home Assistant as a proxy auth provider as [described in the docs](https://goauthentik.io/integrations/services/home-assistant/)
2. Install the Home Assistant app
3. Try to set up Home Assistant app

**Expected behavior**

UI should be more usable. Stacked layout should appear like it does on a normal Web browser outside of the app.

**Screenshots**

<img src="https://user-images.githubusercontent.com/490848/180493346-21953f20-dd52-4eb4-b567-db8df5542cfe.png" data-canonical-src="https://user-images.githubusercontent.com/490848/180493346-21953f20-dd52-4eb4-b567-db8df5542cfe.png" width="200" />

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version: authentik-2022.7.2
 - Deployment: helm

**Additional context**

It appears the div for the stack window is simply not centered vertically and has the incorrect height value. The div is scrollable and you can scroll to enter your email/password and try to figure out MFA (lol).

**Comment by RoboMagus** [comment]
Out of curiosity, can this be reproduced in other webviews on your android device? (e.g. chrome browser)

**Comment by AngellusMortis** [comment]
It does not happen in browsers. I do not have any other apps protected by Authentik to test with.

**Comment by RoboMagus** [comment]
After tinkering with a secondary HA app, can confirm that this reproduces.

**Comment by BeryJu** [comment]
I was also able to reproduce this on a Mi 9T Pro, no idea what is causing this though

**Comment by Fma965** [comment]
Old post but just to say if you set it to "content left" it will work., this still needs to be fixed

**Comment by florianschroen** [comment]
for those who also stumble across this topic... I had to search where to set "content left"

in Admin-Interface: `Flows and Stages > Flows > default-authentication-flow > Edit > Appearance Settings > Layout: Content Left`
