### ISSUE TITLE
Access to API from SPA (CORS)

### ISSUE THREAD

**Issue by rf152** [goauthentik/authentik#3309]
**Describe your question/**
I'm writing an SPA for users to change some additional fields in their profile (rather than them needing to understand how to change JSON). This will be integrated into our existing front-end website.

I want to use OAuth to authenticate, and then use the API to call the information for the user, and to update information as required.

When I try it, I get an XHR error: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://authentik.company/api/v3/core/users/me. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

Is there a way to allow Cross-Origin requests, or do I need to write a wrapper API that proxies the information between my SPA and Authentik?

**Logs**
```
{"event": "/api/v3/core/users/me/", "host": "authentik.company", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 139574, "remote": "10.244.1.0", "request_id": "aab7835b4d0645a2bbe4a757765a7ca9", "runtime": 51, "scheme": "https", "status": 403, "timestamp": "2022-07-25T15:14:10.471050", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:85.0) Gecko/20100101 Firefox/85.0"}
{"event": "Forbidden: /api/v3/core/users/me/", "level": "warning", "logger": "django.request", "timestamp": 1658762050.4727871}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.7.2
 - Deployment: helm/kubernetes

**Comment by rf152** [comment]
Ok, I've implemented CORS in the ingress. Is there a setting that I need to enable to allow the oauth token to access the API? (I'm sure I saw a setting somewhere, but I can't for the life of me work out where!)

**Comment by BeryJu** [comment]
With authentik 2022.7+ you can request the OAuth Scope `goauthentik.io/api` which will give the refresh token permissions on the API
