### ISSUE TITLE
Can a Flow be set per Application?

### ISSUE THREAD

**Issue by brokenscripts** [goauthentik/authentik#3316]
**Describe your question/**
The only way I see to set a flow is via the Tenant tab which sets it for the entire domain.  Is it possible to create different flows and bind them to the Application itself?  The goal being that an application can have a simple user/pass flow, or a different application requiring user/pass + token and internal network validation.

If this is already possible, I'm not sure how to implement it.  I see the Providers tab offering Policy or Bindings.  Thanks in advance.

**Relevant infos**
N/A

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.7.3
 - Deployment: Docker Compose v2.6.0

**Additional context**
N/A

**Comment by BeryJu** [comment]
You cannot directly configure flows per application, but your goal can still be accomplished.

You'd create a flow with your desired minimum level of authentication and select that in the tenant as authentication flow. Afterwards, you can create custom tenants that require 2FA or additional verification, and those flows can then be assigned in the provider as authorization flows. If an unauthenticated user tries to access application, they will first have to login using the tenant authentication flow, and then also pass the provider's authorization flow

**Comment by brokenscripts** [comment]
Thank you for that detailed explanation.  I understand what you mean so I'll give that a whirl tonight.  I'm closing this since the answer is straightforward!

**Comment by sevmonster** [comment]
Just wanted to add that you could also theoretically use [flow redirection](https://goauthentik.io/docs/flow/examples/snippets#redirect-current-flow-to-another-url) if you only wanted to stick to one main flow and tenant for simplicity's sake, or use policies to hide stages that should be reserved for specific applications. Though this may be too involved if you are not wanting to mess with policies to achieve the result.
