### ISSUE TITLE
[BUG, LDAP outpost] RootDSE search not functional

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#3361]
**Describe the bug**
The LDAP server not handling RootDSE searches, it probably should.

**To Reproduce**
1. Install Authentik
2. Create LDAP outpost & provider
3. Try to use it via Authelia or Apache Directory Studio
4. See error regarding RootDSE search failing.

**Expected behavior**
I would expect it to work like it does on OpenLDAP or FreeIPA.

**Version and Deployment:**
 - authentik version: 2022.7.3
 - Deployment: Helm

**Comment by firestrife23** [comment]
any update on this?

**Comment by firestrife23** [comment]
Although I enjoy Authentik, I think their LDAP implementation is pretty rudimentary. Using OpenLDAP and letting Authentik check against it as the source of truth, in my opinion, is much cleaner.

**Comment by samip5** [comment]
> Although I enjoy Authentik, I think their LDAP implementation is pretty rudimentary. Using OpenLDAP and letting Authentik check against it as the source of truth, in my opinion, is much cleaner.

Except that if you delete the user form ldap, it doesn't delete from Authentik like that.

**Comment by firestrife23** [comment]
@samip5 That's good to know, and thank you for the head up.

**Comment by samip5** [comment]
Not really stale, but.. :(
