### ISSUE TITLE
Additional post parameters federated login

### ISSUE THREAD

**Issue by oeiber** [goauthentik/authentik#3374]
Hi!
I'm using federated login with Azure AD, which is working fine. I'm an Microsoft 365 Consultant and browser knows multiple Azure AD accounts. Because of this my browser asks which Azure Ad account to choose, everytime I want to login using SSO with Authentik. For my opinion this behaviour breaks the user expierience :-)
I figered out that there's an additional parameter called 'domain_hint', which can be included to the authorization url.
So my question is, is there a way to add additional post parameters to the authorization url like &domain_hint=mydomain.com ?

Thank you!

Oliver

**Comment by BeryJu** [comment]
With the commit above (included in 2022.8), you can just specify query params in the authorization URL in the settings, and they'll be persisted

**Comment by oeiber** [comment]
Thank you for the implementation.
When I add ?domain_hint=domain.tld to the authorization url, the final url looks like this: domain_hint=%5B%27domain.tld%27%5D
Is it possible to prevent escaping the parameters?

**Comment by BeryJu** [comment]
@oeiber the actual issue wasn't actually the escaping, but rather the missing `doseq=True`, hence the URL param was set to an array which isnt what it should be
