### ISSUE TITLE
How to create `email`, and `profile` scope (previously built in)

### ISSUE THREAD

**Issue by Bhautik0110** [goauthentik/authentik#3389]
### Question
How do create/restore the old scope (`profile`, and `email`) scope, which is come before version `2022.7`, I have restored `email` scope using property mapping but how can I add `profile` scope?

### Deployment
- Method: `docker-compose`
- Version: 2022.7

**Comment by davidus05** [comment]
As you already know how to add scopes, I can provide you with some code. `profile` scope has following expression, maybe this helps:

`authentik default OAuth Mapping: OpenID 'profile'`

```
return {
    # Because authentik only saves the user's full name, and has no concept of first and last names,
    # the full name is used as given name.
    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(" ")`
    "name": request.user.name,
    "given_name": request.user.name,
    "family_name": "",
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    # groups is not part of the official userinfo schema, but is a quasi-standard
    "groups": [group.name for group in request.user.ak_groups.all()],
}
```

![image](https://user-images.githubusercontent.com/32458224/185756108-4e5b5ff7-026a-4bbb-b566-8d385d833bed.png)

**Comment by sevmonster** [comment]
All default authentik values including scopes are now provided via blueprints. For any tenants with modified settings the blueprints are not enabled automatically. Enable the relevant blueprint and you will get them back.
