### ISSUE TITLE
Config System

### ISSUE THREAD

**Issue by obsidiangroup** [goauthentik/authentik#3392]
**Is your feature request related to a problem? Please describe.**
There should be a way to change config settings without having to restart a container.

**Describe the solution you'd like**
Add an config section with all the values that can be set by environment can also be set here.  

**Describe alternatives you've considered**
The only alternative is setting via environment settings.

**Comment by sevmonster** [comment]
Do you change settings frequently enough to warrant this? None of the authentik environment settings are particularly volatile, and under normal circumstances should rarely need to be changed.

**Comment by obsidiangroup** [comment]
It's not that we change settings frequently, but when changing something like the mail settings, having to restart the containers for these settings to take affect can cause issues -- even just the few seconds it takes for the containers to restart can cause users not to be able to access needed services.  This is far from idea

**Comment by BeryJu** [comment]
If availability is this big of a concern then I'd recommend using the kubernetes helm chart which does rolling restarts for these changes 

Additionally, a lot of the config values (like email credentials) can be configured to be read from a file, see https://goauthentik.io/docs/installation/configuration
