### ISSUE TITLE
OAuth `.well-known` doesn't expose proper URLs in kubernetes cluster

### ISSUE THREAD

**Issue by ajgon** [goauthentik/authentik#3405]
**Describe the bug**
I'm trying to set up gitea+authentik+oauth2+kubernetes combo following this tutorial: <https://goauthentik.io/integrations/services/gitea/>. I have `gitea.domain.tld` and `authentik.domain.tld` respectively. Problem occurs, when I'm setting `OpenID Connect Auto Discovery URL` Gitea side. Since it's k8s env, I can't set it up to external URL (unless there is a trick in k8s to route ingress routes inside the cluster which I'm not aware of). When I'm using `authentik.domain.tld` here, gitea throws 500 as it can't resolve it, so I have to use internal `authentik.default.svc.cluster.local`. Then gitea is happy and auth source is added.

The issue is (as far as I understand the python code), authentik basically copies host header for all URLs returned in `/.well-known/`. This is a problem, as when I try to log in in gitea, I'm getting redirected to internal k8s domain, which of course doesn't exist outside of the cluster.

**To Reproduce**
Full steps to reproduce the behavior:
1. Set up authentik and gitea in k8s cluster
2. Follow the <https://goauthentik.io/integrations/services/gitea/> tutorial
3. Set `OpenID Connect Auto Discovery URL` in gitea to `http://authentik.default.svc.cluster.local/application/o/gitea-slug/.well-known/openid-configuration`
4. Try to sign in to gitea using authentik
5. Get redirected to non-existing host and fail to sign in

Simple steps to reproduce the behavior:
1. Set up authentik in k8s cluster
2. Set up open id provider and app
3. Visit `http://authentik.default.svc.cluster.local/application/o/<app slug>/.well-known/openid-configuration` from dummy pod (or authentik pod itself)
4. All returned URLs are internal k8s urls

**Expected behavior**
`/.well-known` endpoint should know which URLs should be returned as external `authentik.domain.tld` (for client communication), and which as internal `.svc.cluster.local` (for server2server). Probably the external URL should be also configured somewhere in openid provider configuration in authentik admin panel.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.7.3
 - Deployment: helm, using official goauthentik chart

**Additional context**
I assume this issue also applies to other applications aside gitea, but I haven't tested it yet.

**Comment by samip5** [comment]
Hi there,

I'm using the same version with Gitea outside k8s, but my `https://authentik.domain.tld/application/o/gitea/.well-known/openid-configuration` works perfectly fine?

My helm-release: <https://github.com/samip5/k8s-cluster/blob/main/cluster/apps/security/authentik/helm-release.yaml>

**Comment by BeryJu** [comment]
This behaviour is on purpose, authentik doesn't know it's public domain (well, somewhat with tenants, but those can use wildcards etc), so it'll always use the same host header in the response as the host header it got.

By default, you should be able to access your ingress from within the cluster without any special config, assuming the DNS name resolves

**Comment by ajgon** [comment]
> By default, you should be able to access your ingress from within the cluster without any special config, assuming the DNS name resolves

Ok, so probably it's some issue on my side - thank you, for clarification :+1:
