### ISSUE TITLE
Authentik in place for specific pages - setting/admin pages

### ISSUE THREAD

**Issue by NickBootOne** [goauthentik/authentik#3410]
I want Authentik login page only on some admin or setting pages.

Now it's the other way, you have to give all the pages (unauthenticated paths) where you don't want to authenticate, but for some applications I want to have only the settings/admin page to let Authentik go in place for authentication.

Is this possible ?

**Comment by sevmonster** [comment]
You could use negative lookahead or some other method of non-matching sequences but I do not think that would be the best option, and without more information it is impossible to say what would be.

1. What app(s) are you trying to protect?
2. How are those app(s) authenticated? It looks like you are using Proxy providers, but is it authentik native proxying, forward auth, forward auth with a reverse proxy, etc?
3. If there is a reverse proxy in front of the app(s), what proxy is it? Nginx, Apache, Traefik, etc?
4. What URIs of the app(s) are you wanting to protect?
5. Are the app(s') URIs static or dynamic?
6. Do the apps in question already support this functionality natively, or is the only way forward with proxying? Or, if using a reverse proxy, can you not forward to authentik selectively via the proxy?

**Comment by NickBootOne** [comment]
Thanks @sevmonster 

1. ghost webpage
2. forward auth with reverse proxy but can be set to Authenik's reverse proxy
3. SWAG
4. https://<domain>/ghost
5. Swag has configs for all sub domain that is managed by Swag.
It worked all with Authelia but not with Authentik.
So I was testing with unauthenticated paths, with no joy.


How does that negative lookahead works ?

**Comment by q20** [comment]
According to Authentik's docs, `Authenticated Paths` use the Golang regex parser. Negative lookahead is not supported by Go's standard library regex engine RE2.
