### ISSUE TITLE
Unreadable labels at radio buttons for new providers in browser dark mode

### ISSUE THREAD

**Issue by ToshY** [goauthentik/authentik#3412]
**Describe the bug**
Both at adding "New provider" modal in (browser) dark mode:

1. Labels for radio buttons are black and quite unreadable in dark mode.
2. When going next in the "Select type" step, the text "Select type" will also turn black.

**EDIT**

This apparently occurs in multiple modals, also at "Customisation" > "Property Mappings" > "Create" (button in table).

**To Reproduce**

1. Set browser preference to  dark
2. Add a new provider
2.1. Look at the labels at the radio buttons
2.2 Go to next step, and see the text "Select type" also turn balck

**Expected behavior**
White text for radio button labels and "Select type" text in dark mode.

**Screenshots**

**Issue 1**
![image](https://user-images.githubusercontent.com/31921460/184440146-f439f4d3-b810-48fd-92da-52b3a9f77035.png)

**Issue 2**
![image](https://user-images.githubusercontent.com/31921460/184441823-0ea52724-6f0a-4728-abaf-5f02071cab34.png)

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: `2022.7`
 - Deployment: `docker compose`

**Comment by BeryJu** [comment]
This is fixed in the current version, I don't remember which commit fixed it
