### ISSUE TITLE
Issues when adding users on Rancher

### ISSUE THREAD

**Issue by Yomanz** [goauthentik/authentik#3413]
**Describe the bug**
When attempting to add users/groups to projects/namespaces the search isn’t working properly and I am unable to add users/groups.
It doesn’t actually search, as there is a user called Daave but no user called Daa. If I type Daave in and click enter, it “adds” them but doesn’t actually give the user permissions.

**To Reproduce**
1. Setup Rancher with Authentik following Authentik documentation.
2. Attempt to add an authentik user to a project/namespace.

**Expected behavior**
It should show the users that exist in Authentik

**Screenshots**
![image](https://user-images.githubusercontent.com/5119107/184451954-432c44fe-545e-4e3c-8c0e-79ebd556e7b0.png)

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.7.2
 - Deployment: Helm

**Comment by badsmoke** [comment]
is there a fix yet?
