### ISSUE TITLE
Cloudflare access - OpenID authentication with authentik

### ISSUE THREAD

**Issue by NickBootOne** [goauthentik/authentik#3422]
**Describe your question/**
Want to setup Cloudflare access with OpenID authentication to Authentik.
But after setting it up and try to authenticate i’m getting an error from Cloudflare “ Failed to fetch user/group information from the identity provider”

Tried the different options with “Subject mode”.
But no success 

**Relevant infos**
Cloudflare access (teams) / zero trust

**Screenshots**
![IMG_0043](https://user-images.githubusercontent.com/59101602/184635908-0fefbe0e-a487-4074-8b0c-3e9ff6d5d5d6.jpeg)

**Comment by BeryJu** [comment]
![image](https://user-images.githubusercontent.com/1932513/184659998-a208dc11-bc2a-4d67-b1f6-2d17d361d311.png)
works fine for me with these settings (defaults on authentik, just make sure you selected a signing key)

**Comment by NickBootOne** [comment]
Thanks @BeryJu 
Just added the email and name OIDC Claims in Cloudflare and give a check at "include claims" in authentik and works like a charm !

**Comment by ShlomiD83** [comment]
I have the same issue, everything looks to be configured correctly but the error persists.

The oidc claims should the word email or my actual email?

**Comment by IIIdefconIII** [comment]
![Schermafbeelding 2023-10-29 235913](https://github.com/goauthentik/authentik/assets/9917659/fd948529-e457-41ae-93b6-1ab01e95be31)

**Comment by d1same** [comment]
> ![Schermafbeelding 2023-10-29 235913](https://user-images.githubusercontent.com/9917659/278908829-fd948529-e457-41ae-93b6-1ab01e95be31.png)

I am getting the same exact error.

**Comment by IIIdefconIII** [comment]
Same her aswell already tired alot of yhing but cant get it to work

**Comment by admecoach** [comment]
I've commented on how I solved this as my adding application policies to the Authentik auth domain gave me same error after it was working and another user noted they fixed based on certs https://github.com/goauthentik/authentik/issues/7526#issuecomment-2035186098

**Comment by VentingBow5** [comment]
I have followed this (#3422) and [https://github.com/goauthentik/authentik/issues/7526](url) thread but I am still getting the same error.

I use the Authentik Self Signed certificate
I checked "include claims" in authentik 
I added the email and name OIDC Claims in Cloudflare
I tried unchecking and re-checking "include claims in ID token" with the same error as a result


Any thoughts?
