### ISSUE TITLE
LDAP Provider: Search Group dropdown field does not show all entries after importing 180 groups from LDAP source

### ISSUE THREAD

**Issue by tinsami1** [goauthentik/authentik#3432]
**Describe the bug**

After importing all users and 180 groups from an LDAP source, I cannot see anymore the 'authentik Admins' group in the dropdown field.  The imported groups all have uppercase first characters and the dropdown's sort is case sensitive.

**To Reproduce**
1. Import from LDAP source 180 groups all having and uppercase first character.
2. Create an LDAP Provider or edit an existing one
3. Click on the Search Group dropdown
4. Not all groups are displayed by the dropdown.

**Expected behavior**
All groups are shown/displayed for selection.

**Screenshots**
![Screenshot from 2022-08-17 14-30-06](https://user-images.githubusercontent.com/37137337/185051728-7afcd052-9054-4b71-b4da-c3213a0c10ef.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.8.1
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
closed by https://github.com/goauthentik/authentik/commit/b429e2439297bb1034c501508551ed286a120212
