### ISSUE TITLE
Ability to have html login forms autofilled using Authentik

### ISSUE THREAD

**Issue by stephenmond** [goauthentik/authentik#3440]
**Is your feature request related to a problem? Please describe.**
Authentik is an extremely robust and wondeful all in one SSO solution for many use cases. Unfortunately there is no option to use Authentik with applications that have **no SSO compatibility, and no ability to shut off basic html form login**, to use a proxy provider auth flow.

**Describe the solution you'd like**
Some SSO solutions have implemented a html form filling option, such as this [Formstack Option](https://help.formstack.com/s/article/Single-Sign-On-SSO-Autofill) or this [autofill plugin from Okta](https://help.okta.com/en-us/Content/Topics/Browser-Plugin/browser-plugin-main.htm)

Basically, the use case would be to develop some sort of configuration to allow Authentik to hold the credentials of users for specific applications that do not fit into any of the other available flows/options, with something like a solution above. Preferably not in a separate browser plugin, but I cannot speak to the feasibility of that request.

**Describe alternatives you've considered**
There unfortunately is not an easy alternative for applications that cant be put behind a proxy auth or have no way of adding SSO compatibility. The best one can do is use Authentik as a bookmark manager for these Applications, but it is capable of so much more, and this feature would be a wonderful addition to an already powerful service.

**Comment by HOSTED-POWER** [comment]
We would really like this feature which is currently lacking, okta seems to have really great functionality regarding this :)

**Comment by ne0YT** [comment]
> Not sure about what I'm saying, but I don't think it's doable without a browser plugin/extension. Though, great idea

I think it should be possible similar to passign basic-auth when using authentik as a reverse-proxy. by selecting the fields to fill by name and just let authentik do an initial POST on the page when the page gets loaded.

**Comment by ne0YT** [comment]
I think this should smh be possible using soemthign like curl as far as it looks to me authentik saves the session cookie for the user right?

**Comment by ne0YT** [comment]
Kemp has a similar Feature:
https://support.kemptechnologies.com/hc/en-us/articles/14337587450253

**Comment by ne0YT** [comment]
![image](https://github.com/goauthentik/authentik/assets/97364807/0c356107-fdd6-4561-808f-bbd4fb31bb67)

**Comment by huberfelix** [comment]
Any update on this Feature request? It would be so nice if sending user/password to backend forms would work!!

**Comment by sammcj** [comment]
This would be really great, especially for apps that can't have their internal authentication disabled.

**Comment by BeryJu** [comment]
This is most likely not something we'll implement anytime soon. Implementing this requires a lot of things we don't want to do, like storing passwords for other applications and building a password-manager-like browser extension to fill those into forms.
