### ISSUE TITLE
Loading flows/stages in administrator UI is very slow

### ISSUE THREAD

**Issue by kdkasad** [goauthentik/authentik#3479]
**Describe the bug**
When navigating to the *Flows*, *Stages*, or *Prompts* pages in the administrator interface, the page loads normally but the list of flows/stages/prompts takes a long time to populate (5-30 seconds).

The long loading time is caused by a request to any of these API endpoints:
 - `/api/v3/stages/all/`
 - `/api/v3/flows/all/`
 - `/api/v3/stages/prompt/prompts`

It takes 15 seconds to get a response, whereas other API requests (like to `/api/v3/stages/all/types/`) load in just a 10-100 milliseconds.
See the screenshot below for Chrome DevTools' timing breakdown for one example.

This behavior is consistent, even when reloading the page within a few seconds.
It still takes a while to load the list.

**To Reproduce**
1. Go to the administrator interface
2. Click on *Flows & Stages* in the sidebar and go to either *Flows* or *Stages*
3. Observe long wait time for list

**Expected behavior**
The list should populate quickly.

**Screenshots**
Chrome DevTools network log while loading the aforementioned page. The middle request is to the `/api/v3/events/notifications/` endpoint, so it's (probably) not relevant to this problem.
![DevTools network log](https://user-images.githubusercontent.com/63574107/186787153-f001ea37-1f52-4812-a9a6-a7bc5acc83db.png)
As you can see, the last request takes almost 14 seconds while the others only take 150-200 ms.

Chrome DevTools request timing breakdown for the slow API request:
![Chrome DevTools timing breakdown](https://user-images.githubusercontent.com/63574107/186786711-761376f2-be2a-4354-aded-4112fb3904e3.png)

**Logs**
Only standard access logs are printed. No error messages appear:
```json
{"auth_via": "session", "event": "/api/v3/stages/all/types/", "host": "[redacted]", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 25058, "remote": "[redacted]", "request_id": "459df910b47b4880bd1816770af65a6c", "runtime": 25, "scheme": "https", "status": 200, "timestamp": "2022-08-25T23:20:51.011078", "user": "kian", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"}
{"auth_via": "session", "event": "/api/v3/stages/all/?ordering=name&page=1&page_size=20&search=", "host": "[redacted]", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 22698, "remote": "[redacted]", "request_id": "0a6f7cdd679e4cf8ba03869d287c58db", "runtime": 11017, "scheme": "https", "status": 200, "timestamp": "2022-08-25T23:21:02.022123", "user": "kian", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.8.2
 - Deployment: Docker Compose

**Additional context**
This is the only time I experience slow loading when using Authentik. All other pages load in reasonable times, so I don't think it's a server misconfiguration.

The Authentik server has a Redis container available for caching, which makes this problem even more strange.

Also note this is with the default Authentik setup. I had not added any flows, stages, or policies when this problem first occurred.

**Comment by billycao** [comment]
Was having an identical issue with slow behavior only for loading flows and stages, same API delay in chrome inspector.

Was running authentik on NFS mounts and this resolved itself after migrating to a local NVME VM disk, in case it helps anyone. 

Likely the API call requires some ordering/fetching that is disproportionately affected by low disk iops. Cheers!

**Comment by BeryJu** [comment]
I forgot to link it to this issue, but this is fixed by https://github.com/goauthentik/authentik/commit/cfad472e1b075682d08dedbf21c66f0a558fae39 and https://github.com/goauthentik/authentik/commit/782fec0eb942236d83c5c2a4bc7f57ef16bbf106, which will be in 2022.10
