### ISSUE TITLE
2fa login flow mobile view zoomed in

### ISSUE THREAD

**Issue by macmoritz** [goauthentik/authentik#3487]
**Describe the bug**
The 2fa login flow is zoomed in on mobile devices. Can not zoom out.

**To Reproduce**
Login on mobile to get to 2fa step.  
Alternative use emulated mobile phones in dev tools of a browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/49832924/187093468-a861296c-dcf9-44c3-a923-9c752a3e7c2f.png)

**Version and Deployment **
 - authentik version: 2022.8.2

**Comment by karpiq24** [comment]
This issue still exists.
