### ISSUE TITLE
Cannot import/create RS256 signing key

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#3496]
**Describe the bug**
I need an RS256  signing key for Synapse/Matrix. I created one with these commenads, cause authentik can't create them directly in the UI.
```
ssh-keygen -t rsa -P "" -b 4096 -m PEM -f jwtRS256.key
ssh-keygen -e -m PEM -f jwtRS256.key > jwtRS256.key.pub
```
However i always get this error: "unable to load certificate"
I also tried mounting the Certificates via /cert into to pods. After running the "certificate_discovery" celery job it reports "Successfully imported 1 files" but the Certs are not selectable in UI. I then tried to create the Certs via authentik shell, they get created without error but are invisible in the UI.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.8.2
 - Deployment: helm

**Comment by BeryJu** [comment]
authentik *Certificate* keypairs are primarily meant to store certificates, hence generating a public/private key pair is not enough. You'd have to generate a certificate with a private key, and authentik will use the certificate's public key

Additionally, the default self-signed certificate generated in every authentik install uses RSA keys so you can just use that certificate without generating a new one (on older installs the self-signed cert is 2048 bits, every new install after 2021.12.4 will have a 4096 bit private key)
