### ISSUE TITLE
initial-setup will not load

### ISSUE THREAD

**Issue by Griffen8280** [goauthentik/authentik#3499]
**Describe your question/**
Installed the stack properly and everything in docker is showing green accross the board.  However when I attempt to go to the initial-setup URL of : https://192.168.1.10:7443/if/flow/initial-setup/ I get greeted with a "Not Found" page.

**Relevant infos**
Latest Docker version and portainer versions.  It is an arm64 system however I have verified that everything is functioning as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/42878642/187291448-ad32ab8d-2866-4900-8e20-e14963eaa257.png)

**Logs**
![image](https://user-images.githubusercontent.com/42878642/187291733-27957d80-4412-457b-85fe-9b0ebc3f0f95.png)

**Version and Deployment (please complete the following information):**
 - authentik version: [2021.8.2]
 - Deployment: [docker-compose]

**Additional context**
Nothing I can think of right now.

**Comment by BeryJu** [comment]
Is your worker container running? It looks like the initial tasks havent run, and one of those tasks creates the initial-setup flow

**Comment by Griffen8280** [comment]
Ok I think you might have pointed me in the right direction here.   I had the value AUTHENTIK_SECRET_KEY: "YOUR_AUTHENTIK_KEY" set in the environment of the main server but not in the worker.  And looking at the logs:
![image](https://user-images.githubusercontent.com/42878642/187415333-42e38d14-8743-4ace-9762-9164338d280b.png)
It would appear I may need to set this value on both of those servers so they can talk to each other.  I wrongly assumed it only needed to be set on the main and it would code it into the database for the worker to pull and use.  I'll try a re-run of the worker with the value set for it as well and see what happens.

**Comment by BeryJu** [comment]
there are some environment variables which only need to be set for the worker (like email for example), but in general they should be set equally for both and the values are not written to the database

**Comment by Griffen8280** [comment]
Understood, thanks for clearing that up.  I'm doing a re-pull now that I have it set for both and we'll see how it goes.

**Comment by Griffen8280** [comment]
Yep that did it.  Everything loads as expected now and seems to be working.  Thank you so much for your help/time!
