### ISSUE TITLE
StartTLS not working

### ISSUE THREAD

**Issue by rheaalleen** [goauthentik/authentik#3509]
I was enabling StartTLS on my OpenLDAP installation and since I´m completely switching over I was forcing the connections to use it 

```
dn: olcDatabase={1}mdb,cn=config
changetype: modify
add: olcSecurity
olcSecurity: tls=1
``` 

The bind is working locally

![StartTLS Bind](https://i.imgur.com/iufEr4c.png)

However when I add the configuration for StartTLS it refuses to connect. It still does a simple bind with the provided credentials.
I tried various configurations, LXC, VM and docker recreations but the result was always the same.

![](https://i.imgur.com/ErzHyhX.png)

![](https://i.imgur.com/S8PUTaU.png)

![](https://i.imgur.com/KkA9Kb4.png)

I confirmed that clients can connect (locally since I didn't distribute CA cert yet)
![](https://i.imgur.com/QHCV8Gh.png)

![](https://i.imgur.com/kO7gNS3.png)

"Confirmation" about the behavior, when you leave the bind pw empty with having StartTLS enabled
![](https://i.imgur.com/3ToPzhX.png)

I made a simple python script based on the ldap3 library to test the logic shown here: https://github.com/goauthentik/authentik/blob/cdf88e44770d5359f5bce945d59cfb852d83fa8b/authentik/sources/ldap/models.py#L108-L141

``` 
# import class and constants
from ldap3 import Server, Connection, ALL, SUBTREE, Tls
from ssl import CERT_REQUIRED

total_entries = 0

tls = Tls(ca_certs_file='C:/Users/rhea/Downloads/OpenLDAP_CA.pem', validate=CERT_REQUIRED)
# define the server
s = Server('ldap.domain.io', get_info=ALL, tls=tls)  # define an unsecure LDAP server, requesting info on DSE and schema

print(s)

# define the connection
c = Connection(s, user='cn=admin,dc=domain,dc=io', password='xyz!')

print(c)

# perform the Bind operation
c.bind()
print(c)

c.start_tls()
print(c)

c.search(search_base = 'ou=users,dc=domain,dc=io',
         search_filter = '(objectClass=inetOrgPerson)',
         search_scope = SUBTREE,
         attributes = ['uid'])
total_entries += len(c.response)
print(total_entries)
for entry in c.response:
    print(entry['dn'], entry['attributes'])
``` 
start_tls before or after bind doesn´t change the result, I initially thought the same as #1049 
https://github.com/goauthentik/authentik/issues/1049#issuecomment-1159604653
This is consistent with the ldap3 documentation.

My quick test ignores tls configuration as it defaults to none which accepts any certificate in return. I added the CA file and CERT_REQUIRED and still could connect.

The only difference I´ve found is if the connections is bound or not depending on the order of bind() and start_tls(). I still get results but the 4th line changes to bound if bind() comes after start_tls().

``` 
ldap://ldap.domain.io:389 - cleartext
ldap://ldap.domain.io:389 - cleartext - user: cn=admin,dc=domain,dc=io - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
ldap://ldap.domain.io:389 - cleartext - user: cn=admin,dc=domain,dc=io - not lazy - unbound - open - <local: 10.0.103.100:23295 - remote: 10.0.106.70:389> - tls not started - listening - SyncStrategy - internal decoder
ldap://ldap.domain.io:389 - cleartext - user: cn=admin,dc=domain,dc=io - not lazy - unbound - open - <local: 10.0.103.100:23295 - remote: 10.0.106.70:389> - tls started - listening - SyncStrategy - internal decoder
4
uid=user1,ou=users,dc=domain,dc=io {'uid': ['user1']}
uid=user2,ou=users,dc=domain,dc=io {'uid': ['user2']}
uid=user3,ou=users,dc=domain,dc=io {'uid': ['user3']}
uid=user4,ou=users,dc=domain,dc=io {'uid': ['user4']}
``` 

At this point I can only theorize since I´m lacking the capabilities to do some quick code tests with running servers.
Either it has something to do how Authentik handles the certificates or something else I haven´t seen so far.

As it stand, and hopefully I´m not wrong here, Authentik will always throw the plain pw/bind into the network and never upgrade the connection.

In addition maybe some cert settings would be awesome for testing purposes.

> validate: specifies if the server certificate must be validated, values can be: CERT_NONE (certificates are ignored), CERT_OPTIONAL (not required, but validated if provided) and CERT_REQUIRED (required and validated)

**Comment by rheaalleen** [comment]
After a bit of logging with `from ldap3.utils.log import set_library_log_detail_level, OFF, BASIC, NETWORK, EXTENDED, PROTOCOL` it boils down to this: 

- Only bind() - No Success - Cleartext PW

-  bind() -> start_tls() - Success but PW visible before TLS

- start_tls() - Success - Encrypted

- start_tls() ->  bind() - Success - Encrypted

**Comment by BeryJu** [comment]
The reason the current order is bind then start_tls is because this behaviour varies for each implementation, some require you to be bound before starting TLS for some reason (also doesn't help that I mostly test the LDAP Source against active directory since there's a lot less variety there than with OpenLDAP)

**Comment by rheaalleen** [comment]
So best way would be a checkbox/selection which LDAP provider you use in combination with StartTLS.

Maybe I´ve something missing in my OpenLDAP setup that Authentik wants, not ruling that out but every other StartTLS connection works.

Since AD and OpenLDAP, maybe 389 DS also, are the most used this could be something worth doing.

**Comment by BeryJu** [comment]
I've thought about that in the past, in combination with the default property mappings, making it so an admin just selects the kind of LDAP Server and authentik selects reasonable defaults

**Comment by rheaalleen** [comment]
Would be awesome but aren't the property mappings not up to the user configuration? I can do cn/uid for the DN which again would change the mapping

**Comment by BeryJu** [comment]
The property mappings aren't related to this issue, but are very much customisable. The idea above would simply select a generic default that'll work for the selected LDAP Server, while they can still be changed afterwards by an admin

**Comment by BeryJu** [comment]
Looking into the error further, by default ldap3 will try to refresh the server info when starting TLS, which fails with AD, so calling `connection.start_tls(read_server_info=False)` makes it work with active directory:

```
ldap://mso.beryju.org:389 - cleartext - user: Administrator@mso.beryju.org - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
ldap://mso.beryju.org:389 - cleartext - user: Administrator@mso.beryju.org - not lazy - unbound - open - <local: 10.120.20.57:61015 - remote: 10.120.20.32:389> - tls started - listening - SyncStrategy - internal decoder
ldap://mso.beryju.org:389 - cleartext - user: Administrator@mso.beryju.org - not lazy - bound - open - <local: 10.120.20.57:61015 - remote: 10.120.20.32:389> - tls started - listening - SyncStrategy - internal decoder
```
