### ISSUE TITLE
Is there some way to validate/loging/get token by users' name and passwd?

### ISSUE THREAD

**Issue by MushroomSquad** [goauthentik/authentik#3510]
I need to validate users' by their login and password without authentik authorization window 
Can i do that through openid provider?
In keycloak it was possible but i had other troubles and migrate to authentik

**Comment by BeryJu** [comment]
There are a couple options for this; if this is only for a couple users you can use the OAuth Machine-to-Machine flows that allows to get an OAuth token from credentials

If this is for every user, then it would be easiest to create a small flow (for example identification stage with a configured password stage and then a user_login stage), that can be called via API in a single request and will also return a JWT

**Comment by MushroomSquad** [comment]
> There are a couple options for this; if this is only for a couple users you can use the OAuth Machine-to-Machine flows that allows to get an OAuth token from credentials
> 
> If this is for every user, then it would be easiest to create a small flow (for example identification stage with a configured password stage and then a user_login stage), that can be called via API in a single request and will also return a JWT

thanks you 
i'll try to create that flow

**Comment by MushroomSquad** [comment]
@BeryJu 
i'm sorry for  bothering
i did flow (i think so) 
but i can't uderstand how to call it throu api 
![image](https://user-images.githubusercontent.com/30424265/187871923-458dd764-cb78-4f90-88ea-025484a88b7d.png)

**Comment by BeryJu** [comment]
https://goauthentik.io/developer-docs/api/flow-executor

**Comment by MushroomSquad** [comment]
@BeryJu 

thank you for help 

also
authentik is awesome !!!!

**Comment by jacksgt** [comment]
@MushroomSquad Could you describe the flow you set up? I'm interested in something similar.
