### ISSUE TITLE
Flow policy bindings are rendered in flow diagram as stage policy bindings

### ISSUE THREAD

**Issue by sevmonster** [goauthentik/authentik#3534]
**Describe the bug**
Rather than directing policy deny program flow in the diagram directly to the end state, it instead skip whatever is next in the program flow, whether that is to check a policy or show a stage.

**To Reproduce**
1. Create a flow
2. Create a policy
3. Bind that policy to the flow under *Policy / Group / User Bindings*
4. Create a stage
5. Bind that stage to the flow twice
6. Check the diagram

**Expected behavior**
The flow policy in the diagram should route its *Policy denies* to *End*, skipping both bound stages, but it instead routes it to the second bound stage.

**Screenshots**
Flow stage bindings:
![image](https://user-images.githubusercontent.com/16788697/188538370-8766c160-4dfc-4ab1-a268-9278666569e5.png)
Flow policy bindings:
![image](https://user-images.githubusercontent.com/16788697/188538433-85580039-5357-4bc8-b481-e87c7e810467.png)
Diagram:
![image](https://user-images.githubusercontent.com/16788697/188538725-2d1044ba-5329-45d7-b9d8-cc2218c70559.png)

**Version and Deployment (please complete the following information):**
 - authentik version: gh-main
 - Deployment: docker-compose

**Additional context**
This has been an observable problem for a very long time (as long as I have used authentik) but I guess I just never thought about it once I understood why it was happening.

**Comment by BeryJu** [comment]
Good observation, this has been broken since https://github.com/goauthentik/authentik/commit/d570feffacd4f3e3749a4857da1d4ebe79eff559#diff-9cde612fc95dcddbfad2098007062ab52417f3b80c98f3ee4fc9dbaef59481aa
