### ISSUE TITLE
OIDC group scope? Harbor

### ISSUE THREAD

**Issue by badsmoke** [goauthentik/authentik#3543]
Hello,

i am pretty new to the saml/oidc/ldap material

i am currently testing with authentik, 2022.8.2 and harbor 2.6.0

i would like to have the groups i have in authentik also available in harbor, what do i have to create for this? i assume that i can adapt this for portainer and rancher for example?

thanks already

**Comment by BeryJu** [comment]
The screenshot in the harbor documentation is a bit outdated, you dont have to create anything for this you can just set the groups claim to `groups`

**Comment by badsmoke** [comment]
thanks, 
don't i have to create another group scope on the authentics page?

in the harbor at least it does not look like it would work

**Comment by BeryJu** [comment]
No, the `groups` claim is included in the default `profile` scope, see https://github.com/goauthentik/authentik/blob/main/blueprints/system/providers-oauth2.yaml#L47

**Comment by badsmoke** [comment]
ah cool thanks.


should I automatically see something in the harbor?

i have for example the group maintainer, with a user test.

but in the harbor this group does not exist automatically, and when i add it manually the user test still does not have access.

**Comment by badsmoke** [comment]
everything works now, I just forgot to set the "group claim name"


but the groups are only set when someone has logged in with the corresponding group?

**Comment by BeryJu** [comment]
What do you mean with `has logged in with the corresponding group`?

**Comment by BeryJu** [comment]
Due to the way OIDC works the Groups are only provisioned when the user logs in. I don't know if Harbor has support for something like SCIM or supports OIDC and LDAP at the same time, but that would solve this issue.
