### ISSUE TITLE
Add `x5c` and `x5t`to the `jwks` response

### ISSUE THREAD

**Issue by dcshoes23** [goauthentik/authentik#3555]
**Is your feature request related to a problem? Please describe.**
I am trying to use Authentik as the identity provider for netbird via OAuth2/OIDC

**Describe the solution you'd like**
netbird expects the JWKS endpoint which is `/application/o/<provider name>/jwks/` to have a property for the `x5c`. The `x5c` (X.509 certificate chain) Header Parameter contains the X.509 public key certificate or certificate chain corresponding to the key used to digitally sign the JWS (JSON Web Signature).

**Describe alternatives you've considered**
n/a

**Additional context**
For the OAuth2 Provider, I specified a signing key which populated the `jwks` endpoint response with the following values:
```
{
    "keys": [
        {
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            "kid": "*REDACTED*",
            "n": "*REDACTED*",
            "e": "AQAB"
        }
    ]
}
```

Comparing it to the example here: https://example.eu.auth0.com/.well-known/jwks.json , it is missing the `x5t` and `x5c` properties.

**Comment by braginini** [comment]
NetBird founder here.
That was quick @BeryJu! 
Thank you @dcshoes23 for creating the issue!

We will prepare NetBird-Authentik integration docs once #3556 has been merged.

FYI NetBird repo: https://github.com/netbirdio/netbird

**Comment by BeryJu** [comment]
@dcshoes23 Could you try this build and see if that fixes the issue? https://github.com/goauthentik/authentik/pull/3556#issuecomment-1241039450

**Comment by dcshoes23** [comment]
Tried that build and confirmed the values are there are work!

![image](https://user-images.githubusercontent.com/4748680/189214336-6aec01c9-1cd5-486b-aac9-99883db2426c.png)

**Comment by bohemtucsok** [comment]
> NetBird founder here. That was quick @BeryJu! Thank you for the PR. Thank you @dcshoes23 for creating the issue!
> 
> We will prepare NetBird-Authentik integration docs once #3556 has been merged.
> 
> FYI NetBird repo: https://github.com/netbirdio/netbird

Hi 

When is the Netbird-Authentic documentation expected ????
