### ISSUE TITLE
`userinfo` endpoint missing CORS headers

### ISSUE THREAD

**Issue by dcshoes23** [goauthentik/authentik#3565]
**Describe the bug**
Web application is calling the `/application/o/userinfo/` endpoint from the browser. 

It is failing with the message in the Chrom Debug Console 
```
Access to fetch at 'https://auth.mydomain.com/application/o/userinfo/' from origin 'https://myapp.mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Analyzing the responce with CURL, I see that it is missing the following headers:
```
access-control-allow-credentials: true
access-control-allow-origin: https://myapp.mydomain.com
```

**To Reproduce**
1. Create an OAuth2 provider and set `Redirect URIs/Origins (RegEx)` to `https://myapp.mydomain.com/.*`
2. App logs in and gets token from `https://auth.mydomain.com/application/o/token/` (response has the correct CORS headers)
3. Make GET request to `https://auth.mydomain.com/application/o/userinfo/` with the bearer token 

**Expected behavior**
Response contains proper CORS headers with the origin specified on the provider
```
access-control-allow-credentials: true
access-control-allow-origin: https://myapp.mydomain.com
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.8.2
 - Deployment: Helm

**Comment by BeryJu** [comment]
There are already some CORS headers that are being set on the userinfo endpoint: https://github.com/goauthentik/authentik/blob/main/authentik/providers/oauth2/views/userinfo.py#L96
which allows these things https://github.com/goauthentik/authentik/blob/371f1878a8b3f3e6fad288a6315ed06e4418a0e2/authentik/providers/oauth2/utils.py#L61
so it should work correctly already

**Comment by dcshoes23** [comment]
ya, it's confusing me as well when I look at the code but the request works through curl (copied curl request from Chrom developer tools for the request) I see the user info JSON response and you can see the headers missing:

`/application/o/userinfo/`
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200
< cache-control: no-store
< content-encoding: deflate
< content-type: application/json
< date: Fri, 09 Sep 2022 12:52:32 GMT
< pragma: no-cache
< referrer-policy: same-origin
< strict-transport-security: max-age=63072000
< vary: Accept-Encoding
< vary: Accept-Encoding
< vary: Cookie
< x-authentik-id: 3**REDACTED**2
< x-content-type-options: nosniff
< x-frame-options: DENY
< x-powered-by: authentik
< x-xss-protection: 1; mode=block
< content-length: 209
```

When I try the `/application/o/token/` endpoint, I see these headers:
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 400
< access-control-allow-credentials: true
< access-control-allow-origin: https://nb.mydomain.com
< cache-control: no-store
< content-encoding: deflate
< content-type: application/json
< date: Fri, 09 Sep 2022 12:54:59 GMT
< pragma: no-cache
< referrer-policy: same-origin
< strict-transport-security: max-age=63072000
< vary: Accept-Encoding
< vary: Accept-Encoding
< vary: Origin, Cookie
< x-authentik-id: 3**REDACTED**2
< x-content-type-options: nosniff
< x-frame-options: DENY
< x-powered-by: authentik
< x-xss-protection: 1; mode=block
< content-length: 158
<
```

**Comment by BeryJu** [comment]
The userinfo endpoint only adds those headers with a valid token, as that token is used to figure out which origins are valid

**Comment by dcshoes23** [comment]
The token is valid because I am getting the JSON response with my user info

**Comment by BeryJu** [comment]
oh right, could you check the server container's logs for any mention of CORS? (Maybe also bump the log level to info or debug)

I'll do some testing with this later

**Comment by dcshoes23** [comment]
I have the logs set to trace and don't see anything related to CORS or to the /uerinfo/ endpoint

**Comment by BeryJu** [comment]
When testing locally and sending a request with an Origin header, it works as expected:

Preflight CORS request:
![image](https://user-images.githubusercontent.com/1932513/189480326-f3185652-fb3e-4572-8875-6cd3e0ba5bff.png)

Actual request:
![image](https://user-images.githubusercontent.com/1932513/189480334-10f4e1a0-bb7a-4d54-ae1f-181bc204ba38.png)

Does the curl command generated by chrome have the Origin header set?

**Comment by dcshoes23** [comment]
Good find! Looks like the request headers are missing the `Origin` header. When I add it in the curl request, I get the `access-control-allow-*` headers in the reply. I'll close this bug.

**Comment by dcshoes23** [comment]
looks like the issue was with one of the traefik middlewares that I think TrueCharts has as follows: 
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: ix-traefik
  creationTimestamp: "2022-08-31T21:05:37Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: chain-basic
  namespace: default
  resourceVersion: "9271612"
  uid: 9cff5f39-8138-4c32-bb9e-a1a9b623fe59
spec:
  chain:
    middlewares:
    - name: basic-ratelimit
    - name: basic-secure-headers
    - name: compress
 ```

and here is the `basic-secure-headers` that it refers to (and is messing with the headers)
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: ix-traefik
  creationTimestamp: "2022-08-31T21:05:37Z"
  generation: 5
  labels:
    app.kubernetes.io/managed-by: Helm
  name: basic-secure-headers
  namespace: default
  resourceVersion: "10157815"
  uid: 4966c033-7925-4d6f-ad61-a364d72fe94e
spec:
  headers:
    accessControlAllowMethods:
    - GET
    - OPTIONS
    - HEAD
    - PUT
    accessControlMaxAge: 100
    browserXssFilter: true
    contentTypeNosniff: true
    customRequestHeaders:
      X-Forwarded-Proto: https
    customResponseHeaders:
      server: ""
    forceSTSHeader: true
    referrerPolicy: same-origin
    stsSeconds: 63072000
```

If I remove `basic-secure-headers` from the chain, then everything works.
