### ISSUE TITLE
How can I change the password?

### ISSUE THREAD

**Issue by Dan6erbond** [goauthentik/authentik#3571]
**Describe your question/**
A clear and concise description of what you're trying to do.

I know this sounds like a stupid question, but after some trying I'm starting to think I might have come across an issue instead of simply wrong configuration. But would be happy to be proven wrong!

I'm using the default change password flow (`default-password-change`) to attempt to change my password (and consequently let users do so as well), which works with the inspector enabled - values look correct and password is changed, but if I run the flow directly I get the "Request denied, unknown error" message, and see the following logs:

```json
{"auth_via": "session", "event": "Aborting write to empty username", "host": "auth.example.com", "level": "warning", "logger": "authentik.flows.stage", "pid": 8102, "request_id": "7a3811d538b645b0b86a37e436591dde", "stage": "default-password-change-write", "stage_view": "authentik.stages.user_write.stage.UserWriteStageView", "timestamp": "2022-09-09T21:46:01.348949", "user": "<User: >"}
```

**Relevant infos**
i.e. Version of other software you're using, specifics of your setup

Brave on Windows 11.

**Screenshots**

![image](https://user-images.githubusercontent.com/32235074/189450727-aea70ba9-d013-4eeb-9454-7470c4f50ea5.png)

**Logs**
Output of docker-compose logs or kubectl logs respectively

See above.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.8.2
 - Deployment: helm on DOKS

**Additional context**

None.

**Comment by BeryJu** [comment]
This shouldn't be an issue anymore, this was caused in older versions when directly accessing the flow URL and not via the user settings, which wouldn't preload the flow context with the required variables and as such this error would happen
