### ISSUE TITLE
FR: Ability to disable pagination on UI, either user level or global

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#3573]
**Is your feature request related to a problem? Please describe.**
I would like to have to clicky click UI elements less and do changes more.

**Describe the solution you'd like**
Ability to say to the front end to always show all the things in the list, like under Directory -> Users.

**Additional context**
It's rather frustrating to do clicky click.

**Comment by burner-** [comment]
I totally agree. That pagination just eat soul and zest for life.
