### ISSUE TITLE
Different behaviour on "With inspector" and normal login -Flow: TOTP forcefully wants to be setup even though its already setup rendering the 2FA useless

### ISSUE THREAD

**Issue by theoneandonly-vector** [goauthentik/authentik#3580]
**Describe the bug**
Since a recent Update 

-> very important:
This issue only happens on real logins and on "Execute flow" -> "Normal" BUT using "With inspector" will do everything correctly, just as before the update.

**To Reproduce**
1. Try to login normally -> Issue occurs!
2. Try to login using "Execute flow" -> "With inspector" -> no Issue!

**Expected behavior**
The same things happen on "Execute flow" -> "With inspector" and normal login.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.8.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Can you post the diagram of the flow in question?

**Comment by theoneandonly-vector** [comment]
![image](https://user-images.githubusercontent.com/10380051/189691665-f38d4719-066a-4e33-a52c-26a8f6a19e9d.png)

**Comment by BeryJu** [comment]
The TOTP Setup stage should not be bound directly to an authentication flow. While in previous versions the TOTP stage would simply finish and continue with the next stage when the user already has a device, it was never intended to be bound directly to an authentication flow. Instead, in the Authenticator validation stage, you can configure a flow to run if the user does not have any matching device.

**Comment by theoneandonly-vector** [comment]
This is very bad for my use-case.. I actually need to be able to force the user once to setup a TOTP-device on first login!, while also let him setup a webauthn device first. Because the way the user connects to RDP (only using guacamole) he cannot use his webauthn-device inside his RDP session and I don't want to force him to use TOTP and Webauthn before.. so I do match the RDP-Server per IP-Address so from there you automatically will be asked for the TOTP instead of the Webauthn.

**Comment by theoneandonly-vector** [comment]
so the update destroyed my use-case?

**Comment by BeryJu** [comment]
You can still use two authenticator validation stages, one for TOTP and one for WebAuthn show those conditionally with policies

**Comment by theoneandonly-vector** [comment]
but how can I make a condition to only set TOTP up when not coming from an RDP-IP and not ask for it (because I already ask for webauthn?

**Comment by theoneandonly-vector** [comment]
I found a way.. (really had to much sun yestarday..) still I dont' get why when I use the "inspector"-feature it still works like before.

**Comment by theoneandonly-vector** [comment]
ok.. I thought it was fixed.. but still the same problem occurs..

**Comment by theoneandonly-vector** [comment]
so this policy only seems to work when usign the inspector:
```
auth = ak_user_has_authenticator(request.user,"totp")

if auth:
    return False
else:
    return True
```

**Comment by theoneandonly-vector** [comment]
whatever I try.. it always works as expecte diwht the inspector but never when login in normally

**Comment by theoneandonly-vector** [comment]
sometimes it even has a wrong order and showing a later phase before another one..

**Comment by BeryJu** [comment]
https://goauthentik.io/docs/policies/expression#variables use `request.user` with caution in policies that bound to flows

**Comment by theoneandonly-vector** [comment]
really weird it worked before..
but this fixed it "context['pending_user']" instead of "request.user"
