### ISSUE TITLE
I replaced the favicon but it sometimes shows the original one (cleared cache and tried on multiple devices)

### ISSUE THREAD

**Issue by theoneandonly-vector** [goauthentik/authentik#3584]
**Describe the bug**
I replaced the favicon but it sometimes shows the original one (cleared cache and tried on multiple devices)

**To Reproduce**
put the favicon in the /media folder.

**Expected behavior**
it should always display my favicon

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.8.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/commit/f68ed3562e7a1034de78420494bafb50673b3b07 will be fixed with 2022.9
