### ISSUE TITLE
Add default values to Prompt, options for text and Interpret would be ideal. 

### ISSUE THREAD

**Issue by ithan** [goauthentik/authentik#3600]
**Is your feature request related to a problem? Please describe.**
Currently, you can't set the default value of an input, only the placeholder. 

**Describe the solution you'd like**
Under stages/prompts, there should be an option for "value", not only a placeholder, that allows you to interpret code like in the placeholder. 
( In the future it would be nice if the placeholder script could access the return value of the suggested new script, but for now, having them separated would be enough )

**Describe alternatives you've considered**
An alternative that I can think would be to be able to write your own prompts component, but that sounds more complicated 

**Additional context**
Currently, if you want to have something like password suggestions, or autofill some data based on already known data ( like the current date, or the IP of the request ), you can only do it for placeholders and not values.

**Comment by BeryJu** [comment]
This is possible since a couple of versions, in the prompt the placeholder can be configured to be interpreted as an expression
