### ISSUE TITLE
Social login (Discord) redirects back to login page: Could not retrieve token

### ISSUE THREAD

**Issue by LeehamElectronics** [goauthentik/authentik#3605]
**Question:**
Hi, I'm trying to set up Authentic with an OAuth2 login with Discord. I have managed to setup Authentic with Nginx Proxy Manager which works well with a basic username and password. I also set up Discord as an OAuth login using the guide here:
https://goauthentik.io/integrations/sources/discord/

The Discord OAuth also works fine (no errors when logging in). However, people who log in with Discord are just redirected back to Authentik instead of being taken to the web service Application, which does make sense as their Discord user account has not been enrolled(?) in Authentik as of yet _(I think that's the terminology, I'm pretty new to Authentik)_ 

My question is, how do you enrol a user that has logged in with Discord _(or any social OAuth)_ to give them access to an Application? I have looked through the Authentik web panel and can't figure it out. 
I also tried logging in with a test Discord account. I can't see the Discord account email address or any new accounts showing up under the Users tab in Authentik, so I'm guessing that I need to enable some way of registering users that log in with OAuth, but I can't see anything on the wiki about that.

**Screenshot:**
When logging in with Discord I get redirected back the Authentik page `auth.mypublicdomain.com` instead of `service.mypublicdomain.com`, however using the normal username and password works just fine.
![image](https://user-images.githubusercontent.com/51737378/190847438-5cc8a412-61cd-4522-a94c-a94caef38b45.png)

**Relevant infos**
Docker-compose install of Authentik on an Ubuntu headless VM in ESXi.  Using Nginx Proxy Manager.

**Sidenote:**
And as a side note, would it be possible to automatically allow Discord logins to have access to a webpage but only if the Discord account in question is in a specified guild or has a specified role within that guild? That would be amazing if it's possible. 

**Conclusion:**
I believe the terminology I'm looking for is OAuth user enrollment, but I could be wrong. Whether it's automatic enrollment or not I don't really mind, I just need some way for it to work with Discord users. Thanks in advance for any tips you have.

**Comment by LeehamElectronics** [comment]
update from the author:

> by default all users have access to all applications, to see the discord users open the goauthentik.io folder, there should be a sources folder and then a discord folder where the users will be
> that folder will show up after a user has logged in with discord

I have tried looking in that folder but it is empty, even after logging in with Discord OAuth.
![image](https://user-images.githubusercontent.com/51737378/192076034-b1258066-6143-403c-b04e-861e3fa911f1.png)

The issue must lie elsewhere then because when I press the Discord button and log in with Discord, I am simply redirected back to the Authenik login screen. I’m guessing the OAuth login process is failing then? I assume that’s why the folder is not there. I don’t know what else to try, Discord doesn’t indicate that there are any OAuth errors at all, it allows login and redirects back to `auth.authtikdomainexample.com` so everything seems okay from my viewpoint. What else could be going wrong here?
Thanks

**Comment by LeehamElectronics** [comment]
It looks like the OAuth process must be failing, I checked the logs and I am getting a `Authentication Failure Could not retrieve token`
Here is the full error:
```
{"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 272803, "remote": "127.0.0.1", "request_id": "REDACTED", "runtime": 14, "scheme": "http", "status": 204, "timestamp": "2022-09-26T22:19:57.015221", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}
{"auth_via": "unauthenticated", "event": "/if/flow/default-authentication-flow/", "host": "auths.REDACTED.com.au", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 272803, "remote": "192.REDACTED", "request_id": "8a0236f39a9a4f40ab9d11e8c4258bd3", "runtime": 24, "scheme": "https", "status": 200, "timestamp": "2022-09-26T22:19:56.158417", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/flows/-/default/authentication/", "host": "auths.REDACTED.com.au", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 272803, "remote": "192.REDACTED", "request_id": "acfd5c49201846c9838470ec76fab4de", "runtime": 16, "scheme": "https", "status": 302, "timestamp": "2022-09-26T22:19:56.120594", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/source/oauth/callback/discord/?code=REDACTED&state=REDACTED", "host": "auths.REDACTED.com.au", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 272803, "remote": "192.REDACTED", "request_id": "0adb9c1160104REDACTED", "runtime": 719, "scheme": "https", "status": 302, "timestamp": "2022-09-26T22:19:56.087189", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "Authentication Failure", "host": "auths.REDACTED.com.au", "level": "warning", "logger": "authentik.sources.oauth.views.callback", "pid": 272803, "reason": "Could not retrieve token.", "request_id": "0adb9c1160104c67REDACTED", "timestamp": "2022-09-26T22:19:56.079412"}
```
Thanks

**Comment by matmair** [comment]
I am seeing the same error with Azure AD

**Comment by LeehamElectronics** [comment]
> I am seeing the same error with Azure AD

Did you find a solution? Do you see a sources folder under goauthentik.io? @matmair

**Comment by matmair** [comment]
I switched back to keycloak for now.

**Comment by matmair** [comment]
@BeryJu this seems to be a bug, the problem persists with Azure AD - the state is passed but not recognised by authentik. What kind of info do you need for debugging? I have multiple production systems from whom I can pull logs.
It used to work till end of july.

Log on server:
![image](https://user-images.githubusercontent.com/66015116/206695887-f81882eb-aeed-470b-88c7-2fd01db63184.png)


Response header:
![image](https://user-images.githubusercontent.com/66015116/206695486-9ea8f6a7-776a-4244-9d04-ee51d3581bea.png)

**Comment by matmair** [comment]
@BeryJu I do not have access to the problematic instance right now - I will try again once I do on Monday.
I see the headers in the POST response, I have an extension installed that logs all oAuth traffic.

**Comment by BeryJu** [comment]
fair enough, I was thrown off a bit by the screenshot above making the headers look like XML

**Comment by LeehamElectronics** [comment]
> @BeryJu I do not have access to the problematic instance right now - I will try again once I do on Monday. I see the headers in the POST response, I have an extension installed that logs all oAuth traffic.

Any updates on this? I'm still lost on how to get this working.

**Comment by matmair** [comment]
I can not reproduce it reliably, it sometimes works for some users. We are actually looking into our AD tenant config right now - my MSP thinks the problem lies there.

**Comment by LeehamElectronics** [comment]
Solved by reinstalling Authentik in a clean setup with latest update, I have no idea what was causing the issue. I will close this for now.

**Comment by BeryJu** [comment]
In the App registration, under `API permissions`, try adding the Microsoft Graph permission for `User.Read`, and granting admin consent for the organisation

**Comment by rootd00d** [comment]
@BeryJu Thanks for the follow-up!   Seems like the app registration had that out of the box --
![image](https://user-images.githubusercontent.com/7344985/219647630-05d6aefd-17c4-44c3-91ca-4bf1fcae9c5b.png)

The other two were added when I added some optional claims, hoping that might do some "magic" --
![image](https://user-images.githubusercontent.com/7344985/219647818-40dc6a8c-55ab-439b-bef8-cc6da5ca7dfc.png)

**Comment by rootd00d** [comment]
There seems like more of it, but I don't see any new revelations --
```
{"auth_via": "unauthenticated", "client_id": "8856ca76-482b-4a2e-966e-824e33c8952d", "event": "redirect args", "host": "<REDACTED>", "level": "info", "logger": "authentik.sources.oauth.clients.base", "pid": 21, "redirect_uri": "https://<REDACTED>/source/oauth/callback/azure-ad/", "request_id": "5b0ec3a476034640be25ff2cfd3d968d", "response_type": "code", "scope": "https://graph.microsoft.com/User.Read openid", "source": "azure-ad", "state": "jb5HTWX56DEK64pgpR8VmPCRt3Zgb3PO", "timestamp": "2023-02-17T15:41:05.725700"}
{"auth_via": "unauthenticated", "event": "/source/oauth/login/azure-ad/", "host": "<REDACTED>", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "<REDACTED>", "request_id": "5b0ec3a476034640be25ff2cfd3d968d", "runtime": 34, "scheme": "https", "status": 302, "timestamp": "2023-02-17T15:41:05.728888", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "Unable to fetch access token", "exc": "HTTPError('401 Client Error: Unauthorized for url: https://login.microsoftonline.com/<REDACTED>/oauth2/v2.0/token')", "host": "<REDACTED>", "level": "warning", "logger": "authentik.sources.oauth.clients.oauth2", "pid": 21, "request_id": "be189977258b4cf1868c0062973b828e", "response": "401 Client Error: Unauthorized for url: https://login.microsoftonline.com/<REDACTED>/oauth2/v2.0/token", "timestamp": "2023-02-17T15:41:07.509199"}
{"auth_via": "unauthenticated", "event": "Authentication Failure", "host": "<REDACTED>", "level": "warning", "logger": "authentik.sources.oauth.views.callback", "pid": 21, "reason": "Could not retrieve token.", "request_id": "be189977258b4cf1868c0062973b828e", "timestamp": "2023-02-17T15:41:07.509496"}
{"auth_via": "unauthenticated", "event": "/source/oauth/callback/azure-ad/?code=0.AUYA3i3wXyEwB0WRgnGZpmsSWnbKVogrSC5Klm6CTjPIlS1GAAA.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wUA9P8kid__k4CO6A1ELHF1vKEVomnCJpN1DyPQpyBLVh6xe2Bnde1K-aIFvWsxUVCIwJGUCHaH0SRDidSZjvJkTBefY9vt_4i6VEMOk3nFiXknfy6yJa-JDsgJJ11drDYRSZdFs5_Q4fDkaSp6i84MRn5O6iewbkr5VbGLDaIWV_na8ZE7ba663XrR9eiXx5tQD4yuAHb2tqSY8X1_aezkIc0Ws7yqBW_qoT57pcP-BkrstEtp-BsAEIJ5X2OezYkaZ8eNe4pCtKmaaHUBWgljOKqfbmnvd8Mur3wfWUNirY6Dd9DVnMPfe_cCL4hTuLUf3EWXFL2fFgcqJXp9W_P9dicVx5OseaqIQf3dub-ykE7cdtY7ZHQ6UM7BfTbDqM4qzVKujLKh9G-2lEPOPekF6mLaABWzLlop6WK-55KxzmYfC5yiVHwXRwU6mmJgR8igXyxCmq40G2eFwIGnJOSZoJ9e1KCUdyrEbjTmGezm2ZJ8HMgF6uhv38-j9qz7B4SK7wk21o7fNU4_lyo5XeiBDuYW4Q7OZI7n8fjhptizsrO7KTJmZHrHwnKXwp0xPIoBVNWWgFAFi56-dLeiSjayv-JYgZQmCp7bdH_AzC_-oy6F28QUTamiBLiDUSfIeRzl3FlDYmxhm3lACp9adsenCxqvImjFm9Fc2U1yall0GrBcDPp24zpBzLwB914t2PKwhoHpybfGtNfSa7XT7Bp2UcCUd2wJHvH6X2oW3nnHYSHDCYmfMl9VEtp02DqJzfrb&state=jb5HTWX56DEK64pgpR8VmPCRt3Zgb3PO&session_state=2ca1d81c-6037-4730-8cde-4c40a9dc8209", "host": "<REDACTED>", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "<REDACTED>", "request_id": "be189977258b4cf1868c0062973b828e", "runtime": 766, "scheme": "https", "status": 302, "timestamp": "2023-02-17T15:41:07.515308", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/flows/-/default/authentication/", "host": "<REDACTED>", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "<REDACTED>", "request_id": "0af27a975e0141da8a1fe3675fdf1768", "runtime": 27, "scheme": "https", "status": 302, "timestamp": "2023-02-17T15:41:07.549562", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/if/flow/default-authentication-flow/", "host": "<REDACTED>", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "<REDACTED>", "request_id": "fd1b80c3a98844bfb24fb4bc80027a1e", "runtime": 53, "scheme": "https", "status": 200, "timestamp": "2023-02-17T15:41:07.609130", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"event":"/static/dist/assets/fonts/RedHatText/RedHatText-Regular.woff2","host":"<REDACTED>","level":"info","logger":"authentik.router","method":"GET","remote":"<REDACTED>","runtime":"1.395","scheme":"http","size":28169,"status":200,"timestamp":"2023-02-17T07:41:07-08:00","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"event":"/static/dist/assets/fonts/RedHatDisplay/RedHatDisplay-Medium.woff2","host":"<REDACTED>","level":"info","logger":"authentik.router","method":"GET","remote":"<REDACTED>","runtime":"1.997","scheme":"http","size":28661,"status":200,"timestamp":"2023-02-17T07:41:07-08:00","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"event":"/static/dist/assets/fonts/webfonts/fa-solid-900.woff2","host":"<REDACTED>","level":"info","logger":"authentik.router","method":"GET","remote":"<REDACTED>","runtime":"5.589","scheme":"http","size":79100,"status":200,"timestamp":"2023-02-17T07:41:07-08:00","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/default-authentication-flow/?query=", "host": "<REDACTED>", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 21, "remote": "<REDACTED>", "request_id": "7e30e866ee89441e8def8210e09acb9e", "runtime": 55, "scheme": "https", "status": 200, "timestamp": "2023-02-17T15:41:07.875736", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
{"event":"/static/dist/assets/fonts/RedHatText/RedHatText-Medium.woff2","host":"<REDACTED>","level":"info","logger":"authentik.router","method":"GET","remote":"<REDACTED>","runtime":"0.729","scheme":"http","size":29049,"status":200,"timestamp":"2023-02-17T07:41:07-08:00","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"}
```

**Comment by rootd00d** [comment]
OMG, I'm an idiot -- I copied the "Secret ID" and not the actual secret.  That's a first for me.
![image](https://user-images.githubusercontent.com/7344985/219702731-a201e5b2-7833-4e0e-bf60-684110c70c5a.png)

Works great now!  Sorry for the distraction... :-(

Maybe there's a place in a FAQ regarding this error -- `401 Client Error: Unauthorized for url: https://login.microsoftonline.com/<REDACTED>/oauth2/v2.0/token`

This literally just means the app registration credentials are invalid, I guess.

**Comment by arpanghosh8453** [comment]
I am having the same issue with Discord Oauth. it just redirects back to the initial flow without authorizing. Any solutions for this?

**Comment by loveablecabbage** [comment]
> I am having the same issue with Discord Oauth. it just redirects back to the initial flow without authorizing. Any solutions for this?

@arpanghosh8453 Did you ever find a solution to this?

**Comment by GD-Dal** [comment]
Did you? I'm seeing the exact issues with both Google and Github Integration
