### ISSUE TITLE
SAML Schema?

### ISSUE THREAD

**Issue by dragon2611** [goauthentik/authentik#3621]
Trying to setup an intergration using SAML the guide shows but it's not matching on the username

http://schemas.goauthentik.io/2021/02/saml/username

should this return data rather than notfound when visted with a browser?  (I.e is the schema acutally there?)

**Comment by BeryJu** [comment]
This URL (like all the other URLs like http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress) are used as a unique identifier and are on purpose not serving any data
