### ISSUE TITLE
FR: Proper parent groups

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#3622]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have a user belong to the parent group, without having to also include that.

**Describe the solution you'd like**
Create a group a with a parent group b, and then add user a to group b. It should inherit group a.

**Additional context**

Similar requests exist for LDAP: https://github.com/goauthentik/authentik/issues/3284
https://github.com/goauthentik/authentik/issues/1278

**Comment by BeryJu** [comment]
as the group system within authentik works like this now I'll close this, exposing this via LDAP is tracked via #2417
