### ISSUE TITLE
prompt=select_account

### ISSUE THREAD

**Issue by martijndierckx** [goauthentik/authentik#3636]
**Describe your question/**
When I click the microsoft social login button, I want the option to switch between different accounts.
Now, when I'm logged in on MS side, I'm automatically logged in with that account on Authentik as well.

**Relevant infos**
Microsoft provides the prompt=select_account option for this in its OAuth flow.
https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.09
 - Deployment: docker-compose, portainer

**Comment by BeryJu** [comment]
you can include `?prompt=select_account` in the authorize URL in the source settings, the URL will be built correctly with those parameters preserved

**Comment by martijndierckx** [comment]
Works!
