### ISSUE TITLE
Social login default

### ISSUE THREAD

**Issue by martijndierckx** [goauthentik/authentik#3638]
**Describe your question/**
I only support Microsoft social login on my Authentik, not a manual user-password flow nor other social logins. Is it possible to automatically redirect from the login page to the social login?

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.09
 - Deployment: docker-compose, portainer

**Comment by selmernoid** [comment]
I'm facing a similar issue.

Your case might be solved in that way:

- open Flows
- open default-authentication-flow if you using the default settings, otherwise your main flow in Authentication section
- Stages
- edit Identification Stage
- Unselect 'authentik Built-in'
- Select your social login there

This should works

**Comment by martijndierckx** [comment]
Still shows the login form on my end.
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/3973630/192473409-96f745fe-48b2-4f5e-a6f1-2e944eb8e294.png">

**Comment by martijndierckx** [comment]
If I deselect the username/email user fields, I get this: but I want to skip the login screen entirely:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/3973630/192479983-1f2794b4-f01f-4cd9-9d5c-863603797af8.png">

**Comment by RobinBeismann** [comment]
I'm interested in this also. @martijndierckx - did you find anything out?

**Comment by martijndierckx** [comment]
Nope :-(
________________________________
Van: Robin Beismann ***@***.***>
Verzonden: Thursday, February 2, 2023 9:08:32 PM
Aan: goauthentik/authentik ***@***.***>
CC: Martijn Dierckx ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [goauthentik/authentik] Social login default (Issue #3638)


I'm interested in this also. @martijndierckx<https://github.com/martijndierckx> - did you find anything out?

**Comment by RobinBeismann** [comment]
I was thinking to bypass this by forwarding the default login page to the IdP login page via Traefik, but I'd prefer a built in solution..

**Comment by RobinBeismann** [comment]
`
      - "traefik.http.middlewares.forward-idp-replacepathregex.replacepathregex.regex=^/if/flow/default-authentication-flow/(.*)"
      - "traefik.http.middlewares.forward-idp-replacepathregex.replacepathregex.replacement=/source/oauth/login/azuread/$$1"`
      
There we go.

**Comment by RobinBeismann** [comment]
There we go.

```
- "traefik.http.middlewares.forward-idp-replacepathregex.replacepathregex.regex=^/if/flow/default-authentication-flow/(.*)"
- "traefik.http.middlewares.forward-idp-replacepathregex.replacepathregex.replacement=/source/oauth/login/azuread/$$1"
```

**Comment by BeryJu** [comment]
I think it might be a reasonable assumption that when only a single source is selected in an identification stage to auto redirect to that source

**Comment by brotherko** [comment]
This issue seems to be fixed. I have the same single source setup and it gets redirected to Github directly. Pretty cool :)!

**Comment by BeryJu** [comment]
Oh yeah, I forgot to close this issue with the PR, added by #5583
