### ISSUE TITLE
Logoff Nginx

### ISSUE THREAD

**Issue by martijndierckx** [goauthentik/authentik#3639]
**Describe your question/**
I use the Passtrough proxy template provided by Authentik in Nginx Proxy Manger to make sure some of my apps are shielded by Authentik login. Works like a charm.
Is it possible to create a route in that config which triggers a logoff, deleting the auth cookie(s)?

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.09
 - Deployment: docker-compose, portainer

**Comment by BeryJu** [comment]
See https://docs.goauthentik.io/docs/providers/proxy/#logging-out, also this behaviour was improved in 2023.10 (#7099)
