### ISSUE TITLE
FR: Ability to have OAuth Sources w/o enrollment

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#3683]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I only want to allow linking existing accounts to things like Google, but not allow enrollment via any of those.

**Describe the solution you'd like**
Do not require enrollment flow on the OAuth source.

**Comment by BeryJu** [comment]
This has actually been supported since a long time, just the web interface didn't allow to set empty flows
