### ISSUE TITLE
custom email template is not loading, 

### ISSUE THREAD

**Issue by codeArtisanry** [goauthentik/authentik#3692]
![image](https://user-images.githubusercontent.com/87218847/192747802-5ad9b7d2-076b-42ae-9d0a-a3ab6704258f.png)

i put `custom-templates` folder next to docker-compose file, 
its showing in admin console in staging, but when i send email is not loading and showing above img.

**Comment by MB175** [comment]
I might have a related issue, if im trying to use a custom template I get the following error page in the flow with no  additional info on worker or server.
<img width="682" alt="Bildschirm­foto 2022-11-01 um 17 20 01" src="https://user-images.githubusercontent.com/57674787/199286909-c23461d8-02c1-41ff-a630-3c2f0329588b.png">
