### ISSUE TITLE
Documentation doesn't mention directories where Authentik persists data

### ISSUE THREAD

**Issue by thibaultamartin** [goauthentik/authentik#3693]
**Is your feature request related to a problem? Please describe.**

The documentation doesn't mention what are the important directories authentik relies on, either for the server or workers.

They can somehow be guessed from the docker-compose.yml file linked in https://goauthentik.io/docs/installation/docker-compose, but there is no explanation regarding what the volumes are used for.

**Describe the solution you'd like**

Having a list of all the directories where Authentik may persist data, what data is persisted, and under which condition would be very useful.

**Describe alternatives you've considered**

Not using volumes, fiddling with Authentik, recreating the container, and trying to find what is missing :D

**Comment by BeryJu** [comment]
authentik itself doesn't store any persistent data itself, everything is stored in PostgreSQL. Some persistent-ish data is stored in redis, but redis does not need to be persistent.

**Comment by thibaultamartin** [comment]
Doesn't Authentik rely on `/media` (I imagine for the tenant's logo?), `/certs` for SAML certificates and `/templates` (not sure what it's used for)?

**Comment by BeryJu** [comment]
All of those are optional and simply created by default on compose setups

- `/media` is indeed used to store icons and such, but not required, and if not mounted, authentik will allow you to set a URL to icons in place of a file upload
- `/certs` is used for authentik to import external certs, which in most cases shouldn't be used for SAML, but rather if you use authentik without a reverse proxy, this is used for the lets encrypt integration
- `/templates` is used for custom email templates, and as with the other ones fully optional
