### ISSUE TITLE
Add ability to choose a default authentication flow for a provider

### ISSUE THREAD

**Issue by rissson** [goauthentik/authentik#3694]
**Is your feature request related to a problem? Please describe.**

Currently, choosing a default authentication flow for a provider/app involves monkeying around with policies to make sure that only one of them passes for said provider/app.

**Describe the solution you'd like**

As it is done for authorization flows, add an option to choose an authentication flow for a provider.

**Describe alternatives you've considered**

No alternative have been discussed yet.

**Additional context**

This feature was discussed on [Discord](https://discordapp.com/channels/809154715984199690/809154716507963434/1024684056979456000).

**Comment by rissson** [comment]
I would love to contribute to this project. As this has been discussed with @BeryJu already, I'll try to implement this. Anything specific I should be aware of?

**Comment by chriscarpenter12** [comment]
How do you use the policies to pick a different flow besides the `default-authentication-flow`?

**Comment by fluc-tus** [comment]
I'm asking myself the exact same question right now. Real hard to get by some information on that. I would really like to select different authentication flows based on the app.

**Comment by jarrettprosser** [comment]
I'd find this very useful too. In my case I have an Azure AD source, and I want users logging into this application to get redirected to Azure immediately without requiring them to click the Microsoft logo.
