### ISSUE TITLE
Authentik doesn't seem to say it supports iss claim in well-known claims_supported field

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#3702]
**Describe the bug**
It seems that Authentik doesn't support claim iss, aka Issuer in OpenID Connect, which seems to be required by spec for validation.

**To Reproduce**
1. Create a OpenID Connect app and provider
2. Click on the provider and go to the well-known openid config url
3. Scroll down to supported_claims
4. See that there is no iss.

**Expected behavior**
I expected it to be supported as the coming sso support in Dendrite will not work without.

**Version and Deployment:**
 - authentik version: 2022.9.0
 - Deployment: Helm

**Additional context**
https://openid.net/specs/openid-connect-discovery-1_0.html#IssuerDiscovery

```
time="2022-09-29T04:27:16.010089840Z" level=error msg="Failed to get SSO authorization URL" error="claim \"iss\" is not supported in \"https://id.<snip>.fi/application/o/dendrite/.well-known/openid-configuration\"" req.id=IV41Z9y3RmoT req.method=GET req.path=/_matrix/client/r0/login/sso/redirect/authentik
```
https://github.com/matrix-org/dendrite/blob/698a75ce45cf71758f1df2797f17d288aa4f2e62/clientapi/auth/sso/oidc.go#L173

**Comment by tommie** [comment]
Hi, I'm the author of the referenced Dendrite PR. This is a question about the OIDC discovery: https://openid.net/specs/openid-connect-discovery-1_0.html

`claims_supported` is only marked recommended in the spec:

> RECOMMENDED. JSON array containing a list of the Claim Names of the Claims that the OpenID Provider MAY be able to supply values for. Note that for privacy or other reasons, this might not be an exhaustive list.

The code I added is just a sanity check to fail a provider as early as possible. For something as benign as `iss` and `sub` (the two I check for), I don't see why it/they wouldn't be listed, but Authentik is definitely spec compliant as-is. I'd still recommend making the list complete as e.g. Google's: https://accounts.google.com/.well-known/openid-configuration

**Comment by BeryJu** [comment]
The reason why the list only has `sub` currently is because all of the claims are generated just-in-time using expressions, so authentik can't know in advance which claims those expressions will return, and the return value of them may depend on user logging in.

However it is indeed true that there's a lot more claims that are hardcoded and always set than just `sub`
