### ISSUE TITLE
Email with - in

### ISSUE THREAD

**Issue by dragon2611** [goauthentik/authentik#3703]
**Describe the bug**
Logging in using an AzureAD user to an openID enabled app (netbird) with an email address that contains a - (Hyphen) results in a 401 error.

Netbird is configured in authentik with the subject mode "Based on the Users's Email"

On inspecting the JWT token the "sub" field is blank for the user whos email address contains a - (hypen), Inspecting the token on another account whos email address does not contain a - shows the sub field as being populated with the users email address.

**To Reproduce**
Setup an Oauth enabled application to use the the email address as the subject mode,
Try logging in with a user who has a - character in their email address

**Expected behavior**
sub: field in JWT to be populated with the users email address.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.09
 - Deployment: Docker-Compose

**Additional context**
User had SSO'd from AzureAD.

**Comment by BeryJu** [comment]
I'm not able to reproduce this
![image](https://user-images.githubusercontent.com/1932513/193359473-e9c77df2-f6c9-4403-831a-2b3e409ecc25.png)
![image](https://user-images.githubusercontent.com/1932513/193359490-35183aa1-a46d-463a-9a30-e86e2347eaaf.png)
![image](https://user-images.githubusercontent.com/1932513/193359517-2f4d47a3-2837-47d1-baf2-ba438b8987d8.png)

**Comment by dragon2611** [comment]
Apolagies, this is user error, Turns out the account I was trying to sign-in with didn't have an email address accociated with it.
Because it was user@domain I never thought to check this.
