### ISSUE TITLE
LDAP integration fails with LDAPInvalidCredentialsResult - 49 - invalidCredentials 

### ISSUE THREAD

**Issue by RogerSik** [goauthentik/authentik#3704]
**Describe the bug**
LDAP integration setup with authentik (kubernetes) + OpenLDAP. It fails with 

![29_11-02-38](https://user-images.githubusercontent.com/165814/192989556-f6f16725-8330-4438-9fa4-817fb6dae71f.png)

But I can use this user to login over phpldapadmin and other web applications.

**Expected behavior**
Working LDAP integration or somehow more information why / where it is failing. 

**Logs**
Output of docker-compose logs or kubectl logs respectively

* worker container shows no new log when running openldap sync.
* web container shows nothing useful (see below)

**Version and Deployment:**
 - authentik version: 2022.9.0
 - Deployment: helm

**Comment by RogerSik** [comment]
In attach the configuration. 
![29_11-05-43](https://user-images.githubusercontent.com/165814/192990326-9fc077fe-cc2a-4c5a-9612-223df754266b.png)
![29_11-05-54](https://user-images.githubusercontent.com/165814/192990331-1bf8e220-0939-4e8b-86e9-03a7543af585.png)
![29_11-06-02](https://user-images.githubusercontent.com/165814/192990336-a92392b4-4996-4d44-a213-a85d69ba9dce.png)

**Comment by RogerSik** [comment]
Is ther a way to execute *ldapsearch* on the authentik kubernetes pods?

**Comment by BeryJu** [comment]
You could exec into the pod as root and apt-get install it, but also you might want to re-create this issue as the tracing logs from above include session cookies that shouldn't be shared (the trace log level should only be used in very rare cases as they can include things like this, but that should also be documented better)

**Comment by RogerSik** [comment]
@BeryJu is this critical for an empty instance which can be deleted and recreated after this issue is solved? 

How can exec as root? With
```
kubectl exec --stdin --tty authentik-worker-7d77566d8d-qhdml -- /bin/bash
```
im the user authentik and with su there is a password asked.

**Comment by RogerSik** [comment]
The tracing logs is now deleted, thanks for the hint. :)

**Comment by BeryJu** [comment]
Added a note about the logs here https://goauthentik.io/docs/installation/configuration#authentik_log_level

The more critical part in what you posted is that there were some other cookies in there for other applications, and editing the issue leaves a history that anyone can look at, so if you don't mind I'll delete this issue

For exec, I misremembered and though kubectl allowed to exec as a user, but only docker directly allows that

Regardless, you could create a temporary pod with an ubuntu image and install anything you want to test on there

**Comment by RogerSik** [comment]
@BeryJu i deleted the older version but if you are able to read it, im fine that you delete this issue. 

> Regardless, you could create a temporary pod with an ubuntu image and install anything you want to test on there

Will do this 👍

**Comment by BeryJu** [comment]
TIL that you can delete the older version, and I can no longer read it both logged in and logged out 🎉

**Comment by RogerSik** [comment]
Found the issue with a ubuntu container and ldapsearch

```
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
```

the issue was that our (new) kubernetes cluster has their own ip range which wasn't in our firewall allowed to connect the ldap server.
