### ISSUE TITLE
Enhance compatibility with KeePassXC

### ISSUE THREAD

**Issue by t-aus-m** [goauthentik/authentik#3716]
**Is your feature request related to a problem? Please describe.**
I am using https://keepassxc.org/ as a password manager. The issue is that KeePassXC's browser extension does not recognize the input fields of the login page, so that the automatic filling in of credentials does not work.

**Describe the solution you'd like**
I would suggest to enhance the compatibility of the login page in a away that KeePassXC or password management software in general could more easily pick up the fields as username and password fields. Since I am not really into web development and have no clear understanding of how the KeePassXC browser extension works, I can not give clear steps on what needs to happen to enhance the compatibility.

**Additional context**
This is how the view for picking user-defined fields looks like with Authentik
![grafik](https://user-images.githubusercontent.com/12219297/193464772-feff6654-e9c6-49e0-8db6-7bb1bef19a18.png)

...and this is how it looks with a service that is properly supported by the KeePassXC extension (https://funkwhale.audio/)
![grafik](https://user-images.githubusercontent.com/12219297/193464928-adcb0279-bb7d-4f95-8fc3-2429a0679f2c.png)

**Comment by BeryJu** [comment]
you can enable "Compatibility mode" in the flow settings which increases compatibility with password managers

**Comment by t-aus-m** [comment]
That solves the issue, thanks for pointing it out. Just out of curiosity: What is the downside of using compatibility mode?

**Comment by cmorty** [comment]
@BeryJu : I want to second @t-aus-m: Are there drawbacks, and if not: Why isn't it turned on by default? A quick dive into the code revealed that this options only seems to set  `ShadyDom`:
https://github.com/goauthentik/authentik/blob/841c13ed77e6835339fc168286edd984149d9a6f/authentik/core/templates/if/flow.html#L11-L13
If I interpret things correct, this however hinders the inspector to do its work, right?

Independent of whether this should be turned on by default, I'd suggest removing the hint at mobile devices in the doc and add that it is not compatible with the inspector. I'm willing to make a PR. I have no insight in this project beside being a user, though.
https://github.com/goauthentik/authentik/blob/36cbc44ed64b0d94f822cd318078dab9e583b401/authentik/flows/migrations/0019_alter_flow_background_squashed_0024_alter_flow_compatibility_mode.py#L61

**Comment by t-aus-m** [comment]
To revisit this issue:
Some users are reporting that KeepassXC only sometimes detects the username field. I can reproduce this and it seems like KeepassXC can not detect the username field in around 50 % of the tries.
