### ISSUE TITLE
Guacamole oauth redirect broken in 2022.9.0

### ISSUE THREAD

**Issue by tomlawesome** [goauthentik/authentik#3734]
**Describe the bug**
Login to Guacamole using oAuth and when you click 'continue' you are redirected back to the same screen. 

**To Reproduce**
Upgrade to 2022.9.0
Try to login to Guacamole using oAuth

**Expected behavior**
It logs in. In 2022.8.1 this works as expected with no other changes. 

**Screenshots**

**Logs**
Redacted

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2021.8.5]
 - Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
authentik 2022.9 added `x5c` and `x5t` to the JWKS response, and guacamole only checks the JWKS endpoint on start, please try restarting your guacamole (only guacamole, guacd doesn't matter for this)

also I'd recommend you remove the logs and delete the edit as they seem to contain sensitive data (there's now a note on the authentik website to be careful with the log level trace)

**Comment by tomlawesome** [comment]
Thanks — logs removed. 

I tried restarting, I even removed and remade the containers (both guacamole and gaucd just in case, via ‘docker container rm -f guacamole guacd’ with stopped containers). 

The problem still seems to persist?

**Comment by BeryJu** [comment]
Can you post the logs of the guacamole container? There shouldn't be any sensitive data in that, but hopefully an error message

**Comment by BeryJu** [comment]
Check if your guacamole provider has any signing key selected, from the screenshot it looks like the JWKS response is `[]` which happens when no such key is selected

**Comment by tomlawesome** [comment]
Fixed. Issue was a bit of both Guacamole and incorrect settings in Authentik. 

I added an SSL cert to the Guacamole container's CAcerts (/usr/local/openjdk-8/jre/lib/security/cacerts) and then added that cert to Authentik, and selected it in the provider options. 

All seems well again now.
