### ISSUE TITLE
Tautulli forward auth doesn't work

### ISSUE THREAD

**Issue by 2ndwonder** [goauthentik/authentik#3745]
Hi all, I'm having issues with Tautlli forward auth on authentik. all my other containers work on docker except tautulli not with authentik. when I try to reach external host, it says 
    "Message": "no app for hostname",
    "Host": "tautulli.domain.nl",
    "Detail": "Check the outpost settings and make sure 'tautulli.domain.nl' is in cluded."
even tho it's there in the outpost settings. Can someone confirm if you have the same issue? thanks in advance

![unknown](https://user-images.githubusercontent.com/24813161/194683203-ddcd3a2a-632f-470c-8011-5ad366a8cde7.png)
![unknown2](https://user-images.githubusercontent.com/24813161/194683204-aa4a30ba-c078-4061-9cb4-ca476f9399fa.png)
![unknown3](https://user-images.githubusercontent.com/24813161/194683206-8bb0c5a5-9a68-4bb6-a075-3f91f22d6b4d.png)
![unknown4](https://user-images.githubusercontent.com/24813161/194683209-bd5a54f8-7831-47bc-8167-cc6d882e3348.png)
![unknown5](https://user-images.githubusercontent.com/24813161/194683211-f47b019c-3f3a-4c92-8576-f0b39ddbbcad.png)
![unknown6](https://user-images.githubusercontent.com/24813161/194683212-709aecba-80d2-41e0-823a-5f3346494a9d.png)
![unknown7](https://user-images.githubusercontent.com/24813161/194683213-a27decae-025b-44e6-9c79-4370da3183fe.png)

**Comment by 2ndwonder** [comment]
got it working.. restarted my gas

**Comment by igor47** [comment]
i had the same issue, my `authentik.worker` container was stopped for some reason, no info in the logs about why it stopped. i restarted it and things started working again. you can tell that's the problem from the admin overview page, look under `Workers`:

![image](https://github.com/goauthentik/authentik/assets/200575/242a9e3f-2ab2-489d-bc94-3b34a0960856)

**Comment by migracing** [comment]
I cannot believe it. I spent the past SIX HOURS diagnosing the issue just to figure out i needed to restart!!! 🤦‍♂️ The solution was simply restart the worker container. Haha. I had restarted the main Authentik container and the external outpost tons of times with many different setting but never the worker!!! Haha. I forgot to do the most basic thing. 
Thanks @2ndwonder and @igor47
