### ISSUE TITLE
Datetime localization or use of ISO 8601

### ISSUE THREAD

**Issue by not7cd** [goauthentik/authentik#3768]
Currently, the date and time in the event log are displayed in the US standard. Which is quite confusing for the rest of the world. Even switching to a different localization doesn't help with that. This could be solved altogether by the use of ISO 8601 timestamp. As we are operating computer systems, and authentik is part one of them, timestamps should follow a standard.
What I really want to say, is that I get incredibly confused when the month is first.

**What I get**
10/13/2022, 12:02:53 AM

**What I expect**
2022-10-13 00:02:53

**Comment by BeryJu** [comment]
The date and time are displayed in whichever locale the browser is configured for, see https://github.com/goauthentik/authentik/blob/main/web/src/admin/events/EventListPage.ts#L69

I think the better option would be to use the user's configured locale to decide how to show the language
