### ISSUE TITLE
Access groups in pfsense

### ISSUE THREAD

**Issue by depuits** [goauthentik/authentik#3775]
**Describe your question/**
According to the [documentation from pfsense](https://docs.netgate.com/pfsense/en/latest/usermanager/ldap.html#ldap-groups) it should be possible to assign groups from ldap. I was not able to get this to work. When using the `Diagnostics > Authentication` the user was authenticated but no groups where added. I tested by adding a `admins` group in authentik like the default in pfsense. Is this currently possible or can we only limit access by changing the search group?

**Relevant infos**
i.e. Version of other software you're using, specifics of your setup

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.9.0
 - Deployment: docker-compose

**Additional context**

**Comment by EuleMitKeule** [comment]
I am experiencing the same problem right now with the latest authentik version, I configured pfSense to use the `memberOf` attribute and can authenticate without problem, but pfSense tells me, that my users are not members of any groups.

**Comment by m0nji** [comment]
are there any news on this. experiencing the same issue.
