### ISSUE TITLE
Docs: In the feature comparison table it does nocht become clear that Keycloak is not an LDAP provider 

### ISSUE THREAD

**Issue by lindenthal** [goauthentik/authentik#3800]
As far as I know Keycloak is not a LDAP provider. It would be helpful to show this in your comparison table. Unfortunately I couldn't find the sources to create a PR to adapt this. Can you please direct me to the correct place?

![image](https://user-images.githubusercontent.com/1019287/196164117-93d0699e-e717-41cd-8803-bc4b79ea17ca.png)

**Comment by BeryJu** [comment]
The table already shows that Keycloak is not an LDAP Provider (3rd row), but Keycloak can federate with LDAP to import users (8th row)

**Comment by lindenthal** [comment]
Hi @BeryJu,

you are absolutely right. Sorry for not rtfm.

Best
Niels
