### ISSUE TITLE
Passwordless login Traceback

### ISSUE THREAD

**Issue by slimshizn** [goauthentik/authentik#3803]
**Describe the bug**
Follow passwordless login documentation, uncheck Evaluate on plan and check Re-evaluate policies, and passwordless login does not work. Check Evaluate on plan, and uncheck Re-evaluate polices, passwordless login works. Upon logging in, traceback is shown on notification panel.

**Expected behavior**
No traceback.

**Logs**
[logs](https://short.slimsflix.com/4hf2)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.9.0
 - Deployment: docker

**Comment by BeryJu** [comment]
The docs were incorrect, and they also didn't show correctly that there are two different ways to setup passwordless auth

**Comment by slimshizn** [comment]
Thank you for the very fast update.

**Comment by slimshizn** [comment]
So updating the filter got rid of the traceback, but still will not work with the directions as follows...

"Make sure to uncheck Evaluate on plan and check Re-evaluate policies, otherwise an invalid result will be cached."

I'm able to use passwordless login with "Evaluate on plan". It is not working with "Re-Evaluate policies", and just has me log in with the password.
![firefox_LGr4xUYisi](https://user-images.githubusercontent.com/23506499/196564248-17faf1a1-3248-418c-97fe-4e241c20a49c.png)

**Comment by slimshizn** [comment]
Both of them checked, allows for me to use passwordless login as well.

**Comment by slimshizn** [comment]
Additional [logs](https://short.slimsflix.com/ljgd)

**Comment by slimshizn** [comment]
![firefox_cBLdQjXCDS](https://user-images.githubusercontent.com/23506499/196566885-a12506d6-622d-4c64-9a4b-10a0ecc09b22.png)

Is this section relevant to have this working without error? Thank you.

**Comment by BeryJu** [comment]
Looking at the diagram, I think the option `Negate result` should be set, as currently the password stage is applied if the user has an MFA device which doesn't really make sense

The passwordless flow setting is for the alternate way of passwordless login, see https://goauthentik.io/docs/flow/stages/authenticator_validate/#passwordless-authentication

**Comment by slimshizn** [comment]
![firefox_t6kfFRM8lC](https://user-images.githubusercontent.com/23506499/199133314-b88eee4a-4c95-469d-a3e4-ffec8560eaaf.png)

The documentation pretty much says to add a policy with ```from authentik.stages.authenticator_webauthn.models import WebAuthnDevice
return WebAuthnDevice.objects.filter(user=request.context['pending_user'], confirmed=True).exists()```

Why isn't the passwordless flow settings used under the identification stage or talked about in the documentation?

btw I selected the `negate result` option, seems like the diagram didn't change but I believe the traceback issues are resolved.
