### ISSUE TITLE
Method GET not allowed on api/v3/core/users/{user_id}/set_password

### ISSUE THREAD

**Issue by lxndrbnsv** [goauthentik/authentik#3806]
Hello. I'm trying to set passwords for users I've created via the API. When I use the set_password endpoint end send a POST request, I'm getting a 405 response, {'detail': 'Method "GET" not allowed.'}

The source code of request attached below. 

 - authentik version: 2022.9.0
 - Deployment: docker-compose

```
def set_password(user_id, password):
    url = f"https://auth.example.com/api/v3/core/users/{user_id}/set_password"

    headers = {
        "Authorization": f"Bearer {ADMIN_TOKEN}",
        "Content-Type": "application/json",
    }
    data = {"password": password}
    r = requests.post(url, headers=headers, json=data)
    return r, json.loads(r.text)
```

**Comment by BeryJu** [comment]
The request URL in your example is missing a trailing slash, hence it's redirected by authentik, and that redirect turns the POST into a GET

**Comment by lxndrbnsv** [comment]
> The request URL in your example is missing a trailing slash, hence it's redirected by authentik, and that redirect turns the POST into a GET

Thank you. And sorry for a silly mistake
