### ISSUE TITLE
How to get Forward Auth single application to work with BunkerWeb ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [goauthentik/authentik#3851]
**Describe your question/**
Hi,

I am trying to get Forward Auth to work with BunkerWeb to secure my *arr applications (radarr, sonarr...) while still being able to do per application authorizations. Bunkerweb is based on Nginx, and uses env variables to setup. They provide this example: https://github.com/bunkerity/bunkerweb/blob/master/examples/authentik/docker-compose.yml . I'm trying to get it working with it and while also sticking to this : https://goauthentik.io/docs/providers/proxy/forward_auth#nginx , but I'm struggling to do it.

Here is my configuration so far:
Authentik compose: https://paste.techbag.app/?63db0d19bb99e56c#B4W3aSrG26KgvoPNYB1j3758n4Es6B2h5ohQ1TQan2tJ
Bunkerweb + outpost compose: https://paste.techbag.app/?45290a371c8569c1#EQVhQ1ufsm4gBEhwgZzSbTjFTdQbdxzZ3L2FPTeZ9Z9G
Radarr compose: https://paste.techbag.app/?0e1f6dc72c0a1883#HNyfdf2vbuijQjM6n3ZyvBC6KpuRrbyYMSLvDnjDrkgK

I am encountering this Nginx error when trying to access radarr.mydomain.com:
`2022/10/17 13:52:00 [error] 1711#1711: *1275 auth request unexpected status: 404 while sending to client, client: clientip, server: radarr.mydomain.com, request: "GET / HTTP/2.0", host: "radarr.mydomain.com"
radarr.mydomain.fr 104.28.214.63 - - [17/Oct/2022:13:52:00 +0000] "GET / HTTP/2.0" 500 170 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"`

I can't find where my error is, I tried to stick as much as possible to the examples. I would really appreciate some help to get this right. Thanks in advance for any answer, have a great day.

**Relevant infos**
BunkerWeb works by using env variables, setting names are very close to Nginx. Setting list is avaiable here: https://docs.bunkerweb.io/1.4/settings/

**Logs**
`2022/10/17 13:52:00 [error] 1711#1711: *1275 auth request unexpected status: 404 while sending to client, client: clientip, server: radarr.mydomain.com, request: "GET / HTTP/2.0", host: "radarr.mydomain.com"
radarr.mydomain.fr 104.28.214.63 - - [17/Oct/2022:13:52:00 +0000] "GET / HTTP/2.0" 500 170 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"`

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.10
 - Deployment: docker-compose

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I'm struggling with this for months now, does anyone has an idea ? I would appreciate it a lot. Have a great day everyone !

**Comment by BirdInFire** [comment]
> Hi, I'm struggling with this for months now, does anyone has an idea ? I would appreciate it a lot. I made a help request on Discord too but I'm not getting any answer so far. Is there other places where I could get help ? Have a great day everyone !

I ask the same since I searched a way to do that too.

**Comment by BeryJu** [comment]
I'd recommend asking about this on the https://github.com/bunkerity/bunkerweb repo
