### ISSUE TITLE
Restoring from postegresql backup results in server error.

### ISSUE THREAD

**Issue by inmanturbo** [goauthentik/authentik#3874]
**Describe the bug**

Restoring a postegresql backup results in server error.

**To Reproduce**
1. Fire up authentik instance using docker-compose
2. Make all sorts of changes (create flows and applications, add LDAP sources, etc)
3. Backup your database using pgadmin or similar tool
3. Deploy empty authentik instance (same version) to kubernetes cluster
4. Import your database using pgadmin or similar tool
5. See error

**Expected behavior**
Everything works aside from a few environment specific details which as should be easy to repair through web GUI.

**Screenshots**
**To be by added**
**Logs**
Output of docker-compose logs or kubectl logs respectively
**Coming soon**

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2021.8.5]
 - Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by Lanhild** [comment]
Could you provide more details? Any logs? I encountered a somewhat similar issue not too long ago, but it was because of the backup method I used. Can't help if you don't provide more info
