### ISSUE TITLE
Nextcloud with OpenID groups claims

### ISSUE THREAD

**Issue by sachz19** [goauthentik/authentik#3878]
**Describe your question/**
Hi,
I implemented OpenID authentication on my Nextcloud instance based on the information I found from this support topic: https://github.com/goauthentik/authentik/issues/2772

Everything works and the groups are populated from Authentik. The only issue currently is that each group gets a prefix based on your tenant. 
Nextcloud only uses the builtin admin group to assign admin rights. But currently I can't populate the admin group because every group i create in Authentik gets a prefix in Nextcloud. 
There is currently not really another way (that I found) to assign admin rights.

Is there a way to handle this issue within authentik?

The reason I don't want to go with the SAML provider is that I need multiple login sources
The users that still use the other authentication will probably keep on connecting through that way, because they only have access to email and Nextcloud, not to any other services I host through Authentik.

If there isn't a solution with OpenID, I guess I'll have to look into migrating those users, but thats a whole different story.

**Relevant infos**
I'm on Nextcloud 24
Social plugin on the latest update
Docker host (ubuntu based)

**Comment by sevmonster** [comment]
I would not consider following that issue to be a very good idea, given the issues the poster encountered :) but it's good you got it to work.

Why can you not use the SAML provider? Users can still access the non-SAML login page with the `/login?direct=1` endpoint if I recall. Or maybe that is a headache you don't want them to have to deal with.

Regardless, if you are using the `groups` claim (part of the default `profile` scope) then you can find the groups defined in *Customization -> Property Mappings -> authentik default OAuth Mapping: OpenID 'profile'*:
![image](https://user-images.githubusercontent.com/16788697/212395744-8c8334b9-0aa3-4ecd-8994-95342332bfa4.png)

I don't believe there is any prefixing being done by Authentik, it is done [by the plugin](https://github.com/zorn-v/nextcloud-social-login/issues/372). I haven't used `sociallogin` but I believe you can set up group mappings between received groups and Nextcloud groups, for OIDC. If that doesn't work for you you might have to use the other OAuth2 plugin and see if that fits your needs.

In any case, nothing can be done from Authentik's side here.

**Comment by sachz19** [comment]
Awesome for the follow-up!I’ll look into it further and post if i figure it out.I remember something like you mention from something i read a while ago so i will explore that.Thank you for pointing me into the right direction!On 13 Jan 2023, at 19:56, sev ***@***.***> wrote:﻿
I would not consider following that issue to be a very good idea, given the issues the poster encountered :) but it's good you got it to work.
Why can you not use the SAML provider? Users can still access the non-SAML login page with the /login?direct=1 endpoint if I recall. Or maybe that is a headache you don't want them to have to deal with.
Regardless, if you are using the groups claim (part of the default profile scope) then you can find the groups defined in Customization -> Property Mappings -> authentik default OAuth Mapping: OpenID 'profile':

I don't believe there is any prefixing being done by Authentik, it is done by the plugin. I haven't used sociallogin but I believe you can set up group mappings between received groups and Nextcloud groups, for OIDC. If that doesn't work for you you might have to use the other OAuth2 plugin and see if that fits your needs.
In any case, nothing can be done from Authentik's side here.

**Comment by BeryJu** [comment]
will be fixed by #9153
