### ISSUE TITLE
LDAP Federation Logs

### ISSUE THREAD

**Issue by MB175** [goauthentik/authentik#3880]
Is there any significant log output regarding the LDAP Option in federation, im not able to establish a connection to my LDAP server.

Sadly I can't find any traces of the LDAP Sync job in the Server or the worker log, is there any way to be able to log the connection attempt to be able to debug it ?

**Comment by MB175** [comment]
Looks like, setting the Authentik log level to trace instead of the default info allows the ui to print more logs.
Otherwise changing the loglevel and restarting fixed an issue with the ui logs

**Comment by BeryJu** [comment]
this is fixed by #7263
