### ISSUE TITLE
System Task Error - Apply single blueprint

### ISSUE THREAD

**Issue by Ejant** [goauthentik/authentik#3898]
Hi Everyone, I've been using authentik for a while. I was trying to made some modifications, specifically on user session duration. After that I'm seeing a system task error:
`{"entry": "BlueprintEntry(model='authentik_tenants.tenant', identifiers={'domain': 'authentik-default', 'default': True}, attrs={'flow_authentication': UUID('e2c15f5a-f99d-4f5a-8e4b-5d73b85a2a33'), 'flow_invalidation': UUID('9f950681-9cf3-4121-9a6c-c6f7a8780571'), 'flow_user_settings': UUID('eac14775-f1de-4e11-9fa2-7438b6adaba7'), 'domain': 'authentik-default', 'default': True}, id=None, _state=BlueprintEntryState(instance=None))", "error": "EntryInvalidError(\"Serializer errors {'non_field_errors': [ErrorDetail(string='Only a single Tenant can be set as default.', code='invalid')]}\")", "event": "entry invalid: Serializer errors {'non_field_errors': [ErrorDetail(string='Only a single Tenant can be set as default.', code='invalid')]}", "level": "warning", "log_level": "warning", "logger": "authentik.blueprints.v1.importer", "pid": 818, "task_id": "task-a7f4de83d7034fa3980484eea5af55b4", "timestamp": "2022-10-29T00:07:13.548370"}
`
![image](https://user-images.githubusercontent.com/24468827/198752494-791a5fb4-feb1-4586-83bf-3ce6ba9b1ae7.png)

 - authentik version: 2022.10.0
 - Deployment: docker-compose (Docker version 20.10.5+dfsg1)
 
Everything seems to be OK except the changes I've applied, I need to keep the user session even after the user closes the browser.
This is the change I made:

![image](https://user-images.githubusercontent.com/24468827/198752690-3058facd-e0d4-4e0f-830a-af8f7f8a8ca3.png)

Should I ignore that error? Will it gone after certain amount of time? Maybe I did configure something wrong?

**Comment by deltabweb** [comment]
Same error here after updating to 2023.10.1

**Comment by Neferites** [comment]
Hello, i encounter the same error in 2024.2.2.
Configuration : 
```
brand name: new-brand.tld
Is default brand: yes
```

I've already delete the authentik-default'brand ...
Error : 
```
{"domain_url": null, "entry": "BlueprintEntry(model='authentik_brands.brand', state=<BlueprintEntryDesiredState.CREATED: 'created'>, conditions=[], identifiers={'domain': 'authentik-default', 'default': True}, attr
s={'flow_authentication': <authentik.blueprints.v1.common.Find object at 0x7fb55dadade0>, 'flow_invalidation': <authentik.blueprints.v1.common.Find object at 0x7fb55d8f41a0>, 'flow_user_settings': <authentik.bluepr
ints.v1.common.Find object at 0x7fb55d8f41d0>}, id=None, _state=BlueprintEntryState(instance=None))", "error": "EntryInvalidError(\"Serializer errors {'default': [ErrorDetail(string='Only a single brand can be set
as default.', code='invalid')]}\")", "event": "entry invalid: Serializer errors {'default': [ErrorDetail(string='Only a single brand can be set as default.', code='invalid')]}", "level": "warning", "log_level": "wa
rning", "logger": "authentik.blueprints.v1.importer", "pid": 40667, "schema_name": "public", "task_id": "task-9987ca71e3e3479d938d0207bd2a80b3", "timestamp": "2024-04-03T07:48:36.792996"}
```

If i recreate a brand named : authentik-default, error is changed in : 
```
{"domain_url": null, "entry": "BlueprintEntry(model='authentik_brands.brand', state=<BlueprintEntryDesiredState.CREATED: 'created'>, conditions=[], identifiers={'domain': 'authentik-default', 'default': True}, attr
s={'flow_authentication': <authentik.blueprints.v1.common.Find object at 0x7fb55f35a060>, 'flow_invalidation': <authentik.blueprints.v1.common.Find object at 0x7fb55f358530>, 'flow_user_settings': <authentik.bluepr
ints.v1.common.Find object at 0x7fb55f35b890>}, id=None, _state=BlueprintEntryState(instance=None))", "error": "EntryInvalidError(\"Serializer errors {'domain': [ErrorDetail(string='This field must be unique.', cod
e='unique')]}\")", "event": "entry invalid: Serializer errors {'domain': [ErrorDetail(string='This field must be unique.', code='unique')]}", "level": "warning", "log_level": "warning", "logger": "authentik.bluepri
nts.v1.importer", "pid": 40672, "schema_name": "public", "task_id": "task-d41b5ef0fb2b4488b48f9d45ae6154bd", "timestamp": "2024-04-03T07:52:56.302355"}
```

PostgreSQL database do not contain the authentik-default brand in the first test.

Regards
