### ISSUE TITLE
Add support for nodeSelector, labels & annotations for Kubernetes-based outposts.

### ISSUE THREAD

**Issue by justSem** [goauthentik/authentik#3910]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more a nice-to-have.
In bigger clusters we often have several pools of nodes dedicated to different tasks. It would be neat if authentik could add some basic support for kubernetes labeling/annotations on the outpost deployments

**Describe the solution you'd like**
I'd  like to be able to:

- Set a nodeSelector on my outposts
- Set basic labels/annotations on my outposts.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by BeryJu** [comment]
added with #6319
