### ISSUE TITLE
Discord checking membership

### ISSUE THREAD

**Issue by slimshizn** [goauthentik/authentik#3931]
Currently we are trying to match discord users in a guild, with a specific role, and allow those members specific auth if they are in a group.

So far this is what we are using, just need a bit of assistance here.

```
ACCEPTED_ROLE_ID = "092698362475836802"
if context['source'].provider_type != "discord":
     return True
connection = context['goauthentik.io/sources/connection']
access_token = connection.access_token
guild_member_object = requests.get(
    "https://discord.com/api/users/@me/guilds/092698362475836802/member",
  headers= {
      "Authorization": "Bearer " + access_token,
  }
).json()
user_matched = False
user_matched = any(ACCEPTED_ROLE_ID == g["role"] for g in guild_member_object.roles)
if not user_matched:
    ak_message(f"User is not member of {ACCEPTED_ROLE_ID}.")
return user_matched
```

Traceback we are getting is
```
Exception
Traceback (most recent call last):
  File "Checking for membership of a Discord Guild", line 18, in <module>
  File "Checking for membership of a Discord Guild", line 14, in handler
builtins.AttributeError: 'dict' object has no attribute 'roles'
```
![Screenshot 2022-11-02 at 11-51-06 discord-authentication-flow - Admin - authentik](https://user-images.githubusercontent.com/23506499/199537571-65f6ec87-5158-406d-95fe-d59667aef155.png)

![Screenshot 2022-11-02 at 11-53-48 discord-enrollment-flow - Admin - authentik](https://user-images.githubusercontent.com/23506499/199537926-ddc2bf81-a9f4-439d-994d-325a57d1c4df.png)

![Screenshot 2022-11-02 at 11-54-58 Discord - Admin - authentik](https://user-images.githubusercontent.com/23506499/199538226-05c7d77f-8b32-4ca5-8745-612878bcc5f5.png)

**Comment by slimshizn** [comment]
ID was scrambled around, not actual ID

**Comment by slimshizn** [comment]
Changed over `guild_member_object.roles` to `guild_member_object["roles"]`

```
Exception
Traceback (most recent call last):
  File "Checking for membership of a Discord Guild", line 18, in <module>
  File "Checking for membership of a Discord Guild", line 14, in handler
builtins.KeyError: 'roles'
```

**Comment by slimshizn** [comment]
tried changing the api in this line from:
 "https://discord.com/api/users/@me/guilds/{guild.id}/member",
to
 "https://discord.com/api/users/@me/guilds/{guild.id}/members/search", same error

**Comment by Aterfax** [comment]
Note: The following policy expression seemed to do the trick for me: https://pastebin.com/qq1YdZbj

**Check user is in guild and has role:**
```
ACCEPTED_ROLE_ID = "ROLE_ID_HERE"
ACCEPTED_ROLE_NAME = "ROLE_NAME_HERE"
GUILD_NAME = "GUILD_NAME_HERE"
 
# Ensure flow is only run during oauth logins via discord
if context['source'].provider_type != "discord":
    return True
 
# Get the user-source connection object from the context, and get the access token
connection = context['goauthentik.io/sources/connection']
access_token = connection.access_token
 
 
# Make sure you change the GUILD_ID_HERE below
 
guild_member_object = requests.get(
    "https://discord.com/api/users/@me/guilds/GUILD_ID_HERE/member",
    headers= {
        "Authorization": "Bearer " + access_token,
    }
).json()
 
 
user_matched = False
user_matched = any(ACCEPTED_ROLE_ID == g for g in guild_member_object["roles"])
if not user_matched:
    ak_message(f"User is not member of the {ACCEPTED_ROLE_NAME} role in {GUILD_NAME}.")
return user_matched
```

You add the above as the 'Policy' binding and then define subsequent 'User Write Stage' bindings to add any authentik groups to the accounts

It should be noted that I only applied and tested this for the enrollment flow and that a similar set of logic would be needed on the authentication flow (to reset and rewrite the authentik groups to keep them up to date with the current state of the discord roles.) 

I expect you could choose to only define "User Write Stages" on the authentication stage and be fine.

If concerned about excessive data access / logging (GDPR?) then I think it is also possible to apply the policy on the 'Federation & Social login' Oauth source for your discord linkage to reject users failing the policy check as early as possible (again I've not tested.)
