### ISSUE TITLE
Some flows get logged out by closing and reopening browser

### ISSUE THREAD

**Issue by thechubbypanda** [goauthentik/authentik#3944]
**Describe the bug**
For OIDC (e.g. Gitea) and the Authentik dashboard, closing and reopening the browser, logs the user out and forces them to login again.
This issue does not happen for forward auth applications (such as Traefik dashboard) or SAML applications like Nextcloud.

**To Reproduce**
1. Go to 'authentik.example.com' (Dashboard)
2. Login
3. Close all browser windows
4. Go to 'authentik.example.com' again
5. Observe logged out state

**Expected behavior**
Dashboard should remain logged in after closing browser and immediately reopening it

**Logs**
[Pastebin](https://pastebin.com/wLpimZfX)

**Version and Deployment:**
 - authentik version: 2022.10.1
 - Deployment: docker-compose

P.S. Thanks @BeryJu, amazing piece of software, and congrats on the company

**Comment by rbooth84** [comment]
When you first install authentik the Session duration of the default-authentication-login stage is set to 0 which means the sessions lasts until the browser is closed. I set mine to "hours=720" which is good for 30 days.
