### ISSUE TITLE
Enrolment restriction by specific email domains

### ISSUE THREAD

**Issue by mbh-dev** [goauthentik/authentik#3956]
Hi, I'm looking to enrol new users by restricting them to specific email domains, for example me@domain1.com can sign up, but me@domain2.com cannot.
This is to onboard specific organisations and their members.

If anyone knows how this could be done, I'd greatly appreciate the advice.

Thanks

**Comment by zaourzag** [comment]
Hey, i did some digging and i think this suits your case the most
https://goauthentik.io/docs/policies/expression#regex_matchvalue-any-regex-str---bool

**Comment by mbh-dev** [comment]
@zaourzag Thanks, I've attempted to implement this within the enrolment flow however the following error is displayed when just accessing the signup form 

'AnonymousUser' object has no attribute 'email'

Any ideas? 
Thanks

**Comment by zaourzag** [comment]
Hmmm, makes sense As qt that stage they're just signing up and not a user yet, hence the AnonymousUser. Could you perhaps share your code? Perhaps that'll give me more of an insight

**Comment by mbh-dev** [comment]
Here's my code, it's based off the example on the authentik docs;

return regex_match(request.user.email, '.*testtld.*')

I've dropped a message on discord :)

Thanks

**Comment by stategyhq** [comment]
Did anyone find a solution to this? also looking to restrict enrollment to specific domain names

**Comment by mbh-dev** [comment]
@stategyhq unfortunately not, hoping someone is able to help, I've posted here and on the discord, but the solution presented above didn't work, throws an error, maybe it should be a feature request?

**Comment by zaourzag** [comment]
@mbh-dev i just found this, perhaps this could help. https://github.com/goauthentik/authentik/issues/4347#issue-1517962341

**Comment by BeryJu** [comment]
See the note under https://docs.goauthentik.io/docs/policies/expression#variables

also there's an example for this kind of policy here: https://docs.goauthentik.io/docs/policies/working_with_policies/whitelist_email
