### ISSUE TITLE
Add redis cluster support

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#3979]
**Is your feature request related to a problem? Please describe.**
Authentik does not work without redis. To archive real HA redis has to run in multi-master (custer) mode which does not support multiple Databases.

**Describe the solution you'd like**
Either allow all services to use the same redis db (I don't know if this is already an option) or allow to specify multiple redis connections (host,port,username,pw).

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by benedikt-bartscher** [comment]
fixed by https://github.com/goauthentik/authentik/pull/4009

**Comment by ProjectInitiative** [comment]
@benedikt-bartscher you marked this as completed, how did you end up setting up your deployment? I am attempting to use redis-cluster with the most recent release of authentik and it is throwing all kinds of errors not seen with a standard redis deployment

**Comment by benedikt-bartscher** [comment]
@ProjectInitiative you are right.
Authentik uses celery for background tasks. Celery requires some kind of broker (redis, rabbitmq, sqs, ..). Authentik has celery configured to use redis as broker. Sadly the celery redis backend does not support redis cluster mode yet (see https://github.com/celery/kombu/pull/1021 and https://github.com/celery/celery/issues/2852).

Maybe we should think about switchting to RabbitMQ? I am using the same setup (django+celery+rmq) with kubernetes in another project, which is working just fine (perfect failover with 0 downtime).

**Comment by ProjectInitiative** [comment]
I am going to try and setup a normal redis replication with sentinel for failover, otherwise the current deployment I am testing takes a considerable amount of time to fail over and authentik just hangs, waiting for a redis master to spin up on another node.

**Comment by benedikt-bartscher** [comment]
Thanks @BeryJu, this commit should allow using rmq instead of redis: https://github.com/goauthentik/authentik/commit/34189439491e2dc9552a0b48d1ca6e23dac4e376

**Comment by PKizzle** [comment]
@benedikt-bartscher If you still want to give Redis cluster a try you may have a look at https://github.com/goauthentik/authentik/pull/7118 and test out the images uploaded to [Docker Hub](https://hub.docker.com/r/thegrandpkizzle/authentik/tags). If you experience any issue do not hesitate to comment on the PR.

**Comment by PKizzle** [comment]
Just make sure not to try it in a production environment as the Redis cluster support is far from perfect.

**Comment by wmcfight** [comment]
any update for this feature?
