### ISSUE TITLE
Disable creation of new users / enrollment in an easy way

### ISSUE THREAD

**Issue by joggs** [goauthentik/authentik#3988]
**Is your feature request related to a problem? Please describe.**
I think there are many users that uses authentik for their homelabs and only need one user. I would like to be able to disable the creation of new users and enrollments.
It is risky when you have an oauth provider, such as google, and you notice that everyonbe can login with nay google user and then just enter their wanted username and they are in. You do not want to insert deny stages everywhere and risk that you miss someting.

**Describe the solution you'd like**
I would like a setting in Authentik admin panel that says disable enrollment, which disables all possibilities to enroll. even when you go the oauth login path mentioned above.

**Describe alternatives you've considered**
using deny stages everywhere, but it is ugly

**Additional context**

**Comment by BeryJu** [comment]
A default authentik install has no pre-configured way for users to enroll. To achieve your goal, you can simply select the empty option for enrollment flow in your OAuth source, and this will stop new users from being able to enroll. Existing users that have enrolled with that source in the past will continue to be able to authenticate

**Comment by insunaa** [comment]
@BeryJu 
> A default authentik install has no pre-configured way for users to enroll. To achieve your goal, you can simply select the empty option for enrollment flow in your OAuth source, and this will stop new users from being able to enroll. Existing users that have enrolled with that source in the past will continue to be able to authenticate

This no longer seems to work. Whenever I select the empty flow in the Enrollment Flow dropdown, upon hitting "Save" it will say successfully saved, but when I open the flow settings again the enrollment flow is once again selected. I've tried this on different machines with different accounts and it's impossible to remove it, now.

**Comment by BeryJu** [comment]
I think this might be the same issue as https://github.com/goauthentik/authentik/pull/6767 (I can also reproduce it)
