### ISSUE TITLE
UI, while group creation, adding members, removes the parent selection.

### ISSUE THREAD

**Issue by ranomier** [goauthentik/authentik#3999]
**Describe the bug**
When i create a group i first give it a name, then i select the parent and then i add members. In the select users window, i select a user and click on add. Back in the create group window the selection of the parent is gone.

**To Reproduce**
1. In the Admin Interface, under Directory -> Groups
2. Click on "Create"
3. Select a Parent in the drop down menu
4. add at least on member
5. the selection of the parent is gone

**Expected behavior**
The selection of the parent stays intact

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.10.1
 - Deployment: docker-compose

**Additional context**
 - Firefox Linux 106.0.5

**Comment by BeryJu** [comment]
This is fixed in 2022.12
