### ISSUE TITLE
Subdomains for services that use some sort of VNC or Guacamole don't function correctly

### ISSUE THREAD

**Issue by Avsynthe** [goauthentik/authentik#4010]
**Describe the bug**
Hi guys

I'm having an issue with things like Firefox, Calibre, and Krusader containers that don't work correctly when Authentik Forward Auth is put in front of it. Firefox and Calibre (which I believe use guacamole) show a blank white screen with the guacamole options button on the left, and Krusader's noVNC won't successfully connect.

Removing the NGINX Proxy Manager configs for these subdomains, removing them from behind Authentik, causes them to instantly function correctly and they also work fine behind Authelia

I've tried both adding and removing a variety of authenticated paths from the provider with no luck.

**To Reproduce**
1. Go to firefox.mydomain.com, calibre.mydomain.com or krusader.mydomain.com
2. See blank white screen with guacamole options or noVNC "Failed to connect to server" error

**Expected behavior**
Firefox and Calibre (Guacamole) should after a brief white screen, continue to show the UI
Krusader (noVNC) should successfully connect to the server and display the UI

**Screenshots**
![firefox-error](https://user-images.githubusercontent.com/102600593/201920840-3549fe48-13db-44ac-8009-71f9dee9ec54.png)
![krusader-error](https://user-images.githubusercontent.com/102600593/201920842-b3d73d0e-0e15-41c3-bf8d-3ba4bad1f06f.png)

**Version and Deployment (please complete the following information):**
 - Deployment: unRAID

**Comment by Avsynthe** [comment]
I've spun Authelia back up just for my three affected subdomains though this is a bit inconvenient if I want to have 2FA on both. Looks like I'll also need to do this if I want to add any other services that use Guacamole or noVNC.

If this is ever looked into, I'll be switching back to Authentik for them in a heartbeat. I'll be monitoring this for sure.

**Comment by HHUBSS** [comment]
I'm getting the same error. When I removed the NPM config, the vnc is working fine. I'm also using unraid.

**Comment by ngnl0** [comment]
Try adding a handler for the /websockify path (wss or ws). I had the same problem when configuring tinymediamanager and I solved it with the following method

```
location /websockify {
# This proxy_pass should point directly to your tinymediamanager's internal noVNC WebSocket port
# Replace <TMM_INTERNAL_IP> and <TMM_NOVNC_PORT> with your actual values
proxy_pass http://tinymediamanager:4000/websockify;

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme; # Important for backend to know it's HTTPS 

# These headers are for Authentik, but usually not needed for WebSocket directly 
# If your Authentik proxy provider also handles websockets, it might need them 
# auth_request /outpost.goauthentik.io/auth/nginx; 
# error_page 401 = @goauthentik_proxy_signin; 
# auth_request_set $auth_cookie $upstream_http_set_cookie; 
# add_header Set-Cookie $auth_cookie; 
# (Authenticator might break WebSocket. If it does, you might need to exclude websockify from auth)
}
```
