### ISSUE TITLE
Keep getting `Connection error, reconnecting...`.

### ISSUE THREAD

**Issue by Anas-Sherif** [goauthentik/authentik#4024]
**Describe your question/**
A clear and concise description of what you're trying to do.

When opening the WebUI and waiting a few seconds i keep getting "Connection error, reconnecting..."

**Screenshots**
![image](https://user-images.githubusercontent.com/77907877/202074741-575054d9-21ff-40f8-9a84-d964af5ed4a0.png)

**Comment by Anas-Sherif** [comment]
i get `WebSocket connection to 'wss://sso.doman.com/ws/client/' failed:` can you tell me a fix?

**Comment by samip5** [comment]
> i get `WebSocket connection to 'wss://sso.doman.com/ws/client/' failed:` can you tell me a fix?

If you're using a reverse proxy, you need to fix it's config.

**Comment by eloebl** [comment]
I know this is stale, but in case someone runs into this in the future, and using an nginx ingress, I had to add this to the ingress annotations:
```
  annotations:
    nginx.org/websocket-services: "authentik"
   ```

**Comment by jader31** [comment]
hi @EmilyNerdGirl  

Could you explain your fix to me ?
I just do not know what to do with your tip... hehehe... sorry!
The "... I had to add this to the ingress annotations" means nothing to me! 

I'm a newbie on Authentik using Nginx Proxy Manager to proxy + SSL certificates by LetsEncrypt
I'm getting those annyoing errors about "Connection error, reconnecting..." on my Authentik page... not very professional like I'd like for my SSO page!

**Comment by deanfourie1** [comment]
I am also getting this now behind Cloudflare.

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I am also getting this error behind Cloudflare. Is there a way to force websockets to use wss instead of ws protocol?

**Comment by rama31244** [comment]
I'm getting this error too and use traefik reverse proxy. Has anyone manages to resolve this issue with traefik?
