### ISSUE TITLE
initial-setup still works after setting up akadmin password

### ISSUE THREAD

**Issue by ishioni** [goauthentik/authentik#4033]
**Describe the bug**
After going through initial-setup after installation, I can still access /if/flow/initial-setup/ and re-set the admin password for a couple of minutes

**To Reproduce**
1. Install authentik (kubernetes helm in my case)
2. Go through /if/flow/initial-setup/, log out
3. Open up an incognito window, navigate to /if/flow/initial-setup/
4. Profit
5. After around 2 minutes it now properly denies the request with "Flow does not apply to current user (denied by policy)."

**Expected behavior**
The initial-setup flow should be denied immiediately after setting the admin password

**Screenshots**

**Logs**
Not sure which ones I should provide

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.10.1
 - Deployment: helm

**Comment by mdekoninck28** [comment]
Please share the workaround before closing the case
