### ISSUE TITLE
'Copy' button in TOTP setup page does not work

### ISSUE THREAD

**Issue by Pinkbyte** [goauthentik/authentik#4037]
**Describe the bug**
'Copy' button in TOTP setup page does not work

**To Reproduce**
1. Authenticate as user
2. Go to Settings->'MFA devices'
3. Click 'Enroll', choose 'TOTP authenticator', click on 'Copy' button
4. See error in browser's console

**Expected behavior**
TOTP secret is copied into clipboard

**Logs**
In browser console i see these errors:

- In Firefox:
```
Uncaught TypeError: navigator.clipboard is undefined
    value AuthenticatorTOTPStage.ts:87
    handleEvent lit-html.js:6
    r helpers.js:90
AuthenticatorTOTPStage.ts:87:46
    value AuthenticatorTOTPStage.ts:87
    handleEvent lit-html.js:6
    r helpers.js:90
```
- In Microsoft Edge:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at n.<anonymous> (AuthenticatorTOTPStage.ts:89:42)
    at pe.handleEvent (lit-html.js:6:7113)
    at pe.r [as handleEvent] (helpers.js:90:17)
```

**Version and Deployment (please complete the following information):**
 - Browser: Firefox 102.5.0esr and Microsoft Edge 107.0.1418.52
 - authentik version: 2022.10.1
 - Deployment: docker-compose

**Comment by Pinkbyte** [comment]
Still happens with release 2022.12.2

**Comment by Lanhild** [comment]
I can't seem to reproduce this issue. Maybe try updating your version?

**Comment by Pinkbyte** [comment]
I have just tested with 2023.1.2 and i confirm that issue is gone
