### ISSUE TITLE
allow to customize outposts ingress path

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#4039]
It would be helpful if the ingress path for outposts could be modified. Currently you can only set kubernetes_ingress_class_name, kubernetes_ingress_annotations and kubernetes_ingress_secret_name.

**Comment by BeryJu** [comment]
This can be done using `kubernetes_json_patches ` and supplying a custom patch: https://docs.goauthentik.io/docs/outposts/integrations/kubernetes; see https://github.com/goauthentik/authentik/pull/6319#issuecomment-1817093411 for an example
