### ISSUE TITLE
Fine-grained Permissions

### ISSUE THREAD

**Issue by MrMuster** [goauthentik/authentik#4072]
**Is your feature request related to a problem? Please describe.**
An authentik administrator has full control over the server.
It is possible to restrict admins to impersonate users and access all their application accounts: https://goauthentik.io/docs/installation/configuration#authentik_impersonation
But as admins are able to execute arbitrary code using policy expressions this restriction can easily be circumvented. 
Further they can place persistent backdoors, change configs, DoS the server...

In the case you want to grant a person the privilege to manage users (add/delete/edit) you always have to grant full server control and fully trust this person.

**Describe the solution you'd like**
Beside the 'admin' role there should be a role, that is only permitted to manage user and is not able to create policies. Related to: https://github.com/goauthentik/authentik/issues/2673

**Describe alternatives you've considered**
Alternatively the policy execution could be sandboxed to prevent arbitrary code execution, but I think this would be quite complex and can not fully prevent malicious behavior.

**Comment by gueldenstone** [comment]
This would be a very helpful feature! Any plans if and maybe when this will be considered?

**Comment by BeryJu** [comment]
duplicate of #5451 , but yes this is very much a feature we will be adding
