### ISSUE TITLE
How can I invalidate the domain level forward auth token when signing out of authentik?

### ISSUE THREAD

**Issue by GasimGasimzada** [goauthentik/authentik#4083]
**Describe your question/**

I have setup authentik for my domain enabled forward auth using Traefik (using Docker swarm mode) by creating a middleware as described in the documentation. Everything works as expected. When a user goes to a page, they are asked to provide passwords. However, if a user goes to the authentik page and signs themselves out, they are still able to access the pages. Is there a way to prevent that from happening? My initial thought was that Traefik will send forward auth request to authentik on every request and authentic will check if the user is signed in the backend regardless of the token stored in the cookie. If they are not, authentik will send `KO`. However, when I test the response by going to forward auth URL (https://auth.example.com/outpost.goauthentik.io/auth/traefik), I keep getting `OK` with all my data attached to it even though I am logged in.

**Additional context**

- Authentik v2022.11.1
- Traeffik v2.9
- Docker v20.10.21

**Comment by yananet** [comment]
Same with my situation. Maybe this issue? #2023

**Comment by BeryJu** [comment]
this should be fixed by #7099
