### ISSUE TITLE
The comparison seems outdated

### ISSUE THREAD

**Issue by ptman** [goauthentik/authentik#4088]
The web page about the comparison doesn't seem to be up to date. Authelia seems to support OpenID Connect and self-service.

**Comment by ptman** [comment]
Not stale

**Comment by ptman** [comment]
Thank you (is there maybe a typo ('passwd') in https://github.com/goauthentik/authentik/commit/0abbe8288eb2006d4ab70918ab1489f8cb598eb9#diff-f088381fc549cbf5dafd0922ca5e97549d67211e183ec5a3dda1da7698c7ebb8R190?).


Main page (authelia.com) has two items which fit into the self-service terminology. i.e. a user can perform a task that could also be handled by an administrator: password reset and email identity validation.

**Comment by james-d-elliott** [comment]
This unfortunately is still not accurate, as we fill the provider role, not the relying party role:

https://www.authelia.com/overview/authorization/openid-connect-1.0/
https://www.authelia.com/configuration/identity-providers/open-id-connect/

**Comment by BeryJu** [comment]
seems like I changed it in the wrong row of the table, should be fine now
