### ISSUE TITLE
[Feature Request] Authentik authorization should support MFA

### ISSUE THREAD

**Issue by ftong2020** [goauthentik/authentik#4089]
**Is your feature request related to a problem? Please describe.**
Hi, I am using authentik as my central Idp, and everything works pretty well. Now I am considering enhancing security for "some" of my apps, not all of them, by enforcing MFA. I tried adding "Authenticator Validation Stage" to my authorization flow with no sucess. My access to the app is always denied. From my understanding, "Authenticator Validation Stage" currently is only supported in authentication, not in authorization.

**Describe the solution you'd like**
MFA validation should be supported in authorization flow, so that MFA validation will not be enforced until user needs to access certain app.

**Describe alternatives you've considered**
Enforce MFA on all users/certain groups.

**Additional context**
Among all the apps I manage, only 10% ~ 20% worth the hassle from MFA, and even a user is granted privilege to access these apps, he or she might only access it a few times every week. Enforcing MFA on everyone all the time is just too much.

**Comment by AndrewBucklin** [comment]
I'm hoping to configure the same thing. Some apps have a requirement to log out after inactivity. However, the user might still be logged into Authentik and can simply re-authenticate to the application **without** going through MFA. This is especially problematic in environments with shared computers. Thanks!

**Comment by Lanhild** [comment]
Bumping as it would a very useful feature

**Comment by BeryJu** [comment]
This is supported, there was a bug for some time that broke authenticator_validation stages in non-authentication flows, but the stage is fully supported in authorization (or any other) flows
