### ISSUE TITLE
Is there a way to use forward auth to protect a subfolder?

### ISSUE THREAD

**Issue by anoosa1** [goauthentik/authentik#4091]
**Describe your question/**
A clear and concise description of what you're trying to do.
Trying to protect a subfolder using forward auth

**Additional context**
When I set it up it just puts me in an infinite redirect loop.

**Comment by erroltuparker** [comment]
I found the config listed here helpful in trying to configure subfolder proxying

https://github.com/goauthentik/authentik/issues/2305

The only issue i'm facing is parsing basic http username and password headers atm

**Comment by Anas-Sherif** [comment]
> I found the config listed here helpful in trying to configure subfolder proxying
> 
> #2305
> 
> The only issue i'm facing is parsing basic http username and password headers atm

I have tried this and it works however it only works if you are protecting only 1 subfolder if you try to protect another one it will always redirect you to the first one.
Also as you said http auth doesnt work

**Comment by igorferreir4** [comment]
Hi, any progress on this?

It would be a great feature.

**Comment by Anas-Sherif** [comment]
Any updates on this?

**Comment by BeryJu** [comment]
duplicate of #2305
