### ISSUE TITLE
This page isn’t working right now, redirected you too many times. | Authentik w/ Caddy

### ISSUE THREAD

**Issue by JaxzKyd** [goauthentik/authentik#4096]
**Describe the bug**
I'm trying to get Authentik to add protection to my Lidarr instance with Caddy as the reverse proxy. But trying to access the URL I had for Lidarr it gives me a "This page isn’t working right now, redirected you too many times." error

**To Reproduce**
1. Went to Providers, added a 'lidarr' provider in Authentik as `Forward auth (single application)` and added the domain I wanted to use for Lidarr in the External Host section
2. Went to Applications and created a new application with the name and slug being lidarr and added the provider as the provider I made in the last step
3. Went to Outposts and changed the 'authentik_host' to the domain I had assigned for Authentik
4. Went back to Providers and clicked on the provider I made. In the setup section, I scrolled over to 'Caddy (Standalone)' and copied the configuration on that page which I added below
```
lidarr.[REDACTED].duckdns.org {
    # always forward outpost path to actual outpost
    reverse_proxy /outpost.goauthentik.io/* http://192.168.1.166

    # forward authentication to outpost
    forward_auth http://192.168.1.166 {
        uri /outpost.goauthentik.io/auth/caddy

        # capitalization of the headers is important, otherwise they will be empty
        copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version

        # optional, in this config trust all private ranges, should probably be set to the outposts IP
        trusted_proxies private_ranges
    }

    # actual site configuration below, for example
    reverse_proxy localhost:1234
}
```

5. I then pasted that into my Caddyfile, but I changed the port at the bottom of the configuration to the port Lidarr was on. I also added the tls section I needed for duckdns at the bottom as well.
6.  I then ran Caddy and tried to load up the page I had for Lidarr and then I hit the error stated above.

**Expected behavior**
I expected to be greeted with an authentication page when I opened my page for Lidarr

**Logs**
My entire log for authentik-server is 61MB so GitHub wouldn't allow the upload :P
But here is a snippet, if it helps
`INF auth_via=unauthenticated event=/-/health/live/ host=localhost:8000 logger=authentik.asgi method=GET pid=5381 remote=127.0.0.1 request_id=00d30f4b1d9b4b8ba1837c39e569a5e3 runtime=20 scheme=http status=204 timestamp=2022-11-26T22:30:32.944926 user= user_agent=goauthentik.io/proxy/healthcheck
INF auth_via=unauthenticated event=/-/health/ready/ host=localhost:9000 logger=authentik.asgi method=HEAD pid=5381 remote=127.0.0.1 request_id=66d6ae6fb74f4698abdeb7dd1a64219e runtime=29 scheme=http status=204 timestamp=2022-11-26T22:31:01.717050 user= user_agent=goauthentik.io lifecycle Healthcheck
INF auth_via=unauthenticated event=/-/health/live/ host=localhost:8000 logger=authentik.asgi method=GET pid=5381 remote=127.0.0.1 request_id=76cb67672c5b4bdba106b18414bfd415 runtime=22 scheme=http status=204 timestamp=2022-11-26T22:31:02.944267 user= user_agent=goauthentik.io/proxy/healthcheck
INF event=updating tenant certificates logger=authentik.router.tenant_tls timestamp=2022-11-26T22:31:04Z
INF auth_via=secret_key event=/api/v3/core/tenants/ host=localhost:8000 logger=authentik.asgi method=GET pid=5381 remote=127.0.0.1 request_id=8e2b184211374818b2203f616d1b7775 runtime=63 scheme=http status=200 timestamp=2022-11-26T22:31:04.499742 user=ak-outpost-04c8d3a649be494389d9cce2aa4384b2 user_agent=goauthentik.io/outpost/2022.11.1
INF auth_via=unauthenticated event=/-/health/live/ host=localhost:8000 logger=authentik.asgi method=GET pid=5380 remote=127.0.0.1 request_id=c5324d2c86a640eeb7ef008cbe6c7b0b runtime=37 scheme=http status=204 timestamp=2022-11-26T22:31:32.957831 user= user_agent=goauthentik.io/proxy/healthcheck
INF auth_via=unauthenticated event=/-/health/ready/ host=localhost:9000 logger=authentik.asgi method=HEAD pid=5380 remote=127.0.0.1 request_id=1c86ce0d2d5a4bafb500267b530080b5 runtime=28 scheme=http status=204 timestamp=2022-11-26T22:31:33.827262 user= user_agent=goauthentik.io lifecycle Healthcheck`

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.1
 - Deployment: docker-compose

**Additional context**

**Comment by Neon-44** [comment]
ever solved it?

**Comment by JaxzKyd** [comment]
[Yes](https://www.reddit.com/r/selfhosted/comments/10wch2i/authentik_w_caddy/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)

**Comment by Neon-44** [comment]
That worked perfectly

Thanks a lot, appreciate it 🤗
