### ISSUE TITLE
Issue uploading application icons unRaid/Docker

### ISSUE THREAD

**Issue by ConnorEMacLean** [goauthentik/authentik#4109]
**Describe your question/**
Greetings,
Attempting to upload additional icons to my /media directory within Authenik. I successfully did this in the past but am running into an issue uploading an icon for a new application. I did check and see https://goauthentik.io/docs/troubleshooting/image_upload and confirm my permissions on the location look correct. 

**Relevant infos**
I am hosting Authenik on an unRaid system w/ [beryju/authentik:latest](https://hub.docker.com/r/beryju/authentik/) from the Community Apps. 
I have mounted `/media to /mnt/user/appdata/authentik/media/`

**Screenshots**
Media directory
![appicons](https://user-images.githubusercontent.com/47136415/204357509-7e4dd97f-fb7d-4808-ae13-68abca1e23e0.PNG)
Mount within Docker container
![media](https://user-images.githubusercontent.com/47136415/204357512-7895f378-d18c-4f42-8467-802ca42fbf97.PNG)
Example of a working application icon
![UI](https://user-images.githubusercontent.com/47136415/204357514-303d8bec-3bdb-496b-aa9c-836563225676.PNG)
Console output of trying to choose/upload.
![console](https://user-images.githubusercontent.com/47136415/204360408-5aaf3756-f3ac-4e1a-85eb-8f8412b55cf6.PNG)

**Logs**
Apologizes, I'm a bit new still to Docker Compose vs installing via Community Apps so unsure which log files we are looking for here/where to locate those.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.1
 - Deployment: unRaid Community Apps

**Additional context**
I've run chown 1000:1000 media/ & chmod ug+rwx media/ from within the command line within Docker.
Tried uploading on both Chrome and Firefox.
Thanks for any assistance and if there is any additional information I can provide gladly can!

**Comment by BeryJu** [comment]
closed by https://github.com/goauthentik/authentik/commit/d5329432fed9ed2a025ca0f7f3aa0317b44cfa85
