### ISSUE TITLE
Cannot add Plex Social Login 

### ISSUE THREAD

**Issue by priceaj** [goauthentik/authentik#4111]
**Describe the bug**
Cannot add plex social login.

**To Reproduce**
1. Go to Directory > Federation & Social Login
2. Click on create
3. Scroll down to Plex Source
4. Click Next 
5. Fill in the following details:
Name: plex
User Matching mode: "Link to user with identical email...."
Click Load servers
Login with Plex
Uncheck Friends
Check an allowed server
6. Open Flow settings
Authentication flow: default-authentication-flow
Enrollment flow : default-source-enrollment
7. click Finish

Nothing happens, no errors in logs nothing

tried on firefox and chrome

**Expected behavior**
The Plex source to be added

**Logs**
Nothing relevant appears in logs

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.1
 - Deployment: docker-compose

**Additional context**

**Comment by priceaj** [comment]
downgraded to 2022.9 and managed to add Plex as a source

**Comment by BeryJu** [comment]
should be fixed by #4095

**Comment by EuleMitKeule** [comment]
@BeryJu This does not seem to be fixed on `ghcr.io/goauthentik/server:2022.11.4`. I still can not add plex as a source.
