### ISSUE TITLE
Unable to set up plex.tv as source on Authentik

### ISSUE THREAD

**Issue by drkmtr** [goauthentik/authentik#4147]
**Describe the bug**
I've been trying to set up plex.tv as an authentication source in beryju/authentik. But when I am configuring the new source, I provide all of the details, including signing in to Plex, but when click in on the "Finish" button - it does nothing. The documentation for the provider doesn't specify that further information is needed, and the UI isn't telling me that something is missing.. Tried different browsers, clearing cache, etc - just in case its a browser issue, but still the same. Am I missing something?

**To Reproduce**
(https://goauthentik.io/integrations/sources/plex/)
Login as akadmin.
Navigate : Directory > Federation & Social Login
Click "Create"
Select " Plex Source" as type, then click Next
Type a Name and Slug
Tick "Enabled"
Select matching mode "Link users on Unique identifier"
Leave "User path", "icon" and" ClientID" as set by the system
Click on "Load servers", authenticate to plex.tx
Select a server that "a user has to be a member of to be allowed to authenticate."
Click "Finish"

**Expected behavior**
After clicking "finish", following the steps above, it is expected that Authetik will add plex.tv as an authentication source with prescribed parameters. However, the UI does nothing.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3 (docker : beryju/authentik)
 - Deployment: docker on UNRAID 6.11.5

**Comment by Oyo95** [comment]
Hi, 

Same issue. When i want to cleat in create, nothing happens on webui

Version and Deployment (please complete the following information):

    authentik version: 2022.11.3 (docker : beryju/authentik)
    Deployment: docker on Synology 920+ - DSM 7.1.1-42962 Update 1

**Comment by j-insan3** [comment]
Hi, i'm having the same issue. I am using the truechart on a truenas scale.

**Comment by linedpaper** [comment]
Same.  2022.11.3 on Synology 1520+

**Comment by drkmtr** [comment]
Any thoughts on this issue @BeryJu ?

**Comment by testsforaclient** [comment]
Same issue her

**Comment by EuleMitKeule** [comment]
Same issue on `ghcr.io/goauthentik/server:2022.11.3` using docker-compose on Unraid.

**Comment by Oyo95** [comment]
Hi,

Unfortunately, I still have this problem after upgrading. 

authentik version: 2022.11.3 (docker : beryju/authentik)
Deployment: docker on Synology 920+ - DSM 7.1.1-42962 Update 1

**Comment by BeryJu** [comment]
this is fixed by #4095 which will be included in 2022.12.0
