### ISSUE TITLE
Codemirror doesn't always render on Safari

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#4155]
**Describe the bug**
Try to create an invitation from Authentik Admin UI and have it fail with "this field may not be null".

**To Reproduce**
1. Login to Authentik
2. Go to invitations
3. Try to create new one

**Expected behavior**
Successful creation of invitation.

**Screenshots**
![image](https://user-images.githubusercontent.com/1703002/205716376-1e5aca2e-9c20-4004-ba85-cf0be4749dac.png)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3
 - Deployment: Docker Compose via Ansible

**Comment by jsaltzman** [comment]
Are you using safari? I encountered this issue in safari.

**Comment by GenuineJakob** [comment]
I am experiencing the same issue in Safari through most parts of the UI of Authentik.
![Screenshot 2022-12-30 at 18 13 03](https://user-images.githubusercontent.com/37959554/210096157-0d26f0fb-f947-4b69-a00d-37414c05aae0.png)
![Screenshot 2022-12-30 at 18 13 24](https://user-images.githubusercontent.com/37959554/210096161-2667730a-236a-414c-b3c0-318f4edf6587.png)

**Comment by samip5** [comment]
Hmmm, I don't think its stale?

**Comment by samip5** [comment]
Hmmm, I don't think its stale?

**Comment by samip5** [comment]
@BeryJu Could you please look at this? It's an ongoing issue as Safari is among the only ones with proper passwordless hardware auth support?

**Comment by btrepp** [comment]
I spent a while reading the docs and was wondering why I couldn't configure an outpost at all, despite the docs saying I could.

I appreciate dev-time is expensive, a short term help might be having a warning banner at the top if the user is using safari?.
