### ISSUE TITLE
JWT Issuer and JWK endpoint - Proxy Outpost

### ISSUE THREAD

**Issue by regbo** [goauthentik/authentik#4156]
**Describe the bug**
When using the embeded outpost the iss field always has an http://localhost:8080 issuer. Additionally, the well known url (ex:  https://authentik.company.tld/application/o/whoami/.well-known/openid-configuration) contains a jwks_uri field, but the url does not contain any JWK information. (The jwk issue also applies when using a seperate proxy container)

**To Reproduce**
1. Follow this guide: https://goauthentik.io/docs/providers/proxy/forward_auth
2. Visit https://authentik.company.tld/application/o/whoami/.well-known/openid-configuration
3. Observer an empty json string

**Expected behavior**
The jwk uri should be populated and contain public keys that allow jwts to be validated, and the jwt should contain the correct iss field.

**Comment by EHLO1** [comment]
I ran across this recently in a similar scenario, but the symptom was the same, where the JWK was just {}. The solution for me was to set a Signing Key in the OAuth2 Provider Settings:

![image](https://user-images.githubusercontent.com/59938682/213454607-44b66164-749d-4c10-9811-e285c22e1e10.png)

**Comment by regbo** [comment]
Hey, I’ll double check that this is still the case, but this is only and issue when using the built in proxy provider. The issuer will always be local host and the jwks uri will be empty. Even when using a different cert.

**Comment by EHLO1** [comment]
My apologies! I did skip right over the issuer portion.

I am using a reverse proxy (Traefik), configured to forwardAuth to Authentik via its embedded outpost, then using the example middleware to forward authentication to authentik's embedded outpost with the following address:

http://authentik_server:9000/outpost.goauthentik.io/auth/traefik

Where authentik_server is the name of the authentik server container. My configuration is likely not the same, but, I am seeing https://your.domain.com/application/o/whoami/ as the issuer. This guide is for Traefik and Authentik, but even if you use a different reverse proxy, it may help with the configuration within Authentik, or at least shed some light: https://github.com/brokenscripts/authentik_traefik

**Comment by BeryJu** [comment]
The PR above fixes the JWT issuer and the JWKS url pointing to localhost as well as the JWKS url, see #3909 for the JWKS url being empty
