### ISSUE TITLE
synology ldap - failed to connect to ldap server

### ISSUE THREAD

**Issue by badsmoke** [goauthentik/authentik#4164]
**Describe your question/**
hey folks

i am trying to connect a synology to the ldap outpost.

unfortunately the synology tries to find out the base DN automatically, there is problem.

you can not enter the entry manually, as soon as you click it tries to find the base DN.

do you have to enable "anonymous" search in the authentik ldap outpost? is that possible?

i have tested it with an openldap container, so the automatic query works

**Relevant infos**
synology version 7.1.1

**Screenshots**

![image](https://user-images.githubusercontent.com/24853712/205862227-bc997c93-2e78-4da2-b91c-4ad813c80788.png)

![image](https://user-images.githubusercontent.com/24853712/205862034-15604ff2-3f65-4eff-868b-9553044abefb.png)

**Logs**

`authentik_ldap_1  | timestamp="2022-12-06T08:40:02Z" level=warning event="No provider found for request" bindDN= client=10.1.0.181 request=bind requestId=f16e9200-8ab7-4151-a42f-1953c3ed369e
authentik_ldap_1  | timestamp="2022-12-06T08:40:02Z" level=info event="Bind request" bindDN= client=10.1.0.181 requestId=f16e9200-8ab7-4151-a42f-1953c3ed369e took-ms=0`

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3
 - Deployment: docker-compose

**Additional context**

**Comment by romancin** [comment]
Same problem here :( Did you find a solution?

**Comment by badsmoke** [comment]
no have unfortunately also still no solution

**Comment by Cookie-Monster-Coder** [comment]
Same issue. I thought it was my setup. Spent a day trying to troubleshot and even spun up another authentik instance in docker for a fresh setup still a no go. Authelia has no issues with Synology so I wonder what is causing authentik to have problems.

**Comment by pelicangris** [comment]
Hi, i have the same issue and indeed pasting the Base DN and quickly hitting next allows to go a step further.
It then fails with this (apologies, this is in French):
![image](https://user-images.githubusercontent.com/4183405/215273499-0a954b2e-3430-4368-a7e3-998dbc674c86.png)

The LDAP provider in Authentik only maps the users to ObjectClass=user, inetOrgPerson, organisationalPerson and goauthentik/ldap/user where Synology DSM seems to expect ObjectClass=posixAccount.
![image](https://user-images.githubusercontent.com/4183405/215273580-3c0e7930-1b1d-4e0f-9e61-dd0fadf85402.png)

I have tried to amend the filter that Synology DSM is trying to use but this seems to get ignored.
Would there be a way to add posixAccount as an objectClass through a custom mapping in Authentik?

**Comment by eloebl** [comment]
I was thinking a bout this last night after I got ssh public keys working with LDAP from this issue, so it may be possible; https://github.com/goauthentik/authentik/issues/2145

**Comment by eloebl** [comment]
However I think we're running into this issues; https://github.com/goauthentik/authentik/issues/2573

**Comment by eloebl** [comment]
https://www.synology.com/en-ro/dsm/7.1/software_spec/dsm 

```
Synology LDAP client uses objectClass posixAccount for users and objectClass posixGroup for groups by default. If your LDAP server does not support posixAccount or posixGroup, please set up a profile to map the attributes correctly:
User name: posixAccount - uid
User ID: posixAccount - uidNumber
Group name: posixGroup - cn
Group ID: posixGroup - gidNumber
```

**Comment by roche-quentin** [comment]
Hello, I'm building a fix for something Synology.

https://github.com/roche-quentin/authentik

**Comment by eloebl** [comment]
Has anyone been able to get it to work in 2023.3.0 ?  I get further (so no errors to get to the wizard now, thank you!) but it's failing the Check Profile for (objectClass=posixAccount) uid/uidNumber . I see the same thing when I use Apache Directory Studio, I get results for (objectClass=user) but not (objectClass=posixAccount). Thanks!

**Comment by romancin** [comment]
Finally, it works correctly. You have to configure a custom mapping for attributes like this one:

![89A54401-13F0-43BF-85E2-61E2D19BF34A](https://user-images.githubusercontent.com/17579835/225427659-42e77f8a-c79e-4aad-8c69-efd07c9b130a.jpeg)

**Comment by eloebl** [comment]
Thank You!!! That worked!

**Comment by pelicangris** [comment]
I would suggest some slightly different user and group filters to remove authentik service accounts and virtual groups:
User: (&(objectClass=user)(!(goauthentikio-user-service-account=true)))
Group: (objectClass=goauthentik.io/ldap/group)

I am getting errors in the Synology logs when trying to amend the group settings:
synoscgi_SYNO.Core.Group_1_admin_check[9754]: group_is_admin_group.c:161 SYNOGroupGetGID(ldapsearch@goauthentik.io) failed [0x1800 group_get.c:127]

I suspect an attribute is missing on the group but i haven't figured out what is is exactly.

**Comment by jmadden91** [comment]
Hi, @pelicangris, did you ever get your authentik Admin group to correctly map to synology?

**Comment by pelicangris** [comment]
Hi, no i couldn't figure this out and eventually gave up.

**Comment by Cookie-Monster-Coder** [comment]
Just so everyone knows, LDAP is not required anymore.
There is a new "account type" setting in Synology you can set it to local. 
<img width="467" alt="Screenshot 2023-09-28 173038" src="https://github.com/goauthentik/authentik/assets/53286741/078cc2b1-01f3-43e6-8495-886a8c85cff5">
SSO with Authentik now works with Synology without setting up Domain/LDAP. I'm on DSM 7.2-64570 Update 3

**Comment by eloebl** [comment]
> Just so everyone knows, LDAP is not required anymore. There is a new "account type" setting in Synology you can set it to local. <img alt="Screenshot 2023-09-28 173038" width="467" src="https://user-images.githubusercontent.com/53286741/271431665-078cc2b1-01f3-43e6-8495-886a8c85cff5.png"> SSO with Authentik now works with Synology without setting up Domain/LDAP. I'm on DSM 7.2-64570 Update 3

You mind posted a screenshot with the authorization scope and username claim? Thanks!

**Comment by Cookie-Monster-Coder** [comment]
<img width="497" alt="Screenshot 2023-09-28 181654" src="https://github.com/goauthentik/authentik/assets/53286741/76427cf1-2a2b-4ebe-9bdf-e4e2b1d2d198">

I want to see if it's possible to have multiple username claims so one has to match both before being grated access, e.g. `preferred_username,email `. I haven't tried that yet.

**Comment by eloebl** [comment]
> <img alt="Screenshot 2023-09-28 181654" width="497" src="https://user-images.githubusercontent.com/53286741/271437452-76427cf1-2a2b-4ebe-9bdf-e4e2b1d2d198.png">
> I want to see if it's possible to have multiple username claims so one has to match both before being grated access, e.g. `preferred_username,email `. I haven't tried that yet.

Thank you so much! That worked!!! Now to figure out the group permissions :D

**Comment by badsmoke** [comment]
but without ldap users are not automatically created? or am i missing something.

so i still have to create the users beforehand?

**Comment by badsmoke** [comment]
bump

**Comment by RyanTheTechMan** [comment]
I am leaving this here in case anyone else stumbles upon this. (ps. I am an Authentik and LDAP noob. But, I am assuming there are others stuck on this same thing)

Use: `(memberOf=cn=GROUP_NAME_HERE,ou=groups,DC=ldap,DC=authentik,DC=io)`
within the `passwd` in the profile -> filter options in the LDAP settings within Synology DSM.

NOTE: The group name must NOT contain a space. Synology does NOT accept spaces.
Doing this should make Synology create LDAP users only for users who are in a specific group in authentik.

<img width="476" alt="image" src="https://github.com/goauthentik/authentik/assets/13668634/5230f88c-3450-4bc6-bb81-8636d0bed27d">

NOTE: I am not using `(objectClass=group)` within filter->group. You do NOT need it, however, if you know you want to use [Virtual Groups](https://docs.goauthentik.io/docs/providers/ldap/), you need to add `(objectClass=group)` there. Without it it will still pull groups from Authentik. **This can be changed at anytime without losing group permission data configured within Synology.**

In addition to creating the LDAP rule, you can choose to also [setup OpenID](https://docs.goauthentik.io/integrations/services/synology-dsm/), this is NOT required, but it is nice to keep everything under the same SSO.

**Why set up LDAP anyway?**
LDAP with Synology DSM allows you to automatically create accounts within Synology based on the users located on Authentik. Without this, you can still use OpenID with manually created Synology accounts. **Do note that when LDAP is enabled, users can login to DSM and Synology Drive using their LDAP username and password.** This is why you may be interested in restricting what accounts are created in DSM with the `memberOf` shown above.

Last note: When you make changes to groups or LDAP, restart the LDAP container to apply changes instantly. (aka, clear the cache, or just wait)

**Comment by sunmetis** [comment]
Hi I cannot import groups from synology as in authentik. What is the correct filter ? Tried group . That is ok for users not for groups. Groups are in the same cn as Users . How to solve this ? Please
