### ISSUE TITLE
Doesn't use selected web certificate

### ISSUE THREAD

**Issue by arcdigital** [goauthentik/authentik#4182]
**Describe the bug**
I imported a TLS certificate and selected it as the "web certificate" for my tenant. When I go to the URL, the default certificate is still presented. I verified my selection was saved successfully by going back to the edit tenant page and seeing the correct certificate selected. 

**To Reproduce**
1. Import custom TLS certificate and private key
2. Select that certificate as the "web certificate" for a tenant
3. Visit the tenant
4. See that the incorrect certificate is presented

**Expected behavior**
I expected the correct certificate to be presented to my browser.

**Logs**
A few possibly relevant things I found in the logs:
```
{"event":"Starting HTTPS server","level":"info","listen":"0.0.0.0:9443","logger":"authentik.router","timestamp":"2022-12-08T05:37:38Z"}
{"event":"using default, self-signed certificate","level":"trace","logger":"authentik.router","timestamp":"2022-12-08T05:37:38Z"}
{"event":"updating tenant certificates","level":"info","logger":"authentik.router.tenant_tls","timestamp":"2022-12-08T05:37:44Z"}
{"event":"failed to get certificate for ServerName","level":"debug","logger":"authentik.outpost.proxyv2","server-name":"XXXXXX","timestamp":"2022-12-08T05:38:40Z"}
{"event":"failed to get certificate for ServerName","level":"debug","logger":"authentik.outpost.proxyv2","server-name":"XXXXXX","timestamp":"2022-12-08T05:38:46Z"}
```
**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3
 - Deployment: docker-compose

**Additional context**
I tried this with a custom tenant and the default tenant. I confirmed my custom tenant was loading since the correct name showed up in the title. I also tried restarting the server container.

**Comment by arcdigital** [comment]
After a few hours the problem seems to have resolved on its own.

**Comment by g0rbe** [comment]
Can you reopen this issue? Im affected too.
Tried with the default tenant, with a  custom tenant (not set to default) and a custom tenant (set to default).

**Comment by rbooth84** [comment]
I'm also running into the same issue.
