### ISSUE TITLE
Limit number of sessions per user

### ISSUE THREAD

**Issue by myspaghetti** [goauthentik/authentik#4190]
**Is your feature request related to a problem? Please describe.**
This isn't a problem exactly, but I'd rather have a built-in mechanism to invalidade some or all of a user's previous sessions when a user logs in. Some apps are rather resource-intensive and I'd like to be able to use Authentilk to limit the number of sessions per user.

**Describe the solution you'd like**
Add an optional stage to the default login that terminates all previous sessions, or allow setting the "Session duration" to be "until a new session is started" by the same user.

**Describe alternatives you've considered**
Rolling my own stage. That would require delving a little into the guts of Authentik, and I think I need more documentation to do that.

**Additional context**
Thank you for developing this piece of software! Very easy to set up and configure!

**Comment by Lanhild** [comment]
Would very much like this feature
