### ISSUE TITLE
How to set user attributes automatically?

### ISSUE THREAD

**Issue by jacksgt** [goauthentik/authentik#4194]
Hello,

first of all: thanks for this awesome and powerful piece of software!

I'm currently looking into using "App Passwords" combined with OIDC to facilitate login with applications that don't support a web-based login flow for some reason. Hence it is required to use [static authentication](https://goauthentik.io/docs/providers/oauth2/client_credentials#static-authentication) (just username + password).

By default, the app passwords expire after one hour.
In a [previous thread](https://github.com/goauthentik/authentik/issues/1498) it was mentioned that the expiration can be disabled by setting the `token-expires` attribute for a user:

```
goauthentik.io/user/token-expires: false
```

Is it possible to set this attribute automatically for each user that gets created?

**Comment by Juliaria08** [comment]
> depending on your user enrollment flow, you can set that attribute via policy (something like
> 
> ```python
> request.context["prompt_data"]["attributes"] = {"goauthentik.io/user/token-expires": false}
> return True
> ```
> 
> or via property mappings (when importing from LDAP). The other option would be to trigger a policy on the user_write event, however I'm not 100% sure if that would work and not trigger an infinite loop

If it triggered the policy again you'd just need to add a check to validate if the atribute is set as wanted, and if so `return` instead of writing to the policy again?, (haven't tested, just a thought)
