### ISSUE TITLE
LDAP search only returning bind user

### ISSUE THREAD

**Issue by brianclemens** [goauthentik/authentik#4195]
**Describe your question**
Filed as a question rather than a bug, because I assume I'm doing something wrong here. I am attempting to use an Authentik LDAP provider for ejabberd authentication.

There are two accounts in the xmpp group that the provider is assigned to. However, when doing an LDAP search, I am only able to see the bind user. For example, `ldapsearch -x -h ak-outpost-ldap.authentik.svc.cluster.local -p 389 -D 'cn=ejabberd,ou=users,dc=xmpp,dc=domain,dc=com' -w 'password' -b 'ou=users,dc=xmpp,dc=domain,dc=com' '(objectClass=user)'` only returns an entry for the `ejabberd` service account user. Similarly, when I try doing an LDAP search with another user as the bind user, I only get an entry for that user, and don't see the `ejabberd` user.

How do I get Authentik to return the search with both the users listed?

**Relevant infos**
ejabberd 22.10, however the behavior is also replicated with ldapsearch as shown above.

**Logs**
ejabberd:
```
/opt/ejabberd $ ejabberdctl registered_users domain.com

ejabberd
```
Authentik:
```
2022-12-11T22:13:04+09:00 {"baseDN":"ou=users,dc=xmpp,dc=domain,dc=com","bindDN":"cn=ejabberd,ou=users,dc=xmpp,dc=domain,dc=com","client":"10.42.3.66","event":"Search request","filter":"(sAMAccountName=*)","level":"info","requestId":"cf8080a4-5399-4dc0-a5a4-f0aa7c55d4da","scope":"Whole Subtree","timestamp":"2022-12-11T13:13:04Z","took-ms":0}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3
 - Deployment: Helm

**Comment by BeryJu** [comment]
the LDAP outpost will only return all users when the bind user is in User group which is configured in the LDAP outpost as "search group"

This is to prevent any authentik authenticated-user to get all users

**Comment by jennydaman** [comment]
I was having this issue too, disabling cache helped to fix it.

![image](https://github.com/goauthentik/authentik/assets/20404439/b075d77f-3a6a-4ac8-867f-d0ef034c49b6)
