### ISSUE TITLE
Enable web3 login through user's wallet

### ISSUE THREAD

**Issue by pdarcos** [goauthentik/authentik#4225]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to login without the usual web2 creds flow. Thankfully there are more and more open source libraries that can be used to login to web3 Dapps which I think would be a great addition to authentik

**Describe the solution you'd like**
Enable users to authenticate with just their crypto wallet

**Describe alternatives you've considered**
None really

**Additional context**
There are many open source libraries that are used for this. One example is https://docs.walletconnect.com/2.0/introduction/auth

**Comment by BeryJu** [comment]
Thank you for your feature request. We appreciate your suggestion and the thought you put into it. However, after careful consideration, we have decided not to implement this feature at this time.

There are a few reasons for this decision. Firstly, we believe that the feature you have suggested is not aligned with the overall vision and goals of our product. Additionally, we feel that this feature may not be well received by our user base and could potentially alienate some of our customers.

We understand that this may be disappointing to hear, but we appreciate your understanding and look forward to hearing any other suggestions or feedback you may have in the future.

**Comment by pdarcos** [comment]
Ok, understood. Too bad since I believe web3 logins are going to become the norm.

Thanks for taking my suggestion into consideration

**Comment by DRSchlaubi** [comment]
@pdarcos there is an OIDC compatible version of this on login.xyz

You can simply use the OIDC generic auth source with this metadata url: `https://oidc.signinwithethereum.org/.well-known/openid-configuration`

Client registration is described here: https://docs.login.xyz/servers/oidc-provider/hosted-oidc-provider#openid-connect-provider-configuration
