### ISSUE TITLE
Set redirection url for invalidation logout flow

### ISSUE THREAD

**Issue by MrMuster** [goauthentik/authentik#4248]
**Is your feature request related to a problem? Please describe.**
If a user logs out from any service, the user is always redirected back to the login page.
For some sevices like vikunja the user got logged in directly after the logout again.
Sometimes it is also desired to redirect the user to a specific url after the logout.

**Describe the solution you'd like**
It would be very convenient to specify a url the user should be redirected to in the invalidation flow.

**Comment by MrMuster** [comment]
This could be solved theoretically by setting the `redirect` variable using a policy.
Related issues: https://github.com/goauthentik/authentik/issues/1677 and https://github.com/goauthentik/authentik/issues/1203 .
But unfortunately this is not working in version  2022.12.1.

This is how I created the policy for the login flow:
![redirect-policy](https://user-images.githubusercontent.com/116727180/210759495-fe136319-7609-45e9-8010-d78010cf7336.png)
![login_stage_binding](https://user-images.githubusercontent.com/116727180/210760163-55a8cb93-5194-431b-b2df-c308c9ee3eb7.png)
![login_flow](https://user-images.githubusercontent.com/116727180/210759403-63308755-79f9-415a-96a5-6e9bb3adb183.png)
And the same for the logout flow:
![logout_stages](https://user-images.githubusercontent.com/116727180/210760481-5005470d-535a-4e69-bcce-f6087a142a87.png)
![logout_flow](https://user-images.githubusercontent.com/116727180/210760520-47c70bac-22c9-4012-a271-08728ff45750.png)

Neither of both is working.
As seen in the event logs, the `redirect` variable is set successfully: 
![logout_log](https://user-images.githubusercontent.com/116727180/210760838-38914e23-ddde-4397-a7df-fed116c56097.png)

The log of the policy execution also looks fine:
```
2023-01-05T10:00:54.725209278Z {'action': 'policy_execution',
 'auth_via': 'session',
 'client_ip': 'X.X.X.X',
 'context': {'binding': {'app': 'authentik_policies',
   'model_name': 'policybinding',
   'name': 'Binding from Flow-stage binding #0 to 3f97d56d-f9cc-4f98-9b44-769f6767c112 #0 to Policy redirect-policy',
   'pk': 'e670e05880cb472f929e24008c98ed0e'},
  'http_request': {'args': {'query': ''},
   'method': 'GET',
   'path': '/api/v3/flows/executor/default-invalidation-flow/'},
  'message': 'Policy Execution',
  'policy_uuid': '0c8563bd6bac4c598de9402e126db640',
  'request': {'context': {'flow_plan': {'bindings': [{'app': 'authentik_flows',
       'model_name': 'flowstagebinding',
       'name': 'Flow-stage binding #0 to 3f97d56d-f9cc-4f98-9b44-769f6767c112',
       'pk': 'f201bba2cbb146b2ad7b2204c10effcc'}],
     'context': {},
     'flow_pk': '3f97d56df9cc4f989b44769f6767c112',
     'markers': [{'binding': {'app': 'authentik_flows',
        'model_name': 'flowstagebinding',
        'name': 'Flow-stage binding #0 to 3f97d56d-f9cc-4f98-9b44-769f6767c112',
        'pk': 'f201bba2cbb146b2ad7b2204c10effcc'}}]},
    'redirect': 'https://example.com'},
   'debug': False,
   'http_request': None,
   'obj': {'app': 'authentik_flows',
    'model_name': 'flowstagebinding',
    'name': 'Flow-stage binding #0 to 3f97d56d-f9cc-4f98-9b44-769f6767c112',
    'pk': 'f201bba2cbb146b2ad7b2204c10effcc'},
   'user': {'email': 'muster@example.com', 'pk': 4, 'username': 'test'}},
  'result': {'log_messages': [],
   'messages': [],
   'passing': True,
   'source_binding': None,
   'source_results': []}},
 'event': 'Created Event',
 'host': 'authentik.example.com',
 'level': 'info',
 'logger': 'authentik.events.models',
 'pid': 42742,
 'request_id': 'dddb9aef304b4397a50f2d07acbc08e4',
 'timestamp': '2023-01-05T10:00:54.722518',
 'user': {'email': 'muster@example.com', 'pk': 4, 'username': 'test'}}
```

**Comment by MrMuster** [comment]
I could solve it:
```
context['flow_plan'].context['redirect'] = 'https://example.com'
return True
```
This should be fixed in the docs: https://goauthentik.io/docs/policies/expression

**Comment by skiwheelr** [comment]
<img width="1051" alt="Screen Shot 2023-07-29 at 7 37 34 PM" src="https://github.com/goauthentik/authentik/assets/16263861/09b5447d-3b77-4901-8af2-32263f8f52c8">
my redirect is not defined, everything was done exactly like above

**Comment by Ctrl-Alt-Delight** [comment]
> my redirect is not defined, everything was done exactly like above it seems my policy comes BEFORE the flow

@skiwheelr: It looks like you are setting a Flow policy rather than a policy on the stage

Thanks to this thread I was able to piece together what I wanted which was to be able to set a redirect GET param. This is my resulting Policy Expression:

```
from django.http import QueryDict
from urllib.parse import urlparse 
import re

def uri_validator(x):
    try:
        result = urlparse(x)
        return all([result.scheme, result.netloc])
    except:
        return False
        
def check_redirect_uri(redirect_uri):
    try:
        return any(re.fullmatch(x, redirect_uri,flags=re.IGNORECASE) for x in allowed_redirect_urls)
    except:
        return False
        
def set_flow_redirect(redirect):
    if redirect is not None:
        if not all([uri_validator(redirect),check_redirect_uri(redirect)]):
            if use_default_redirect:
                redirect = default_return_url
            else:
                return True
        context['flow_plan'].context['redirect'] = redirect

allowed_redirect_urls = [".*"]
default_return_url = "https://example.com"
use_default_redirect = True
redirect_param = "redirect"    
redirect_url = QueryDict(request.http_request.GET.get("query")).get(redirect_param)
set_flow_redirect(redirect_url)

return True
```

Hope it helps someone

**Comment by ali-whizz** [comment]
> my redirect is not defined, everything was done exactly like above it seems my policy comes BEFORE the flow which is why i get 'flow_plan' not defined <img alt="Screen Shot 2023-07-29 at 8 13 19 PM" width="610" src="https://private-user-images.githubusercontent.com/16263861/257000929-6c63ce48-3386-4f99-8c3f-f6764231cc68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTg3MTIsIm5iZiI6MTcxOTMxODQxMiwicGF0aCI6Ii8xNjI2Mzg2MS8yNTcwMDA5MjktNmM2M2NlNDgtMzM4Ni00Zjk5LThjM2YtZjY3NjQyMzFjYzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDEyMjY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNmY5YjY1ZGMyYzRkM2Y2MjY3N2M1MWUyYmQyYTI5NDY4ZDAyZjE4NTZmNzlmMzAyYjRhNGUxMDQ4ZDk0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5SdTDN1bPLG6HoOgP-KhUC0oF3w_7jlz9npWKEjloc">
> 
> <img alt="Screen Shot 2023-07-29 at 7 37 34 PM" width="1051" src="https://private-user-images.githubusercontent.com/16263861/256998943-09b5447d-3b77-4901-8af2-32263f8f52c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTg3MTIsIm5iZiI6MTcxOTMxODQxMiwicGF0aCI6Ii8xNjI2Mzg2MS8yNTY5OTg5NDMtMDliNTQ0N2QtM2I3Ny00OTAxLThhZjItMzIyNjNmOGY1MmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDEyMjY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNzBlNDQ5NWQ5ODBlNTJhZWRiNDEwYTQ3MjBiOGQ3NTgwNWY4YWJmMWE0OThmOGJkMzNkODcxZTYzZWMyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lSKo_lxejKbZhEOXRm5B63MLMwNAT2kYSsI7XesJBPQ">

bro i was facing the same issue but got the solution. 
you are creating the policy on the flow not on the stage. 
Go to policy/group/user tab and delete that policy 
and then click on Stage binding tab. In the stage row you will see a arrow 
![image](https://github.com/goauthentik/authentik/assets/168444813/7ffd4189-f84c-44c3-a494-a4e111fd5301)
and then click on arrow it will allow you cretae the policy inside that stage then you will get the straight flow as per expected like that 
![image](https://github.com/goauthentik/authentik/assets/168444813/c7a2596d-1030-4108-9542-7b11ffe0ad6f)

**Comment by thefiredragon** [comment]
Is there a documentation to set the correct post logout uri? 
One of our service need this to correctly sign out users. I've tried the policy under stages which has currently no effect.
best Regards

**Comment by programmer-pns** [comment]
@thefiredragon I can confirm that. But no idea how someday I was able to get the redirection to the test url http://localhost:4200 When I tried changing the domain to the intended one I got no redirection. Again when I updated back to test url I got no redirection and still unable to solve this. Do you find any solution for the same? 

@BeryJu Requesting your concern on this.

**Comment by kalinjul** [comment]
context['flow_plan'].context['redirect'] = redirect
didn't work at all.
```context['flow_plan'].redirect(redirect)``` worked for me, but i have no idea if this the correct way..
