### ISSUE TITLE
FR: Add API endpoints for adding/removing user from groups

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#4252]
**Is your feature request related to a problem? Please describe.**
I'm really frustrated with how the API currently is constructed with regards to managing users and groups.

**Describe the solution you'd like**
I would like to be able to safely add and remove user by id or name from a group without having to patch the group fully which is an expensive operation if the group has 300+ users and very error prune.

**Describe alternatives you've considered**
There is none.

**Additional context**

I would want to add/remove a single user per APi call to the group or multiple removals/adds in a single query without having to patch the whole group to do so.

Somewhat related to #4251

**Comment by burner-** [comment]
+1 this definedly need that.

**Comment by samip5** [comment]
@BeryJu Why was it decided that it's a good thing to use the pk-numbers for the adding and removing a user from a group? I would like to use username or email rather than that.
