### ISSUE TITLE
Usage of Authentik on separate servers

### ISSUE THREAD

**Issue by audciz** [goauthentik/authentik#4253]
**Describe your question/**
Hello!
Is it possible to use Authentik for authorization on separate servers?

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.11.3
 - Deployment: docker-compose

**Additional context**
I have a server with Authentik installed. I've tried to install and integrate Outpost using Manual Outpost deployment in docker-compose on a separate server, but I receive error "no app for hostname" when I make a request to deployment from the same server, and I get status "Unhealthy" from the main Authentik deployment in Outpost Integrations section.

**Comment by RedJohn14** [comment]
Any news on this? Also interested for me.

**Comment by BeryJu** [comment]
Outposts can be installed on any server, as long as they can communicate with the authentik API. The "no app for hostname" error is most commonly caused by a reverse proxy misconfiguration, see https://docs.goauthentik.io/docs/providers/proxy/forward_auth
