### ISSUE TITLE
Error configuring SMTP for email

### ISSUE THREAD

**Issue by jsaltzman** [goauthentik/authentik#4265]
I am trying to send a test email (so I can get password reset working) but I get error 99. My my redacted environment variables are below as well as a log.

Environment Variables
  -e 'AUTHENTIK_EMAIL__HOST'='smtp.mail.me.com'
  -e 'AUTHENTIK_EMAIL__PORT'='587'
  -e 'AUTHENTIK_EMAIL__USERNAME'='[icloud email]'
  -e 'AUTHENTIK_EMAIL__PASSWORD'=' [icloud app specific password]
  -e 'AUTHENTIK_EMAIL__USE_TLS'='true'
  -e 'AUTHENTIK_EMAIL__USE_SSL'='false'
  -e 'AUTHENTIK_EMAIL__TIMEOUT'='10'
  -e 'AUTHENTIK_EMAIL__FROM'='[icloud email]'

Log: https://pastebin.com/r5y1QQGE

I tried a working gmail config from authelia and got the same error. Hoping I can get this working for password reset!

**Comment by g0rbe** [comment]
My configs are in the `.env` file and works like a charm.

**Comment by jsaltzman** [comment]
I do not have a .env file, but I used the config here:https://goauthentik.io/docs/installation/docker-compose

I also have Authelia up and email works on Authelia. So I do not think this is a case of my ISP blocking SMTP somehow.

**Comment by jsaltzman** [comment]
Separately from the email issue I fixed my GEOIP config within docker (it was misconfigured) and now email may be working. I am doing some additional investigation BUT I think it is possible that this a true bug: email would not send if GEOIP was misconfigured.

**Comment by jsaltzman** [comment]
I got this working but am using an ENV file. I think this was some combination of: GEOIP, using an env file, not having matching environment variables for worker and main docker container, and some nuances with iCloud SMTP.
