### ISSUE TITLE
Invitation Flow Does Not Work Unless "Continue flow without an invitation" is checked

### ISSUE THREAD

**Issue by jsaltzman** [goauthentik/authentik#4278]
**Describe the bug**
I set up an invitation flow using invite links using the following video: https://youtu.be/mGOTpRfulfQ but I get an unknown error unless I check "Continue flow without invitation" in my invitation stage

**To Reproduce**
1. I created a new enrollment invitation flow with the following states: an invitation stage, a prompt stage to enter user info, a user write stage, and a user login stage.
2. When I go to directory > invitations to create a new invite link I get an unknown error. 
3. If I edit my invitation stage to "continue flow without invitation" then the invite links now work. But this is unintended.

**Expected behavior**
My invite links should work without needing to turn on "Continue flow without invitation.

**Screenshots**

**Logs**

**Version and Deployment (please complete the following information):**
 - 2022.11.4
 - Deployed using docker on Unraid.

**Additional context**

**Comment by sdimovv** [comment]
Did you happen to select a flow for which the invitation is valid?
![image](https://user-images.githubusercontent.com/36302090/209480376-ee5a9802-b6e4-45a1-ac6e-92eadb29e6cc.png)

This option was added in 2022.11.4 to mitigate a security vulnerability. 

I had a similar issue when I selected a flow for which the invitation is valid. Even though I was using the selected in the invitation flow, the logs still showed something like "invitation is not valid for the current flow". 

I wasn't sure if I have encountered a bug or it was a misconfiguration of some kind on my side. In any case it fixed itself when I disselected the flow binding from the invitation (i.e. made the invitation valid for all flows).

Can you confirm if you have the same issue?

**Comment by jsaltzman** [comment]
Selecting the correct flow gives me the error. Getting rid of the selection (leaving it --) fixes my issue.
