### ISSUE TITLE
PAGE_SIZE 100 | Request to jira\ldap

### ISSUE THREAD

**Issue by Skurat** [goauthentik/authentik#4292]
Good day.
As I understand it, the PAGE_SIZE variable is 100 in the file authentik/root/setting.py is bound to the web interface and to the request api.
When requesting users from Jira, the number is equal to the PAGE_SIZE variable, the request does not retrieve all users and groups.
Can you share this value or fix this problem?

**Comment by lupin3rd** [comment]
I confirm the "problem". If i use LDAP outpost it retrive only 100 users .
