### ISSUE TITLE
Authentik fails to connect to PostgreSQL 15.1

### ISSUE THREAD

**Issue by luisnabais** [goauthentik/authentik#4313]
**Describe the bug**
I'm running Postgres 15.1 in a Raspberry Pi 4 (ARM64) and now running ghcr.io/goauthentik/server:2022.12.0 with Docker Compose.
I haven't tried PostgreSQL 15.0, just 15.1.

The error I have is both in server and worker:
{"event": "PostgreSQL connection failed, retrying... (SCRAM authentication requires libpq version 10 or above\n)", "level": "info", "logger": "authentik.lib.config", "timestamp": 1672404885.720217}

**To Reproduce**
Run Authentik with PostgreSQL 15.1, regardless of being on the same docker-compose.yml or separate services.

**Expected behavior**
Connection successful to PostgreSQL.

**Logs**
Output of docker-compose logs:
{"event": "PostgreSQL connection failed, retrying... (SCRAM authentication requires libpq version 10 or above\n)", "level": "info", "logger": "authentik.lib.config", "timestamp": 1672404885.720217}

**Version and Deployment:**
 - authentik version: 2022.12.0
 - Deployment: docker-compose

**Comment by luisnabais** [comment]
The issue remains with authentik 2022.12.1 and 2022.12.2

**Comment by ranomier** [comment]
I think this is more an enhancement, then a bug.

Is  postgresql 15 even supported? The docker-compose file still uses 12, which is supported until 2024-11-14.

**Comment by BeryJu** [comment]
This seems to be specific to Postgres > 12 and ARM, there are several github issues for psycopg2 for that. Psycopg3 should fix this, however it is not compatible with django yet. A way around this would be to build psycopg2 from source in the container build but I'd rather not do that if possible.

There's no explicit version requirement for postgres, anything 12+ should work, the reason why the compose file still uses 12 is because upgrading postgres in docker is quite painful (binaries from both $oldVersion and $newVersion need to be available), but when PostgreSQL 16 comes out that'll likely be the new default

**Comment by luisnabais** [comment]
> I think this is more an enhancement, then a bug.
> 
> Is postgresql 15 even supported? The docker-compose file still uses 12, which is supported until 2024-11-14.

It's a bug, as there is nothing on the documentation specifying limitations in Postgres version.


> This seems to be specific to Postgres > 12 and ARM, there are several github issues for psycopg2 for that. Psycopg3 should fix this, however it is not compatible with django yet. A way around this would be to build psycopg2 from source in the container build but I'd rather not do that if possible.
> 
> There's no explicit version requirement for postgres, anything 12+ should work, the reason why the compose file still uses 12 is because upgrading postgres in docker is quite painful (binaries from both $oldVersion and $newVersion need to be available), but when PostgreSQL 16 comes out that'll likely be the new default

Thank you for your answer. If I understood correctly, the issue is related only to the ARM version, x86_64 should work, right?
What's your suggestion for me to solve this? I don't mind creating a step in Dockerfile to build something, if needed, I just need a bit of guidance.
Which image do you suggest to build psycopg2? The latest stable Python? Or other?

Thank you

**Comment by BeryJu** [comment]
Django 4.2 Alpha 1 was just announced which adds support for psycopg3, so this might be the easier route than shipping authentik with a custom built psycopg2 install (https://docs.djangoproject.com/en/dev/releases/4.2/#psycopg-3-support)

**Comment by BeryJu** [comment]
I'm not suggesting authentik to use an alpha version, more so saying that this will soon be solved with that

**Comment by septatrix** [comment]
> There's no explicit version requirement for postgres, anything 12+ should work, the reason why the compose file still uses 12 is because upgrading postgres in docker is quite painful (binaries from both $oldVersion and $newVersion need to be available), but when PostgreSQL 16 comes out that'll likely be the new default

This is greatly simplified when using `pg_upgrade`. Simply stop the cluster, pull the newer image and start an ephemeral container with the volume mounted, perform the upgrade, replace the version number in the docker-compose and bring it up again.

**Comment by luisnabais** [comment]
> > There's no explicit version requirement for postgres, anything 12+ should work, the reason why the compose file still uses 12 is because upgrading postgres in docker is quite painful (binaries from both $oldVersion and $newVersion need to be available), but when PostgreSQL 16 comes out that'll likely be the new default
> 
> This is greatly simplified when using `pg_upgrade`. Simply stop the cluster, pull the newer image and start an ephemeral container with the volume mounted, perform the upgrade, replace the version number in the docker-compose and bring it up again.

And we can have two postgres instances running in two different containers, one with the old version and the other with the new, pointing to the same data, so the upgrade is very simple.

**Comment by codestation** [comment]
A workaround is to switch the password encryption for the user to md5. For example:

```sql
alter system set password_encryption = 'md5'; -- set the password encryption to md5
select pg_reload_conf(); -- reload config
alter user authentik with password 'mypassword'; --update the password so the hash is saved in md5 format
alter system reset password_encryption; -- restore the setting to don't affect other users
select pg_reload_conf(); -- reload config
```

You can check the current password hash with 

```sql
select rolname, rolpassword from pg_authid where rolname = 'authentik';
```

It should start with md5 so the connection doesn't fail.

**Comment by BeryJu** [comment]
It seems that psycopg2 2.9.6 also fixes this

```
Package manylinux 2014 for aarch64 and ppc64le platforms, in order to include libpq 15 in the binary package (🎫[#1396](https://github.com/psycopg/psycopg2/issues/1396)).
```
