### ISSUE TITLE
Wrong placeholders in user Update details

### ISSUE THREAD

**Issue by fuomag9** [goauthentik/authentik#4317]
**Describe the bug**
After #4297 got fixed, there have been wrong data placeholders in user Update details and the `Admin email` placeholder is used for every user even when they are not an admin

**To Reproduce**

1. Go to https://example.com/if/user/#/settings
2. Click on Update details
3. See error

**Expected behavior**
Placeholders should use the correct context data

**Screenshots**

![image](https://user-images.githubusercontent.com/1580624/210148951-9311a807-9e56-4951-893a-1f97a144ad2f.png)
![image](https://user-images.githubusercontent.com/1580624/210148979-9844c33e-2d5b-4c3b-88a1-981bd3ef00ce.png)

**Logs**
None relevant

**Version and Deployment (please complete the following information):**
 - authentik version: `2022.12.1`
 - Deployment: `docker-compose`

**Additional context**
It was not like this before

**Comment by sdimovv** [comment]
I think that got fixed recently (https://github.com/goauthentik/authentik/commit/9d422918b34ee7c49b98a27b0fa51eb72da8691f)

Can you still reproduce this with `gh-next`/`gh-main`?

**Comment by fuomag9** [comment]
I can still replicate this in `gh-next` deployed as per instructions here https://goauthentik.io/docs/installation/beta

**Comment by sdimovv** [comment]
Weird. I am unable to reproduce this on a stock authentik instance.

Can you try spinning up a stock instance with a new DB from `gh-main`?  Deployment is the same as `gh-next`, just change the tag to `gh-main.

**Comment by fuomag9** [comment]
> Weird. I am unable to reproduce this on a stock authentik instance.
> 
> Can you try spinning up a stock instance with a new DB from `gh-main`? Deployment is the same as `gh-next`, just change the tag to `gh-main`.
> 
> Also, if you have previously downloaded those images, you may need to `docker compose down`, delete them manually (`docker image rm ...`), and then `docker compose up` again to force docker to download new(er) images.

A clean instance does indeed not exhibit that issue, but if I downgrade only the `Admin email` remains broken and the `username` becomes correct again

Upgrading to both `gh-main` and `gh-next` does not seem to fix the issue on the production instance

**Comment by fuomag9** [comment]
Updated production to `2023.1.0`, `Username` is now correct again but `Email` is still shown as `Admin email`

**Comment by BeryJu** [comment]
This was caused by the OOB flow's email field overwriting the default user settings email field
