### ISSUE TITLE
"No pending user" error with complex user settings flow

### ISSUE THREAD

**Issue by sdimovv** [goauthentik/authentik#4318]
**Describe the bug**
When a user settings flow contains a stage that is not supported by the stripped down user settings flow executor and the full featured flow executor must be opened an error is displayed stating "No pending user". 

**To Reproduce**
1. Start with a stock authentik instance
2. Add an email verification stage to the default user settings flow (after the prompt stage and before the user write stage)
3. Go to the user settings page
4. Execute the flow
5. Click on the "Open settings" button
6. Observe an error notification with text "No pending user"
7. (OPTIONAL) Fill in all fields and click continue
8. (OPTIONAL) Observe the emaill stage failing, due to the lack of a pending user attribute.

**Expected behavior**
No error and email stage succeeding.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/36302090/210151062-5e863c4d-fed7-419a-a0fb-fffbdcf06d5c.png)

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.1 and gh-main
 - Deployment: docker-compose

**Additional context**
N/A

**Comment by rulim34** [comment]
@BeryJu I'm still getting that error with similar flow
