### ISSUE TITLE
3rd Party Captchas do not load

### ISSUE THREAD

**Issue by akoyaxd** [goauthentik/authentik#4321]
**Describe the bug**
After Setting up hCaptcha I get stuck in an infinite loading at the captcha stage.

**To Reproduce**
* Set up hCpatcha acordingly, as described in the docs.
* Run your flow with the hcaptcha stage
* See the hcaptcha stage get stuck loading indefinetly

**Expected behavior**
I get a hcaptcha challange.

**Screenshots**
![image](https://user-images.githubusercontent.com/22196236/210177373-0f3148b0-a2d9-4fb1-9081-7fdd533bfe70.png)
![image](https://user-images.githubusercontent.com/22196236/210177441-7e253166-2ccc-483b-bfde-898aabf33f54.png)
![image](https://user-images.githubusercontent.com/22196236/210177452-dff25087-182b-401d-85b9-d109e17b9bc7.png)

**Logs**
I'll provide if needed.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.1
 - Deployment: docker-compose (portainer) with nginx reverse proxy

**Additional context**
Discussion on Discord: https://discord.com/channels/809154715984199690/1058751960674734100

Followup from #2407

**Comment by PKizzle** [comment]
I have the same issue using a kubernetes deployment (helm) and the Turnstile captcha provider
