### ISSUE TITLE
Basic auth doesn't work

### ISSUE THREAD

**Issue by FunDeckHermit** [goauthentik/authentik#4336]
**Describe the bug**
I'm using Prowlarr and it forces basic auth on the user. Using the pretty GUI to set the username/password it fails to set the header correctly. 

**To Reproduce**
1. Run Prowlarr with user/pass -> admin/adminadmin
2. Setup application + proxy provider
3. Enable basic authentication and set credentials
4. Check Prowlarr log, it suddenly **knows** the email of the user in Authentik.
![image](https://user-images.githubusercontent.com/5075692/210265890-0c3239ba-a26c-4bd6-aa36-8d2f19ce44ca.png)

**Expected behavior**
Logging in with admin/adminadmin

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12
 - Deployment: docker-compose

**Additional context**
I made a scope to hard-code admin/adminadmin in the authentication header. This fixes the problem for me. So the credentials aren't propegated somewhere between pretty GUI and back-end. 
![image](https://user-images.githubusercontent.com/5075692/210266059-182ecea5-3126-47da-aa3b-aab3707bb36d.png)
```

return {
    "ak_proxy": {
        "user_attributes": {
            "additionalHeaders": {
                "Authorization": "Basic YWRtaW46YWRtaW5hZG1pbg=="
            }
        }
    }
}
```

**Comment by mattisz** [comment]
@FunDeckHermit are you entering the actual username and password in the proxy configuration? Or are you using keys that map to either a user or a group? I am also using docker-compose for my setup and am running the latest version of authentik (2022.12) with no issues. 

Here's my set up:
![sh1](https://user-images.githubusercontent.com/104524322/210667563-68e3f062-11f9-49b5-aea3-d0754eb84b5d.png)

![sh2](https://user-images.githubusercontent.com/104524322/210668051-f983a965-4703-4ed0-b9ff-7148d6554f5e.png)

This is a "Forward auth (single application)" provider so I'm not sure if things are different with the other 2 proxy provider types.

I did have to add a little to the default nginx configuration that authentik provides to make this work. However, I don't think that's your issue considering your scope solution works for you (it didn't for me which is when I realized my reverse proxy was the issue).

Additions under `location / {`
`auth_request_set $authentik_auth $upstream_http_authorization;`
`proxy_set_header Authorization $authentik_auth;`

**Comment by FunDeckHermit** [comment]
Hello @mattisz,

I'm using a proxy provider with an embedded proxy outpost to reach Prowlarr. The username/password is fixed to admin/adminadmin without any variables. 

The scope solution seemed to work at first but it might just be a cookie that was set. The scope solution doesn't forward my Authentik username, so that's good. 

My main concern by opening this bug is that my email was send to an application in the auth header without me knowing.

**Comment by adamzvolanek** [comment]
I am running into a similar issue with sonarr. I followed the respective [sonarr ](https://goauthentik.io/integrations/services/sonarr/) flavor of the instructions and at a loss why it continues to prompt for username and password in a freshly cleared of history/cookies, etc. Chrome incognito browser. 

Here is my Proxy Provider
![image](https://user-images.githubusercontent.com/80661527/211127891-c727341a-a918-4999-91e8-14a83b1d738f.png)

Group attributes and member account tied
![image](https://user-images.githubusercontent.com/80661527/211127923-07b9651e-cde0-4573-9fda-625291af785e.png)

Sonarr setup
![image](https://user-images.githubusercontent.com/80661527/211127949-280405d2-bb8e-4d43-88c1-874c12e58545.png)


Let me know where I am going wrong?

**Comment by casabryant** [comment]
Sorry to reply to an old issue. Just wanted to add that this chain finally got my issue straightened out.

I was having no luck getting basic auth to forward at all, but I'm using linuxserver.io's SWAG image as my reverse proxy. Turns out I had to add those 2 lines to my nginx/authentik-location.conf file in the SWAG container, final version looking like this:

```
## Version 2023/04/27 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/nginx/authentik-location.conf.sample
# Make sure that your authentik container is in the same user defined bridge network and is named authentik-server
# Rename /config/nginx/proxy-confs/authentik.subdomain.conf.sample to /config/nginx/proxy-confs/authentik.subdomain.conf

## Send a subrequest to Authentik to verify if the user is authenticated and has permission to access the resource
auth_request /outpost.goauthentik.io/auth/nginx;
## If the subreqest returns 200 pass to the backend, if the subrequest returns 401 redirect to the portal
error_page 401 = @goauthentik_proxy_signin;

## Translate the user information response headers from the auth subrequest into variables
auth_request_set $authentik_email $upstream_http_x_authentik_email;
auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
auth_request_set $authentik_name $upstream_http_x_authentik_name;
auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
auth_request_set $authentik_username $upstream_http_x_authentik_username;
auth_request_set $authentik_auth $upstream_http_authorization; #had to add this

## Inject the user information into the request made to the actual upstream
proxy_set_header X-authentik-email $authentik_email;
proxy_set_header X-authentik-groups $authentik_groups;
proxy_set_header X-authentik-name $authentik_name;
proxy_set_header X-authentik-uid $authentik_uid;
proxy_set_header X-authentik-username $authentik_username;
proxy_set_header Authorization $authentik_auth; #had to add this

## Translate the Set-Cookie response header from the auth subrequest into a variable
auth_request_set $set_cookie $upstream_http_set_cookie;
```

**Comment by keesfluitman** [comment]
> Sorry to reply to an old issue. Just wanted to add that this chain finally got my issue straightened out.
> 
> I was having no luck getting basic auth to forward at all, but I'm using linuxserver.io's SWAG image as my reverse proxy. Turns out I had to add those 2 lines to my nginx/authentik-location.conf file in the SWAG container, final version looking like this:
> 
> ```
> ## Version 2023/04/27 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/nginx/authentik-location.conf.sample
> # Make sure that your authentik container is in the same user defined bridge network and is named authentik-server
> # Rename /config/nginx/proxy-confs/authentik.subdomain.conf.sample to /config/nginx/proxy-confs/authentik.subdomain.conf
> 
> ## Send a subrequest to Authentik to verify if the user is authenticated and has permission to access the resource
> auth_request /outpost.goauthentik.io/auth/nginx;
> ## If the subreqest returns 200 pass to the backend, if the subrequest returns 401 redirect to the portal
> error_page 401 = @goauthentik_proxy_signin;
> 
> ## Translate the user information response headers from the auth subrequest into variables
> auth_request_set $authentik_email $upstream_http_x_authentik_email;
> auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
> auth_request_set $authentik_name $upstream_http_x_authentik_name;
> auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
> auth_request_set $authentik_username $upstream_http_x_authentik_username;
> auth_request_set $authentik_auth $upstream_http_authorization; #had to add this
> 
> ## Inject the user information into the request made to the actual upstream
> proxy_set_header X-authentik-email $authentik_email;
> proxy_set_header X-authentik-groups $authentik_groups;
> proxy_set_header X-authentik-name $authentik_name;
> proxy_set_header X-authentik-uid $authentik_uid;
> proxy_set_header X-authentik-username $authentik_username;
> proxy_set_header Authorization $authentik_auth; #had to add this
> 
> ## Translate the Set-Cookie response header from the auth subrequest into a variable
> auth_request_set $set_cookie $upstream_http_set_cookie;
> ```

Hey. I'm also using swag. And I've had problems getting the same done. But in my nginx logs, even if i log the header, it doesn't show it. I've struggled for a while now, to get this done...For instance, in Ombi, you can set a custom header to login users: 
X-authentik-username.

Yet they're simply not present and authentication fails.
If I make a CURL request, the swag logs do show the proper Headers, but just not if it comes directly from Authentik. I'm at loss what I've done wrong. If you would like to help me, please. :(
