### ISSUE TITLE
request.user is 'Anonymous User'

### ISSUE THREAD

**Issue by gueldenstone** [goauthentik/authentik#4347]
**Describe the bug**
I check the uniquness of an email address with the following policy on the prompt stage for the user settings:

```
other_user = ak_user_by(email=context['prompt_data']['email'])
if (other_user != None and other_user.username != request.user.username):
    ak_message('Email is already registered!')
    return False
return True
```
After the upgrade to 12.1 this policy fails because (I found this through debug logging) request.user.username is 'Anonymous User' subsequently the policy returns False. Strangely the policy worked one time after the upgrade.

**To Reproduce**
1. Add the above policy to the default user settings prompt stage
2. Try to edit the user settings
3. See error

**Expected behavior**
The request variable should hold the current users information as it worked before

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.1
 - Deployment: docker-compose

**Comment by sdimovv** [comment]
I had the same issue.

This commit should fix it: https://github.com/goauthentik/authentik/commit/9d422918b34ee7c49b98a27b0fa51eb72da8691f

**Comment by gueldenstone** [comment]
With authentik 2022.12.2 this works again! Thanks for the fast fix! Awesome work!
