### ISSUE TITLE
Add radio prompt/checkbox groups

### ISSUE THREAD

**Issue by sdimovv** [goauthentik/authentik#4352]
**Is your feature request related to a problem? Please describe.**
Add an ability to select only one out of multiple options. This will allow to create branches in flows. For example in a recovery flow a user can select in a prompt stage if they want to restore a forgotten password or a lost MFA method. Then later flow stages and logic can take into account the selection.

Currently not possible as checkbox controls are not able to be grouped together and no radio controls exists.

**Describe the solution you'd like**
Add a new radio button prompt or add ability to group checkbox prompts together

**Describe alternatives you've considered**
There isn't one I think

**Additional context**
N/A

**Comment by sevmonster** [comment]
Related: #2521
