### ISSUE TITLE
Can't use certificate without a key for verifying the TLS certificate of an LDAP source

### ISSUE THREAD

**Issue by a-gerhard** [goauthentik/authentik#4376]
**Describe the bug**
CA Certificates that don't have private keys seem to be not showing up in the list of certificates for the configuration of TLS verification for LDAP sources

**To Reproduce**
1. Import the CA certificate of an LDAP server
2. Configure an LDAP source for that LDAP server
3. During configuration, try to select the CA certificate imported earlier as "TLS Verification Certificate"
4. In the list of certificates, only those with a private key are visible. I obviously don't have the private key of the CA, and I wouldn't want to import it here even if I had it, for security reasons.

**Expected behavior**
Certificates without private key can be selected if the purpose is only to validate remote servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/986924/210997942-f365f51c-693e-4c43-9dfc-27a2a7ddd577.png)
![image](https://user-images.githubusercontent.com/986924/210997752-ad195308-5af7-43dc-b1fa-4bb4d8fc6cf7.png)

**Logs**
I can see that the request sent from the browser for the certificate list includes the URL parameter `has_key=true`.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.2
 - Deployment: docker-compose

**Additional context**
(nothing)

**Comment by joachimtingvold** [comment]
@BeryJu, was the change committed in 643b36b verified to fix the issue? If so, it seems to be broken again. I see the same behaviour in 2023.8.1;

![image](https://github.com/goauthentik/authentik/assets/359918/e47ed936-49b8-4c4c-841e-3a67a5d99e9b)
![image](https://github.com/goauthentik/authentik/assets/359918/fd6c429c-ce33-4260-9ca2-37397cf06eeb)
