### ISSUE TITLE
Basic Arr Auth Not Working

### ISSUE THREAD

**Issue by adamzvolanek** [goauthentik/authentik#4381]
**Describe the bug**
I followed the respective [sonarr](https://goauthentik.io/integrations/services/sonarr/) documentation/instructions and at a loss why it continues to prompt for username and password in a freshly cleared of history/cookies, etc. Chrome incognito browser.

Included in the screenshot section is my setup.

**To Reproduce**
1. Sign into my Authentik instance as my user who is in the arr users group with the correct attributes.
2. Select Sonarr
3. Have browser dialog box appear prompting for username and password.

**Expected behavior**
I expect the HTTP-Basic Username/Password Key's to be used for authentication.

**Screenshots**
Here is my Proxy Provider
![image](https://user-images.githubusercontent.com/80661527/211127988-f46a449e-bf40-4237-bd33-91832f8b3f9c.png)

Group attributes and member account tied
![image](https://user-images.githubusercontent.com/80661527/211127923-07b9651e-cde0-4573-9fda-625291af785e.png)

Sonarr setup
![image](https://user-images.githubusercontent.com/80661527/211127949-280405d2-bb8e-4d43-88c1-874c12e58545.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12
 - Deployment: docker via Unraid template

**Comment by pbvdven** [comment]
did you add the group to the application? i set it up for prowlarr today and it works fine.

**Comment by adamzvolanek** [comment]
> did you add the group to the application? i set it up for prowlarr today and it works fine.

The group of an application does not tie to the groups made in the directory. Application groups are just for organization _of_ applications.

**Comment by pbvdven** [comment]
No not that group on the application tan choose sonarr then there is a tab groups

**Comment by BeryJu** [comment]
You don't have to bind the group with these attributes to the application, however I'm not sure if it works correctly when the user logging in isn't a direct member of the group with the attributes (as the screenshot you posted it looks like you have an Admin group as part of that group)

The other thing to make sure is that you log out of the application you're making this change to, as these attributes are only transferred on login

**Comment by adamzvolanek** [comment]
> however I'm not sure if it works correctly when the user logging in isn't a direct member of the group with the attributes (as the screenshot you posted it looks like you have an Admin group as part of that group)

I do not have an admin group assigned, it reads 'Adam'. Likewise the Arr User's group is on it's own with no parent group.
![image](https://user-images.githubusercontent.com/80661527/211178088-96fc60e1-9260-4218-a9aa-71bf927251b5.png)


I've been testing this by restarting the sonarr docker container, entering incognito on my browser. Signing into my authentik.domain.tld, and using the dashboard to 'jump' to sonarr.


> No not that group on the application tab choose sonarr then there is a tab groups

I'll be honest, I can't find that page on my Authentik setup. I've checked Applications --> Applications which is the same screenshot as above. Applications --> Providers which allows me to update the proxy provider, and lastly Applications --> Outposts... which I don't think is related, though I verified that Sonarr is selected.

**Comment by adamzvolanek** [comment]
I've also tried flipping between Proxy and Forward Auth in terms of providers. Sonarr does sit behind an nginx proxy, however continues to be basic auth. Currently setting the Sonarr Proxy Provider to Proxy is the only way to reach sonarr without receiving a 500 internal server error. 


Can this still be achieved with only Proxy? The reason I ask is because I have to Nginx Proxy Managers, one for external access and one for internal. The internal nginx proxy manager being on a _different_ ip address than what Authentik runs on. Perhaps this is affecting my outposts? Though I did update the Setup of Nginx Proxy Manager to include the correct IP address:

```
# all requests to /outpost.goauthentik.io must be accessible without authentication
location /outpost.goauthentik.io {
    proxy_pass              http://auth.domain.tld/outpost.goauthentik.io;
CHANGED TO: https://NPM_IP:Port/outpoost...
    # ensure the host of this vserver matches your external URL you've configured
    # in authentik
    proxy_set_header        Host $host;
    proxy_set_header        X-Original-URL $scheme://$http_host$request_uri;
    add_header              Set-Cookie $auth_cookie;
    auth_request_set        $auth_cookie $upstream_http_set_cookie;
    proxy_pass_request_body off;
    proxy_set_header        Content-Length "";
}

# Special location for when the /auth endpoint returns a 401,
# redirect to the /start URL which initiates SSO
location @goauthentik_proxy_signin {
    internal;
    add_header Set-Cookie $auth_cookie;
    return 302 /outpost.goauthentik.io/start?rd=$request_uri;
    # For domain level, use the below error_page to redirect to your authentik server with the full redirect path
    # return 302 https://auth.domain.tld/outpost.goauthentik.io/start?rd=$scheme://$http_host$request_uri;
CHANGED TO https://NPM_IP?outpost....
}
```

This change is required to allow other applications I have running to work behind Nginx.

**Comment by davbay1** [comment]
I'm having the same issue. Can't seem to figure out why basic auth isn't being passed through. Any help would be appreciated.

**Comment by adamzvolanek** [comment]
> I'm having the same issue. Can't seem to figure out why basic auth isn't being passed through. Any help would be appreciated. 

If you're using traefik this may help: https://github.com/goauthentik/authentik/issues/4379#issuecomment-1374420008

**Comment by davbay1** [comment]
> > I'm having the same issue. Can't seem to figure out why basic auth isn't being passed through. Any help would be appreciated.
> 
> If you're using traefik this may help: [#4379 (comment)](https://github.com/goauthentik/authentik/issues/4379#issuecomment-1374420008)

Nope NPM.

**Comment by samip5** [comment]
@adamzvolanek Which Sonarr version are you on? You do know the latest is v4 that's in beta that has better support for things like this right?

**Comment by adamzvolanek** [comment]
> @adamzvolanek Which Sonarr version are you on? You do know the latest is v4 that's in beta that has better support for things like this right?

I did not know that, but I'll ask: why do you think it's an issue on the Sonarr end? Do you have V4 and it working for you?


I checked, my sonarr is using linuxservers flavor of it but not the develop branch (V4). I generally don't update that often for the old "if it ain't broke, don't fix it" mantra.

**Comment by samip5** [comment]
> > @adamzvolanek Which Sonarr version are you on? You do know the latest is v4 that's in beta that has better support for things like this right?
> 
> I did not know that, but I'll ask: why do you think it's an issue on the Sonarr end? Do you have V4 and it working for you?
> 
> 
> I checked, my sonarr is using linuxservers flavor of it but not the develop branch (V4). I generally don't update that often for the old "if it ain't broke, don't fix it" mantra.

I'm just saying to Sonarr that my auth is external and it disables its own thing and relies on my forward auth. If auth backend doesn't respond, my Traefik will just error with 500.

**Comment by adamzvolanek** [comment]
I tried the same credentials with radarr given it is updated to V4, and it resembles the same behavior as sonarr.

**Comment by ZuluWhiskey** [comment]
You look to have everything set up correctly from what I can see - Are you 100% sure you have the username and password correct for Sonarr? I just tested on my side and replicated your issue for my setup that was working flawlessly:
I added an extra character to my password configured for my Sonarr group in Authentik (to make the pw incorrect), cleared my cookies on my Sonarr domain, refreshed the page and then was met with Sonarr's basic login popup.

To fix it, I changed the password back, cleared cookies, refreshed the page and got straight in as previously.

It sounds like Authentik is configured right for you as you're getting to Sonarr once authenticating via Authentik.

**Comment by adamzvolanek** [comment]
> Are you 100% sure you have the username and password correct for Sonarr? I just tested on my side and replicated your issue for my setup that was working flawlessly: I added an extra character to my password configured for my Sonarr group in Authentik (to make the pw incorrect), cleared my cookies on my Sonarr domain, refreshed the page and then was met with Sonarr's basic login popup.

I went ahead and also... I would be happy to test this case, however for both sonarr (version 3) and radarr (version 4) they both stop at the same point, where the basic-auth. browser pop-up appears and nothing is 'entered'. 

> I changed the password to something different, cleared cookies, refreshed the page and got the same prompt.

Looking through the radarr logs I see...

```
2023-01-20 21:13:45.9|Info|Radarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.
2023-01-20 21:13:45.9|Info|Radarr.Http.Authentication.BasicAuthenticationHandler|AuthenticationScheme: Basic was challenged.
```

Is this some browser setting? Chrome, Edge, and Firefox all give the same result in incognito.

**Comment by ZuluWhiskey** [comment]
Okay, interesting... In your original bug report you mention your method for accessing Sonarr is to go via Authentik > Click the link to the Sonarr application > You get the popup

What happens when you attempt to get to Sonarr via its URL without using the link in the Authentik GUI? (In incognito mode). Do you get the Authentik login prompt?

**Comment by adamzvolanek** [comment]
> What happens when you attempt to get to Sonarr via its URL without using the link in the Authentik GUI? (In incognito mode). Do you get the Authentik login prompt?

No, it goes directly to the container and prompts for login with the html pop-up.


Authentik is on the same docker network, I have other containers that are redirecting properly though do not have basic-auth.

**Comment by ZuluWhiskey** [comment]
I have no clue then to be honest - The only other thing I would suggest is to create an app specific user group (rather than your generic Arr one) to see if that's causing any issues. That's the only thing I can think of that's different to my setup that is working

**Comment by adamzvolanek** [comment]
> I have no clue then to be honest - The only other thing I would suggest is to create an app specific user group (rather than your generic Arr one) to see if that's causing any issues. That's the only thing I can think of that's different to my setup that is working.

It's a long shot, but would you be willing to do a Discord call to perhaps walk through my setup and let me know where I may differ?

**Comment by davbay1** [comment]
> > I have no clue then to be honest - The only other thing I would suggest is to create an app specific user group (rather than your generic Arr one) to see if that's causing any issues. That's the only thing I can think of that's different to my setup that is working.
> 
> It's a long shot, but would you be willing to do a Discord call to perhaps walk through my setup and let me know where I may differ?

I found a workaround to get it working. The issue has something to do with the Advanced Config that needs to be entered into NPM. We can bypass that by choosing to setup the apps in "Proxy" mode instead of "Forward Auth". However, I am not sure what difference those modes really make down the line.

In proxy mode, input the local IP in the internal host field and uncheck Internal host SSL verification.

After that in NPM remove the Advanced Custom Config for the app and set the app forward port to your authentik port.

Once I did all of that, it immediately passed the authentication through.

**Comment by zackchadwick** [comment]
I had the same issue described here but I make use of the nginx ingress controller in Kubernetes. 

I imagine a similar fix would work for you, although I haven't used NPM before. I just needed to add `authorization` to the list of auth response headers that was generated by the Provider config in Authentik.

```
nginx.ingress.kubernetes.io/auth-response-headers:
  Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,authorization 
```

**Comment by zackchadwick** [comment]
I actually spoke too soon; that seemed to work for Radarr and Sonarr, both of which were seeing intermittent basic auth prompts, but Prowlarr continues to prompt even with that change.

Looking at the Prowlarr logs it appears that it's getting *something* as a header, but it's stating wrong username/password, even when I type it in manually at the prompt and know it's correct. If I remove the auth forwarding from my ingress it does accept it without issue. Presumably, there's something missing from the annotations for Prowlarr in particular regarding auth.

As a workaround, you can set Prowlarr to External auth mode in the config file and it won't require any prompt since it's securely behind Authentik. Personally, I'd prefer to have the basic auth working as a backup though.

Ref: https://wiki.servarr.com/prowlarr/faq#can-i-disable-forced-authentication

**Comment by davbay1** [comment]
I was inspired by @zackchadwick to try figuring out the "Forward Auth" method using auth-response-headers and I found it.

@adamzvolanek Give it a go.

    # translate headers from the outposts back to the actual upstream
    auth_request_set $authentik_username $upstream_http_x_authentik_username;
    auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
    auth_request_set $authentik_email $upstream_http_x_authentik_email;
    auth_request_set $authentik_name $upstream_http_x_authentik_name;
    auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
    auth_request_set $authentik_auth $upstream_http_authorization;

    proxy_set_header X-authentik-username $authentik_username;
    proxy_set_header X-authentik-groups $authentik_groups;
    proxy_set_header X-authentik-email $authentik_email;
    proxy_set_header X-authentik-name $authentik_name;
    proxy_set_header X-authentik-uid $authentik_uid;
    proxy_set_header X-authentik-uid $authentik_uid;
    proxy_set_header Authorization $authentik_auth;
    }

Add ` auth_request_set $authentik_auth $upstream_http_authorization;` to the end of the first part.
Then add `proxy_set_header Authorization $authentik_auth;` to the second part.

**Comment by zackchadwick** [comment]
Thanks, @davbay1, I'll have to see how those translate into Kubernetes ingress annotations and I'll be set as well, hopefully.

**Comment by davbay1** [comment]
> Thanks, @davbay1, I'll have to see how those translate into Kubernetes ingress annotations and I'll be set as well, hopefully.

I had to make one additional change for it to work in NPM. Not sure how it will apply in Kubernetes. 

@adamzvolanek  As a heads up, in NPM I also had to turn off "Cache Assets" in the edit proxy host popup in the details cache.

**Comment by zackchadwick** [comment]
I figured out how to add those extra headers and it did not solve the issue, however, it started giving me a base64 error with Prowlarr.

That led me to play around with some things and come to the conclusion that this was an issue with my Ingress configuration from the start.

The Ingress I was using has existed for quite some time and wasn't using the `
spec:
  ingressClassName: nginx
` format but the old annotation style. Simply removing those extra headers and defining that ingressClassName seems to have resolved the issue for me. I'm no longer receiving the pop-up when using the Authentik provided ingress configuration, and I can see successful basic auth in the Prowlarr logs.

Lesson learned!

**Comment by romprod** [comment]
> I was inspired by @zackchadwick to try figuring out the "Forward Auth" method using auth-response-headers and I found it.
> 
> @adamzvolanek Give it a go.
> 
> ```
> # translate headers from the outposts back to the actual upstream
> auth_request_set $authentik_username $upstream_http_x_authentik_username;
> auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
> auth_request_set $authentik_email $upstream_http_x_authentik_email;
> auth_request_set $authentik_name $upstream_http_x_authentik_name;
> auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
> auth_request_set $authentik_auth $upstream_http_authorization;
> 
> proxy_set_header X-authentik-username $authentik_username;
> proxy_set_header X-authentik-groups $authentik_groups;
> proxy_set_header X-authentik-email $authentik_email;
> proxy_set_header X-authentik-name $authentik_name;
> proxy_set_header X-authentik-uid $authentik_uid;
> proxy_set_header X-authentik-uid $authentik_uid;
> proxy_set_header Authorization $authentik_auth;
> }
> ```
> 
> Add ` auth_request_set $authentik_auth $upstream_http_authorization;` to the end of the first part. Then add `proxy_set_header Authorization $authentik_auth;` to the second part.

I just wanted to add that this fixed it for me for radarr at least, I'll try the rest of the *arr applications shortly. I guess the NPM vonfig bit needs updating in Authentik to include those two lines.

**Comment by adamzvolanek** [comment]
> > I was inspired by @zackchadwick to try figuring out the "Forward Auth" method using auth-response-headers and I found it.
> > 
> > @adamzvolanek Give it a go.
> > 
> > ```
> > # translate headers from the outposts back to the actual upstream
> > auth_request_set $authentik_username $upstream_http_x_authentik_username;
> > auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
> > auth_request_set $authentik_email $upstream_http_x_authentik_email;
> > auth_request_set $authentik_name $upstream_http_x_authentik_name;
> > auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
> > auth_request_set $authentik_auth $upstream_http_authorization;
> > 
> > proxy_set_header X-authentik-username $authentik_username;
> > proxy_set_header X-authentik-groups $authentik_groups;
> > proxy_set_header X-authentik-email $authentik_email;
> > proxy_set_header X-authentik-name $authentik_name;
> > proxy_set_header X-authentik-uid $authentik_uid;
> > proxy_set_header X-authentik-uid $authentik_uid;
> > proxy_set_header Authorization $authentik_auth;
> > }
> > ```
> > 
> > Add ` auth_request_set $authentik_auth $upstream_http_authorization;` to the end of the first part. Then add `proxy_set_header Authorization $authentik_auth;` to the second part.
> 
> I just wanted to add that this fixed it for me for radarr at least, I'll try the rest of the *arr applications shortly. I guess the NPM config bit needs updating in Authentik to include those two lines.

I'm a bad person and forgot to follow-up. My arr family of apps are working, I'll post my configuration soon (TM) so others can follow suit.

Soon being today/tomorrow.

**Comment by adamzvolanek** [comment]
To finally close out this thread, here is my configuration for sonarr and radarr, both using basic auth via Authentik.

At an Unraid docker scope, they are running in my docker network.

## Authentik Configuration

- A provider for each and an application for each.
- Both enabled in the Application Outpost
- Providers Configuration:
  - Authorization Flow: implicit
  - Forward auth
    - CNAME from my domain
  - Authentication Settings
    - Both 'Intercept header authentication' and 'Send HTTP-Basic Authentication' are enabled/checked
    - HTTP-Basic Username: `sonarr_user`
    - HTTP-Basic Password Key: `sonarr_password`.
- I created a Group for arr items (Directory --> Group)
  - Attributes of them include: `sonarr_user: username` and `sonarr_password: password`.
  - There are setup as the username and password for sonarr and radarr in this example as they are under the 'Arr User Group'
    - The naming of the attribute just happens to be **son**arr_user...

## Nginx Proxy Manager

- Replace line 48 with your Authentik's docker:port endpoint.
  - `proxy_pass http://outpost.company:9000/outpost.goauthentik.io;` -> `proxy_pass https://<docker_name>:<docker_port>/outpost.goauthentik.io;`
- As mentioned in https://github.com/goauthentik/authentik/issues/4381#issuecomment-1457438495 add the headers. My configuration looks appears as follows:
- 
```
    # translate headers from the outposts back to the actual upstream
    auth_request_set $authentik_username $upstream_http_x_authentik_username;
    auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
    auth_request_set $authentik_email $upstream_http_x_authentik_email;
    auth_request_set $authentik_name $upstream_http_x_authentik_name;
    auth_request_set $authentik_uid $upstream_http_x_authentik_uid;

## Added
    auth_request_set $authentik_authorization $upstream_http_authorization;

    proxy_set_header X-authentik-username $authentik_username;
    proxy_set_header X-authentik-groups $authentik_groups;
    proxy_set_header X-authentik-email $authentik_email;
    proxy_set_header X-authentik-name $authentik_name;
    proxy_set_header X-authentik-uid $authentik_uid;

## Added
     proxy_set_header Authorization $authentik_authorization;

}
```

In NPM, create a Proxy Host pointed to your respective arr family container on its basic HTTP port. **Do not** select 'Cache Assets'. Setup NPM as you would normally otherwise and paste in your modified configuration file. Repeat the steps for other arr family products, no need to modify the template.


I hope this helps everyone in the future, the issue is already closed at the time of writing, but I also type this up for my own sanity.

Supporting images:

<details><summary>Expand for images</summary>

### Application

![image](https://github.com/goauthentik/authentik/assets/80661527/910c9e6e-4ee8-4112-a960-d7855b56b88f)

### Proxy Provider

![image](https://github.com/goauthentik/authentik/assets/80661527/5d74bc46-c414-44b7-8789-057d66f74264)

### Comparison of NPM Template

![image](https://github.com/goauthentik/authentik/assets/80661527/8f4220af-1b73-4616-ba3c-6d067cc768e0)


</details>

**Comment by pippobimbo** [comment]
I experienced the same issue with Sonarr.
Solved it using « external » as authentication method in Sonarr config file.

**Comment by amlucent** [comment]
> I experienced the same issue with Sonarr. Solved it using « external » as authentication method in Sonarr config file.

2024.  This is the way.

[https://wiki.servarr.com/prowlarr/faq#can-i-disable-forced-authentication](https://wiki.servarr.com/prowlarr/faq#can-i-disable-forced-authentication)

**Comment by cpuks** [comment]
> I experienced the same issue with Sonarr. Solved it using « external » as authentication method in Sonarr config file.

But it disables auth so anyone in local network can access sonarr/radarr/prowlarr - it's not a solution TBH.

**Comment by krstn420** [comment]
> > I experienced the same issue with Sonarr. Solved it using « external » as authentication method in Sonarr config file.
> 
> But it disables auth so anyone in local network can access sonarr/radarr/prowlarr - it's not a solution TBH.

you can also choose to not expose the port of *arr dockers

**Comment by funkyapple** [comment]
> I had the same issue described here but I make use of the nginx ingress controller in Kubernetes.
> 
> I imagine a similar fix would work for you, although I haven't used NPM before. I just needed to add `authorization` to the list of auth response headers that was generated by the Provider config in Authentik.
> 
> ```
> nginx.ingress.kubernetes.io/auth-response-headers:
>   Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,authorization 
> ```

This worked for me.

**Comment by mikemilligram** [comment]
> I hope this helps everyone in the future, the issue is already closed at the time of writing, but I also type this up for my own sanity.

Thank you so much, this needs to be added to the documentation, and honestly also to the source code. I don't know how to go about that, but in any case, this finally made my basic auth apps work!

**Comment by EphoxiaGit** [comment]
I have a new problem related to this, I added the headers which seeemed to fix everyone elses issue, but for me it makes the login prompt pop up like before the fix, but this time no matter what i put it will not log in. if i try all i get is

`2024-04-12 20:21:07.8|Info|Sonarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: The username or password is not correct.
2024-04-12 20:21:07.8|Info|Sonarr.Http.Authentication.BasicAuthenticationHandler|AuthenticationScheme: Basic was challenged.`


I followed the config adamzvolanek posted in the comments, in my group i set `arr_pw: 1937
arr_usr: admin` as a test. 
under sonarr provider "Intercept header authentication" and "Send HTTP-Basic Authentication" is enabled and under "HTTP-Basic Username Key" and password i put "arr_usr" and "arr_pw" respectively. But sonarr logs still say username or password is not correct. If i remove the headers i can atleast login using the prompt as normal.

This is my NGINX config:

`
# Increase buffer size for large headers
# This is needed only if you get 'upstream sent too big header while reading response
# header from upstream' error when trying to access an application protected by goauthentik
proxy_buffers 8 16k;
proxy_buffer_size 32k;

# Make sure not to redirect traffic to a port 4443
port_in_redirect off;

location / {
    # Put your proxy_pass to your application here
    proxy_pass          $forward_scheme://$server:$port;
    # Set any other headers your application might need
     proxy_set_header Host $host;
    # proxy_set_header ...

    ##############################
    # authentik-specific config
    ##############################
    auth_request     /outpost.goauthentik.io/auth/nginx;
    error_page       401 = @goauthentik_proxy_signin;
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header       Set-Cookie $auth_cookie;

    # translate headers from the outposts back to the actual upstream
    auth_request_set $authentik_username $upstream_http_x_authentik_username;
    auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
    auth_request_set $authentik_email $upstream_http_x_authentik_email;
    auth_request_set $authentik_name $upstream_http_x_authentik_name;
    auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
    auth_request_set $authentik_auth $upstream_http_authorization;

    proxy_set_header X-authentik-username $authentik_username;
    proxy_set_header X-authentik-groups $authentik_groups;
    proxy_set_header X-authentik-email $authentik_email;
    proxy_set_header X-authentik-name $authentik_name;
    proxy_set_header X-authentik-uid $authentik_uid;
    proxy_set_header Authorization $authentik_auth;

}

# all requests to /outpost.goauthentik.io must be accessible without authentication
location /outpost.goauthentik.io {
    proxy_pass              http://192.168.10.200:9000/outpost.goauthentik.io;
    # ensure the host of this vserver matches your external URL you've configured
    # in authentik
    proxy_set_header        Host $host;
    proxy_set_header        X-Original-URL $scheme://$http_host$request_uri;
    add_header              Set-Cookie $auth_cookie;
    auth_request_set        $auth_cookie $upstream_http_set_cookie;
    proxy_pass_request_body off;
    proxy_set_header        Content-Length "";
}

# Special location for when the /auth endpoint returns a 401,
# redirect to the /start URL which initiates SSO
location @goauthentik_proxy_signin {
    internal;
    add_header Set-Cookie $auth_cookie;
    return 302 /outpost.goauthentik.io/start?rd=$request_uri;
    # For domain level, use the below error_page to redirect to your authentik server with the full redirect path
    # return 302 https://authentik.company/outpost.goauthentik.io/start?rd=$scheme://$http_host$request_uri;
}

`

**Comment by enscott89** [comment]
> I experienced the same issue with Sonarr. Solved it using « external » as authentication method in Sonarr config file.

Thank you so much! Working after doing this and implementing adam's changes too

**Comment by adamzvolanek** [comment]
> I followed the config adamzvolanek posted in the comments, in my group i set `arr_pw: 1937 arr_usr: admin` as a test. under sonarr provider "Intercept header authentication" and "Send HTTP-Basic Authentication" is enabled and under "HTTP-Basic Username Key" and password i put "arr_usr" and "arr_pw" respectively. But sonarr logs still say username or password is not correct. If i remove the headers i can atleast login using the prompt as normal.


I've since stopped having my arr family available by subdomain, however here is my previously working configuration under the "Advanced" tab in Nginx Proxy Manager.


```bash
# Increase buffer size for large headers
# This is needed only if you get 'upstream sent too big header while reading response
# header from upstream' error when trying to access an application protected by goauthentik
proxy_buffers 8 16k;
proxy_buffer_size 32k;

# Make sure not to redirect traffic to a port 4443
port_in_redirect off;

location / {
    # Put your proxy_pass to your application here
    proxy_pass          $forward_scheme://$server:$port;
    # Set any other headers your application might need
    # proxy_set_header Host $host;
    # proxy_set_header ...

    ##############################
    # authentik-specific config
    ##############################
    auth_request     /outpost.goauthentik.io/auth/nginx;
    error_page       401 = @goauthentik_proxy_signin;
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header       Set-Cookie $auth_cookie;

    # translate headers from the outposts back to the actual upstream
    auth_request_set $authentik_username $upstream_http_x_authentik_username;
    auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
    auth_request_set $authentik_email $upstream_http_x_authentik_email;
    auth_request_set $authentik_name $upstream_http_x_authentik_name;
    auth_request_set $authentik_uid $upstream_http_x_authentik_uid;

## Added
    auth_request_set $authentik_authorization $upstream_http_authorization;

    proxy_set_header X-authentik-username $authentik_username;
    proxy_set_header X-authentik-groups $authentik_groups;
    proxy_set_header X-authentik-email $authentik_email;
    proxy_set_header X-authentik-name $authentik_name;
    proxy_set_header X-authentik-uid $authentik_uid;

## Added
     proxy_set_header Authorization $authentik_authorization;

}

# all requests to /outpost.goauthentik.io must be accessible without authentication
location /outpost.goauthentik.io {
    proxy_pass              https://authentik:9443/outpost.goauthentik.io;
    # ensure the host of this vserver matches your external URL you've configured
    # in authentik
    proxy_set_header        Host $host;
    proxy_set_header        X-Original-URL $scheme://$http_host$request_uri;
    add_header              Set-Cookie $auth_cookie;
    auth_request_set        $auth_cookie $upstream_http_set_cookie;
    proxy_pass_request_body off;
    proxy_set_header        Content-Length "";
}

# Special location for when the /auth endpoint returns a 401,
# redirect to the /start URL which initiates SSO
location @goauthentik_proxy_signin {
    internal;
    add_header Set-Cookie $auth_cookie;
    return 302 /outpost.goauthentik.io/start?rd=$request_uri;
    # For domain level, use the below error_page to redirect to your authentik server with the full redirect path
    # return 302 https://authentik.company/outpost.goauthentik.io/start?rd=$scheme://$http_host$request_uri;
}
```

Note my,

```bash
# all requests to /outpost.goauthentik.io must be accessible without authentication
location /outpost.goauthentik.io {
    proxy_pass              https://authentik:9443/outpost.goauthentik.io;
```

reads only 'authentik` since it is in the same docker network on my Unraid server.

**Comment by AblabiX** [comment]
with traefik+authentik i was able to work the Basic Auth only with traefik dashboard access and Bazarr
the rest of the Arr all external as auth setting.

**Comment by excaliburzarau** [comment]
Hello guys,

I am using Caddy as a reverse proxy,
Just added the Authorization header to my caddy and the issue was resolved.
The credentials are passed properly, even in incognito mode.


Best Regards

**Comment by speedyconzales** [comment]
you are all making sure that in sonarr or whatever arr you set the authentication to basic, not forms. Right?
and surely using external... is like None. So you would not need something like authentik anyway if you plan to just skip authentication entirely. so please don't do that either

**Comment by excaliburzarau** [comment]
> you are all making sure that in sonarr or whatever arr, you set the authentication to basic, not forms. Right? and surely using external... is like None. So you would not need something like authentik anyway if you plan to just skip authentication entirely. so please don't do that either

Hello,

I believe that is irrelevant for the concept itself. Yes, the Arr web apps do support a Basic authentication without form but i believe that the idea would Be to ensure the undersranding of the concept to other applications that behave the same way for http Basic authentication and relate the issue. It worked for my use case and it is behaving as expected. Hopefully it Will help someone else.

Cheers

**Comment by martinbjeldbak** [comment]
> Hello guys,
> 
> I am using Caddy as a reverse proxy, Just added the Authorization header to my caddy and the issue was resolved. The credentials are passed properly, even in incognito mode.
> 
> Best Regards

Can confirm, I added the value `Authorization` to Caddy's `copy_headers` directive and it worked after seeing the following in Sonarr's logs on authenticating with Authentik

> [Info] Sonarr.Http.Authentication.BasicAuthenticationHandler: Basic was not authenticated. Failure message: Authorization header missing. 
> [Info] Sonarr.Http.Authentication.BasicAuthenticationHandler: AuthenticationScheme: Basic was challenged

Maybe the [Sonarr docs](https://docs.goauthentik.io/integrations/services/sonarr/) need to be updated?

**Comment by mangobiche** [comment]
am I just dumb? I've been fighting with this for months. I'm using some apps (the legacy ones that don't allow OAuth or other methods) behind authentik as a proxy. I haven't been able to get it to do basic auth. If I tried directly to the service ip, without going trhough authentik, basic auth works. As soon as authentik get in teh way it fails. 

Things I've tried:
* defined user and pass in the user/group attributes
* all kinds of crazy stuff on caddy (which I believe is where my sin lies)
* removed, "Intercept headers" from authentik
* enabled "Intercept headers"
* trying to use "bruno" to check headers, but I haven't being able to make the app password work so I can check what headers are ending up when already authenticated

I'm using caddy by the way. I saw @martinbjeldbak 's comment about `Authorization` and `copy_headers` but after a bit of reading it seems to only apply to ``forward_auth``.

what am I missing here? help!

**Comment by kpatdev** [comment]
> [!NOTE]
Radarr v6 removed basic auth and my default got set back to forms. Sonarr still works for now.

To still avoid the double login you can edit the config.xml and find the line that has the key `<AuthenticationMethod>forms</AuthenticationMethod>` and change forms to External making it **`<AuthenticationMethod>External</AuthenticationMethod>`**.

> [!CAUTION] 
With this, on your local network Radarr **won't be behind any auth**. Such a brain dead change to remove basic auth before implementing OIDC (if that will ever come). Oh well.

If you want to read some more discussions regarding this [change](https://www.reddit.com/r/radarr/comments/1p4i9lq/did_basic_auth_disappear/)
