### ISSUE TITLE
Not Synced Yet

### ISSUE THREAD

**Issue by hugofreed0m** [goauthentik/authentik#4382]
**Describe the bug**
I added a LDAP to the directories, It sync but still in status "Not synced yet"
<img width="269" alt="image" src="https://user-images.githubusercontent.com/108002550/211159165-fdb5c8a5-d0c4-4392-855e-1c9bb566cf55.png">

**To Reproduce**
1. Fresh install
2. add LDAP-Source at federation and social logins
3. Save
4. Start Sync

**Expected behavior**
See the syncs.

**Version and Deployment (please complete the following information):**
 - authentik version: latest
 - Deployment: docker-compose

**Additional context**
There is my configuration : 
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/108002550/211159381-2dd9a792-8214-44f3-b642-22b0a352ce40.png">

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/108002550/211159399-01b3cb58-30d4-4ffe-b11d-81594ebf5cd7.png">

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/108002550/211159411-64eb9ee3-d2fc-4cc4-908b-1503f44aac9c.png">

But  as you can see here, my user is sync imported : 
<img width="336" alt="image" src="https://user-images.githubusercontent.com/108002550/211159484-e046f010-cd63-4cf6-b4b8-3c55f6737775.png">

Thanks for helping me !

**Comment by sauramel** [comment]
I am also experiencing this bug after updating to the latest version

**Comment by lupin3rd** [comment]
Same problem in my installation with 2022.12.x release.

**Comment by rheaalleen** [comment]
Can confirm with the most recent release.

Makes troubleshooting a new connection impossible since you don't get any feedback messages

**Comment by borkie** [comment]
Same bug here, also ldap System Task directly started with play button doesn't work
