### ISSUE TITLE
UI: large numbers in donut diagrams not displayed correctly in overview dashboard

### ISSUE THREAD

**Issue by a-gerhard** [goauthentik/authentik#4390]
**Describe the bug**
Large numbers disappear behind the donut circle diagrams in the Overview Dashboard's top row (see screenshot)

**To Reproduce**
1. Have an instance with more than 10,000 users, groups, flows, outposts, or LDAP sources (it'll likely be users)
2. navigate to `/if/admin/#/administration/overview`
3. Try to read the respective number from the dashboard

**Expected behavior**
The number is readable. This could be achieved by reducing font size, for example.

**Screenshots**
![image](https://user-images.githubusercontent.com/986924/211304997-720b3b5e-6cab-44bf-bb9a-0463a3be20e4.png)

**Logs**
(none)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.2
 - Deployment: docker-compose

**Additional context**
(none)

**Comment by BeryJu** [comment]
I think it might be a better alternative to switch the donut diagrams for something else, especially for users and groups, it might be better to have a normal line graph (and maybe combine users and groups)
