### ISSUE TITLE
JWT Token Payload does not contain all mappings

### ISSUE THREAD

**Issue by Stormfox2** [goauthentik/authentik#4420]
**Describe the bug**
Hey!

I am currently trying to integrate Authentik with the new JetBrains Space on Prem, with the help of OpenID connect. The connection between Authentik is established and I get fully redirected, but space is throwing this error: Cannot register a new account for you: Last name should not be empty.

The payload looks like this: 
{
    "iss": "redacted",
    "sub": "redacted",
    "aud": "redacted",
    "exp": 1673534007,
    "iat": 1673532207,
    "auth_time": redacted,
    "acr": "goauthentik.io/providers/oauth2/default",
    "amr": [
        "pwd"
    ],
    "email": "qbraendli@redacted",
    "email_verified": true,
    "name": "Quirin Braendli",
    "given_name": "Quirin Braendli",
    "family_name": "",
    "preferred_username": "qbraendli",
    "nickname": "qbraendli",
    "groups": [
        "authentik Admins",
        "admins"
    ]
}

The users properties look like this:
sn: Braendli
givenName: Quirin
ldap_uniq: redacted
family_name: Braendli
distinguishedName: redacted

**To Reproduce**
Setup space as a OpenID provider.
Try to login.

**Expected behavior**
Logging in and passing the family_name attribute.

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2021.8.5]
 - Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by BeryJu** [comment]
This is the intended behaviour, to map custom attributes from a user to an OAuth claim create a scope mapping with the expression 
```python
return {
    "family_name": request.user.attributes.get("family_name"),
}
``` and select that scope in your provider (and also ask for that scope mapping's name in the authorization request)

**Comment by jtitley** [comment]
> This is the intended behaviour, to map custom attributes from a user to an OAuth claim create a scope mapping with the expression
> 
> ```python
> return {
>     "family_name": request.user.attributes.get("family_name"),
> }
> ```
> 
> and select that scope in your provider (and also ask for that scope mapping's name in the authorization request)

I'm going to chime in here because I needed to alter preferred_name and this lead me in the right direction. I don't know if it's correct but I did this:

return {
    "custom_username": "preconfigured_adminaccount" if request.user.username == "akadmin" else request.user.username,
}

If referencing request object is correct, it needs to be made more clear on the property_mappings/expression page as it's a powerful way to alter properties similar to that other cloud provider that starts with O.
