### ISSUE TITLE
Dedicated GeoIP/ASN policy

### ISSUE THREAD

**Issue by sdimovv** [goauthentik/authentik#4433]
**Is your feature request related to a problem? Please describe.**
Since the GeoIP DB is now bundled with authentik and is available out of the box, it is logical to assume that even more users will want to take advantage of what GeoIP can offer. 

However, currently the only way to use the GeoIP features is through an expression policy. The problem with that is:
1. Not flexible. To change rules you need to either edit the code in the policy directly or have some kind of a system where it can take settings from environment variables or tenant attributes.
2. Requires programming knowledge

**Describe the solution you'd like**
A dedicated GeoIP policy which can be used to set rules for passing/failing. 

**Describe alternatives you've considered**
Write/update code in an expression policy

**Additional context**
N/A

**Comment by nhhandevops** [comment]
U guys provide documents really suck
