### ISSUE TITLE
Machine-to-Machine via service accounts?

### ISSUE THREAD

**Issue by davidgiga1993** [goauthentik/authentik#4435]
**Describe your question**
I'm evaluating authentik for protection various services, some of them have oauth2 support, others don't.
Therefore I'm using oauth2 and proxy provider (nginx) which is working fine on its own. However I also have the use case for M2M communication, thus I need to be able to authorize from code (for example from a python script).

I already found https://goauthentik.io/developer-docs/api/flow-executor and https://github.com/goauthentik/authentik/issues/3229
but from what I can tell, none of these provide a viable solution.

My naive idea would be to:
1) Create service account
2) Post that data to authentik to authenticate and get a token back (ideally this token can be used for oauth as well)
3) Send the token in the header in the request to the application protected via nginx proxy provider

Is something like this possible?

**Comment by BeryJu** [comment]
This will be possible with #4421 which will be in 2023.1

**Comment by gagan-multani** [comment]
@davidgiga1993 I am trying to do the same, were you able to accomplish that ?

**Comment by davidgiga1993** [comment]
> @davidgiga1993 I am trying to do the same, were you able to accomplish that ?

1. Create a user of type `Service Account`
2. Go to `Token and App passwords` and create a token for that user
3. The token can be used with basic auth.

In my setup I'm protecting a service using a nginx as outpost with authentic.

```python
import requests
requests.get('https://your-protected-service/test', user=('service-user-name', 'token')) 
```

**Comment by luiplapin1** [comment]
I'm trying your lines and I obtain this error :(

\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'user'

**Comment by luiplapin1** [comment]
Have you done any specific configuration in the proxy provider of that app? I have an app configured by proxy provided (which I can authenticate via other users in the graphical interface), but when I try your code with a service account I cannot acess:
![image](https://github.com/goauthentik/authentik/assets/72936554/29e075b6-9495-4ba3-a2af-e4a39e9115c4)

**Comment by BeryJu** [comment]
![image](https://github.com/goauthentik/authentik/assets/1932513/38284074-b0d0-40cd-96f1-9fb958cb117c)
this option must be enabled in the proxy provider
