### ISSUE TITLE
Certificate Error on Documentation Link

### ISSUE THREAD

**Issue by aevans1987** [goauthentik/authentik#4437]
**Describe the bug**
Certificate Error when hitting documentation link in Create Outpost.

**To Reproduce**
1. Go to Create Outpost
2. Click on Documentation
3. See error

**Expected behavior**
Documentation site opens properly

**Screenshots**
![image](https://user-images.githubusercontent.com/23514631/212552567-56de8052-b077-4009-affd-78aecc086dde.png)

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.2
 - Deployment: Helm

**Additional context**

**Comment by BeryJu** [comment]
Normally this should automatically be taken care of by netlify, I've just regenerated the certificate on there manually and the domains work now
