### ISSUE TITLE
ldap property mapping test is broken

### ISSUE THREAD

**Issue by tograss** [goauthentik/authentik#4459]
**Describe the bug**
When using the test feature for ldap mapping (custom and default ones ) the result is always
`name 'ldap' is not defined`

**To Reproduce**
1. go to domain/if/admin/#/core/property-mappings
2. unselect hide managed properties
3. click on test tube in row authentik default LDAP Mapping: mail
4. select user 
5. click test
6. See error

**Expected behavior**
The user email / a clear error message or indication that something went wrong

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.2
 - Deployment: docker
  
**Additional context**
The LDAP Sync it self works.
Looks like an import is missing where the code is tested  ?

**Comment by FilipK-CZ** [comment]
I have same issue 

Version and Deployment:
authentik version: 2022.12.2
Deployment: docker

**Comment by AndrewBucklin** [comment]
I am having the same issue on 2023.5.2

`{"action": "property_mapping_exception", "auth_via": "session", "client_ip": "x.x.x.x", "context": {"expression": "return list_flatten(ldap.get('userPrincipalName'))", "geo": {"city": "X", "continent": "NA", "country": "US", "lat": X, "long": X}, "http_request": {"args": {"format_result": "true"}, "method": "POST", "path": "/api/v3/propertymappings/all/4df0d709-0256-4a2b-a618-fd951996b727/test/"}, "message": "Traceback (most recent call last):\n  File \"authentik default Active Directory Mapping: userPrincipalName\", line 3, in <module>\n  File \"authentik default Active Directory Mapping: userPrincipalName\", line 2, in handler\nbuiltins.NameError: name 'ldap' is not defined"}, "event": "Created Event", "host": "X", "level": "info", "logger": "authentik.events.models", "pid": 33, "request_id": "504c4ac3eeec405e8b71eb4bd4b94b34", "timestamp": "2023-05-28T19:05:39.193526", "user": {"email": "X", "pk": 431, "username": "X"}}`
