### ISSUE TITLE
Setting Authorization header when using client-go 

### ISSUE THREAD

**Issue by AndriyKalashnykov** [goauthentik/authentik#4464]
**Additional context**
My use case is following, I have a CLI utility written in Go which need to authenticate human users against Authintik, similar to what docker does: `docker login -u HumanUser -p HumanUserPassword`. Is it possible to achieve it with Authentik?

**Describe your question/**
I want to use `goauthentik/client-go` to invoke Authentik API, i was not able to find working Go sample utilizing `goauthentik/client-go` and  struggling to find information regarding how to get OAuth token for default `akadmin` user (or any other user) so I can call Authentik API. 

**Relevant infos**
```go
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"

	httptransport "github.com/go-openapi/runtime/client"
	api "goauthentik.io/api/v3"
)

func GetTLSTransport(insecure bool) http.RoundTripper {
	tlsTransport, err := httptransport.TLSTransport(httptransport.TLSClientOptions{
		InsecureSkipVerify: insecure,
	})
	if err != nil {
		panic(err)
	}
	return tlsTransport
}

func main() {

	config := api.NewConfiguration()
	config.Debug = true
	config.Scheme = "https"
	config.Host = "172.18.255.202:9443"
	config.HTTPClient = &http.Client{
		Transport: GetTLSTransport(true),
	}

        config.AddDefaultHeader("Authorization", fmt.Sprintf("Bearer %s", "???")) // <- how to obtain it
        apiClient := api.NewAPIClient(config)

	resp, r, err := apiClient.AdminApi.AdminAppsList(context.Background()).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `AdminApi.AdminAppsList``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	// response from `AdminAppsList`: []App
	fmt.Fprintf(os.Stdout, "Response from `AdminApi.AdminAppsList`: %v\n", resp)
}
```

**Comment by BeryJu** [comment]
There's currently no way to directly authenticate to the API with username/password, and this is on purpose. The recommended way is to either use a API Token created in the user settings, or alternatively using the OAuth device flow (see https://github.com/BeryJu/oidc-test-client/blob/master/cmd/device.go#L25) and requesting the `goauthentik.io/api` scope, which allows the token to send API requests as the user

**Comment by AndriyKalashnykov** [comment]
> There's currently no way to directly authenticate to the API with username/password, and this is on purpose. The recommended way is to either use a API Token created in the user settings, or alternatively using the OAuth device flow (see https://github.com/BeryJu/oidc-test-client/blob/master/cmd/device.go#L25) and requesting the `goauthentik.io/api` scope, which allows the token to send API requests as the user

Thanks for the prompt reply! First approach may potentially work in our usecase. But even with the info you provide, i'm not sure how use with go client. An example would hep tremendously.
Another question, after installation of Authentik, how can i create a user and mentioned API token programmatically?

**Comment by BeryJu** [comment]
The user-generated API token is directly sent as Bearer token, so you can just pass it in with your snippet above
There's some more example usage for the API client in the terraform provider: https://github.com/goauthentik/terraform-provider-authentik/blob/main/internal/provider/provider.go#L155

For the OAuth device flow, you can basically copy the code linked above and use the resulting refresh_token from that as Bearer token

You can use this https://goauthentik.io/docs/installation/automated-install to create a token on install, then with that token you can create more users afterwards

**Comment by AndriyKalashnykov** [comment]
Thanks, i'll give it a try. One more thing, to call and admin API using Go client what else is mandatory to specify other then token?

**Comment by BeryJu** [comment]
nothing, with the token the example you posted above should just work

**Comment by AndriyKalashnykov** [comment]
Thanks again, will keep you posted. If you'd like I could create a PR with complete Go client sample when done.
