### ISSUE TITLE
On first UI load of the page "User Interface -> Dashboards -> Overview" it displays Welcome, {name}. instead of "Welcome, authentik Default Admin."

### ISSUE THREAD

**Issue by AndriyKalashnykov** [goauthentik/authentik#4472]
**Describe the bug**
On first UI load of the page "User Interface -> Dashboards -> Overview" it displays Welcome, {name}. instead of "Welcome, authentik Default Admin."

**Expected behavior**
Displays "Welcome, authentik Default Admin."

**Screenshots**
![image](https://user-images.githubusercontent.com/2081253/213337040-4b327569-b108-4e5b-82e2-e37e3d6b4642.png)

**Comment by senbax** [comment]
Same here. Not dependent on any specific authentik Version, all Versions from 2022 and 2023 are affected

**Comment by arcoast** [comment]
Not sure as I'm no dev, but is it to do with the localisation stuff lacking a `$`?

https://github.com/goauthentik/authentik/search?q=%22Welcome%2C+%7Bname%7D%22&type=code

**Comment by BeryJu** [comment]
This shouldn't happen anymore since we [migrated to lit-localize](https://github.com/goauthentik/authentik/pull/5761)
