### ISSUE TITLE
Enrollment flows return unable to create user errors after upgrade

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#4490]
**Describe the bug**
All of my user write stages give out an no user found and can't create new user errors after upgrade.

**To Reproduce**
1. Have perfectly working enrollment flows prior to upgrade
2. Upgrade
3. Have them all error out on user write stage

**Version:**
 - authentik version: 2023.1.1

**Comment by BeryJu** [comment]
Fixed in 2023.1.2
