### ISSUE TITLE
Unable to use FQDN for Proxy Authentication

### ISSUE THREAD

**Issue by drtech981** [goauthentik/authentik#4496]
I have setup authentik as described in the docs, and authentik is available at authentik.drtech981.cc.

Endpoint I'm trying to protect is nginx.drtech981.cc.

Under NGINX Proxy Manager > Advanced, here's the config: 
```
proxy_buffers 8 16k;
proxy_buffer_size 32k;
port_in_redirect off;

location / {
    proxy_pass          $forward_scheme://$server:$port;

    auth_request     /outpost.goauthentik.io/auth/nginx;
    error_page       401 = @goauthentik_proxy_signin;
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header       Set-Cookie $auth_cookie;

    auth_request_set $authentik_username $upstream_http_x_authentik_username;
    auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
    auth_request_set $authentik_email $upstream_http_x_authentik_email;
    auth_request_set $authentik_name $upstream_http_x_authentik_name;
    auth_request_set $authentik_uid $upstream_http_x_authentik_uid;

    proxy_set_header X-authentik-username $authentik_username;
    proxy_set_header X-authentik-groups $authentik_groups;
    proxy_set_header X-authentik-email $authentik_email;
    proxy_set_header X-authentik-name $authentik_name;
    proxy_set_header X-authentik-uid $authentik_uid;
}

location /outpost.goauthentik.io {
    proxy_pass              http://10.0.0.252:8201/outpost.goauthentik.io;
    proxy_set_header        Host $host;
    proxy_set_header        X-Original-URL $scheme://$http_host$request_uri;
    add_header              Set-Cookie $auth_cookie;
    auth_request_set        $auth_cookie $upstream_http_set_cookie;
    proxy_pass_request_body off;
    proxy_set_header        Content-Length "";
}

location @goauthentik_proxy_signin {
    internal;
    add_header Set-Cookie $auth_cookie;
    return 302 /outpost.goauthentik.io/start?rd=$request_uri;
}
```
If I try to use   proxy_pass  http://authentik.drtech981.cc/outpost.goauthentik.io;
I keep on getting error 500.

What am I doing wrong ?

**Comment by BeryJu** [comment]
When using the external FQDN in the nginx forward auth, nginx will overwrite certain headers that are required by authentik, hence the forward auth traffic should directly go to the outpost via internal DNS entry or otherwise

**Comment by drtech981** [comment]
Can you elaborate a little more ?

**Comment by drtech981** [comment]
@BeryJu Can you elaborate a little more ?

**Comment by agent-squirrel** [comment]
@drtech981 What @BeryJu is getting at is that if you use an external address NGINX destroys some headers so authentik can't process the request.

The suggestion is to use an internal DNS entry or IP address in the proxy_pass directive. An example in my case as both nginx proxy manager and authentik are on the same docker bridge is to use the docker container name of authentik. 

`# all requests to /outpost.goauthentik.io must be accessible without authentication
location /outpost.goauthentik.io {
    proxy_pass              http://authentik_server_1:9000/outpost.goauthentik.io;
    # ensure the host of this vserver matches your external URL you've configured
    # in authentik
    proxy_set_header        Host $host;
    proxy_set_header        X-Original-URL $scheme://$http_host$request_uri;
    add_header              Set-Cookie $auth_cookie;
    auth_request_set        $auth_cookie $upstream_http_set_cookie;
    proxy_pass_request_body off;
    proxy_set_header        Content-Length "";
}
`

This doesn't stop you having authentik itself on an external address or any other app, just that the communication between authentik and nginx will take place within the docker network. You could use the IP or internal DNS name of another server too if they aren't both on the same machine.

Hope that helps?

**Comment by drtech981** [comment]
@agent-squirrel Thanks for the help, but that doesn't solve my problem.
Authentik and other apps I'm trying to protect are hosted on two different networks.

Authentik --> Digital Ocean Droplet
App 1-10 --> Home based Server (say ISP 1)
App 11-20 --> Another Home Based Server (say ISP 2)

I have a bunch of estate, each having at the least a CCTV, VoIP and Storage Servers, besides basic apps like Grafana Dashboards and WOL Webpages. It's tedious to have to sign in to each of them separately. Hence the endeavor -- most of these services have the option to disable inbuilt authentication, and thus I was thinking of protecting them with Authentik.

Authelia works for now, but it lacks a GUI and is a pain to work with specially when dealing with users that are not so well versed with tech.

**Comment by agent-squirrel** [comment]
Are you sending Authentik requests over the internet or some sort of tunnel?
