### ISSUE TITLE
Upgrading from 2022.11.3 to 2023.1.2 changed Fields in default-source-enrollment-prompt

### ISSUE THREAD

**Issue by tobias-urdin** [goauthentik/authentik#4507]
**Describe the bug**

We upgraded from 2022.11.3 to 2023.1.2 and the selected Field in the default-source-enrollment-prompt
prompt stage that we had modified was changed breaking our enrollment flow.

**To Reproduce**

**Expected behavior**
Upgrade should not have modified our selected fields in default-source-enrollment-prompt

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: docker

**Additional context**
Upgrading from 2022.11.3 -> 2023.1.2

**Comment by tobias-urdin** [comment]
Is it recommend to always create your own stage and never modify Fields on a default stage?

**Comment by BeryJu** [comment]
This will also be fixed by #4497 and doesn't really have anything to do with the upgrade, but rather with blueprints overwriting each others prompt fields, there's a better description in that PR

**Comment by tobias-urdin** [comment]
I see, closing in favor or #4497 – thanks for a great project!
