### ISSUE TITLE
INF event=PostgreSQL connection failed, retrying... (connection to server at "postgresql" (192.168.80.4), port 5432 failed: FATAL:  password authentication failed for user "authentik" ) logger=authentik.lib.config timestamp=1674569107.8800704

### ISSUE THREAD

**Issue by LuXc-NL** [goauthentik/authentik#4512]
**Describe the bug**
`INF event=PostgreSQL connection failed, retrying... (connection to server at "postgresql" (192.168.80.4), port 5432 failed: FATAL:  password authentication failed for user "authentik"
) logger=authentik.lib.config timestamp=1674569107.8800704`
Edit: While setting up Authentik for the first time.

**To Reproduce**
1. Download docker-compose file from [https://goauthentik.io/docs/installation/docker-compose#preparation](https://goauthentik.io/docs/installation/docker-compose#preparation)
2. Create .env and set PG_PASS, AUTHENTIK_SECRET_KEY, AUTHENTIK_PORT_HTTP=8008, AUTHENTIK_PORT_HTTPS=8443, AUTHENTIK_ERROR_REPORTING__ENABLED=true
3. Run `docker-compose pull && docker-compose up -d`
4. See error via logs from worker and server container.

**Expected behavior**
Application should be reachable when going to https://`serverip`:8443/if/flow/initial-setup/.

**Logs**
`INF event=PostgreSQL connection failed, retrying... (connection to server at "postgresql" (192.168.80.4), port 5432 failed: FATAL:  password authentication failed for user "authentik"
) logger=authentik.lib.config timestamp=1674569107.8800704`

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: docker-compose

**Comment by LuXc-NL** [comment]
I already tried to open the port 5432 for the postgresql container and setting the environment variables without the .env file but no success.

**Comment by LuXc-NL** [comment]
Repaired it today. I created passwords without the exact length (PG_PASS 40 characters and SECRET_KEY 50 characters). Also deleted my volumes that were created and that did the trick.

**Comment by harveysm** [comment]
I'm running into this exact issue. Using compose from [https://goauthentik.io/docker-compose.yml](https://goauthentik.io/docker-compose.yml) Created .env same as documentation: 
echo "PG_PASS=$(openssl rand -base64 36 | tr -d '\n')" >> .env
echo "AUTHENTIK_SECRET_KEY=$(openssl rand -base64 60 | tr -d '\n')" >> .env

Both server & worker are giving the PostgreSQL connection failed mentioned above. Have tried deleting, recreating the authentik folders multiple times. Any other thoughts around this? If not, I might start a new issue for visibility. Thanks.
