### ISSUE TITLE
Dynamically update CONFIG from shell/other source

### ISSUE THREAD

**Issue by sevmonster** [goauthentik/authentik#4514]
**Describe your question**
I have a need to update `footer_links` while authentik is running. I would rather not have to restart it, as the value needs to be changed hourly. Is there any way to easily change this value, maybe from the authentik shell? I am thinking I could use the API but I feel that is overkill to set up for a root shell script.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.0
 - Deployment: docker-compose

**Additional context**
I tried `ak shell` and doing this:
```python
### authentik shell (2023.1.0)
### Node 21553f26306f | Arch x86_64 | Python 3.11.1
>>> from authentik.lib.config import CONFIG
>>> CONFIG.y('footer_links')
[]
>>> CONFIG.update_from_dict({'footer_links': [{'name': 'Link Name', 'href': 'https://goauthentik.io'}]})
>>> CONFIG.y('footer_links')
[{'name': 'Link Name', 'href': 'https://goauthentik.io'}]
```
But I believe this is not the actual live config the server is using, right? Since the list is empty after exiting the shell.

**Comment by BeryJu** [comment]
Currently, the config is only loaded on startup, I'm working on a PR that will allow values that reference files (via `file://`) to be updated whenever the file they are referencing updates
