### ISSUE TITLE
Add max-age for static content

### ISSUE THREAD

**Issue by Mortein** [goauthentik/authentik#4525]
`Cache-Control` in the response for static content doesn't have a `max-age`, so is not consistently cached.

https://github.com/goauthentik/authentik/blob/0bc1b33663e9f3eb7ab67e13c2c858de03e74d9a/internal/web/static.go#L64

Consider switching it to `max-age=604800, public, no-transform` for 7 days, or maybe longer (such as 30 days).

I don't think it should be a quoted string, only comma-separated. See Cache-Control on [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#directives) or [GeeksforGeeks](https://www.geeksforgeeks.org/http-headers-cache-control/).

**Comment by BeryJu** [comment]
Good point, the double quotes are probably not required

There's purposefully no max-age specified in the header as I have a feeling this would further increase the amount of cache-related issues, caused by certain vendors (*cough cloudflare cough*) not supporting the Vary header
