### ISSUE TITLE
Error 405 Method Not Allowed error when authenticating a proxy provider

### ISSUE THREAD

**Issue by jsaltzman** [goauthentik/authentik#4528]
**Describe the bug**
After updating to 2023.1.2, I can no longer authenticate my proxy provider forward auth applications/providers. While OAuth2, SAML apps/providers, and my authentik dashboard work, my forward auth proxy providers are down. Reverting to 2023.1.0 fixes the issue. I get the following error:

{"event": "Method Not Allowed: /application/o/token/", "level": "warning", "logger": "django.request", "timestamp": 1674656933.3394656}
{"error":"oauth2: cannot fetch token: 405 Method Not Allowed\nResponse: ","event":"failed to redeem code","level":"warning","logger":"authentik.outpost.proxyv2.application","name":"[App Name]","timestamp":"2023-01-25T09:28:53-05:00"}

**To Reproduce**
1. Create a proxy provider
2. Try and login
3. Error occurs. In chrome I get an error 400. In safari, I get a white page and the following URL: https://[subdomain].[domain].com/outpost.goauthentik.io/callback?X-authentik-auth-callback=true&code=2bd8e1e13ec24f22bec9c637d1b58878&state=uFP_DOFNyYc1PzkEc1R46NEkDUaZLXJOwX3OVn0eS8M

**Expected behavior**
There has not been a change in my configuration since updating to 2023.1.0, I should not be getting errors.
**Screenshots**

**Logs**
{"event": "Method Not Allowed: /application/o/token/", "level": "warning", "logger": "django.request", "timestamp": 1674656933.3394656}
{"error":"oauth2: cannot fetch token: 405 Method Not Allowed\nResponse: ","event":"failed to redeem code","level":"warning","logger":"authentik.outpost.proxyv2.application","name":"[App Name]","timestamp":"2023-01-25T09:28:53-05:00"}

When I go to events > log I do not see any errors. There are login, application authorized, and model created events.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2

**Comment by EugeneDae** [comment]
Same problem occurs after updating to 2023.1.2 from the November '22 version of Authentik, except that in the outpost config ("authentik Embedded Outpost") `authentik_host` value already has `https`... I've no clue where to even start debugging this.
