### ISSUE TITLE
Webview issue

### ISSUE THREAD

**Issue by Fma965** [goauthentik/authentik#4530]
Repeating the outstanding issue that was closed as stale

Still relevant as of 2023.1.2

https://github.com/goauthentik/authentik/issues/3304
> **Describe the bug**
> 
> The default "stacked" layout does not render right at all on Android (tested on Android 11 and Android 12) when authenticating via the Home Assistant mobile app.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Setup Home Assistant as a proxy auth provider as [described in the docs](https://goauthentik.io/integrations/services/home-assistant/)
> 2. Install the Home Assistant app
> 3. Try to set up Home Assistant app
> 
> **Expected behavior**
> 
> UI should be more usable. Stacked layout should appear like it does on a normal Web browser outside of the app.
> 
> **Screenshots**
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/490848/180493346-21953f20-dd52-4eb4-b567-db8df5542cfe.png">
> 
> **Logs** Output of docker-compose logs or kubectl logs respectively
> 
> **Version and Deployment (please complete the following information):**
> 
> * authentik version: authentik-2022.7.2
> * Deployment: helm
> 
> **Additional context**
> 
> It appears the div for the stack window is simply not centered vertically and has the incorrect height value. The div is scrollable and you can scroll to enter your email/password and try to figure out MFA (lol).

**Comment by florianschroen** [comment]
for those who also stumble across this topic...

I found a workaround [here](https://github.com/home-assistant/android/issues/1438#issuecomment-1328810156) by changing a setting in Admin-Interface: `Flows and Stages > Flows > default-authentication-flow > Edit > Appearance Settings > Layout: Content Left`
