### ISSUE TITLE
missing/strange values in fields username and email of user details.

### ISSUE THREAD

**Issue by pbvdven** [goauthentik/authentik#4531]
it looks like something went wrong while updating to 2023.1.2

i dont really have a idea how to fix this or if i did something wrong or maybe this is normal?

all users see Username Admin email instead of there username/email.
![image](https://user-images.githubusercontent.com/39600990/214656943-acad2f84-b056-49c9-a024-d9778786b46a.png)

also in enrollment the email field show admin email.
![image](https://user-images.githubusercontent.com/39600990/214658066-3056d159-f53a-493a-8040-f1ec8b3e54b6.png)

here the flow overview
![image](https://user-images.githubusercontent.com/39600990/214658671-b2eeddf1-8848-46d3-b0c3-7b3c4cdceba3.png)

![image](https://user-images.githubusercontent.com/39600990/214658825-03d888eb-cbc3-45fe-86dd-86c5dcecc01e.png)

**Comment by sevmonster** [comment]
Open the Email prompt and check the placeholder. What does it say?
![image](https://user-images.githubusercontent.com/16788697/214669964-c78d116f-85c2-4045-a941-872b74c3419b.png)

**Comment by BeryJu** [comment]
this is fixed by #4497

**Comment by pbvdven** [comment]
> Open the Email prompt and check the placeholder. What does it say? ![image](https://user-images.githubusercontent.com/16788697/214669964-c78d116f-85c2-4045-a941-872b74c3419b.png)

Thanks this was very helpful.
