### ISSUE TITLE
Is `depends_on` not needed for `docker-compose` installation?

### ISSUE THREAD

**Issue by septatrix** [goauthentik/authentik#4542]
**Describe your question/**
I have authentik set up using docker-compose though after inspecting the configuration a bit more in depth I noticed that it does not specify any `depends_on` for service ordering. Is this not necessary or has this simply been forgotten in the provided YAML spec?

Knowing that kubernetes does not provide such an ordering feature (as components should also be able to handle connection drops etc) it would not be surprised if ordering is not needed though a confirmation of this would be appreciated.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
It's purposefully omitted, as like you already said, Kubernetes doesn't have any mechanism like this. The authentik containers are designed to check for postgres and redis connectivity on startup, and not attempt to actually start before both are available. This means that in docker-compose, if the authentik server container is started before postgres and redis, it will simply keep trying to connect to both of them and only then properly start

**Comment by septatrix** [comment]
Thanks for the clarification.
