### ISSUE TITLE
Which configs apply to server, worker, and both?

### ISSUE THREAD

**Issue by septatrix** [goauthentik/authentik#4548]
**Describe your question/**
Based on the documentation it is not clear whether all configuration variables should be put in an environment file or if some only need to be applied to a single container.

**Comment by BeryJu** [comment]
Which options will be used by different components changes over time, hence it is assumed (and recommended) to set all the configuration options that are listed for both worker and server

**Comment by septatrix** [comment]
Thanks for the clarification
