### ISSUE TITLE
Allow passing secrets via a file instead of as an environment variable

### ISSUE THREAD

**Issue by septatrix** [goauthentik/authentik#4549]
**Is your feature request related to a problem? Please describe.**
Environment variables have several downsides which make them unsuitable for passing secrets. Excerpt from a man page:

> Note that environment variables are not suitable for passing secrets (such as passwords, key material, ...) to service processes. Environment variables set for a unit are exposed to unprivileged clients via D-Bus IPC, and generally not understood as being data that requires protection. Moreover, environment variables are propagated down the process tree, including across security boundaries (such as setuid/setgid executables), and hence might leak to processes that should not have access to the secret data.

**Describe the solution you'd like**
Kubernetes, Docker, but also many other ways to run services (like systemd) allow passing secrets as files instead of env vars.
This is safer and allows more fine-grained controls (like passing some stuff as env vars and only a few selected values as files).
The docker postgres image for example provides `POSTGRES_PASSWORD_FILE` as an alternative to the non-`_FILE` variant to read such secrets.
Python's [`pydantic`](https://docs.pydantic.dev/usage/settings/#secret-support) simply looks for secrets in a configurable directory (usually `/var/run` (systemd) or `/var/secrets` (docker)) and reads the content of all files whose names match config keys.

I am not very experienced in the golang world so I am not sure how the env vars are parsed and what solution people usually reach for in the go world. However, implementing one of the above ways (even without using libraries which provide these features) is rather straightforward.
Looking at the config mechanism it seems like all config access is nicely encapsulated and such a mechanism could be added during the setup/load phase without major problems. https://github.com/goauthentik/authentik/blob/a9680d6088178d052ce9e0f40b4bb83fee756a9c/internal/config/config.go#L49

Also I was unable to find any architecture documentation and am not sure which parts are Python/Django, which ones are Go and especially how they interact. So I am not sure whether this parsing would have to be implemented in two places...

**Describe alternatives you've considered**
Another rather exotiv way to support secret files would be to special case variables starting with `file:` though that would strictly speaking be backwards incompatible (as someone might have used that as part of their secret/password for questionable reasons).

**Comment by BeryJu** [comment]
This is already supported, see the third paragraph here https://goauthentik.io/docs/installation/configuration

**Comment by septatrix** [comment]
Oh sorry, I must have missed that
