### ISSUE TITLE
AWS IAM Identity Center SSO 

### ISSUE THREAD

**Issue by peakematt** [goauthentik/authentik#4554]
**Describe your question/**
I'm working on setting up Authentik as the identity provider for AWS IAM Identity Center (which is the rebranded name for AWS SSO). Neither app officially supports the other, but its just a SAML2 integration. I created the saml provider and app in Authentik and exchanged metadata files between the two apps. Both apps accepted the metadata and AWS redirects to Authentik. Both IdP and SP-initiated flows appear to start correctly. However, when redirected back to AWS, AWS' login screen presents a generic error message: `We couldn't complete your request right now. Please try again later. ` When I look in CloudTrail logs for the corresponding event, I get messages like: 
```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "Unknown",
        "principalId": "<AWS Account number>",
        "arn": "",
        "accountId": "<AWS Account number>",
        "accessKeyId": ""
    },
    "eventTime": "2023-01-28T17:16:48Z",
    "eventSource": "signin.amazonaws.com",
    "eventName": "ExternalIdPDirectoryLogin",
    "awsRegion": "us-east-2",
    "sourceIPAddress": "<my ip>",
    "userAgent": "<my user agent>",
    "errorMessage": "Response contains invalid name id policy format",
    "requestParameters": null,
    "responseElements": {
        "ExternalIdPDirectoryLogin": "Failure"
    },
    "requestID": "5d21c791-9132-4ea8-b6b7-5a07db654346",
    "eventID": "c148dedd-9057-4e63-b4ee-44c675f2353b",
    "readOnly": false,
    "eventType": "AwsConsoleSignIn",
    "managementEvent": true,
    "recipientAccountId": "<AWS Account number>",
    "eventCategory": "Management"
}
```

So - it seems like AWS is unhappy with the NameID being returned by Authentik. Based on [AWS' documentation](https://docs.aws.amazon.com/singlesignon/latest/userguide/other-idps.html), AWS SSO wants NameID to be an email address. I did go in and update the NameID property mapping value to be the Authentik default email attribute mapping (see screenshot), but that does not seem to help. Auth also did not work with the NameID Property Mapping field left unassigned. 

I haven't set up any SCIM functionality so I have to provision AWS IAM Identity Center users manually. I have confirmed that I have a user provisioned in AWS that matches the user information Authentik is asserting. 

Any thoughts on what might be causing this? Or ideas on what I might try changing to get it working? 

**Relevant infos**
using authentik version 2023.1.2 running from the official (ghcr.io/goauthentik/server:2023.1.2) container. My containers are scheduled by Hashicorp Nomad and HTTP traffic enters via a HAProxy reverse proxy that terminates TLS connections. 

**Screenshots**
<img width="1094" alt="Screenshot 2023-01-28 at 12 31 20 PM" src="https://user-images.githubusercontent.com/7741049/215281993-15bba3bf-a246-40e4-846c-4572984e8c83.png">

**Logs**
Not super relevant? I can provide details if needed, but Authentik shows a successful application authorization and AWS generates errors like above.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: Official docker container running in HashiCorp Nomad behind HAproxy. 

**Additional context**
None

**Comment by StevenMonty** [comment]
Having a very similar issue myself, commenting to stay in the loop

**Comment by BeryJu** [comment]
![image](https://user-images.githubusercontent.com/1932513/219600455-d1e186db-4268-473b-840c-4a42773885d7.png)
![image](https://user-images.githubusercontent.com/1932513/219600496-7d347851-e5a0-41f2-bd6d-e1f5b7495339.png)
These settings work for me, no custom NameID property required

**Comment by andresdb91** [comment]
@StevenMonty I got automatic provisioning working using SCIM by modifying the user and group property mappers to include:
- User:
  - externalId = str(request.user.id)
  - displayName = request.user.name
  - active = request.user.is_active
  - groups = [...] (optional, see below)

- Group:
  - externalId = str(group.group_uuid)
  - members = [...] (optional, see below)

I had to add the last one since users would be deactived by default without it.

To get user-group relationships to work I had to add the `groups` and `members` attributes to both user and group mappers following the [RFC structure](https://www.rfc-editor.org/rfc/rfc7643#section-8.3) and replacing the `..` by the Authentik URL followed by `/scim/v2` -> `https://authentik.ourdomain/scim/v2`.
For the values I used the same IDs previously specified as `externalId`, so `user.id` for the members and `group.group_uuid` for the groups in my case.
Finally, to iterate groups/members you have to use the [ManyToManyField defined in the User model](https://github.com/goauthentik/authentik/blob/main/authentik/core/models.py#L154) and iterate over the `all()` method:
```
for group in request.user.ak_groups.all():
  ...

for member in group.users.all():
  ...
```

Also for some reason users wouldn't get mapped if they didn't have any custom attributes in them so I put a simple `asd: asd` field in there.

**Comment by BeryJu** [comment]
@andresdb91 I just noticed that the displayName and active attributes got lost somehow when I migrated the provider to use mappings instead of having a fixed internal mapping, thanks!

Also FYI, I recommend not setting the externalId in your mapping as the provider sets this by default (https://goauthentik.io/docs/providers/scim/#using-in-conjunction-with-other-providers) and with the default value, the same identifier is used as with SAML and OAuth

Also for groups, you shouldn't have to do anything custom, as authentik will update the group membership when a user is added to/removed from a group

(During development I actually tested the provider mainly on the AWS SSO implementation of SCIM so this all *should* just work out of the box)

**Comment by BeryJu** [comment]
We have docs for the AWS Identity Center (or whatever they've renamed it to today) now, so I'll close this issue https://goauthentik.io/integrations/services/aws/#select-your-method

**Comment by kuzaxak** [comment]
Still reproducible with default settings. Any tips on how to troubleshoot it? 

@BeryJu

**Comment by jslay88** [comment]
I have followed the docs, gone through it multiple times. SCIM is working fine, users and groups are created, but I cannot seem to actually get any user to sign in. I have made sure the user has been added to AWS accounts with permission sets.

When a user tries to sign in, they are given the error 

![image](https://github.com/goauthentik/authentik/assets/6158929/f14435fe-fc9b-4d0a-b867-61c2127d3811)

**Comment by lanrat** [comment]
@jslay88 I had the exact same issue.

The problem was that I had Authentik's AWS SAML & SCIM providers using the `username` as the Authentik `username`, where AWS needs the `username` to be the user's `email`. This is not well documented and the error message is not helpful at all.


![Screenshot 2023-12-29 at 12 45 17 PM](https://github.com/goauthentik/authentik/assets/164192/d435d32b-dccc-44e0-b303-b8ea4908a7f0)


![Screenshot 2023-12-29 at 12 45 55 PM](https://github.com/goauthentik/authentik/assets/164192/b51828d3-a2bb-4976-bf99-f5fab0833691)

**Comment by jslay88** [comment]
> @jslay88 I had the exact same issue.
> 
> The problem was that I had Authentik's AWS SAML & SCIM providers using the `username` as the Authentik `username`, where AWS needs the `username` to be the user's `email`. This is not well documented and the error message is not helpful at all.
> 
> ![Screenshot 2023-12-29 at 12 45 17 PM](https://private-user-images.githubusercontent.com/164192/293422556-d435d32b-dccc-44e0-b303-b8ea4908a7f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDA1MTMsIm5iZiI6MTcwMzkwMDIxMywicGF0aCI6Ii8xNjQxOTIvMjkzNDIyNTU2LWQ0MzVkMzJiLWRjY2MtNDRlMC1iMzAzLWI4ZWE0OTA4YTdmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQwMTM2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWYwYTkwMDE5NzliMTc4M2U5OWU1MDk2OGJhYzUyMWFmOWEzM2YyMTUzMTU1MmMzYTJkYWYxNWUxM2VhOWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j2MEhpQfZAt8Ri1IgGmWrgHZ8Hi1ZGYvz07uMs98D0g)
> 
> ![Screenshot 2023-12-29 at 12 45 55 PM](https://private-user-images.githubusercontent.com/164192/293422607-b51828d3-a2bb-4976-bf99-f5fab0833691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MDA1MTMsIm5iZiI6MTcwMzkwMDIxMywicGF0aCI6Ii8xNjQxOTIvMjkzNDIyNjA3LWI1MTgyOGQzLWEyYmItNDk3Ni1iZjk5LWY1ZmFiMDgzMzY5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQwMTM2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDI0ZTczNmE1MDY0MTk1NWFiNDI5YjdlN2EwMDllYzVjMmMyNWY1NTEzNTc3NmViYjgyZWZmNmY3M2U1ZjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i0lCKOMgb0jY_R9u6chsDYRiW12FBll-OAxODkCZ_Zo)

Good find! I am not able to test this until late next week, but I definitely will!

**Comment by edw1nzhao** [comment]
@jslay88 did you end up figuring this out? I'm running into a similar problem here - I have SCIM working, but unable to login a user.

I'm using the first image's property mapping there in @jslay88 's comment.

**Comment by thechubbypanda** [comment]
@lanrat do you have a working solution at the moment?
I'm running up against the same "code isn't right" error.
I've swapped the default SAML username mapping with your suggested one but the problem does not change.

**Comment by thechubbypanda** [comment]
@lanrat I have added the SAML mapping from the first photo in a new mapping and then replaced the default `authentik default SAML Mapping: Username` with it. This does not appear to change anything.

What is the second screenshot? Would you be able to provide a slightly more detailed explanation of what goes where? I feel I may be missing something.

**Comment by lanrat** [comment]
@thechubbypanda you need 2 customized property mappings. Once for SAML (first screenshot) and one for SCIM (2nd screenshot)

![image](https://github.com/goauthentik/authentik/assets/164192/a855a23f-9297-4749-b289-10a3299c6161)

Here is the code for `authentik default SCIM Mapping: AWS-User`:

```python
# Some implementations require givenName and familyName to be set
givenName, familyName = request.user.name, " "
formatted = request.user.name + " "
# This default sets givenName to the name before the first space
# and the remainder as family name
# if the user's name has no space the givenName is the entire name
# (this might cause issues with some SCIM implementations)
if " " in request.user.name:
    givenName, _, familyName = request.user.name.partition(" ")
    formatted = request.user.name

# photos supports URLs to images, however authentik might return data URIs
avatar = request.user.avatar
photos = None
if "://" in avatar:
    photos = [{"value": avatar, "type": "photo"}]

locale = request.user.locale()
if locale == "":
    locale = None

emails = []
if request.user.email != "":
    emails = [{
        "value": request.user.email,
        "type": "other",
        "primary": True,
    }]
return {
    "userName": request.user.email,
    "name": {
        "formatted": formatted,
        "givenName": givenName,
        "familyName": familyName,
    },
    "displayName": request.user.name,
    "photos": photos,
    "locale": locale,
    "active": request.user.is_active,
    "emails": emails,
}
```

Each mapping is used by the SAML and SCIM providers, respectively.

![image](https://github.com/goauthentik/authentik/assets/164192/24bdb378-23c9-4d32-8a74-3fbd89262681)


## SAML

![image](https://github.com/goauthentik/authentik/assets/164192/5230cac4-9ef1-43b5-8cff-7344a8615cf1)

## SCIM

![image](https://github.com/goauthentik/authentik/assets/164192/e5c3f86e-b786-43c9-8081-a1c0e8706e94)

**Comment by thechubbypanda** [comment]
@lanrat Thank you, the SCIM mapping was what I was missing. Works a treat now. I wish that error message was a bit clearer! :joy:

**Comment by timvw** [comment]
I also struggled with this, the configuration provided by @lanrat worked.
Noticed that depending on your SCIM mapping for username you need a different name_id_mapping.

Here is what works for me, in terraform: https://gist.github.com/timvw/efae5eeb9a777078a1d9a7564cd2df23

**Comment by kagesenshi** [comment]
Adding a note here in case someone else had trouble to get this to work. On my setup `photos` (which provide gravatar URLs) seems to cause issue with SCIM sync. Setting it to `None` works around it.

**Comment by watn3y** [comment]
@timvw What did you end up selecting here in the SCIM Provider Settings:

<img width="862" height="246" alt="Image" src="https://github.com/user-attachments/assets/255c83ee-59d3-4d88-b0ca-e557bea77bd0" />

**Comment by timvw** [comment]
When I go to the edit page of the scim provider "Default" is selected... 

(Consistent with my terraform gist and the [documentation](https://registry.terraform.io/providers/goauthentik/authentik/latest/docs/resources/provider_scim#optional)
[compatibility_mode](https://registry.terraform.io/providers/goauthentik/authentik/latest/docs/resources/provider_scim#compatibility_mode-1) Defaults to "default"

**Comment by LaPlazesDemon** [comment]
> @thechubbypanda you need 2 customized property mappings. One for SAML (first screenshot) and one for SCIM (2nd screenshot)
> 
> ![image](https://github.com/goauthentik/authentik/assets/164192/a855a23f-9297-4749-b289-10a3299c6161)
> 
> Here is the code for `authentik default SCIM Mapping: AWS-User`:
> 
> # Some implementations require givenName and familyName to be set
> givenName, familyName = request.user.name, " "
> formatted = request.user.name + " "
> # This default sets givenName to the name before the first space
> # and the remainder as family name
> # if the user's name has no space the givenName is the entire name
> # (this might cause issues with some SCIM implementations)
> if " " in request.user.name:
>     givenName, _, familyName = request.user.name.partition(" ")
>     formatted = request.user.name
> 
> # photos supports URLs to images, however authentik might return data URIs
> avatar = request.user.avatar
> photos = None
> if "://" in avatar:
>     photos = [{"value": avatar, "type": "photo"}]
> 
> locale = request.user.locale()
> if locale == "":
>     locale = None
> 
> emails = []
> if request.user.email != "":
>     emails = [{
>         "value": request.user.email,
>         "type": "other",
>         "primary": True,
>     }]
> return {
>     "userName": request.user.email,
>     "name": {
>         "formatted": formatted,
>         "givenName": givenName,
>         "familyName": familyName,
>     },
>     "displayName": request.user.name,
>     "photos": photos,
>     "locale": locale,
>     "active": request.user.is_active,
>     "emails": emails,
> }
> Each mapping is used by the SAML and SCIM providers, respectively.
> 
> ![image](https://github.com/goauthentik/authentik/assets/164192/24bdb378-23c9-4d32-8a74-3fbd89262681)
> 
> ## SAML
> ![image](https://github.com/goauthentik/authentik/assets/164192/5230cac4-9ef1-43b5-8cff-7344a8615cf1)
> 
> ## SCIM
> ![image](https://github.com/goauthentik/authentik/assets/164192/e5c3f86e-b786-43c9-8081-a1c0e8706e94)

Can we please get this put into the official Authentik Cloud Provider docs?
