### ISSUE TITLE
Authentik forward_auth (domain) + caddy, being redirected to the library after a successful auth

### ISSUE THREAD

**Issue by marouamghar** [goauthentik/authentik#4555]
**Describe the bug**
I use caddy proxy and authentik. When I type in my app's link (ex app.server), i get forwarded to autntik, I see in the logs that the first request has a host of app.server, but as soon as I successfully auth, the subsequent calls have a host of authentik.server. At the end, I am redirected to my authentik's library.

**To Reproduce**
Create an app.

Create a proxy provider, of type forward auth (domain level)
![image](https://user-images.githubusercontent.com/78270663/215302341-22fec51f-a79a-4d54-8621-9d340a955b4b.png)

Add the provider to the enbedded outpost.
![image](https://user-images.githubusercontent.com/78270663/215302369-ecc7fb1f-8f89-457b-b056-b920ae2819c1.png)

Set up a reverse proxy in caddy, using the documentation provided:
`app.server {
        # import authentik
        
        # always forward outpost path to actual outpost
        reverse_proxy /outpost.goauthentik.io/* authentik:9000

        # forward authentication to outpost
        forward_auth authentik:9000 {
                uri /outpost.goauthentik.io/auth/caddy

                # capitalization of the headers is important, otherwise they will be empty
                copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version

                # optional, in this config trust all private ranges, should probably be set to the outposts IP
                trusted_proxies private_ranges
        }

        reverse_proxy app:80
        tls internal
}`

Try to login to an app hosted on the same server, such as app.server.
**Expected behavior**
Get redirected to my app

**Screenshots**

**Logs**
`{"event":"hello'd","level":"trace","logger":"authentik.outpost.ak-api-controller","loop":"ws-health","timestamp":"2023-01-29T02:49:04Z"}
{"app":"Local server","event":"Found app based on cookie domain","host":"app.server","level":"debug","logger":"authentik.outpost.proxyv2","timestamp":"2023-01-29T02:49:10Z"}
{"event":"passing to application mux","host":"app.server","level":"trace","logger":"authentik.outpost.proxyv2","timestamp":"2023-01-29T02:49:10Z"}
{"event":"tracing headers for debug","header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Language":["en-US,en;q=0.9"],"Sec-Ch-Ua":["\"Chromium\";v=\"109\", \"Not_A Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["none"],"Sec-Fetch-User":["?1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"],"X-Forwarded-For":["10.0.0.2"],"X-Forwarded-Host":["app.server"],"X-Forwarded-Method":["GET"],"X-Forwarded-Proto":["https"],"X-Forwarded-Uri":["/"]},"level":"trace","logger":"authentik.outpost.proxyv2.application","name":"Local server","timestamp":"2023-01-29T02:49:10Z"}
{"event":"traefik forwarded url","level":"trace","logger":"authentik.outpost.proxyv2.application","name":"Local server","timestamp":"2023-01-29T02:49:10Z","url":"https://app.server/"}
{"event":"/outpost.goauthentik.io/auth/caddy","host":"app.server","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Local server","remote":"10.0.0.2","runtime":"2.569","scheme":"http","size":359,"status":302,"timestamp":"2023-01-29T02:49:10Z","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}
{"app":"Local server","event":"Found app based direct host match","host":"authentik.server","level":"trace","logger":"authentik.outpost.proxyv2","timestamp":"2023-01-29T02:49:10Z"}
{"event":"tracing request to backend","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Language":["en-US,en;q=0.9"],"Sec-Ch-Ua":["\"Chromium\";v=\"109\", \"Not_A Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["none"],"Sec-Fetch-User":["?1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"],"X-Forwarded-For":["10.0.0.2"],"X-Forwarded-Host":["authentik.server"],"X-Forwarded-Proto":["https"]},"level":"trace","logger":"authentik.router","timestamp":"2023-01-29T02:49:10Z","url":"http://localhost:8000/application/o/authorize/?client_id=k7EWuG41YzdQgmxqOvkR5qlpGt1ipS9h81fBrwsg&redirect_uri=https%3A%2F%2Fauthentik.server%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=profile+openid+email+ak_proxy&state=g6PMu9pA-ZQZrUj3qFkue1cJ-gyvxN_bmf2L75zBFEI"}
{"auth_via": "unauthenticated", "event": "/application/o/authorize/?client_id=k7EWuG41YzdQgmxqOvkR5qlpGt1ipS9h81fBrwsg&redirect_uri=https%3A%2F%2Fauthentik.server%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=profile+openid+email+ak_proxy&state=g6PMu9pA-ZQZrUj3qFkue1cJ-gyvxN_bmf2L75zBFEI", "host": "authentik.server", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 25, "remote": "10.0.0.2", "request_id": "bbcf4b01d5234635bbe7e16c4924affd", "runtime": 24, "scheme": "https", "status": 302, "timestamp": "2023-01-29T02:49:10.287764", "user": "", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}
{"app":"Local server","event":"Found app based direct host match","host":"authentik.server","level":"trace","logger":"authentik.outpost.proxyv2","timestamp":"2023-01-29T02:49:10Z"}`

I used log level trace. I trimmed after that last sentenec, because since then there is no mention of my app name on my logs. As you can see, it starts with a good host (app.server), then at some point it just forgets about it. Weird thing, I am using caddy, but there is still a mention of traefik in the logs.

**Version and Deployment (please complete the following information):**
 - authentik version: latest
 - Deployment: docker compose

**Comment by tgxn** [comment]
I have the exact same problem with `2023.1.2` try using `2022.10.1` which worked for me
```
image: ghcr.io/goauthentik/server:2022.10.1
```

**Comment by techn0pia** [comment]
Any update to this bug?

I have the same problem with Caddy.
But also with Nginx Proxy Manager I used before.

**Comment by xadves** [comment]
I spent a lot of time searching for this, I found the documentation does not cover a very important part. For my specific setup, I have a Caddy proxy setup in front of authentik and needed to add:

auth.mydomain.tld
```
# Authelia use Host for redirect URL instead of X-Forwarded-Host for some reasons
                header_up Host {http.request.header.X-Forwarded-Host}

                # We don't want to change some of the X-Forwarded-*, or use trusted_proxies instead
                header_up X-Forwarded-Host {http.request.header.X-Forwarded-Host} 
                header_up X-Forwarded-Proto {http.request.header.X-Forwarded-Proto}
```

in addition to the suggested setup from authentik on the outpost. 

I found this old issue where this solution was talked about https://github.com/caddyserver/caddy/issues/5244

**Comment by rriemann** [comment]
Dear @xadves ,

For testing, I try to put authentik in front of some webservice (proxy config, here uptime-kuma). Both authentik and webservice are served via caddy.

However, I get in a redirect loop. Can you post a few more details of what is working for you and which configuration you have in place?

Best,
Robert

![image](https://github.com/goauthentik/authentik/assets/111932/fed00d89-937b-4e8c-83e5-4de3ad5e13e4)


~~~Caddyfile
(authentik) {
	forward_auth http://authentik:9000 {
		copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version
		uri /outpost.goauthentik.io/auth/caddy
	}
	reverse_proxy /outpost.goauthentik.io/* http://authentik:9000
}

auth.some-domain.cc {
	log
	reverse_proxy 172.19.0.5:9000 {
		header_up Host {http.request.header.X-Forwarded-Host}
		header_up X-Forwarded-Host {http.request.header.X-Forwarded-Host}
		header_up X-Forwarded-Proto {http.request.header.X-Forwarded-Proto}
	}
	tls {
		dns gandi [TOKEN]
	}
}

status.some-domain.cc {
	import authentik
	reverse_proxy 172.19.0.6:3001
	tls {
		dns gandi [TOKEN]
	}
}
~~~

In authentik, I have:

![image](https://github.com/goauthentik/authentik/assets/111932/626d1d8e-bbef-48bb-837a-6c79eb586a62)


Everything lives on the same docker host with containers reachable as uptime-kuma, authentik and caddy.

**Comment by JPBeltman** [comment]
Have you solved your issues @rriemann? Ran in to the same issues as you did but managed to fix it, here are the relevant parts of my config. Everything is hosted in vm's on Proxmox, so no docker-hostnames.

Please also note the difference in providers, I'm using `domain level forward-auth` ( instead of individual proxies)

#### Caddyfile snippet
```
(authentik) {
        reverse_proxy /outpost.goauthentik.io/* http://10.0.1.103 {
                header_up Host {http.reverse_proxy.upstream.hostport}
        }

        forward_auth http://10.0.1.103 {
                uri /outpost.goauthentik.io/auth/traefik
                copy_headers X-Authentik-Username X-Authentik-Groups ......
                trusted_proxies 10.0.1.1/24
        }
}

git.{$DOMAIN} {
        import authentik
        reverse_proxy 10.0.1.100:80
}

auth.{$DOMAIN} {
        reverse_proxy 10.0.1.103:80
}
```

#### Authentik web
##### Providers:
Proxy-provider, domain level FA: 
  authentication url; `https://auth.{$DOMAIN}`, cookies; `{$DOMAIN}`
##### Application:
Embedded outpost -> configuration:
`authentik_host: https://auth.{$DOMAIN}`

-------------

Regarding your post, I think you're mixing up different articles/posts, some guides have a general import statement but some handle it inside the proxy body: you're doing both right now?

**Comment by rriemann** [comment]
Hi @JPBeltman, thanks for getting back with code. I got it running. Most importantly, I had to switch to *forward auth (single application)*. I guess for the domain, it would have worked at all.

For caddy, all upstream headers are [set by default](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults). So I deleted all header_up statements.

You wrote:
>  I think you're mixing up different articles/post […]  you're doing both right now?

I do not see what you refer to. I tried to follow https://goauthentik.io/docs/providers/proxy/server_caddy .
