### ISSUE TITLE
x509 : Cannot validate certificate for [IP] because it doesn't contain any IP SANs on ak-outpost-outportldap docker container

### ISSUE THREAD

**Issue by tech62** [goauthentik/authentik#4557]
**Describe the bug**
The console loop on the error reported in the title

**To Reproduce**
1. Clone repo
2. Setup the configuration file
3. Start docker

![image](https://user-images.githubusercontent.com/16237642/215314894-be9bf282-2b75-469b-92f2-ccb90a61eaae.png)

**Comment by BeryJu** [comment]
This happens due to authentik configuring the embedded outpost based on the URL authentik is first accessed at. You can configure the domain in the applications -> outpost settings and change `authentik_host` to the domain you plan to access authentik at
