### ISSUE TITLE
Documentate unoffice kubernetes Operatoren

### ISSUE THREAD

**Issue by genofire** [goauthentik/authentik#4558]
**Is your feature request related to a problem? Please describe.**
To automate the Setup (with Application and so on), it would be nice, to have in kubernetes an operator. Which you could configure with CustomResourceDefinitions (CRDs):
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/

**Describe the solution you'd like**
Till authentik has no own Operator, it should documentat, that there are some.

**Describe alternatives you've considered**

**Additional context**
Operatoren which i found:
  - https://gitlab.com/GeorgeRaven/authentik-manager in Golang written
  - https://github.com/dsluijk/authentik-operator in Rust

**Comment by MacroPower** [comment]
Just going to casually toss my little project in the ring as well. I made a Crossplane provider for Authentik using upjet (code generated from the Terraform provider) and have been using it for a few months:
https://github.com/MacroPower/provider-authentik

Example provider config:
https://github.com/MacroPower/homelab/blob/main/applications/base/crossplane-packages/authentik.yaml

I'm still learning about Compositions and am working on making some examples here:
https://github.com/MacroPower/homelab/tree/main/applications/base/authentik/config

Might not be as good as some of these. But being able to just do code generation using the already written Terraform provider is quite convenient.

**Comment by BeryJu** [comment]
For all the projects mentioned in this thread, feel free to email us at hello+community@goauthentik.io and we can include the project in https://github.com/authentik-community (of course the creators will retain all their ownership, this is just a place to put together projects around authentik)

**Comment by Kampe** [comment]
Incredible thanks@MacroPower!!
