### ISSUE TITLE
Locale Auto-detect doesn't work

### ISSUE THREAD

**Issue by Izanagi52** [goauthentik/authentik#4562]
**Describe the bug**
Using a browser configured in French, but Authentik is in English when locale is "Auto-detect".

**To Reproduce**
1. Got to Authentik with a French browser
2. View Authentik UI in English

**Expected behavior**
Authentik UI in French.

**Logs**
Logs of Firefox and Chrome debug console
`authentik(early): version 2023.1.2, apiBase /api/v3 [config.ts:105:8]
authentik/locale: No matching locale for en-us [locale.ts:147:20]
authentik/locale: Activating detected locale 'en' [locale.ts:143:20]`

**Version and Deployment (please complete the following information):**
 - 2023.1.2
 - docker compose

**Additional context**
Tested with multiple browser (Chrome Desktop 109.0.5414.120, Chrome Android 109.0.5414.117, Firefox 109.0)

**Comment by BeryJu** [comment]
Can you run `navigator.language || navigator.userLanguage` in the browser's developer console and post the output?

**Comment by Izanagi52** [comment]
In Firefox:
"fr"
In Chrome: 
'fr-FR'

**Comment by xavierjulie** [comment]
same problem for me with 2023.2

**Comment by Izanagi52** [comment]
Problem still present in 2023.4.1

**Comment by manuviens** [comment]
Not sure if it's the same issue, but it don't work in 2023.5.3.
My preferred languages in Firefox and Chromium are (in priority order) :
- fr-ca
- fr
- en-ca
- en
But pages shows in english.

Also, in the user settings, the list of available languages appears oddly :
![image](https://github.com/goauthentik/authentik/assets/98410832/7e94796a-ba54-46e9-977c-84c98756fd33)

**Comment by serxoz** [comment]
I'd like to report the same with Spanish and version 2023.6.0
I've tried Firefox and Chromium and both 'es' and 'es-ES'.

**Comment by sevmonster** [comment]
This got fixed at some point.

**Comment by Izanagi52** [comment]
Not resolved in 2023.8.3

**Comment by Izanagi52** [comment]
Not resolved in 2023.10.5

**Comment by Izanagi52** [comment]
Not resolved in 2024.2.1.

**Comment by felixscheinost** [comment]
To me it seems like the precedence of the locales is wrong.

In `helpers.ts` the following code is executed:

```ts
    const localeCandidates: string[] = [
        globalAK()?.locale ?? TOMBSTONE,
        localeCodeFromUrl("locale"),
        requestedCode ?? TOMBSTONE,
        window.navigator?.language ?? TOMBSTONE,
        DEFAULT_LOCALE,
    ].filter(isLocaleCandidate);
```

In my case this evaluates to: `['en-us', 'en', 'de', 'en']`

If I add `.map(getBestMatchLocale)`, `de` keeps there but in 3rd place.

My browser is set to `de` and I would expect `de` to take precedence. But seems that currently `globalAk()?.locale` takes precedence?

**Comment by felixscheinost** [comment]
The browser language seems to be respected correctly in 2024.4.1 now, thanks!

**Comment by Izanagi52** [comment]
Yes it works now, thanks!
