### ISSUE TITLE
Include callback url in e-mail confirmation?

### ISSUE THREAD

**Issue by hkdb** [goauthentik/authentik#4577]
**Describe your question/**
New to authentik here. I am currently using different custom built apps to authenticate via the Authentik oauth2 provider and passing the callback url via the query string which works well for login. (ie. app redirects to login with callback in query string --> Login --> Redirect back to my application based on callback url in query string.)

For enrollment, if I don't bind an e-mail confirmation stage, it works well too as it automatically redirects back to my application once the "default-source-enrollment-write" stage completes. However, if I bind an e-mail confirmation stage to the flow, the existing query string is obviously not included in the url sent by the e-mail so it also doesn't include it in the login stage either which then lands the user into the Library page after the login stage instead of the originally specified callback url.

If I only had one application authenticating against my authentik's oauth2 provider, I know that I can hardcode a redirect with an expression policy but since I would like to authenticate for multiple applications, that doesn't really work.

So my question is, given the situation/flow, what is the best and most proper way to ensure that the callback url is included in the emailed URL so that it can be used for login?

Your help is much appreciated! Thanks!

**Relevant infos**
N/A 

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.10.1
 - Deployment: docker-compose

**Additional context**
N/A

**Comment by BeryJu** [comment]
This shouldn't be an issue anymore as this was fixed quite a few versions ago. @hkdb could you double check and re-open this if this is still an issue
