### ISSUE TITLE
Changing the parent group of a group removes all users from the group

### ISSUE THREAD

**Issue by a-gerhard** [goauthentik/authentik#4578]
**Describe the bug**
Changing the parent group of a group removes all users from the group. This means that I also lose that information and had to reconstruct who was a member of that group.

I have not checked what happens when I edit any other property of the group.

**To Reproduce**
1. Create a group with no parent group
2. Add one or more users to that group
3. Edit the group and set another group as parent
4. Go back to the users list of the group, and you'll see it's empty.
5. Add one or more users to that gorup
6. Edit the group and set parent group to None (------)
7. Go back to the users list of the group, and you'll see it's also empty.

**Expected behavior**
Group Membership to that group is not changed

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.0
 - Deployment: docker-compose

**Additional context**
The users are users that have been imported by an LDAP source, the group has been created locally in authentik.

**Comment by BeryJu** [comment]
This seems to be a race condition when confirming the group update form prior to the users having loaded

**Comment by BeryJu** [comment]
Since user updates are no longer made from the group edit modal, this shouldn't be an issue anymore; feel free to re-open the issue if it still is
