### ISSUE TITLE
Sentry - Authentik integration

### ISSUE THREAD

**Issue by elg0ch0** [goauthentik/authentik#4579]
**Describe your question/**
Is[ the guide](https://goauthentik.io/integrations/services/sentry/) to integrate Sentry with Authentik still updated?
I did what's indicated there but by the time I input these values:

```
IdP User ID: http://schemas.goauthentik.io/2021/02/saml/uid
User Email: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
First Name: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name

```
it returns an "**Oops! Something went wrong**" error

**Relevant infos**
 - Sentry version: 22.11.0 60999b0

**Screenshots**
N/A

**Logs**

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/views.py", line 68, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/web/frontend/base.py", line 295, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/sentry/web/frontend/organization_auth_settings.py", line 224, in handle
    return helper.current_step()
  File "/usr/local/lib/python3.8/site-packages/sentry/pipeline/base.py", line 172, in current_step
    return self.dispatch_to(step)
  File "/usr/local/lib/python3.8/site-packages/sentry/auth/helper.py", line 723, in dispatch_to
    return step.dispatch(request=self.request, helper=self)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/web/frontend/base.py", line 295, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/auth/providers/saml2/generic/views.py", line 70, in handle
    return helper.next_step()
  File "/usr/local/lib/python3.8/site-packages/sentry/pipeline/base.py", line 219, in next_step
    return self.current_step()
  File "/usr/local/lib/python3.8/site-packages/sentry/pipeline/base.py", line 172, in current_step
    return self.dispatch_to(step)
  File "/usr/local/lib/python3.8/site-packages/sentry/auth/helper.py", line 723, in dispatch_to
    return step.dispatch(request=self.request, helper=self)
  File "/usr/local/lib/python3.8/site-packages/sentry/auth/providers/saml2/provider.py", line 82, in dispatch
    auth = build_auth(request, saml_config)
  File "/usr/local/lib/python3.8/site-packages/sentry/auth/providers/saml2/provider.py", line 399, in build_auth
    return OneLogin_Saml2_Auth(saml_request, saml_config)
  File "/usr/local/lib/python3.8/site-packages/onelogin/saml2/auth.py", line 59, in __init__
    self._settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
  File "/usr/local/lib/python3.8/site-packages/onelogin/saml2/settings.py", line 128, in __init__
    raise OneLogin_Saml2_Error(
onelogin.saml2.errors.OneLogin_Saml2_Error: Invalid dict settings: sp_acs_url_invalid,sp_sls_url_invalid
13:56:48 [ERROR] django.request: Internal Server Error: /organizations/sentry/auth/configure/ (status_code=500 request=<WSGIRequest: POST '/organizations/sentry/auth/configure/'>)
13:56:48 [INFO] sentry.access.api: api.access (method='POST' view='sentry.web.frontend.organization_auth_settings.OrganizationAuthSettingsView' response=500 user_id='56' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/organizations/sentry/auth/configure/' caller_ip='178.128.227.216' user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.3138861656188965 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
13:56:48 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_details.OrganizationDetailsEndpoint' response=200 user_id='56' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/' caller_ip='x.x.x.x' user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.1407325267791748 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
13:56:49 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_teams.OrganizationTeamsEndpoint' response=200 user_id='56' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/teams/' caller_ip='x.x.x.x' user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.16913318634033203 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
13:56:49 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_projects.OrganizationProjectsEndpoint' response=200 user_id='56' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/projects/' caller_ip='x.x.x.x' user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.22551870346069336 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.7.1
 - Deployment: helm chart (using Rancher UI)

**Additional context**
- Sentry on-premise deployment.

**Comment by BeryJu** [comment]
The errors seem to point to an invalid url `onelogin.saml2.errors.OneLogin_Saml2_Error: Invalid dict settings: sp_acs_url_invalid,sp_sls_url_invalid`

could you post the URLs you've specified in sentry?

**Comment by elg0ch0** [comment]
I used those indicated in the document:

```
IdP User ID: http://schemas.goauthentik.io/2021/02/saml/uid
User Email: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
First Name: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name

```

Sentry asks for the last name also, so as a test I provided the same value as First Name.

I noticed that schemas.goauthentik.io does not resolve to an IP address, so that's why I wondered if the document was updated

```
$ nslookup schemas.goauthentik.io
Server:         192.168.1.1
Address:        192.168.1.1#53

** server can't find schemas.goauthentik.io: NXDOMAIN
```

and I get a 404 error when trying:

```
$ curl -L -I  -X GET "https://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
HTTP/2 404 
content-length: 103
content-type: text/html
server: Microsoft-IIS/10.0
x-cache: TCP_MISS
x-powered-by: ASP.NET
x-azure-ref-originshield: 0CUbYYwAAAACdC9v68D2nSLUFlUH6VVeFTU5aMjIxMDYwNjExMDMxAGEwZDBiZDNkLWZkNmItNDA3My04ZDJmLWMwNmVjMzNkMTVjZQ==
nel: {"report_to":"network-errors","max_age":604800,"success_fraction":0.01,"failure_fraction":1.0}
report-to: {"group":"network-errors","max_age":604800,"endpoints":[{"url":"https://mdec.nelreports.net/api/report?cat=schemas"}]}
x-azure-ref: 0CUbYYwAAAADct00U+pk0QJJQIclJGiTwWU1RMDFFREdFMDkwOABhMGQwYmQzZC1mZDZiLTQwNzMtOGQyZi1jMDZlYzMzZDE1Y2U=
date: Mon, 30 Jan 2023 22:34:50 GMT
```

**Comment by BeryJu** [comment]
While those fields are URLs, they are not meant to be accessed, they are simply unique identifiers for the data in SAML requests/responses

Can you post the ACS URL specified in sentry?

**Comment by elg0ch0** [comment]
> Can you post the ACS URL specified in sentry?

In Sentry?
I specified the ACS URL only in authentik when I created the SAML Provider, its value is:

`https://mysentry-server/saml/acs/sentry/`

**Comment by BeryJu** [comment]
Sorry, I meant the `Single Sign On URL` in sentry

**Comment by elg0ch0** [comment]
It's working now after updating a pair of things:
1. Add system.url-prefix: "https://mysentry-server" to config.yml ConfigMap sentry-sentry)
2. Adjust FW rules (authentik and sentry are not on the same network)

I will continue from there

Thanks a lot, @BeryJu!
