### ISSUE TITLE
How to replace the default background image in ALL flows?

### ISSUE THREAD

**Issue by AlphaJack** [goauthentik/authentik#4586]
**Describe your question**

How to replace the default background image in ALL flows?

**Relevant infos**

I can set a custom background for most flows under Flow & Stages > Flows > Update Flow > Appearance Settings, but it still appears in some pages (even within a customized flow, e.g. when a user is not allowed).   
Maybe a global option could help?

**Screenshots**

For instance, I cannot find the option to customize the following screens:

The logout flow (Default Invalidation Flow) has already a custom background, but I see this when a OAuth2 logout appears:

![mountain-2](https://user-images.githubusercontent.com/19962243/216031491-c38ed019-136b-4b1c-be6c-999d58ad21d0.png)

This screen appeared when I tried to access an application as a non-whitelist user:

![mountain-1](https://user-images.githubusercontent.com/19962243/216031460-58a25422-d7ad-4fca-adc4-d33dbedcd55c.png)

**Logs**

Not relevant

**Version and Deployment (please complete the following information):**

 - authentik version: 2023.1
 - Deployment: podman

**Additional context**

Other things I saw, with lower importance:

1. The authentik tenant Title property is not used in the log off screen, and "Log out of **authentik**" is used instead.
2. When selecting the same background image for a new flow (it has the same name), the image is uploaded with a different suffix to make the name unique, even if it could reuse the file already present in the server:

![bg](https://user-images.githubusercontent.com/19962243/216035820-6fc47fd8-0354-457c-b99a-4f6eec4c5f3e.png)

**Comment by sevmonster** [comment]
Do note you can replace backgrounds [programmatically](https://github.com/goauthentik/authentik/issues/4340#issuecomment-1402460831) rather than replace all of them one at a time. I do agree it would be a nice comfort feature however to have a tenant-wide default background, and leave the flow backgrounds unset/blank to fall back to that background.

**Comment by sevmonster** [comment]
I have actually been interested in this a bit myself and did some digging. @BeryJu added `custom.css` a year ago but it is not included with any of the shadow DOMs which severely limits its usage. If that were not the case you could solve this issue with some CSS.

In any case, see also this issue for some potential workarounds: #2364

Dupe: #3974

Related: #3845 #2693

**Comment by BeryJu** [comment]
The reason why the custom css is not included in the shadow dom components is because then indeed it would be compiled into the javascript bundle, and changes to it would not be reflected

The issue for file uploads is unrelated and the current behaviour is caused by how the Django FileField works, and requiring a lot of boilerplate for each model that can accept a file. but I'm working on a different way of dealing with files which will allow re-using of files and setting more defaults on a tenant level

**Comment by kekalainen** [comment]
An alternative workaround using triggers to maintain a default value:

```sql
CREATE OR REPLACE FUNCTION set_default_flow_background()
RETURNS TRIGGER AS $$
BEGIN
    NEW.background = '/background.jpg';
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_default_flow_background_trigger ON authentik_flows_flow;

CREATE TRIGGER set_default_flow_background_trigger
	BEFORE INSERT OR UPDATE ON authentik_flows_flow
	FOR EACH ROW
	WHEN (NEW.background IS NULL OR NEW.background = '')
	EXECUTE FUNCTION set_default_flow_background();
```

_This might cause issues with future migrations._

**Comment by BeryJu** [comment]
I think for the time being the best solution is still to just map over the default file in the container, which we should also document. Also the method of using the `custom.css` file to set an image from a different URL if you don't want to use a local file

**Comment by kekalainen** [comment]
@BeryJu while perhaps less fragile, those workarounds would lead to [false attribution](https://github.com/goauthentik/authentik/blob/c5222bf439ec15959673695c8fb21b8e0dc9edd8/web/src/flow/FlowExecutor.ts#L527-L536) and the above-mentioned preloading issue, though, no?

**Comment by sevmonster** [comment]
> [false attribution](https://github.com/goauthentik/authentik/blob/c5222bf439ec15959673695c8fb21b8e0dc9edd8/web/src/flow/FlowExecutor.ts#L527-L536)

That alone is enough to make the solution unworkable. Is there a reason why the match is so broad? You can't even mount your own files to `/static` because of this, should you see that as a beneficial option.

**Comment by almereyda** [comment]
While the `:root` selector did not work with a fresh `2023.8.1` install, `.pf-c-background-image` did.

The snippet in use with us is hence:

```
.pf-c-background-image {
    --ak-flow-background: url('https://example.com/images/logo.svg') !important;
}

```

**Comment by ektorasdj** [comment]
Hello everyone, I want to thank the developer for this fine tool.
While the above worked and I was able to change the background image for those flows that cant be changed from the UI, i also want to be able to change the layout to the sidebar-left.
Is this possible (Not just aligned to the left from CSS but to do it like you can do it from the UI for the other Flows)?
Thank you

**Comment by sevmonster** [comment]
You should probably open another issue for that. I believe the default non-flow pages use a fixed layout.

**Comment by BeryJu** [comment]
duplicate of #4586, see https://github.com/goauthentik/authentik/issues/4340#issuecomment-2064525132

**Comment by LoganTann** [comment]
The default background can indeed be changed in the branding settings page.
