### ISSUE TITLE
PGAdmin documentation outdated

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#4603]
**Describe the bug**
Since pgadmin version 6.18 logins into pgadmin via authentik are not working. Authentik docs might be updated.
Related pgadmin issue: https://github.com/pgadmin-org/pgadmin4/issues/5666
More details in the issue i mentioned.

**To Reproduce**
1. Setup pgadmin and authentik following the authentik docs: https://goauthentik.io/integrations/services/pgadmin/
2. try to login into pgadmin via authentik

**Expected behavior**
Login works

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: helm

**Comment by BeryJu** [comment]
Edit the OAuth provider and select a signing key, and restart pgadmin. That should fix it. If so I'll update the docs to include that

**Comment by benedikt-bartscher** [comment]
Thanks @BeryJu the only thing i missed was to restart pgadmin. It works fine now. So pgadmin only fetches the metadata url at startup?
