### ISSUE TITLE
Invalid YAML in example and blueprint flows

### ISSUE THREAD

**Issue by AlphaJack** [goauthentik/authentik#4604]
**Describe the bug**

EDIT: the "Apply Blueprint" functionality inside authentik works, everything I'm writing here refers to the "Import flow" button

The YAML code is flawed in the following example flows present in the website.  
Authentik returns 405 method not allowed when I try to upload them, while https://yaml-online-parser.appspot.com/ gives an in-depth detail of the faulty line:

```
ERROR:

could not determine a constructor for the tag '!KeyOf'
  in "<unicode string>", line 92, column 15:
          target: !KeyOf flow
                  ^
```

- [Enrollment (2 Stage)](https://github.com/goauthentik/authentik/blob/cadb710c38e21af420b727833a8702d21b1a9994/blueprints/example/flows-enrollment-2-stage.yaml#L104), line104
- [Enrollment with email verification](https://github.com/goauthentik/authentik/blob/cadb710c38e21af420b727833a8702d21b1a9994/blueprints/example/flows-enrollment-email-verification.yaml#L122), line 122
- [Recovery with email verification](https://github.com/goauthentik/authentik/blob/cadb710c38e21af420b727833a8702d21b1a9994/blueprints/example/flows-recovery-email-verification.yaml#L92), line 92

These others example flows are ok:

- Two-factor Login
- Login with conditional Captcha
- User deletion

**To Reproduce**

1. Try to import an example flow
2. Get error 405
3. Try to parse the YAML code

**Expected behavior**

The flow can be imported succesfully

**Screenshots**

Not relevant

**Logs**

Not relevant

**Version and Deployment (please complete the following information):**

 - authentik version: 2023.1
 - Deployment: podman

**Comment by AlphaJack** [comment]
I'm also seeing the same problem with certain blueprints:

Not OK:

- flow-default-source-enrollment
- flow-default-user-settings-flow
- flow-oobe
- flow-password-change

OK:

- flow-default-authentication-flow
- flow-default-authenticator-static-setup
- flow-default-authenticator-totp-setup
- flow-default-authenticator-webauthn-setup
- flow-default-invalidation-flow
- flow-default-provider-authorization-explicit-consent
- flow-default-provider-authorization-implicit-consent
- flow-default-source-authentication
- flow-default-source-pre-authentication

**Comment by BeryJu** [comment]
The 405 is caused by this https://github.com/goauthentik/authentik/issues/4588

The error you're seeing on that online YAML parser is a custom authentik tag, see https://goauthentik.io/developer-docs/blueprints/v1/tags

Also when importing example blueprints, make sure to get them from the correct version subdomain, so https://version-2023-1.goauthentik.io/
