### ISSUE TITLE
BUG: Webauthn and Clipboard Errors due to HTTP instead of HTTPS

### ISSUE THREAD

**Issue by ReaHe** [goauthentik/authentik#4614]
**Describe the bug**
Firefox and Brave (also possibly other browsers) remove certain javascript API capabilities (such as objects in navigator) based on whether the user connects with HTTPS or HTTP. When playing with Authentik to learn more about it, I found that when a user uses HTTP against the server and tries to use certain functionality such as the Clipboard or Webauthn it ends up erroring as if its broken with the errors "Error: Error creating credential: TypeError: navigator.credentials is undefined" for Webauthn via firefox and "navigator.clipboard is undefined" for the clipboard on firefox. Brave also had these errors but described them differently but fundamentally was fixed simply by being HTTPS. However this functionality is not broken its just restricted and Authentik just doesnt acknowledge this.

**To Reproduce**
Steps to reproduce the behavior for Webauthn:
1. Log into Authentik vi a HTTP connection
2. Attempt to make a Webauthn token
3. Receive Error

Steps to reproduce the behavior for Clipboard:
1. Log into Authentik vi a HTTP connection
2. Generate a app passwd
3. Attempt to copy the password
4. Receive error on the top right

**Expected behavior**
The user be notified that a HTTPS connection is required to do these actions and dont even attempt them with HTTP.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: docker-compose

**Additional context**
No logs or screenshots were provided as this seems be a contextual issues based on the browser and how the user connects.

**Comment by BeryJu** [comment]
fixed by https://github.com/goauthentik/authentik/pull/4917
