### ISSUE TITLE
Bad user policy may cause Generic webhook infinite loop

### ISSUE THREAD

**Issue by matutter** [goauthentik/authentik#4623]
**Describe the bug**

When a generic webhook is configured with a URL that is unreachable, or otherwise causes an exception (like mentioned in #4589), `system_exception` and `system_task_exception` events are created in an infinite loop.  Restarting the server (database, workers, and server) does not clear this loop.

If the webserver comes online at some point the initial webhook and all subsequent exception events get sent.

**To Reproduce**

**1.** Configure a Notification Transport, the WebHook URL must be unreachable. In this case I've pointed the URL at a server that is stopped (e.g. is not running or listening on port 8000).

![notification_transport](https://user-images.githubusercontent.com/2701379/216971526-6df9cb0d-8807-4d6d-8f0c-21a566da6c37.png)

**2. (OPTIONAL)** Configure a Notification Rule as shown.

![notification_rule](https://user-images.githubusercontent.com/2701379/216971795-1beadc57-6009-48b4-8ef4-c8b9f2c8604f.png)

**3. (OPTIONAL)** Add a Notification Policy as shown.

![notification_policy](https://user-images.githubusercontent.com/2701379/216972035-70951634-6c02-4fa1-937f-6e9146fcf542.png)

**4.** Test the Notification Transport

![click_test](https://user-images.githubusercontent.com/2701379/216972787-39146ffd-d185-42bc-b2e7-b3a1f8b5f60b.gif)

**5.** View event logs.

![event_log_1](https://user-images.githubusercontent.com/2701379/216973246-725f141c-8847-4e0d-9106-8d38c8f70a40.png)

**Expected behavior**

When a webhook fails to send I would expect one of a few behaviors.

1. A single event to be logged locally to capture the failed webhook.
2. A timeout of some flavor to slow down consecutive retries of the webhook. Either a "backoff" that grows increasingly longer or a constant "5 minute" delay in consecutive retries.
3. An option or checkbox to disable retry attempts.
4. Since I am aware the custom policy is somewhat responsible for the infinite loop, an easier way to determine when an event is an exception would be reasonable to have. Right now I can't seem to figure out how to filter-out exception events but that is a separate problem.

**Screenshots**

Screenshots above.

**Logs**

Two examples of log messages that are repeated forever.

```json
{
  "action": "system_task_exception",
  "client_ip": null,
  "context": {
    "message": "Task notification_transport encountered an error: Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/trace.py\", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/trace.py\", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py\", line 34, in run\n    return task._orig_run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/events/tasks.py\", line 126, in notification_transport\n    transport.send(notification)\n  File \"/authentik/events/models.py\", line 324, in send\n    return self.send_webhook(notification)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/events/models.py\", line 365, in send_webhook\n    raise NotificationTransportError(exc.response.text) from exc\n                                     ^^^^^^^^^^^^^^^^^\nbuiltins.AttributeError: 'NoneType' object has no attribute 'text'"
  },
  "event": "Created Event",
  "level": "info",
  "logger": "authentik.events.models",
  "pid": 96992,
  "task_id": "task-9dc157a05aaf4323a6ccfdb063a5d4e6",
  "timestamp": "2023-02-06T12:18:35.879450",
  "user": {}
}```



```json
{
  "action": "system_exception",
  "client_ip": null,
  "context": {
    "message": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/trace.py\", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/trace.py\", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py\", line 34, in run\n    return task._orig_run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/events/tasks.py\", line 126, in notification_transport\n    transport.send(notification)\n  File \"/authentik/events/models.py\", line 324, in send\n    return self.send_webhook(notification)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/authentik/events/models.py\", line 365, in send_webhook\n    raise NotificationTransportError(exc.response.text) from exc\n                                     ^^^^^^^^^^^^^^^^^\nbuiltins.AttributeError: 'NoneType' object has no attribute 'text'"
  },
  "event": "Created Event",
  "level": "info",
  "logger": "authentik.events.models",
  "pid": 96992,
  "timestamp": "2023-02-06T12:18:35.884808",
  "user": {}
}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: docker-compose & helm. I encountered this issue in a production instance and recreated it on a local docker-compose test.

**Additional context**

I'm somewhat aware the custom policy is actually causing the infinite loop.

```python
if "event" not in request.context:
    return False
return True
```

Because if I just `return False` the exception events stop being created. However I don't see any graceful way to resolve this with policy logic since policies are evaluated before sending to the transport.

**Comment by BeryJu** [comment]
As you've already found, #4589 fixes the main issue behind this.

For the loop part, authentik already tries to detect loops in event notifications, see https://github.com/goauthentik/authentik/blob/main/authentik/events/tasks.py#L49, however this only applies to errors that happen within events caused by policies

This issue is somewhat bound to happen when you have execution logging enabled, as this will create an event for each policy execution, which then triggers a notification, which fails, which triggers the policy for a new event, etc, etc

**Comment by matutter** [comment]
Thanks for the quick reply.

I disabled Execution Logging and added this to my policy to stop the exceptions from attempting to send over the transport.

```python
if event := request.context.get("event"):
  if event.action in {"system_exception", "system_task_exception"}:
    return False
  return True
return False
```
