### ISSUE TITLE
BUG: HTTPS session causes login loop when using HTTP connection there-after

### ISSUE THREAD

**Issue by ReaHe** [goauthentik/authentik#4625]
**Describe the bug**
When logging into Authentik via HTTPS or even migrating from HTTP to HTTPS after logging in via HTTP first, this causes an inability to thereafter use HTTP with Authentik with said browser (Was using Brave when I found this, firefox also showed this issue). If a user tries to use HTTP, it will cause a infinite loop of requesting your identity and after clicking "Log in" it will never move forward in the flow and force you to sit at the identity prompt until to move back to HTTPS via the url again.

This behaviour seems to be connected to the cookies of the browser as clearing my browser data, fixed HTTP connections until I moved back to HTTPS again which disabled it thereafter to downgrade for the login and would cause the infinite login loop again.

**To Reproduce**
1. Connect to Authentik via HTTPS and login via said HTTPS link
2. Change your URL to the HTTP connection to connect to Authentik in your browser by changing the URL to lead with http://
3. Get put back to a login screen and attempt to enter creds
4. Click "Log in"
5. Flow never moves forward and you're stuck at the login prompt

**Expected behavior**
Allow the individual to either correctly login or dissalow the user to downgrade the protocol and warn the user they must use HTTPS as they did when they originally logged in.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: docker-compose

**Additional context**
This is a low-risk bug in my opinion and will most likely be caused by a misconfiguration. I only found it since I was playing around with the program. However this did cause a serious issue when I originally setup SAML for testing which I set it too go to the HTTP address while initially logging into HTTPS. This caused a DOS on users disabling their ability to access the app. Hypothetically this bug is a good thing as it forces the user to stick to SSL if initially done. But the user just doesnt know why HTTP is broken after the fact from this issue.

**Comment by nanospearing** [comment]
Im having this exact issue, and I have no idea how to fix it T_T

**Comment by wookiesh** [comment]
shoudn't this be reopened as it still an issue with 2025.2.2 ?

**Comment by melizeche** [comment]
I don't think this is a bug, this is a protection against protocol downgrade attacks so it shouldn't be allowed, neither you should use an authentication provider on plain HTTP
but if for some reason this happens on your local tests you can delete your browser cookies and should allow you to log in again
