### ISSUE TITLE
Non-docker app config results in "no app for hostname"

### ISSUE THREAD

**Issue by fluc-tus** [goauthentik/authentik#4626]
**Describe your question/**
I have successfully set up authentik to secure my docker apps on unraid, that is working very well. What I wanted to achieve now is to expose my unraid dashboard too. That fails with this message:

`{
	"Message": "no app for hostname",
	"Host": "hal.pasmater.de",
	"Detail": "Check the outpost settings and make sure 'hal.pasmater.de' is included."
}`

**Relevant infos**
I have this setup:
![image](https://user-images.githubusercontent.com/61095687/217121037-584a7d7c-f1ba-4702-beaa-c12993d62d67.png)
![image](https://user-images.githubusercontent.com/61095687/217121113-6e202a01-03d5-4ff6-a995-96cdc06335c9.png)
![image](https://user-images.githubusercontent.com/61095687/217121447-7df0ca83-f6c6-485b-820e-2c1f2ae14967.png)
Traefix is my reverse proxy, when authentik is disabled it works, the config is basicly copied from authentik/ibracorp/etc. pretty basic.

**Additional context**
Apperantly the error message is wrong because there is an app configured. Any idea what might be causeing the issue?

**Comment by fluc-tus** [comment]
After a reinstall it worked again. No idea what broke authentik.

**Comment by igor47** [comment]
since this comes up in a search about the issue, the resolution might be in https://github.com/goauthentik/authentik/issues/3745#issuecomment-1751560188
