### ISSUE TITLE
Following invite link on logged-in session leads to user overwrite

### ISSUE THREAD

**Issue by dcabecinhas** [goauthentik/authentik#4631]
**Describe the bug**
If invited person B follows an invite and registers in a computer that is currently logged in with user A then registration data of user A is overwritten with new data from B. This essentially means user A disappears from the system and user B will have all the history and properties of user A.

The username and email will be from user B but attributes such as ID# will remain the same (from user A).

**To Reproduce**
1. Have a registered user
2. Create an invite link
3. Open invite and register in a browser where user is currently logged in
4. See error – the current user account disappears and new user will have attributes from original user.

**Expected behavior**
A new user should be created without affecting the logged in user.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: docker-compose

**Comment by sevmonster** [comment]
This can be rectified through proper flow configuration. Easiest I believe would be to configure the flow to require the user not be logged in. In case that doesn't work (I am not sure if that is checked when a FlowToken is used to restore the session via invite link) you could always use a policy to not proceed if the user is already logged in.

Does this happen with the default invitation flow?

**Comment by dcabecinhas** [comment]
I believe it is a plain vanilla default-enrollment-flow. If anything I downloaded some flows from Authentik's website, I don't recall hand-tuning them. 

Your suggestion seems simple enough but I don't have time to follow-up, I just wanted to alert the community, and also the developers, in case this happened to anyone else.

**Comment by cmcooper1980** [comment]
I came across this issue as well... Not knowing I was working/testing out of two incognito windows (so same session). I overwrote myself, however, thanks to this issue posted and @sevmonster 's suggestion it was an easy enough fix to include a logout stage early on in the flow to ensure a fresh session.
:thumbsup::smiley:

**Comment by sevmonster** [comment]
I didn't even think of that. When I think "logout" I think "end of flow", that's a smart use of it.
