### ISSUE TITLE
Authentik cluster

### ISSUE THREAD

**Issue by Skurat** [goauthentik/authentik#4661]
**Describe your question/**
Hi. 
1) How does an authentik cluster work? I have a problem deploying to kubernetes via helm. 
2) Can an authentik cluster run in separate kubernetes?

**Version and Deployment (please complete the following information):**
 - authentik 2022.10.0
 - authentik remote cluster 1.0.3
 - helm 3.10.1
 - terraform v1.3.4
**Additional context**
I used this manual
<img width="798" alt="image" src="https://user-images.githubusercontent.com/24324543/218053886-da331564-bdac-4df7-bb0d-c392d3d7fa12.png">
and insert output from this command (below) to terraform resource "authentik_service_connection_kubernetes" "remote-test-cluster"
<img width="722" alt="image" src="https://user-images.githubusercontent.com/24324543/218054234-df020dd1-d325-4f7e-9e51-2e7b747a0e2f.png">
I deployed separate helm 
chart = "authentik-remote-cluster"
chart_version = "1.0.3"
But how to test cluster work ?
P.S.
Thanks for the help

**Comment by BeryJu** [comment]
the authentik-remote-cluster helm chart is used to deploy outposts in different k8s clusters where authentik doesn't run, and gives you the RBAC and outputs a kubeconfig file that can be used with authentik to connect to that k8s cluster

It doesn't have anything to do with clustering authentik itself. To do that, you'd use the normal helm chart and scale up the server or worker deployments. An authentik "cluster" can run in different kubernetes clusters, as long as all pods can connect to postgres and redis
