### ISSUE TITLE
Bug: Editing user attributes in frontend results in user losing all their groups

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#4685]
**Describe the bug**
Frontend seems to take forever to load the groups and as a result, it will push the attribute change without groups at all.

**To Reproduce**
1. Go to `/if/admin/#/identity/users/`
2. Pick a user that has groups
3. Change user attributes w/o changing groups
4. Press update
5. Notice that the groups are gone but the attribute change stays

**Expected behavior**
I would have expected it to retain groups or better yet, not touch groups at all if only attribute was touched.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2.0
 - Deployment: docker-compose

**Additional context**

The frontend seems to struggle really hard with more than 30 groups. It takes absolutely forever to show the groups instead of "loading" in the group section of the profile.

**Comment by BeryJu** [comment]
This is caused by the frontend loading all groups and filtering them client-side, causing the load times to be slower. As a workaround, for 2023.2.1, the groups field in the user form and the members field in the group form will be removed to prevent this from happening

**Comment by nwinkelstraeter** [comment]
> This is caused by the frontend loading all groups and filtering them client-side, causing the load times to be slower. As a workaround, for 2023.2.1, the groups field in the user form and the members field in the group form will be removed to prevent this from happening

Well, but now I cannot create users anymore because `groups` is a required field

**Comment by samip5** [comment]
not stale.

**Comment by BeryJu** [comment]
Since https://github.com/goauthentik/authentik/commit/fbd00bf5f8e7b370f6612e5cbbe44bcfe2e71e1f#diff-fccf15836f094fc1a7b30c213e22f804cabeb3ebbaabd3c3fc2c5cef2d42adfc the groups are no longer sent with the user update (and a patch instead of a put requests is sent), so this is fixed since 2023.2.1
