### ISSUE TITLE
After updating to 2023.2.0 proxy outpost provider fails with HTTP 400

### ISSUE THREAD

**Issue by cwildfoerster** [goauthentik/authentik#4688]
**Describe the bug**
After updating to 2023.2.0, the proxy outpost return HTTP 400, somehow the provider url schemes doesn't match anymore, but i don't know why and if there is a new setting for it. Internal host is connected with HTTP via an internal docker network. Maybe it has to do with https://github.com/goauthentik/authentik/pull/4675 ?

**To Reproduce**
1. Create a proxy provider and application and try to use it.

**Expected behavior**

**Logs**
`error":"oidc: id token issued by a different provider, expected \"https://auth.example.org/application/o/zigbee2mqtt/\" got \"http://auth.example.org/application/o/zigbee2mqtt/\"","event":"failed to redeem code","level":"warning","logger":"authentik.outpost.proxyv2.application","name":"zigbee2mqtt","timestamp":"2023-02-14T15:40:14Z`

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2.0
 - Deployment: default docker-compose

**Comment by romancin** [comment]
Same problem here, auto updated by Flux and had to restore previous version.

**Comment by BeryJu** [comment]
This is fixed by https://github.com/goauthentik/authentik/commit/58e001c3d5165ee5eed935e4398134eafcf6b7a9, 2023.2.1 will be out shortly

**Comment by cwildfoerster** [comment]
thank you @BeryJu ❤️

**Comment by weikinhuang** [comment]
I'm still seeing this in 2023.2.1
