### ISSUE TITLE
Error 400 after logging in using a proxy outpost: "error":"securecookie: the value is too long"

### ISSUE THREAD

**Issue by romancin** [goauthentik/authentik#4693]
**Describe the bug**
After updating to 2023.2.1, cannot reach the application using a proxy provider. It gives an HTTP ERROR 400 when trying to redirect to the application after logging in.
The problem occurs even in a new Incognito window.

**To Reproduce**
1. Write the application URL
2. Login in Authentik
3. Error 400 after logging in

**Expected behavior**
Login should work.

**Screenshots**
N/A

**Logs**
{"event":"/outpost.goauthentik.io/auth/traefik","host":"sonarr.apps.mydomain.info","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"sonarr.apps.mydomain.info","remote":"10.42.3.134:50130","runtime":"0.357","scheme":"http","size":387,"status":302,"timestamp":"2023-02-15T07:07:43Z","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}
{"error":"securecookie: the value is too long","event":"failed to save session","level":"warning","logger":"authentik.outpost.proxyv2.application","name":"sonarr.apps.mydomain.info","timestamp":"2023-02-15T07:07:43Z"}
{"event":"/outpost.goauthentik.io/auth/traefik","host":"sonarr.apps.mydomain.info","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"sonarr.apps.mydomain.info","remote":"10.42.3.134:50130","runtime":"116.794","scheme":"http","size":0,"status":400,"timestamp":"2023-02-15T07:07:43Z","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2.1
 - Deployment: helm

**Additional context**
Restoring backup to go back to 2023.1.2 makes it work again.

**Comment by romancin** [comment]
That was really fast! Thank you! Are you going to create a new release including it soon?

**Comment by BeryJu** [comment]
For now you can use the beta https://goauthentik.io/docs/installation/beta since there's only bugfixes in that compared to the released versions, but yeah a new release will probably be out soon, I'm waiting a bit to see if any other issues come up
