### ISSUE TITLE
404 Not Found on Forward Auth

### ISSUE THREAD

**Issue by EmilZackrisson** [goauthentik/authentik#4698]
**Describe the bug**
After the 2023.02.1 update my forward auth with Traefik doesn´t work, getting "404 Not Found nginx" Same issue on multiple apps. Get the same error when visiting https://auth.domain.se/outpost.goauthentik.io/auth/traefik. Other apps using the inbuilt proxy setting work.

**To Reproduce**
Not sure.

**Expected behavior**
Getting to the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/51415707/219101594-3f397695-7e08-4c55-bc29-4fdac87c38bc.png)

**Logs**
Nothing that stands out in the logs, either Authentik server/worker or Traefik.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.02.1
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
I'm not sure why you're getting an nginx 404 page, if you're using traefik, since authentik doesn't bundle any kind of nginx

**Comment by EmilZackrisson** [comment]
> I'm not sure why you're getting an nginx 404 page, if you're using traefik, since authentik doesn't bundle any kind of nginx
> 
> 

Hmm, I don't have any nginx proxy. I will keep looking then.

**Comment by EmilZackrisson** [comment]
I can access the page if I remove the Authentik middleware in the Traefik config file. The middleware config I use is copied from the provider in Authentik.

**Comment by EmilZackrisson** [comment]
Solved it. I had another rule with the same path in the Traefik config that pointed to my kubernetes ingress that is nginx.
