### ISSUE TITLE
Apply single blueprint System Task Fails

### ISSUE THREAD

**Issue by ddavtian** [goauthentik/authentik#4702]
Started seeing this fail in the UI

 - authentik version: 2023.2.2
 - Deployment: helm

<img width="1125" alt="Screenshot 2023-02-15 at 7 41 37 PM" src="https://user-images.githubusercontent.com/1940369/219264412-1b555a0b-f5bd-4afa-a18c-21c8f1fdb4ec.png">

```
│ authentik-worker-cf9f84bcf-86vk2 authentik {"entry": "BlueprintEntry(model='authentik_tenants.tenant', state=<BlueprintEntryDesiredState.CREATED: 'crea │
│ ted'>, conditions=[], identifiers={'domain': 'authentik-default', 'default': True}, attrs={'flow_authentication': <authentik.blueprints.v1.common.Find  │
│ object at 0x7fcb05d82ed0>, 'flow_invalidation': <authentik.blueprints.v1.common.Find object at 0x7fcb05d81f10>, 'flow_user_settings': <authentik.bluepr │
│ ints.v1.common.Find object at 0x7fcb05d83490>}, id=None, _state=BlueprintEntryState(instance=None))", "error": "EntryInvalidError(\"Serializer errors { │
│ 'non_field_errors': [ErrorDetail(string='Only a single Tenant can be set as default.', code='invalid')]}\")", "event": "entry invalid: Serializer error │
│ s {'non_field_errors': [ErrorDetail(string='Only a single Tenant can be set as default.', code='invalid')]}", "level": "warning", "log_level": "warning │
│ ", "logger": "authentik.blueprints.v1.importer", "pid": 139, "task_id": "task-e71197dd8d464b98b9e68728bf926a16", "timestamp": "2023-02-16T03:58:48.9095 │
│ 43"}
```

**Comment by ddavtian** [comment]
After creating a default tenant, seems like the issue has gone away, closing it.

![image](https://user-images.githubusercontent.com/1940369/219495012-51953d10-71e0-4728-af9c-2d675cc79991.png)

**Comment by brujoand** [comment]
I've been having this exact same problem, but in my system there was apparently already a default tenant created. I tried creating a new tenant as described above, setting that one as default instead of the old. But I'm still seeing the error `'Only a single Tenant can be set as default.'`. Did you have 0 tenants listed when this error occured @ddavtian ?

**Comment by ddavtian** [comment]
I already had an existing default tenant which I had made changes to prior. I set that as none default and the system auto generated another one for me and set that as default. From that point forward waiting a bit of time the error was not present anymore.

**Comment by brujoand** [comment]
That did the trick, thanks 👍
