### ISSUE TITLE
[Feature Request] User apps and providers.

### ISSUE THREAD

**Issue by minecraftchest1** [goauthentik/authentik#4708]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have a way to allow users to create their own Apps and Providers, possibly using policies or groups to control who grant or block access to certian users.

**Describe alternatives you've considered**
Creating a flow that allows users to create their own apps and providers, using policies for access control. However, this does not seem possible.

Creating a seperate webapp to provide this functionality. This does seem like it would invite security holes however.

**Additional context**
Both Github and Gitlab (possibly others) provide this functionality. However, these do not fit my usecase. My goal is to fufill the requirements of a somewhat theoretical usecase I have in mind.

**Comment by BeryJu** [comment]
This can be done using RBAC: https://docs.goauthentik.io/docs/user-group-role/roles/
