### ISSUE TITLE
LDAP User Sync

### ISSUE THREAD

**Issue by Profecy** [goauthentik/authentik#4712]
**Describe your question/**
Hi! I've been enjoying Authentik thus far quite a lot.
However, I find myself wondering, how often will authentik sync against the LDAP Directory?
Say for instance I create a new user, add a user to a group, etc, how long will it take to sync to authentik and can I configure the interval ?
All I could find in the docs is that "groups are synced in the background every 5 minutes".

**Relevant infos**
LDAP is ActiveDirectory

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: Docker compose setup

**Additional context**

**Comment by boesr** [comment]
I am also interested in the answer. I just monitored the system for 30 minutes. Since that time there was no sync between the LDAP Directory and Authentik thus some group assignments are missing. Would be nice to be able to configure that.

**Comment by BeryJu** [comment]
Currently the sync is run every 2 hours at a random-ish minute, but you can re-run a sync by sending a PATCH request here: https://goauthentik.io/developer-docs/api/browser#patch-/sources/ldap/-slug-/

**Comment by boesr** [comment]
Thanks for the answer. That does work. Would be nice to be able to configure the sync period, but this can be achieved by a script.

**Comment by Profecy** [comment]
Thank you very much for the information, however there should be a config option for this, ideally when configuring the LDAP connection.
