### ISSUE TITLE
Issues when logging in via Chrome on Android: Policy exception

### ISSUE THREAD

**Issue by t-aus-m** [goauthentik/authentik#4714]
**Describe the bug**
On our Authentik instance an user has reported issues when trying to log into a service via SSO through authentik. We were able to reproduce the behaviour on Chrome on Android (the plattform that the user was on) with every other combination of OS and browser seemingly unaffected. While the user reported having the issue on Chrome on PC (OS unknown to us) as well, we could not reproduse that.

**To Reproduce**
1. Take an Android phone with Chrome installed on it
2. Log into a service through SSO or into Authentik directly
3. UI shows Error `Failed to authenticate`

**Expected behavior**
The user should be able to login regardless of the OS or browser used 

**Screenshots**
![authentik-log](https://user-images.githubusercontent.com/12219297/219851955-025a8869-46d6-4622-bace-e9b63f24591e.png)
![Screenshot_20230217-175908](https://user-images.githubusercontent.com/12219297/219851961-8646ed81-a3a6-4b71-a317-de12900abe21.png)

**Logs**
From admin UI:
```
{
    "geo": {
        "lat": "redacted",
        "city": "redacted",
        "long": "redacted",
        "country": "redacted",
        "continent": "redacted"
    },
    "binding": {
        "pk": "60583b23681049c7a6f631178cd13aec",
        "app": "authentik_policies",
        "name": "Binding from Flow-stage binding #30 to 9d54a392-6d07-4a5d-b658-0e494e9bc975 #0 to Policy test-not-app-password",
        "model_name": "policybinding"
    },
    "message": "Traceback (most recent call last):\n  File \"test-not-app-password\", line 3, in <module>\n  File \"test-not-app-password\", line 2, in handler\nbuiltins.KeyError: 'auth_method'",
    "request": {
        "obj": {
            "pk": "aa7c1d60bf864717ad9670494b9fa086",
            "app": "authentik_flows",
            "name": "Flow-stage binding #30 to 9d54a392-6d07-4a5d-b658-0e494e9bc975",
            "model_name": "flowstagebinding"
        },
        "user": {
            "pk": 2,
            "email": "",
            "username": "AnonymousUser"
        },
        "debug": false,
        "context": {
            "geoip": {
                "lat": "redacted",
                "city": "redacted",
                "long": "redacted",
                "country": "redacted",
                "continent": "redacted"
            },
            "flow_plan": {
                "context": {},
                "flow_pk": "9d54a3926d074a5db6580e494e9bc975",
                "markers": [],
                "bindings": [
                    {
                        "pk": "1308a2d95a064781a7d958e6701c4257",
                        "app": "authentik_flows",
                        "name": "Flow-stage binding #10 to 9d54a392-6d07-4a5d-b658-0e494e9bc975",
                        "model_name": "flowstagebinding"
                    }
                ]
            }
        },
        "http_request": null
    },
    "policy_uuid": "8bab323fe5b649c7a8a52c167e7c6676",
    "http_request": {
        "args": {
            "query": "redacted"
        },
        "path": "/api/v3/flows/executor/default-authentication-flow/",
        "method": "GET"
    }
}
User
{
    "pk": 2,
    "email": "",
    "username": "AnonymousUser"
}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Can you post the expression of the `test-not-app-password` policy?

**Comment by t-aus-m** [comment]
Sure thing:
`return context["auth_method"] != "app_password"`

**Comment by Azerioxal** [comment]
I have the same policy failing repeatedly and sending notifications. But I don't experience any login issues.

**Comment by BeryJu** [comment]
Depending on what the policy is bound to, `auth_method` might not be set; you can use `context.get("auth_method")`, but also make sure to bind the policy with the re-evaluate flag set in the stage binding

**Comment by t-aus-m** [comment]
Unfortunately, that does not solve the problem. The error (on the admin side) just changed:
![New Error](https://user-images.githubusercontent.com/12219297/220195036-ccddb915-7164-41c8-bf1c-83b1963e8eb6.png)

What I did:
1. Change the re-evaluate flag to true  for `default-authentication-identification`
2. Change the expression of the `test-not-app-password` policy to be `return context.get("auth_method") != "app_password"`

I am running another Authentik instance (same version) that does not have this policy at all. Where does it come from?

**Comment by Azerioxal** [comment]
My flow looks the same. I also don't know where the policy came from.

**Comment by nhhandevops** [comment]
how can your context have geoip data? What do we need to enable or do some configuration in order to get that?
