### ISSUE TITLE
CSRF Errors in admin console after install using helm chart

### ISSUE THREAD

**Issue by JohnnyRacket** [goauthentik/authentik#4719]
**Describe your question/**
I just recently set up Authentik on my k8s cluster using the helm chart, all pods are healthy, and I was able to log in and create an administrative user. However, one in the admin console, I saw my outpost had this error:

![image](https://user-images.githubusercontent.com/6663338/219982189-77cd01c1-5db4-4ba7-9ded-b6b2f89c00e5.png)

When I got to try to set the authentik domain in the outpost settings I get:
![image](https://user-images.githubusercontent.com/6663338/219982282-df10b6e7-655f-4abf-b3df-fc0671e504ff.png)

if this is relevant, when I look at system tasks I see this task also failed:
![image](https://user-images.githubusercontent.com/6663338/219982323-0171ca90-f797-40ba-a374-0ceaef7cd2bb.png)

When I retry I get a 403, so it is presumably the same CSRF issue. I am just not sure why I am getting a CSRF, my origin is hostname I provided the helm chart value of `ingress.hosts.host` 

**Relevant infos**
- Latest Helm chart
- k8s (k3s default setup specifically)
- domain is using cloudflare nameservers and proxied

**Screenshots**

**Logs**
I saw another ticket where someone used docker to check their worker config, I used `kubectl describe` but saw no mention of `csrf_trusted_origins`

**Version and Deployment (please complete the following information):**
 - authentik version: latest
 - Deployment: helm

**Additional context**
Any tips or pointers in the right direction appreciated.

**Comment by BeryJu** [comment]
https://goauthentik.io/docs/troubleshooting/csrf

**Comment by JohnnyRacket** [comment]
Thank you for the quick reply: 

from `https://auth.******.tools/api/v3/admin/system/`: ( a ctrl+ f found 2 instances)
![image](https://user-images.githubusercontent.com/6663338/219983036-2390445e-4667-417b-9202-5e24b8f7771e.png)
![image](https://user-images.githubusercontent.com/6663338/219983080-28f1ac78-7160-4841-840c-2050b8e70e12.png)

from a network call:
![image](https://user-images.githubusercontent.com/6663338/219983207-a3ccc160-cd92-4b33-acaa-1efd9f437cac.png)


The domains match, is it the lack of `https://` prepending them?

I didnt put this in the `values.yml` because the example values were shaped as such:
```
ingress:
    enabled: true
    hosts:
        - host: authentik.domain.tld
 ```

**Comment by JohnnyRacket** [comment]
I now believe this to be an SSL issue on my end. I think the error message was perhaps misleading where I was looking. Not solved yet, but working on it

**Comment by JohnnyRacket** [comment]
It was an SSL error, basically it looks like that csrf error will throw if you dont have SSL between cloudflare and your k8s cluster. which is probably obvious to many people who know network, for me I had to search for a while to understand.

**Comment by lukeberry99** [comment]
@JohnnyRacket I'm having the same issue, can you explain how you resolved it?
