### ISSUE TITLE
goauthentik.io/user/token-expires has no effect

### ISSUE THREAD

**Issue by gi-yt** [goauthentik/authentik#4727]
**Describe the bug**
I tried to set the `goauthentik.io/user/token-expires: false` as an admin user's attribute, but it does not have any effect.
**To Reproduce**
1. Go to 'admin interface -> directory -> users -> user folders -> users -> edit any user'
2. Add 'attribute: `goauthentik.io/user/token-expires: false`'
3. Go to settings -> tokens and generate a new token
4. token details contains an expiry

**Expected behavior**
the attribute should disable token expiry 
**Screenshots**
![image](https://user-images.githubusercontent.com/73596856/220071665-9944290e-3ac0-454f-8931-3fde23c2af8b.png)
![image](https://user-images.githubusercontent.com/73596856/220071875-0dd1d9ad-437b-4be4-8bb5-7c1b4ffd7096.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2.2
 - Deployment: docker-compose

**Comment by Lanhild** [comment]
Same issue here on v.2023.2.2 upon creation of a service account

**Comment by sdimovv** [comment]
I believe those are more for metadata purposes but I might be wrong. 

In any case you can change the update the token attributes from `Directory > Tokens & App Passwords > Edit token`

**Comment by BeryJu** [comment]
the `goauthentik.io/user/token-expires` attribute only applies when the token is being created by the user that has the flag, and additionally it only applies to non-superusers
