### ISSUE TITLE
Reintegrate a backup functionality for flows and configurations.

### ISSUE THREAD

**Issue by Lanhild** [goauthentik/authentik#4734]
**Is your feature request related to a problem? Please describe.**
Generating automated backups of an authentik configuration

**Describe the solution you'd like**
Having a utility/UI to automatically backup or schedule backups of an authentik instance exclusively for configurations, not user data.

**Additional context**
Agreed, letting users make their database backups themselves is appropriate, but what should be reinstated in authentik is an automatic backup of configurations. It might be based on https://goauthentik.io/developer-docs/blueprints/export.

This is very useful to, e.g., keep versions of your configurations in a git repository, or importing back your configuration inside another instance/dev instance.

**Comment by sdimovv** [comment]
You can export instance configuration in the form of a blueprint:
https://goauthentik.io/developer-docs/blueprints/export#global-export

Maybe you can automate this with a cronjob?

**Comment by Lanhild** [comment]
Thanks, didn't think about this one. Shall I close the issue then?
