### ISSUE TITLE
Certificate Added with no Private Key is Unavailable in SAML Provider Verification KP

### ISSUE THREAD

**Issue by ReaHe** [goauthentik/authentik#4753]
**Describe your question/**
In configuring a SAML provider in Authentik, there is an option available that allows for setting for the verification_kp and signing_kp. However when selecting the verification_kp, you're unable to select a certificate key pair that only has a certificate and no private key associated with it. Considering I imagine the verification_kp is only needed to verifying the signature from the SP, this seems like a bug as a private key from my knowledge should not be needed to verify the SP signature for SAML.

I making this ticket:
1. to verify this is a bug and is not intended.
2. Once concluded I plan on making a feature or bug request if necessary depending on the answer.

**Relevant infos**
- Certificate key pairs are added via blueprints, one certificate was added by only including the certificate and not the private key

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.1.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
This is fixed in 2023.2, see https://github.com/goauthentik/authentik/commit/93e665949f8b08abd33984e73493f4ef58ce8433
