### ISSUE TITLE
user "akadmin" deleted on upgrade

### ISSUE THREAD

**Issue by funktionierbar** [goauthentik/authentik#4766]
**Describe the bug**
I did an update of my docker container from Version 2023.1.2 to 2023.2.2 with docker-compose,  I guess I was logged in during that time with my akadmin user. 
When I tried to login again after the update, the login process fails with "failed to authenticate", likewise with the password recovery flow. 
I tried the "initial-flow" again, but it fails with "Request has been denied.", 'NoneType' object has no attribute 'has_usable_password'
I then tried again in bash "docker-compose run --rm server create_recovery_key 10 akadmin", and it logs a lot of unsuspicious messages and fails with: "User 'akadmin' not found."
Then I tried "docker-compose run --rm server createsuperuser" and it asks me to provide username, mail, password, password repeat, and then fails with the following error:

`Username: akadmin    `
`Email address: mail@mail.com`
`Password: `
`Password (again): `
`{"event": "sending event to sentry", "exc": "AttributeError(\"property 'is_staff' of 'User' object has no setter\")", "level": "debug", `"logger": "authentik.lib.sentry", "pid": 6, "source_logger": null, "timestamp": "2023-02-23T12:47:16.276373"}`
`Traceback** (most recent call last):`
`  File "<frozen runpy>", line 198, in _run_module_as_main`
`  File "<frozen runpy>", line 88, in _run_code`
`  File "/manage.py", line 31, in <module>`
`    execute_from_command_line(sys.argv)`
`  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line`
`    utility.execute()`
 ` File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
 `   self.fetch_command(subcommand).run_from_argv(self.argv)`
 ` File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
`    self.execute(*args, **cmd_options)`
`  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute`
`    return super().execute(*args, **options)`
`           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute`
`    output = self.handle(*args, **options)`
`             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 233, in `handle`
`    self.UserModel._default_manager.db_manager(database).create_superuser(`
`  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/models.py", line 172, in create_superuser`
`    return self._create_user(username, email, password, **extra_fields)`
`           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/models.py", line 153, in _create_user`
`    user = self.model(username=username, email=email, **extra_fields)`
`           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 554, in __init__`
`    _setattr(self, prop, value)`
`AttributeError: property 'is_staff' of 'User' object has no setter`
`ERROR: 1`

All other users seem to still be there, I can list them all from my local machine with ldapsearch.
Could you help me gain access to my authentik again?

**Comment by BeryJu** [comment]
```
ak shell
```
then

```
User.objects.create(username="akadmin")
```

then you can follow https://goauthentik.io/docs/troubleshooting/missing_admin_group to make that user admin and the recovery key command above to login as that user

**Comment by funktionierbar** [comment]
Thank you so much! It worked
