### ISSUE TITLE
Ability to customize LDAP attributes via property mappings

### ISSUE THREAD

**Issue by sdimovv** [goauthentik/authentik#4770]
**Is your feature request related to a problem? Please describe.**
Currently the LDAP provider (and outpost) are not capable of returning arbitrary property mappings like other providers can (for example SAML).

**Describe the solution you'd like**
I want to be able to assign property mappings to LDAP providers. Those properties should then be returned as attribute records from the LDAP outpost.

**Describe alternatives you've considered**
Not aware of any

**Additional context**
N/A

**Comment by zphd** [comment]
you can use custom user attributes as an alternative, you get them all in a LDAP response. but be aware it's buggy at the moment in 2023.3.0 as it returns them multiple times, see my recent bugreport: https://github.com/goauthentik/authentik/issues/4971

**Comment by sdimovv** [comment]
> you can use custom user attributes as an alternative, you get them all in a LDAP response. but be aware it's buggy at the moment in 2023.3.0 as it returns them multiple times, see my recent bugreport: #4971

Hi,
Yes I am aware LDAP provides access to user/group/tenant attributes, however that is not what I need. I need to be able to assign property mappings that return values based on some computation and/or DB lookup. Similar to how property mappings work for other providers.

In my opinion the current LDAP implementation is a hack. Instead of always providing all of those object classes it needs to be configurable via property mappings and the the current values should be exported as default LDAP property mappings.

**Comment by zphd** [comment]
in my opinion LDAP is an oldschool solution for authentication and should be used only if there's no better option like SAML or OAuth. so I'm really thankful to Authentik I don't have to deal with a "real" LDAP server for authenticating my users, this "hack" is way more comfortable for my use cases. if you need a full LDAP implementation you still can use an external LDAP source.

**Comment by mentos1386** [comment]
+1 for this future. I assumed this was already implemented as you can define property mappings for ldap already, but the on thing missing for me is to be able to access `request.user.attributes` inside this property mappings.

How come the `request.user.attributes` is not already available for ldap property mappings?

**Comment by BeryJu** [comment]
For the foreseeable future this will not be possible due to how the LDAP server interacts with the API to fetch the data needed.
