### ISSUE TITLE
Certificate dropdown partly hidden

### ISSUE THREAD

**Issue by lkiesow** [goauthentik/authentik#4814]
Going to the certificate selection for the tenant which is at the bottom of the page and opening the dropdown menu, the menu will partly exceed the limit of the page with no option for me to scroll down and see more than the first two items of the dropdown.

**To Reproduce**

0. Make sure you have more than two certificates in your authentik
1. Go to Admin Interface → System → Tenants
2. Edit a tenant
3. Expand “Other global settings” and scroll all the way down
4. Open the “Web Certificate” dropdown
5. You will only see the first entries with the later ones hidden behind the end of the dite

**Expected behavior**

The drop-down should either open to the top if there is insufficient space, or make the page scrollable, or make the dropdown scrollable.

**Screenshots**

![Screenshot from 2023-02-27 19-41-34](https://user-images.githubusercontent.com/1008395/221927350-3bb1b658-868e-423d-bb37-9ff093817c19.png)

**Version and Deployment**

 - authentik version: 2023.2.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
The dropdown does actually scroll, however it only does if the elements dont fit within it's size. The commit above is not the full fix to make it open upwards if required, but a workaround to move the certificate field higher in the form

**Comment by kensternberg-authentik** [comment]
![image](https://github.com/goauthentik/authentik/assets/133134217/58213fb8-8f46-4fa0-8677-4f1593dbb50c)

I tried to repo this bug and was unable to.  Scrolling is enabled on the form, and with all the additional fields beneath the certificate drop-down it appears to work without needing intervention.

**Comment by BeryJu** [comment]
the certificate field was moved up as it used to be rendered below the attributes field, the main way to reproduce this is to resize the viewport to be quite small @kensternberg-authentik

**Comment by kensternberg-authentik** [comment]
Ah.  PR #9517 has a fix; I used [floating](https://floating-ui.com/) and it will put the pop-up wherever there's the most room, as in here where I crowd the certificate dropdown from below with the _Inspect_ window.

![image](https://github.com/goauthentik/authentik/assets/133134217/37a8f1a2-1309-41b9-95cb-64c139693c98)
