### ISSUE TITLE
LDAP provider bind flow selection not recognized

### ISSUE THREAD

**Issue by lkiesow** [goauthentik/authentik#4815]
Creating or editing an LDAP provider, the selection for “Bind flow” is not recognized when you submit the form and authentik will complain that the field is required. It will work if you submit the form again.

**To Reproduce**

0. Make sure you have an LDAP provider (the issue might already pop up when you create one but I'm not entirely sure and haven't tried reproducing this yet)
1. Go to Admin Interface →Applications → Providers
2. Edit your LDAP provider
3. Change nothing and click “Update”
4. Authentik will complain that “Bind flow” is not set, but it is
5. Change nothing, but click “Update” again. Now it will work

**Expected behavior**

The form should recognize that values are set if they are set.

**Screenshots**

![Screenshot from 2023-02-28 18-15-51](https://user-images.githubusercontent.com/1008395/221930948-5402bd4f-1b02-4dbd-968e-691ae746f465.png)

**Version and Deployment**

 - authentik version: 2023.2.2
 - Deployment: docker-compose

**Comment by ja2ui0** [comment]
Still an issue in 2023.3.1

**Comment by BeryJu** [comment]
This is fixed in 2023.4, which will be out soon

**Comment by ja2ui0** [comment]
Just looked at the release notes and this issue isn't listed under Minor changes/fixes. As it's not closed, I was wondering if it made it in?

**Comment by BeryJu** [comment]
The main PR that fixes this issues (and others like it) is https://github.com/goauthentik/authentik/pull/5049 which is in 2023.4
