### ISSUE TITLE
Application image upload sometimes not working

### ISSUE THREAD

**Issue by lkiesow** [goauthentik/authentik#4816]
Trying to clear and then set the image of a given application, authentik will just discard the new image.

**To Reproduce**

1. Go to Admin Interface → Application → 
2. Edit an application with an image and select “Clear Icon” (Screenshot 1)
3. Click “Update” and the icon is gone
4. Stay on the page, edit the same application again and set a new icon (Screenshot 2)
5. Click “Update”. There is no new icon. Not in the table, nor if you open the edit form again (Screenshot 3)
6. Reload the page (F5), try again and it works. I'm wondering if the “Clear Icon” is never reset but just hidden?

**Expected behavior**

Uploading an icon, the image should update the icon. The file should not just be discarded.

**Screenshots**

Screenshot 1: Clear icon
![Screenshot from 2023-02-28 18-29-45](https://user-images.githubusercontent.com/1008395/221932566-e800b1e3-4776-4db5-ba0c-d75106d6f1c7.png)

Screenshot 2: Upload new icon
![Screenshot from 2023-02-28 18-30-20](https://user-images.githubusercontent.com/1008395/221933123-5f8ddeda-5ebe-4a37-ac8e-e605aa4d460b.png)

Screenshot 3: No icon uploaded
![Screenshot from 2023-02-28 18-30-43](https://user-images.githubusercontent.com/1008395/221933622-6fe72977-44c6-4f07-939a-a907c8d5fc56.png)

**Version and Deployment**

 - authentik version: 2023.2.2
 - Deployment: docker-compose

**Comment by PKizzle** [comment]
Has this issue already been solved?
