### ISSUE TITLE
Global python functions/vars for expression policies

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#4842]
Add an option to globaly define some variables and functions to reuse python code in expression policys.
Currently i find myself having similar code and variables chaotically distributed in policies.

**Comment by sdimovv** [comment]
You can already achieve this... Well sort of.

1. Define your common functionality in an expression policy
2. Add each method/value to the context dict
3. Return `True` from the policy so it always passes

Now:
1. Attach the policy to the beginning of each flow
2. Use the custom method and variable definitions in other policies. 

Or if it is just variables (without custom code) you can define your them in as tennant or group attributes. 

Hope that helps

**Comment by benedikt-bartscher** [comment]
Hey @sdimovv, thanks for the detailed information. I will try Option 2 and report back with my results. Do you think this approach should become the recommended approach for authentik or is it worth to add a seperate Feature/Model for this? Both sides have their pros/cons.

Seperate Model:
+ could be made intuitive
+ (depending on the implementation) no additional config needed for policies using it
- more models/terminoligies to learn
- additional code+testing needed

"Helper" Expression Policys:
+ no additional code/abstraction/testing needed
- requires additional config in every policy which uses the helper
- not very intuitive

No matter which way is choosen, we should document how to share code/variables and present a recommended approach in the docs.

**Comment by BeryJu** [comment]
Ny recommendation would also be the 2nd option, basically using polices as functions and then calling them via `ak_call_policy()`, which will return whatever the policy called returns (it doesn't have to be boolean)

It would be a bit clunky to call `ak_call_policy()` multiple times as each call does a database lookup for the policy, so I think changing it to `ak_import_policy()` that returns a callable function would be cleaner `my_policy = ak_import_policy("foo"); my_policy("foo", "bar")`

**Comment by macmoritz** [comment]
Return does not work. Even in the PolicyResult object there is not field for the return value.
My current workaround is using the request context to passing data between policies.

**Comment by benedikt-bartscher** [comment]
I found another challange: Where to store secrets like API Tokens? From a security perspective it wouldn't be great to store them in the policy which is saved as plain-text in the DB. Maybe a K8 Secret + volume mount works, however i haven't tested it yet.

**Comment by macmoritz** [comment]
Would be nice to use method 2, so using `ak_call_policy` in placeholder (used as expression) in prompts. 
With the latest changes to prompts (#4822) we can create dynamic prompts.

**Comment by macmoritz** [comment]
Thanks @BeryJu
