### ISSUE TITLE
Publish PR docker images

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#4849]
Hey @BeryJu, i just wanted to test PR #4822 and checked the Github CI log which seems to build docker images tagges like this:
```
--tag ghcr.io/goauthentik/dev-server:gh-feat-new-prompt-fields --tag ghcr.io/goauthentik/dev-server:gh-feat-new-prompt-fields-1677868953-200c1f5
```
However these images are only build and tagged, not pushed to ghcr.io. Is there any specific reason for this? It would be awesome for testing.

**Comment by macmoritz** [comment]
Would be great to have those for rapid development.
