### ISSUE TITLE
Outpost is not able to select more than 100 Applications

### ISSUE THREAD

**Issue by zilvernet** [goauthentik/authentik#4880]
**Describe the bug**
The embedded outpost application select box is only able to list 100 items.

**To Reproduce**
once you edit the outpost the applications selector is lock to 100 ordered alphabetically.

![293CC595-88CE-4194-A76B-B3AFFC39630D](https://user-images.githubusercontent.com/75147745/223916334-63eb6192-fff5-4a43-9bb9-23fd440c05f1.png)

**Version and Deployment (please complete the following information):**
 - authentik version:  2023.2.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
This is the same for all multi-select boxes, the workaround for this currently is to use terraform, blueprints or the API directly

**Comment by zilvernet** [comment]
Thanks for the feedback.

**Comment by ne0YT** [comment]
> This is the same for all multi-select boxes, the workaround for this currently is to use terraform, blueprints or the API directly

using the API smh resultet in issues not being authenticated when connecting to some of the added applications.

It would be great to have this fixed soon :)
