### ISSUE TITLE
Tasks API `start_timestamp` is not set, `task_duration` is wrong

### ISSUE THREAD

**Issue by sevmonster** [goauthentik/authentik#4885]
**Describe the bug**
I noticed that System Tasks durations in the web UI are not right. The source of that data is the tasks API, and it's being calculated incorrectly there. `start_timestamp` is not part of the task schema, so it's not possible to calculate it yourself either.

**To Reproduce**
Check System Tasks page in admin interface, or `GET /admin/system_tasks/`

**Expected behavior**
Duration is correct, and `start_timestamp` is set

**Screenshots**
![image](https://user-images.githubusercontent.com/16788697/224092395-bacc6038-e263-41bf-801b-c0b3c00de36f.png)
![image](https://user-images.githubusercontent.com/16788697/224098644-eb942b08-9918-4cbb-9068-d99172dd62c1.png)

**Version and Deployment (please complete the following information):**
 - authentik version: `gh-main`
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
`start_timestamp` is set here https://github.com/goauthentik/authentik/blob/main/authentik/events/monitored_tasks.py#L141 and here https://github.com/goauthentik/authentik/blob/main/authentik/events/monitored_tasks.py#L165

I think the incorrect value in the webui comes from the fact that the timestamps are from `default_timer`, which uses https://docs.python.org/3/library/time.html#time.perf_counter, which is maybe not the best thing to do here (I'm pretty sure I went with that as a lot of tasks can be sub 1-second long)
