### ISSUE TITLE
schemas.goauthentik.io is down - how can i setup nextcloud?

### ISSUE THREAD

**Issue by hofq** [goauthentik/authentik#4903]
**Describe your question/**
I can't find a dns record for schemas.goauthentik.io so i cant set it up

**Relevant infos**
I tried following https://goauthentik.io/integrations/services/nextcloud/ but the mentioned link does not work for me. is there an alternative?

**Screenshots**
![grafik](https://user-images.githubusercontent.com/54744977/224442800-2d8741cb-34b3-49f2-8004-2afad0d06c71.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2
 - Deployment: Docker CLI

**Comment by BeryJu** [comment]
The identifier used in SAML setups is a unique identifier, it's not a domain that is accessed and hence this is on purpose
