### ISSUE TITLE
With creating and delete some providers and application django.urls.exceptions.NoReverseMatch: 'authentk_providers_oauth2' is not a registered namespace

### ISSUE THREAD

**Issue by yodatak** [goauthentik/authentik#4905]
**To Reproduce**
Don't know but i do this 
With creating and delete some providers and application i got this error

provider

chat | Assigned to application                       chat2 | OAuth2/OpenID Provider
-- | -- | --

  | chat2 | - | chat | OAuth2/OpenID Provider
-- | -- | -- | -- | --

**Expected behavior**

**Screenshots**

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 256, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 246, in get_redirect_url
    url = reverse(self.pattern_name, args=args, kwargs=kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'authentk_providers_oauth2' is not a registered namespace
```
</details>

https://sso.XXXX.org/application/o/chat2/.well-known/openid-configuration
{
  "issuer": "https://sso.XXXX.org/application/o/chat2/",
  "authorization_endpoint": "https://sso.XXXX.org/application/o/authorize/",
  "token_endpoint": "https://sso.XXXX.org/application/o/token/",
  "userinfo_endpoint": "https://sso.XXXX.org/application/o/userinfo/",
  "end_session_endpoint": "https://sso.XXXX.org/application/o/chat2/end-session/",
  "introspection_endpoint": "https://sso.XXXX.org/application/o/introspect/",
  "revocation_endpoint": "https://sso.XXXX.org/application/o/revoke/",
  "device_authorization_endpoint": "https://sso.XXXX.org/application/o/device/",
  "response_types_supported": [
    "code",
    "id_token",
    "id_token token",
    "code token",
    "code id_token",
    "code id_token token"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post"
  ],
  "jwks_uri": "https://sso.XXXX.org/application/o/chat2/jwks/",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "implicit",
    "client_credentials",
    "password",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "id_token_signing_alg_values_supported": [
    "HS256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic"
  ],
  "acr_values_supported": [
    "goauthentik.io/providers/oauth2/default"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "profile"
  ],
  "request_parameter_supported": false,
  "claims_supported": [
    "sub",
    "iss",
    "aud",
    "exp",
    "iat",
    "auth_time",
    "acr",
    "amr",
    "nonce",
    "email",
    "email_verified",
    "name",
    "given_name",
    "family_name",
    "preferred_username",
    "nickname",
    "groups"
  ],
  "claims_parameter_supported": false
}

**Version and Deployment (please complete the following information):**
- authentik version: 2023.2.2
- Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by yodatak** [comment]
In the source release i got 
authentik-version-2023.2.3  rg authentk 
website/docs/flow/stages/authenticator_duo/index.md
20:This requires authentk 2022.9

authentik/providers/oauth2/urls.py
45:        RedirectView.as_view(pattern_name="authentk_providers_oauth2:provider-info"),

its the only place writen authentk and not authentik

**Comment by yodatak** [comment]
The link here go to 
https://goauthentik.io/docs/releases/2023.2    ghcr.io/goauthentik/server:2023.2.3
and 
https://goauthentik.io/docker-compose.yml
go to ghcr.io/goauthentik/server:2023.2.2

**Comment by yodatak** [comment]
it solved in [providers/oauth2: fix typo (](https://github.com/goauthentik/authentik/commit/5e60db8593dd599d607cb33e76b0e7598e187efa)https://github.com/goauthentik/authentik/pull/4803[)](https://github.com/goauthentik/authentik/commit/5e60db8593dd599d607cb33e76b0e7598e187efa)

**Comment by BeryJu** [comment]
fixed by the commit linked above
