### ISSUE TITLE
Local Docker connection is missing from Outpost integrations.

### ISSUE THREAD

**Issue by zilvernet** [goauthentik/authentik#4952]
**Describe the bug**
I'm not sure if this a bug or if it is a new intentional behavior, but I noticed that on the last version: 2023.3.0 if I create an authentik instance from scratch.
The Local Docker connection is missing from the authentik Embedded Outpost.

![image](https://user-images.githubusercontent.com/75147745/225172003-cc664328-3ae7-4c0e-ae94-761014763ad5.png)
![image](https://user-images.githubusercontent.com/75147745/225172072-b14a94ec-5eeb-486e-8d46-f8df042abc66.png)

Here is a print screen from an instance i have running on version 2023.2.2 that was recently created.
![image](https://user-images.githubusercontent.com/75147745/225170649-63847d2d-9684-4a9c-b106-9a5529d90c90.png)
![image](https://user-images.githubusercontent.com/75147745/225170839-ad2def95-15ca-4b9d-ad9b-7670aca0bf5c.png)

It seems that somewhere on the docker-compose installation the outpost integration gets created automatically, but on the version 2023.3.0 it doesn't get created.

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2023.3.0]
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
The local service connections are created by the `outpost_local_connection` task, which by default runs every 8 hours +- random delta, and also runs on worker startup. Check the logs to see if there's any errors related to `outpost_local_connection`

**Comment by zilvernet** [comment]
It looks that this log shows on the authentik_worker container:   
![image](https://user-images.githubusercontent.com/75147745/225177340-9f9cd981-23fb-4378-a6bf-e2e3984ddd91.png)

**Comment by aureateflux** [comment]
Is there any other resolution or workaround to this? I tried waiting 8 hours for outpost_connection_discovery to re-run, I tried forcing it to re-run. I tried restarting the container. This system task always reads "successful" but never discovers my docker environment.  At this point am I stuck redoing setup over and over until it works?

**Comment by speedyconzales** [comment]
fresh authentik install, same behaviour. no solution

**Comment by pwaldon** [comment]
Happens on 2024.6.3

**Comment by pwaldon** [comment]
Happens on 2024.6.3, `outpost_local_connection` task is missing.

@BeryJu  can we please have this reopened?

**Comment by Mathpro** [comment]
> Happens on **2024.6.3**, `outpost_local_connection` task is missing.
> 
> @BeryJu can we please have this reopened?
> 
> //Latest working version seems to be 2023.10.7 -- 'Local Docker connection' is then created, shows unhealthy, when you click on it is green with docker version.

Same here

**Comment by kibblewhite** [comment]
> > Happens on **2024.6.3**, `outpost_local_connection` task is missing.
> > @BeryJu can we please have this reopened?
> > //Latest working version seems to be 2023.10.7 -- 'Local Docker connection' is then created, shows unhealthy, when you click on it is green with docker version.
> 
> Same here

Same here also.

**Comment by BeryJu** [comment]
see #11260
