### ISSUE TITLE
Authenticator Validation Stage text is Black in both Light and Dark themes. 

### ISSUE THREAD

**Issue by xcsdm** [goauthentik/authentik#4973]
**Describe the bug**
Authenticator Validation Stage text is Black in both Light and Dark themes.  Firefox and Chrome have the same issue.

**To Reproduce**
Using the Light theme in your browser, begin a login with a user that has multiple MFA methods enabled.  Once you see selection screen, you can read the text.
Change the current browser theme to Dark, and attempt the same login.
The text is still Black against the dark background.

**Expected behavior**
Text and icons should be White against the dark background

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2023.3.0]
 - Deployment: docker-compose

**Comment by jeremywillans** [comment]
@BeryJu, this is fixed in Chrome, but I am still seeing the issue in Firefox 112.0.2. 

![mfa-screen](https://user-images.githubusercontent.com/31495062/235055413-a1c7c8d0-8e47-4f81-a064-017e19f3d6bb.png)

Running 2023.4.1

**Comment by typkrft** [comment]
I'm currently having this issue on 2023.10.5, did not have this issue on the previous version.

**Comment by xNinjaKittyx** [comment]
I just updated to 2023.10.5 and also running into this issue. I tested on Firefox 121.0, Edge 120.0.2210.91, and Brave 1.61.114/Chromium 120.0.6099.199. All of them have this problem for my setup.

**Comment by xNinjaKittyx** [comment]
Looks like someone made a duplicate here https://github.com/goauthentik/authentik/issues/7990

**Comment by jamesngob** [comment]
If I just select 1 method, it will display correctly e.g. text is dark but visible and you can see it's properly displayed. If you select 2 methods, then it is completely black-out, even if you try to "high-light" it (press-n-hold the mouse then move over it)... There is "nothing" in that area
Tested on Chrome (latest) and Safari (latest) on Jan 4, 2024
Cheers
