### ISSUE TITLE
MFA selection display in 2023.3.1

### ISSUE THREAD

**Issue by justsomemate** [goauthentik/authentik#4992]
**Describe the bug**
Selection of authentication method at login is displaying without the icons and with a grey background.

**To Reproduce**
1. Have more than one MFA device configured on a user or have MFA setup required
2. Log in
3. Authenticator choices are displayed incorrectly

**Expected behavior**
Authenticator choices are displayed with icons and same color background as the rest of the flow

**Screenshots**
In 2023.3.1 at Login
![image](https://user-images.githubusercontent.com/80608392/225970275-42d5bfb6-1bec-4fd2-b09d-baceb7990358.png)
In 2023.3.0 and before
![image](https://user-images.githubusercontent.com/80608392/225970605-66ca2d53-7ee0-4e1c-a173-9d18b6a90213.png)

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: docker-compose

**Additional context**
The display on initial login for a user when MFA configuration is required is similar (although it didn't have icons before 2023.3.1 either)
2023.3.1
![image](https://user-images.githubusercontent.com/80608392/225970546-1e286aa8-dc60-4ee3-9d1f-10ebd6e715f2.png)
2023.3.0
![image](https://user-images.githubusercontent.com/80608392/225971622-5d309f99-5966-4296-8a01-5c68b3b653b4.png)

**Comment by maevebaksa** [comment]
+1 Can confirm the same behavior on my instance after upgrading. The logo also broke, but that is for a separate issue.

**Comment by BeryJu** [comment]
This will be fixed in 2023.3.2
