### ISSUE TITLE
Visual Issues During Login of 23.3.1 Update

### ISSUE THREAD

**Issue by maevebaksa** [goauthentik/authentik#4998]
**Describe the bug**
There are a few visual issues since upgrading to version 23.3.1. I Upon login, the tenant icon is no longer scaled properly, and there are now 2 scrollbars that also cause weird jumpness when filling out text prompts.

**To Reproduce**
1. Update to 23.3.1.
2. Utilize a tenant icon larger than 560px wide.
3. Notice the icon falling off to the right of the page, and even with a properly sized 560px there are 2 scrollbars on the right side of the screen that cause weird motion. Powered by authentik and background image links are no longer visible and are now difficult to scroll to.

**Expected behavior**
Login page similar to that of 23.3.0. Icon auto scaling and centering, and the page not being too long that a scrollbar is required. 

**Screenshots**
<img width="241" alt="image" src="https://user-images.githubusercontent.com/90474549/226087397-b35fedd2-3d8c-4edc-86ae-c5ff38043913.png">

**Logs**
N/A

**Version and Deployment (please complete the following information):**
 - authentik version: 23.3.1
 - Deployment: docker-compose

**Additional context**
Please let me know if there are any further points of information I could provide.

**Comment by BeryJu** [comment]
This will be fixed in 2023.3.2

**Comment by maevebaksa** [comment]
Looks fixed in 23.4.0! :>
