### ISSUE TITLE
Logout is not logging out of proxied applications

### ISSUE THREAD

**Issue by wrt54gl** [goauthentik/authentik#4999]
Maybe we only need documentation on how to turn this but it seems all my proxied apps stay logged in even when I log out of authentik.

> @BeryJu was the recent fix supposed to log out proxied applications? E.g Say I use authentik proxy provider in front of a website with no auth. If I add a user, the user has access to said website.
> 
> If I remove the user, delete their session, remove the explicit consent, the user then should not have access to said website. I'm still seeing the same behavior as before, where the user is still able to access the website, even after removed, or logged out.

I am having this problem as well.

_Originally posted by @wrt54gl in https://github.com/goauthentik/authentik/issues/2023#issuecomment-1474574439_

**Comment by Schachte** [comment]
I'm seeing this same issue. Session invalidation still allows loading of application behind reverse proxy.
