### ISSUE TITLE
LDAP provider w/ LDAP outpost provides encoded output for accented names in name, displayName, sn fields

### ISSUE THREAD

**Issue by zphd** [goauthentik/authentik#5001]
**Describe the bug**
using accents in users name leads to encoded strings in LDAP output.

**To Reproduce**
1. create a User with accented name like "Fí Sándor"
2. query it via LDAP request
3. see bad results in name, displayName and sn fields: "RsOtIFPDoW5kb3I="
4. no errors in names w/out accents though

**Expected behavior**
get the given name in name, displayName and sn fields in LDAP output like "Fí Sándor"

**Version and Deployment (please complete the following information):**
 - 2023.3.1
 - docker-compose

**Comment by BeryJu** [comment]
This seems to be ldapsearch behaviour, see https://lurchi.wordpress.com/2009/11/03/ldapsearch-and-base64-encoding/

**Comment by zphd** [comment]
you're right, sorry for the false alarm.
