### ISSUE TITLE
Passwordless login using email magic link

### ISSUE THREAD

**Issue by drigolin** [goauthentik/authentik#5012]
It can be userfull to implement a passwordless login using a "magic link" sent the user private email and have te user loggin in by clicking on the received link.
A variation can be senting an OTP via EMAIL or SMS to have user to not setup a real password but the login process will rely on the "secure" channel like email or SMS.

**Comment by BeryJu** [comment]
duplicate of #3291

**Comment by nicoduck** [comment]
The other issue is about sending OTPs via E-Mail, while this is about sending a magic-link via E-Mail, as also noted here: https://github.com/goauthentik/authentik/issues/3291#issuecomment-1899322005
The Magic link could (should) directly login the session and could (depending on the implementation) even be used at another machine.

**Comment by thibaultmol** [comment]
@BeryJu @melizeche this isn't a duplicate, please reopen

**Comment by dewi-tik** [comment]
Will be adding an example that can be imported and achieve this with an email stage and a login stage
