### ISSUE TITLE
MFA SMS setup works but verification doesnt call SMS api

### ISSUE THREAD

**Issue by akshayohri** [goauthentik/authentik#5020]
During the first setup SMS API is called with the custom payload, but after first setup next time it just says SMS is sent but does not call the API and is actually waiting for totp code, which works if totp is setup.

**Comment by tograss** [comment]
I have the same problem. Device setup works but during login no sms is send.
For context: During setup I use the generic sms provider and a custom mapping.

I think the relevant part of the logs is:

{
  "auth_via": "unauthenticated",
  "challenge": "DeviceChallenge(data={'device_class': 'sms', 'device_uid': 3, 'challenge': {}}):\n    device_class = CharField()\n    device_uid = CharField()\n    challenge = JSONField()",
  "event": "adding challenge for device",
  "host": "xxx",
  "level": "debug",
  "logger": "authentik.flows.stage",
  "pid": 238297,
  "request_id": "53474ac79f764813b025a803f4305868",
  "stage": "default-authentication-mfa-validation",
  "stage_view": "authentik.stages.authenticator_validate.stage.AuthenticatorValidateStageView",
  "timestamp": "2023-05-09T10:16:16.638213"
}
Maybe challenge should not be empty ? Let me know if you need more from the logs.
