### ISSUE TITLE
New dropdown prompts do not work with arbitrary values and cannot receive default value

### ISSUE THREAD

**Issue by sevmonster** [goauthentik/authentik#5045]
**Describe the bug**
The new dropdown prompts cannot seem to handle strings as their value, and since their choices are set using the placeholder box, it's not straightforward to choose a default/placeholder value from the list.

**To Reproduce**
1. Set up some dropdown prompts with spaces in the values
2. Add them to a stage (I am using user settings) and try to save the values

**Expected behavior**
The values pass verification

**Screenshots**
![image](https://user-images.githubusercontent.com/16788697/226949532-4aeca73c-349b-40a8-852a-a59157fce4c7.png)

**Version and Deployment (please complete the following information):**
 - authentik version: `gh-main`
 - Deployment: docker-compose

**Additional context**
While the current implementation using the placeholder field is good, it would be better to be able to provide a default/placeholder value (in my case default, for user-settings flows) in addition to the list, but this does not seem to be obviously possible when using dropdowns. I suppose you could reorder the values so the top choice is the preferred one, but that seems annoying to have to write into every dropdown placeholder expression. Since I can't get dropdowns to work I also do not know at first glance if the associated attribute value will change the selected default/placeholder implicitly, but I assume not since this does not happen with other fields.

**Comment by sevmonster** [comment]
@sdimovv

**Comment by sdimovv** [comment]
@BeryJu , I will be interested to hear your take on the above, when you can spare a few minutes!

**Comment by sevmonster** [comment]
I definitely prefer the 2 value return, and frankly I don't get the reason for not including it, when shifting the preselected/default value to the first position isn't great UX, no worse than telling the admin to add a comma and another value is. authentik is already heavy on the Python and policies, I would think anyone trying to use it would understand that and be ready to do some learning if they don't understand something.

Also, using the values as the indexes really locks you in to whatever verbiage you used when initially setting up the values, which also sucks—dict would have been better.

If I had considered these issues when you were first writing the PR I probably would have said something then, but I didn't dig too deep into it at the time...

**Comment by sdimovv** [comment]
You have a point about authentik already making heavy use of Python in policies. I guess we can expect/require admins to have some knowledge of Python. 

But even so, I am not sure overloading (again) the meaning of the placeholder field in this way is a good UX. 

Until now the placeholder had 1 meaning - return a single value to be used as placeholder string. With the addition of the choice fields it got overloaded with another meaning - returning a list of choices. Now adding this second value/list for specifying default choice(s), overloads it with yet another meaning.

In my opinion, this way it starts feeling more like a hack.

> dict would have been better.

Did not understand what you mean by this. Can you show  some examples? 

In fact, can you explain/show examples of how you imagine the general choice fields functionality to look like (pretend you are developing it from scratch)?

**Comment by sevmonster** [comment]
Technically the placheholder was already repurposed as a default/prefilled value when used in user settings flows. They were only placeholders in normal flows. So the field is already a bit hacky to begin with, which probably is why I am not too opposed to addingm ore hackiness :)

To me something like this makes the most sense:
```python
vals = {
  1: 'Value one',
  2: 'Second value',
  3: 'Foobar',
  4: 'Bazquux'
}
try:
    return vals, user.attributes['myfield'] # this is a key from the dict
except:
    return vals, 2 # 'Second value' key
```
The only additions are the selection of a default value and the use of dicts so that the textual value is decoupled from the selection. This severely increases backend simplicity and usability. I don't want to have to 1) hardcode a bunch of English strings to check against or 2) run a policy every time to get an enum of values to cast against.

**Comment by sdimovv** [comment]
> Technically the placheholder was already repurposed as a default/prefilled value when used in user settings flows

I believe (haven't checked) the user settings flow just sets the placeholder as a the "value" attribute of the HTML element, instead of as the "placeholder", which in my opinion, doesn't really count as overloading the meaning of the placeholder.

With regards to the dict idea - even more complicated and unnecessary. There is no reason to return a dictionary. I have no use of it. I will have to extract the values of it and then pass them on to the frontend as a list again.


But you might still be onto something. For example:
```
return ["a", "b", "c"], 1 # index 1 is defaut ("b") 
return ["a", "b", "c"], [1, 2] # indexes 1 and 2 are defaut 
```

This is pretty much identical to my earlier implementation proposal. It gets rid of the need to specify the default values twice. Although it will require you to know the index(es) of the default value(s) which is more or less the same. Not sure which makes more sense.


And regarding your dict idea you can still achieve the same functionality with a list:

```
vals = {
  1: 'Value one',
  2: 'Second value',
  3: 'Foobar',
  4: 'Bazquux'
}
try:
    return vals.values(), vals[user.attributes['myfield']] # this is a key from the dict
except:
    return vals.values(), vals[2] # 'Second value' key
```

**Comment by sevmonster** [comment]
> I believe (haven't checked) the user settings flow just sets the placeholder as a the "value" attribute of the HTML input element, instead of as the "placeholder", which in my opinion, doesn't really count as overloading the meaning of the placeholder.

You're correct about the functionality. It's a semantic difference, sure, but it's still a notable case where the purpose of the value does something different than expected. It would also be nice UX to allow a placeholder and provide an initial value since one may not always exist.

This is getting off-topic, but this also introduces an issue where if you open your user settings flow in the normal flow executor, you can't edit the placeholder text, and must retype any values you want. It also prevents you from easily adapting an existing flow into a user settings flow since the existing placeholders must all be removed if they contain free text or instructions instead of example/prefilled values.

> With regards to the dict idea - unnecessary. There is no reason to return a dictionary. I have no use of it.

This is perhaps the worst argument I see when discussing code and issues, and it makes me sad every time I do. I earnestly request you try to avoid making it.

I understand you might not have or see a particular problem with the implementation, or might not want to write the code or implement it yourself. However, that doesn't change that there are clearly shown problems that are avoided or solved by utilizing a new approach. It is a common paradigm to use enumerations for data in lists for good reason, to avoid using a fixed string as a value. It's bad practice and puts more work on the admin.

> And regarding your dict idea - you can achieve the same functionality and still return a list:

There is no reason to do this if the dict index is not saved. It is a waste of typing. The point of using indexes is to prevent the things I already stated, and for this particular example you could just as easily use a list with numeric indexes instead of a dict. But like I said that's not the point.

Even if you don't find an issue with it now, you and anyone else sure will in the future when all the policies and flows you've written that expect a certain string value need to be updated because you want to change how a specific choice is written, or perhaps translate it to another language.

If you're concerned about the code-wary admin, be concerned about how they will react when they need to do the above. Changing a single string in a single prompt, vs changing it in however many places, I'm sure our poor hypothetical admin has forgotten by now. (I know this isn't a great example because a code-wary admin won't be using policies if they can help it I'm sure, but the reasoning stands.)

> I will have to extract the values of it and then pass them on to the frontend as a list again.

Then this may be a limitation of the frontend framework or implementation. Listboxes have separate values and inner text.

I have not done any authentik development but if you really don't see the problems with this approach enough to warrant updating it, I will certainly try.

Let me be clear too that we all value your work. I have wanted more input choices for a while and you were the first to step up. It's admirable.

@BeryJu You may want to convert this to a discussion.

**Comment by sdimovv** [comment]
Moved to https://github.com/goauthentik/authentik/discussions/5063
