### ISSUE TITLE
LDAP outpost with SSL

### ISSUE THREAD

**Issue by ra2f** [goauthentik/authentik#5056]
**Describe your question/**
I'm trying to deploy a LDAP outpost with TLS. I can successfully run the following command to get the list of users:

```console
ldapsearch  -x -h my_server -p 389 \
            -D 'cn=ldapservice,ou=users,dc=ldap,dc=goauthentik,dc=io' \
            -w 'my_password' \
            -b 'dc=ldap,dc=goauthentik,dc=io' '(objectClass=user)'
```

But same command with ldaps:
```console
ldapsearch  -x -h my_server -p 636 \ <-- 636 for ldaps
            -D 'cn=ldapservice,ou=users,dc=ldap,dc=goauthentik,dc=io' \
            -w 'my_password' \
            -b 'dc=ldap,dc=goauthentik,dc=io' '(objectClass=user)'
```
return the following error:
```console
ldap_initialize( ldap://127.0.0.1:636 )
ldap_result: Can't contact LDAP server (-1)
```
The ldap server output the following error:  **handleConnection ber.ReadPacket ERROR: tls: first record does not look like a TLS handshake**

I followed the following [instructions](https://goauthentik.io/docs/providers/ldap/generic_setup), and it's working on 389.

**Relevant infos**
Authentik server, worker and the ldap outpost are running under Docker on the latest version 2023.3.1. The Authentik server is behind a reverse proxy (Traefik) - could it be the source of the issue?

My LDAP docker instance is launched using the following command:
```console
docker run -it --rm -p 389:3389 -p 636:6636 \
           -e AUTHENTIK_HOST="https://authentik.local" \
           -e AUTHENTIK_TOKEN="TOKEN" \
           -e AUTHENTIK_DEBUG="true" \
           -e AUTHENTIK_INSECURE="true" \
           ghcr.io/goauthentik/ldap:2023.3.1
```
The environment variable `AUTHENTIK_INSECURE` is set to `true` because my provider is using the certificate: **authentik Self-signed Certificate** as suggested [here](https://goauthentik.io/docs/providers/ldap#ssl)

I tried to set it to false and remove the certificate from the provider without success.
I tried to re-create the provider-outpost-application without success either.

**Logs**
The full logs of the deployment:
```console
{"event":"Loaded config from environment","level":"debug","timestamp":"2023-03-23T15:44:59Z"}
INFO[0000] Starting Debug server                         listen="0.0.0.0:9900" logger=authentik.go_debugger
INFO[0001] Fetching certificate and private key          logger=authentik.outpost.cryptostore uuid=1220ae38-edef-490b-9016-2d1a8703995b
INFO[0002] Fingerprint hasn't changed, not fetching cert  logger=authentik.outpost.cryptostore uuid=1220ae38-edef-490b-9016-2d1a8703995b
INFO[0002] initialised direct binder                     logger=authentik.outpost.ldap.binder.direct
INFO[0002] Update providers                              logger=authentik.outpost.ldap
INFO[0002] Starting LDAP SSL server                      listen="0.0.0.0:6636" logger=authentik.outpost.ldap
INFO[0002] Starting LDAP server                          listen="0.0.0.0:3389" logger=authentik.outpost.ldap
INFO[0002] Starting Metrics server                       listen="0.0.0.0:9300" logger=authentik.outpost.metrics
INFO[0002] Starting authentik outpost                    hash=tagged logger=authentik.outpost version=2023.3.1
INFO[0003] Fingerprint hasn't changed, not fetching cert  logger=authentik.outpost.cryptostore uuid=1220ae38-edef-490b-9016-2d1a8703995b
INFO[0003] Update providers                              logger=authentik.outpost.ldap
2023/03/23 15:45:19 handleConnection ber.ReadPacket ERROR: tls: first record does not look like a TLS handshake
```
It seems that authentik fetched the certificate and private key. Nevertheless it still fail with `ldapsearch`.
Do you know if any step of my deployment is wrong or if it's a bug?

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: Docker

**Additional context**
-

**Comment by BeryJu** [comment]
(just for clarity, the LDAP outpost only supports SSL not StartTLS)

I think you might need to tell ldapsearch to use SSL, try using `-H ldaps://my_server` which should imply the port and correctly tell it to use SSL

**Comment by ra2f** [comment]
I also tried that without success. I'll take a closer look to SSL vs StartTLS.

I can also add that the error  **handleConnection ber.ReadPacket ERROR: tls: first record does not look like a TLS handshake**, can simply be triggered with a `curl 127.0.0.1:636`. Is it expected?

**Comment by cuthulino** [comment]
Ignoring the cert helped me for debug query.
Maybe this will help you too.

Take a look at my issue #4713
