### ISSUE TITLE
Connection error : reconecting

### ISSUE THREAD

**Issue by thestarrypage** [goauthentik/authentik#5064]
**Describe the bug**

**To Reproduce**
When login as Administrator and navigate to the Dashboards>Overview
On the top right corner keep popping out "Connection error"
I cannot seem to find any error logs to get more information.
Everything is working perfectly

3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/113044240/227417917-80e01e6d-723a-468a-9fc4-a920e00742b1.png)

**Logs**
Output of docker-compose logs or kubectl logs respectively
no visible logs showing connection error

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by thestarrypage** [comment]
think for pointing out, fixed this on Nginx

**Comment by Lord-ZuzurNC** [comment]
For Nginx Proxy Manager just ticking "Websockets Support" (on Details tab) and "HTTP/2 Support" (in SSL tab) make it work.
