### ISSUE TITLE
This project used requests-oauthlib , which uses oauthlib with confusing licensing.

### ISSUE THREAD

**Issue by v3ss0n** [goauthentik/authentik#5071]
**Describe your question/**
This project uses Ouathlib indrectly
**Relevant infos**
Oauthlib prohibit uses of their lib in closesource products , and neeed to subscribe 1000$/year license if it is not free / opensource software.

What will be the impact of this project when we use it for clients to sell our services?

**Comment by BeryJu** [comment]
Hi, thanks for pointing this out! I wasn't aware of this, could you link the licensing page for this?

**Comment by v3ss0n** [comment]
I double checked and i was wrong  . requests-oauthlib is depended on :  https://github.com/oauthlib/oauthlib
I thought it was depended on authlib : https://github.com/lepture/authlib which used confusing license -> https://github.com/lepture/authlib/issues/475

I was using Authentik and we are going to devleop an internal srum/taskboard tool using [starlite](https://github.com/starlite-api/starlite) , which currently don't have OIDC implementation so i am checking for a client and found about that license confusion issue.
