### ISSUE TITLE
Plan resumed for invitation flow, even though invitation ID differs

### ISSUE THREAD

**Issue by flyte** [goauthentik/authentik#5073]
**Describe the bug**
When developing our invitation system, we're clicking on many different invitation URLs and executing our invitation flow for each of them. Prior to fixing my configuration, I had been redirecting out of the flow, to our app using `plan.redirect("<url>")`, which never let the plan complete. Then when we revisited the same flow, but with a different invitation `itoken` value, Authentik tried to resume our previous plan, and just returned the redirect instead of executing a new plan.

I admit, this is somewhat of an edge case, but perhaps Authentik should take into account the `itoken` when deciding to continue an existing session's plan, or start a new one. At the moment it just checks if the plan was for the current flow or not, which it is in our case.

**Logs**

```json
{
  "auth_via": "session",
  "event": "f(exec): Continuing existing plan",
  "flow_slug": "tf-my-invitation-login",
  "host": "auth.redacted.com",
  "level": "debug",
  "logger": "authentik.flows.views.executor",
  "pid": 19,
  "request_id": "1f951722db914d0094269a5198d4e7ad",
  "timestamp": "2023-03-24T11:17:45.385536"
}
{
  "auth_via": "session",
  "current_stage": "<Stage: In-memory Stage <class 'authentik.flows.stage.RedirectStage'>>",
  "event": "f(exec): Current stage",
  "flow_slug": "tf-my-invitation-login",
  "host": "auth.redacted.com",
  "level": "debug",
  "logger": "authentik.flows.views.executor",
  "pid": 19,
  "request_id": "1f951722db914d0094269a5198d4e7ad",
  "timestamp": "2023-03-24T11:17:45.386585"
}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: k8s

**Comment by BeryJu** [comment]
Yeah currently the `itoken` is only checked by the invitation stage, so if the flow in the session is already ahead of the invitation stage then it's value won't be checked.

One way to make this testing workflow easier would be to have an iframe in the admin interface to run the flow with the `sandbox` attribute set to prevent the frame from reading any cookies on the same page, and thus acting like an incognito browser window
