### ISSUE TITLE
Cancel/End flow if a stage fails

### ISSUE THREAD

**Issue by motey** [goauthentik/authentik#5074]
**Describe your question/**
How to end a complete flow (do not run any further stages) if a specific stage is denied.

**Relevant infos**
At the moment i can not find a configuration in my flow/stage/policiy construct to skip certain or all stages when  a precursor stage fails (is denied by policy). I read the docs 3 times and tried it for 3 hours. Am i just stupid or is it my requirement that is stupid?

**Screenshots**
![image](https://user-images.githubusercontent.com/1006417/227553450-bcdf4d57-00b9-41f2-b48c-48352d6f70ab.png)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**
 - authentik version:2023.3.1
 - Deployment: docker-compose

Any hint is very appreciated :heart:

**Comment by BeryJu** [comment]
Currently a policy bound to a stage can only affect the stage it's bound to, you could bind your policy to the other stage to affect that too, or you can flip the logic around and conditionally have a deny stage that ends the flow execution too

**Comment by motey** [comment]
Ok, thanks. That's a little bit confusing for me?
So do i misuse/misinterpret Policies? 
The goal i want to achieve is to validate, sanitize user input and generate a username (`firstname.lastname`) on enrollment. 
Ideally it would just bounce back to the first stage and explain the user whats wrong ("Email allready in use", "name too short", ...)
Do you think this is possible?
