### ISSUE TITLE
Cannot bind policy to application

### ISSUE THREAD

**Issue by julianq** [goauthentik/authentik#5076]
**Describe the bug**

**To Reproduce**
1. Go to Applications
2. Click on any Application
3. Go go Policy / Group/ User Bindings
4. Click Create Binding
5. Configure Binding
6. Click Create

**Expected behavior**
Binding to be created - instead binding creation fails with a 400 Bad Request error.

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: docker-compose

**Additional context**
As above. Existing bindings remain and function as expected.

**Comment by BeryJu** [comment]
I assume there's no errors on the form, could you open the browser developer console, check on the network tab and post the response of the failed request?

**Comment by julianq** [comment]
Of course, see below, anonymized, please let me know if you'd like anything else:

> HTTP/1.1 400 Bad Request
> Allow: GET, POST, HEAD, OPTIONS
> Content-Encoding: gzip
> Content-Type: application/json
> Date: Fri, 24 Mar 2023 19:29:18 GMT
> Referrer-Policy: same-origin
> Vary: Accept-Encoding
> Vary: Cookie
> X-Authentik-Id: <string>
> X-Content-Type-Options: nosniff
> X-Frame-Options: DENY
> X-Powered-By: authentik
> Content-Length: 62

> POST /api/v3/policies/bindings/ HTTP/1.1
> Host: 192.168.1.100:7000
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
> Accept: */*
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate
> Referer: http://192.168.1.100:7000/if/admin/
> sentry-trace: <string>
> Content-Type: application/json
> X-authentik-CSRF: <string>
> Content-Length: 105
> Origin: http://192.168.1.100:7000
> Connection: keep-alive
> Cookie: organizrLanguage=en; authentik_csrf=<string>; authentik_session=<string>

**Comment by BeryJu** [comment]
there should also be some more text below, this is excluding the actual response body

the request that's failing is the policy create request which makes sense

**Comment by julianq** [comment]
Here's the request (for a group access binding, but same behavior on user and policy bindings):

> {"group":[string],"negate":true,"enabled":true,"order":"10","timeout":"30"}

And the response:

> {"target":["This field is required."]}

Stack trace:

> Rr/</<
> [instrument.js:137:27](http://192.168.224.100:7000/static/node_modules/@sentry/utils/esm/instrument.js)
> a/this.fetchApi/<
> [runtime.js:84:72](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> a
> [runtime.js:17:57](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> (Async: promise callback) u
> [runtime.js:19:90](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> i</<
> [runtime.js:20:8](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> i<
> [runtime.js:16:11](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> a/this.fetchApi
> [runtime.js:77:49](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> request/<
> [runtime.js:115:40](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> a
> [runtime.js:17:57](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> (Async: promise callback) u
> [runtime.js:19:90](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> i</<
> [runtime.js:20:8](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> i<
> [runtime.js:16:11](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> request
> [runtime.js:113:15](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/runtime.js)
> policiesBindingsCreateRaw/<
> [PoliciesApi.js:300:40](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/apis/PoliciesApi.js)
> Cu</<
> [PoliciesApi.js:20:70](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/apis/PoliciesApi.js)
> Cu<
> [PoliciesApi.js:16:11](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/apis/PoliciesApi.js)
> policiesBindingsCreateRaw
> [PoliciesApi.js:290:15](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/apis/PoliciesApi.js)
> policiesBindingsCreate/<
> [PoliciesApi.js:315:40](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/apis/PoliciesApi.js)
> Cu</<
> [PoliciesApi.js:20:70](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/apis/PoliciesApi.js)
> Cu<
> [PoliciesApi.js:16:11](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/apis/PoliciesApi.js)
> policiesBindingsCreate
> [PoliciesApi.js:314:15](http://192.168.224.100:7000/static/node_modules/@goauthentik/api/dist/esm/apis/PoliciesApi.js)
> value/<
> [PolicyBindingForm.ts:93:51](http://192.168.224.100:7000/static/src/admin/policies/PolicyBindingForm.ts)
> pe</e/<
> [Form.ts:222:40](http://192.168.224.100:7000/static/src/elements/forms/Form.ts)
> d
> [regeneratorRuntime.js:44:16](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/regeneratorRuntime.js)
> n/k/<
> [regeneratorRuntime.js:125:30](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/regeneratorRuntime.js)
> n/x/</<
> [regeneratorRuntime.js:69:20](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/regeneratorRuntime.js)
> r
> [asyncToGenerator.js:3:24](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js)
> s
> [asyncToGenerator.js:22:27](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js)
> i/</<
> [asyncToGenerator.js:27:6](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js)
> i/<
> [asyncToGenerator.js:19:11](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js)
> pe</<.d<.value<
> [Form.ts:282:5](http://192.168.224.100:7000/static/src/elements/forms/Form.ts)
> e/<
> [ModalForm.ts:31:33](http://192.168.224.100:7000/static/src/elements/forms/ModalForm.ts)
> d
> [regeneratorRuntime.js:44:16](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/regeneratorRuntime.js)
> n/k/<
> [regeneratorRuntime.js:125:30](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/regeneratorRuntime.js)
> n/x/</<
> [regeneratorRuntime.js:69:20](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/regeneratorRuntime.js)
> r
> [asyncToGenerator.js:3:24](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js)
> s
> [asyncToGenerator.js:22:27](http://192.168.224.100:7000/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js)

It is entirely possible I'm missing something in the configuration but I don't think I am. Just noticed this behavior today.

**Comment by julianq** [comment]
Sorry, just now managed to get back. Confirmed resolved. Thank you for your hard work.
