### ISSUE TITLE
User can't copy app password created by Admin

### ISSUE THREAD

**Issue by kirik** [goauthentik/authentik#5080]
**Describe the bug**
When Admin creates App Password on user's behalf - User then can't copy this App Password from his/her account, getting 403 for /api/v3/core/tokens/cy-at-mail_sac_ag/view_key/ with "You do not have permission to perform this action." message.

**To Reproduce**
1. Create a non expiring App Password for User using Admin account;
2. Log in under the User account and try to copy this app password;
3. You will get "Error: You do not have permission to perform this action."

**Expected behavior**
User should be able to copy App Password which belongs to his/her account

**Screenshots**
n/a

**Logs**
n/a

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: docker compose / manual

**Additional context**
There are 2 ways to create App Passwords with no expire time for users:
1. using `goauthentik.io/user/token-expires: false`
2. creating App Passsword under Admin account

this issue covers case number 2.

**Comment by BeryJu** [comment]
This is currently intended, more flexibility for this will be possible with #5451
