### ISSUE TITLE
Redirects to API endpoint after refreshing forward auth token instead of returning to page

### ISSUE THREAD

**Issue by yaakovfeldman** [goauthentik/authentik#5097]
**Describe the bug**
I have deployed Authentik 2023.3.1 in Docker and am using it with Caddy as forward auth for an app, using a proxy provider and 'forward auth single application'. This app makes frequent javascript requests to its backend. The frontend and backend API have the same domain `example.com`.

Occasionally I see an error message in the app's UI due to the auth token expiring. When I refresh the page, the auth is satisfactorily renewed but I am redirected to `example.com/api/endpoint` rather than to `example.com\page-i-was-actually-on`.

I assume the app must have made an javascript request to `example.com/api/endpoint` in the background earlier. Looking at the app's typical network requests I see there is no header such as `X-Requested-With: XMLHttpRequest` to hint that they are made by javascript.

**To Reproduce**
This only happens on one app https://github.com/benphelps/homepage and I am not sure if it can easily be reproduced but it happens to me regularly. I have not yet noticed this with other apps but I have only been using Authentik for several days.

**Expected behavior**
Be returned to page I was on.

**Logs**
I cannot see anything relevant in logs.
```
27/03/2023 20:52:01

    auth_via= unauthenticatedevent= /application/o/authorize/?client_id=Pz0wvEco24AJq5pqHH4cdL8qeEZelpZ0TAqo7YGE&redirect_uri=https%3A%2F%2Fapps.example.com%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=openid+profile+email+ak_proxy&state=OHV5qzcnNrjtehX0_py7t710ch3PM87Y6BhCZuL_eZUhost= authentik.apps.example.comlevel= infologger= authentik.asgimethod= GETpid= 36838remote= 127.0.0.1request_id= e063705985814047b786165deb546878runtime= 36scheme= httpsstatus= 302timestamp= 2023-03-27T19:52:01.135905user= user_agent= Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

    add  auth_via=unauthenticated
    add  event=/application/o/authorize/?client_id=Pz0wvEco24AJq5pqHH4cdL8qeEZelpZ0TAqo7YGE&redirect_uri=https%3A%2F%2Fapps.example.com%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=openid+profile+email+ak_proxy&state=OHV5qzcnNrjtehX0_py7t710ch3PM87Y6BhCZuL_eZU
    add  host=authentik.apps.example.com
    add  level=info
    add  logger=authentik.asgi
    add  method=GET
    add  pid=36838
    add  remote=127.0.0.1
    add  request_id=e063705985814047b786165deb546878
    add  runtime=36
    add  scheme=https
    add  status=302
    add  timestamp=2023-03-27T19:52:01.135905
    add  user=
    add  user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

27/03/2023 20:53:31

    event= /outpost.goauthentik.io/auth/caddy?type=disk&target=/host= apps.example.comlevel= infologger= authentik.outpost.proxyv2.applicationmethod= GETname= homepage-proxyremote= 127.0.0.1runtime= 2.356scheme= httpsize= 371status= 302timestamp= 2023-03-27T19:53:31Zuser_agent= Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

    add  event=/outpost.goauthentik.io/auth/caddy?type=disk&target=/
    add  host=apps.example.com
    add  level=info
    add  logger=authentik.outpost.proxyv2.application
    add  method=GET
    add  name=homepage-proxy
    add  remote=127.0.0.1
    add  runtime=2.356
    add  scheme=http
    add  size=371
    add  status=302
    add  timestamp=2023-03-27T19:53:31Z
    add  user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: docker compose

I have had no other issues and think Authentik is great!

**Comment by DomiStyle** [comment]
I'm constantly getting this as well.

If you leave any website open for long enough and an API call fails in the background upon refreshing the website you will be redirected to the API route.

It seems like authentik is trying to redirect to the first requested site that was unauthenticated instead of the last one?

**Comment by yaakovfeldman** [comment]
Not stale: issue still occurs.

**Comment by saxobroko** [comment]
Can confirm i've been getting this for the past 8 months since I started with Authentik

**Comment by nakinney** [comment]
So, is this going to get fixed or is it just going be ignored by the dev team?

**Comment by yaakovfeldman** [comment]
> So, is this going to get fixed or is it just going be ignored by the dev team?

Seems to be duplicate of https://github.com/goauthentik/authentik/issues/6886 which was recently fixed
