### ISSUE TITLE
Outpost providers not updating

### ISSUE THREAD

**Issue by qistoph** [goauthentik/authentik#5110]
**Describe the bug**
Changes to providers don't seem to reflect in my outpost configurations. Not even after restarting all services.

**To Reproduce**
I have added a new application, provider and mapping to my outpost. 

Provider:
Name: Paperless
Auth flow: ...-implicit
Forward Auth (single application) 
External host: https://paperless.ORG.nl 

Application
Name: Paperless
Slug: paperless
Provider: Paperless
Policy Engine: any

**Expected behavior**
Forward auth for new app should work

**Screenshots**
```
{
	"Message": "no app for hostname",
	"Host": "paperless.ORG.nl",
	"Detail": "Check the outpost settings and make sure 'paperless.ORG.nl' is included."
}
```

**Logs**
See below

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: docker-compose

**Additional context**
Build proxy locally with added trace logging of apps and providers for proxy:
```diff
diff --git a/internal/outpost/proxyv2/refresh.go b/internal/out
post/proxyv2/refresh.go
index 357044c46..f8c1581c5 100644
--- a/internal/outpost/proxyv2/refresh.go
+++ b/internal/outpost/proxyv2/refresh.go
@@ -46,6 +46,8 @@ func (ps *ProxyServer) Refresh() error {
                }
        }
        ps.apps = apps
+       ps.log.WithField("apps", apps).Trace("tracing apps for
swapped maps")
+       ps.log.WithField("providers", providers).Trace("tracing
 providers for swapped maps")
        ps.log.Debug("Swapped maps")
        return nil
 }
```

Current outpost doesn't log new app, doesn't reflect any changes to the outpost selection of providers. 

Added a new testing outpost. Its logging doesn't show any apps:
```
{"apps":{},"event":"tracing apps for swapped maps","level":"tra
ce","logger":"authentik.outpost.proxyv2","timestamp":"2023-03-2
8T14:03:56Z"}
{"event":"tracing providers for swapped maps","level":"trace","
logger":"authentik.outpost.proxyv2","providers":{"pagination":{
"count":0,"current":1,"end_index":0,"next":0,"previous":0,"star
t_index":0,"total_pages":1},"results":[]},"timestamp":"2023-03-
28T14:03:56Z"} 
```

Query API directly for usual outpost doesn't reflect any changes:
```
$ curl --http1.1 -H 'Authorization: Bearer TOKEN_OUTPOST' 'https://authentik.ORG.nl/api/v3/outposts/proxy/' | jq '.results[]|{name,mode,exter
nal_host}'     
{
  "name": "Cacti Proxy Provider",
  "mode": "forward_single",
  "external_host": "https://www.ORG.nl/cacti/"
}
{
  "name": "Jupyter",
  "mode": "forward_single",
  "external_host": "https://jupyter.ORG.nl"
}
{
  "name": "Photoprism",
  "mode": "forward_single",
  "external_host": "https://foto.ORG.nl"
}
{
  "name": "whoami-proxy",
  "mode": "forward_single",
  "external_host": "https://whoami.ORG.nl"
}
```

Query API directly for new testing outpost doesn't return anything:
```
curl --http1.1 -H 'Authorization: Bearer TOKEN_TEST' 'https://authentik.ORG.nl/api/v3/outposts/proxy/' | jq '.'
{
  "pagination": {
    "next": 0,
    "previous": 0,
    "count": 0,
    "current": 1,
    "total_pages": 1,
    "start_index": 0,
    "end_index": 0
  },
  "results": []
}
```

Query API directly for new testing outpost on any type does show the new outpost of type proxy:
```
$ curl --http1.1 -H 'Authorization: Bearer TOKEN_TEST' 'https://authentik.ORG.nl/api/v3/outposts/instances/' | jq '.results[]|{name,type}'
{
  "name": "Test Outpost",
  "type": "proxy"
}
```

It seems the outpost API is not being updated to include the new app. Am I doing something wrong? Is this a bug in Authentik?

**Comment by BeryJu** [comment]
The reason for this is that when a provider is added to an outpost, the outpost's service account's permissions are updated to allow the outpost to access all it's configured providers via API. However this update process happens in the background (via the `outpost_post_save` task, which calls the `outpost.token` getter and `outpost.build_user_permissions()`

**Comment by qistoph** [comment]
Thanks for the quick reply, @BeryJu.

When should the changes be reflected in the available outpost configuration? I'm having issues configuring my new app and can't seem to get the outpost to recognize it for a couple of days now.

**Comment by brujoand** [comment]
@qistoph were you able to resolve this? I'm seeing the same issue now using version `2023.4.1`. No matter what changes I make to the outposts the ingress objects are not updated with the new hosts. I can however change the log level, which shows that "something" is atleast happening, but it's being triggered twice:

```
{"event":"Got update trigger...","level":"debug","logger":"authentik.outpost.ak-api-controller","loop":"ws-handler","timestamp":"2023-05-01T07:40:25Z"}
{"event":"Fetched outpost configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","name":"Services","timestamp":"2023-05-01T07:40:25Z"}
{"event":"Swapped maps","level":"debug","logger":"authentik.outpost.proxyv2","timestamp":"2023-05-01T07:40:25Z"}
{"event":"Got update trigger...","level":"debug","logger":"authentik.outpost.ak-api-controller","loop":"ws-handler","timestamp":"2023-05-01T07:40:34Z"}
{"event":"Fetched outpost configuration","level":"debug","logger":"authentik.outpost.ak-api-controller","name":"Services","timestamp":"2023-05-01T07:40:34Z"}
{"event":"Swapped maps","level":"debug","logger":"authentik.outpost.proxyv2","timestamp":"2023-05-01T07:40:34Z"}
```

But both the worker and server are only 1 instance each.

**Comment by qistoph** [comment]
It was resolved after some tinkering around. Stopping and restarting the services. I think my disks might have been full at some point, maybe causing issues for redis.

Never figured out what the actual cause was
