### ISSUE TITLE
Proxy Provider doesn't allow docker compose container names

### ISSUE THREAD

**Issue by lyz-code** [goauthentik/authentik#5126]
**Describe the bug**
When configuring a proxy provider to forward traffic to a docker created through a `docker-compose` command I'm getting an `Enter a valid URL` error.

Docker compose uses underscores instead of dashes to split the container name, for example `prometheus_prometheus_1`. This is not a valid URL.

**To Reproduce**
1. Create a new proxy provider
2. In the internal host configuration enter: `http://prometheus_prometheus_1:9090`
3. Click on Create

**Expected behavior**
Container names should be taken as valid urls

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.2.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Docker changed this with compose v2, which is built into the docker CLI using `docker compose` without the hyphen, this is intended as URLs with underscores are not valid DNS names and as such don't pass the validation. The alternative is to add an aliases section to the compose service, which allows specifying additional hostnames that don't use underscores

**Comment by lyz-code** [comment]
[Aliases did work for me](https://docs.docker.com/compose/compose-file/compose-file-v3/#aliases) thank you :)
