### ISSUE TITLE
Unable to complete the Device code flow

### ISSUE THREAD

**Issue by timoles** [goauthentik/authentik#5133]
**Describe the bug**
The [Device Code Flow](https://goauthentik.io/docs/providers/oauth2/device_code) appears to not work and seemingly has issues in multiple steps.

**To Reproduce**
1. Setup up the server with docker as described [here](https://goauthentik.io/docs/installation/docker-compose/?utm_source=github)
2. Create a public OAuth provider and attach an application
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/18122064/229139083-3fafb86f-af40-4243-8275-af335f0bb039.png">
3. Create a device token as described [here](https://goauthentik.io/docs/providers/oauth2/device_code#device-side)
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/18122064/229139370-2f203e5d-fbc0-40dd-93b7-59060b388ba1.png">
4. Attempt to access the device code page (First error, HTTP 404)
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/18122064/229139582-551c02bd-d118-45ad-9218-c03287232ad2.png">
5. Attempt to retrieve the access token (Expected response `authorization_pending`, however it can't find the token) (as described [here](https://goauthentik.io/docs/providers/oauth2/device_code#device-side)) (I attempted to submit the device code URL encoded, and raw)
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/18122064/229139998-d20595a3-5de5-4ea0-b83e-0b943469cc86.png">

**Expected behavior**
1. It is expected to retrieve an HTTP page in which a user can access their device code when accessing `http://localhost:9000/device`
2. It is expected to get `authorization_pending` response, when querying the device code.

Potential error on my side: Do i need to enable the `device_grant` flow explicitly? I didn't find an option/documentationf or that.

**Version and Deployment (please complete the following information):**
 - authentik version: ghcr.io/goauthentik/server:2023.3.1
 - Deployment: docker-compose

Any help is greatly appreciated. Thank you.

**Comment by BeryJu** [comment]
See https://goauthentik.io/docs/providers/oauth2/device_code, there needs to be a device flow configured in the tenant

**Comment by timoles** [comment]
Thanks for the reference. 

In the docs it states:

> This device flow is only possible if the active tenant has a device code flow setup

However, I couldn't find an example on how to configure the device code flow. Within the "flows" overview I also can't find the device flow. (I also couldn't find a template to manually import it as a flow.)

<img width="872" alt="image" src="https://user-images.githubusercontent.com/18122064/231115366-177d93db-55a8-49d1-a4a8-c10abccf4d61.png">

When configuring the OAuth provider I also only see two different auth flows (highlighted within the following screenshot)

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/18122064/231114007-7613d631-d592-433b-91fe-71eec30b94ba.png">

Is there some additional documentation regarding the device code flow setup, which I missed?

**Comment by BeryJu** [comment]
There's no default device code flow, you can create a new authentication flow called device-token and select that in the flow. cc @tanberry we should expand the documentation on how to configure this and that a flow needs to be created

**Comment by heoyongun** [comment]
> Thanks for the reference.
> 
> In the docs it states:
> 
> > This device flow is only possible if the active tenant has a device code flow setup
> 
> However, I couldn't find an example on how to configure the device code flow. Within the "flows" overview I also can't find the device flow. (I also couldn't find a template to manually import it as a flow.)
> 
> <img alt="image" width="872" src="https://user-images.githubusercontent.com/18122064/231115366-177d93db-55a8-49d1-a4a8-c10abccf4d61.png">
> 
> When configuring the OAuth provider I also only see two different auth flows (highlighted within the following screenshot)
> 
> <img alt="image" width="1119" src="https://user-images.githubusercontent.com/18122064/231114007-7613d631-d592-433b-91fe-71eec30b94ba.png">
> 
> Is there some additional documentation regarding the device code flow setup, which I missed?

I am struggling with the same issue.
https://github.com/goauthentik/authentik/issues/5566

The following is working
http://localhost:9000/application/o/device/

But when I do the following to get the token, I get an error.
http://localhost:9000/application/o/token/

Did you solve the problem?

**Comment by ApolloF** [comment]
You need to create a flow like this at: 
Authentik admin interface > Flows & Stages > Flows > Create

![Screenshot 2023-06-14 220958](https://github.com/goauthentik/authentik/assets/98666317/ff92d4a4-3141-498e-a345-7c719360e419)

Then go to: System > Tenants > Edit used tenant > Default flows > set Device code flow to newly created device flow

![Screenshot 2023-06-14 220838](https://github.com/goauthentik/authentik/assets/98666317/8c6234c2-2653-4913-848b-49c637101dd7)


Indeed this probably needs to be in the docs. Took me ages to figure out, but I finally found this solution on slack.

**Comment by barto95100** [comment]
It's closed but for other people have the same problem it's resolve my problem

please add this information on documentation on netbird -> authentik provider...

Maybe This will save time for users ;)

**Comment by excaliburzarau** [comment]
Hello guys. Even though i have Changed this , i AM still unable to authenticate the devices. After i try to connect to the server with the URL, it adds the peer to the netbird (appears offline).

When i press on connect, it redirects to authentik it presents as successfully logged on and it gets stuck on connecting, as seen below.

![Screenshot_20240901_174947_NetBird](https://github.com/user-attachments/assets/149e918a-b354-4318-8847-f976333d772e)

![Screenshot_20240901_175030_Chrome](https://github.com/user-attachments/assets/3ba8edcf-b368-4a31-a7aa-8d292b6d38c7)

After this, i checked the logs and it reports as not logged as seen below.

![Screenshot_20240901_175606_Termius](https://github.com/user-attachments/assets/3e5e423b-01a7-461f-a51e-08af81cf5357)

Do you guys have any ideia of why this u expected behavior is happening? 

If you could point me on the right Direction it would really help me. 

Thank you all in advance. 
Best Regards

**Comment by willdogg01** [comment]
Hello. I have precisely the same issue @excaliburzarau . Were you able to solve it?

Thanks.

**Comment by excaliburzarau** [comment]
> Hello. I have precisely the same issue @excaliburzarau . Were you able to solve it?
> 
> Thanks.

Hello. I have been around this issue for a while now. I was still unable to resolve this. I already created a thread but until now i don t have a Reply on the issue. I AM trying to fix it or have some guidance but no luck for now. Best Regards

**Comment by willdogg01** [comment]
@excaliburzarau I was able to fix my issue; for me, I adjusted my management.json file as shown here and it began working -essentially change port 10000 to 443. Hope this helps!
Before:
    "Signal": {
    "Proto": "http",
    "URI": "netbird.example.com:10000",
    "Username": "",
    "Password": null
},
After
    "Signal": {
    "Proto": "http",
    "URI": "netbird.example.com:443",
    "Username": "",
    "Password": null
},

**Comment by excaliburzarau** [comment]
> @excaliburzarau I was able to fix my issue; for me, I adjusted my management.json file as shown here and it began working -essentially change port 10000 to 443. Hope this helps! Before: "Signal": { "Proto": "http", "URI": "netbird.example.com:10000", "Username": "", "Password": null },
> 
> After: "Signal": { "Proto": "http", "URI": "netbird.example.com:443", "Username": "", "Password": null },

Hello, thank you for your Reply. I AM now having a different issue which i Will now further troubleshoot the issue but i can safelly tell you that  even though i set the ports correctly (i think), by following your advise the flow is completed and even tough i have a different issue the flow is completed. Thank you very much.
