### ISSUE TITLE
Unable to configure OIDC for Synapse

### ISSUE THREAD

**Issue by Changer90** [goauthentik/authentik#5134]
Hi everyone,

I followed the guide for synapse sso on authentik. I am currently using the latest version of authentik 2023.3.1. Unfortunately, when I try to log in using my authentik user, I receive an error
![image](https://user-images.githubusercontent.com/12458406/229148720-3c992d94-602b-48e2-9ead-9f37e7f12bfb.png)
As far as I read about it, synapse needs an RS256 signed certificate. I create a RSA Cert and set it as signing cert for my provider. Unfortunately it doesn't work. Is here someone who can help me with this? 
Synapse Log:
![image](https://user-images.githubusercontent.com/12458406/229149344-f3024faa-2243-413b-ad0b-51dd58fec237.png)
Authentik Provider:
![image](https://user-images.githubusercontent.com/12458406/229149912-0e641157-5e61-498a-9e72-30a83e6637c1.png)

Thank you everyone,
best regards changer

**Comment by Changer90** [comment]
Restarting synapse again suddenly solved the issue. Sorry for the inconvenience

**Comment by wrenix** [comment]
I got the same problem with gotosocial.
```
Unauthorized: could not verify id token: oidc: id token signed with unsupported algorithm, expected ["RS256"] got "HS256"
```

on https://authentik.example.org/application/o/gotosocial/.well-known/openid-configuration
i got also only "HS256" listed on `id_token_signing_alg_values_supported` how to enable/support more algorithmen?

**Comment by DesertCookie** [comment]
Audiobookshelf is another application that expects RS256.

![rs256](https://github.com/goauthentik/authentik/assets/17095983/a2a7e1d4-d879-4aa4-b9c2-833ad8eb3eea)
