### ISSUE TITLE
Unsupported authentication type sometimes when attempting to login

### ISSUE THREAD

**Issue by mtthidoteu** [goauthentik/authentik#5148]
**Describe the bug**
Unable to login to Authentik on a device which has previously logged in (sometimes)

**To Reproduce**
1. Go to Authentication Screen
2. Attempt to Signin
3. Error Encountered

**Expected behavior**
Login to Authentik and/or App

**Screenshots**
<img width="1149" alt="Screenshot 2023-04-03 at 11 25 28" src="https://user-images.githubusercontent.com/66959271/229483703-7908afe1-af41-44eb-a48a-4266956d4aeb.png">

**Logs**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/usr/local/lib/python3.11/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/usr/local/lib/python3.11/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/api/authentication.py", line 97, in authenticate
    user = bearer_auth(auth)
           ^^^^^^^^^^^^^^^^^
  File "/authentik/api/authentication.py", line 35, in bearer_auth
    user = auth_user_lookup(raw_header)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/api/authentication.py", line 47, in auth_user_lookup
    auth_credentials = validate_auth(raw_header)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/api/authentication.py", line 27, in validate_auth
    raise AuthenticationFailed("Unsupported authentication type")
rest_framework.exceptions.AuthenticationFailed: Unsupported authentication type
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: docker-compose.yml

**Additional context**

A Workaround is to open an incognito tab and attempt to login from there, which works. It seems to open happen on a browser which has existing cookies.

**Comment by TiFu** [comment]
In case anyone stumbles upon this as there was no hint previously: 

I had a very similar issue where the above error screen popped up when loading the authentik login screen (without being able to enter any login details). 

In my case, my browser had cached the HTTP Basic Authentication that was being used previously for the domain and submitted this when requesting the login form. This then triggered authentik to attempt to decode the header and check whether the user is logged in already; as Authentik uses Bearer Authorization this then yielded the unsupported authentication exception.

**Comment by GolemancerVekk** [comment]
I can confirm the above. I first set up access to the target app through nginx reverse proxy with HTTP Basic Auth, then inserted Authentik in between nginx and the app. This caused Authentik to receive the cached Basic Auth. Closing and reopening the browser (or deleting current logins) will fix it.
