### ISSUE TITLE
what's this question?after entering for the first time，Not Found

### ISSUE THREAD

**Issue by manduted** [goauthentik/authentik#5167]
![Snipaste_2023-04-04_20-20-47](https://user-images.githubusercontent.com/47053686/229791739-25aa1249-c7e8-4be6-adae-bed2c965502f.jpg)

Pressing the gohome button did not respond and stay at http://192.168.50.200:5005/flows/-/default/authentication/?next=/

 - authentik version: 2023.3.1
 - Deployment: Unraid docker

**Comment by manduted** [comment]
emmmmmm...I deleted the docker and redeployed it. It was the same problem at first this time, but it was fine to refresh it a few minutes later. Maybe the program is slow to load?

**Comment by ShlomiD83** [comment]
Having the same issue on a new deployment on Raspberry Pi 4.
Please assist..

**Comment by talistech** [comment]
> Having the same issue on a new deployment on Raspberry Pi 4. Please assist..

Straight from the docs:
> To start the initial setup, navigate to https://<your server's IP or hostname>:9000/if/flow/initial-setup/.

**Comment by ShlomiD83** [comment]
> > Having the same issue on a new deployment on Raspberry Pi 4. Please assist..
> 
> Straight from the docs:
> 
> > To start the initial setup, navigate to https://<your server's IP or hostname>:9000/if/flow/initial-setup/.

yeah, my bad.
My compose had a few things missing as well.
I have another issue after authenticating but I won't hijack this issue.

**Comment by antoineguilbert** [comment]
I've the same error and follow the documentation and docker compose. 
Any idea ?

**Comment by Minkiu** [comment]
Hey there,

just to add, I am facing the same issue with `2023.5.3` (and `docker-compose`) where when I attempt to go through the initial setup flow, I'm greeted with Not Found.

Opening the DevTools, I can see the following error:
```
GET
https://<hostname>/if/flow/initial-setup/
[HTTP/1.1 404 Not Found 99ms]
```

And a Javascript error:
```
Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    <anonymous> https://auth.tiphar.es/if/flow/initial-setup/:23
initial-setup:23:22
    <anonymous> https://auth.tiphar.es/if/flow/initial-setup/:23
```

Looking into it, it fails at parsing the JSON here:
```js
window.authentik = {
        locale: "en-us",
        config: JSON.parse(''), // <--- Here
        tenant: JSON.parse(''), // And I assume it would fail here as well..
        versionFamily: "",
        versionSubdomain: "",
        build: "",
    };
```

So I located this in the templates: https://github.com/goauthentik/authentik/blob/f099bd764e247efa761fdd65b51045cfd741e561/authentik/core/templates/base/header_js.html#L7

My assumption, that at some point, when that template is used, neither `{{ config_json|escapejs }}` nor `'{{ tenant_json|escapejs }}'` get replaced to a valid JSON value,  I didn't dig further, but where does the `config_json` object gets built? Unsure if passing an empty `{}` would help at all.

Let me know if you rather me opening a new issue.

Cheers!

**Comment by LachlanNewman** [comment]
Did anyone figure out this issue ?

**Comment by Minkiu** [comment]
Hey! So after searching in their discord, I was lead to look at the Worker container logs, so check the logs there, if the worker can't launch it won't make you go through the first time setup.

In my instance, the worker environment was missing the `AUTHENTIK_SECRET_KEY` , which mind you, it's not there in the `docker-compose.yml` that you download form the docs.

**Comment by husos** [comment]
@Minkiu In my case you solve my problem... I'm using Docker Unraid and i don't know how but my Authentik and Authentik-Worker had different AUTHENTIK_SECRET_KEY. I've updated them and reboot now working. 

Thanks!

**Comment by billettg** [comment]
I could never get this initial setup to work despite triple checking documentation, trying completely vanilla installation after purging all previous data, no special characters in any passwords or secrets etc etc. The workflow is clearly broken for initial setup using Docker.

For the benefit of others a simple way to work around the issue is to add to your .env file:

AUTHENTIK_BOOTSTRAP_PASSWORD=akadmin
AUTHENTIK_BOOTSTRAP_EMAIL=akadmin@example.com

Restart the authentik-server container, and login with the provided credentials.

**Comment by raulcnadal** [comment]
Hey there!,

The issue seems to be happening when you pass AUTHENTIK_PORT_HTTP and AUTHENTIK_PORT_HTTPS instead of new variables COMPOSE_PORT_HTTP and COMPOSE_PORT_HTTPS.

If you use new and rebuild, you can perform initial admin password set using http as intended.

I've seen several posts still referencing old Environment Variables, hence the issue.

Hope this can help,

**Comment by bastianhilton** [comment]
for those still experiencing this issue, follow this doc here for Docker: https://docs.goauthentik.io/docs/installation/docker-compose and this one for bootstrapping https://docs.goauthentik.io/docs/installation/automated-install.

Also make sure that the worker has the same credentials as the server or you will receive the not found error.

**Comment by danielrumata** [comment]
I faced the same problem so I tried the [automated install](https://docs.goauthentik.io/docs/installation/automated-install), but it only works over https.
