### ISSUE TITLE
bulk delete all Users from User path

### ISSUE THREAD

**Issue by x4x** [goauthentik/authentik#5185]
**is there a way to bulk delete all Users from a specific User path?**
I was trying to import users from a LDAP source and now have about 4000 users witch i want to delete again.

**Comment by Profecy** [comment]
**DESPERATELY** needed !! I have the same issue!

**Comment by timoschwarzer** [comment]
```sql
DELETE FROM authentik_core_user WHERE path = 'goauthentik.io/sources/my-ldap-source';
```

**Comment by phauch** [comment]
@timoschwarzer Is this the recommended way to (bulk) delete users or has this method any unwanted side-effects?

**Comment by timoschwarzer** [comment]
@phauch I didn't notice any side effects but I can't tell you whether this is 100% safe to do or messes something up. A feature on application level would be the cleaner and safer solution but it doesn't exist yet.

**Comment by rissson** [comment]
You definitely shouldn't delete users from postgresql directly.

You can either write a script to do this with the API, or run `ak shell` and do:

```
User.objects.filter(path="mypath").delete()
```

**Comment by phauch** [comment]
I wasn't aware of the existence of the `ak shell` CLI command, a tool capable of handling such tasks. Is there any documentation available for it? Despite a quick search, I couldn't find any references.

**Comment by rissson** [comment]
It's a Django shell, you can basically write the code you want in there

**Comment by rissson** [comment]
> Thanks @rissson I had no idea that this tool was available.

We don't advertise it because it's easy to shoot yourself in the foot. The best way still is to use the API

**Comment by PaulBunkey** [comment]
I've gathered all the above to make a coherent answer to the question: How do delete all users (except system ones):
If you're running the Authentik the recommended way then your compose.yaml probably calls the main Authentik container "server".
If so, the command to run `ak shell` is:
```
cd /<your Authentick's compose.yaml folder>
docker compose exec server ak shell
```
then you list all Authentik users with their path, so you can identify right path prefix (folder) you wan to delete users in:
```
for u in User.objects.filter(path__startswith=""): print (f"{u.path} - {u.username}")
```
before you are ready to delete unwanted users with appropriate path prefix (in my example: `goauthentik.io/sources/myldap`), print them:
```
for u in User.objects.filter(path__startswith="goauthentik.io/sources/myldap"): print (f"{u.path} - {u.username}")
```
now you can delete selected users:
```
User.objects.filter(path__startswith="goauthentik.io/sources/myldap").delete()
```
