### ISSUE TITLE
Update stage binding window missing stage

### ISSUE THREAD

**Issue by electrofloat** [goauthentik/authentik#5210]
**Describe the bug**
When in flow->stage bindings->clicking on Edit Binding the window that appears missing the Stage set in the first entry.
Also sometimes a "Target" entry appears as a first entry in that window, that quickly disappers.
See attached file.

**To Reproduce**
1. Go to Flow & Stages
2. Click on Flows
3. Click on a flow
4. Click on stage bindings
5. Click on Edit Binding next to a stage

**Expected behavior**
The stage entry is correctly filled every time the Edit Binding button is clicked, and also the mistery "Target" entry does not appear.

**Screenshots**

https://user-images.githubusercontent.com/477252/230775122-ca3f880c-a4e2-416b-86f5-acc053bea5ce.mp4

(Note that I'm pressing escape every time the window appears and then clicking on Edit Binding)

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3.1
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
This is (should be) fixed in 2023.4, which will be released next week
