### ISSUE TITLE
Improve API docs by showing the HTTP method in the sidebar

### ISSUE THREAD

**Issue by nogweii** [goauthentik/authentik#5214]
**Is your feature request related to a problem? Please describe.**
Browsing the API docs by the sidebar is really difficult, as it's hard to tell the difference between different routes with the same path but differentiated by the HTTP method. (I think that's the proper way to design the API though.)

![image](https://user-images.githubusercontent.com/14547/230793610-edfb001b-c2be-4996-b569-601b29ea2e82.png)

**Describe the solution you'd like**
Add the HTML attribute `show-method-in-nav-bar` to the RapiDoc top element. There are three possible options:

* `as-plain-text`: 
![image](https://user-images.githubusercontent.com/14547/230793714-75fd596a-cf99-4dc2-a329-e9287b47538c.png)

* `as-colored-block`:
![image](https://user-images.githubusercontent.com/14547/230793739-69bd7933-6672-4f96-9234-7287500d53a9.png)

* `as-colored-text`:
![image](https://user-images.githubusercontent.com/14547/230793749-14726a88-a5e5-48b5-bdb2-8780b0eeead7.png)

My personal preference would be for `as-colored-text`.

**Describe alternatives you've considered**
Clicking multiple times to each entry to find the right one.

You can also edit the DOM live to preview these yourself; Press F12 and then add the attribute to the `<rapi-doc>` element.

**Comment by BeryJu** [comment]
I agree with `as-colored-text` making the most sense, feel free to PR this if you want to!
