### ISSUE TITLE
Allow Setting Additional Parameters on OAuth URLs

### ISSUE THREAD

**Issue by lanrat** [goauthentik/authentik#5232]
**Is your feature request related to a problem? Please describe.**

If OAuth login is restricted to a single domain, the OAuth login prompt should pre-populate that domain to make it clear only accounts within the domain are allowed.

**Describe the solution you'd like**

Some OAuth providers, like Google's have additional query string parameters that can be set to pre-populate parts of the login form, like the domain. In Google's case, adding `hd=example.com` to the redirect authorization URL will pre-populate the login form with the domain provided.

Note: this is not strongly enforced and not a security control. This is an ease-of-use enhancement and makes it clearer to the user that they should use an account within the provided domain to login.

I am proposing that there be a provider agnostic way to add or override the URL parameters for OAuth providers so that additional parameters such as `hd` or `login_hint` can be used.

Alternatively a per-provider option could be added that can manually set these settings if the provider supports it.

**Describe alternatives you've considered**

NA

**Additional context**
This is what the Google OAuth login form would look like with `hd=example.com` added to the querystring:
<img width="572" alt="Screenshot 2023-04-12 at 11 25 37 AM" src="https://user-images.githubusercontent.com/164192/231550656-cd9dd1b5-f245-42ec-9ad8-b96f2ebb1df1.png">

**Comment by lanrat** [comment]
Additionally for Google OAuth:

If the user is signed into multiple Google accounts, with only 1 belonging to the allowed domain, setting the `hd` option skips the Google Account chooser and automatically used the correct account.

**Comment by tschoesi** [comment]
I also believe that being able to add for example `login_hint` to prepopulate the username would be very handy.

**Comment by BeryJu** [comment]
With https://github.com/goauthentik/authentik/commit/4c9878313ccb00e0db034d3b7af99c8fee82b645 this should by possible by including those additional parameters in the authorization URL configured in authentik

**Comment by marcportabellaclotet-mt** [comment]
I would like to have this feature as well. Although additional parameters can be included in the authorization URL, only static parameters are currently supported.

In my use case, I need a standard Authentik login where the user is prompted for their username or email. A policy would then check the domain of the username and, based on that, either redirect to Google SSO or use the local database. However, with static parameters, I cannot set the login_hint dynamically, as it should be the email entered in the initial Authentik form.
