### ISSUE TITLE
After upgrade from 2023.3 to 2023.4 worker container is unhealthy

### ISSUE THREAD

**Issue by ovizii** [goauthentik/authentik#5258]
**Describe the bug**
After upgrade from 2023.3 to 2023.4 worker container goes from starting to unhealthy. No errors to be found at a glance in the logs.

**To Reproduce**
Steps to reproduce the behaviour:
1. docker-compose up -d
2. Wait for the worker container to finish the "starting up" phase
3. Check and see it being reported as unhealthy

**Expected behavior**
A healthy container.

**Screenshots**
![image](https://user-images.githubusercontent.com/837902/232036573-01c204eb-3283-4f1f-912f-11a7920a618b.png)

**Logs**
Logs show no error, do you still want them?

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.4
 - Deployment: docker-compose

**Additional context**
Switching back to 2023.3 and all containers show as healthy again. Btw. even in the unhealthy state with 2023.4 everything seemed to be working. I logged in as administrator and all system tasks were green, no problems to eb found.

**Comment by BeryJu** [comment]
Feel free to install the beta version https://goauthentik.io/docs/installation/beta
