### ISSUE TITLE
Reduce Attack Surface for APIs: Make SELECTIVE sensitive APIs Private while keep the project specific requirement public. Is there a toggle button for each API which can make them unexposed in the Swagger documentation and otherwise for a given usecase. (Self hosted on K8s)

### ISSUE THREAD

**Issue by sagungargs15** [goauthentik/authentik#5275]
**Describe your question/**
How can I make selective APIs private and switched off inaccessible from Swagger Docs and Keep handful usable ones public that eventually get used by the project in Production 

**Relevant infos**
Latest version installed on K8s

**Comment by BeryJu** [comment]
Not possible with authentik itself, the schema is public (see https://goauthentik.io/developer-docs/api/browser)

You could selectively block requests to some API endpoints with a reverse proxy, but the admin interface and the outposts use most of all APIs. Also all API endpoints have the same authentication logic

**Comment by sagungargs15** [comment]
Thanks for this input @BeryJu
