### ISSUE TITLE
Azure AD Social login not working

### ISSUE THREAD

**Issue by stefanelul2000** [goauthentik/authentik#5288]
I have setup login via Azure AD with the help of the provided documentaion.

However I am experiencing issues when performing authentication and I am not sure what the issue is here. Permissions are granted to the application in Azure AD.

```
warning undefined | auth_via=unauthenticated event=Unable to fetch access token exc=HTTPError('400 Client Error: Bad Request for url: https://login.microsoftonline.com/<redacted>/oauth2/v2.0/token') host=auth.internal.domain.com logger=authentik.sources.oauth.clients.oauth2 pid=25 request_id=66edf10e341849a593db08cf5bb3f3fc response=400 Client Error: Bad Request for url: https://login.microsoftonline.com/<redacted>/oauth2/v2.0/token timestamp=2023-04-18T10:00:31.555144 
warning undefined | auth_via=unauthenticated event=Authentication Failure host=auth.internal.domain.com logger=authentik.sources.oauth.views.callback pid=25 reason=Could not retrieve token. request_id=66edf10e341849a593db08cf5bb3f3fc timestamp=2023-04-18T10:00:31.555828
```

**Comment by vherrlein** [comment]
Ensure the following from your Azure App:
1. Grant admin consent to all permissions, it should looks like the following:
![image](https://user-images.githubusercontent.com/24614045/233036072-ef95428b-37f6-41d8-a437-b71276ac567b.png)
2. Ensure redirect URI is well defined, eg:
![image](https://user-images.githubusercontent.com/24614045/233036524-692f2664-f2ff-4c65-a445-fc7bcefbec03.png)
3. Front-channel logout URL is well defined, eg:
![image](https://user-images.githubusercontent.com/24614045/233036759-acd31d75-8e94-48f2-9225-0fc082549af9.png)
4. Ensure token configuration contains required properties:
  - aud
  - email
  - given_name
eg: 
![image](https://user-images.githubusercontent.com/24614045/233037899-f9918091-76ad-45f0-ae4d-7c96ece989fe.png)

**Comment by wearethedynamite** [comment]
Sorry to hijack this thread - I'm receiving this exact same error, I have gone through and verified my setup matches the screenshots provided but still unable to retrieve authentication token. 
Probably missing something obvious, but I've been pulling my hair out for two days!

**Comment by vherrlein** [comment]
Another check, within your Azure App Manifest, look at the settings:
- signinAudience => AzureADMyOrg
- logOutUrl => https://yourauthentik.fqdn.com/flows/~/default/invalidation/

another point, make sure within the the login screen your are using the correct user account registered within the tenant of your Azure App.

**Comment by wearethedynamite** [comment]
Manifest reflects those values correctly, User acc is correct, the sign in logs for the app in Azure even suggests a successful login...

![image](https://user-images.githubusercontent.com/79176174/233491831-912ad78d-44b6-4a76-ac90-f55eba8ab6e8.png)

Very much a head scratcher!

**Comment by wearethedynamite** [comment]
So it looks like it's an issue with authorisation, but I'm not sure why. Account is a global admin in azure.
Set all permissions according to the documentation and as outlined in this thread and i'm still getting this error.


```
{"auth_via": "unauthenticated", "event": "Unable to fetch access token", "exc": "HTTPError('401 Client Error: Unauthorized for url: https://login.microsoftonline.com/*tenant ID*/oauth2/v2.0/token')", "host": "auth.*domain*.com", "level": "warning", "logger": "authentik.sources.oauth.clients.oauth2", "pid": 27639, "request_id": "63a77fcbf6b84c6686bc77543ed6709f", "response": "401 Client Error: Unauthorized for url: https://login.microsoftonline.com/*Tenant ID*/oauth2/v2.0/token", "timestamp": "2023-04-21T12:03:35.460923"}
{"auth_via": "unauthenticated", "event": "Authentication Failure", "host": "auth.*domain*.com", "level": "warning", "logger": "authentik.sources.oauth.views.callback", "pid": 27639, "reason": "Could not retrieve token.", "request_id": "63a77fcbf6b84c6686bc77543ed6709f", "timestamp": "2023-04-21T12:03:35.461261"}
``` `

**Comment by vherrlein** [comment]
@wearethedynamite the first screen is showing your account is well authenticated which makes sense because that the first redirection. 

cf : https://learn.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-openid-connect-code#authentication-flow-using-openid-connect

According to logs on your second message, it's an access denied message received when Authentik requests the authorization_code to Azure.
So, check non-interactive logs:
1. Go to AZ Portal > Azure AD > Enterprise Application > Authentik (Your AZ App) > Sign-in Logs
2. Open "User sign-in (non-interactive)" tab
3. Find log lines with a failure status

From a failure log record, you will be able to see the reason like Conditional Access, Wrong secret, ...

**Comment by vherrlein** [comment]
I think you copied pasted the secret id instead of the secret value.
Good for you.
