### ISSUE TITLE
Contradicting docs for HTTP and HTTPS port environment variables

### ISSUE THREAD

**Issue by Bojan023** [goauthentik/authentik#5291]
The docker-compose installation instructions mention the following variables to put in a `.env`:

https://github.com/goauthentik/authentik/blob/f44175303bd376a30b505e41ddd449b1302ba225/website/docs/installation/docker-compose.md?plain=1#L66-L67

However, the configuration page mentions "These are all the configuration options you can set via environment variables":

https://github.com/goauthentik/authentik/blob/f44175303bd376a30b505e41ddd449b1302ba225/website/docs/installation/configuration.md?plain=1#L54-L55

It took me a while to figure out that the `AUTHENTIK_PORT_` variables concern the EXTERNAL ports mapping of Docker on the host machine, while the `AUTHENTIK_LISTEN__` variables affect the INTERNAL container ports. 

My confusion comes from the following: in the docker-compose instructions, after creating a fresh `.env` the suggestion is made to optionally configure e-mail. These variables are INTERNAL variables, following the same naming scheme as `AUTHENTIK_LISTEN__`. Directly after that, comes the suggestion that `AUTHENTIK_PORT_` alters the default configuration which I interpret as INTERNAL ports given the current clarification and context.

My suggestion is to rename the `AUTHENTIK_PORT_` to something like `AUTHENTIK_EXTERNAL_PORT_` and to clarify that this variable changes the EXTERNAL mapping or EXPOSED port. Because that is what this variable actually changes: the mapping. Not the default listening port (that is controlled by the `AUTHENTIK_LISTEN__` variables).

**Comment by BeryJu** [comment]
Good point, it might be even clearer to use a prefix like `COMPOSE_PORT_` instead of the same prefix as the config itself uses

**Comment by Bojan023** [comment]
Just made a PR: https://github.com/goauthentik/authentik/pull/5292
