### ISSUE TITLE
Outpost Integrations fails to load

### ISSUE THREAD

**Issue by justsomemate** [goauthentik/authentik#5299]
**Describe the bug**
Outpost Integrations page shows the spinner and says Loading

**To Reproduce**
1. Log into admin interface
2. Click on System > Outpost Integrations

**Expected behavior**
Outpost integrations load.

**Screenshots**
![image](https://user-images.githubusercontent.com/80608392/232823402-28f6480b-4ab8-48e3-b2bc-4fcf1348b339.png)

**Logs**
[authentik-logs.txt](https://github.com/goauthentik/authentik/files/11263892/authentik-logs.txt)

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.4.0, 2023.4.1
 - Deployment: docker compose

**Additional context**
Behavior is seen on both an upgrade from 2023.3.1 and a clean install.
Log is from a fresh install.

**Comment by benedikt-bartscher** [comment]
Same issue with authentik 2023.4.1 deployed via helm on k8
