### ISSUE TITLE
Duplicate blueprints when providing blueprints via ConfigMap in helm chart

### ISSUE THREAD

**Issue by cskwrd** [goauthentik/authentik#5301]
**Describe the bug**
Blueprints sourced from a ConfigMap are duplicated in the web UI's blueprint list.

**To Reproduce**
1. Deploy authentik helm chart with a blueprint ConfigMap.
2. After deployment finishes, navigate to the list of blueprints in the admin interface.
3. Find the blueprint(s) sourced from the ConfigMap in step 1.
4. Notice multiple entries. Expand details and notice path.

**Expected behavior**
1 entry per blueprint in ConfigMap.

**Screenshots**
`-`

**Logs**
`-`

**Version and Deployment (please complete the following information):**
 - authentik version: `2023.4.1`
 - Deployment: `helm`

**Additional context**
It appears as though authentik doesn't account for symlinks with respect to ConfigMap resources in k8s. k8s uses symlinks to support auto update functionality for data in ConfigMap resources without the need to restart the pod. For each YAML blueprint definition in a ConfigMap resource, authentik discovers `2 + <number of updates to the original ConfigMap data>` blueprints.

**Comment by BeryJu** [comment]
fixed by https://github.com/goauthentik/authentik/pull/5472
