### ISSUE TITLE
Update Gitlab Integration Documentation With Warnings About User Impersonation

### ISSUE THREAD

**Issue by ReaHe** [goauthentik/authentik#5312]
**Is your feature request related to a problem? Please describe.**
It was found and discussed in https://discord.com/channels/809154715984199690/937086250924531812/1096423065539317820
that the current gitlab documentation found at https://goauthentik.io/integrations/services/gitlab/ for gitlab integration with SAML opens the owners gitlab up to user impersonation if Authentik is not correctly configured.

For example on users first login to gitlab if the user is not already linked to said gitlab, this allows the user to link to any user in which they have the email address set for. So if a Authentik configuration allows for the user to change their email address, as long as that user has yet to login to the gitlab for the first time, they can impersonate any other user in the gitlab. The implications of this are far  less worse if the gitlab relys on SAML for RBAC however if gitlab uses RBAC through hard coded access controls in gitlab or through another external source like LDAP, then the linked SAML user will gain said rights or accesses.

**Describe the solution you'd like**
Place a warning at the top of the gitlab integration page that mentions something along the lines of "for the best security, make sure to disable UID and Email Address changes done by the user to prevent impersonation as other users.".

**Describe alternatives you've considered**
I find it strange this kinda concept is not more published on the Authentik docs in general. On the configuration page a warning should also exist at the top https://goauthentik.io/docs/installation/configuration#authentik_default_user_change_email discussing that "leaving email and uid changes by the user allows for impersonation attempts against apps that use Authentik.". This seems like an important security concept that waltz over.

**Additional context**
N/A

**Comment by BeryJu** [comment]
From looking through the integration docs, it seems that gitlab was the only one that relied on the email as a UID. However I do think it makes sense to enable the flags to prevent username/email change by default, see #5312. Feel free to re-open this if you don't think thats adequate
