### ISSUE TITLE
LDAP source when using 2FA is broken in 2023.4.1 

### ISSUE THREAD

**Issue by Nayruden** [goauthentik/authentik#5313]
**Describe the bug**
Unable to authenticate using a federated LDAP source with Authentik when using 2FA. This is a new bug to 2023.4.1 and possibly 2023.4.0.

**To Reproduce**
1. Run an external LDAP service capable of 2FA. I'm using FreeIPA.
2. Connect Authentik to LDAP server (via Directory->Federation & Social Login)
3. Observe that federated users cannot connect using 2FA, but federated users with only password-based authentication sitll work

**Additional context**
2FA from an LDAP source is working in Authentik 2023.3.1, but not 2023.4.1 -- even though all other configurations stayed the same. I rolled back to version 2023.3.1 and authentication immediately worked again.

**Comment by Nayruden** [comment]
This is still a problem

**Comment by BeryJu** [comment]
I'm not quite sure what you mean with 2FA in this case, 2FA coming from the LDAP Source (assuming adding ;123456 to a password for the TOTP code?) or 2FA from authentik?

**Comment by Nayruden** [comment]
Did specifying 2FA to the upstream change as well?

Our users are registered in FreeIPA, so Authentik is not managing the users or passwords. However, FreeIPA is configured to require 2FA for all logins.

We also have Authentik configured to use FreeIPA as a federated source of user accounts (over LDAP). This is currently working great on an older version of Authentik. When we log in to Authentik, we specify our username, then the password as "<static password><OTP>" -- the two factors are concatenated together at the Authentik password prompt. That no longer works on newer versions of Authentik. Are you saying we need to do "<static password>;<OTP>" now? If so, does that cause any problems if the password itself contains `;`?
