### ISSUE TITLE
Support non-default Redis username

### ISSUE THREAD

**Issue by bardiharborow** [goauthentik/authentik#5348]
When using Redis >6 with [ACLs](https://redis.io/docs/management/security/acl/) enabled, Redis may [require a username to authenticate with the server](https://redis.io/commands/auth/). The Authentik configuration does not provide a setting to specify this username.

Authentik should support a `AUTHENTIK_REDIS__USER` environment variable to configure the username passed to Redis.

**Comment by lstellway** [comment]
I agree ☝️ 
I am also missing the ability to specify a trusted self-signed certificate authority. 

From what I've found:
- The project uses [redis-py](https://redis-py.readthedocs.io/)
  - There's an [example using login credentials](https://redis-py.readthedocs.io/en/stable/examples/connection_examples.html#Connecting-to-a-redis-instance,-specifying-a-host-and-port-with-credentials.)
  - There's a good example of [specifying a self-signed CA](https://redis-py.readthedocs.io/en/stable/examples/ssl_connection_examples.html#Connecting-to-a-Redis-instance-via-SSL,-while-specifying-a-self-signed-SSL-certificate.)

The Python portion for Redis looks to be implemented in two places:
- [/lifecycle/wait_for_db.py](https://github.com/goauthentik/authentik/blob/2fb8d4b410660081a65d0490c40274a2ca7ad9b1/lifecycle/wait_for_db.py#L44C1-L54)
- [/root/settings.py](https://github.com/goauthentik/authentik/blob/2fb8d4b410660081a65d0490c40274a2ca7ad9b1/authentik/root/settings.py#L185-L194)

The configuration object looks to be defined as a Go struct:
- [/internal/config/struct.go](https://github.com/goauthentik/authentik/blob/2fb8d4b410660081a65d0490c40274a2ca7ad9b1/internal/config/struct.go#L27-L38)
