### ISSUE TITLE
Certificate expiry date is green even after it has passed

### ISSUE THREAD

**Issue by danaelg** [goauthentik/authentik#5351]
**Describe the bug**
The expiry date of the certificates is green even after it has passed

**To Reproduce**

1. Go to 'System' -> 'Certificate'
2. Wait for expiration of an already existing one
3. See 'expiry date' is still green

**Expected behavior**
To me, the expiry date should be red when it has passed. We could imagine having it yellow when the expiry date is closed (30 to 60 days before expiration) - but it's out of the scope of a bug report. 

**Screenshots**
On the screenshot bellow, you can see that the last two certificates have expired
![image](https://user-images.githubusercontent.com/7955413/233832414-7f662459-43eb-4e21-ad07-7691ce8dca3b.png)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
Oops yeah that's a bug, don't know how that logic error got in there https://github.com/goauthentik/authentik/blob/main/web/src/admin/crypto/CertificateKeyPairListPage.ts#L105
