### ISSUE TITLE
Forward auth (domain level) throws error

### ISSUE THREAD

**Issue by premar** [goauthentik/authentik#5364]
**Describe the bug**
Straight forward I want to use the Proxy Provider with multiple apps.

Domain: example.com
Authentik: auth.example.com
Apps: app1.service.example.com, app2.service.example.com, ...

**To Reproduce**

1. Create a new provider: Proxy Provider
2. Select: Forward auth (domain level)
3. Authentication URL: auth.example.com
4. Cookie domain: service.example.com

After click update I receive a red error message with no content. Authentication URL gives error message "Enter a valid URL". The network analyzer on https://auth.example.ch/api/v3/providers/proxy/6/  throws a 400 code.

If the I change the Authentication URL: http://auth.example.com or https://auth.example.com the form can be saved. But then I cannot access the apps. The login mask from authentik is showing up, and after the login I end up at auth.example.com.

Furthermore the automatically generate config looks strange:
```
(...)
 location /outpost.goauthentik.io {
        proxy_pass              http://http://auth.example.ch//outpost.goauthentik.io;
(...)
```
That should be http://auth.example.ch/outpost.goauthentik.io, or I am wrong?

**Expected behavior**
Can setup the proxy config. And later login to app1.service.example.com, app2.service.example.com, ...

**Screenshots**
![image](https://user-images.githubusercontent.com/4980874/234049926-c86910b0-d337-4c5f-8f2e-94dcaaf84001.png)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Additional context**
Love what you do with authentik, keep the good work up!

**Comment by BeryJu** [comment]
The authentication URL should be set to a full URL, the generated config is a bit finicky so for the time being ignore that double http://

The reason you're being redirected back to auth.domain.tld is because the `proxy_pass` in nginx shouldn't be set to the public domain, but rather to the internal Hostname of IP of the authentik server

**Comment by premar** [comment]
I am using a vanilla nginx as reverse proxy in front of my apps + authentik.

I changed the `proxy_pass` for my setup. Sorry, that was not clear our my statement from above. I copied the recommended configuration from authentik and changed the `proxy_pass`:

```
(...)
 location /outpost.goauthentik.io {
        proxy_pass              http://internal.server.local:9000/outpost.goauthentik.io;
(...)
```

I'll delete the config again. And setup it from scratch to check if that change something.

**Comment by premar** [comment]
Unfortunately the same behaviour after new setup. The login page pops up and after the login I end up at the library on https://auth.example.com.

Steps to reproduce the behavior:

1. Create a new provider: Proxy Provider
2. Select: Forward auth (domain level)
3. Authentication URL: https://auth.example.com
4. Cookie domain: service.example.com
5. Other settings are default
6. Add Application with name + provider
7. Enable on embedded outpost
8. Setup proxy config for host app1.service.example.com

Open https://app1.service.example.com -> Login Page -> Login with credentials -> redirects to https://auth.example.com.

For the nginx server I use the template and change only the `proxy_pass` portion:

```
proxy_pass http://server.example.local:9000/outpost.goauthentik.io;
```

When I setup the provider with Forward auth (single application) and set the external host to https://app1.service.example.com its working with the single application.

Is there perhaps a problem that I use a second subdomain for the cookie domain `*.service.example.com`? Can I provide any logs or debug the login with redirect?

**Comment by fbartels** [comment]
> Cookie domain: service.example.com

According to the documentation this needs to be example.com, since your authentik is running at auth.example.com.

**Comment by premar** [comment]
Okay, it was the subdomain. I recreated the scenario without the subdomain. In this configuration the login works with forwarding:

Domain: example.com
Authentik: auth.example.com
Apps: app1.example.com, app2.example.com, ...

That means at the moment there is a limiting factor that the cookie domain cannot be a subdomain of the authentik domain. I'll would say I can live with that limitation and create a provider for each app in the subdomain.

Also I'll close the the issue:

1. @BeryJu already handled the error message that was confusing me.
2. As @fbartels stated the domain should be the same as the authentik instance. So in the end it was more or less my mistake.
3. So that was not really a bug -> More a feature.

Perhaps a short hint in the documentation would be nice. What you think?

**Comment by ChenWenBrian** [comment]
I have the same issue, I’m curious why subdomains are not supported?

**Comment by schnillerman** [comment]
This error persists ... I have
- provider
  - provider type: domain level forward auth
  - auth. URL: `https://auth.domain.tld`
  - cookie domain: `domain.tld`
- outpost: the embedded standard outpost (automatically created during initial setup)

In my Nginx rev. proxy app settings, in advanced:
`proxy_pass              http://192.168.1.11:11425/outpost.goauthentik.io;`

App is at `app.domain.tld`.

If I switch from domain level to single application forward auth, it works, but domain level forward auth always throws me back to `auth.domain.tld` after authentication (which itself works fine).

Fun fact: I have a Synology SSO server as OpenID provider for Authentik (see [here](https://github.com/schnillerman/nginx-authentik-oidc-SSO-docker/blob/main/README.md). And it seems that during the authentication, the "app" part of the URL I'm trying to reach (app.domain.tld) is not preserved during authentication.
