### ISSUE TITLE
Login via SAML IDP

### ISSUE THREAD

**Issue by boesr** [goauthentik/authentik#5401]
**Describe your question/**
As far as I understand the SAML source it is possible to define Authentik as the SP for an IDP. I just setup and IDP. I created a SAML Source and entered the SSO URL. I also defined the entity id of the Authentic source within my IDP configuration. Now if I try to login via the login screen, I cannot use the user data defined in my IDP. Is that possible or did I miss something?

**Relevant infos**
- tested with own IDP: https://hub.docker.com/r/kristophjunge/test-saml-idp/

**Screenshots**
/

**Logs**
/

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Additional context**
/

**Comment by BeryJu** [comment]
We use the same docker image for SAML Source testing, you can see the settings here: https://github.com/goauthentik/authentik/blob/01663468de370c369c21f4209a259d3a6027f993/tests/e2e/test_source_saml.py#L107

**Comment by boesr** [comment]
Thanks, it seems like my configuration. With wich parameters did you start die docker container?

Should the authentik web ui then redirect to the simple saml ui as soon as I enter the saml account (e.g. user1)?

**Comment by BeryJu** [comment]
These are the parameters for the container https://github.com/goauthentik/authentik/blob/01663468de370c369c21f4209a259d3a6027f993/tests/e2e/test_source_saml.py#L90

To login via SAML, you need to edit the Identification stage under Flows -> Stages and select the SAML source, then it will show up as an option on the login screen

**Comment by boesr** [comment]
Thanks @BeryJu. This has given me clarity. I was missing the Stage configuration.
