### ISSUE TITLE
default-authentication-flow should ignore the password stage if "Password stage" is selected in default-authentication-identification

### ISSUE THREAD

**Issue by fuomag9** [goauthentik/authentik#5407]
**Describe the bug**
`default-authentication-flow` should ignore the password stage if the "Password stage" option is selected in `default-authentication-identification`. Currently this does not happen, so if authentik is configured to show username and password in the same flow, the user will have to input the password twice, unless the `default-authentication-password` stage is deleted from the flow. This is a problem as the flow is reset when updating authentik, and a custom flow should not be the solution to this issue as this is a default configuration and should work as it is. Furthermore, not using a default flow can lead to security issues as it will miss flow updates.

**To Reproduce**
Configure the `default-authentication-flow` like this

![image](https://user-images.githubusercontent.com/1580624/235132501-3df65796-a801-418a-9c6c-60401420bee2.png)

Try to login with username and password
![image](https://user-images.githubusercontent.com/1580624/235132850-80ce7307-5cdd-465e-b559-4f22d16d9faa.png)

The password will be asked again:

![image](https://user-images.githubusercontent.com/1580624/235132687-40930d50-0b75-4caa-ae42-f1eb3d829238.png)

**Expected behavior**
I should not have to input my password twice
**Screenshots**
See above
**Logs**
None relevant
**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Additional context**

**Comment by mescobarcl** [comment]
I have the same issue in the last version; I must enter my credentials two times. I tested older versions, and at least 2 versions before had the same issue. In my case, I have configured it with an OpenId provider.

**Comment by fuomag9** [comment]
> I have the same issue in the last version; I must enter my credentials two times. I tested older versions, and at least 2 versions before had the same issue. In my case, I have configured it with an OpenId provider.

Yes, this has been happening for a while. I was using a custom flow to fix in the last few months this because I thought I had misconfigured something, but it wasn't actually me

**Comment by mescobarcl** [comment]
> > I have the same issue in the last version; I must enter my credentials two times. I tested older versions, and at least 2 versions before had the same issue. In my case, I have configured it with an OpenId provider.
> 
> Yes, this has been happening for a while. I was using a custom flow to fix in the last few months this because I thought I had misconfigured something, but it wasn't actually me causing this

Can you share how to do that flow?

**Comment by Akruidenberg** [comment]
Whats the progress of this fix. Since the last versions i have this problem also. Asking for my paswword and totp twice. Very annoying.

**Comment by Akruidenberg** [comment]
Will test this when new version is released.
