### ISSUE TITLE
"Invalid provider type ak-provider-radius-form" when creating a RADIUS outpost

### ISSUE THREAD

**Issue by kapsikkum** [goauthentik/authentik#5429]
**Describe the bug**
RADIUS provider/applications don't work. Trying to view a provider that is assigned to a RADIUS outpost will result in a "Invalid provider type ak-provider-radius-form" error.

**To Reproduce**

1. Create a RADIUS Provider
2. Create a RADIUS Application
3. Assign Application to provider
4. Create RADIUS outpost
5. Add Provider to outpost
6. Viewing the Provider shows the error.

**Expected behavior**
RADIUS to work, and being able to view the Provider information.

**Screenshots**
![image](https://user-images.githubusercontent.com/52489043/235386764-ba342c29-8adf-4efd-8581-bcb5a8cd0dcd.png)
![image](https://user-images.githubusercontent.com/52489043/235386927-ace25686-5173-4648-87ab-e2e4951e0509.png)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Additional context**

**Comment by Svenum** [comment]
Same Issue here.
