### ISSUE TITLE
Unable to create new login stage

### ISSUE THREAD

**Issue by yananet** [goauthentik/authentik#5453]
**Describe the bug**
Unable to create new login stage

**To Reproduce**
1. Go to 'Flow & Stages -> Stages'
2. Click on 'Create'
3. Select 'User Login Stage'
4. Click on 'Next'
5. Set a name as 'temp-login'
6. Click on 'Finish'
7. Find the console error

**Expected behavior**
User stage is created

**Screenshots**
N/A

**Logs**

```
postgresql-authentik         | 2023-05-03 00:11:50.514 UTC [280] ERROR:  null value in column "remember_me_offset" violates not-null constraint
postgresql-authentik         | 2023-05-03 00:11:50.514 UTC [280] DETAIL:  Failing row contains (509c102f-da3c-40f8-bbe1-df5cf5ae6619, seconds=0, f, null).
postgresql-authentik         | 2023-05-03 00:11:50.514 UTC [280] STATEMENT:  INSERT INTO "authentik_stages_user_login_userloginstage" ("stage_ptr_id", "session_duration", "terminate_other_sessions") VALUES ('509c102f-da3c-40f8-bbe1-df5cf5ae6619'::uuid, 'seconds=0', false)
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.3.1
-   Deployment: docker-compose

**Additional context**
N/A

**Comment by BeryJu** [comment]
`remember_me_offset` is a field added in 2023.4 so it looks like your database was upgraded to 2023.4 and then downgraded again, which is not supported. Upgrade to 2023.4 to fix the error
