### ISSUE TITLE
API Swagger docs are not rendering/visiable

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#5477]
**Describe the bug**
The API swagger documentation page doesn't render anything.

**To Reproduce**

1. Go to https://authentik.example.tld/api/v3/
2. See that nothing loads except an empty page

**Expected behavior**
I expected swagger API documentation to load.

**Logs**
There is nothing of interest.

**Version and Deployment:**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Additional context**
Browser console yells:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'config')
    at config.ts:12:72
(anonymous) @ config.ts:12
```

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/pull/5402
