### ISSUE TITLE
Frontend: Updating stage binding order seems broken

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#5479]
**Describe the bug**
Trying to update stage binding's order value, and the result is HTTP status code 400, aka bad request.

**To Reproduce**

1. Go to any flow's stage bindings
2. Try to edit binding for any to change it's order value
3. See error about `{"target":["This field is required."]}` from PUT request

**Expected behavior**
It would work and there were proper tests to prevent these issues.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Additional context**
Please do a better job with not breaking things with improving test coverage.

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/issues/5286
