### ISSUE TITLE
Add users to group functionality missing 

### ISSUE THREAD

**Issue by liquidfrollo** [goauthentik/authentik#5495]
**Describe the bug**
The ability to add users to a group is missing 

**To Reproduce**

Directory > Groups > Select Edit on a group

**Expected behavior**
Expected: See a field / line item consistent with instructions and images with the functionality to add users to groups

**Screenshots**
![image](https://user-images.githubusercontent.com/14299962/236520327-a890c04b-1d24-4b15-ac43-35ba15205ea3.png)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version:  2023.4.1
-   Deployment: Truecharts 2023.4.1_10.0.46

**Additional context**
Tested via Chrome (Version 112.0.5615.138 (Official Build) (64-bit)) and Edge

**Comment by BeryJu** [comment]
Users can be added to groups by clicking on the group name, going to the user tab and adding existing/new users there. The reason this was removed from this from is that it caused a lot of problems when adding users here as the changes could be overridden by other requests
