### ISSUE TITLE
settings.enabledFeatures doenst work corretly

### ISSUE THREAD

**Issue by Tauebenuss** [goauthentik/authentik#5507]
**Describe the bug**
After Setting one of the values from settings.enabledFeatures all Features are enabled. 

all values are set to false 

**To Reproduce**

1. Go to 'System - Tentants - Attributes"
2. Set Attributes: 
```settings:
  locale: de
  enabledFeatures:
    search: false
```
3. Go to Users Home to verify, all Features are disabled

**Expected behavior**
Only the disabled feature are affected. 

**Logs**
No Logs needed.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
The attributes are missing the `settings` key;

```yaml
settings:
  enabledFeatures:
    search: false
```
