### ISSUE TITLE
Group permissions not working with vCenter ADFS

### ISSUE THREAD

**Issue by sjkjs** [goauthentik/authentik#5511]
**Describe the bug**
When logging into vCenter via Authentik with a user account that is granted permission via an Active Directory group (e.g. vCenter Users), the permissions are not applied and the error "Unable to login because you do not have permission on any vCenter Server systems connected to this client." is displayed.

**To Reproduce**

1. Configure vCenter and Authentik as per these instructions: https://goauthentik.io/integrations/services/vmware-vcenter/
2. Under vCenter Global Permissions, assign Administrator permissions to the Active Directory group vCenter Users
3. In Active Directory, create a user Test and add it to the group vCenter Users
4. Log in to Authentik as Test and attempt to access vCenter
5. Error message is displayed

**Expected behavior**
Login should succeed.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   vCenter version: 8.0.1 build 21560480
-   Deployment: docker-compose

**Additional context**
If within vCenter Global Permissions I specifically give access to user Test by account name then everything works as expected. The issue is specifically related to permissions via groups.

If I disable ADFS/Authentik login and use Active Directory authentication in vCenter then everything works as expected.

**Comment by BeryJu** [comment]
I don't have a vCenter instance or an ADFS instance to test this with, but try this:

Create a scope mapping with the scope name `profile` and the expression

```python
ldap_base_dn = "DC=ldap,DC=goauthentik,DC=io"
groups = []
for group in request.user.ak_groups.all():
    group_dn = f"CN={group.name},dc=groups,{ldap_base_dn}"
    groups.append(group_dn)
return {
    # Because authentik only saves the user's full name, and has no concept of first and last names,
    # the full name is used as given name.
    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(" ")`
    "name": request.user.name,
    "given_name": request.user.name,
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    "groups": groups,
}
```

And select it instead of the default openid scope in the provider

It seems that vCenter is expecting the `groups` attribute to be a list of LDAP DNs instead of just group names, which the mapping above does. vCenter also doesn't allow for the selection of custom scopes hence we have to override one of the default ones it does request

**Comment by sjkjs** [comment]
Thanks for the suggestion. I gave it a shot after changing the ldap_base_dn and group_dn strings to match my Active Directory environment (I'm not using Authentik's LDAP). No change. I can still login when the users are granted permission individually but not via group membership.

Is there a good way to debug exactly what data is being sent so I can make sure it looks the way I expect it to? I installed a Chrome plugin to trace SAML/OIDC but it isn't showing me what I expect. I can see some OIDC messages but they just contain things like redirect_uri, state, resource. I'm not seeing things like username, email, groups.

**Comment by BeryJu** [comment]
vCenter gets its data from the JWT that the access token is, but iirc vcenter uses a method that gets the token in the background. It also doesn't help that vCenter doesn't document what it needs as only ADFS is "supported". I'll try to get a vCenter instance to test this

**Comment by obsidiangroup** [comment]
If you do get an instance running, would you mind updating the integrations for vCenter 8?  I'd even include getting certificates imported properly since this is important if you are using say self-signed certificates, Let's Encrypt, or other's.

**Comment by sjkjs** [comment]
I set up an ADFS server for testing, and can confirm that vCenter wants the groups presented using the "Token-Groups - Qualified by Long Domain Name" type in ADFS.

I found this site which describes what the different group types mean:

https://nzpcmad.blogspot.com/2012/06/adfs-sending-groups-as-claims.html

It says that when using this type the groups are presented as a list of "…identity/claims/role" with values like "domainname.com\groupname".

Based on that information, I tried modifying the scope mapping so that it matches this syntax instead of using the DC=.... syntax. No luck. I also tried changing the scope mapping so that instead of returning "groups": groups, it would return "role": groups.

I feel like it should be simple to get it working, I just can't get it quite right.

**Comment by sjkjs** [comment]
I've just looked in the vCenter syslog messages and I can see these two messages each time I try to log in:

`Missing groups claim 'group'`

`name = <user>@<domain name>,\n    domain = <domain name>,\n    groupNames = [],\n    groupIds = []\n}`

It doesn't matter what name I use in the scope mapping, I always get these same errors. So it seems that vCenter isn't actually seeing the groups at all.

**Comment by sjkjs** [comment]
Still an issue

**Comment by christian-2** [comment]
Is seems to me that vSphere sees groups if they arrive in a claim `group` with values formatted as `my-domain\my-group`; `sso/tokenservice.log` conveys that much:

```
INFO tokenservice ...
[com.vmware.vcenter.tokenservice.jit.JitJwt] JITing user: my-user@my-domain, ... => {\n
  identityProviderId = ...,\n
  name = my-user@my-domain,\n
  domain = my-domain,\n
  groupNames = [my-group],\n
  groupIds = [my-group]\n
}
```

Despite this step forward, `my-user@my-domain` still cannot log into vSphere (the error message in the browser reads "Unable to login because you do not have permission on any vCenter Server systems connected to this client"), even though the necessary group memberships and role assignments should all be in place.

**Comment by christian-2** [comment]
I was mistaken and a role assignment was still missing in vSphere by mistake. After fixing that, `my-user@my-domain` can now authenticate to vSphere as `Administrator` by virtue of being a member of `my-group`.

**Comment by sjkjs** [comment]
> I was mistaken and a role assignment was still missing in vSphere by mistake. After fixing that, `my-user@my-domain` can now authenticate to vSphere as `Administrator` by virtue of being a member of `my-group`.

Would you be able to share what your Scope Mapping looks like? I'm using the one suggested earlier:

`ldap_base_dn = "DC=ldap,DC=goauthentik,DC=io"
groups = []
for group in request.user.ak_groups.all():
    group_dn = f"CN={group.name},dc=groups,{ldap_base_dn}"
    groups.append(group_dn)
return {
    # Because authentik only saves the user's full name, and has no concept of first and last names,
    # the full name is used as given name.
    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(" ")`
    "name": request.user.name,
    "given_name": request.user.name,
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    "group": groups,
}`

The only change being that I changed groups to group as per your suggestion.

This still has the same problem of being unable to authenticate via group membership.

**Comment by christian-2** [comment]
@sjkjs I am doing this in a context of [another project](https://github.com/christian-2/oidc-passkey) that employs Keycloak (with WebAuthn-enabled flows) as a identity provider for vSphere. I came across this issue as I researched that final obstacle, namely granting access for user `username@mydomain.com` with vSphere's role `Administstrator` by virtue of user `username` being a member of a group `groupname` in Keycloak. This now works with Keycloak 21.1.2 and vSphere 8.1.

I'm configuring the vSphere ADFS provider with `cn=users,dc=mydomain,dc=com` as base distinguished name for users and with `cn=groups,dc=mydomain,dc=com`as base distinguished name for groups.

And I am configuring mappers that include the following claims: `"sub": "username"`, `"upn": "username@mydomain.com"`, `"group": ["groupname@mydomain.com"]` (the format `mydomain.com\groupname` would apparently work as well).

The missing role assignment I was referring to was a permission `Administrator` for group `groupname@mydomain.com` configured under Inventory / *vServer* / Permissions in vSphere.

Does that help?

**Comment by sjkjs** [comment]
And actually, I decided to try again but by hardcoding all 3 values this time:

`return { "sub": "jsmith", "upn": "jsmith@mydomain.com", "group": ["vCenter Users@mydomain.com"], }`

No change, still the same issue. Obviously there's something misconfigured here.

**Comment by christian-2** [comment]
The following items come to mind:

* `upn` is, strictly speaking, not an email address, but `username` followed by `@` and the domain configured into the ADFS provider. The ADFS provider [derives the domain from the base distinguished name for users](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.authentication.doc/GUID-C5E998B2-1148-46DC-990E-A5DB71F93351.html), which may be `ldap.goauthentik.io` in your case. What specific domain does vSphere display e.g. in the window where it autocompletes names from AD?
* Could you try with a group name without spaces first or instead. I don't know whether the syntax `groupname@domain` (same for `domain\groupname`) would require any special escaping for those (e.g. in the case of `vCenter Users`).
* Inside vSphere, I have assigned permission `Administrator` to the intended group both under Administration / Global Permissions and under the vServer instance (as mentioned above). Perhaps you only have the second one.
* The OIDC tester (see above) proved very useful for confirming that the ID token really contained the verbatim claims that I wanted to pass to vSphere.
* I gained some key insights from vSphere log files `/var/log/vmware/sso/ssoAdminServer.log` and `/var/log/vmware/sso/tokenservice.log`.

**Comment by hotrod225** [comment]
Any luck with this? I am having the same issue.

**Comment by sjkjs** [comment]
I know this is closed as won't fix, but I guess people might find their way here by searching.

I got it working under vCenter 8.0.2 build 23319993. The scope mapping to use is:

`groups = []
for group in request.user.ak_groups.all():
  if group.name == "vCenter Users":
    groups.append(group.name)
return {
  "upn": request.user.email,
  "group": groups,
}`

Replace "vCenter Users" with the name of your AD group. The reason for the if statement is because if the list of groups is too long, vCenter throws an exception and won't let you log in. The list needs to be short.

**Comment by ddavtian** [comment]
Here is my working version with the latest `8.0.2`

```
ldap_base_dn = "DC=ldap,DC=goauthentik,DC=io"
domain = "ldap.goauthentik.io"
groups = []
for group in request.user.ak_groups.all():
    group_dn = f"CN={group.name},dc=groups,{ldap_base_dn}"
    groups.append(group_dn)
return {
    "name": request.user.name,
    "email": request.user.email,
    "given_name": request.user.name,
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    "groups": groups,
    "upn": request.user.username+'@'+domain,
    "domain": domain
}
```

**Comment by Logianer** [comment]
I have `8.0.3` and none of the solutions are working for me. I can see that vcenter is correctly querying the groups when i search for them in the UI, but something is probably not parsing them in the right way in vcenter and it just returns "no results".

Overall, this seems more like a vCenter bug than an inability to configure authentik's oidc to me.
