### ISSUE TITLE
Authentik logs showing local instead of remote ip for client ip

### ISSUE THREAD

**Issue by Keyinator** [goauthentik/authentik#5529]
**Describe your question**
In my current authentik implementation Event Logs always show the docker-host's ip instead of the client's ip

**Relevant infos**
I am running two lxcs on a proxmox node: "authentik" and "docker".
For security reasons I wanted to have them separate. They both have ips within 10.1.0.0/16

On docker I have an outfacing nginx-proxy-manager instance.
I have tried solving this error by adjusting the nginx-proxy-manager host entry for authentik.
I currently have these headers in the "custom locations"-tab:
```
proxy_set_header   X-Real-IP $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header   Upgrade $http_upgrade;
proxy_set_header   Connection "upgrade";
```
(No Host-header since it led to a ``400 Bad Request``)
(Also Websockets Support is turned on in the porxy-host config)

I highly doubt that the issue lies within nginx proxy manager since the ip inside of the logs is the one of the docker-host authentik is running on (so neither the docker-host of nginx-proxy-manager nor the nginx-proxy-manager instance itself).
I think that this has something to do with my 2-docker-hosts approach.

**Screenshots**
![image](https://user-images.githubusercontent.com/44442933/236839398-b8390c01-46d2-4746-9a98-129e6ca4b162.png)
![image](https://user-images.githubusercontent.com/44442933/236839699-0aba3c6c-cbcb-4ba4-886c-c428c790d013.png)
![image](https://user-images.githubusercontent.com/44442933/236839718-07f4b42c-f1c9-490a-bc4f-d5a6ffcec0f8.png)
![image](https://user-images.githubusercontent.com/44442933/236839739-bfaac4f4-3e7c-40fd-9d85-20ed4163492d.png)
![image](https://user-images.githubusercontent.com/44442933/236839755-9ee7149d-a3fa-40f6-85e2-0eee50545069.png)

**Logs**
```
{"auth_via": "session", "event": "/api/v3/core/applications/", "host": "auth.<MASKED>", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": "<MASKED>", "remote": "172.18.0.1", "request_id": "<MASKED>", "runtime": 79, "scheme": "https", "status": 200, "timestamp": "2023-05-08T13:47:39.300435", "user": "<MASKED>", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose
-   nginx-proxy-manager version: 2.10.2

How can I change it into showing the actual client's ip address?

**Comment by Keyinator** [comment]
With help over at the discord I came to the following assumption and could not find a fix:
> Seems like this is a docker issue:
> https://github.com/docker/roadmap/issues/157
> (Originating from https://github.com/docker/for-mac/issues/180)

**Comment by Keyinator** [comment]
I am a little bit embarrassed, but I was totally blindsided.
The issue lied within docker but was fixable by creating the file ``/etc/docker/daemon.json`` with content:
```
{
  "userland-proxy": false
}
```
in **both** containers/docker-hosts
(and applying ``sudo systemctl restart docker`` afterwards).

Before, I was only trying this config on the authentic docker-host.

**Comment by uwugression** [comment]
Had a similar issue on authentik deployed on k8s, turns out my pod CIDR was not matching the default value set in `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS`. So I had to adjust it in values.yaml like so:

```yaml
server:
  env:
    - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
      value: "192.160.0.0/16"
```
