### ISSUE TITLE
Device code flow Not working

### ISSUE THREAD

**Issue by heoyongun** [goauthentik/authentik#5566]
**Describe the bug**
The device code flow doesn't seem to work

**To Reproduce**
System > Tenants  
Device code flow > default-source-pre-authentication
![스크린샷 2023-05-11 00-21-01](https://github.com/goauthentik/authentik/assets/6076067/2ea1f6a5-6871-43d8-a805-6d0f2dae7151)

Applicaiotns > Providers, create device_provider
Authorization flow > default-provider-authorization-explicit-consent
![스크린샷 2023-05-11 00-23-44](https://github.com/goauthentik/authentik/assets/6076067/2104757b-8592-4283-bb93-f6f2524d724f)

Applications > Applications
Provider > device_provider
![스크린샷 2023-05-11 00-25-10](https://github.com/goauthentik/authentik/assets/6076067/2f0c10b7-4162-4a76-87e6-7d96af4ec2e0)

**Expected behavior**
1. POST, http://localhost:9000/application/o/device/ request is ok
![스크린샷 2023-05-11 00-26-26](https://github.com/goauthentik/authentik/assets/6076067/a2621381-92b9-4a67-af77-8038ecc12268)

2. POST, http://localhost:9000/application/o/token/, request, is fail,  I was expecting an [authorization_pending] response to come.
![스크린샷 2023-05-11 00-29-36](https://github.com/goauthentik/authentik/assets/6076067/df6f9d95-9196-4c24-a6d1-fb581872f5f9)

**Version and Deployment (please complete the following information):**
![스크린샷 2023-05-11 00-30-18](https://github.com/goauthentik/authentik/assets/6076067/e4191216-91bc-476b-83c8-9d82fbeef38c)

-   authentik version: 2023.3.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
I'm assuming when you sent the request to `/application/o/device/` you set the client_id to the same client_id as you're using in the second request?

Also when copying the device code from the JSON certain characters will be escaped, make sure those are unescaped when sent in the second request

**Comment by heoyongun** [comment]
> I'm assuming when you sent the request to `/application/o/device/` you set the client_id to the same client_id as you're using in the second request?
> 
> Also when copying the device code from the JSON certain characters will be escaped, make sure those are unescaped when sent in the second request

The same client_id was used.
applied encodeURI 
It fails the same. 

![스크린샷 2023-05-11 23-45-58](https://github.com/goauthentik/authentik/assets/6076067/2c7b67c2-535e-4ca4-b625-23611c5a683c)
![스크린샷 2023-05-11 23-47-37](https://github.com/goauthentik/authentik/assets/6076067/bfe5a616-6e77-4ecf-8fba-014ac80c4e4d)

Expect the same error as #5133.

**Comment by BeryJu** [comment]
`encodeURI` is not correct, load the response with `JSON.parse` and output only the code with `console.log(JSON.parse(response).device_code)`

**Comment by BeryJu** [comment]
Postman does `encodeURI` in the background, you don't need to manually `encodeURI` the parameters

**Comment by heoyongun** [comment]
> Postman does `encodeURI` in the background, you don't need to manually `encodeURI` the parameters

If [encodeURI] is executed, the following error message is displayed.
![스크린샷 2023-05-15 00-32-43](https://github.com/goauthentik/authentik/assets/6076067/25432af8-4ba8-4bc6-9bd5-9a49cd34093a)

If [encodeURI] is not performed, the following error message is displayed.
![스크린샷 2023-05-15 00-31-58](https://github.com/goauthentik/authentik/assets/6076067/93038e48-5d43-4f0a-bb1c-a4db08aeb563)

Both will result in an error. 

Suspecting a version issue, I updated the version.

The same problem occurs.

![스크린샷 2023-05-15 00-36-37](https://github.com/goauthentik/authentik/assets/6076067/10aa994f-3a79-40d5-b206-a5536c6b81df)
