### ISSUE TITLE
SAML Errors all of the sudden

### ISSUE THREAD

**Issue by amanzella** [goauthentik/authentik#5635]
Wanted to see if someone could point me in the right direction. I have had the same setup since I started using Authentik, but last week, one of our SAML auths stopped working for one of our apps. We haven't changed anything on either side. 

Any ideas? Here is the error

Error processing external authentication return: SAML Configuration Error (https://auth.******.com/api/v3/providers/saml/1/metadata/?download): An error occurred while sending the request.

**Comment by BeryJu** [comment]
What happens when you open the URL above in your browser? You can also try without the `?download` parameter

**Comment by amanzella** [comment]
@BeryJu I just figured out the issue. For some reason, the app no longer likes the URL. If I open the URL with the ?download, it does download the XML. If I open it without ?download, it displays instead of downloading. 

I took the XML and placed it on one of my other webservers and pointed the app to that URL and it works fine now. 

It just doesn't like the URL not containing the .XML file I guess
