### ISSUE TITLE
vCenter Auth Issue

### ISSUE THREAD

**Issue by ddavtian** [goauthentik/authentik#5644]
**Describe your question**
- After going through the integration process I am getting the following error when trying to SSO 

> Unable to login because you do not have permission on any vCenter Server systems connected to this client.

<img width="1138" alt="image" src="https://github.com/goauthentik/authentik/assets/1940369/a537e8d6-4f26-436a-80d7-3ac34ecef4be">

- Followed the instructions at the following URL for [VMware vCenter](https://goauthentik.io/integrations/services/vmware-vcenter/) integration. 
- vCenter 8 is bound to an Active Directory Domain controller.
- Under Single Sign On Configuration, I have the following.
- I am using the integrated LDAP outpost.
<img width="1241" alt="image" src="https://github.com/goauthentik/authentik/assets/1940369/f769c87a-5c9c-485f-8846-bcf18235eee5">

- I have created an ldap provider, a vcenter provider and their respective applications.
- Under vCenter, given an Administrator permissions to the user I am doing SSO with.

<img width="1231" alt="image" src="https://github.com/goauthentik/authentik/assets/1940369/13e0608a-4e46-44a7-881b-2a50b3ea70d4">

**Version and Deployment (please complete the following information):**
-   authentik version: 2023.4.1
-   Deployment: helm

I am using the following property mapping

```
ldap_base_dn = "DC=ldap,DC=goauthentik,DC=io"
groups = []
for group in request.user.ak_groups.all():
    group_dn = f"CN={group.name},dc=groups,{ldap_base_dn}"
    groups.append(group_dn)
return {
    # Because authentik only saves the user's full name, and has no concept of first and last names,
    # the full name is used as given name.
    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(" ")`
    "name": request.user.name,
    "email": request.user.email,
    "given_name": request.user.name,
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    "groups": groups,
}
```

**Comment by ddavtian** [comment]
On my own setup I am able to drill down into users.

<img width="1259" alt="SCR-20230518-nzjl" src="https://github.com/goauthentik/authentik/assets/1940369/23b0d86d-ef3e-478f-a65a-1714cebfbfba">

**Comment by Catospye** [comment]
Could you by any chance post a picture of your configuration for the ldap provided on vCenter maybe im missing something you got. Also I think the login issue might be with permission and groups on the vCenter side add the user you want to the admin group on vCnt and see if that does the trick I was haveing that same error when I made a new user on the native login.

**Comment by ddavtian** [comment]
@Catospye the config is posted above in my second screenshot. For your primary server, you have 10.10.1.123:389, did you create an LDAP outpost for that in Authentik? You'll want to test out that it works once created by using ldapsearch or something similar, something similar to this. You won't need to create an entry for Open LDAP. Just go through the Microsoft ADFS option.

`ldapsearch -H ldap://authentik-ldap.xxxx.com -x -D "cn=ldapservice,ou=users,DC=ldap,DC=goauthentik,DC=io" -W -b "cn=ou=users,DC=ldap,DC=goauthentik,DC=io" "(objectClass=user)"`

> Also I think the login issue might be with permission and groups on the vCenter side add the user you want to the admin group on vCnt and see if that does the trick I was haveing that same error when I made a new user on the native login.

Tried that without luck.

**Comment by ddavtian** [comment]
@BeryJu -- one log entry that caught my attention in vCenter is the following

`2023-05-18T22:41:05.624-07:00 info vpxd[34223] [Originator@6876 sub=UserDirectorySso opID=lhl83skp-47650-auto-10rs-h5:70018610-67] GetUserInfoInternal(gmail.com\<username>, false) res: GMAIL.COM\<username>`

`2023-05-18T22:41:05.624-07:00 info vpxd[34223] [Originator@6876 sub=AuthorizeManager opID=lhl83skp-47650-auto-10rs-h5:70018610-67] [Auth]: User GMAIL.COM\<username>`

Maybe there is a mismatch here? Since in vCenter we are giving permission based on usernames and not emails as such.

<img width="1273" alt="SCR-20230518-tqjg" src="https://github.com/goauthentik/authentik/assets/1940369/7fd8bb20-5a7b-494b-92e8-3e538e7a7336">

Perhaps we need to tweak the property setting further?

```
ldap_base_dn = "DC=ldap,DC=goauthentik,DC=io"
groups = []
for group in request.user.ak_groups.all():
    group_dn = f"CN={group.name},dc=groups,{ldap_base_dn}"
    groups.append(group_dn)
return {
    # Because authentik only saves the user's full name, and has no concept of first and last names,
    # the full name is used as given name.
    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(" ")`
    "name": request.user.name,
    "email": request.user.email,
    "given_name": request.user.name,
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    "groups": [group.name for group in request.user.ak_groups.all()]
```

**Comment by Catospye** [comment]
> @Catospye the config is posted above in my second screenshot. For your primary server, you have 10.10.1.123:389, did you create an LDAP outpost for that in Authentik? You'll want to test out that it works once created by using ldapsearch or something similar, something similar to this. You won't need to create an entry for Open LDAP. Just go through the Microsoft ADFS option.
> 
> `ldapsearch -H ldap://authentik-ldap.xxxx.com -x -D "cn=ldapservice,ou=users,DC=ldap,DC=goauthentik,DC=io" -W -b "cn=ou=users,DC=ldap,DC=goauthentik,DC=io" "(objectClass=user)"`
> 
> > Also I think the login issue might be with permission and groups on the vCenter side add the user you want to the admin group on vCnt and see if that does the trick I was haveing that same error when I made a new user on the native login.
> 
> Tried that without luck.

AH alright thank you I will test out with your config adjusted to my environment; but yes I made a provider and the whole 9 yards I think I just messed up the config in vCNT.

and oh another thing vCNT likes to use the uid of the user as the user name so it might be getting confused on what is what...

**Comment by ddavtian** [comment]
Seems like I got the integration working, I created a property mapping with the following payload, most props are probably not needed but it's there anyway, the key ones are domain, sub and probably groups ( haven't tested groups though )

```
ldap_base_dn = "DC=ldap,DC=goauthentik,DC=io"
groups = []
for group in request.user.ak_groups.all():
    group_dn = f"CN={group.name},dc=groups,{ldap_base_dn}"
    groups.append(group_dn)
return {
    "name": request.user.name,
    "email": request.user.email,
    "given_name": request.user.name,
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    "groups": groups,
    "domain": "ldap.goauthentik.io",
    "sub": request.user.username
}
```

<img width="1601" alt="SCR-20230520-tnvj" src="https://github.com/goauthentik/authentik/assets/1940369/5bc98ad3-5dfe-47c8-b81c-4dbeb05d8b0e">

If you run into any auth issues, tail the following for clues

`tail -f  /var/log/vmware/sso/tokenservice.log`

**Comment by BeryJu** [comment]
For `sub` it would be easier to select the matching `Subject mode` in the provider, but aside from that, do you want to PR this fix to the vCenter docs?

**Comment by ddavtian** [comment]
@BeryJu, thanks and here's the PR https://github.com/goauthentik/authentik/pull/5706
