### ISSUE TITLE
SCIM provider automatic sync not triggering since 2023.5.0

### ISSUE THREAD

**Issue by darioef** [goauthentik/authentik#5654]
**Describe the bug**
SCIM provider automatic sync is not triggering (hourly & on user/group change).
Just upgraded to 2023.5.0 yesterday and (I think) that sync is broken since upgrade. I was using 2023.3.1 and 2023.4.1 previously with the SCIM provider to provision AWS SSO (IAM Identity Center) and those triggers worked (but without PATCH added in 2023.5.0 so that was the main reason for this upgrade).

**To Reproduce**
Configure SCIM provider and wait for the full sync hourly, try to add/remove a member in a group or create a new user.

**Expected behavior**
From [documentation](https://goauthentik.io/docs/providers/scim/#syncing):

```
Data is synchronized in multiple ways:

When a user/group is created/modified/deleted, that action is sent to all SCIM providers
Periodically (once an hour), all SCIM providers are fully synchronized
```

**Screenshots**
No screenshots for this case.

**Logs**
There's no sync events events in logs. Logs are configured in trace level.
The only SCIM events I see are:

```
2023-05-17 09:24:58 | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 5476, "task_id": "d2f7357b-caf3-40b9-8750-93134c36badf", "task_name": "scim_signal_direct", "timestamp": "2023-05-17T12:24:58.174683"}
2023-05-17 09:24:58 | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 5476, "state": "SUCCESS", "task_id": "d2f7357b-caf3-40b9-8750-93134c36badf", "task_name": "scim_signal_direct", "timestamp": "2023-05-17T12:24:58.210445"}
```

**Version and Deployment (please complete the following information):**

-   authentik version:2023.5.0
-   Deployment: Helm chart

**Additional context**
If I run the sync manually it works, but the full sync adds/replace objects it doesn't remove users from a group since I think it's only incremental and the removal of a member should be done whent the group is modified.

**Comment by BeryJu** [comment]
With 2023.5, the SCIM provider is only active when its assigned as a backchannel provider to an application. The docs/release notes might not make this clear

**Comment by darioef** [comment]
Great! It's working fine after assigning the SCIM provider to the application however I have a configuration in the User Write Stage (default-source-enrollment-write) to add newly created users to a group by default. When a new user is created is added to the Authentik group but not in the remote group. I can't see and update event in the logs for this case (it worked in older versions). I have to remove/add the user from the group manually to get the sync working.

Thanks for your quick response and your awesome work.

**Comment by BeryJu** [comment]
> Great! It's working fine after assigning the SCIM provider to the application however I have a configuration in the User Write Stage (default-source-enrollment-write) to add newly created users to a group by default. When a new user is created is added to the Authentik group but not in the remote group. I can't see and update event in the logs for this case (it worked in older versions). I have to remove/add the user from the group manually to get the sync working.

I'm not able to reproduce this, but you should be able to search for `scim_signal_m2m` in your worker logs, take the `task_id` value of that log entry and search for that ID which will show all the relevant log entries. Also this should probably be a new issue

**Comment by BeryJu** [comment]
Yeah please open a new issue for this (also set your log level to debug if it isn't already)
