### ISSUE TITLE
Questions for Backup and Restore of Authentik

### ISSUE THREAD

**Issue by christophdb** [goauthentik/authentik#5672]
**Current setup:**
- Authentik 2023.5.
- docker-compose setup on a standalone server.
- I use authentik als central IdP for my company. <10 users, 15 SAML providers, 10 proxy providers.
- custom flow to enforce 2FA for all users.

**My Goal? Create a backup!**
I want to do create a backup of my authentik server but don't find any description what has to be saved. The only description I found is that Authentik removed the integrated backup solution with 2022-02 (https://goauthentik.io/docs/releases/2022.2#removal-of-integrated-backup). 

Right now, I save the following components. Can you please tell me if this is sufficient:
- everything below /opt/authentik. This includes the .env-file, docker-compose.yml and the folders media, certs and custom-templates
- The dump of the Postgres database

**Here are my questions:**
- I just dump the postgres database with the password from the .env file. Anything special here?
- what about redis or the other containers. Anything that has to be saved?
- my certs folder is empty. Is that normal? 
- anything else that I forgot?

I would love if somebody just shares his script, steps or approach how to save authentik. I don't need the information how to save it on a remote location. Everybody will use another backup target. What I want to know is how to get everything in one place that is needed for backup and restore.

Thanks and best regards
Christoph

**Comment by BeryJu** [comment]
Hi, you're pretty much spot on. The only thing that needs to be backed up is PostgreSQL. Redis _can_ also be backed as it stores all the user sessions and other temporary data, but it's optional

The `certs` folder is empty by default as it is used to import certificates from outside authentik into the database, so if you don't use that feature the empty folder is to be expected. It is a good idea to just backup the entire folder where the docker-compose file is located especially if you've uploaded any icons/etc

**Comment by christophdb** [comment]
Thanks for your input. 
So for everybody looking how to dump the Postgres-database, here is the command I use.

In general:
`docker exec -i <postgres-container> /usr/local/bin/pg_dump --username <postgres-user> <postgres-database> > <target-dump-file>`

concrete:
`docker exec -i authentik-postgresql-1 /usr/local/bin/pg_dump --username authentik authentik > /opt/authentik/postgres-backup.sql`

**Comment by OliverPifferi** [comment]
Thanks for the input here which finally answered one of my open questions regarding authentik, @christophdb!
