### ISSUE TITLE
Improve or make information on TOTP code dialog customizable

### ISSUE THREAD

**Issue by motey** [goauthentik/authentik#5673]
**Is your feature request related to a problem? Please describe.**

The TOTP dialog just aske for a "Code". Non technical or non regular users could be confused what is expected here.

**Describe the solution you'd like**
 A better hint on what this dialog wants could improve UX. Ideally this hint is customizable. 

**Describe alternatives you've considered**
An extra flowstage with a display only prompt "preparing" the user for the following dialog. Quite awkward if you ask me. 

**Additional context**
![image](https://github.com/goauthentik/authentik/assets/1006417/71a42c7e-5bfb-4037-b8e2-197538dbe0de)

**Comment by BeryJu** [comment]
![image](https://github.com/goauthentik/authentik/assets/1932513/81782120-0bc4-48c1-897a-e9f811c7644a)

What do you think about this? @motey Also curious about your opinion @tanberry

**Comment by macmoritz** [comment]
I am sorry for needing to correct you.
First of all this is a great help for non-tech and/or first-time users.

The issue I found is regarding to the "mobile phone". There are multiple other TOTP generating devices out there, in fact I would say that smartphones are only one of a dozen plattforms to generate TOTPs.

For example we have multiple dedicated devices out there, like for a  keychain or in a calculator style. Also there are apps for all desktop OSes. 

I would suggest changing the wording again to be more general in a matter of devices.

"Enter your two-factor authenticator code from your authenticator device or app."

**Comment by motey** [comment]
You are totally right. 
But i think it is acceptable to assume that people that are using TOTP devices are "techies" or people that have some kind education about TOTP devices. And this hint is just for people, that would be lost with this dialog otherwise. So in my opinion it is a level of acceptable incorrectness, as a tradeoff to keep things simple and have a clear instruction on what to do. 
On the other hand you proposed sentence is still in the "simple clear instruction" realm. But in favor of keeping the workload for the team, working on this free and open source app, low i would propose to live with the current version :)
