### ISSUE TITLE
Server healthcheck failes with 403 status code

### ISSUE THREAD

**Issue by a-gerhard** [goauthentik/authentik#5694]
**Describe the bug**
Server healthcheck (command `/lifecycle/ak healthcheck`) is failing with a 403 issue. This started happening after upgrading from 2023.4.1 to 2023.5.1

It's a breaking issue for me since traefik's loadbalancer (which I'm using as reverse proxy) doesn't forward requests to unhealthy docker containers. I'm unsure if the fact that authentik's public URL is not available until the healthcheck succeeds might be an issue here.

**To Reproduce**

1. Install via docker-compose
2. observe how the healthcheck fails and the container is set to unhealthy

**Expected behavior**
The built-in healthcheck should not fail with a 403 status code.

**Logs**
In the server's docker log:
```
auth_via=unauthenticated event=/-/health/live/ host=localhost:8000 logger=authentik.asgi method=GET pid=51 remote=127.0.0.1 request_id=1f22b189433a45d7ba0eb66bdfa91f43 runtime=13 scheme=http status=204 timestamp=2023-05-19T09:37:06.759487 user= user_agent=goauthentik.io/proxy/healthcheck
```

Manually running the healthcheck command in the server:
```
authentik@edd80195dd06:/$ /lifecycle/ak healthcheck
{"event":"checking health","level":"debug","mode":"server","timestamp":"2023-05-19T09:33:57Z"}
{"event":"Loaded config","level":"debug","path":"./authentik/lib/default.yml","timestamp":"2023-05-19T09:33:57Z"}
{"event":"Loaded config from environment","level":"debug","timestamp":"2023-05-19T09:33:57Z"}
{"event":"unhealthy status code","level":"warning","status":403,"timestamp":"2023-05-19T09:33:57Z"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.1
-   Deployment: docker-compose, 
-   Reverse Proxy: traefik (using docker provider)

**Comment by gezuka77** [comment]
> **Describe the bug** Server healthcheck (command `/lifecycle/ak healthcheck`) is failing with a 403 issue. This started happening after upgrading from 2023.4.1 to 2023.5.1
> 
> It's a breaking issue for me since traefik's loadbalancer (which I'm using as reverse proxy) doesn't forward requests to unhealthy docker containers. I'm unsure if the fact that authentik's public URL is not available until the healthcheck succeeds might be an issue here.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install via docker-compose
> 2. observe how the healthcheck fails and the container is set to unhealthy
> 
> **Expected behavior** The built-in healthcheck should not fail with a 403 status code.
> 
> **Logs** In the server's docker log:
> 
> ```
> auth_via=unauthenticated event=/-/health/live/ host=localhost:8000 logger=authentik.asgi method=GET pid=51 remote=127.0.0.1 request_id=1f22b189433a45d7ba0eb66bdfa91f43 runtime=13 scheme=http status=204 timestamp=2023-05-19T09:37:06.759487 user= user_agent=goauthentik.io/proxy/healthcheck
> ```
> 
> Manually running the healthcheck command in the server:
> 
> ```
> authentik@edd80195dd06:/$ /lifecycle/ak healthcheck
> {"event":"checking health","level":"debug","mode":"server","timestamp":"2023-05-19T09:33:57Z"}
> {"event":"Loaded config","level":"debug","path":"./authentik/lib/default.yml","timestamp":"2023-05-19T09:33:57Z"}
> {"event":"Loaded config from environment","level":"debug","timestamp":"2023-05-19T09:33:57Z"}
> {"event":"unhealthy status code","level":"warning","status":403,"timestamp":"2023-05-19T09:33:57Z"}
> ```
> 
> **Version and Deployment (please complete the following information):**
> 
> * authentik version: 2023.5.1
> * Deployment: docker-compose,
> * Reverse Proxy: traefik (using docker provider)

Hi, I am seeing the same error in the logs. Have you possibly figured our what is wrong?
