### ISSUE TITLE
How to create a new authentication flow called device-token

### ISSUE THREAD

**Issue by heoyongun** [goauthentik/authentik#5697]
**Describe your question/**

How to create a new authentication flow called device-token.

I don't know how to create or configure a device-token.

If anyone has a successful example or story, I'd love to help.

#5133 

**Relevant infos**
v2023.5.1

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [v2023.5.1]
-   Deployment: [docker-compose]

**Comment by BeryJu** [comment]
https://docs.goauthentik.io/docs/flow/ you require an empty flow with the designation "Stage configuration" and select it in the brand that you want to use it under.
