### ISSUE TITLE
Unable to deploy remote outpost

### ISSUE THREAD

**Issue by luketainton** [goauthentik/authentik#5718]
**Describe your question**
I'm trying to deploy a remote Proxy Outpost but I'm getting the following as an error:
`timestamp="2023-05-22T17:47:33Z" level=error event="Failed to fetch global configuration" error="is_enterprise is not a valid CapabilitiesEnum" logger=authentik.outpost.ak-api-controller`

**Relevant info**
- Server OS: Debian 10 x64

**Logs**
See error above.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
Make sure that the outpost container image is the same version as the authentik server
