### ISSUE TITLE
Not sure that OAuth2 client source should use authorization header

### ISSUE THREAD

**Issue by mccullerlp** [goauthentik/authentik#5725]
I've been testing authentik using an Auth0 openIDC source as well as a google source. I have gotten both to work, but Auth0 was not working before a fix to prevent adding the access token to the authorizaton Bearer headers. Google auth works fine with or without this fix. 

https://auth0.com/blog/id-token-access-token-what-is-the-difference/ suggests that many endpoints should not be given the access token. Not sure this is relevant.

I think Auth0 is less permissive and prefers the access_token param rather than the Authorization Bearer token

in sources/oauth/clients/oauth2.py
```
class OAuth2Client(BaseOAuthClient):
    """OAuth2 Client"""

   ...

    def do_request(self, method: str, url: str, **kwargs) -> Response:
        """Build remote url request. Constructs necessary auth."""
        if "token" in kwargs:
            token = kwargs.pop("token")

            params = kwargs.get("params", {})
            params["access_token"] = token["access_token"]
            kwargs["params"] = params

            headers = kwargs.get("headers", {})
            # Note this fix
            # headers["Authorization"] = f"{token['token_type']} {token['access_token']}"
            kwargs["headers"] = headers
        return super().do_request(method, url, **kwargs)
```

**Comment by uumas** [comment]
It seems authentik sets both the `access_token` query parameter and the `Authorization` header, which makes my oauth2 provider (https://wordpress.org/plugins/oauth2-provider/) return 400 invalid request error. With just one or the other set it works. So this should be configurable or at least follow the spec.

**Comment by BeryJu** [comment]
We do indeed send both by default for better compatibility, there is https://github.com/goauthentik/authentik/blob/main/authentik/sources/oauth/clients/oauth2.py#L138 which sends only the header (which is better in theory as its much harder to accidentally log), and that client is used for OIDC and a couple other providers.

OIDC actually specifies to use the Authorization header only https://openid.net/specs/openid-connect-core-1_0.html#UserInfoRequest

**Comment by uumas** [comment]
it would be totally fine if it only sent the authorization header but it is sending both with an OAuth Source with provider type "Generic OpenID Connect"

**Comment by BeryJu** [comment]
```diff
diff --git a/authentik/sources/oauth/types/oidc.py b/authentik/sources/oauth/types/oidc.py
index 189209c43..7ebd24579 100644
--- a/authentik/sources/oauth/types/oidc.py
+++ b/authentik/sources/oauth/types/oidc.py
@@ -20,7 +20,7 @@ class OpenIDConnectOAuthRedirect(OAuthRedirect):
 class OpenIDConnectOAuth2Callback(OAuthCallback):
     """OpenIDConnect OAuth2 Callback"""

-    client_class: UserprofileHeaderAuthClient
+    client_class = UserprofileHeaderAuthClient

     def get_user_id(self, info: dict[str, str]) -> str:
         return info.get("sub", "")
```

d'oh after looking at it again, yeah, I can see why not lol
