### ISSUE TITLE
Add `offline_access` scope for OAuth2 / OIDC

### ISSUE THREAD

**Issue by bbaumgartl** [goauthentik/authentik#5754]
I am trying to integrate Authentik with Zerotier. Their [documention](https://docs.zerotier.com/central/sso/#sso-provider-configuration) states that the `offline_access` scope is required. But i can't find it anywhere.

Is it possible to implement the `offline_access` scope like [Authelia](https://www.authelia.com/integration/openid-connect/introduction/#offline_access) or [Keycloak](https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/sessions/offline.html)? Or is there another way i can add it?

The official OpenID Connect specification can be found [here](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess).

**Comment by ostiwe** [comment]
bump

**Comment by bbaumgartl** [comment]
Seems to be implemented added with `2024.2.1` ([doc](https://goauthentik.io/docs/providers/oauth2/#authorization_code)). 

But some applications can have a problem with the implementation as described [here](https://github.com/goauthentik/authentik/issues/8660#issuecomment-1965147392).
