### ISSUE TITLE
Latest docker-compose yml is breaking .env variables 

### ISSUE THREAD

**Issue by tazboyz16** [goauthentik/authentik#5756]
**Describe the bug**

https://goauthentik.io/docs/installation/configuration
AUTHENTIK_LISTEN__HTTP: Listening address:port (e.g. 0.0.0.0:9000) for HTTP (Server and Proxy outpost)
AUTHENTIK_LISTEN__HTTPS: Listening address:port (e.g. 0.0.0.0:9443) for HTTPS (Server and Proxy outpost)

https://raw.githubusercontent.com/goauthentik/authentik/version-2023.5/docker-compose.yml
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
https://raw.githubusercontent.com/goauthentik/authentik/version-2023.1/docker-compose.yml
      - "${AUTHENTIK_PORT_HTTP:-9000}:9000"
      - "${AUTHENTIK_PORT_HTTPS:-9443}:9443"

From my .env file 
#By default, authentik listens on port 9000 for HTTP and 9443 for HTTPS. To change this, you can set the following variables in .env
AUTHENTIK_PORT_HTTP=80
AUTHENTIK_PORT_HTTPS=443
      
**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
-   Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by BeryJu** [comment]
This is documented in the release notes https://goauthentik.io/docs/releases/2023.5 and the documentation was updated to match
