### ISSUE TITLE
Authentik as ldap provider and ubuntu as client

### ISSUE THREAD

**Issue by pbvdven** [goauthentik/authentik#5775]
**Describe your question/**
I want to use authentik as ldap provider and ubuntu desktop as client

I tried several online tutorials on generally setting up ldap client on ubuntu but im not getting any connection with authentik ldap provider.  i have successfully setup authentik ldap provider for proxmox, calibre and jellyfin. but no luck to use it for user login on ubuntu. maybe someone could help me out a little or could point me to a working tutorial. thanks for your time.

**Comment by BeryJu** [comment]
There is https://goauthentik.io/integrations/services/sssd/, have you tried that?

**Comment by pbvdven** [comment]
No i didn't know that was it. I'll try that thanks

**Comment by pbvdven** [comment]
Oke I’ve i understand correctly looks like sssd/ldap on ubuntu needs start_tls and authentik doesn’t support that.

**Comment by BeryJu** [comment]
SSSD can use SSL which authentik does support, hence the docs use the `636` port for LDAPS
