### ISSUE TITLE
Outpost integrations show local Docker connection as unhealthy

### ISSUE THREAD

**Issue by esackbauer** [goauthentik/authentik#5780]
**Describe the bug**
When using Docker Local as Outpost integration, I get the status in red "unhealthy". However everything seems to work.
When I click on change, and just update the Docker local outpost integration without actually changing anything, it reverts back to the outpost inregration page and shows checkmar in green and the docker version 24.0.1.
Reloading (F5) of that page shows red "unhealthy" again.
Clicking on the "Refresh" button on the page is turning it to green again.

**To Reproduce**

As admin, go to "Outpost Integrations" page. Notice status is red "unhealthy".
Click on the edit symbol.
Just press "Update" at the bottom of the page.

**Expected behavior**
If the connection works properly (it seems it does), it should show in green the docker version

**Screenshots**

**Logs**
No logs containing the issue available

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.2
-   Deployment: Portainer
-   Docker Version 24.0.1 on Debian 11

**Additional context**

**Comment by manuviens** [comment]
Same problem (2023.5.3).
I just have to click the Refresh button and it turns green (24.0.2).
But if I change page then go back to the Outpost integrations page, it's red Unhealthy again...
I click Refresh and hop, it's green!
