### ISSUE TITLE
Authentik sessions never end

### ISSUE THREAD

**Issue by RobertBrown3** [goauthentik/authentik#5803]
**Describe the bug**
When accessing a URL protected by Authentik, once you have logged in you stay logged in forever -- even if you close and reopen the browser!
**To Reproduce**
1. Log in to Authentik
2. Configure an application in the standard way (create a Provider, create an Application, set the app to be handled by the Outpost, etc)
3. Log out of Authentik (being logged in shouldn't matter, but just in case)
4. In the browser, go to the application
5. See the Authentik login screen. Log in.
6. Once the application page is displayed, close the browser
7. Reopen the browser and go back to the application page

**Expected behavior**
According to the documentation, if the session timeout is set to zero an Authentik "session" should last as long as the browser is running. Accordingly, closing the browser (all windows) and restarting it should cause the user to see the Authentik login page when accessing the application again.

What actually happens is that the browser goes straight to the application after the browser is restarted. The only way to get the Authentik login page again is to completely clear all sessions from the browser.

This behavior is consistent on Chrome and Firefox.

-   authentik version: 2023.5
-   Deployment: docker-compose

**Comment by tograss** [comment]
I stumbled over the same behavior, however this is not something authentik can fix. @BeryJu  improved the documentation see https://goauthentik.io/docs/flow/stages/user_login/  Quote: 

Different browsers handle session cookies differently, and might not remove them even when the browser is closed. See [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#expiresdate) for more info.

I think there is also a warning about this when configuring login-stage .

**Comment by RobertBrown3** [comment]
Actually, having one's sessions depend on browser cookie handling is not a good implementation where security is concerned. Applications like Wazuh manage sessions which will terminate after a period of inactivity, forcin It should be a simple matter to implement a similar session management mechanism in an application like Authentik. In fact, such a mechanism is essential for making Authentik more secure.

This bug *can* be fixed. In fact, it should be. As long as it is there Authentik will be less secure than it could be.

**Comment by Schaschlikcode** [comment]
Still interested. It would be nice to at least have a choice with policy customization.
That this feature is not planned is a surprise for me and actually poses a significant Vulnerability for my Infrastructure.
Once a session-cookie is stolen the attacker has access to everything that the targeted user has FOREVER.

**Comment by petter1** [comment]
Is this still the case?!

**Comment by petter1** [comment]
<img width="1094" height="793" alt="Image" src="https://github.com/user-attachments/assets/a6301132-f62d-4c44-8432-72a199cdf74b" />

you can just set a session duration to mitigate this
