### ISSUE TITLE
How to force only some users to setup a second factor 

### ISSUE THREAD

**Issue by tograss** [goauthentik/authentik#5820]
I would like to force only some users to setup a second factor. I can force all users via a setting in the default-authentication-mfa-validation Stage. I'm guessing it should be possible to create a second stage which enforces the setup of a second factor and having a policy deciding which user get's which stage ? However I'm unable  to create such a policy and any tips on how to archive this are greatly appreciated.

**Comment by sdimovv** [comment]
Have an expression policy that injects a 2FA stage (with mandatory 2FA setup for users who don't have 2FA) for users, who belong to a particular group, have a specific user attribute, or any other criteria that you use to identify them (see the authentik and possibly Django docs for the user object attributes). 

For other users not matching your criteria you can just not inject a 2FA stage or have a different 2FA stage that allows login even if the user does not have 2FA setup.

**Comment by tograss** [comment]
Hi @sdimovv , thank you for your reply. However I'm having problem with two things: First how do I inject a stage ? Do you have an example or is it documented somewhere. I've read https://goauthentik.io/docs/policies/expression but didn't find anything. 

Second problem as the decision which Stage to use happens before the user is fully authenticated i think request.user is the Django anonymous User . Do you know how i excess the object created after username and password is entered but before authorization is completed ?

Thanks for your time and help.

**Comment by tograss** [comment]
Ok I was wrong here. I missed you can bind policies directly to stages.
