### ISSUE TITLE
How do i program authentik that "User1" is the same user as "user1"

### ISSUE THREAD

**Issue by pbvdven** [goauthentik/authentik#5827]
Can anyone tell me how i program authentik "i think its possible but i cant find it" to think that "User1" is the same user as "user1" or "uSer1"?

**Comment by larsl-net** [comment]
@pbvdven in the  `Identifikation Stage` is the Option `Case insensitive matching`. Wich should solve your problem.

**Comment by pbvdven** [comment]
> @pbvdven in the  `Identification Stage` is the Option `Case insensitive matching`. Wich should solve your problem.

Thanks for answering. but then my question is how do i make sure that users can only create upper case usernames in the sign up flow?  that option was checked but users can still create user12 and User12 trough the signup flow it doesn't say user is already existing.

**Comment by pbvdven** [comment]
I checked also the following option Flows & Stages>prompts>default-source-enrolment-field-username>type username "prevents duplicates" this field is the username field in main page enrolment but is does not prevent to a new user to create **U**ser12 but **u**ser12 is already present.

**Comment by larsl-net** [comment]
The field of the type `username` should avoid supposedly duplicates, I would evaluate this here as a bug. Maybe you can catch this with a policy.

**Comment by pbvdven** [comment]
ill report a bug and see if i can set a policy in the mean time. thanks for your time
