### ISSUE TITLE
Dark Color Theme Causes Authentication Text To Be Unreadable

### ISSUE THREAD

**Issue by FirbyKirby** [goauthentik/authentik#5863]
**Describe the bug**
The "Need an Account?" text in the default-authentication-identification stage when the enrollment flow is selected becomes unreadable when the settings.theme.base variable is set to dark, or it's set to automatic (default), and the system theme changes to dark.

**To Reproduce**

1. Ensure the settings.theme.base variable is set to dark, or it's set to automatic and your client system is set to "dark."
2. Update the default-authentication-identification stage with a recovery flow.
3. Execute a flow that includes the default-authentication-identification stage.
4. Observe the "Need an account?" text in the bottom grey box.

**Expected behavior**
The grey box color should be changed. Either a medium grey would work in both light or dark color schemes, or it should change with the theme to a dark grey in the dark color scheme (with white text,) and remain a light grey in the light color scheme.

**Screenshots**
Light Color Scheme (text highlighted with a red box.)
![Screenshot 2023-06-05 at 12 59 48 PM](https://github.com/goauthentik/authentik/assets/17125911/9959e47a-1337-4e5c-9bec-350bf63a8f63)

Dark Color Scheme (text highlighted with a red box.)
![Screenshot 2023-06-05 at 1 15 02 PM](https://github.com/goauthentik/authentik/assets/17125911/a801bb57-5cff-4a0d-8c3d-ecf772ff0303)

**Logs**
No relevant logs.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.3
-   Deployment: Unraid via Docker (not docker-compose)

**Additional context**
None that seems relevent.

**Comment by FirbyKirby** [comment]
Unable to upload screenshots right now due to my location, but I've got them and will post them tonight.

**Comment by manuviens** [comment]
Same thing here with Firefox 113.0.2 and authentik 2023.5.3.
Deployed with the docker-compose.yml at [https://goauthentik.io/docker-compose.yml](https://goauthentik.io/docker-compose.yml).

**Comment by FirbyKirby** [comment]
Good point on reported browser. My issue came up on Firefox too (113.0.1.) But confirmed in Safari 16.3 as well.

**Comment by manuviens** [comment]
I tried to force authentik using the light theme following this part of the doc : [https://goauthentik.io/docs/interfaces/flow/customization](https://goauthentik.io/docs/interfaces/flow/customization)
Not sure if I understood how to do it, but this dosen't seems to work :
![image](https://github.com/goauthentik/authentik/assets/98410832/280461fb-a0b4-48e2-b008-097f11d7bacb)

**Comment by mittler-works** [comment]
@manuviens did you find a way to force the light mode? For me, the settings in Tenant have no effect either.

**Comment by manuviens** [comment]
> @manuviens did you find a way to force the light mode? For me, the settings in Tenant have no effect either.
```
settings:
  theme:
    base: light
```
In the attruibutes of your tenant.
But as you can see in my previous message, it will not entirely correct the problem if you are using Firefox with Website appearance set to Dark like this :
![image](https://github.com/goauthentik/authentik/assets/98410832/8d0fa608-1e33-44fe-afcf-b5e65ab8f989)

**Comment by BeryJu** [comment]
After some testing, this seems to be related with the flow compatibility mode (doesn't show up if compat mode isn't enabled)
