### ISSUE TITLE
Make the input fields detectable by KeePassXC plugin

### ISSUE THREAD

**Issue by tuxmainy** [goauthentik/authentik#5864]
**Is your feature request related to a problem? Please describe.**
When using [KeePassXC](https://github.com/keepassxreboot/keepassxc), one could use the browser extension of KeePassXC to detect logins and request entering of username and password directly from the browser without the need to go into KeePassXC. But somehow (I have no idea why) the input fields of the authentik authentication dialog are not noticed by the plugin which is working very well on other websites.

**Describe the solution you'd like**
Make the input fields detectable by KeePassXC plugin.

**Describe alternatives you've considered**
Opening KeePassXC issue?!

**Comment by manuviens** [comment]
I resolved this issue by going in **Flows & Stages -> Flows**, editing my flows to activate **Compatibility mode** in **Behavior settings**.

**Comment by tuxmainy** [comment]
![grafik](https://github.com/goauthentik/authentik/assets/27895250/07510a86-4ab7-4c92-9b6e-55991cfc1984)

Worked! Thank you a lot.

@manuviens I don't think it needs to be the default. But a more "CLICK HERE TO MAKE IT WORK" hint would be nice. Maybe in the documentation?

Closing anyway because initial request is answered.

**Comment by theRoboxx** [comment]
It worked for me too, thanks a lot :top:

**Comment by gbomacfly** [comment]
> Thanks for sharing this solution! In compatibility mode, the field is recognized when I explicitly right-click it and choose to "Fill username" (wasn't before), but it's still not recognized automatically. Any ideas?

same here, chrome actual on Mac 15.3.1

**Comment by domints** [comment]
It's worth noting, that there's setting in KeePassXC now, that lets it traverse ShadowDOM for given login, which fixes the issue without changing Authentik's behaviour :)
See comments at the bottom of https://github.com/keepassxreboot/keepassxc-browser/issues/1922
