### ISSUE TITLE
custom.css is not applied on 404 Not Found

### ISSUE THREAD

**Issue by coelho** [goauthentik/authentik#5873]
**Describe the bug**
custom.css is not applied on 404 Not Found

**To Reproduce**
Open a URL on Authentik that does not exist

**Expected behavior**
custom.css should apply

**Additional context**
Additionally, custom.css's load order seems funky. You can noticeably see the CSS flicker on refresh. 

> **Cause:** This is because the stylesheet binding in the AKElement is being modified twice (once for main style, again for custom)
> 
> **Solution:**  Should be changed to a 1x modification (only update stylesheets after the custom CSS await), which will also improve page load time since the 2x modifications currently cause 2x layout shift/repaints.

Appreciate your time & thank you to all contributors for your efforts! <3

**Comment by almereyda** [comment]
Possibly a duplicate of #2693.
