### ISSUE TITLE
Allow end users to create app passwords with longer (or no) expiry

### ISSUE THREAD

**Issue by ruifung** [goauthentik/authentik#5881]
**Is your feature request related to a problem? Please describe.**
So I have calibre-web authenticating to authentik via LDAP (for it's OPDS function). With MFA enabled, ideally that would use an app password. However, user created app passwords have a (fixed?) lifetime of 30 minutes which is not ideal for this use case.

**Describe the solution you'd like**
An option to allow users to create longer lived app passwords, or even potentially non-expiring one.

**Describe alternatives you've considered**
Some way to alter the default lifetime of those app passwords, but might not be ideal I suppose.

**Additional context**

**Comment by ekrekeler** [comment]
I second this, right now having no way to extend the expiration past 30 minutes makes App Passwords unusable outside evaluation.

Also if it's not too much trouble, I think it would be a good idea to have a configurable policy for this where administrators can set min/max/default expiration time. Maybe for Tokens too 😄

**Comment by ruifung** [comment]
I'd like to add a note here, the issue is specifically with app passwords created from the *end user* interface.

The creating them from the admin side faces no such limitations. But yes, this effectively renders app passwords all but useless in scenarios where it's an *end user* trying to create the app password.

**Comment by ekrekeler** [comment]
> The creating them from the admin side faces no such limitations.
I didn't even realize you could create them in the admin panel. Thanks for pointing that out!

**Comment by Aljutor** [comment]
Is there any plans for this functionality?
