### ISSUE TITLE
Authentik not "finding" certificates mapped in /certs

### ISSUE THREAD

**Issue by rovingclimber** [goauthentik/authentik#5888]
I'm trying to follow the instructions at https://goauthentik.io/docs/core/certificates regarding adding an external certificate/key pair.

In my docker-compose I have mapped /certs in the worker container to a volume as described (modification of the default compose to use docker-managed volume not mapped to static folder).

```
  worker:
.
.
.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - media:/media
      - certs:/certs
      - templates:/templates
.
.
.
volumes:
  database:
  redis:
  media:
  certs:
  templates:

```

I've sftp'd a valid letsencrypt cert folder to the volume as described:

```
ls -lisa /var/lib/docker/volumes/authentik_certs/_data/auth.mydomain.com/
576278 8 -rw------- 1 root root 5958 Jun  7 14:30 fullchain.pem
577895 4 -rw------- 1 root root 3243 Jun  7 14:30 key.pem

```

However this cert never shows in the UI ... I can only see the default authentik Self-signed Certificate
I've tried lots of things - suggestion to map to /etc/ssl instead, tried different file permissions etc. Just doesn't seem to work as described.

**To Reproduce**
Deploy authentik using default docker-compose.yaml, place letsencrypt cert folder in folder mapped to /certs

**Expected behavior**
Certificate should appear in UI as described in documentation

**Version and Deployment (please complete the following information):**

-   authentik version 2023.5.3
-   Deployment: docker-compose (via Stack in Portainer)

**Comment by aaronnad** [comment]
Experiencing the same issue running version 2023.5.3
Setup certbot to output certs to /certs
```
root@960ff470a482:/certs/live/domain.tld# ls -al
lrwxrwxrwx 1 authentik authentik   47 Jun 18 16:35 cert.pem -> ../../archive/domain.tld/cert1.pem
lrwxrwxrwx 1 authentik authentik   48 Jun 18 16:35 chain.pem -> ../../archive/domain.tld/chain1.pem
lrwxrwxrwx 1 authentik authentik   52 Jun 18 16:35 fullchain.pem -> ../../archive/domain.tld/fullchain1.pem
lrwxrwxrwx 1 authentik authentik   50 Jun 18 16:35 privkey.pem -> ../../archive/domain.tld/privkey1.pem
root@960ff470a482:/certs/livedomain.tld# pwd
/certs/live/domain.tld
```
refreshed the web page and see nothing.

Restarted the worker container, still no improvement
Restarted the full stack and still not seen the certs appear.

When running the command to manually import the certificate, i get the following
```
root@960ff470a482:/certs/live/domain.tld# ak import_certificate --certificate cert.pem --private-key privkey.pem --name test-manual-import
/usr/local/bin/python: No module named manage
```

**Comment by rstrblstr** [comment]
I too am experiencing this.  

`authentik version 2023.5.3`

My /swag/etc/letsencrypt/live folder is mapped to /certs, but the certificate does not show after restart or refresh, and manual imports in the Worker console give the same "No module named manage" error that aaronnad is experiencing.

`    volumes:
      - /share/Data/config/swag/etc/letsencrypt/live/website.com:/certs/website.com`



`root@efd7581e1d07:/certs/website# ls
README  cert.pem  chain.pem  fullchain.pem  priv-fullchain-bundle.pem  privkey.pem  privkey.pfx
root@efd7Q4141jd07:/certs/website# ak import_certificate --certificate fullchain.pem --private-key privkey.pem --name website
/usr/local/bin/python: No module named manage`

**Comment by BeryJu** [comment]
The import_certificate command should be run from the root directory of the container

**Comment by rstrblstr** [comment]
> The import_certificate command should be run from the root directory of the container

interesting.. it does do something different for me here, but still fails to import a cert.  Currently claiming to not see the cert, even though it's confirmed to exist.

```
root@efd7581e1d07:/# ak import_certificate --certificate /certs/website/fullchain.pem --private-key /certs/website/privkey.pem --name website_imported{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832367.4501078, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832367.450976, "count": 16}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.570275, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.571585, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.572598, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.5743587, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.5773337, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.5802772, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.5817933, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.583099, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.5846562, "path": "authentik.stages.authenticator_static.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.5852275, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.5857525, "path": "authentik.stages.authenticator_validate.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.591363, "path": "authentik.blueprints.settings"}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1687832368.591708, "version": "2023.5.3"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1687832368.5925627}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1687832368.59285, "path": "authentik.enterprise.settings"}
{"event": "Failed to load GeoIP database", "exc": "IsADirectoryError(21, 'Is a directory')", "level": "warning", "logger": "authentik.events.geo", "pid": 6968, "timestamp": "2023-06-27T02:19:29.117607"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 6968, "task_id": "59647cbb-6f11-4335-918d-beff12cd5b34", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2023-06-27T02:19:29.938161"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 6968, "task_id": "c04b9a6f-f6e4-4c0e-a6b4-1690aa2a55fa", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2023-06-27T02:19:29.941691"}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/crypto/management/commands/import_certificate.py", line 25, in handle
    with open(options["certificate"], mode="r", encoding="utf-8") as _cert:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/certs/website/fullchain.pem'
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
root@efd7581e1d07:/# 
```

**Comment by BeryJu** [comment]
My suspicion is that the certificate file that shows up is a symbolic link to a file outside the container, can you post the output of `ls -lah /certs/website/fullchain.pem`

**Comment by BeryJu** [comment]
the folder mounted into the container should contain the actual file itself, so try mounting the entire certbot folder into authentik

**Comment by rstrblstr** [comment]
Tried this with the actual cert's folder under /archive, but it's still not showing up.  I presume this is because the cert files here get their filenames appended with a "1".

```
volumes:
      - /swag/etc/letsencrypt/archive/website:/certs/website
```      

```
root@181d0cae5081:/certs/website# ls -l
total 20
-rw-rw----+ 1 authentik authentik 1517 Jun 18 17:22 cert1.pem
-rw-rw----+ 1 authentik authentik 3749 Jun 18 17:22 chain1.pem
-rw-rw----+ 1 authentik authentik 5266 Jun 18 17:22 fullchain1.pem
-rw-------+ 1 authentik authentik  241 Jun 18 17:22 privkey1.pem
```

**Comment by rstrblstr** [comment]
Update:  Manually importing the cert worked after this!  

Now working on trying it out with my oauth provider that kept failing.

```
root@181d0cae5081:/# ak import_certificate --certificate /certs/website/fullchain1.pem --private-key /certs/website/privkey1.pem --name website   
```

<img width="874" alt="Screenshot 2023-06-29 at 1 59 48 PM" src="https://github.com/goauthentik/authentik/assets/26982195/125f0c01-b411-4551-8539-6e67e075d911">

**Comment by Akruidenberg** [comment]
I have the same problem. Authentik did not importing my certs anymore. Adguardhome is reading without problem. Looks like the a bug in Authentik.

**Comment by lekoOwO** [comment]
Same issue here. Though manual import is working.

**Comment by murphysprings** [comment]
> Edit: looks like a permission issue. gives 755 to /certs solves this issue.

Hmm. I've got 755 on /certs and all subdirectories and it doesn't discover, even after redeploying the stack. Still a bug in 2023.08

**Comment by japtain-cack** [comment]
I've been running into all kinds of certificate issues. I use vault to issue short-lived TLS certs and Authentik doesn't like my CA. Anyway, along the path to figuring out that issue, I seemingly solved this one.

Permissions were my issue. In my case, everything is owned by root. So even if you set owner/group perms, it's not enough. You have the set the user permission to at least read. The main directory contains symlinks, but if you look in `..data/`, you can see the actual file permissions.

```
authentik@authentik-server-6ffc44d7bc-bzrgk:/$ ls -l /certs/sso.example.com/
total 0
lrwxrwxrwx 1 root root 34 Oct  8 20:58 ca.example.com.pem -> ..data/ca.example.com.pem
lrwxrwxrwx 1 root root 20 Oct  8 20:58 fullchain.pem -> ..data/fullchain.pem
lrwxrwxrwx 1 root root 35 Oct  8 20:58 sso.example.com.pem -> ..data/sso.example.com.pem
```

looking in `..data/`.
```
ls -l /certs/sso.example.com/..data/
total 24
-rw-r--r-- 1 root root  1444 Oct  8 20:58 ca.example.com.pem
-rw-r--r-- 1 root root 11751 Oct  8 20:58 fullchain.pem
-rw-r--r-- 1 root root  5362 Oct  8 20:58 sso.example.com.pem
```


Using the below volumes/volumeMounts, you can mount a certs directory and define the filenames [based on authentik certificates documentation](https://goauthentik.io/docs/core/certificates#external-certificates). Once I did this, I can run the `certificate_discovery` task, and they all appear. CA cert still doesn't seem to work though and there appears to be no way to import a CA cert into an outpost.
```
volumeMounts:
  - name: authentik-web-tls-volume
    mountPath: /certs/sso.example.com/

volumes:
  - name: authentik-web-tls-volume
    secret:
      secretName: authentik-web-tls
      defaultMode: 0644
      items:
        - key: tls.crt
          path: sso.example.com.pem
        - key: ca.crt
          path: ca.example.com.pem
        - key: tls-combined.pem
          path: fullchain.pem
```

**Comment by Daniel15** [comment]
Make sure you mount both the `live` **and** the `archive directories:
```
      - /etc/letsencrypt/live/auth.example.com:/certs/auth.example.com
      - /etc/letsencrypt/archive/auth.example.com:/archive/auth.example.com
```

that way, the symlinks work properly.

**Comment by GordonFreemanK** [comment]
So the same issue happened to me, and @Daniel15 's solution helped me figure out what was wrong with my setup, because they restrict the subfolder with the certificate and suddenly it works. In my case it's just that the volume I'd mapped to `/certs` contained more than one valid certificate for my domain with the same folder name. I had made a mistake at some point with certbot and there was a valid certificate under `certs/live/example.com` and another one under `certs/certs/live/example.com`.
In your certs folder, you should only see one fullchain.pem and one privkey.pem, **excluding anything with archive in the path**.

The [logic](https://github.com/goauthentik/authentik/blob/1ed69999946c5eb9865bbcd4ae1e66efc64c0f81/authentik/crypto/tasks.py#L41) that detects certificates in the `.certs/` path explores all the files there recursively and sorts them using the name, and the presence of two certificates with the same name throws it.

**Comment by VanCannon** [comment]
I had this issue as well.  version 2025.21.

I could see my certificate listed in the UI under System -> Certificates

So in System->Brands I had to delete the default domain (you may be able to just edit it and flip the default switch for a less drastic approach).

Still in System->Brands -> Create
  - add my domain.  
  - Under Other global settings -> Web certificate I had to enter the name of my cert (that is displayed in System -> Certificates) 
  - Flip the switch here to default.

Finally, sudo docker compose down and sudo docker compose up -d and it took.  Be nice to have that in the documentation.,

![Image](https://github.com/user-attachments/assets/f1c514c4-d05b-4f8e-adf9-55702818dc85)

**Comment by Fuseteam** [comment]
is there a way to check if the worker job to import the certificate is running? it seems manual import is working, but since it is a letsencrypt certificate it is bound to change every 3 months

**Comment by psleep** [comment]
On version 2025.6.3 and I cannot get certificates to be discovered in kubernetes: 
```
volumeMounts:
- mountPath: /certs/wildcard/
  name: wildcard
  readOnly: true 

volumes:
- name: wildcard
   secret: 
     defaultMode: 420
     items:
     - key: tls.crt
       path: tls.pem
     - key: tls.key
       path: key.pem
     secretName: wildcard
```

manual import using ak import_certificate works though but I'd rather not have to manually import each time

**Comment by TomGudman** [comment]
I'd like to confirm @RamonAbudAlcala comment above https://github.com/goauthentik/authentik/issues/5888#issuecomment-2849242995 that the **key MUST be set to 644** or more I guess. 

I tried 600, 640 and it didn't work until I changed perms to 644, despite the files being owned by the authentik user and group. It's unfortunate because it isn't ideal...

I use docker compose and Authentik 2025.6.{3,4} and this is still true. 

**WONT WORK: 600 or 640**
```
authentik@4660fb4ff7a9:/certs$ ls -l
total 8
-rw------- 1 authentik authentik 3243 Jul 24 01:36 foo.key
-rw-r--r-- 1 authentik authentik 1757 Jul 24 01:36 foo.pem
```

**WILL WORK: 644**
```
authentik@4660fb4ff7a9:/certs$ chmod 644 *
authentik@4660fb4ff7a9:/certs$ ls -l
total 8
-rw-r--r-- 1 authentik authentik 3243 Jul 24 01:36 foo.key
-rw-r--r-- 1 authentik authentik 1757 Jul 24 01:36 foo.pem

```

**Comment by Fuseteam** [comment]
seems there is a task called `certificate_discovery` but it is not running for me, i have not found logs on why not

<img width="1311" height="1145" alt="Image" src="https://github.com/user-attachments/assets/a295edeb-4396-4ef0-9fa9-94ae397a9dfe" />

I have the certs in /certs/authentik.domain.tld
```
-rw-r--r-- 1 authentik authentik 1814 Nov  4 00:00 cert.pem                                                                                                               
-rw-r--r-- 1 authentik authentik 1801 Nov  4 00:00 chain.pem
-rw-r--r-- 1 authentik authentik 3615 Nov  4 00:00 fullchain.pem
-rw-r--r-- 1 authentik authentik 1704 Nov  4 00:00 privkey.pem
```
(letsencrypt, but copied over because behind a reverse proxy)

running the import command via cli works
```
root@181d0cae5081:/# ak import_certificate --certificate /certs/authentik.domain.tld/fullchain.pem --private-key /certs/authentik.domain.tld/privkey.pem --name authentik.domain.tld
```

**Comment by Fuseteam** [comment]
found it!
looking through the docker logs of the worker i get this: 
```
{
  "event": "Failed to process message authentik.crypto.tasks.certificate_discovery() with unhandled exception.",
  "exception": [
    {
      "exc_notes": [],
      "exc_type": "IntegrityError",
      "exc_value": "duplicate key value violates unique constraint \"authentik_crypto_certificatekeypair_name_719603a4_uniq\"\nDETAIL:  Key (name)=(authentik.domain.tld) already exists.",
      "exceptions": [],
      "frames": [
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/dramatiq/worker.py",
          "lineno": 487,
          "name": "process_message"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/dramatiq/actor.py",
          "lineno": 185,
          "name": "__call__"
        },
        {
          "filename": "/authentik/crypto/tasks.py",
          "lineno": 85,
          "name": "certificate_discovery"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/models/base.py",
          "lineno": 892,
          "name": "save"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/models/base.py",
          "lineno": 998,
          "name": "save_base"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/models/base.py",
          "lineno": 1161,
          "name": "_save_table"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/models/base.py",
          "lineno": 1202,
          "name": "_do_insert"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/models/manager.py",
          "lineno": 87,
          "name": "manager_method"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/models/query.py",
          "lineno": 1847,
          "name": "_insert"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py",
          "lineno": 1836,
          "name": "execute_sql"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/backends/utils.py",
          "lineno": 79,
          "name": "execute"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/backends/utils.py",
          "lineno": 92,
          "name": "_execute_with_wrappers"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/backends/utils.py",
          "lineno": 100,
          "name": "_execute"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/utils.py",
          "lineno": 91,
          "name": "__exit__"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/backends/utils.py",
          "lineno": 105,
          "name": "_execute"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django_prometheus/db/common.py",
          "lineno": 69,
          "name": "execute"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/psycopg/cursor.py",
          "lineno": 97,
          "name": "execute"
        }
      ],
      "is_cause": false,
      "is_group": false,
      "syntax_error": null
    },
    {
      "exc_notes": [],
      "exc_type": "UniqueViolation",
      "exc_value": "duplicate key value violates unique constraint \"authentik_crypto_certificatekeypair_name_719603a4_uniq\"\nDETAIL:  Key (name)=(authentik.domain.tld) already exists.",
      "exceptions": [],
      "frames": [
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django/db/backends/utils.py",
          "lineno": 105,
          "name": "_execute"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/django_prometheus/db/common.py",
          "lineno": 69,
          "name": "execute"
        },
        {
          "filename": "/ak-root/.venv/lib/python3.13/site-packages/psycopg/cursor.py",
          "lineno": 97,
          "name": "execute"
        }
      ],
      "is_cause": true,
      "is_group": false,
      "syntax_error": null
    }
  ],
  "level": "error",
  "logger": "dramatiq.worker.WorkerThread",
  "timestamp": "2025-11-04T16:37:20.325708"
}
```

this part jumped at me:
```
"duplicate key value violates unique constraint \"authentik_crypto_certificatekeypair_name_719603a4_uniq\"\nDETAIL:  Key (name)=(authentik.domain.tld) already exists."
````
turns out that since i imported via commandline with `--name authentik.domain.tld` the task couldn't import the certs under `/certs/authentik.domain.tld` properly. 

Renaming `authentik.domain.tld` in UI not only allowed the task to run but for it to actually import the files in `/certs/authentik.domain.tld`. This means that the manually imported one could then be deleted
