### ISSUE TITLE
Embedded proxy redirects to authentik_host, not authentik_host_browser

### ISSUE THREAD

**Issue by btrepp** [goauthentik/authentik#5922]
**Describe the bug**

With the embedded outpost configured with a host browser option and host configured, it redirects the user to the host, not host_browser.

This is a bit surprising as the k8s services can't be made accessible, and the doc implies the browser key is for specifying the browser based urls.

**To Reproduce**

```
authentik_host: http://authentik.system.svc.cluster.local
authentik_host_browser: https://authentik.externaldomain.com
```

```
curl -v https://authentik.externaldomain.com/outpost.goauthentik.io/auth/traefik
```

**Expected behavior**
Redirect is to url based on authentik.externaldomain.com

It currently redirects to authentik.system.svc.cluster.local. Which isn't externally accessible

**Screenshots**

**Logs**

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
2023.5.2
-   Deployment: [e.g. docker-compose, helm]
kustomize

**Additional context**

Examples seem to reference the internal k8s services a lot, so it's also a bit confusing to pin this down.

Reading comments in the code, it does appear that this is by design, but it does make it interesting.

When configuring forward auth, and having single app forwarding, that means all urls must be external, even to the one in the cluster. It's kinda awkward as you would have a k8s service right there, but I don't think you can use that, as it causes redirect loops.

Ideally if authentik_host_browser was honoured in the embedded outpost, you could probably use k8s services internally for the most part, ad the browser host for the user part

**Comment by btrepp** [comment]
Current workaround for me is to stand up a outpost, which works mainly as expected.

**Comment by eulores** [comment]
I was hit by the same problem with version 2024.6.1.
The variable `authentik_host_browser` is being ignored for embedded outpost.
