### ISSUE TITLE
Help on LDAP provider 

### ISSUE THREAD

**Issue by bloodyburger** [goauthentik/authentik#5923]
I setup Authentik on a DO droplet and configured firewall to allow 389 and 636. Created LDAP provider and app and all works fine when I do ldapsearch from the machine where Authentik is running. However, when I do ```ldapsearch -x -h ldap://1x.x.x.x -p 636 -D "cn=ldapservice,ou=users,DC=ldap,DC=goauthentik,DC=io" -b 'DC=ldap,DC=goauthentik,DC=io' '(objectClass=user)' -W```  using the external IP from another machine I get error ```ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)```.

**Comment by joshuakraitberg** [comment]
You can do `nc -v {ip/hostname} 636` from the other machine to check if the port is open.

**Comment by bloodyburger** [comment]
It works, says connection succeeded but the ```ldapsearch``` command doesnt work, nevermind , I can connect to ldap from the application anyhow and now getting ```The username "akadmin" was not found in the LDAP directory```

**Comment by vherrlein** [comment]
Hi,
Did you setup the LDAP Auth Flow for your service account ?

![](https://goauthentik.io/assets/images/general_setup15-b985f95bee2173d7530f58a3edb28e83.png)

By default you can’t perform search queries.

Please read carefully the documentation here : https://goauthentik.io/docs/providers/ldap/generic_setup#create-ldap-provider

**Comment by bloodyburger** [comment]
Thanks @vherrlein I just recreated the same steps as documented and it works fine now with Jellyfin.

**Comment by rqi14** [comment]
> ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

Hi. Do you mind sharing how you solved the `ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)` error?

**Comment by Ard3ny** [comment]
Also getting `ldap_result: Can't contact LDAP server (-1)`

**Comment by MarcPartensky** [comment]
Use LDAPTLS_REQCERT=never

**Comment by skillcodeone** [comment]
> Use LDAPTLS_REQCERT=never

Hi Marc, 

sorry where i need to set this variable? In ldapsearch command i can't use it

thanks
