### ISSUE TITLE
Poor performance on User page when a file is involved.

### ISSUE THREAD

**Issue by xNinjaKittyx** [goauthentik/authentik#5942]
**Describe the bug**

I noticed when trying to setup avatars, that when you upload an avatar, it ends up lagging the user page pretty significantly. Sometimes the group list page also lags as well... And this is for just one user with a 1-2MB profile picture.

```/if/admin/#/identity/users/1;{"page"%3A"page-overview"}```

My guess is that when loading the list of attributes, because it's spitting out the entire data as base64, that causes some lag.

Might be tangentially related to https://github.com/goauthentik/authentik/issues/2631 since one of the ways that might fix this is to have the file uploaded then have some way of referencing it either via file or api endpoints.

I'm fairly new to this project, so please let me know if I'm misunderstanding.

**To Reproduce**

1. Went to Flows -> default-user-settings-flows -> stage bindings -> Edit Stage Bindings -> Fields Create
```
name: avatar
field key: attributes.avatar
label: avatar
type: File
```
2. Selected the new field in the stage binding -> Update
3. Open UI -> Settings -> Upload an Avatar -> Save
4. Go to Users -> Admin... You can tell the page takes some time to load.

**Expected behavior**

I don't think it's normal for it to be this bad. It takes like several seconds.

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.3
-   Deployment: docker + unraid

**Additional context**

**Comment by drpetersen** [comment]
@xNinjaKittyx: Not sure if this is still of interest to you, but I have encountered the same problem, and come up with [this solution](https://github.com/goauthentik/authentik/discussions/6824).
