### ISSUE TITLE
Unable to download SAML metadata

### ISSUE THREAD

**Issue by bloodyburger** [goauthentik/authentik#5962]
I'm on latest version, running on docker and trying to configure SAML with new AWS Identity Center.
Followed the guide and created provider and application. When I click on "Download" under related objects, I get Server Error.
and checking docker logs of authentik server, I see this
```
{"event": "Internal Server Error: /api/v3/providers/saml/5/metadata/", "exc_info": ["<class 'xmlsec.Error'>", "Error(1, 'failed to sign')", "<traceback object at 0x7f49257a2f00>"], "level": "error", "logger": "django.request", "timestamp": 1686762890.8613932}
```

**Comment by BeryJu** [comment]
fixed by #9537
