### ISSUE TITLE
How to use reCaptcha v3 with authentik

### ISSUE THREAD

**Issue by tograss** [goauthentik/authentik#5971]
**Describe your question/**
How do I protect user login with a captcha ?
**Relevant infos**
I tried to protect user logins with a captcha. Therefore I created a new captcha stage and added the stage to the default-login-flow. However I was only able to create a reCaptcha Enterpreise api key (v3). I entered the credentials and it seams working, the reCaptcha logo appears on the login site. However, accesses is never blocked and I'm not forced to solve a captcha, even when creating a test key which always returns 0 (the highest risk) 
Further I struggle to see how authentiks reputation policy comes into play with reCaptcha v3 
Any tipp how to get a captcha in front of the login is greatly appreciated

**Comment by rucciva** [comment]
i'm seeing problem too with the captcha stage. when i add captcha stage before login form, the login form is still susceptible to brute force attack by calling the login API directly with cookie obtained after loading the login page
