### ISSUE TITLE
User dashboard application list can show wrong applications when tenant-based policies are used

### ISSUE THREAD

**Issue by ruifung** [goauthentik/authentik#6020]
**Describe the bug**
When applying policies that decides by tenant domain / attributes. The "My Applications" listing in the "User Interface" will show the set of applications based on the last tenant accessed by the user.

**To Reproduce**
Assuming
Tenant A (Default) is at auth.services.home.example.com
Tenant B is at auth-home.example.com

1. Create application A accessible only to Tenant A (expression policy)
2. Create application B accessible only to Tenant B (expression policy)
3. Log in to tenant A on device 1.
4. Observe that the "My applications" list shows application A.
5. Log in to tenant B on device 2.
6. Observe that the "My applications" list shows application B.
7. Refresh the page ("My applications") on device 1.
8. Observe that the "My applications" page via Tenant A on device 1 now shows application B.

**Expected behavior**
For the "My applications" listing to show the correct applications based on the current tenant.

**Screenshots**
Not applicable.

**Logs**
Not applicable.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.3
-   Deployment: helm

**Additional context**
I'll note that it doesn't seem to affect actual policy decisions, since I'm still able to access the applications via the appropriate tenant regardless of what the user dashboard shows.

My primary use case for this is that I use different domains for accessing applications while at home and outside, and was trying to make the inaccessible applications not show up when they are inaccessible (using external tenant).

I imagine this would also affect it when policies that are based on IP address are being used, and there are multiple simultaneous sessions from different IP addresses.

**Comment by BeryJu** [comment]
This is somewhat intended as the application list is one of the slowest views (since the policy engine cannot run in parallel). A workaround might be to only cache the application list per session ID which will be different for each domain and different devices, however it would also decrease the cache effectiveness. This shouldn’t really matter for a small ish number of applications, but for anything > 20 applications it could lead to some quite slow application list calls
