### ISSUE TITLE
Authentik crash because no more connections slots are available to database

### ISSUE THREAD

**Issue by balucio** [goauthentik/authentik#6029]
After some hours the Authentik fills database with multiple connections, those connections are not closed and database will not accept more connections (`max_connections` is set to `1000`).

```
FATAL:  remaining connection slots are reserved for non-replication superuser connections
```
Database idle query
```
023-06-21 07:23:18.294086+00
 1174759 | 16384 | authentik | UPDATE "authentik_core_user" SET "password" = '************************************************', "last_login" = NULL, "username" = 'ak-outpost-deb914dcb7dc42e5bef0572fdf447c97', "first_nam
e" = '', "last_name" = '', "email" = '', "is_active" = true, "date_joined" = '2023-03-09T14:34:44.907452+00:00'::timestamptz, "uuid" = 'f2cb8950-b2ea-4002-ac69-8dadae9c9f31'::uuid, "name" = 'Outpost authentik Embe
dded Outpost Service-Account', "path" = 'goauthentik.io/outposts', "password_change_date" = '2023-03-09T14:34:44.907823+00:00'::timestamptz, "attributes" = '{"goauthentik.io/user/override-ips": true, "goauthentik.
io/user/service-account": true}' WHERE "authentik_core_user"."id" = 3                                                                                                                                                
```

I set a postgresql master/replica using docker.

**Comment by gmemstr** [comment]
I think it's worth reopening this. I've noted authentik slowly fills up idle database connections over time, with `ghcr.io/goauthentik/server:2023.10.4`. As part of some troubleshooting I got my PostgreSQL metrics setup and observed the following

![image](https://github.com/goauthentik/authentik/assets/1878840/69afc58e-a346-4fe9-9001-026fa795a8b8)

I can't figure out *why* it's taking so many connections - going off the worker and web threads/concurrency numbers, they don't add up.

**Comment by anony253** [comment]
I also have the same problem, present on 2025.8.1
Can we figure out what is causing this and how to resolve it ?

**Comment by Bleala** [comment]
Same problem here since 2025.8.1

**Comment by SisyphusMD** [comment]
Same problem here when scaling worker replicas to 3 via helm chart in 2025.10.1, pointed at a cnpg PostgreSQL database.

**Comment by impcyber** [comment]
Same problem 2025.10.3 with external Postgres

**Comment by balucio** [comment]
The problem still exists... https://github.com/goauthentik/authentik/issues/7965

**Comment by joaoffs** [comment]
Ran into this on 2025.12

**Comment by mpflanzer** [comment]
I just observed it after upgrading to 2026.2. In my case it's the worker using up all the connections with this query:

```
INSERT INTO "django_channels_postgres_message" ("id", "channel", "message", "expires") VALUES ($1, $2, $3, $4)
```

**Comment by ednxzu** [comment]
Observing the same behavior as above, upgrade to 2026.2, worker uses up all the connections.

**Comment by tomorrow-nf** [comment]
I'm seeing the exact same thing after upgrading to 2026.2. Consistently occurs every time the containers are restarted.

**Comment by tomorrow-nf** [comment]
Issue still occurs in 2026.2.1

Increasing max connections on the postgres container seems to have "solved" this for now
`command: -c 'max_connections=500'
`
