### ISSUE TITLE
User synchronization from MS Active Directory too slow

### ISSUE THREAD

**Issue by medir** [goauthentik/authentik#6052]
**Describe your question/**
We are trying to sync users using "Federation & social logins" against an Active Directory (Windows Server 2016) . We are running Authentik with the default docker compose (1 redis, 1pg, 1 server and 1 worker) and we want to synchronize 9k users but the process is too slow, approximately 1.2 users / second.

We have tried to add more workers (12) but we have not noticed any speed improvement. Is there any kind of configuration that could improve the synchronization speed?

Maybe the only solution is the one proposed in [this enhancement.](https://github.com/goauthentik/authentik/issues/4391)

**Relevant infos**

-   Host OS: Ubuntu 22.04 LTS
-   Docker version: Docker version 20.10.17, build 100c701
-   Docker compose version: docker-compose version 1.29.2, build unknown

**Version and Deployment (please complete the following information):**

-   authentik version: 2021.5.3
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
The main reason why the sync speed doesn't scale with more workers is because the sync happens in a single task (well, there's a task for user sync, group sync and membership sync)
