### ISSUE TITLE
How to whitelist allowed list of email domains in Authentik?

### ISSUE THREAD

**Issue by devadattas** [goauthentik/authentik#6068]
**Describe your question/**
How to whitelist allowed list of email domains in Authentik? We currently use Google Auth with Authentik and wish to restrict creation of Authentik accounts to specific email domains like `example.com` and `example.net`. Any other domain should raise an error.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.4
-   Deployment: docker-compose

**Comment by Bivab0** [comment]
Hello @devadattas 

Here is a solution by modifying the default policy named `default-source-enrollment-if-sso`

change the default codes like follows
```
allowed_domains = ["example.net", "example.com"]
current_domain =request.context["prompt_data"]["email"].split("@")[1]
if current_domain in allowed_domains:
  email = request.context["prompt_data"]["email"]
  request.context["prompt_data"]["username"] = email
  return ak_is_sso_flow
else:
  return ak_message("Access denied for this email domain")
 ```
 
 If your email is in the allowed domain you can log in using Google Oauth2, else you will get access denied.
 
 I have attached some screenshots below.
 
 You can find the policy here
![Screenshot from 2023-06-28 10-19-57](https://github.com/goauthentik/authentik/assets/96464808/94c9fd69-a52d-4fae-b5c0-e3272043c977)

 Update the expression as follows
![Screenshot from 2023-06-28 10-24-12](https://github.com/goauthentik/authentik/assets/96464808/38ec8084-ecb2-421b-a77f-11cf4d69726c)

If your email domain is in the allowed domain you will get the following output screen
![Screenshot from 2023-06-28 10-18-32](https://github.com/goauthentik/authentik/assets/96464808/9c157e65-399c-4d30-b2ec-0981cc06e19e)

If your email domain is not in the allowed domain list you will get the following 
![Screenshot from 2023-06-28 10-19-28](https://github.com/goauthentik/authentik/assets/96464808/523a39c9-fe2b-4a1e-8bf7-768e7ff78d55)

**Comment by rkhirata** [comment]
> Bivab0

I used the code above on one of my policies (enrollment-email-domain-verification). However, when clicking on "sign-up", I get the error "Request has been denied" / "Flow does not apply to current user."

I need to force users to create accounts with just one single e-mail domain.

I also read these 2:
https://docs.goauthentik.io/docs/customize/policies/working_with_policies/whitelist_email
https://docs.goauthentik.io/docs/customize/policies/expression#variables

However, I couldn't figure out what is wrong.

Can anyone help me?

![image](https://github.com/user-attachments/assets/9b6558fd-3ddf-4b86-b17a-f258ee026896)
![image](https://github.com/user-attachments/assets/0771f2c6-2c20-4d95-a7c5-a6b12cc412ac)

**Comment by devadattas** [comment]
Updated code:

Policy **`default-source-authentication-if-sso`**:
```python
# This policy ensures that this flow can only be used when the user
# is in a SSO Flow (meaning they come from an external IdP)
allowed_domains = ["domain1.com", "domain2.com", "domain3.com"]
current_domain = request.user.email.split("@")[1] if hasattr(request.user, 'email') and request.user.email else None
if current_domain in allowed_domains:
  return ak_is_sso_flow
else:
  return ak_message("Authentication denied for this email domain")
```

Policy **`default-source-enrollment-if-sso`**:
```python
# This policy ensures that this flow can only be used when the user
# is in a SSO Flow (meaning they come from an external IdP)
allowed_domains = ["domain1.com", "domain2.com", "domain3.com"]
current_domain = request.context["prompt_data"]["email"].split("@")[1] if request.context.get("prompt_data", {}).get("email") else None
if current_domain in allowed_domains:
  email = request.context["prompt_data"]["email"]
  request.context["prompt_data"]["username"] = email
  return ak_is_sso_flow
else:
  return ak_message("Enrollment denied for this email domain")
```
