### ISSUE TITLE
Allow to configure k8 tolerations for proxy outposts

### ISSUE THREAD

**Issue by benedikt-bartscher** [goauthentik/authentik#6078]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to configure k8 tolerations for Authentik managed proxy deployments.

**Describe the solution you'd like**
Add an attribute to configure tolerations.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by BeryJu** [comment]
See #5938 and #5908
