### ISSUE TITLE
How to get/send user attributes based RADIUS?

### ISSUE THREAD

**Issue by CygnusHyoga** [goauthentik/authentik#6091]
**Describe your question/**

I'm trying to configure RADIUS provider/outpost to authenticate APC UPS (with apc management card).  I can login to the UPS correctly via authentik radius provider, as read-only user, but I can't get/send the correct privileges for admin role.

For read only-user the ups expect APC-Service-Type = 3 (default) and for admin expect APC-Service-Type = 1.

admin Cleartext-Password := "123qwe.."
        APC-Service-Type = 1

bruno Cleartext-Password := "boss123"
        APC-Service-Type = 3

The user account named Admin will have administrative permission over the APC UPS.
The user account named Bruno will have read-only permission over the APC UPS.

 I want to be an Admin user, how to get/send user attributes based RADIUS on authentik?

Thanks!

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.3
-   Deployment:  helm
-   Kubernetes Version: v1.27.3+k3s1

**Comment by nikdoof** [comment]
I don't think this is currently supported, I looked at the code and I think it just returns a success without any way to provide extra attributes. It would be a useful feature, especially for Cisco IOS kit, as you need to provide `cisco-av-pair` to deal out permissions.
