### ISSUE TITLE
context['application'] does not exist in expression policies

### ISSUE THREAD

**Issue by RobotHanzo** [goauthentik/authentik#6112]
**Describe the bug**
As indicated in the documentation (https://goauthentik.io/docs/policies/expression#variables), there is supposed to a key called `application` in the `context` when evaluating an application's policy binding.
However, that is not the case, accessing `context['application'] ` will raise a `KeyError` and `"application" in context` returns False

**To Reproduce**
1. Create a policy binding in an application that tries to access `context['application'] `
2. Open the user interface page or use the test button to check access
3. It fails

**Expected behavior**
There is supposed to a key called `application` in the `context` when evaluating an application's policy binding.

**Raw Context specified in logs**
```
{
    "geo": {
Redacted
    },
    "result": {
        "passing": true,
        "messages": [],
        "raw_result": true,
        "log_messages": [],
        "source_binding": null,
        "source_results": []
    },
    "binding": {
        "pk": "3a12e320b2214b2da24aa06eb6db388b",
        "app": "authentik_policies",
        "name": "Binding from CDN #0 to Policy scopes-privilege-checker",
        "model_name": "policybinding"
    },
    "message": "Policy Execution",
    "request": {
        "obj": {
            "pk": "96a9548857cf47b29911d64d95bca681",
            "app": "authentik_core",
            "name": "CDN",
            "model_name": "application"
        },
        "user": {
            "pk": 4,
            "email": "Redacted",
            "username": "robothanzo"
        },
        "debug": false,
        "context": {
            "geoip": {
Redacted
            }
        },
        "http_request": null
    },
    "policy_uuid": "79f733f4000444a99fc4c78a529dbb39",
    "http_request": {
        "args": {},
        "path": "/api/v3/core/applications/",
        "method": "GET"
    }
}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.4
-   Deployment: docker-compose

**Comment by RobotHanzo** [comment]
This issue still persists

**Comment by BeryJu** [comment]
You can use `request.obj` which is the application/source/flow/etc that the policy is run against, the docs need an update to reflect this better

**Comment by wiktormalyska** [comment]
There is no request.obj documentation at all, logging within policy testing gives null for this object
