### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by Spark61** [goauthentik/authentik#6116]
**Describe the bug**
If I add this URL to the redirect URL I get a Forbidden Response http://localhost:8080/login/oauth2/code/authentik
if I replace the http with https, the request will work

**To Reproduce**
Go on this URL:
https://MY_COOL_PROVIDER.de/application/o/authorize/?response_type=code&client_id=xxxx&scope=openid%20profile%20email&redirect_uri=http://localhost:8080/login/oauth2/code/authentik

You see a forbidden response

If you use this url, there is a correct server response:
https://MY_COOL_PROVIDER.de/application/o/authorize/?response_type=code&client_id=xxxx&scope=openid%20profile%20email&redirect_uri=https://localhost:8080/login/oauth2/code/authentik

**Expected behavior**
Get no forbidden response

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/28624736/d5603969-6035-427a-b874-6d91d1b8f156)

**Version and Deployment (please complete the following information):**

-   authentik version:  2023.5.4
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
That 403 response does not come from authentik, the response from authentik would have a custom error page, and also a matching entry in the server containers' logs

I could imagine that the 403 comes from some sort of web filtering that detects the `http://`? Which reverse proxy are you using? Are you using cloudflare/anything similar?
