### ISSUE TITLE
Authentik not sending saml attribute

### ISSUE THREAD

**Issue by thestarrypage** [goauthentik/authentik#6118]
**Describe your question/**
I am using SSO SAML integration with cloudflare zerotrust dashboard.
however it doesn't sent any attribute to cloudflare even when i set a group for the user

**Relevant infos**
i.e. Version of other software you're using, specifics of your setup
2023.5.4

**Screenshots**

![](https://i.imgur.com/VTvMAeR.png)

[https://i.imgur.com/VTvMAeR.png](url)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
-   Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by sloanja** [comment]
I believe it should be lowercase "groups".

**Comment by BeryJu** [comment]
You'll have to create a SAML property mapping, the `attributes` attribute of a user is not sent as-is to any SAML application; see https://docs.goauthentik.io/integrations/services/aws/#role-mapping
