### ISSUE TITLE
User settings flow errors out on email confirmation stage for non superusers.

### ISSUE THREAD

**Issue by bpsanto** [goauthentik/authentik#6123]
**Describe the bug**
Adding an email confirmation stage between the prompt and write stages of user settings makes the whole flow error out with `No pending user` shown in a notification modal in the upper right corner.

The email confirmation stage is never reached and no email is sent.

For superusers the email confirmation stage acts as intended.

**To Reproduce**
Listing something similar to my actual context in case checking with the default flow won't reproduce the issue.

PREP:
1. prep a non superuser `testuser` 
2. prep 4 groups `g1`, `g2`, `g3`, `g4` of which `g4` is a superuser group
3. add default superuser to  group `g4` and `testuser` to `g1`
4. have two prompt stages A and B ordered sequentially; 
both with 'any' for policy match;
stage `A` has `g1` and `g2` bound;
stage `B` has `g3` and `g4` bound.
5. add an email confirmation stage right after the prompt stage(s) and before the write stage

TEST1 - what should happen for all users:
1. As superuser go to user settings
2. Attempt to change email
3. Email resend button is shown and email is properly sent
4. Clicking on the link in the email allows the write stage to update the email

TEST2 - what happens for regular users:
1. As `testuser` go to user settings
2. Attempt to change email
3. Flow ends with the `no pending user` error shown in a modal and the form is reloaded to show an `open settings` button - similar to when the user would lack access to the user settings flow completely.
4. On a page refresh the form is again visible

TEST3 - to confirm it is not an issue with that particular prompt stage:
1. replace the group for `testuser` from `g1` to `g3`
2. go to settings page and see the alternate prompt only available to g3 and g4 groups which the superuser managed to operate just fine in TEST1
3. observe exact same situation otherwise as with TEST2

Additionally (removed for the above tests) I have an expression policy that checks if email field differs, bound to the email confirmation stage:
With it enabled, if the email is not changed, we avoid the email confirmation stage and flow completes properly.
With it enabled, if the email is changed, situation is as described in tests above.
With it disabled, situation is again same as described.

**Expected behavior**
For it to work for regular users as it does for the superuser

**Screenshots**
non applicable

**Logs**
nothing relevant that authentik considers log worthy - did not crawl through docker logs though

**Version and Deployment (please complete the following information):**
-   authentik version: 2023.5.4
-   Deployment: docker-compose

**Additional context**
Client: Debian 12 / Wayland / KDE / 2560 x 1600 / Firefox-ESR / 133% scale
Host: Authentik>localhost:80>cloudflare tunnel>cloudflare proxy terminating TLS

**Comment by asifbacchus** [comment]
Just noticed this situation also. Seems `request.context['pending_user']` doesn't exist for non-superuser accounts in this situation. Also, an email destination cannot be set manually as suggested in the documentation (https://goauthentik.io/docs/flow/stages/email/#behaviour).

Is this a bug? Is there a workaround?
