### ISSUE TITLE
2023.6.0 LDAP query stop working i can connect but but not filter pve, jellyfin, calibre and linux all the same

### ISSUE THREAD

**Issue by pbvdven** [goauthentik/authentik#6195]
Ldap filters stopt working i can do base search but not filter its all comes up empty with alle programs proxmox jellyfin calibre connections seems to be fine base search also but filters wont show up anything

for jellyfin use these 2 with 2023.5.5 it shows 17 users 3admins and on 2023.6.0 it shows 0 users 0 admins 
user filter
(memberOf=cn=users,ou=groups,DC=ldap,DC=pbvdven,DC=nl)
admin filter
(memberOf=cn=admins,ou=groups,DC=ldap,DC=pbvdven,DC=nl)

Also proxmox cant sync users and groups from ldap anymore all comes up empty in 2023.6.0
no filters used just full sync.

I did not see anyone else complain so maybe there where some changes in 2023.6.0 but i could find any news about it.

**Comment by Chifilly** [comment]
I have the same issue. After updating Authentik, Nextcloud and Jellyfin can no longer find users

**Comment by MegaShinySnivy** [comment]
Myself as well, I had to downgrade.

**Comment by grepler** [comment]
Same on my end, sonatype nexus cannot query ldap for users.

**Comment by agent-squirrel** [comment]
Confirmed, this appears to be an issue with 2023.6.0. Rolling back to 2023.5.5 fixes the issue.
The following image is the log from Jellyfin.
![image](https://github.com/goauthentik/authentik/assets/10679391/a096d812-60fe-48d2-9154-0cd31bce5491)

I didn't have Authentik's logging set to anything higher than info before rolling back but if you would like more info I can update and change logging to debug.

**Comment by Svenum** [comment]
Same Here with Nextcloud and JellyFin

**Comment by BeryJu** [comment]
this should be fixed by #6188, please try the beta (just using the beta outpost image is fine, ghcr.io/goauthentik/dev-ldap:gh-next), we'll release 2023.6.1 later today
