### ISSUE TITLE
API GET /core/users/ with uuid filter leads to (500) internal server error

### ISSUE THREAD

**Issue by horego** [goauthentik/authentik#6201]
**Describe the bug**
Hello everyone i'm currently struggeling with the API. Regarding the API documentation the API method "GET /core/users/" describes different kind of filtering mechanism. One is  by using the http query parameter "uuid (string)" which should filter the user by the uid.

But whenever i'm using this parameter i end up getting an internal server error (500). I need to retreive the user by it's uid (not the internal pk (int)). For me it looks like a bug. Can u help me with that? other parameters like search and username are working as expected.

**To Reproduce**

1. Install Authentik
2. Execute an GET request i.e.
`"http://localhost:9000/api/v3/core/users/?uuid=8d5440262e02c36a33dd9d78c5aea0d77cec0ab7a11848364e64919734fc30db"
`or
`Use the api web interface http://localhost:9000/api/v3
`

**Expected behavior**
Return the users machting the applied uid filter.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.6.0 (latest). Also tried some older versions without success.
-   Deployed with docker-compose (latest)

i hope everything is explained clearly. 
Best regards

**Comment by horego** [comment]
Hey @BeryJu thx for resolving this fast. I applied the changes you made within your commit locally. Now i end up with

```
{
  "uuid": [
    "Enter a valid UUID."
  ]
}

```

For me the uuid looks valid. I copy pasted it from the users response (uid). Example:

```
...
"uid": "0a35f5e72e484a1904f0b23be304eb47c6517f2d7875c520bff882abf1912feb",
"path": "users"
...
```

**Comment by BeryJu** [comment]
`uid` is not a uuid, it's a generic unique ID
