### ISSUE TITLE
Authentik spams my mailbox / Celery problem?

### ISSUE THREAD

**Issue by vschwaberow** [goauthentik/authentik#6216]
**Describe your question/**
Authentik spams my email mailbox with "email_sent" notifications

worker_1 seems to spam as well

451f-4369-a9bf-5ba55a3f7be7", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.211577"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18849, "state": "SUCCESS", "task_id": "95901b62-451f-4369-a9bf-5ba55a3f7be7", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.226287"}
worker_1      | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 18850, "task_id": "7ab385a7-33a6-4f4d-b784-c69960407a5a", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.327314"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18850, "state": "SUCCESS", "task_id": "7ab385a7-33a6-4f4d-b784-c69960407a5a", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.343296"}
worker_1      | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 18851, "task_id": "3168656b-b1b3-4e26-8a1b-46905e4fae26", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.351203"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18851, "state": "SUCCESS", "task_id": "3168656b-b1b3-4e26-8a1b-46905e4fae26", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.366109"}
worker_1      | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 18855, "task_id": "6c03d9de-92e1-4c71-82c8-5ede0e5f45e0", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.637823"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18855, "state": "SUCCESS", "task_id": "6c03d9de-92e1-4c71-82c8-5ede0e5f45e0", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.654259"}
worker_1      | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 18856, "task_id": "8e689914-10da-4f10-a34e-970b38751775", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.756440"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18856, "state": "SUCCESS", "task_id": "8e689914-10da-4f10-a34e-970b38751775", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.772324"}
worker_1      | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 18857, "task_id": "746c4c8f-1c66-4d8e-8570-539921b5d67d", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.780166"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18857, "state": "SUCCESS", "task_id": "746c4c8f-1c66-4d8e-8570-539921b5d67d", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:46.795025"}
worker_1      | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 18861, "task_id": "4648d35e-f750-4635-bd8b-4e047a00d1f1", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:47.068599"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18861, "state": "SUCCESS", "task_id": "4648d35e-f750-4635-bd8b-4e047a00d1f1", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:47.086481"}
worker_1      | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 18862, "task_id": "83267c58-e0d5-44d9-a861-fb660d3688df", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:47.189975"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18862, "state": "SUCCESS", "task_id": "83267c58-e0d5-44d9-a861-fb660d3688df", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:47.205362"}
worker_1      | {"event": "Task started", "level": "info", "logger": "authentik.root.celery", "pid": 18863, "task_id": "8c95d901-7a2d-4b81-a2fb-21496260e149", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:47.214681"}
worker_1      | {"event": "Task finished", "level": "info", "logger": "authentik.root.celery", "pid": 18863, "state": "SUCCESS", "task_id": "8c95d901-7a2d-4b81-a2fb-21496260e149", "task_name": "notification_transport", "timestamp": "2023-07-11T12:52:47.229176"}

How can I fix this?

**Relevant infos**
Latest

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.6.1
-   Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
Is this an upgraded instance or an install from scratch?

**Comment by df503** [comment]
Mine started spamming last night around 11pm PST. Even after upgrading from 2023.6.0 to 2023.6.1 first thing, the spam emails are still coming in. I went into the notification settings and deactivated all notifications and it is still spamming both associated admin email addresses. I might just have to block the authentik server IP address from my local email server to get some relief.

**Comment by BeryJu** [comment]
Could you post screenshots of the policies you have attached to your notification rules? I'm wondering if this is a bug in the event matcher policy or if something didn't get migrated correctly

**Comment by df503** [comment]
<img width="1302" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/48989e29-cfe9-49f0-9bca-a2b41c45dc6e">

<img width="1321" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/16c5c18e-ee67-4201-99be-c4905ffa69eb">

it was still sending even after disabling all the notification in the web gui. I commented out the SMTP server and port in my .env file temporarily. I believe it was sending every 30 seconds.

**Comment by df503** [comment]
<img width="1110" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/d5b02a5f-0a1a-46db-bdf5-8449ff60f485">

it appears to be a notification of sending an email to both of my admin registered email addresses. It might be stuck in a loop if its notifying the admins that an email to the admins has been sent.

**Comment by df503** [comment]
Here are the screenshots of the notification policy details.

<img width="1093" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/77f6505e-660c-495d-a38e-c5319c1a15e5">


<img width="1096" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/9dc93f54-71e8-4ea7-b341-91244893bdf7">

<img width="1093" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/7b431a00-e089-441d-890b-9e52f78591be">

<img width="1092" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/17a96763-73be-458d-ac74-39da08a746c2">

**Comment by df503** [comment]
My internal SMTP server settings must be cached somewhere because I'm still getting emails sent to my on-prem email server 40 minutes after removing the SMTP details from my .env file and doing a docker compose down and them docker compose up -d

**Comment by BeryJu** [comment]
One last question that might be a bit harder to find out (but should help fix this), what did the first email contain? It's pretty clear that the emails are triggered by some notification rule policy, so it would be really helpful to see the first policy/trigger that caused this to see where the error is exactly

**Comment by df503** [comment]
I went into my deleted items and recovered the earliest deleted email. It showed 4:19am but I recalled seeing them start at 11pm last night, so the date time stamps are a little off in my estimation. Here is the contents of the first email received.

<img width="561" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/b4039865-a050-4d61-8ef2-c310ddb10424">

**Comment by df503** [comment]
Then the next email was the following. And this is the one that starts repeating indefinately: 

<img width="692" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/b58e791b-a8de-4604-ba9a-c7ddd3c243be">

<img width="691" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/dea4e80a-d9cf-4723-8e90-39298df955ae">

<img width="687" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/cba6b2bc-d3bd-4d99-b8a0-32b4d8db9850">

<img width="697" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/822a251f-5711-469d-a503-656c264f6186">

**Comment by BeryJu** [comment]
@df503 and the screenshots above are all the notification rules you have, correct?

**Comment by df503** [comment]
> @df503 and the screenshots above are all the notification rules you have, correct?

Correct.

**Comment by BeryJu** [comment]
So it looks like a bug in the event matcher policy triggering for other events that it shouldn't, but I can't reproduce this locally, all events I create just create 1 notification and trigger the policies once, including `email_sent`

**Comment by df503** [comment]
Maybe the fact I have a second member of the akadmin group is the key to replicate.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shmanubhav** [comment]
I also faced the same issue and provided some more detailed in a previously filed bug: https://github.com/goauthentik/authentik/issues/6196. Several other folks are facing it too. I am using the default email transport with globally configured smtp settings as previous running versions.

**Comment by df503** [comment]
Oh wow, I never noticed the worker version before you mentioned it. I was manually updating the version in the docker-compose and I missed the worker container. I'm just going to default them to latest.

<img width="699" alt="image" src="https://github.com/goauthentik/authentik/assets/121280101/2c7f2fda-6e7a-4ef1-800d-3cb4aed30268">

**Comment by vschwaberow** [comment]
Same here. Thanks for pointing into the right direction to all.

**Comment by badsmoke** [comment]
I have had the same problem for a few days, but the server, worker and outpost are all on the same version.

it started with 2023.5.5 but also an update 2023.6.1 did not help.

it runs with me in kubernetes


![image](https://github.com/goauthentik/authentik/assets/24853712/38dce097-2da8-483f-aa45-a68250e138ee)


<html>
<body>




Active | authentik-server | ghcr.io/goauthentik/server:2023.6.1 | 1/1 | 1 | 1 | 0 | 379 days |   |  
  | Active | authentik-worker | ghcr.io/goauthentik/server:2023.6.1 | 2/2 | 2 | 2 | 0 | 379 days |   |  
  |  

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by vschwaberow** [comment]
No idea. Updating the worker solved this issue after the queue was empty.
