### ISSUE TITLE
Authentik Radius authentification for switch

### ISSUE THREAD

**Issue by Figabra** [goauthentik/authentik#6243]
Please tell me how to configure the Radius server for authorization of network devices (Mikrotik, Cisco etc)? There are detailed instructions for configuring LDAP, but there is nothing for Radius. I tried to set up similar to LDAP, but external switches cannot log in.

-   authentik version: [e.g. 2023.6.1]
-   Deployment: docker-compose

**Comment by nikdoof** [comment]
I've done this with my HPE switches, but Cisco devices require some extra attributes to actually work, which isn't provided by the current RADIUS outpost.

* Follow the [Generic LDAP](https://goauthentik.io/docs/providers/ldap/generic_setup) guide and make a 'radius-authentication-flow` if you don't want to do anything fancy
* Create a Radius Provider, specifying the radius flow created. Take note of the shared key.
* Create a Application that uses the Provider
* Create a Radius Outpost and make sure the Provider is selected.

On the device side, provide the RADIUS server as the IP/hostname of the Authentik Outpost system with port 1612, and the shared key that was provided as part of the Provider setup. Obviously how this is done depends on the device.

Permissions then can be done via assigning policies to the Application.

**Comment by Figabra** [comment]
Thank you very much for your answer! 
Did everything by analogy with LDAP. I'm trying to log in with Mikrotik, but I'm getting a timeout.
I have attached screenshots of my configuration.
Please see where I could have made a mistake.
![Mikrotik](https://github.com/goauthentik/authentik/assets/139442077/b06aac42-7b93-479e-b8a2-02ece298f652)
![Mikrotik-status](https://github.com/goauthentik/authentik/assets/139442077/6a8ae737-02bf-49d1-8671-7e8f670f02d8)
![radius-application](https://github.com/goauthentik/authentik/assets/139442077/485cd06f-d1a3-40c3-a70a-7e8797d14b35)
![radius-authintification-flow](https://github.com/goauthentik/authentik/assets/139442077/615a7583-a7d1-4d4b-80a7-c64daa231e61)
![radius-authintification-login](https://github.com/goauthentik/authentik/assets/139442077/71f66008-f4d3-4197-ac67-c7f7da279506)
![radius-authintification-password-stage](https://github.com/goauthentik/authentik/assets/139442077/1348bb86-7c1f-4755-a2ea-f3afc9f98ab3)
![radius-identification-stage](https://github.com/goauthentik/authentik/assets/139442077/f95e6a65-0ce2-467c-a479-dc249faf7e0f)
![radius-outpost](https://github.com/goauthentik/authentik/assets/139442077/ef90d555-c1fe-4a9e-ac02-f6b0e4436f75)
![radius-provider](https://github.com/goauthentik/authentik/assets/139442077/f1743c8d-8a3c-4db4-a29f-4266a8a4950c)
![stages](https://github.com/goauthentik/authentik/assets/139442077/ef456799-b381-4576-ac8d-608029e5b637)

**Comment by nikdoof** [comment]
I'd check to see if the outpost container is running and listening on 1812, maybe up that timeout as well, I think 300ms may cut it a bit fine if it has a slow response.

**Comment by Figabra** [comment]
Port 1812 the container is listening on
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 0.0.0.0:radius          0.0.0.0:*
udp        0      0 localhost:domain        0.0.0.0:*
udp        0      0 authentik:bootpc 0.0.0.0:*
udp6       0      0 [::]:radius             [::]:*

docker container ls
LDAP and Radius outposts are also running
 ghcr.io/goauthentik/radius:2023.6.1   
"/radius"                2 days ago   Up About an hour (unhealthy)   
0.0.0.0:1812->1812/udp, :::1812->1812/udp, 9300/tcp                                      ak-outpost-radiusoupost
828e9ce6e332   
ghcr.io/goauthentik/ldap:2023.6.1     
"/ldap"                  2 days ago   Up About an hour (unhealthy)   9300/tcp, 0.0.0.0:389->3389/tcp, :::389->3389/tcp, 0.0.0.0:636->6636/tcp, :::636->6636/tcp   
ak-outpost-ldapprovider

**Comment by Figabra** [comment]
Please tell me, could you post a working config? 
I would compare it to mine.

**Comment by rqi14** [comment]
> Please tell me, could you post a working config? I would compare it to mine.

Hi. Did you solve the problem?

**Comment by Figabra** [comment]
Hi. 
Yes, the problem is solved.  Thank for your assistance!

**Comment by rqi14** [comment]
> Hi.
> Yes, the problem is solved. Thank for your assistance!

Good to know you have solved it. I have the same problem now. Do you mind sharing how you solved it?

**Comment by thewillwilson** [comment]
@Figabra Any insight you can share on the fix please?

**Comment by andrewgdunn** [comment]
@Figabra it'd be great to know how you got this working!

**Comment by oblom86** [comment]
Currently Mikrotik will not work with Authentik for WinBox authorization. Mikrotik uses CHAP, MSCHAP protocol while Authentik uses PAP. You can check it like this:
1. Attempts to authorize via WinBox should give the error "flow error non_field_errors: Failed to authenticate" in the Authentik logs:
```
docker logs -f authentik-radius_outpost-1
{"code":"Access-Request","event":"Radius Request","level":"info","logger":"authentik.outpost.radius","request":"a080ff46-fd29-479d-8eca-e3ad343dc9d0","timestamp":"2024-06-14T13:33:11Z"}
{"code":"Access-Request","error":"flow error non_field_errors: Failed to authenticate.","event":"failed to execute flow","level":"warnestamp":"2024-06-14T13:33:15Z","username":"test"}
```
2. You can check the correct settings of your Authentik Radius using the RadTest 2.6 utility. Successful authorization for PAP protocol only:

```
--------------------15.06.2024 11:47:08 Test started  [AuthTest(PAP)]-------------------------
Sending Access-Request of id 176 to 192.168.88.29 port 1812
	User-Name = "test"
	Password = "123456"
Sending Access-Request of id 176 to 192.168.88.29 port 1812
	User-Name = "test"
	Password = "123456"
rad_recv: Access-Accept packet from host 192.168.88.29 port 1812, id=176, length=20

	   Total approved auths:  1
	     Total denied auths:  0
	       Total lost auths:  0
	       Total time(secs):  4
--------------------15.06.2024 11:47:12 Test finished [AuthTest(PAP)]-------------------------
```
3. The Mikrotik community has been asking for this feature since 2008, I think there is nothing to wait for. You need to ask Authentik to enable more protocols for authorization in RADIUS.
Source links:
[Authentik limitation](https://docs.goauthentik.io/docs/providers/radius/)
[Mikrotik radius feature](https://forum.mikrotik.com/viewtopic.php?t=25524)
