### ISSUE TITLE
Date field can't be serialized to JSON on user write stage

### ISSUE THREAD

**Issue by lazaroblanc** [goauthentik/authentik#6262]
**Describe the bug**

`Date` fields can't be serialised to JSON and thus are not saved to the user.

**To Reproduce**

I've added a field of type `Date` to my user settings by adding it in the `default-user-settings` prompt stage.
When I go into my user settings, set a value and save it, my user's fields are no longer displayed, instead replaced by a `Open settings` button.

![image](https://github.com/goauthentik/authentik/assets/40198445/d6945e36-424d-4678-9bec-8b4b82c4614a)

When I click the button I get this error message:

```
builtins.TypeError: Object of type date is not JSON serializable
```

![image](https://github.com/goauthentik/authentik/assets/40198445/41867936-781a-44e2-a941-1a205320a9ef)

-   authentik version:  2023.6.1
-   Deployment: docker-compose

**Additional context**
https://discord.com/channels/809154715984199690/1129892642080161913

**Comment by lazaroblanc** [comment]
The error is still present in 2023.8.3

**Comment by Techwolf12** [comment]
Error seems to still be present in 2023.10.6.
```
{"auth_via": "session", "event": "Failed to save user", "exc": "TypeError('Object of type date is not JSON serializable')", "host": "REDACTED", "level": "warning", "logger": "authentik.flows.stage", "pid": REDACTED, "request_id": "REDACTED", "stage": "default-user-settings-write", "stage_view": "authentik.stages.user_write.stage.UserWriteStageView", "timestamp": "2024-01-16T18:09:04.449412"}
```


Did a workaround by setting the field key to exclude attributes (like `date`), and creating the initial value expression like so:
```
try:
    return user.attributes.get("date", '')
except:
    return ''
```

Then creating an expression policy to attach to the flows that require this, this translates the field key to an attribute, but as a string:
```
request.context['prompt_data']['attributes']['date'] = str(request.context['prompt_data']['date'])

return True
```

**Comment by RobotHanzo** [comment]
@BeryJu After testing, this issue is still present in the latest 2025.8.1 version:
`2025-08-26T03:06:03.514434600Z warning | auth_via=unauthenticated domain_url=<redacted> event=Failed to save user exc=TypeError('Object of type date is not JSON serializable') host=<redacted> logger=authentik.flows.stage pid=37699 request_id=<redacted> schema_name=public stage=registration-save-details stage_view=authentik.stages.user_write.stage.UserWriteStageView timestamp=2025-08-26T03:06:03.514164 `
