### ISSUE TITLE
Mail send for new User not work

### ISSUE THREAD

**Issue by gentilsol** [goauthentik/authentik#6349]
**Describe the bug**
I want, that a new user recive an email that they are registred on the system

**To Reproduce**

1 i create a new User
2. System want send en E-Mail
3. Fail message in the logs

**Expected behavior**

**Screenshots**
Dont have

**Logs:**

ExceptionTask notification_transport encountered an error: Traceback (most recent call last):   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task     R = retval = fun(*args, **kwargs)                  ^^^^^^^^^^^^^^^^^^^^   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner     reraise(*exc_info)   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 60, in reraise     raise value   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 270, in _inner     return f(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__     return self.run(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^   File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 60, in run     ret = task.retry(exc=exc, **retry_kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 736, in retry     raise_with_context(exc)   File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 38, in run     return task._orig_run(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/authentik/events/tasks.py", line 129, in notification_transport     raise exc   File "/authentik/events/tasks.py", line 125, in notification_transport     transport.send(notification)   File "/authentik/events/models.py", line 331, in send     return self.send_email(notification)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/authentik/events/models.py", line 472, in send_email     raise NotificationTransportError(exc) from exc authentik.events.models.NotificationTransportError: [Errno 99] Cannot assign requested address
--

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.6.1]
-   Deployment: [docker-compose]

**Comment by Spencer-0003** [comment]
Dealing with the same issue but I haven't noticed any errors in my logs(?). Test email works but can't receive recovery or verification emails.
