### ISSUE TITLE
website/docs: improve User and Group docs by adding procedurals

### ISSUE THREAD

**Issue by tanberry** [goauthentik/authentik#6356]
Let's add some How To (procedural) topics to the User and Group section of our Docs.

-- Modify the parent topic (`user.md`) to be a landing page with the basic info about Users, and then add two new child pages for:
1. Managing users (How To CRUD, how to map to an application)
2. User object reference (everything that is now on the user.md)

Ditto for the `group.md` file.

Be sure to mention the custom attributes on the Create pages, and what they do, how to populate that section, etc.

If you want to help working on this idea or want to contribute in any other way, react to this issue with a :rocket:

**Comment by tanberry** [comment]
I will work on this one.

**Comment by Baloc** [comment]
I will work on this one.

**Comment by Baloc** [comment]
WIth @tanberry we worked on simple instructions on how to handle the users in the Admin interface.
Is is still missing a lot of infos defined in the first post, but that is a start to extend on the user and group topics missing in the documentation.
