### ISSUE TITLE
Google Enrollment

### ISSUE THREAD

**Issue by Surgical17** [goauthentik/authentik#6358]
Question:
I need to know what the correct flow setup is to enroll a new Google Account

**Relevant info**
I have already previously setup the Google source and enrolled two users. What I then did back then was to clear my Google Enrollment stage and set it to deny so no one can try to enroll. But now I cant remember how to add a user again.

I remember there was a Specific way to add the write and login stages but I tried backtracking what I did 9 months ago to try and find a YouTube video or documentation but no help.

**Version and Deployment (please complete the following information):**

-   Authentik version: 2023.5.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
Aside from https://docs.goauthentik.io/docs/sources/google/, there shouldn't be any custom flows required. If you don't have the original default-source-enrollment flow anymore, you can download this file and import it to restore it: https://github.com/goauthentik/authentik/blob/main/blueprints/default/flow-default-source-enrollment.yaml
