### ISSUE TITLE
OIDC/Oauth asks to login twice.

### ISSUE THREAD

**Issue by mclarence** [goauthentik/authentik#6361]
**Describe the bug**
Logging in using OIDC/Oauth provider asks to log in again after successful login.

**To Reproduce**
Using tailscale as an example
1. Create Oauth provider in authentik.
2. Sign up to tailscale with OIDC IdP. This involved hosting a .well-known/webfinger file on the domain. Entered client secret and id.
3. Signs up successfully.
4. Go to login.tailscale.com and initiate login.
5. Tailscale redirects to authentik and asks user to login.
6. After successful login it asks the user to login again (enter credentials and mfa challenge).
7. Asks user to consent to Tailscale application
8. Authentik redirects back to tailscale and logs in succssfully.

**Expected behavior**
Only enter credentials one time.

**Screenshots**
![redacted](https://github.com/goauthentik/authentik/assets/25338414/320d6301-ecfa-47ce-b306-1d0d484d92b1)

**Logs**

Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version:  2023.6.1
-   Deployment: docker compose

**Additional context**

**Comment by mclarence** [comment]
Never mind, the issue was on tailscale's end. I've signed up by selecting all the prompts (consent, login, select_account). I've since then recreated without selecting any prompts and it is now working as expected.

**Comment by BirkhoffLee** [comment]
@mclarence could you elaborate on how to host the webfinger endpoint?

**Comment by mclarence** [comment]
> @mclarence could you elaborate on how to host the webfinger endpoint?

I used github pages. I created a `.well-known` directory with the `webfinger` file inside.

In that file you should have the following contents:
```json
{
  "subject": "acct:${email}",
  "links": [
    {
      "rel": "http://openid.net/specs/connect/1.0/issuer",
      "href": "${issuer URL}"
    }
  ]
}
```

Replace `${email}` with the email of your user from authentik. It must match the domain you have setup.
Replace `${issuer URL}` with your OIDC provider issuer URL (e.g `https://sso.mydomain.xyz/application/o/tailscale/`)
