### ISSUE TITLE
Add "Password change flow" setting to Brand settings

### ISSUE THREAD

**Issue by joriskt** [goauthentik/authentik#6388]
## Is your feature request related to a problem? Please describe.
It is. This is what happened:
- I have a tenant that only permits login & enrollment via Discord. :heavy_check_mark: 
- I have disabled the user settings flow for this tenant. :heavy_check_mark: 
- There is still a  "Change your password" button that initiates the `default-password-change` flow: :warning: 

![image](https://github.com/goauthentik/authentik/assets/82335810/9e0d862a-2216-4eab-8f4a-d232066d3d5d)

- There is no way to disable this button in the Tenant settings: :x:

![image](https://github.com/goauthentik/authentik/assets/82335810/e024ea3b-b59e-43b8-a5b8-d5c9da66800c)

## Describe the solution you'd like
I would like to be able to select a `Password change flow` in my Tenants. If none is selected, the "Change your password" block **should not appear.** (The same goes for the settings flow, the "Update details" block should just not appear if no flow is set, with the exception of a user running in debug mode.)

## Describe alternatives you've considered
- I've _mitigated_ the problem by adding a policy that users must be from \[another tenant\] to be allowed to use the `default-password-change` flow. However, this causes the user to instead see an error when clicking the button:

![image](https://github.com/goauthentik/authentik/assets/82335810/ebb67bf2-f2c4-462f-b464-86a4e2806ae6)

## Additional context
\-

**Comment by Cubea01** [comment]
Bump.

I'm running into a similar issue using Azure AD social login as my only logon source.

**Comment by GeekPro101** [comment]
+1 to this, this would be extremely useful

**Comment by BeryJu** [comment]
The current configuration for this is done through a password stage, where the flow to change a users' password is set. You can set that option to be empty and this button won't show up

**Comment by Cheekie25** [comment]
I agree. Unless I'm missing something, there is no place where to select the `Password change flow`

**Comment by Ant59** [comment]
Has anyone solved this issue? It's probably worth re-opening the issue until we have a solution to the three comments above.

**Comment by Ogoyukin** [comment]
Hi team! 👋

📌 Problem
In previous discussions this feature was removed (or avoided) in favor of dynamic Flows. Change password feature still need a straightforward way to ensure that users must change their password on their next login (e.g., after being created by an admin).

✅ Proposed implementation (compatible with the Flow-based design):
Add a boolean attribute force_password_change to the user object (stored in user.attributes["force_password_change"]).

In the login flow, add a stage or Flow Plan that:
- checks if the user has force_password_change: true
- if so, redirects them to a change-password Flow

In the change-password Flow, after successful password change:
- a simple hook or logic clears the force_password_change flag.

This way:
No need to store a new field in the database
Behavior is still fully driven by Flows
Integrators and admins get an intuitive, practical behavior that's present in most IdPs


Thanks ChatGPT
