### ISSUE TITLE
Add "Beta" to the commit-hash displayed in Version on Admin dashboard

### ISSUE THREAD

**Issue by tanberry** [goauthentik/authentik#6422]
Currently it is not obvious to new users whether or not they have successfully installed the Beta version. On the Admin interface, under Version (Overview Dashboard) it only shows the commit#'s hash... which is linked to the commit in GitHub.. but nowhere does it say anything about being the Beta version.

Let's either prepend or append the word Beta to the hash value.

<img width="498" alt="Screenshot 2023-07-29 at 11 42 33 AM" src="https://github.com/goauthentik/authentik/assets/9368837/ad73081a-65a3-4494-9247-1d71282ba606">

**Comment by sevmonster** [comment]
Food idea, but the mockup looks pretty ugly.  It would be nicer to add it above or below the hash. Also, the underscore implies this is some kind of programmatic version code, filename, or etc. (which it is not)
