### ISSUE TITLE
Permanent triggering of host authentik.error-reporting.a7k.io

### ISSUE THREAD

**Issue by OliverPifferi** [goauthentik/authentik#6469]
Hey everyone,

I have authentik deployed via Docker (docker-compose.yml) running on Debian 12 "Bookworm" and recently discovered a flood of requests through my Pi-hole to the host **authentik.error-reporting.a7k.io**.

Pi-hole serves as internal DNS and while authentik is running great and without problems, there are no active requests that could explain the triggering of the host so I am wondering if this can be disabled somehow or what the reason for this "flooding" is.

I am running 2023.6.1. Seems to have something to do with the health check - when blacklisting the connection, the Docker-error

`{"event": "Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f732decffd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/4504163677503489/envelope/", "level": "warning", "logger": "urllib3.connectionpool", "timestamp": 1691086393.372016}`

is shown in the logs.

When letting everything pass, it looks as follows:

`{"auth_via": "unauthenticated", "event": "/-/health/live/", "host": "localhost:8000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 193341, "remote": "127.0.0.1", "request_id": "8d64d9afa0ed4f9793b17e8aca36efdb", "runtime": 22, "scheme": "http", "status": 204, "timestamp": "2023-08-03T18:13:43.176250", "user": "", "user_agent": "goauthentik.io/proxy/healthcheck"}`

![Bildschirmfoto 2023-08-03 um 20 09 24](https://github.com/goauthentik/authentik/assets/42076599/a6a63b0e-c62a-4d28-abb2-967e8193d267)

Any ideas on that one? Thanks for your help! Don't want to block anything though but the frequency of requests is quite unusual from my point of view.

Best regards,

Oliver

**Comment by BeryJu** [comment]
Disallowing the error reporting requests shouldn't cause this, but it is also recommended to just disable the error reporting (https://goauthentik.io/docs/installation/configuration#authentik_error_reporting) instead of blocking it with DNS/firewall

**Comment by OliverPifferi** [comment]
> Disallowing the error reporting requests shouldn't cause this, but it is also recommended to just disable the error reporting (https://goauthentik.io/docs/installation/configuration#authentik_error_reporting) instead of blocking it with DNS/firewall

Apparently, this did the trick - didn't want to block anything just for blocking's sake so I'd thought asking this question would be a good idea. There is silence now - thanks for the fast reply!
