### ISSUE TITLE
[BUG] Cannot delete Application: FetchError

### ISSUE THREAD

**Issue by deffcolony** [goauthentik/authentik#6507]
**Describe the bug**
After creating a application there was a bug when uploading the icon

After uploading the app icon the app bugged out by hanging on a loading animation... when i tried to delete the application i got the following error: 
`Failed to delete Application(s): FetchError: The request failed and the interceptors did not return an alternative response`

Here is the icon i used but i am not sure if this was causing the bug...
![matomo](https://github.com/goauthentik/authentik/assets/61471128/ffb7ed84-213f-48bd-9948-151317f7e983)

**To Reproduce**
I am not sure if this breaks the app but what i did was:

1. Go to **Admin interface** --> **Applications** --> **Applications**
2. Click on **Create**

Name: Matomo
Slug: matomo
Provider: Matomo - Forward Auth

3. For UI settings select icon and then use the matomo.png 
4. Click **create**

**Expected behavior**
I expected to work like all other applications i made

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/61471128/8a59147a-fd8c-4f5d-adf0-63e11cadb0da)

**Logs**
The logs did not say anything about the fetch error

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.6.1
-   Deployment: Docker with docker-compose

**Additional context**

```[tasklist]
### Tasks
```

**Comment by markiemm** [comment]
Weird, i had this same issue but uploading a different matomo logo

![62bc721e071dec17849af318](https://github.com/goauthentik/authentik/assets/63561809/dbebb2a7-85f8-4d05-abfc-dac2ce11382e)

**Comment by vfosnar** [comment]
Same issue here with Matomo, can't remember if I uploaded a picture though

**Comment by vfosnar** [comment]
Ooh, for some reason uBlock origin blocks the requests, maybe a weird reaction to an unknown method and "matomo" in the request

**Comment by vfosnar** [comment]
@deffcolony can you or someone else confirm the issue was caused by an ad/tracker blocker? if so the issue can be closed

**Comment by saschabrockel** [comment]
Lol had exactly the same. What the hell.

**Comment by usmcamp0811** [comment]
well shit.. I am having this exact same thing..
