### ISSUE TITLE
Caddy V2 Basic Auth missing header

### ISSUE THREAD

**Issue by jmadden91** [goauthentik/authentik#6519]
Been chasing my tail for a few hours trying to get the basic_auth working for my .arr services via Caddy v2 and Authentik. 
Turns out the default forward_auth example for Caddy is missing the "**authorization**" header in the "copy_headers" section. Once this was added everything works fine.

Correct config example below, sorry my git skills aren't up to creating a PR for this.

```Use the following configuration:

app.company {
    # always forward outpost path to actual outpost
    reverse_proxy /outpost.goauthentik.io/* http://outpost.company:9000

    # forward authentication to outpost
    forward_auth http://outpost.company:9000 {
        uri /outpost.goauthentik.io/auth/caddy

        # capitalization of the headers is important, otherwise they will be empty
        copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version authorization

        # optional, in this config trust all private ranges, should probably be set to the outposts IP
        trusted_proxies private_ranges
    }

    # actual site configuration below, for example
    reverse_proxy localhost:1234
}
If you're trying to proxy to an upstream over HTTPS, you need to set the Host header to the value they expect for it to work correctly.

reverse_proxy /outpost.goauthentik.io/* https://outpost.company {
    header_up Host {http.reverse_proxy.upstream.hostport}
}

```

Thanks to this topic for pointing me in the right direction: (https://github.com/goauthentik/authentik/issues/4381)

Cheers

**Comment by Farossco** [comment]
This is actually also the case for the Traefik example

**Comment by jmadden91** [comment]
I've found adding 'authorization' to the headers seems fix the basic auth problem I was having, but breaks a number of other applications like paperless-ngx, pairdrop etc

**Comment by mkoo21** [comment]
Confirming that this is still the case for forward auth
