### ISSUE TITLE
Event Matcher Policy cannot created with Empty Fields

### ISSUE THREAD

**Issue by wesystems** [goauthentik/authentik#6526]
**Describe the bug**
If we try to create a Event Matcher Policy with empty Fields the Policy will not be created.

**To Reproduce**

1. Go to Costomisation > Policies
2. Click on New Policy
3. Choose Event Matcher Policy
4. Put in Name, and Choose Action

**Expected behavior**
Policy should be Created

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/34236645/6d0bf01c-dd80-4df1-962e-29914e664c8e)

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.6.1
-   Deployment: docker-compose

**Comment by daniele-athome** [comment]
Confirmed, on same version.
