### ISSUE TITLE
Add new OAuth Source - Lark

### ISSUE THREAD

**Issue by RavenLiao** [goauthentik/authentik#6577]
# **Is your feature request related to a problem?**
I had login in with Lark(飞书) oauth2 , but only get name from userProfile. I cann't get email auto, and I cann't set a email. It was not allow,
![image](https://github.com/goauthentik/authentik/assets/47520028/4655e1d8-69f7-4601-af03-9ead0a560ac7)

# **Describe the solution you'd like**
add a OAuth Source provider just like github, and add more info from user's profile,such as name, email, mobile and avatar.

# **Describe alternatives you've considered**
Or add more example at `Property Mappings`. I don't know how to config Scope Mapping.

# **Additional context**
## setting
Authorize url: https://passport.feishu.cn/suite/passport/oauth/authorize
Token url: https://passport.feishu.cn/suite/passport/oauth/token
Profile url: https://passport.feishu.cn/suite/passport/oauth/userinfo

### Profile API
[here is doc site, but it is in Chinese](https://open.feishu.cn/document/common-capabilities/sso/api/get-user-info)
#### request Header:
key | value
-- | --
Authorization | Bearer ${access_token}

#### response Header：
key | value
-- | --
Content-Type | application/json;charset=UTF-8

#### response body
parm| desc| type| necessary
-- | -- | -- | --
sub | equal open_id | string | Yes
name | user name| string | Yes
picture | equal avatar_url | string | Yes
open_id | user id in app | string | Yes
union_id | user id in tenant which developing this app| string |  Yes
en_name | user English name | string | Yes
tenant_key | user id in tenant| string | Yes
avatar_url | user avatar| string | Yes
avatar_thumb | user avatar 72x72 | string | Yes
avatar_middle | user avatar240x240 | string | Yes
avatar_big | user avatar 640x640 | string | Yes
user_id | user feishu id, return only after app authorization | string | No
employee_no | user tenant employee no, return only after app authorization | string | No
email | user email, return only after app authorization | string | No
mobile | user mobile number, return only after app authorization | string | No

##### body example
```
{
    "sub": "ou_caecc734c2e3328a62489fe0648c4b98779515d3",
    "name": "李雷",
    "picture": "https://www.feishu.cn/avatar",
    "open_id": "ou_caecc734c2e3328a62489fe0648c4b98779515d3",
    "union_id": "on_d89jhsdhjsajkda7828enjdj328ydhhw3u43yjhdj",
    "en_name": "Lilei",
    "tenant_key": "736588c92lxf175d",
    "avatar_url": "www.feishu.cn/avatar/icon",
    "avatar_thumb": "www.feishu.cn/avatar/icon_thumb",
    "avatar_middle": "www.feishu.cn/avatar/icon_middle",
    "avatar_big": "www.feishu.cn/avatar/icon_big",
    "email": "zhangsan@feishu.cn",
    "user_id": "5d9bdxxx",
    "employee_no": "111222333",
    "mobile": "+86130xxxx0000"
}
```

**Comment by ClearSeve** [comment]
I am looking forward to integrating it

**Comment by BeryJu** [comment]
Changing the email address is not allowed due to this setting: https://docs.goauthentik.io/docs/core/settings#allow-users-to-change-email

configuring a property mapping to use more data will be possible with #8771
