### ISSUE TITLE
Unable to create custom Policy without optional fields. 

### ISSUE THREAD

**Issue by yurividal** [goauthentik/authentik#6578]
**Describe the bug**
I am trying to get my authentik to send me an email every time a user sucessfuly logs in.
When i try to create a Customization Policy, it doesn't allow me to create a policy with blank items on IP Address, App and Model. 
The documentation states you should be able to do so. 

![image](https://github.com/goauthentik/authentik/assets/8555749/2172810b-9725-422b-bfb2-5f6b502fa261)

-   authentik version: latest
-   Deployment: docker-compose

**Comment by yurividal** [comment]
why is this marked as wontfix?

**Comment by BeryJu** [comment]
This is fixed, I forgot to close this issue with the PR that fixed it
