### ISSUE TITLE
SAML Source: property mapping

### ISSUE THREAD

**Issue by szabogyula** [goauthentik/authentik#6622]
Is there any solution to make property mapping for [SAML Source](https://goauthentik.io/integrations/sources/saml/) just like in [LDAP Source](https://goauthentik.io/integrations/sources/saml/)?

It should be great to get something like this:

| SAML Attribute name                        | user property   |
|------------------------------------|----------------|
| urn:oid:0.9.2342.19200300.100.1.3 | user.email         |
| urn:oid:2.16.840.1.113730.3.1.241    | user.name         |
|urn:oid:1.3.6.1.4.1.5923.1.1.1.6           | user.uid             |
|nameID (not attribute)                       | user.username |

**Comment by not7cd** [comment]
Documentation is a bit lackluster about this. https://goauthentik.io/docs/property-mappings/

What was not obvious was the need to navigate to **Customisation > Property Mappings**. There I could set something up.
![image](https://github.com/goauthentik/authentik/assets/4332632/d834d1f5-6564-4714-91cf-fad27c8c029b)

Then in **Applications** select the mapping

![image](https://github.com/goauthentik/authentik/assets/4332632/e8d31c1b-1f97-48db-9ad7-c90ed775f246)

**Comment by szabogyula** [comment]
OK, but  I think this property mapping is for the SAML User provider when authentik act as SAML SP (service provider) and not for the SAML Source when authentik act as SAML IdP (identiy provider).

![Image 2023  08  28  at 9 04](https://github.com/goauthentik/authentik/assets/3406217/c3dcacc1-dcdf-46f4-a3f1-3b801b840dd5)

**Comment by szabogyula** [comment]
So I found some bits in log but I don't know how to set/config this 
event: _discaring key_

```
{
  "auth_via": "unauthenticated",
  "event": "discarding key",
  "host": "example.com",
  "key": "urn:oid:2.16.840.1.113730.3.1.241",
  "level": "info",
  "logger": "authentik.flows.stage",
  "pid": 167053,
  "request_id": "07e5d0064e4643a2b3cc5193695376d7",
  "stage": "default-source-enrollment-write",
  "stage_view": "authentik.stages.user_write.stage.UserWriteStageView",
  "timestamp": "2023-08-28T07:44:41.507276"
}

{
  "auth_via": "unauthenticated",
  "event": "Task published",
  "host": "example.com",
  "level": "info",
  "logger": "authentik.root.celery",
  "pid": 167053,
  "request_id": "07e5d0064e4643a2b3cc5193695376d7",
  "task_id": "30298f7b-9700-4a6b-ad58-3d6c9cd47ea4",
  "task_name": "authentik.providers.scim.tasks.scim_signal_direct",
  "timestamp": "2023-08-28T07:44:41.541125"
}

{
  "action": "user_write",
  "auth_via": "unauthenticated",
  "client_ip": "1.2.3.4",
  "context": {
    "created": true,
    "geo": {
      "city": "Budapest",
      "continent": "EU",
      "country": "HU",
      "lat": 47.5636,
      "long": 19.0947
    },
    "http_request": {
      "args": {},
      "method": "GET",
      "path": "/api/v3/flows/executor/default-source-enrollment/"
    },
    "urn:oid:0.9.2342.19200300.100.1.3": "szabo.gyula@sztaki.hu",
    "urn:oid:1.3.6.1.4.1.5923.1.1.1.6": "gyufi@sztaki.hu",
    "urn:oid:1.3.6.1.4.1.5923.1.1.1.9": "employee@sztaki.hu",
    "urn:oid:2.16.840.1.113730.3.1.241": "Szabó Gyula",
    "username": "gyufi@sztaki.hu"
  },
  "event": "Created Event",
  "host": "example.com",
  "level": "info",
  "logger": "authentik.events.models",
  "pid": 167053,
  "request_id": "07e5d0064e4643a2b3cc5193695376d7",
  "timestamp": "2023-08-28T07:44:41.564595",
  "user": {
    "email": "",
    "pk": 8,
    "username": "gyufi@sztaki.hu"
  }
}
```

**Comment by laopaoer-wallet** [comment]
I also encountered this problem

**Comment by ChenWenBrian** [comment]
+1
for provider case, we can use request.user.xxx to get the properties stored in authentik, but for source case, I can't find any document which model or variable to use
