### ISSUE TITLE
Authentik exposes protected path

### ISSUE THREAD

**Issue by anon243** [goauthentik/authentik#6633]
**Describe your question/**
I have a web app running on node.js (specifically Send by Firefox). I want to restrict access to internal users only, so I've set up nginx proxy manager with Authentik for authentication. The download path is currently accessible to anyone with the link, and this is working as intended. However, clicking on the logo of the page redirects to the home page where the upload feature is located, thereby bypassing the intended restrictions. Interestingly, upon reloading the page, Authentik is triggered and authentication works as expected.

I'm almost done with the entire setup, but I'm stuck on this last step which is causing me a lot of trouble. I've tried various approaches, but none seem to work. Any help in resolving this issue would be greatly appreciated. Currently, I have allowed access for the path ^/download/* in Authentik. I assume it's because of that.

**Relevant infos**
Authentik, nginx-proxy-manager, web app running nodejs.

**Screenshots**
N/A

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: latest
-   Deployment: docker

**Additional context**
N/A

**Comment by BeryJu** [comment]
While I have not tested directly with Firefox send, the behaviour sounds like the web application is a Single-page application, where routing is done client-side with javascript (hence clicking on the logo does not send an HTTP request and as such works, but refreshing does send an HTTP request and is intercepted by authentik)

There isn't really anything authentik can do about this, as none of its code when using the proxy provider runs on the clientside
