### ISSUE TITLE
Link to update notes goes to incorrect url

### ISSUE THREAD

**Issue by mharveyDC** [goauthentik/authentik#6679]
**Describe the bug**
When clicking on the link to the version notes for version 2023.8.0, the link goes to https://goauthentik.io/docs/releases/2023.8.0, while the update notes are located at https://goauthentik.io/docs/releases/2023.8

**To Reproduce**

1. Go to 'Admin Overview, Dashboards, Overview'
2. Click on '2023.8.0' in the version box
3. See 404 error

**Expected behavior**
I'd expect to go to a page that shows the update notes

**Screenshots**
Expected to see:
![image](https://github.com/goauthentik/authentik/assets/104536812/cba05e6e-455e-42dd-a2bc-7c0d77ebd9c1)
Actually saw:
![image](https://github.com/goauthentik/authentik/assets/104536812/5de110a3-ada1-48be-b79d-92e9c6887e45)

**Logs**
Not applicable

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.0
-   Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
fixed by #6676
