### ISSUE TITLE
Spurious HTML encoding in translated strings

### ISSUE THREAD

**Issue by drpetersen** [goauthentik/authentik#6736]
**Describe the bug**

Special characters (in particular, `&`) in translated strings appear as HTML-encoded entities (`&amp;` in the case of `&`). For instance, `Flows & stages` appears as `Abläufe &amp; Phasen` in German or `Flux &amp; Étapes` in French.

**To Reproduce**

1. Log in to authentik
2. Select the user interface
3. Go to Settings (the cog wheel menu)
4. Select a locale where UI strings contain "&" characters, e.g., German or French
5. Go to the Admin interface

**Expected behavior**

In the sidebar, "Flows & stages" should appear as "Abläufe & Phasen" in German or "Flux & Étapes" in French.

**Screenshots**

![Screenshot_20230902_111105](https://github.com/goauthentik/authentik/assets/9879249/89fc6ba5-eacb-4605-b225-c5108fb5de6c) vs. ![Screenshot_20230902_111049](https://github.com/goauthentik/authentik/assets/9879249/03464276-82e1-484c-8767-719688d12235)

**Logs**

No error messages in the logs.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.2
-   Deployment: docker-compose

**Additional context**

Deployed behing an nginx proxy with global `charset utf-8;` setting.

**Comment by drpetersen** [comment]
Oh, and it also affects *un*translated strings when the locale is not set to English.

![Screenshot_20230902_120659](https://github.com/goauthentik/authentik/assets/9879249/0cfdc604-0c77-4e38-98df-29bd59619008)

versus

![Screenshot_20230902_120731](https://github.com/goauthentik/authentik/assets/9879249/c001ea21-5e43-404f-8234-8772e491642a)

**Comment by BeryJu** [comment]
caused by https://github.com/lit/lit/issues/3025
