### ISSUE TITLE
AWS SAML Relay State

### ISSUE THREAD

**Issue by Eyeanman** [goauthentik/authentik#6782]
**Describe your question/**
I have made a SAML connection with AWS but trying to get it to redirect to Amazon Connect after login, this is usually done by "Relay State" however I cannot see an option for this anywhere within Authentik. AWS Documentation suggests needs to come from the IdP and is not configured on AWS's side.

**Relevant infos**
AWS Documentation: https://docs.aws.amazon.com/connect/latest/adminguide/configure-saml.html#destination-relay

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.2
-   Deployment: Unraid - Docker

**Comment by elythh** [comment]
Hey, this should be available since 2023.10.X releases 😄

**Comment by Eyeanman** [comment]
> Hey, this should be available since 2023.10.X releases 😄 #7100

Amazing! Working now, thank you!
