### ISSUE TITLE
Unable to navigate to initial setup page

### ISSUE THREAD

**Issue by sunilgsuthar** [goauthentik/authentik#6804]
**Question**
I am trying to integrate authentik on my application. This is the docker image I am using:

```
FROM ghcr.io/goauthentik/server:2023.8.2 AS final

ENV WORKERS 2

COPY --from=envcreate /opt/.env .env
COPY ./media /media
COPY ./custom-templates /templates

EXPOSE 80 443

CMD ["server", "worker"]
```
.env file contains all the postgress and redis parameters required for connection. I am able to build and run the docker successfully, but on authentik interface, I am getting page not found for initial setup, infact for all the pages.

Screenshot:
![image](https://github.com/goauthentik/authentik/assets/85148297/212f7074-5357-4357-a494-44a606bca5d9)

Any clue what I might be missing? or is there any issue in my docker?

**Comment by BeryJu** [comment]
you'll still need to run a `server` and a `worker` container, `CMD ["server", "worker"]` does not run both of them at once. The 404 is due to the worker not running which would create all the default flows

**Comment by sunilgsuthar** [comment]
Thanks for the help @BeryJu , the issue is resolved, there are some other stability issues, but this one is resolved. Will raise those separately with more details.

**Comment by CryptoTr4der** [comment]
Hi,
had the same problem with the helm-chart because each container started in parallel, so that the authentik-worker pod can't connect to the postgresdb to create the flows. After restart of the worker it seems to work... Thanks

**Comment by CanonCan** [comment]
Hello @BeryJu 

I had accidentally locked myself up deleting an incorrect flow after trying to set up passkeys that would not work on chrome for android i wiped out postgres, redis and the worker and server containers and deleted the folders in my appdata folder (unraid)

no mater how i set my postgres/redis and worker the default page comes to :9000/if/flow/default-authentication-flow/?next=%2F

if i try and set it to :9000/if/flow/initial-setup I get the screen of the original poster above

please help I have all my containers protected with this and have had to shut my reverse proxy down to avoid exposing them.
