### ISSUE TITLE
Mattermost SAML - Failed to verify signature

### ISSUE THREAD

**Issue by FilipK-CZ** [goauthentik/authentik#6817]
**Describe the bug**
I'm trying to add Authnetik SAML to Mattermost (Enterprise Trial) with encryption enabled but I'm getting a "Failed to verify signature" error from Authnetik.
I have generated a set of keys and certificates.
MM - SAML - key and cert added to Mattermost as Service Provider Private Key and Service Provider Public Certificate
Auth - MM - SAML - certificate added to MM as Identity Provider Public Certificate
I have set the Signing Certificate on the provider to Auth - MM - SAML and the Verification Certificate to MM - SAML.
On MM is Signature Algorithm RSAwithSHA256, Authentik Digest algorithm SHA256 and Signature algorithm RSA-SHA256
Without encryption and signing, login works.

**To Reproduce**

1. Generate 2 Certificates in Authentik
2. Use one certifikace of SP and other for IdP(Authentik)
3. Enable Encryption and Signing on both side

**Screenshots**

![Snímek obrazovky 2023-09-03 v 13 55 42](https://github.com/goauthentik/authentik/assets/7279856/7c93939e-8dbc-4e17-8ffb-b689c91e7bea)
![Snímek obrazovky 2023-09-03 v 13 55 28](https://github.com/goauthentik/authentik/assets/7279856/a0a8f07a-8702-4a38-a4ea-7fc69542cc7b)
![Snímek obrazovky 2023-09-03 v 13 54 46](https://github.com/goauthentik/authentik/assets/7279856/dc2a709c-9b60-44f3-9ef0-38d64ed06aaf)
![Snímek obrazovky 2023-09-03 v 13 54 37](https://github.com/goauthentik/authentik/assets/7279856/68bdd578-c99d-4cbf-839a-1108f5e0d884)

**Logs**
```
{"auth_via": "session", "binding": "<PolicyBinding: Binding from Mattermost #0 to User xxxxxxx>", "event": "P_ENG: Starting Process", "host": "auth.domain.cz", "level": "debug", "logger": "authentik.policies.engine", "pid": 27717, "request": "<PolicyRequest user=xxxxxxx obj=Mattermost http_request=<ASGIRequest: GET '/application/saml/mattermost/sso/binding/redirect/?RelayState=eyJpc01vYmlsZSI6ImZhbHNlIn0%3D&SAMLRequest=REDACTED&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=REDACTED'>>", "request_id": "bc932fa0228d454baaa2707f41109196", "timestamp": "2023-09-09T16:12:26.405636"}
{"auth_via": "session", "event": "P_ENG(proc): Running policy", "host": "auth.domain.cz", "level": "debug", "logger": "authentik.policies.process", "pid": 27717, "policy": null, "process": "PolicyProcess", "request_id": "bc932fa0228d454baaa2707f41109196", "timestamp": "2023-09-09T16:12:26.407071", "user": "xxxxxxx"}
{"auth_via": "session", "cached": true, "event": "P_ENG(proc): finished", "host": "auth.domain.cz", "level": "debug", "logger": "authentik.policies.process", "passing": true, "pid": 27717, "policy": null, "process": "PolicyProcess", "request_id": "bc932fa0228d454baaa2707f41109196", "result": "<PolicyResult passing=True>", "timestamp": "2023-09-09T16:12:26.408500", "user": "xxxxxxx"}
{"app": "mattermost", "auth_via": "session", "event": "PolicyAccessView user_has_access", "host": "auth.domain.cz", "level": "debug", "logger": "authentik.policies.views", "pid": 27717, "request_id": "bc932fa0228d454baaa2707f41109196", "result": "<PolicyResult passing=True>", "timestamp": "2023-09-09T16:12:26.410767", "user": "xxxxxxx"}
{"action": "configuration_error", "auth_via": "session", "client_ip": null, "context": {"message": "Failed to verify signature", "provider": {"app": "authentik_providers_saml", "model_name": "samlprovider", "name": "Mattermost - SAML", "pk": 47}}, "event": "Created Event", "host": "auth.domain.cz", "level": "info", "logger": "authentik.events.models", "pid": 27717, "request_id": "bc932fa0228d454baaa2707f41109196", "timestamp": "2023-09-09T16:12:26.417459", "user": {}}
{"auth_via": "session", "event": "Task published", "host": "auth.domain.cz", "level": "info", "logger": "authentik.root.celery", "pid": 27717, "request_id": "bc932fa0228d454baaa2707f41109196", "task_id": "26f233d4b430479680f9d41ad5e96a1d", "task_name": "authentik.events.tasks.event_notification_handler", "timestamp": "2023-09-09T16:12:26.450966"}
{"auth_via": "session", "event": "Failed to verify signature", "host": "auth.domain.cz", "level": "info", "logger": "authentik.providers.saml.views.sso", "pid": 27717, "request_id": "bc932fa0228d454baaa2707f41109196", "timestamp": "2023-09-09T16:12:26.453383"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.2
-   Deployment: docker-compose

**Comment by FilipK-CZ** [comment]
It is not stale

**Comment by jon91** [comment]
this might help you find some answers: https://github.com/goauthentik/authentik/issues/1795#issuecomment-1020683868
