### ISSUE TITLE
Configuring .env's 'AUTHENTIK_EMAIL' to add support for SMTP OAuth 2.0 authentication for outgoing email

### ISSUE THREAD

**Issue by K-J-VV** [goauthentik/authentik#6819]
**Is your feature request related to a problem? Please describe.**
Microsoft seems to have shifted to require OAuth2 for applications to use SMTP email sending

**Describe the solution you'd like**
I'd like for the .env configuration file to include required fields to make this setup simple (i.e., MICROSOFT_TENANT_ID, MICROSOFT_APPLICATION_ID, APPLICATION_CLIENT_SECRET, etc.)

**Describe alternatives you've considered**
I've been able to get email sending to work using Google Workspace (following this reddit post: https://www.reddit.com/r/selfhosted/comments/10c6w7j/notes_about_email_setup_with_authentik/), but would like Authentik to work/integrate as easily with Microsoft's ecosystem

**Comment by MasterKryszn** [comment]
Updated the title to be more clear/relevant to the problem (I am not a programmer/developer, just an advanced home user). Also saw there is a similar request in Keycloak (https://github.com/keycloak/keycloak/issues/17432), appears their platform is in a similar situation
