### ISSUE TITLE
LDAP search filter on objectClass fails for classes not in authentik schema

### ISSUE THREAD

**Issue by Arzaroth** [goauthentik/authentik#6834]
**Describe the bug**
When using Authentik with the LDAP outpost, I'm experiencing an issue with an LDAP search filter based on objectClass. Specifically, when trying to filter users based on objectClass values that do not exist in Authentik's schema (as listed under 'cn=Subschema'), no results are returned.

**To Reproduce**
1. Configure Authentik with LDAP outpost.
2. Create users
3. Use ldapsearch with the following filter: `(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))`
4. result: 0

**Expected behavior**
The query should return users who have at least one of the specified objectClass attributes.

**Logs**
```
{"bindDN":"XXX","client":"YYY","event":"Bind request","level":"info","requestId":"568a3892-86c2-426d-a6f8-44318e2b003c","timestamp":"2023-09-11T08:57:46Z","took-ms":0}    
{"attributes":[],"baseDN":"XXX","bindDN":"XXX","client":"YYY","event":"Search request","filter":"(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))","level":"info","requestId":"0d3b849b-f9e2-4e20-a391-04e167b165d0","scope":"Whole Subtree","timestamp":"2023-09-11T08:57:46Z","took-ms":0}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.2
-   Deployment: docker compose

**Additional context**
I'm trying to set up a password manager called [sysPass](https://github.com/nuxsmin/sysPass) with authentik, which uses this kind of requests (does so for the groups as well). I've been unsuccessful so far.

**Comment by williamhatcher** [comment]
I am also facing this issue.

**Comment by Arzaroth** [comment]
I can confirm the issue still persist to this day (current version 2024.2.2).
