### ISSUE TITLE
Self impersonation possible

### ISSUE THREAD

**Issue by macmoritz** [goauthentik/authentik#6863]
**Describe the bug**
I can impersonate myself.

**To Reproduce**

1. Open admin interface
2. Go to users (directory > users)
3. Search for your username (same as in active session)
4. Impersonate button visible

**Expected behavior**
I dont think self impersonation does make any sense.

**Version and Deployment:**

-   authentik version: 2023.8.3
-   Deployment: helm

**Comment by PKizzle** [comment]
Rather than completely removing the feature how about making it configurable? There might be some users who actually find it useful. Also, it could be extended to something like this: https://blog.devops.dev/user-impersonation-with-keycloak-3397f3451b4

**Comment by BeryJu** [comment]
@PKizzle this will only prevent a user from impersonating themselves via the standard impersonation API; I'm curious to see what kind of usecase this could have

For the token impersonation, that could be quite interesting, but that would be a whole separate thing

**Comment by PKizzle** [comment]
Sorry, misunderstood the title of the issue. Yeah **self**-impersonation does not really make sense.
