### ISSUE TITLE
Does authentik features a SCIM server?

### ISSUE THREAD

**Issue by jacen05** [goauthentik/authentik#6881]
**Describe your question**
For what I understand (I'm not an IAM expert, correct me where I'm wrong), SCIM provisionning needs a client and a server. The client will request the server at /scim/v2/... to get/create/modify users/groups using standard HTTP methods (GET/POST/PUT/DELETE/...).

The identity source can act as the SCIM client or server : 
- When the identity source is the SCIM client, it will push (POST/PUT/PATCH/DELETE) users/groups (on creation/modification/schedule) to the "application" that needs the user data
- When the identity source is the SCIM server, the client "application" will pull users (GET) from the SCIM server endpoint

In Authentik, at first I though there was only a SCIM client (the SCIM provider asks for an URL endpoint and a token), but [this comment](https://github.com/goauthentik/authentik/issues/4554#issuecomment-1485909251) seems to refer to an Authentik endpoint in /scim/v2. So I don't know if I can use Authentik as a SCIM server or not.

If yes, what shall I configure?
If no, is it a planed feature?

**Additional context**
For context, my use-case needs a SCIM server for 2 components: 
- My client NodeJS application is already acting as SCIM client to get the users from a SCIM server, and update the resources on the SCIM server when a modification is done on the app.
- I want to defer user authentication (in some cases) to Azure AD, but I also want to be able to manage the users in my NodeJS app, even before any user has already logged in (for example giving them the correct role). Azure AD can only act as a SCIM client, so I also need a SCIM server that Azure AD can connect to to push the user into my Authentik server.

I'm currently evaluating several IDM, and found out that Gluu server, for example, can act as both SCIM client and server. However it does not meet my other requirements.

**Comment by BeryJu** [comment]
See #3051, authentik is currently only an SCIM client

**Comment by jacen05** [comment]
Thanks for the quick answer. I will thus keep track of the pull request. Without asking for an ETA, would you say it is on a list of priorities or more backlog work?
