### ISSUE TITLE
custom locations not covered

### ISSUE THREAD

**Issue by Kotva666** [goauthentik/authentik#6882]
**Describe your question/**
When I have custom locations set up in Nginx proxy manager. However, authentik does not secure these paths...
cam.domain.tld is secure
cam.domain.tld/zm/ is not secure

how do I secure it????

**Relevant infos**
Unraid OS 6.12.4
Docker
Nginx-Proxy-Manager
Zoneminder
Authentik [2023.8.3]

**Comment by Kotva666** [comment]
Hey, no one's working on it? Can someone answer that? Or does everyone give a shit?

**Comment by NicholasKuchiniski** [comment]
If anyone is having this same problem, i fixed that by simply copying the  `location /` block of the providede snippet and pasting it inside the custom configuration of nginx proxy manager (you have the exclude the proxy_pass section because the NPM is already adding that)
