### ISSUE TITLE
Make `end-session` layout configurable

### ISSUE THREAD

**Issue by madduck** [goauthentik/authentik#6917]
It seems that `/if/session-end/myapp` is not part of a flow, and there is no way to configure layout (sidebar) and background for this. It's a good page to have, but I'd need to style it properly.

It would also help being able to discover how it's generated.

**Comment by madduck** [comment]
Only just found https://github.com/goauthentik/authentik/issues/4586 sorry.

**Comment by kensternberg-authentik** [comment]
@madduck Did #4586 solve your issue?  If so, could you please close this bug?
