### ISSUE TITLE
Proxy container crashes on start, since 2023.8.0

### ISSUE THREAD

**Issue by chrisblech** [goauthentik/authentik#6931]
**Describe the bug**
When starting a authentik-proxy container via docker, it crashes directly while starting up, when trying to connect to its own port 6379 (which imho doesn't make sense).

The authentik application/container (running on another host), has version 2023.8.3.
When downgrading the proxy to version 2023.6.2, everything is fine. Versions 2023.8.0 / .1 / .2 / .3 are throwing this error.

**To Reproduce**

1. `docker run -e AUTHENTIK_HOST=<redacted> -e AUTHENTIK_INSECURE=false -e AUTHENTIK_TOKEN=<redacted> ghcr.io/goauthentik/proxy:2023.8.3`
2. See error

Maybe the cause of this error is related to my specific authentik configuration. To receive my HOST and TOKEN vars for debugging, please send my a PM via discord (see below).

**Expected behavior**
The Proxy container should start up without error, and doing its job.

**Logs**
```
DBG event=Loaded config path=inbuilt-default timestamp=2023-09-18T20:07:21Z
DBG event=Loaded config from environment timestamp=2023-09-18T20:07:21Z
timestamp="2023-09-18T20:07:21Z" level=info event="Starting Debug server" listen="0.0.0.0:9900" logger=authentik.go_debugger
timestamp="2023-09-18T20:07:22Z" level=info event="finished shutdown" logger=authentik.outpost.ak-api-controller
panic: dial tcp 127.0.0.1:6379: connect: connection refused
goroutine 1 [running]:
goauthentik.io/internal/outpost/proxyv2/application.(*Application).getStore(_, {0x19, {0xc000280380, 0x1a}, 0xc000134290, {0xc0002803a0, 0x1f}, 0xc000450a8e, 0xc0001342a0, 0xc0001342b0, ...}, ...)
	/go/src/goauthentik.io/internal/outpost/proxyv2/application/session.go:35 +0x42e
goauthentik.io/internal/outpost/proxyv2/application.NewApplication({0x19, {0xc000280380, 0x1a}, 0xc000134290, {0xc0002803a0, 0x1f}, 0xc000450a8e, 0xc0001342a0, 0xc0001342b0, {{0xc0002da1c0, ...}, ...}, ...}, ...)
	/go/src/goauthentik.io/internal/outpost/proxyv2/application/application.go:140 +0xfae
goauthentik.io/internal/outpost/proxyv2.(*ProxyServer).Refresh(0xc00009d1e0)
	/go/src/goauthentik.io/internal/outpost/proxyv2/refresh.go:37 +0x587
goauthentik.io/internal/outpost/ak.(*APIController).Start(0xc000103d40)
	/go/src/goauthentik.io/internal/outpost/ak/api.go:123 +0x2e
main.glob..func2(0xc0005a2600?, {0x11b397c?, 0x4?, 0x11b3980?})
	/go/src/goauthentik.io/cmd/proxy/main.go:80 +0x3ee
github.com/spf13/cobra.(*Command).execute(0x1b23080, {0xc000134080, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x1b23080)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/go/src/goauthentik.io/cmd/proxy/main.go:93 +0x48
```

**Version and Deployment:**

-   authentik version: 2023.8.3
-   Deployment: docker-compose

**Additional context**
https://discord.com/channels/809154715984199690/1151114455602704434

**Comment by BeryJu** [comment]
the cause for the error is that the outpost tries to connect to redis for the session storage. That is only supposed to happen for the embedded outpost, and not regular outposts (this was changed by https://github.com/goauthentik/authentik/commit/9e29789c09be066817b3c57043480c2018ffa4c9)

When creating an outpost as intended, I don't get this error in the outpost container, did you create a separate outpost in the authentik admin interface and use that created outposts' token? This check could be invalid if the token has access to the wrong outpost which is limited when creating a token via the Outpost itself

**Comment by chrisblech** [comment]
On host A, there is only a authentik proxy container (`ghcr.io/goauthentik/proxy:2023.8.3`, besides traefik and some containers related to my application). This proxy container (thats throwing this error) is configured as described in: `<authentik-host>/if/admin/#/core/providers/25;%7B%22page%22%3A%22page-overview%22%2C%22proxy-setup%22%3A%22page-traefik-compose%22%7D` (forward-auth with traefik/compose), and connected to my base authentik (on host B) via token.
This token was generated with the embedded-outpost (on Host B) as user. I did not create a dedicated outpost.

**Comment by BeryJu** [comment]
Creation of a dedicated outpost is required, just using a manually created token is not supported.

As a superuser, the API returns all outposts as you have access to all of them, while when creating an outpost, a new token is created that only has access to the single outpost and all the resources required for it

**Comment by chrisblech** [comment]
Ah okay, now I see my fault.
My "outpost" was a proxy-container with a manually created token (in the context of the embedded outpost). Authentik didn't knew about this outpost (no entry in outposts list, provider was listed with/attached to embedded outpost).

After deleting this manual created token, creating a dedicated proxy-outpost and using its token in docker-compose, and assigning the provider to this outpost, the proxy is starting without error and doing its job.

Sorry, and thanks for clarification and helping me on the right way.
