### ISSUE TITLE
REST API to login 

### ISSUE THREAD

**Issue by NajiAboo** [goauthentik/authentik#7073]
Hi , 
 We are trying to implement Authentik. We are able to create user and authenticate the user using the web interface. 
Now we need to do the same using the REST end point. use case, By using the user name and password, we need to post against the Authentik and get the id or token from it. I have gone through the REST API provided. But I could not figure out it. 
It will be highly appreciated if i get the details of it. 
 
Thanks.

**Comment by BeryJu** [comment]
See https://docs.goauthentik.io/developer-docs/api/flow-executor
