### ISSUE TITLE
SAML source can't seem to trigger enrollment flow

### ISSUE THREAD

**Issue by mccullerlp** [goauthentik/authentik#7093]
**Describe the bug**
I'm at a university and have our Shibboleth-based SAML source for authentication. It works correctly as far as I can tell and, once enrolled, a user can bind their account to the SAML source. Additionally, I have an OpenIDC source from CILogon.org. 

The CILogon/openIDC source is able to trigger an enrollment flow to bypass the need to create a password. I've tried various permutations of settings, but my SAML source cannot do that and always gives a Permission denied or not allowed rejection when it should trigger an enrollment flow.

I want to ask if this is/should be supported. I assume so since the OpenIDC source can do this.  The SAML source uses a different set of property names, so perhaps this is related to #6622.

**To Reproduce**
Set up Shibboleth implementation of a SAML source. Ensure that the email of a test login is not associated with any account. Attempt to log in using the SAML source.

**Expected behavior**
The SAML source should start an enrollment flow that creates a user and associates that user with the SAML source. This works for the OpenIDC source from CILogon.

Authentik is amazing software BTW. I can still do what I need using a standard enrollment flow followed by associating with the SAML source . This is just not intuitive for users and I assume that Authentik should support fully-federated login, where users do not need passwords at all.

**Comment by laopaoer-wallet** [comment]
Is there any solution?
