### ISSUE TITLE
Rename type attribute in the model

### ISSUE THREAD

**Issue by PKizzle** [goauthentik/authentik#7096]
As the type attribute clashes with Python's `type()` function all mentions in the model shall be renamed.
This would further allow to remove any workarounds that had to be added in order for `pyupgrade` to work.
Take a look at https://github.com/goauthentik/authentik/pull/7092 for further details.

**Comment by JuanitaCathy** [comment]
I would like to work on this, can you assign it to me?

**Comment by PKizzle** [comment]
I don’t have the permission to do so. Maybe @BeryJu can assign this issue to you.

**Comment by JuanitaCathy** [comment]
Hello, due to my college work, I wouldn't be able to contribute much :(
I'll remove my assignment so someone else could work on it, I apologize
