### ISSUE TITLE
Edge browser support

### ISSUE THREAD

**Issue by pelaxa** [goauthentik/authentik#7123]
is anyone using Authentik with Microsoft Edge browser on MacOS?

I just installed Authentik using docker-compose and got the initial-setup flow but no matter what I entered, I could not move forward.  The logs do not show any errors either, and neither does the browser debug console.  Then out of the blue I decided to try a different browser (Chrome) and I managed to move forward.  

After this, even trying to login using Edge I get the same issue. I cannot get past the username field, but I can do everything using Chrome.

Authentik Version: 2023.8.3
Client Browser: 
   Microsoft Edge Version 117.0.2045.55
Client OS:
   MacOS Sanoma 14.0

The only logs entries that show when I click continue are:

```
authentik-server  | {"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/initial-setup/?query=", "host": "10.X.X.Y:9000", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 23, "remote": "10.X.X.X", "request_id": "a91e65030f9544bf8b0d06ced9facb4f", "runtime": 128, "scheme": "http", "status": 302, "timestamp": "2023-10-10T03:01:00.762592", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.55"}
authentik-server  | {"auth_via": "unauthenticated", "event": "/api/v3/flows/executor/initial-setup/?query=", "host": "10.X.X.Y:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 23, "remote": "10.X.X.X", "request_id": "1ef82d80a8e9481386b5377e2bfcb7e1", "runtime": 75, "scheme": "http", "status": 200, "timestamp": "2023-10-10T03:01:00.842457", "user": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.55"}
```

**Comment by cakriwut** [comment]
I found the same problem. Currently I am only able to open Authentik in incognito Edge browser.

**Comment by BeryJu** [comment]
I have not been able to reproduce this issue on various edge versions on macOS. Please feel free to re-open this issue if this is still an issue
