### ISSUE TITLE
Recovery Emails not Send until after docker-Redeployment

### ISSUE THREAD

**Issue by shukon** [goauthentik/authentik#7164]
**Describe the bug**
I implemented the default password recovery flow using emails.
It works, after I deploy the docker-compose files using an ansible script. But after a while, it just stops. I haven't been able to figure out the exact time. There is no errors in the logs, just no "Email Sent" events anymore. How can I go about debugging the situation? Is there a queue in authentik? The requests are obviously saved, because after I redeploy the containers, all the missing mails are sent.

**To Reproduce**
I'm using authentik with the [mash-setup](https://github.com/mother-of-all-self-hosting/mash-playbook), however since the environment variables are set correctly and it works for some time, I figure it's more likely related to authentik itself.

1. Set up default email recovery flow
2. Wait
3. Try to recover mails
4. See it failing
5. Redeploy docker-compose
6. See it working

**Expected behavior**
Emails should be sent at any point.

**Logs**
There is no errors I could see, mails are just not sent, but somehow queued.

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.8.3](https://goauthentik.io/docs/releases/2023.8)
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
The only thing coming to mind that might cause this is if you have auto-updates enabled for your redis container, which currently requires an authentik restart to be picked up
