### ISSUE TITLE
Scope authorization for Oauth

### ISSUE THREAD

**Issue by Cousclou** [goauthentik/authentik#7169]
**Describe your question/**
I noticed that we can filter users by group since v22.4.

"By default, every user that has access to an application can request any of the configured scopes. Starting with authentik 2022.4, you can do additional checks for the scope in an expression policy (bound to the application)" 

```python
# There are additional fields set in the context, use `ak_logger.debug(request.context)` to see them.
if "my-admin-scope" in request.context["oauth_scopes"]:
    return ak_is_group_member(request.user, name="my-admin-group")
return True
``` 
I understood where to place the expression Policy, but I didn't understand how to configure the syntax.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/134141465/3482b35c-892a-4576-b482-0a16c75d8702)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.8.3]
-   Deployment: [docker-compose]

**Comment by BeryJu** [comment]
The expression in your screenshot looks correct; when the "profile" scope is requested, access to the application is only granted if the user is in the "cous-private" group, and if the scope is not requested then access is also granted
