### ISSUE TITLE
Reverse Proxy IP instead of Client IP is shown, no IP-based rules possible, worked with 2022.11

### ISSUE THREAD

**Issue by techn0pia** [goauthentik/authentik#7219]
**Describe the bug**
As Client IP, the IP of the NGINX Reverse Proxy is used, not the actual client IP. 
This is critical, as no IP-based rules are possible (e.g. rule: no 2FA in the local Network). 
I downgraded to 2022.11, and here the Client IP is displayed correctly with the identical setup. 

Real Client IP: 192.168.0.20
NGINX and Authentik are connected via docker network 172.52.0.0/24
NGINX has IP 172.52.0.3, Authentik has IP 172.52.0.10
Wrongly displayed Client IP: 172.52.0.3

**To Reproduce**

I'm using the NGINX-Config for Reverse Proxy as described here: 
https://goauthentik.io/docs/installation/reverse-proxy
with proxy_pass https://172.52.0.10:9443;

NGINX and Authentik Server are in the same Docker network:

```
networks:        
 authentik-proxy:
  name: npm-extern
  driver: bridge
  ipam:
   config:
    - subnet: 172.52.0.0/24
```
NGINX is Port-Mapping the Host-Ports 80 / 443 

I disabled userland-proxy for Docker, as this can prevent Client-IPs being forwarded
/etc/docker/daemon.json
```
{
  "userland-proxy": false
}
```

**Expected behavior**
The IP of the client ( 192.168.0.20) should be shown. 

I didn't find any possibility, to define "trusted proxies" in Authentik (in many other apps this is the solution, if the wrong Client IP is shown) 

**Version and Deployment (please complete the following information):**

-   authentik version:2023.8.3
-   Deployment: Docker Compose

**Comment by BeryJu** [comment]
See https://goauthentik.io/docs/installation/configuration#listen-setting, especially `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS`

**Comment by techn0pia** [comment]
> See https://goauthentik.io/docs/installation/configuration#listen-setting, especially `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS`

Thanks! I added in the docker compose for the authentik server: 
`AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS: "172.52.0.0/24"`
but as Client IP still 172.52.0.3 is shown.

**Comment by techn0pia** [comment]
Okay, I think it's really a bug.

I did a fresh install to the last version I used (2022.11) and the Client IP is showing up again correctly. 
When I did an update to 2023.8.3 and the Client IP is showing the Reverse Proxy again.
