### ISSUE TITLE
Microsoft Social Login

### ISSUE THREAD

**Issue by OneAutumnSheath** [goauthentik/authentik#7252]
**Describe your question/**
Iam trying to configure a single tendant login with microsoft and it gives me the error. Any Idea why this comes up?

**Relevant infos**
all steps to the microsoft login where i put my creds are done. When i login in microsoft then i get the error: "Authentication failed: State check failed."
I've had an previous error wich i fixed with the help of the issue #5288 
**Screenshots**
![grafik](https://github.com/goauthentik/authentik/assets/96901993/d2af2fb6-869b-416d-a1c9-83c5f7b6e2a4)

**Logs**
[log.txt](https://github.com/goauthentik/authentik/files/13060650/log.txt)

**Version and Deployment (please complete the following information):**

-   authentik version: [latest]
-   Deployment: [docker compose]

**Additional context**
None

**Comment by OneAutumnSheath** [comment]
now i restarted the container and i get the could not retrieve token error again

**Comment by OneAutumnSheath** [comment]
I've also tried it with discord, it wont work.

**Comment by OneAutumnSheath** [comment]
nevermind, i found the issue on my own

**Comment by sanzoghenzo** [comment]
@OneAutumnSheath I got the same problem with the latest version, can you please share the solution?
