### ISSUE TITLE
Remove the built-in authentication form from login page

### ISSUE THREAD

**Issue by fgionghi** [goauthentik/authentik#7276]
**Describe your question/**
Since I login to authentik only with azure oauth, is it possible to remove the red rectangle and leave only the azure button?
![image](https://github.com/goauthentik/authentik/assets/51024333/00c08be9-ed74-4f22-9ea9-c6e3c30ed345)

**Comment by BeryJu** [comment]
See https://goauthentik.io/docs/flow/stages/identification/#user-fields, you can unselect all user fields in the identification stage and then only sources can be used
