### ISSUE TITLE
Database error when upgrading to 2023.10 from a version older than 2023.8

### ISSUE THREAD

**Issue by klutchrider** [goauthentik/authentik#7326]
**Describe your question/**
Just updated to 2023.10.1 and since I'm already logged into authentik on a browser, everything is working, but since I tried another browser, I seem to be not getting the login screen, but getting either an iframe or html information as shown below.  Not sure what else is needed, but will provide if asked.

**Relevant infos**
<!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"> <title> authentik </title> <link rel="icon" href="/static/dist/assets/icons/icon.png"> <link rel="shortcut icon" href="/static/dist/assets/icons/icon.png"> <link rel="prefetch" href="/static/dist/assets/images/flow_background.jpg" /> <link rel="stylesheet" type="text/css" href="/static/dist/patternfly.min.css"> <script type="36da15029b380e93da54aebd-text/javascript"> window.authentik = { locale: "en-us", config: JSON.parse(''), tenant: JSON.parse(''), versionFamily: "", versionSubdomain: "", build: "", }; window.addEventListener("DOMContentLoaded", () => { }); </script> <link rel="stylesheet" type="text/css" href="/static/dist/authentik.css"> <link rel="stylesheet" type="text/css" href="/static/dist/theme-dark.css" media="(prefers-color-scheme: dark)"> <link rel="stylesheet" type="text/css" href="/static/dist/custom.css" data-inject> <script src="/static/dist/poly.js?version=2023.10.0" type="36da15029b380e93da54aebd-module"></script> <script src="/static/dist/standalone/loading/index.js?version=2023.10.0" type="36da15029b380e93da54aebd-module"></script> <style> :root { --ak-flow-background: url("/static/dist/assets/images/flow_background.jpg"); --pf-c-background-image--BackgroundImage: var(--ak-flow-background); --pf-c-background-image--BackgroundImage-2x: var(--ak-flow-background); --pf-c-background-image--BackgroundImage--sm: var(--ak-flow-background); --pf-c-background-image--BackgroundImage--sm-2x: var(--ak-flow-background); --pf-c-background-image--BackgroundImage--lg: var(--ak-flow-background); } /* Form with user */ .form-control-static { margin-top: var(--pf-global--spacer--sm); display: flex; align-items: center; justify-content: space-between; } .form-control-static .avatar { display: flex; align-items: center; } .form-control-static img { margin-right: var(--pf-global--spacer--xs); } .form-control-static a { padding-top: var(--pf-global--spacer--xs); padding-bottom: var(--pf-global--spacer--xs); line-height: var(--pf-global--spacer--xl); } </style> <meta name="sentry-trace" content="ff4a21f450be473b9ecd9b487d2d1296-904c7813eee473bb-0" /> </head> <body> <div class="pf-c-background-image"> <svg xmlns="http://www.w3.org/2000/svg" class="pf-c-background-image__filter" width="0" height="0"> <filter id="image_overlay"> <feColorMatrix in="SourceGraphic" type="matrix" values="1.3 0 0 0 0 0 1.3 0 0 0 0 0 1.3 0 0 0 0 0 1 0" /> <feComponentTransfer color-interpolation-filters="sRGB" result="duotone"> <feFuncR type="table" tableValues="0.086274509803922 0.43921568627451"></feFuncR> <feFuncG type="table" tableValues="0.086274509803922 0.43921568627451"></feFuncG> <feFuncB type="table" tableValues="0.086274509803922 0.43921568627451"></feFuncB> <feFuncA type="table" tableValues="0 1"></feFuncA> </feComponentTransfer> </filter> </svg> </div> <ak-message-container></ak-message-container> <div class="pf-c-login"> <div class="ak-login-container"> <header class="pf-c-login__header"> <div class="pf-c-brand ak-brand"> <img src="/static/dist/assets/icons/icon_left_brand.svg" alt="authentik Logo" /> </div> </header> <main class="pf-c-login__main"> <header class="pf-c-login__main-header"> <h1 class="pf-c-title pf-m-3xl"> Server Error </h1> </header> <div class="pf-c-login__main-body"> <form method="POST" class="pf-c-form"> <p></p> <a id="ak-back-home" href="/" class="pf-c-button pf-m-primary"> Go home </a> </form> </div> </main> <footer class="pf-c-login__footer"> <ul class="pf-c-list pf-m-inline"> <li> <a href="https://goauthentik.io?utm_source=authentik"> Powered by authentik </a> </li> </ul> </footer> </div> </div> <script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="36da15029b380e93da54aebd-|49" defer></script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"81c5bcebafd3e792","r":1,"version":"2023.10.0","token":"2efdb94088f04f08955a32f32a52650a"}' crossorigin="anonymous"></script> </body> </html>

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/5239065/e859209a-29b3-4090-b00a-6fa6b6df678c)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.10.1]
-   Deployment: [Unraid]

**Additional context**

**Comment by raldnor** [comment]
I've got the same issue. Started with 10.0, cannot roll back to 10.8 unfortunately.

**Comment by raldnor** [comment]
I fixed it by adding the missing column in the postgres DB:
```
alter table authentik_stages_authenticator_static_authenticatorstaticstage add column token_length INTEGER default 12;
```

**Comment by BeryJu** [comment]
@klutchrider @raldnor which version did you upgrade from?

**Comment by raldnor** [comment]
I went from 2023.5.0 to 2023.10.0

**Comment by BeryJu** [comment]
So it seems the error happens when going from a version older than 2023.8 to 2023.10, as a short term solution I'll add a banner to the release notes

**Comment by Leptopoda** [comment]
I now face the same issue.
For reference I came from 2023.06

**Comment by los93sol** [comment]
Any updates on this, facing the same issues

**Comment by klutchrider** [comment]
Yeah I came from 2023.4, let me try your fix @raldnor

**Comment by klutchrider** [comment]
As stated from @raldnor, connect to your postgres DB, and try adding the table mentioned, should get you back up and running.

Thanks @BeryJu @raldnor

**Comment by los93sol** [comment]
I came from 2023.8 and still had this issue.  I ended up manually inserting the migration records into the database, oddly enough, comparing the code in the migrations against my database it appears they actually had been applied properly as all the new fields were there

**Comment by natoleet** [comment]
I was bitten by the same bug while keeping everything updated with Watchtower using the :latest tag.

**Comment by DKingAlpha** [comment]
For anyone who have no prior knowledge about authentik's postgres, the possible online fix is

`docker-compose exec -ti -u postgres postgresql     psql -U authentik`
then in psql shell
`alter table authentik_stages_authenticator_static_authenticatorstaticstage add column token_length INTEGER default 12;`

**Comment by dweee** [comment]
I've tried all the fixes across the issue threads on here, now I'm finally faced with the same login page as OP, Will try joining the discord and asking there. Will report back if anything else works.

**Comment by keesfluitman** [comment]
> I came from 2023.8 and still had this issue. I ended up manually inserting the migration records into the database, oddly enough, comparing the code in the migrations against my database it appears they actually had been applied properly as all the new fields were there...
> 
> insert into django_migrations (app, name, applied) VALUES ('authentik_stages_authenticator_static', '0008_initial', current_timestamp); insert into django_migrations (app, name, applied) VALUES ('authentik_stages_authenticator_static', '0009_throttling', current_timestamp); insert into django_migrations (app, name, applied) VALUES ('authentik_stages_authenticator_totp', '0008_initial', current_timestamp); insert into django_migrations (app, name, applied) VALUES ('authentik_stages_authenticator_totp', '0009_auto_20190420_0723', current_timestamp);

this actually worked. Thank you so much.
