### ISSUE TITLE
Failed migration when updating to 2023.10.1

### ISSUE THREAD

**Issue by Leptopoda** [goauthentik/authentik#7338]
**Describe the bug**
I tried to update my instance to the latest 2023.10.1 release but now get the following exception.
I'm sorry but the following log is the only information I got.

**To Reproduce**
N.A.

**Screenshots**
N.A.

**Logs**
Postgres:
```
authentik-postgresql-1  | 2023-10-27 08:51:34.489 UTC [32] ERROR:  column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
authentik-postgresql-1  | 2023-10-27 08:51:34.489 UTC [32] STATEMENT:  ALTER TABLE "authentik_stages_authenticator_static_staticdevice" ADD COLUMN "throttling_failure_count" integer DEFAULT 0 NOT NULL CHECK ("throttling_failure_count" >= 0)
```
Server:
```
authentik-server-1      | Operations to perform:
authentik-server-1      |   Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_password, authentik_policies_reputation, authentik_providers_ldap, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_rbac, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, sessions
authentik-server-1      | Running migrations:
authentik-server-1      | Traceback (most recent call last):
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
authentik-server-1      |     return self.cursor.execute(sql)
authentik-server-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
authentik-server-1      |     return super().execute(*args, **kwargs)
authentik-server-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
authentik-server-1      |     raise ex.with_traceback(None)
authentik-server-1      | psycopg.errors.DuplicateColumn: column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
authentik-server-1      | 
authentik-server-1      | The above exception was the direct cause of the following exception:
authentik-server-1      | 
authentik-server-1      | Traceback (most recent call last):
authentik-server-1      |   File "<frozen runpy>", line 198, in _run_module_as_main
authentik-server-1      |   File "<frozen runpy>", line 88, in _run_code
authentik-server-1      |   File "/lifecycle/migrate.py", line 112, in <module>
authentik-server-1      |     execute_from_command_line(["", "migrate"])
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
authentik-server-1      |     utility.execute()
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
authentik-server-1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
authentik-server-1      |     self.execute(*args, **cmd_options)
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
authentik-server-1      |     output = self.handle(*args, **options)
authentik-server-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
authentik-server-1      |     res = handle_func(*args, **kwargs)
authentik-server-1      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
authentik-server-1      |     post_migrate_state = executor.migrate(
authentik-server-1      |                          ^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
authentik-server-1      |     state = self._migrate_all_forwards(
authentik-server-1      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
authentik-server-1      |     state = self.apply_migration(
authentik-server-1      |             ^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
authentik-server-1      |     state = migration.apply(state, schema_editor)
authentik-server-1      |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
authentik-server-1      |     operation.database_forwards(
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
authentik-server-1      |     schema_editor.add_field(
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 712, in add_field
authentik-server-1      |     self.execute(sql, params)
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
authentik-server-1      |     return super().execute(sql, None)
authentik-server-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
authentik-server-1      |     cursor.execute(sql, params)
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 628, in execute
authentik-server-1      |     return real_execute(self, sql, params)
authentik-server-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
authentik-server-1      |     return self._execute_with_wrappers(
authentik-server-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
authentik-server-1      |     return executor(sql, params, many, context)
authentik-server-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
authentik-server-1      |     with self.db.wrap_database_errors:
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
authentik-server-1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
authentik-server-1      |     return self.cursor.execute(sql)
authentik-server-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
authentik-server-1      |     return super().execute(*args, **kwargs)
authentik-server-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
authentik-server-1      |   File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
authentik-server-1      |     raise ex.with_traceback(None)
authentik-server-1      | django.db.utils.ProgrammingError: column "throttling_failure_count" of relation "authentik_stages_authenticator_static_staticdevice" already exists
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.1
-   Deployment: docker-compose

**Additional context**
N.A.

**Comment by BeryJu** [comment]
in the authentik container you can run `ak migrate authentik_stages_authenticator_static 0009_throttling --fake`

**Comment by Leptopoda** [comment]
Hi there and thanks for the fast reply. Looks like my db is f***ed. 
Running the mentioned command:
```
{"app_name": "authentik.stages.authenticator", "event": "Could not import app's URLs", "exc": "ModuleNotFoundError(\"No module named 'authentik.stages.authenticator.urls'\")", "level": "warning", "logger": "authentik.api.v3.urls", "pid": 113, "timestamp": "2023-10-27T10:44:52.005398"}
Operations to perform:
  Target specific migration: 0009_throttling, from authentik_stages_authenticator_static
Running migrations:
```
Next start of the server:
```
Operations to perform:
  Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_password, authentik_policies_reputation, authentik_providers_ldap, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_rbac, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, sessions
Running migrations:
  Applying authentik_stages_authenticator_totp.0008_initial...Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.DuplicateTable: relation "authentik_stages_authenticator_totp_totpdevice" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/lifecycle/migrate.py", line 112, in <module>
    execute_from_command_line(["", "migrate"])
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 451, in create_model
    self.execute(sql, params or None)
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 628, in execute
    return real_execute(self, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "authentik_stages_authenticator_totp_totpdevice" already exists
```
Postgres:
```
authentik-postgresql-1  | 2023-10-27 10:45:35.704 UTC [31] ERROR:  relation "authentik_stages_authenticator_totp_totpdevice" already exists
authentik-postgresql-1  | 2023-10-27 10:45:35.704 UTC [31] STATEMENT:  CREATE TABLE "authentik_stages_authenticator_totp_totpdevice" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(64) NOT NULL, "confirmed" boolean NOT NULL, "key" varchar(80) NOT NULL, "step" smallint NOT NULL CHECK ("step" >= 0), "t0" bigint NOT NULL, "digits" smallint NOT NULL CHECK ("digits" >= 0), "tolerance" smallint NOT NULL CHECK ("tolerance" >= 0), "drift" smallint NOT NULL, "last_t" bigint NOT NULL, "user_id" integer NOT NULL)
```

Is there any hope in getting this up again as my last backup was a week ago :/

**Comment by Leptopoda** [comment]
Ok I now got to the same point as: 
https://github.com/goauthentik/authentik/issues/7326

**Comment by Elevate08** [comment]
I was able to get past the following error
`django.db.utils.ProgrammingError: relation "authentik_stages_authenticator_totp_totpdevice" already exists`

by running this migration
`ak migrate authentik_stages_authenticator_totp 0010_alter_totpdevice_key --fake`

![authentik_migrations](https://github.com/goauthentik/authentik/assets/3460250/d10796c0-f360-426e-ab21-23ad0eddc058)

I had tried the migration without the --fake option and it showed the exact same error was when the container started up normally. This made me think it was the exact migration failing and that the migration did not need to be executed again.

Afterwards I restarted any containers that were still showing an error and eventually things came back up.

**Comment by keesfluitman** [comment]
so authentik has crashed for all of us? It's not working for me. I tried to run that command just as I start the container, but the container still crashes and stops with the same error. Any solutions present?

**Comment by keesfluitman** [comment]
> Hi there and thanks for the fast reply. Looks like my db is f***ed. Running the mentioned command:
> 
> ```
> {"app_name": "authentik.stages.authenticator", "event": "Could not import app's URLs", "exc": "ModuleNotFoundError(\"No module named 'authentik.stages.authenticator.urls'\")", "level": "warning", "logger": "authentik.api.v3.urls", "pid": 113, "timestamp": "2023-10-27T10:44:52.005398"}
> Operations to perform:
>   Target specific migration: 0009_throttling, from authentik_stages_authenticator_static
> Running migrations:
>   No migrations to apply.
> ```
> 
> Next start of the server:
> 
> ```
> Operations to perform:
>   Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_password, authentik_policies_reputation, authentik_providers_ldap, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_rbac, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, sessions
> Running migrations:
>   Applying authentik_stages_authenticator_totp.0008_initial...Traceback (most recent call last):
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
>     return self.cursor.execute(sql)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
>     return super().execute(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
>     raise ex.with_traceback(None)
> psycopg.errors.DuplicateTable: relation "authentik_stages_authenticator_totp_totpdevice" already exists
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/lifecycle/migrate.py", line 112, in <module>
>     execute_from_command_line(["", "migrate"])
>   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
>     utility.execute()
>   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
>     output = self.handle(*args, **options)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
>     res = handle_func(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
>     post_migrate_state = executor.migrate(
>                          ^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
>     state = self._migrate_all_forwards(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
>     state = self.apply_migration(
>             ^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
>     state = migration.apply(state, schema_editor)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
>     operation.database_forwards(
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
>     schema_editor.create_model(model)
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 451, in create_model
>     self.execute(sql, params or None)
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
>     return super().execute(sql, params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
>     cursor.execute(sql, params)
>   File "/ak-root/venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 628, in execute
>     return real_execute(self, sql, params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
>     return self._execute_with_wrappers(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
>     with self.db.wrap_database_errors:
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/ak-root/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
>     return self.cursor.execute(sql)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
>     return super().execute(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ak-root/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
>     raise ex.with_traceback(None)
> django.db.utils.ProgrammingError: relation "authentik_stages_authenticator_totp_totpdevice" already exists
> ```
> 
> Postgres:
> 
> ```
> authentik-postgresql-1  | 2023-10-27 10:45:35.704 UTC [31] ERROR:  relation "authentik_stages_authenticator_totp_totpdevice" already exists
> authentik-postgresql-1  | 2023-10-27 10:45:35.704 UTC [31] STATEMENT:  CREATE TABLE "authentik_stages_authenticator_totp_totpdevice" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(64) NOT NULL, "confirmed" boolean NOT NULL, "key" varchar(80) NOT NULL, "step" smallint NOT NULL CHECK ("step" >= 0), "t0" bigint NOT NULL, "digits" smallint NOT NULL CHECK ("digits" >= 0), "tolerance" smallint NOT NULL CHECK ("tolerance" >= 0), "drift" smallint NOT NULL, "last_t" bigint NOT NULL, "user_id" integer NOT NULL)
> ```
> 
> Is there any hope in getting this up again as my last backup was a week ago :/

hey how did you run this command? my containers never get up since this error comes before it is running properly. Attempting to run the command in the starting container doesn't bring any results.

**Comment by Elevate08** [comment]
@keesfluitman
 
I was able to run the command this way (I'm using K3S). Mainly what I wanted to share is running the command from the 'exec' command rather than entering a shell in the pod and then running the command.

`kubectl exec -it -n authentik authentik-server-696fdc5675-czqv2 -- /bin/bash ak migrate authentik_stages_authenticator_totp 0010_alter_totpdevice_key`

You should be able to get the command to trigger the migration and see the following output as it starts up.

![image](https://github.com/goauthentik/authentik/assets/3460250/5b9f68d4-104a-4228-8d9e-eadc77f7ef51)

If it doesn't trigger I'd keep trying or you could look into tweaking the pod deployment specifically the liveness / readiness configurations.

**Comment by los93sol** [comment]
If you’re on docker the alternative is to mount the DB in a Postgres container and run the SQL from my post on this thread manually

**Comment by keesfluitman** [comment]
> If you’re on docker the alternative is to mount the DB in a Postgres container and run the SQL from my post on this thread manually

I don't see your post where there is any postgres shell command. Postgres is already running in a separate docker container. 

My error is this
```
django.db.utils.ProgrammingError: relation "authentik_stages_authenticator_totp_totpdevice" already exists
```

**Comment by Elevate08** [comment]
You should be able to run something like this (guessing on the container name) after a restart of the container. You shouldn't need to do anything with the authentik-worker container (except possibly a restart once you get the migration to run)

`docker exec -it authentik-server -- /bin/bash ak migrate authentik_stages_authenticator_totp 0010_alter_totpdevice_key`

**Comment by keesfluitman** [comment]
> You should be able to run something like this (guessing on the container name) after a restart of the container. You shouldn't need to do anything with the authentik-worker container (except possibly a restart once you get the migration to run)
> 
> `docker exec -it authentik-server -- /bin/bash ak migrate authentik_stages_authenticator_totp 0010_alter_totpdevice_key`

really appreciate you taking the time. 
But Since the authentik container crashes almost instantly, i have to start it, quickly run the command, and then it still goes down with the same error. I know a bit about docker, but I'm guessing that my command is never actually ran?

**Comment by keesfluitman** [comment]
> I came from 2023.8 and still had this issue. I ended up manually inserting the migration records into the database, oddly enough, comparing the code in the migrations against my database it appears they actually had been applied properly as all the new fields were there...
> 
> insert into django_migrations (app, name, applied) VALUES ('authentik_stages_authenticator_static', '0008_initial', current_timestamp); insert into django_migrations (app, name, applied) VALUES ('authentik_stages_authenticator_static', '0009_throttling', current_timestamp); insert into django_migrations (app, name, applied) VALUES ('authentik_stages_authenticator_totp', '0008_initial', current_timestamp); insert into django_migrations (app, name, applied) VALUES ('authentik_stages_authenticator_totp', '0009_auto_20190420_0723', current_timestamp);

this actually worked.
