### ISSUE TITLE
Newly created OAuth2 provider does not allow userinfo access 2023.10.1

### ISSUE THREAD

**Issue by rqi14** [goauthentik/authentik#7339]
**Describe the bug**
Accessing `/application/o/userinfo/` fails for newly created OAuth2 provider. Oddly, it fails for only the latest OAuth2 providers (created in 2023.8.3). Older ones are totally fine, even if the settings look the same. If creating new OAuth2 providers, I see the same error.
```
HTTP/1.1 403 Forbidden
Content-Type: text/html; charset=utf-8,
Date: Fri, 27 Oct 2023 10:14:52 GMT,
Referrer-Policy: same-origin,
Server: nginx,
Vary: Accept-Encoding,
Www-Authenticate: error=\insufficient_scope\, error_description=\The request requires higher privileges than provided by the access token\,
X-Authentik-Id: 4c7c19c9447e4fba855dafa0a949b01f,
X-Content-Type-Options: nosniff,
X-Frame-Options: DENY,
X-Powered-By: authentik
```

**To Reproduce**

1. Go to Providers
2. Create a new OAuth2 provider 
3. Associate it with an application.
4. Request for Authorization Code (I used https://github.com/ECNU/Open-OAuth2Playground for testing)
5. Fetch token with Authorization Code
6. Request to userinfo url with the access_token
7. See error in the response

**Expected behavior**

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/26152437/3ebe3ab9-58a6-4b9d-82b7-af2f7f76b3c5)

**Logs**
Output of docker-compose logs or kubectl logs respectively
Logs are fine because userinfo request does not seem to be logged.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.1 (upgraded from 2023.8.3)
-   Deployment: docker compose

**Additional context**

**Comment by BeryJu** [comment]
Can you check the authentik server logs for a warning of `Scope mismatch.`?

**Comment by rqi14** [comment]
> Can you check the authentik server logs for a warning of `Scope mismatch.`?

Yes
`{"auth_via": "unauthenticated", "event": "Scope mismatch.", "host": "authentik.fqdn", "level": "warning", "logger": "authentik.providers.oauth2.utils", "pid": 33, "request_id": "c900992188604934a9f5dd621c82ebbe", "required": "{'openid'}", "timestamp": "2023-10-28T08:23:47.716351", "token_has": "{'Basic'}"}`

but the scope should be available
![image](https://github.com/goauthentik/authentik/assets/26152437/28c42456-2310-4d9f-a8dd-166573393556)

**Comment by ghothan87** [comment]
I am seeing this same issue on v2023.10.4.  Does this bug still exist in the code base?  Thanks

**Comment by vaibhav-kulkarni** [comment]
I faced the same issue, but I could resolve it by adding the "openid" scope when initiating the authorization flow.

**Comment by cfredericksen** [comment]
> I faced the same issue, but I could resolve it by adding the "openid" scope when initiating the authorization flow.

I facing this issue. How do you add the "openid" scope to the authorization flow?

**Comment by vaibhav-kulkarni** [comment]
> I'm facing this issue. How do you add the "openid" scope to the authorization flow?

@cfredericksen 
It depends on how you're integrating Authentik. For e.g., in my case, I was manually generating the /authorize/ URL, to which I had to add the "scope" query parameter, apart from the other required parameters (namely "response_type", "redirect_uri", "state" and "client_id"). Note: if you want to specify multiple scopes, they need to separated by spaces.

If, on the other hand, you're using some library for oauth2 integration, it should be having an option to specify the scope.
