### ISSUE TITLE
Simple LDAP server (possibly with glauth)

### ISSUE THREAD

**Issue by traverseda** [goauthentik/authentik#737]
**Is your feature request related to a problem? Please describe.**

LDAP is tricky to set up, and I'd rather my single source of truth be something like this,

**Describe the solution you'd like**

Embed a [glauth](https://github.com/glauth/glauth) configuration generator in authentik, similar to how [glauth-ui](https://github.com/sonicnkt/glauth-ui) works. Include glauth examples in the docker compose files.

**Describe alternatives you've considered**

This is more an ease of use thing, there are definitely alternative solutions but they don't let you mention "LDAP server" in your list of features.

**Comment by BeryJu** [comment]
Hey,

I'm not quite sure how I feel about this suggestion, I see how it would make things easier, but there's several objections:

- I'd prefer to not implement special support for a single tool, if it was a common protocol then it would make more sense
- I assume you'd want the the generated config to just have the authentik users, so you can just run glauth against that? For this case I was actually playing with the idea of adding LDAP Server support to the Outpost, which would have the same outcome, and be natively integrated.
- I want to be very careful with putting LDAP Sever in the list of features as I don't want to give the impression that a user needs an LDAP Server to setup authentik.

For the LDAP server support, are you more interested in just binding for authentication? Or full LDAP, including searches etc?

**Comment by traverseda** [comment]
glauth is a very minimal read-only LDAP interface, that works with the data you provide it. This makes is a lot simpler then a traditional LDAP stack, it's basically a library that works with the data you provide.

>I'd prefer to not implement special support for a single tool, if it was a common protocol then it would make more sense

glauth is read-only, it's more of a library then a specific tool, and would save you from implementing your own basic LDAP server.

>and be natively integrated.

Sounds good, although it seems like it might be more work. Either way seems like it would solve the problem

>For the LDAP server support, are you more interested in just binding for authentication? Or full LDAP, including searches etc?

Somewhere in between, basic LDAP searches to let you filter users based on groups, but definitely not a full LDAP server and all that entails. Keep it simple, keep it to the very basics to allows filtering. Stuff like `(memberOf=cn=jellyfin_admin,ou=groups,dc=example,dc=com)`. Checking group membership is really the only search I anticipate needing.

**Comment by traverseda** [comment]
>I want to be very careful with putting LDAP Sever in the list of features as I don't want to give the impression that a user needs an LDAP Server to setup authentik.

For sure, that's why I was imagining something like "provides basic authentication for LDAP apps".

**Comment by BeryJu** [comment]
> glauth is read-only, it's more of a library then a specific tool, and would save you from implementing your own basic LDAP server.

I think for the LDAP Server in the outpost I'll do the same as with oauth2_proxy, actually use glauth as a library but have it directly talk to the authentik API.

**Comment by traverseda** [comment]
Seems like a solid plan, it seems to be one of the more sane LDAP servers/libraries out there, and it's good enough that most stuff seems to be able to authenticate against it without any real trouble.
