### ISSUE TITLE
Health endpoint not available after latest update

### ISSUE THREAD

**Issue by johanneszelger** [goauthentik/authentik#7371]
**Describe the bug**
https://auth.domaincom/-/health/live is not found any more since last update

**To Reproduce**
Go to https://auth.domaincom/-/health/live

**Expected behavior**
health endpoint response

**Screenshots**

**Logs**
none

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
2023.10.2

**Additional context**

**Comment by BeryJu** [comment]
The health endpoints are `/-/health/live/` and `[...]/ready/`, trailing slashes are required

**Comment by johanneszelger** [comment]
That's true, that solved the issue, thank you.

However, is there a chance older releases where more leniant regarding that trailing slash? I realized today that a few of our logins were broken due to the same reason. Yesterday the update was deployed, before that, everthing seems to have worked without trailing slashes.

**Comment by BeryJu** [comment]
Yes, it was initially missing from the release notes for 2023.10 but now there's a note about it
