### ISSUE TITLE
Can't change URL settings in Azure AD Social Login

### ISSUE THREAD

**Issue by lameslime** [goauthentik/authentik#7383]
**Describe the bug**
Can't change URL settings in Azure AD Social Login

**To Reproduce**

1. Had 2023.8
2. Upgraded to 2023.10.2
3. Attempted to add new social login
4. URL settings fields are force set to 
 - https://login.microsoftonline.com/common/oauth2/authorize
 - https://login.microsoftonline.com/common/oauth2/token
 - https://login.microsoftonline.com/common/openid/userinfo
5. Attempted changes result in 200 request succeeded 

**Expected behavior**
URL changes after modifying

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/46740316/8f1cd5ff-da70-448b-83c0-d97928978bd9)

**Logs**
I would need help, as everything I see is 200

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: compose

**Additional context**

**Comment by lameslime** [comment]
More info, the only way seems to connect to the DB directly and then edit the url values. 

Also during the enrollment if user quits (can't do forced mfa at that moment) and then logs in later to start then enrollment again it fails, as the account is then in a limbo state. Only fix is to delete the account and tell the user to try logging in again. 

I tried using default policies and tried creating custom ones with different combinations of login, fill and mfa steps - couldn't solve it.

**Comment by vb4life** [comment]
Same for me.. Freshly setup authentik 2023.10 on my lab computer, and I can't update any of the URL settings:
![image](https://github.com/goauthentik/authentik/assets/7789599/f64d4a4a-9b04-44b7-bb3d-97b43c348ba6)

**Comment by wazoo** [comment]
Hello!  I just ran into this today and just in case it is helpful I hit it using the terraform provider, it attempts to change them but they don't get updated (and terraform thinks it was a success).  

I found some of the entries in the database but changing them didn't seem to update them in the UI so I am assuming I didn't have the right table.

**Comment by lameslime** [comment]
> I found some of the entries in the database but changing them didn't seem to update them in the UI so I am assuming I didn't have the right table.

Changing them works, but isn't shown in UI.

**Comment by nusol-sc** [comment]
I just ran into the same problem.

Also worth noting is that if you attempt to make ANY changes to the source via the UI after manually updating the database, the URLs will be reverted to the defaults.

**Comment by BeryJu** [comment]
The issue itself comes from the fact that 2023.10 adds default OIDC well-known and JWKS URLs for azure AD (and google and github), which are used when updating the source to fetch the correct OAuth urls; however for non OIDC sources the input to change those URLs wasnt shown hence when saving with different URLs this would happen

**Comment by hkjarral** [comment]
This issue is still happening with 2023.10.4 as well. Just tested it. Replacing common value in Azure AD Oaauth Source does not gets saved and still shows common in UI.

**Comment by BeryJu** [comment]
There isn't a disclaimer for it, but you need to either change the well-known URL to the one from your Azure AD tenant or remove its value fully

**Comment by BeryJu** [comment]
There is with 2023.10.4, make sure to clear your browser cache too after upgrading.

**Comment by hkjarral** [comment]
I did try clearing cache on 2 different browsers, Still don't see it. Anyone else also seeing this or updated URLs ?

![Xnip2023-11-27_13-41-31](https://github.com/goauthentik/authentik/assets/42726887/0d2dd78b-abc7-4fa3-96e3-41e99102c3f3)

**Comment by BeryJu** [comment]
See https://github.com/goauthentik/authentik/issues/7744#issuecomment-1867022311
