### ISSUE TITLE
Expired certificates are still working

### ISSUE THREAD

**Issue by loikki** [goauthentik/authentik#7391]
**Describe your question/**
I have been using authentik for over a year and I am very happy about it. Unfortunately my only certificate (the one generated automatically by authentik) is expired. I am wondering why authentik can still work if it does not have a valid certificate? Could it be a security issue?

Thanks a lot for your help.

**Screenshots**
Certificates:
![image](https://github.com/goauthentik/authentik/assets/14158679/d0e28a9b-3b24-455d-a63f-90781e0b055a)

Provider:
![image](https://github.com/goauthentik/authentik/assets/14158679/26368e98-f39e-4437-a194-9ef68b88671a)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.1
-   Deployment: helm

**Comment by BeryJu** [comment]
authentik itself does not need any certificate to function; if a certificate used by OAuth or SAML needs to be valid very much depends on the application checking it.

**Comment by loikki** [comment]
Thanks for the fast answer. It still puzzle me that in the provider you ask for the signing key. It needs one to sign the tokens, right? It just that authentik does not care if the certificate is up to date, right?
