### ISSUE TITLE
OAuth2 Provider -> Edit -> Checkbox: Include claims in id_token ? - label display error + no state retain

### ISSUE THREAD

**Issue by oopen** [goauthentik/authentik#7405]
**Describe the bug**
When you edit a OAuth2 Provider
The checkbox "Include claims in id_token ?" have 2 problems :

1. Label display error
2. State is not retain (active state)

**To Reproduce**

1. Go to ==> OAuth2 Provider
3. Click on 'YOUR PRIVIDER'
4. Click on 'Edit' button
6. Click on 'Update' button

**Expected behavior**
The checked active state must be preserved

**Screenshots**
![Capture d’écran du 2023-11-01 11-52-51](https://github.com/goauthentik/authentik/assets/7348132/cb350529-2345-4ed3-adff-adafe1878a84)

**Version and Deployment**

-   authentik version: ghcr.io/goauthentik/server:2023.10.2
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
fixed by #7384
