### ISSUE TITLE
Webhook notification transport is missing webhook input field

### ISSUE THREAD

**Issue by ggondim** [goauthentik/authentik#7418]
**Describe the bug**

When creating a new webhook transport, the webhook field is missing, causing an error (inspectable in devtools).

**To Reproduce**

1. Go to 'Notification Transports'
2. Click on 'Create'
3. Select 'Webhook' (either generic or Slack/Discord)
4. Give transport a name and click 'Create'

**Expected behavior**

A webhook URL input should be presented.

**Screenshots**

Modal missing input:

![image](https://github.com/goauthentik/authentik/assets/2074685/46e4e7b6-a79d-42e1-950f-37d23ad40c69)

Notification toast upon click with empty message:

![image](https://github.com/goauthentik/authentik/assets/2074685/ea236976-eb0b-4f34-8c80-74cb6a723a9f)

**Logs**

Output of HTML in DevTools, showing the component as "hidden":

![image](https://github.com/goauthentik/authentik/assets/2074685/a8954a7c-4498-47a4-885d-906fb61bc53f)

Output of Network in DevTools, showing the API response error:

![image](https://github.com/goauthentik/authentik/assets/2074685/4b7bd09b-3332-44d3-a11c-e3ad8f6cc23e)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.1
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
This is fixed by https://github.com/goauthentik/authentik/pull/7348 which is included in 2023.10.2
