### ISSUE TITLE
Proxy providers suddenly stop working and hit a redirect loop

### ISSUE THREAD

**Issue by brujoand** [goauthentik/authentik#7435]
**Describe the bug**
One or two of the applications using proxy provider will stop working. They will just go for an infinite redirect loop until I recreate them from scratch in Authentik. Sometimes they can start working again seemingly at random. Looking at the logs all I see is the redirect being logged. All these apps are registerted as app.mydomain.com without any path fiddling. Ref: #6540  

The applications are mostly in the k8s cluster, and I use local dns to reach them. For instance http://frigate.automation.svc.cluster.local:5000/, with https://frigate.mydomain.com/ as the external url. The only problem I'm seeing in the worker/server logs is "context canceled" "failed to proxy to backend". Worker and Server logs from a redirect loop is over here: https://gist.github.com/brujoand/37b372545f4a5ad86828077f1f230de3

**To Reproduce**
1. Create a proxy provider
2. Create an application using the proxy provider
3. Add the application to an outputs
4. Repeat and wait for some of the applications to go into a infinite redirect loop

**Expected behavior**
There should be a simple auth flow and the application should appear, instead of a redirect loop

**Screenshots**

**Logs**
Logs are here: https://gist.github.com/brujoand/37b372545f4a5ad86828077f1f230de3

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: Helm

**Additional context**
Nope

**Comment by hdlineage** [comment]
Yes this started happening to with me in 2023.10.2 as well. going to downgrade for 2023.8 for now.

**Comment by cfouche3005** [comment]
same behaviour with forward auth

**Comment by brujoand** [comment]
Can note that this behavior is also present on 2023.10.1 and 2023.10.0. One thing that puzzles me though is that logging in with the same user on two different machines yields different results. Some sites I can login to on one machine, while on another machine that site death loops and vice versa for other sites.

**Comment by brujoand** [comment]
I've also tested with the images from #7385 which was referenced in #7374 and #7342 but that didn't make much difference unfortunately.

**Comment by phoen88** [comment]
Adding to this, still having issues on my install as well. Was driving me crazy as a recently joined user as well. Earlier versions work but I run into other issues, namely with permissions binding.

**Comment by brujoand** [comment]
After upgrading to 2023.10.3 and deleting all browser state I’m unable to reproduce this problem. Thanks!

**Comment by brujoand** [comment]
Unfortunately this problem reappeared with the same symptoms as before.

**Comment by hdlineage** [comment]
For me the issue no longer exists in 2023.10.3 for now, will continue to monitor.

**Comment by phoen88** [comment]
It appears to be super intermittent in my case. I notice though that sometimes it'll eventually let you in when you come back later - like 5-10 minutes later - and when trying to 'Launch' from the Authentik dashboard. Hasn't been an issue further from there unless of course you log out and in again. It's more annoying rather than service impacting. Also on 10.3.

**Comment by OsteHovel** [comment]
Yea this still happens on 10.3 but not if you run old proxies at 2023.8 and Authentik 10.3.
I do not have a clear reproduction steps but if I clear cookies and login again it does NOT happen.
Seems to only be happening if you been signed in to Authentik (not the proxy) for a while.

**Comment by brujoand** [comment]
I tried setting the outputs log level to trace, which gave the following error when hitting a loopy application:
```
{
  "error": "open /tmp/session_3US4WE2WMLA4UZEGKKKPYJTIBZRRV3T2YRX6JWNKHSTZ6DBVT7LQ: no such file or directory",
  "event": "failed to decode session",
  "level": "warning",
  "logger": "authentik.outpost.proxyv2.application",
  "name": "Frigate",
  "timestamp": "2023-11-12T07:08:18Z"
}
```

**Comment by brujoand** [comment]
Just throwing stuff at the wall here. When I check the statistics over logins pr application, try to login to a looping application and count how many times I'm redirected, the loop count is always half of the increased number of logins on the application. Do we have a race condition where we authenticate twice?

**Comment by aheath70** [comment]
Following as I appear to be having similar issues. Due to it's intermittent nature, I feel like I am goiing in circles though. Works perfectly for one app for not for others.

**Comment by YTOAA** [comment]
I also downloaded to 2023.8.4 after finding the same symptoms in 2023.10.* versions. Everything then works fine.

**Comment by Simon-Design** [comment]
i have the same issue when n application is not in the root directory of the domain and the requested url is not a .php or .html file...
Still no idea how to fix it

**Comment by frprm** [comment]
I experience the same issue after upgrading to 2013.10.

**Comment by tkdrob** [comment]
I've seen this as well but not recently and currently running 2013.10.3, YMMV. I have noticed that the Authentik cookie for an app does not seem to expire now nor does it redirect back to Authentik to verify a valid session. I have app sessions set to 1 hour. Did something change intentionally or is this also a bug?

**Comment by l-maia** [comment]
I have this issue with the 10.3, with an error opening the session file in the integration pod and in each loop a new session is written to /tmp/.

From a cursory look at the source seems that there is a difference in session handling between the integration and embedded proxy (redis or file based).

If you cannot reproduce this, are you using embedded?

**Comment by janosmiko** [comment]
I'm facing the same issue. I've tried to downgrade to 2023.8.4, but I'm facing the error below.

How did you manage to downgrade guys?

```
Operations to perform:
  Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_password, authentik_policies_reputation, authentik_providers_ldap, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, otp_static, otp_totp, sessions
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.DuplicateTable: relation "otp_static_staticdevice_user_id_7f9cff2b" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
...
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "otp_static_staticdevice_user_id_7f9cff2b" already exists
  Applying otp_static.0001_initial
```

**Comment by ytoaa** [comment]
> 나는 같은 문제에 직면하고 있습니다. 2023.8.4로 다운그레이드하려고 했는데 아래와 같은 오류가 발생했습니다.
> 
> 어떻게 다운그레이드하셨나요?
> 
> ```
> Operations to perform:
>   Apply all migrations: auth, authentik_blueprints, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_password, authentik_policies_reputation, authentik_providers_ldap, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, otp_static, otp_totp, sessions
> Running migrations:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
>     return self.cursor.execute(sql)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
>     return super().execute(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
>     raise ex.with_traceback(None)
> psycopg.errors.DuplicateTable: relation "otp_static_staticdevice_user_id_7f9cff2b" already exists
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
> ...
>   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
>     return self.cursor.execute(sql)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
>     return super().execute(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
>     raise ex.with_traceback(None)
> django.db.utils.ProgrammingError: relation "otp_static_staticdevice_user_id_7f9cff2b" already exists
>   Applying otp_static.0001_initial
> ```

Unfortunately, we reinstalled it to version 8.4 after initialization.

**Comment by l-maia** [comment]
Built from source from the main branch that has the commits referenced above and it fixed the problem without having to go through the  downgrade route.

**Comment by brujoand** [comment]
Fixed by 2023.10.4 

thanks 👍

**Comment by jaredallard** [comment]
Did anyone have to do something after upgrading? I'm still hitting this on 2023.10.4 and it's maddening, can't login to anything without a redirect loop at this point....

**Comment by Simon-Design** [comment]
> Did anyone have to do something after upgrading? I'm still hitting this on 2023.10.4 and it's maddening, can't login to anything without a redirect loop at this point....

same for me... nothing has changed

**Comment by jmdilly** [comment]
On my side, I deleted the old cookies in browsers and now it works fine.

**Comment by Hyurt** [comment]
> On my side, I deleted the old cookies in browsers and now it works fine.

This - make sure you restart as well workers/outpost integrations as well.

**Comment by jaredallard** [comment]
Restarting everything and deleting cookies didn't do it for me 😢

**Comment by jaredallard** [comment]
Oh, wait, it's working now. I think clearing the cookies did help, but I think I did an ineffective job of clearing them at first (cleared everyone one for the top-level domain I was using).
