### ISSUE TITLE
High I/O Timeout Causes Crash

### ISSUE THREAD

**Issue by nrgbistro** [goauthentik/authentik#7462]
**Describe the bug**
When my server is experiencing high i/o loads, my Authentik server will occasionally crash.

**To Reproduce**

1. Run authentik server with high i/o wait

**Expected behavior**
The Authentik server shouldn't crash, instead it should wait for the resource to be available

**Logs**
```
panic: i/o timeout

goroutine 97 [running]:
goauthentik.io/internal/outpost/proxyv2/application.(*Application).getStore(_, {0x4, {0xc00bdee690, 0xb}, 0xc0042808c0, {0xc0149843a0, 0x20}, 0xc00bdee69b, 0xc0042808d0, 0xc0042808e0, ...}, ...)
        /go/src/goauthentik.io/internal/outpost/proxyv2/application/session.go:43 +0x439
goauthentik.io/internal/outpost/proxyv2/application.NewApplication({0x4, {0xc00bdee690, 0xb}, 0xc0042808c0, {0xc0149843a0, 0x20}, 0xc00bdee69b, 0xc0042808d0, 0xc0042808e0, {{0xc00065b6e0, ...}, ...}, ...}, ...)
        /go/src/goauthentik.io/internal/outpost/proxyv2/application/application.go:140 +0xfce
goauthentik.io/internal/outpost/proxyv2.(*ProxyServer).Refresh(0xc00012f130)
        /go/src/goauthentik.io/internal/outpost/proxyv2/refresh.go:37 +0x587
goauthentik.io/internal/outpost/ak.(*APIController).OnRefresh(0xc0006781c0)
        /go/src/goauthentik.io/internal/outpost/ak/api.go:180 +0x314
goauthentik.io/internal/outpost/ak.(*APIController).startIntervalUpdater(0xc0006781c0)
        /go/src/goauthentik.io/internal/outpost/ak/api_ws.go:191 +0x17b
goauthentik.io/internal/outpost/ak.(*APIController).StartBackgroundTasks.func3()
        /go/src/goauthentik.io/internal/outpost/ak/api.go:218 +0x5d
created by goauthentik.io/internal/outpost/ak.(*APIController).StartBackgroundTasks in goroutine 55
        /go/src/goauthentik.io/internal/outpost/ak/api.go:216 +0x38d
```
**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: docker-compose on Unraid

**Comment by leutnantlurch** [comment]
Hello! I have the same issue, with the same setup! I run Authentik on unraid and the Authentik docker crashes :(

![grafik](https://github.com/goauthentik/authentik/assets/129696204/76104cd8-d2ab-49e2-828a-424ef00f490f)

**Comment by nrgbistro** [comment]
This issue is causing daily crashes of authenticated services on my server. I don't understand why this issue would be closed without any intervention. it is clearly not an isolated issue.

**Comment by bhavikbhakta** [comment]
I'm also having the same issue.
Docker on UNRAID.  Seems to be daily.  
Currently have to have a CRON job that runs hourly to check and start the container.
