### ISSUE TITLE
Are system tasks supposed to run automatically, and if so, why aren't most of mine?

### ISSUE THREAD

**Issue by aheath70** [goauthentik/authentik#7463]
**Describe your question/**
Only a few of my system tasks appear to be running automatically. If I run them manually, they succeed, but they never run automatically. 

Wondering if this may explain why also the certificate being presented when I hit the web page for Authentik is the default authentik certificate, even though I have set it to be my LE wildcard certificate.

Screenshot shows a lot of tasks with status "unknown". These are the ones I suspect are not running automatically. I am not sure how often they are supposed to run. The "certificate_discovery" task also does not run automatically, but I manually ran that manually to get my LE certs discovered. 

**Relevant infos**
Running Authentik 2023.10.2 under Docker, using the default Docker compose file as per the instructions. 

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/48014700/45955c99-fc72-4a69-a94b-61d471a4460d)
Screenshot shows a lot of tasks with status "unknown", as well as the "certificate_disovery" task, which I ran manually. 

**Logs**
I am fairly new to Docker and unsure how to get these. If someone can give me some guidance, happy to get these logs.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: docker compose

**Additional context**
None that I can think of

**Comment by BeryJu** [comment]
This was a bug with 2023.10.2, and is fixed with 2023.10.3 (see https://github.com/goauthentik/authentik/pull/7508)
