### ISSUE TITLE
Impossible to use the LDAP Provider when adding a WebAuthn key

### ISSUE THREAD

**Issue by foux** [goauthentik/authentik#7478]
**Describe the bug**
If using the LDAP Provider, any user with a WebAUthn key would fail login with the error `no compatible authenticator class found`

**To Reproduce**
1. Add an application with an LDAP outpost
2. Add a user with a WebAuthn key
3. Try to login to the LDAP application with the user having a WebAuthn key

**Expected behavior**
User should be able to login

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
Does the user you're testing with have any other kind of Authenticator device set up?

**Comment by foux** [comment]
No just this one, but as it is LDAP I don't suppose this will change anything, does it?
I can't add TOTP because for LDAP you need all users to have TOTP if one has, and you have to input the TOTP into the password

**Comment by BeryJu** [comment]
If your ldap authentication flow has an authenticator-validation stage and the user has any of the authenticators allowed, then LDAP authentication will fail as webauthn can't be done over LDAP.

You can create a separate flow without that stage for just LDAP usage, which will fix this.

**Comment by foux** [comment]
Oh great, I didn’t think about that. Thanks a lot, I’ll try that tomorrow morning

**Comment by foux** [comment]
THat works like a charm, thanks for your help
