### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#748]
Make it possible to translate Authentik in other languages. Maybe I can help with the dutch language.

**Comment by BeryJu** [comment]
Authentik is fully translate-able, the frontend uses lingui for this and the backend uses the native django translation Library. I'm not quite sure what the go-to tooling for this is, besides just editing the PO files by hand.

To add a new locale to the frontend:

Add it to this block in `/web/package.json`

```json
    "lingui": {
        "locales": [
            "en",
            "pseudo-LOCALE"
        ],
```

Afterwards, run `npx lingui extract` to extract the base PO files, which can then be translated and committed.

**Comment by Akruidenberg** [comment]
Maybe you can take a look at external services like transifex? Its nicer with multiple people.

**Comment by BeryJu** [comment]
I must've completely missed that transifex is free for open-source projects, I'll set it up.

**Comment by BeryJu** [comment]
@Akruidenberg can you try https://www.transifex.com/beryjuorg/authentik/ ?

**Comment by Akruidenberg** [comment]
@BeryJu. I have made a account,

**Comment by Akruidenberg** [comment]
Transifex link in the readme dont work.

**Comment by BeryJu** [comment]
Accidentally added it as an image instead of a link, is fixed now.

**Comment by Akruidenberg** [comment]
I don´t have any permission to begin translating at the moment right now.

**Comment by BeryJu** [comment]
I've just accepted your translation request, my bad for taking so long, this is my first time using transifex
