### ISSUE TITLE
Webhook Notification Transport - Client Error 400

### ISSUE THREAD

**Issue by maurxce** [goauthentik/authentik#7489]
**Describe the bug**
I'm trying to set up a Notification Transport to a discord webhook, but I always get an Internal Server Error

**To Reproduce**

1. Go to `Events > Noification Transports > Create`
2. Use the following settings:
  - Name: `Discord`
  - Mode: `Webhook (Slack/Discord)`
  - Webhook URL: `<URL>`
  - Send once
3. Click on the test button

**Expected behavior**
A test notification will be sent to my discord server

**Screenshots**
(TBA)

**Logs**
```
# Browser Console
TransportListPage.ts:96 
POST https://<domain>/api/v3/events/transports/c7734095-f8b5-4400-8778-f5884a10aaf1/test/ 500 (Internal Server Error)
```
```
# Server Log
{"event": "Internal Server Error: /api/v3/events/transports/c7734095-f8b5-4400-8778-f5884a10aaf1/test/", "level": "error", "logger": "django.request", "timestamp": 1699120874.5951135}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: docker-compose

[Thread on Discord](https://discord.com/channels/809154715984199690/1170422913300693022)

**Comment by ctuIhu** [comment]
Currently experiencing this. After changing the webhool url the Notification Transports doesnt work anymore.

Webhook is active and working but when testing the error is below:

(redacted secrets)
"400 Client Error: Bad Request for url: https://discord.com/api/webhooks/*/*"

**Comment by maurxce** [comment]
> "400 Client Error: Bad Request for url: https://discord.com/api/webhooks/*/*"

The ResponseError 500 seemed to be caused because I hadn't set up a Notification Rule yet.
Now I also get this error

**Comment by maurxce** [comment]
@ctuIhu My issue was not adding `/slack` to the end of my webhook url. Did you forget that too perhaps?
