### ISSUE TITLE
Connecting guacamole

### ISSUE THREAD

**Issue by Smiley-k** [goauthentik/authentik#7503]
I've spent a lot of time trying to solve this problem.

`[2023-11-09 03:35:25] [info] 03:35:25.232 [http-nio-8080-exec-1] WARN  o.a.g.a.o.t.TokenValidationService - Username claim "email" missing from token. Perhaps the OpenID scope and/or username claim type are misconfigured?`

Unfortunately there is no information about it in the documentation on the integration ( https://goauthentik.io/integrations/services/apache-guacamole ), and the authorization does not pass at all without it  

Please add this key to the site to make life a little easier for colleagues
**openid-username-claim-type: sub**

but I would also be grateful if someone could share other working attributes, as right now my username consists of email when using the **sub** attribute it's not right of course, but it works for now....

https://github.com/goauthentik/authentik/assets/11009787/e4435a1a-62b2-4e19-98fe-8fb3fa27a7c0

**Comment by UlascanY** [comment]
Hello @Smiley-k,

I'm encountering challenges in integrating Authentik with Guacamole. Despite following the guide on Authentik, I'm facing issues. When I access my Guacamole site, it redirects me to Authentik, where I can log in successfully. However, upon redirection back to Guacamole, I receive a 'Login failed' message.

Could you kindly share a step-by-step guide on how you configured Authentik and Guacamole? I am operating Guacamole and Authentik within a Kubernetes cluster and would greatly appreciate your insights.
Do you have a specific user-mapping.xml in guacamole?

Thank you!

To investigate my Issue I'have enabled DEBUG mode in guacamole by adding "logback.xml" to $GUAC_HOME

DEBUG LOGS:
16:08:40.539 [http-nio-8080-exec-2] DEBUG o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection                                                                                                                                                                                                                        │
│ 16:08:40.540 [http-nio-8080-exec-2] DEBUG o.a.g.a.j.DynamicallyAuthenticatedDataSource - Creating new database connection for pool.                                                                                                                                                                                     │
│ 16:08:45.139 [http-nio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Created connection 1018260326.                                                                                                                                                                                                              │
│ 16:08:45.140 [http-nio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Testing connection 1018260326 ...                                                                                                                                                                                                           │
│ 16:08:45.641 [http-nio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Connection 1018260326 is GOOD!                                                                                                                                                                                                              │
│ 16:08:45.645 [http-nio-8080-exec-2] DEBUG o.a.g.a.j.user.UserMapper.selectOne - ==>  Preparing: SELECT guacamole_user.user_id, guacamole_entity.entity_id, guacamole_entity.name, password_hash, password_salt, password_date, disabled, expired, access_window_start, access_window_end, valid_from, valid_until, time │
│ zone, full_name, email_address, organization, organizational_role, MAX(start_date) AS last_active FROM guacamole_user JOIN guacamole_entity ON guacamole_user.entity_id = guacamole_entity.entity_id LEFT JOIN guacamole_user_history ON guacamole_user_history.user_id = guacamole_user.user_id WHERE guacamole_entity │
│ .name = ? AND guacamole_entity.type = 'USER'::guacamole_entity_type GROUP BY guacamole_user.user_id, guacamole_entity.entity_id; SELECT guacamole_user_attribute.user_id, guacamole_user_attribute.attribute_name, guacamole_user_attribute.attribute_value FROM guacamole_user_attribute JOIN guacamole_user ON guacam │
│ ole_user.user_id = guacamole_user_attribute.user_id JOIN guacamole_entity ON guacamole_user.entity_id = guacamole_entity.entity_id WHERE guacamole_entity.name = ? AND guacamole_entity.type = 'USER'::guacamole_entity_type                                                                                            │
│ 16:08:45.944 [http-nio-8080-exec-2] DEBUG o.a.g.a.j.user.UserMapper.selectOne - ==> Parameters: null, null                                                                                                                                                                                                              │
│ 16:08:46.144 [http-nio-8080-exec-2] DEBUG o.a.g.a.j.user.UserMapper.selectOne - <==      Total: 0                                                                                                                                                                                                                       │
│ 16:08:46.239 [http-nio-8080-exec-2] DEBUG o.a.i.t.jdbc.JdbcTransaction - Resetting autocommit to true on JDBC Connection [org.postgresql.jdbc.PgConnection@3cb16b66]                                                                                                                                                    │
│ 16:08:46.242 [http-nio-8080-exec-2] DEBUG o.a.i.t.jdbc.JdbcTransaction - Closing JDBC Connection [org.postgresql.jdbc.PgConnection@3cb16b66]                                                                                                                                                                            │
│ 16:08:46.242 [http-nio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Testing connection 1018260326 ...                                                                                                                                                                                                           │
│ 16:08:46.244 [http-nio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Connection 1018260326 is GOOD!                                                                                                                                                                                                              │
│ 16:08:46.244 [http-nio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Returned connection 1018260326 to pool.                                                                                                                                                                                                     │
│ 16:08:46.245 [http-nio-8080-exec-2] DEBUG o.a.g.a.f.FileAuthenticationProvider - Reading user mapping file: "/home/guacamole/.guacamole/user-mapping.xml"                                                                                                                                                               │
│ 16:08:46.345 [http-nio-8080-exec-2] DEBUG o.a.g.r.auth.AuthenticationService - Anonymous authentication attempt from [x.x.x.x, 10.0.0.7] failed.                                                                                                                                                                │
│ 16:08:46.444 [http-nio-8080-exec-2] DEBUG o.a.g.rest.RESTExceptionMapper - Client request rejected: Invalid login.                                                                                                                                                                                                      │
│ 16:08:57.140 [http-nio-8080-exec-7] DEBUG o.a.g.resource.ResourceServlet - Resource not modified: "/app.js" |

And Guacamole makes an POST Request to /guacamole/api/tokens, the response is:
`{"message":"Invalid login.","translatableMessage":{"key":"APP.TEXT_UNTRANSLATED","variables":{"MESSAGE":"Invalid login."}},"statusCode":null,"expected":[{"name":"id_token","type":"REDIRECT","redirectUrl":"xxx","translatableMessage":{"key":"LOGIN.INFO_IDP_REDIRECT_PENDING","variables":null}}],"type":"INVALID_CREDENTIALS"}`
