### ISSUE TITLE
Reverse Proxy IP instead of Client IP with Apache + non-private IP

### ISSUE THREAD

**Issue by danielperna84** [goauthentik/authentik#7504]
**Describe the bug**
We are at the beginning of evaluating Authentik to be an authentication Server at our Company. Everything is working, except that the logs report our Reverse Proxies' IP instead of the real Client IP.  I have seen #7219 and set the `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS` option to include the subnet, in which our Reverse Proxy is located. I can't say for sure if there is a problem with the Apache configuration, as the docs don't mention Apache. But since functionally everything is working - including websockets - I'm fairly sure the configuration is fine.  
One major difference is, that not only the Reverse Proxy has a public IP, but also the host for Authentik. The default CDIRs only mention private subnets, which generally is how it should be. But as that's probably the only difference, my assumption is that maybe the code handling the `X-Forwarded-For` header only works with private networks. Which normally I wouldn't even consider being a limitation, since IP-libraries shouldn't have any problem with that. But I don't have any other idea what the problem could be.

**To Reproduce**

1. Apache Reverse Proxy on Public Class C IP, f. ex. `212.80.128.70` in `212.80.128.64/26` and towards Authentik with `212.80.135.129` in `212.80.135.128/27`
2. Authentik on Ubuntu 22.04 in Docker Compose with Public Class C IP (different subnet), f. ex. `212.80.135.139` in `212.80.135.128/27`
3. Setting in `.env` file: `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS='["212.80.135.128/27","127.0.0.0/8","172.16.0.0/12","fe80::/10","::1/128"]'`
4. Start Authentik
5. Browse to Authentik
6. See incorrect IP in Logs and Dashboard

**Expected behavior**
The logs should show the real Client IP, not the IP of the Reverse Proxy.

**Logs**
```
{"auth_via": "session", "event": "/api/v3/admin/workers/", "host": "sec-login.example.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 38, "remote": "212.80.135.129", "request_id": "abcd...", "runtime": 754, "scheme": "https", "status": 200, "timestamp": "2023-11-09T15:47:37.341504", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: docker-compose

**Additional context**
According to the [Apache Documentation](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers), using the `ProxyPass` directive always sets the headers for `X-Forwarded-For`, `X-Forwarded-Host` and `X-Forwarded-Server`.

Configuration of Apache:

```
<VirtualHost 212.80.128.70:443>
        ServerName sec-login.example.com
        ServerAlias 212.80.135.139

        SSLEngine on
        SSLCertificateFile /etc/pki/tls/certs/somecert.pem
        SSLCertificateKeyFile /etc/pki/tls/private/somekeykey.pem

        ProxyPass "/" "https://212.80.135.139/" upgrade=websocket
        ProxyPassReverse "/" "https://212.80.135.139/"
        ProxyPreserveHost On
</VirtualHost>
```

**Comment by guedressel** [comment]
Same for me - running authentik 2023.10.3 on Kubernetes via official Helm chart: I see the nginx-ingress pod IP address als "Client IP" in the dashboard and in the logs.
Since the `PodCIDR` in my Kubernetes Cluster is not within the default list of trusted reverse proxies, I added the env variable to the Helm chart values:

![image](https://github.com/goauthentik/authentik/assets/1841616/c39b00d8-5464-4829-b6d5-f05f78baaf6e)
