### ISSUE TITLE
Two factor authentication not triggered with different accounts

### ISSUE THREAD

**Issue by hdlineage** [goauthentik/authentik#7525]
**Describe the bug**
Two factor authentication is promiscuous between accounts. If you log in one account successfully and try to log in another account, 2FA will not be triggered.

**To Reproduce**
1. Log in an account with 2FA enabled
2. Select yes to "stay signed in"
3. Log out
4. Log into another account with 2FA enabled
5. No 2FA is prompted

**Expected behavior**
2FA should be triggered if a different account is being logged in.

-   authentik version: 2023.10.3
-   Deployment: Docker

**Comment by BeryJu** [comment]
Please post the log messages that are logged while doing this
