### ISSUE TITLE
Cloudflare access - OpenID authentication with authentik

### ISSUE THREAD

**Issue by aheath70** [goauthentik/authentik#7526]
**Describe the bug**
Cloudflare Zero Trust OIDC is returning "Authentication Error - Failed to fetch user/group information from the identity provider"

It was working a week or so ago. I haven't changed the authetik provider, the application or the Cloudflare config. 

Looks very similar to https://github.com/goauthentik/authentik/issues/3422 which was closed with no explanation as to fix.

**To Reproduce**

1. Open web browser and enter a site that is protected by Cloudflare Zero Trust requiring authentik OIDC to access
2. Site redirects to Cloudflare.
3. Click on the button to use authentik to login
4. Cloudflare redirects to my auth web page.
5. Key in username, password and TOTP.
6. Redirects to Cloudflare with the following screen.

![image](https://github.com/goauthentik/authentik/assets/48014700/90dd4c7e-6b1a-4438-b8a3-e87b085f940f)

7. If I test it the app through authentik, it succeeds.
8. If I test the OIDC login method in Cloudflare (Zero Trust, Settings, Authentication, and click on "Test" it displays the following

![image](https://github.com/goauthentik/authentik/assets/48014700/b6268802-0fb9-4742-bd60-465d0f8e1337)

**Expected behavior**
Authentik shoudl redirect to end web site successfully.

**Screenshots**
See above

**Logs**
Docker log is showing the following event at the time.
```
INF auth_via=session event=/api/v3/flows/executor/default-provider-authorization-implicit-consent/?query=client_id%3DQPhjpLeqbz6xeJkeKFGzLLtPwyCEysvBwB6S8m1K%26code_challenge%3DFV6wGBwIAAX3sZPfF1jrAkl21TL2XXXahjilWD0UkLE%26code_challenge_method%3DS256%26domain%3DQPhjpLeqbz6xeJkeKFGzLLtPwyCEysvBwB6S8m1K%26redirect_uri%3Dhttps%253A%252F%252Fredacted.cloudflareaccess.com%252Fcdn-cgi%252Faccess%252Fcallback%26response_type%3Dcode%26state%3redacted>%25253D%26scope%3Dopenid%2Bemail%2Bprofile host=auth.redacted.online logger=authentik.asgi method=GET pid=141265 remote=172.22.0.1 request_id=2b93dc3e6b444b129f64a690907dbbf4 runtime=45 scheme=https status=200 timestamp=2023-11-12T12:46:41.869685 user=Andrew user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.3]
-   Deployment: docker-compose

**Additional context**
None

**Comment by aheath70** [comment]
Any update on this?

**Comment by rissson** [comment]
Did you enable "include claims in ID token" and have you selected a certificate in the provider?

**Comment by aheath70** [comment]
> Did you enable "include claims in ID token" and have you selected a certificate in the provider?

Yes and Yes. Also tried unchecking and re-checking "include claims in ID token" with the same resultant error.

**Comment by aheath70** [comment]
Managed to get it working again just now. I reverted the certificate away from my valid, LE cert back to the authentik self-signed certificate and it now works. Why would it be failing with my LE cert? I tried with both the certificates circled in red below, and both failed with the same error.

![image](https://github.com/goauthentik/authentik/assets/48014700/b7668418-fa29-4163-877e-df60c03feb52)

**Comment by rissson** [comment]
The only differency I see is that the two failing are EC and the one working is RSA. Perhaps Cloudflare only supports RSA-signed tokens?

**Comment by aheath70** [comment]
Indeed! I generated a new LE certificate using RSA instead of EC, and it works! My bad, I should have tested that before logging the call. Mystery solved, call closed. Thanks for your help, @rissson - much appreciated.

**Comment by rissson** [comment]
No worries, if anyone looks this up, I'm sure it'll help in their debugging

**Comment by admecoach** [comment]
Had similar issue which appears to be related to adding in Cloudflare an application rule for the Authentik instance added after this was Tested and Working as others have mentioned.  To correct, I remove my tight Allow policy and used Bypass in Cloudflare policies Cloudflare > Applications > Access > policies. I'm not sure of the best practice settings for this so any insight would be appreciated but I put a bypass based on my secure IP group and the OpenID Auth using Authentik started working again so for me it was NOT related to the Authentic self signed cert.

**Comment by Christopher-Hayes** [comment]
For what it's worth - **I updated my application's name/slug in Authentik and forgot to update the URLs in Cloudflare access**. This invalidated the Authentik Certificate URL that Cloudflare Access calls. That led to a variety of errors like the one above. Eventually, a `Failed to get oidc public keys. Got 404 undefined` helped me realize my mistake.

A cert issue could just mean the Certificate URL in Cloudflare Access is incorrect.
