### ISSUE TITLE
URI-like format for AUTHENTIK_SECRET_KEY results in 403 Forbidden

### ISSUE THREAD

**Issue by Yaren-IT** [goauthentik/authentik#7527]
**Describe the bug**

When performing a fresh install and attempting to set variables through Docker secrets, the expected behavior is to retrieve the actual secret key. However, the current behavior is that the retrieved value is a URI string instead of the actual key itself. This issue manifests even when adhering to the appropriate Docker secrets setup. This unexpected behavior is hindering the correct functioning of the application as it relies on obtaining the secret key during runtime.

**To Reproduce**

1. Set `AUTHENTICATION_SECRET_KEY` with URI-like `file://<name>`.
1. Set `AUTHENTIK_LOG_LEVEL` to trace, observe the error.
1. Observe that it does not resolve to the actual secret, instead bearing the string "file:///run/secrets/authentik_secret".
1. Outpost status not healthy in adminpanel.

**Expected behavior**
As the [documentation](https://goauthentik.io/docs/installation/configuration#about-authentik-configurations) points out: 
> All of these variables can be set to values, but you can also use a URI-like format to load values from other places:
> - `env://<name>` Loads the value from the environment variable <name>. Fallback can be optionally set like `env://<name>?<default>`
> - `file://<name>` Loads the value from the file `<name>`. Fallback can be optionally set like `file://<name>?<default>`

Doing so for the `AUTHENTIK_SECRET_KEY` does result in errors, like shown in the logs.
`Authorization":["Bearer file:///run/secrets/authentik_secret"],"`
However, dumping the config with `docker-compose run --rm worker dump_config`  shows the secret, and not the URI.

Setting the value of `AUTHENTIK_SECRET_KEY` to the stringcontent of the secret key file works fine.

**Logs**
```sh
authentik-server  | {"auth_via": "unauthenticated", "event": "/api/v3/outposts/instances/", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 52, "remote": "127.0.0.1", "request_id": "bec940a7acd74abc9a778044f844b91d", "runtime": 170, "scheme": "http", "status": 403, "timestamp": "2023-11-12T17:34:11.051882", "user": "", "user_agent": "goauthentik.io/outpost/2023.10.3"}
authentik-server  | {"error":"403 Forbidden","event":"Failed to fetch outpost configuration, retrying in 3 seconds","level":"error","logger":"authentik.outpost.ak-api-controller","timestamp":"2023-11-12T17:34:11Z"}
authentik-server  | {"cidr":"127.0.0.0/8","event":"Setting proxy headers","level":"trace","remoteAddr":"127.0.0.1","timestamp":"2023-11-12T17:34:14Z"}
authentik-server  | {"event":"tracing request to backend","headers":{"Accept":["application/json"],"Authorization":["Bearer file:///run/secrets/authentik_secret"],"Sentry-Trace":["904bcd50d632e0e8a91177ca3e64f36b-53cc5e86fbfd5097-0"],"User-Agent":["goauthentik.io/outpost/2023.10.3"]},"level":"trace","logger":"authentik.router","timestamp":"2023-11-12T17:34:14Z","url":"http://localhost:8000/api/v3/outposts/instances/"}
authentik-server  | {"auth_via": "unauthenticated", "event": "/api/v3/outposts/instances/", "host": "0.0.0.0:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 51, "remote": "127.0.0.1", "request_id": "38bd3b208fe74f0ca18d487ec0c87db8", "runtime": 112, "scheme": "http", "status": 403, "timestamp": "2023-11-12T17:34:14.180385", "user": "", "user_agent": "goauthentik.io/outpost/2023.10.3"}
authentik-server  | {"error":"403 Forbidden","event":"Failed to fetch outpost configuration, retrying in 3 seconds","level":"error","logger":"authentik.outpost.ak-api-controller","timestamp":"2023-11-12T17:34:14Z"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.3
-   Deployment: docker compose

**Additional context**

Prior to reporting this issue, I made a mistake on my end. I generated a secret key using `openssl rand -base64`, resulting in a too long string that caused the secret key file to span across two lines. This inadvertently led to errors with symptoms resembling those described inother issues in this project. Although the root cause of the current problem may be different, I wanted to provide this information for context in case it helps in understanding the issue better or if there are any potential correlations.

```json
{"error":"Get \"http://0.0.0.0:9000/api/v3/outposts/instances/\": net/http: invalid header field value for \"Authorization\"","event":"Failed to fetch outpost configuration, retrying in 3 s......"
```

**Comment by th37rose** [comment]
@BeryJu May I work on this issue?
