### ISSUE TITLE
Figuring out what has changed in versions programmically

### ISSUE THREAD

**Issue by samip5** [goauthentik/authentik#7547]
**Describe your question/**
I'm trying to figure out if there's currently a way to programmically go though API changes and generate an diff based on it to easily see if our integrations need modifications before upgrading.

**Relevant infos**
Currently running Authentik 2023.5.2 and would love to upgrade, but cannot until we can evaluate the API changes.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.2
-   Deployment: docker-compose

**Additional context**
Would love some diff of the changes that are parse-able easily.

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/compare/version-2023.5...main#diff-440e52d4b33e2fe6e8a94f84ec999e6f0b767d47d9b89fc1cc03ad4bbef55753 should help

**Comment by samip5** [comment]
> https://github.com/goauthentik/authentik/compare/version-2023.5...main#diff-440e52d4b33e2fe6e8a94f84ec999e6f0b767d47d9b89fc1cc03ad4bbef55753 should help

Unfortunately it doesn't really help, as I'm hoping there was basically something like https://goauthentik.io/docs/releases/2023.10#api-changes but in a more program friendly format? I'm interested in the diff between the API paths and/or their signatures that I can compare against.

I think the API changes get generated from a GH action to the changelog?

**Comment by BeryJu** [comment]
Yeah the changes are generated using https://github.com/OpenAPITools/openapi-diff which does have a `--json` flag
