### ISSUE TITLE
TOTP setup flow/stage gives weirdly formatted url.

### ISSUE THREAD

**Issue by Mrs-Feathers** [goauthentik/authentik#7564]
**Describe the bug**
TOTP setup flow/stage gives a QR which if your'e on mobile, obviously you cant scan your screen so you have to click "copy" and the link you get is a weirdly formatted link that isn't clickable or useful in any way other than to paste somewhere so you can edit out the actual code to past in authenticator. it would be nice if i could just straight up get the code when i click copy. it would make a lot of signups eaiser

**To Reproduce**

1. set up 2FA with authentik
2. create new user
3. 2FA required. choose TOTP
4. TOTP enrollment copy button gives weirdly formatted html safe non useful link. 

**Expected behavior**
TOTP would give just the TOTP code so i can copypasta to google authenticator

**Screenshots**

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.8.3](https://goauthentik.io/docs/releases/2023.8)
-   Deployment: docker compose

**Additional context**
I personally know how to get the code from the URL but a lot of my users aren't getting that so i'd like to just give them the code so i dont have to disable required 2FA

**Comment by BeryJu** [comment]
The URI which you get from the copy button is the same data that's in the QR code and should be understood by most TOTP applications afaik. Which TOTP App are you using?
