### ISSUE TITLE
Finer generation of "Background image" Link

### ISSUE THREAD

**Issue by mittler-works** [goauthentik/authentik#7595]
**Is your feature request related to a problem? Please describe.**

Yes, I bind-mount a Background Image into the authentik container, at `/web/dist/assets/images/custom_background.png`. Then, inside the flow, I set the path to `/static/dist/assets/images/custom_background.png`. The problem is, the auto-generated "Backgound image" link is still present and points to the default image attribution.

This is because here:

https://github.com/goauthentik/authentik/blob/99cecdb3cac6ca9ef7a9bc79bf9c34d2fa336ab6/web/src/flow/FlowExecutor.ts#L526-L535

the Background image link is generated based on the fact that url start with `/static`.

**Describe the solution you'd like**

I can think of an easy solution, that would be to check the whole path of the image to be `/static/dist/assets/images/flow_background.jpg` and not only to check if it starts with `/static`.

But this is still not optimal either, as there is still a problem: I could come up with the idea to mount a custom image on the default path `/static/dist/assets/images/flow_background.jpg` so I could have my default image without the need to change the background settings in every flow. With the proposed solution, this szenario would not work either.

**Describe alternatives you've considered**

I've found a quite easy workaround: it seems that if I prepend the scheme/host to the url, the check does not evaluate to true: e.g. `http://localhost:9000/static/dist/assets/images/flow_background.jpg` does not seem to trigger the check. However, this forces me to know the host in advance.

**Comment by tongkl1** [comment]
It would be great if a toggle can be added to turn off the attribution. Mounting an image to /web/dist/assets/images/flow_background.jpg has multiple benefits than setting the images in single flows, e.g. there's a hardcoded prefetch in the flow template pointing to that image even when a custom image is specified. Currently I have to use custom CSS to make the attribution not display

**Comment by BeryJu** [comment]
closed by #10318
