### ISSUE TITLE
Where to configure Radius shared secret?

### ISSUE THREAD

**Issue by tedstriker** [goauthentik/authentik#7598]
**Describe your question/**
Where can the Radius shared secret be configured? Will it be configured application or outpost wide?

**Relevant infos**
Authentik 2023.10.3 as well as the radius outpost.

**Screenshots**
nothing to screenshot

**Logs**
no logs, as this is a generic question

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2023.10.3]
-   Deployment: [docker-compose]

**Additional context**

**Comment by Gamechiefx** [comment]
I have the same question? The documentation is spotty on how the RADIUS output works and what must be configured on the console. I have been asked about this for 2 weeks across all of the Authentik social spaces (Github, Discord, Email) and have received no response.

Is this project dead/no longer maintained?

**Comment by BeryJu** [comment]
The radius shared secret is configured in the RADIUS provider, where a CIDR must also be configured, which determines which RADIUS provider/application is used for which request
