### ISSUE TITLE
Redis bad file format

### ISSUE THREAD

**Issue by rpoovey** [goauthentik/authentik#7643]
**Describe the bug**
About once a day Redis crashes and the whole system goes down. When I inspect the logs of the pod I am given:

```
Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
```

The pods are not moving from any node to the other, the filesystem appears to just corrupt. 

**To Reproduce**
Let system run

**Expected behavior**
Redis to not crash

**Logs**
```
 k logs authentik-redis-master-0
1:C 21 Nov 2023 01:37:29.026 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 21 Nov 2023 01:37:29.026 # Redis version=6.2.10, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 21 Nov 2023 01:37:29.026 # Configuration loaded
1:M 21 Nov 2023 01:37:29.029 * monotonic clock: POSIX clock_gettime
1:M 21 Nov 2023 01:37:29.031 * Running mode=standalone, port=6379.
1:M 21 Nov 2023 01:37:29.031 # Server initialized
1:M 21 Nov 2023 01:37:29.411 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.3 (corrected typo)
-   Deployment: helm
-  redis version: 6.2.10-debian-11-r13

**Additional context**
Storage backend: Longhorn
Happens on both arm64 and amd64 nodes.

**Comment by akhilesh2410** [comment]
I am also seeing same issue with Redis version=7.2.2
`root@edge-6a2c384257c5d9cf2c02d296e9fc2953:~# kubectl logs -n redis-system                       redis-replicas-1
1:C 24 Dec 2023 15:35:01.296 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 24 Dec 2023 15:35:01.296 * Redis version=7.2.2, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 24 Dec 2023 15:35:01.296 * Configuration loaded
1:S 24 Dec 2023 15:35:01.297 * monotonic clock: POSIX clock_gettime
1:S 24 Dec 2023 15:35:01.298 * Running mode=standalone, port=6379.
1:S 24 Dec 2023 15:35:01.299 * Server initialized
1:S 24 Dec 2023 15:35:01.299 * Reading RDB base file on AOF loading...
1:S 24 Dec 2023 15:35:01.299 * Loading RDB produced by version 7.2.2
1:S 24 Dec 2023 15:35:01.299 * RDB age 164849 seconds
1:S 24 Dec 2023 15:35:01.299 * RDB memory usage when created 2.74 Mb
1:S 24 Dec 2023 15:35:01.299 * RDB is base AOF
1:S 24 Dec 2023 15:35:01.318 * Done loading RDB, keys loaded: 8889, keys expired: 0.
1:S 24 Dec 2023 15:35:01.318 * DB loaded from base file appendonly.aof.5.base.rdb: 0.019 seconds
1:S 24 Dec 2023 15:35:01.354 * DB loaded from incr file appendonly.aof.5.incr.aof: 0.037 seconds
1:S 24 Dec 2023 15:35:01.354 * DB loaded from append only file: 0.055 seconds
1:S 24 Dec 2023 15:35:01.354 # Can't open the append-only file appendonly.aof.5.incr.aof: Read-only file system`

**Comment by rpoovey** [comment]
I still have this error happening as well. I wonder if the issue shouldn't be opened with Bitnami instead. Doesn't seem these issues gets much triage.

**Comment by rpoovey** [comment]
I disagree with this. I delete the Redis pv/pvc about once a week because of this error.

**Comment by rissson** [comment]
Then it's an issue with your storage backend. We don't have any control over how Redis stores data on disk.
