### ISSUE TITLE
Admin users can not delete user mfa devices anymore

### ISSUE THREAD

**Issue by tograss** [goauthentik/authentik#7659]
**Describe the bug**
Before the 2023.10.3 update admin users could delete user mfa devices. Since the 10.3 updates only a table listing the user devices is shown but the devices can not be deleted,
**Expected behavior**
Admins should be able  to delete user mfa devices. 
Since users constantly loose there mfa devices it is quite important to have an easy way resetting the devices.
**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.3
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
Which version did you upgrade from? Looking through the code I can't find a version where this was possible, despite me also remembering that it used to be possible. Regardless, this will be fixed in 2023.10.4
