### ISSUE TITLE
Redirect user if they only have a social connection and no password

### ISSUE THREAD

**Issue by pingiun** [goauthentik/authentik#7697]
**Describe your question/**
We mainly use a Google Workspace login at work, but I would still like to have the email field for when we create accounts for people that aren't in our google workspace. Is it possible to redirect people to the Google Auth page when they have filled in their email address? The email address could be used to check whether the account has a password set or not.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.4
-   Deployment: docker via nixos configuration

**Comment by BeryJu** [comment]
This can be done with the Source stage: https://docs.goauthentik.io/docs/flow/stages/source/

You'd have to create a policy that checks the email domain/checks for an existing user and if no existing user is found/the existing user does not have a source connection, `return False` in the policy to skip the source stage and resume the flow
