### ISSUE TITLE
AUTHENTIK_AUTHENTIK__BRANDING__TITLE Configuration Option doesn't work

### ISSUE THREAD

**Issue by BhenchodGroup** [goauthentik/authentik#770]
AUTHENTIK_AUTHENTIK__BRANDING__TITLE does not modify site title after rebuild.

**Comment by BeryJu** [comment]
@BhenchodGroup I've fixed the document title not being set based on the config, is there any other place you'd expect it to change?

**Comment by BhenchodGroup** [comment]
That would be the only place I'd expect it to change.

**Comment by BeryJu** [comment]
Sick, will be fixed in the next minor release.
