### ISSUE TITLE
Authentication issue which makes Authentic unusable

### ISSUE THREAD

**Issue by tugdualenligne** [goauthentik/authentik#7705]
**Describe the bug**
Trying to use Authentic in combination with Traefik. I have about 40 other containers but this one resist me...
Issue is:  I set up everything, log into Authentik and then I can consult one page in Authentik and it always keep coming back to the default login page. Further when creating a user, it says "Authentication credentials were not provided."
And some elements don't show up in pages

Please help whether it is a bug of misconfiguration. I spent days on this to try every possible change in my docker-compose

**To Reproduce**
Indicated above

**Expected behavior**
N/A

**Logs**
warning error=context canceled event=failed to proxy to backend logger=authentik.router
 and 

action=model_updated auth_via=unauthenticated client_ip=192.168.4.19 context={"http_request":{"args":{"next":"/if/admin/#/outpost/outposts"},"method":"POST","path":"/api/v3/flows/executor/default-authentication-flow/"},"model":{"app":"authentik_core","model_name":"user","name":"authentik Default Admin","pk":6}} event=Created Event host=auth.domain.fr logger=authentik.events.models pid=23 request_id=12c333ea78164c45a10f4b0738985166 timestamp=2023-11-24T20:02:50.855689 user={"email":"","pk":1,"username":"AnonymousUser"}

May be other lines, I'm not sure what to look for

**Version and Deployment (please complete the following information):**
-   authentik version: 2023.10.4
-   Deployment: docker-compose

My docker compose :
version: "3.4"

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database-authentik:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - stack.env
    networks:
      - traefik_proxy
      
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-authentik:/data
    networks:
      - traefik_proxy

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.10.4}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql # ${AUTHENTIK_POSTGRESQL__HOST}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_HOST: https://auth.domain.fr/
      UID: 1000
      GID: 100
    volumes:
      - /Tech/Authentik/media:/media
      - /Tech/Authentik/custom-templates:/templates
    env_file:
      - stack.env
    ports: 
      - "9005:9005"
      - "9443:9443"
    labels:
      traefik.enable: true
      traefik.port: 9005
      traefik.http.routers.authentik.rule: Host(`auth.domain.fr`)
      traefik.http.routers.authentik.entryPoints: https
      traefik.http.routers.authentik.tls: true
      traefik.http.routers.authentik.tls.certresolver: domain
      traefik.http.routers.authentik-outpost.rule: HostRegexp(`{subdomain:[A-Za-z0-9](?:[A-Za-z0-9\-]{0,61}[A-Za-z0-9])?}.domain.fr`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.services.authentik.loadbalancer.server.port: 9005
      traefik.http.middlewares.authentik.forwardauth.address: http://server:9005/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
      diun.enable: true
    depends_on:
      - postgresql
      - redis
    networks:
      - traefik_proxy

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.10.4}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY} # ajoût 23/11/2023
      UID: 1000
      GID: 100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Tech/Authentik/media:/media
      - /Tech/Authentik/certs:/certs
      - /Tech/Authentik/custom-templates:/templates
    env_file:
      - stack.env
    depends_on:
      - postgresql
      - redis
    networks:
      - traefik_proxy

volumes:
  database-authentik: #modif Josse
    driver: local
  redis-authentik: #modif Josse
    driver: local

networks:
  authentik:
    external: false
    name: authentik
  traefik_proxy:
    external: true
    name: traefik_proxy

**Comment by tugdualenligne** [comment]
It seemed to work normally when I activated a separate, internal, network to interconnect the Authentik containers
(followed internal network conclusion given here https://github.com/goauthentik/authentik/issues/4539

But I after restart of the docker-compose, it doesn't work at all. Drives me crazy

**Comment by TrainDoctor** [comment]
I am also experiencing this issue actively. I am using docker compose with the latest docker-compose template as of time of writing and nothing I seem to do including pulling new images and clearing out the volumes seems to change any aspect of the issue for me.

**Comment by cvietor** [comment]
same exact issue here. tried first with traefik and then without to exclude issues with reverse proxy configuration.
using docker compose version from main branch (AUTHENTIK_TAG:-2024.2.1)

**Comment by tugdualenligne** [comment]
I think I have found the solution. I share here my working docker-compose, if it can help someone else.
I reckon adding my separate traefik network helped fixed the issue I had with the worker which was not connected (and that might have been the problem with Authentic being down every so often
`version: "3.4"

services:
  postgresql:
    image: docker.io/library/postgres:14-alpine
    container_name: authentik-postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database-authentik:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - stack.env
    networks:
      - authentik
      
  redis:
    image: docker.io/library/redis:alpine
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-authentik:/data
    networks:
      - authentik

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG} #:-2023.10.5
    container_name: authentik-server
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql # ${AUTHENTIK_POSTGRESQL__HOST}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      DOMAIN: ${DOMAIN}
      HOST_DOMAIN: ${HOST_DOMAIN}
      AUTHENTIK_HOST: https://${HOST_DOMAIN}
      UID: 1000
      GID: 100
    volumes:
      - authentik-media:/media
      - authentik-templates:/templates
    env_file:
      - stack.env
    expose:
      - 9005
      - 9443
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.authentik.rule: Host(`$HOST_DOMAIN`)
      traefik.http.routers.authentik.entryPoints: https # essai sans "s"
      traefik.http.routers.authentik.tls: true
      traefik.http.routers.authentik.tls.certresolver: du-plessis
      ## Individual Application forwardAuth regex (catch any subdomain using individual application forwardAuth)  
      traefik.http.routers.authentik-outpost.rule: HostRegexp(`{subdomain:[A-Za-z0-9](?:[A-Za-z0-9\-]{0,61}[A-Za-z0-9])?}.$DOMAIN`) && PathPrefix(`/outpost.goauthentik.io/`)
      ## HTTP Services
      traefik.http.middlewares.authentik.forwardauth.address: http://server/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
      diun.enable: true
    depends_on:
      - postgresql
      - redis
    networks:
      - traefik_proxy
      - authentik

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG} #:-latest
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      UID: 1000
      GID: 100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-media:/media
      - authentik-certs:/certs
      - authentik-templates:/templates
    env_file:
      - stack.env
    depends_on:
      - postgresql
      - redis
    networks:
      - authentik
      - traefik_proxy

volumes:
  database-authentik:
    driver: local
  redis-authentik:
    driver: local
  authentik-media:
    driver: local
  authentik-certs:
    driver: local
  authentik-templates:
    driver: local
    
networks:
  authentik:
    internal: true
    name: authentik
  traefik_proxy:
    external: true
    name: traefik_proxy`

**Comment by cvietor** [comment]
I figured that my problem could have been a second "redis" container on the same network as stated [here](https://github.com/goauthentik/authentik/issues/4539#issuecomment-1681680420)
 Renaming the container solved the issue. So no authentik problem but rather a "me" problem

**Comment by tugdualenligne** [comment]
I changed my set-up completely and Authentik now works great:
- I created a separate LXC container which host Authentik through Docker 
- Traefik point to Authentik from another VM
- 
this enables to work smoothly and as expected. I haven’t found the original issue, but at least it works fine, and, I have to say, the Oauth2, SAML, and WebAuthn are great features

**Comment by Cecilius** [comment]
I can confirm I had same issue and it looks like it was caused by two redis servers on same network (even with different name and also implicitly stated correct name in env variables). What help me was to move redis to internal network of stack. What I see - a lot of people on internet have same issues and not a lot of correct answers exist. It should be part of documentation as tip for good practice.

**Comment by mich2k** [comment]
> I can confirm I had same issue and it looks like it was caused by two redis servers on same network (even with different name and also implicitly stated correct name in env variables). What help me was to move redis to internal network of stack. What I see - a lot of people on internet have same issues and not a lot of correct answers exist. It should be part of documentation as tip for good practice.

I just faced the same exact issue, I had a custom docketnet,  two Redis containers with different hostnames and authentik had a lot of issues with finding the defined Redis container

At first I had some AUTH issues since the first (wrong) Redis container did not have --requirepass in its post args
meanwhile the second (correct authentik's) Redis had require pass and yet authentik was complaining he was trying to auth in a container that was not configured with authentication

Eventually I did a reset of both authentik and the worker, authentik did not manage to find the worker and kept kicking me out, I managed to find an error string log somewhere in the dashboard that took me here

Wrapper the other (wrong) Redis container in a net, removed from the main net and now is working great

This behaviour should be reported in the documentation, even because the average user may not notice that there is no Redis at all

**Comment by KevinNaMo** [comment]
> I can confirm I had same issue and it looks like it was caused by two redis servers on same network (even with different name and also implicitly stated correct name in env variables). What help me was to move redis to internal network of stack. What I see - a lot of people on internet have same issues and not a lot of correct answers exist. It should be part of documentation as tip for good practice.

I ran into the same issue, and isolating the stack’s Redis instance on its own Docker network resolved it for me as well. I created a dedicated network for the Authentik stack, and after attaching all relevant containers to it, the problem went away
