### ISSUE TITLE
Generate an initial API token

### ISSUE THREAD

**Issue by cyclingwithelephants** [goauthentik/authentik#7707]
**Is your feature request related to a problem? Please describe.**
I am attempting to gitops my authentik configuration using the Terraform provider. Unfortunately it seems that I need to pop into the UI and generate an API token before I can run Terraform. This prevents me from fully automating the install process end to end

**Describe the solution you'd like**
It would be wonderful to be able to specify some initial API token (`AUTHENTIK_INITIAL_API_TOKEN=<token>`) that can be used to bootstrap programatic configuration without human intervention. This would be backwards compatible since we can simply not create the API token if one is not specified. Authentik could also have a flag like `AUTHENTIK_GENERATE_INITIAL_API_TOKEN=true` and write it back to a k8s secret

**Describe alternatives you've considered**
I've looked in the docs for anything similar, including programatic ways to generate that initial API token with no success

**Comment by jdmarble** [comment]
Does [`AUTHENTIK_BOOTSTRAP_TOKEN`](https://goauthentik.io/docs/installation/automated-install#authentik_bootstrap_token) do what you want?

**Comment by cyclingwithelephants** [comment]
It does 🤦 

Thank you very much
