### ISSUE TITLE
Overriding trusted proxy CIDRs does not work

### ISSUE THREAD

**Issue by joachimtingvold** [goauthentik/authentik#7712]
**Describe the bug**
Overriding trusted proxy CIDRs via the configuration flag `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS` does not work.

**To Reproduce**

1. Configure trusted proxy CIDRs in `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS` with the syntax `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS='["127.0.0.0/8","::1/128"]'`.
2. Restart Authentik
3. Configured trusted proxies does not work (i.e. Authentik does not trust headers from the configured CIDRs).

**Expected behavior**
Authentik should configure it's trusted proxy CIDR list based on the configured values in `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS`.

**Screenshots**
See logs/info in #6749.

**Logs**
See logs/info in #6749.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.2 + 2023.10.4
-   Deployment: docker-compose

**Additional context**
This started out as a question/discussion in #6749, but conclusion seems to be that it's a bug (i.e. Authentik Go config loader does not JSON parse the config file). Current workaround (described in #6749) is to mount a custom `defaults.yaml` file with the CIDRs added (which is confirmed to be working).

**Comment by bdallen** [comment]
+1 Same issue here, using the default.yml workaround on this one.

**Comment by Samppady** [comment]
+1 Same issue here, using the default.yml workaround on this one.
