### ISSUE TITLE
LDAP Outpost seems to only support single provider

### ISSUE THREAD

**Issue by tedstriker** [goauthentik/authentik#7714]
**Describe the bug**
It seems that LDAP outpost can only serve a single provider. Maybe somethings odd in the configuration, but I couldn't find information about that anywhere.

## Setup
Create two identical configured applications A and B, their LDAP providers A and B, as well as groups and service accounts respectively, which will be used in the step-by-step setup

1. Setup internal LDAP outpost
1. LDAP flows have been set up like described on the [homepage](https://goauthentik.io/docs/providers/ldap/generic_setup)
1. Create a group which is allowed to perform LDAP searches  [A|B]. e.g. `Directory Clients`
1. Create groups for access to the applications [A|B]. e.g. `grp-app-[A|B]-users`
1. Create a service-account for each application. e.g.`service-user-app-[A|B]`
1. Assign the service users to the group `Directory Clients`
1. Create LDAP provider [A|B] e.g. `LDAP-provider-[A|B]`
    1. select `LDAP-authentication-flow` as bind flow
    1. select `Directory Clients` as search group
    1. bind mode: direct binding
    1. search mode: direct querying
    1. base DN: DC=example,DC=com
    1. certificate: select certificate which matches auth server name, e.g. for `auth.example.com`
    1. TLS server name: auth.example.com
    1. leave the rest unchanged - I guess the certificate steps (6 & 7) can be omitted
1. Create application the [A|B] and assign it's respective provider to it. e.g. `App-[A|B]`
1. Add a group binding to application `App-[A|B]` for group  `grp-app-[A|B]-users` to allow access to the group members.

Last steps are found in **to Reproduce**

**To Reproduce**
1. Assign both applications to the an LDAP outpost.
2. Try to bind `service-user-app-A` with an LDAP client (I used Apache Directory Studio)
3. Connection to LDAP server could be established successfully
2. Try to bind `service-user-app-B` with an LDAP client
4. Receive an `LDAP result code 50 - insufficientAccessRights` error
5. Now remove application A from the LDAP outpost.
6. Try to bind `service-user-app-B` again.
7. `service-user-app-B` could successfully be connected.

It seems, that only the topmost selected application in the LDAP outpost can be used for connections.

**Expected behavior**
I'd expect that multiple assigned applications - all with their own service accounts - can be used to query the LDAP directory to authenticate users in LDAP-based applications

**Screenshots**
nothing besides an error message

**Logs**
From server:
`INF auth_via=unauthenticated backend=authentik.core.auth.InbuiltBackend event=Successful authentication host=auth.example.com logger=authentik.stages.password.stage pid=81130 request_id=f76882966bd14623b6b16e21e5c2f021 timestamp=2023-11-27T12:22:08.484310 user=service-user-app-B`
Authentication itself seems to work properly (no credential errors)

**Version and Deployment (please complete the following information):**
-   authentik version: [2021.10.4]
-   Deployment: [docker-compose]

**Additional context**

**Comment by BeryJu** [comment]
I think maybe either the documentation or the forms to create LDAP providers (or both) doesn't explain this clearly, the different providers must have different Base DNs as routing to different providers is done based off of the base DN

**Comment by tedstriker** [comment]
The documentation didn't mention this necessity yet.
With a made up OU for each application providers can effectively differentiated.
Thanks for the quick help.
