### ISSUE TITLE
Support custom URI scheme redirection

### ISSUE THREAD

**Issue by adepto-io** [goauthentik/authentik#772]
**Is your feature request related to a problem? Please describe.**
Setting a custom redirect URI scheme in the provider's settings throws a DisallowedRedirect exception during authentication with the following message: 

_"Unsafe redirect to URL with protocol 'com.example.app'"_

**Describe the solution you'd like**
Support  [Private-Use URI Scheme Redirection](https://tools.ietf.org/html/bcp212#section-7.1) that is commonly used by mobile apps.

**Describe alternatives you've considered**
I haven't, any suggestions?

**Comment by BeryJu** [comment]
Sounds good, do you happen to have a stacktrace where that error is thrown?

The only interesting thing about this could be validating the destination URI, since IIRC the final redirect is done by the FlowExecutor, and not the OAuth Provider

**Comment by adepto-io** [comment]
Would the validation of the redirect URI with a custom scheme be any different compared to the HTTPS scheme?

> Traceback (most recent call last):
> File "/authentik/flows/views.py", line 152, in get
> stage_response = self.current_stage_view.get(request, *args, **kwargs)
> File "/authentik/providers/oauth2/views/authorize.py", line 264, in get
> return redirect(self.create_response_uri())
> File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 41, in redirect
> return redirect_class(resolve_url(to, *args, **kwargs))
> File "/usr/local/lib/python3.9/site-packages/django/http/response.py", line 504, in __init__
> raise DisallowedRedirect("Unsafe redirect to URL with protocol %s" % parsed.scheme)
> django.core.exceptions.DisallowedRedirect: Unsafe redirect to URL with protocol 'com.example.app'

**Comment by BeryJu** [comment]
The only difference is that for the oauth2 provider, redirect URIs are validated against the list, and for a normal logins, only relative URIs are allowed.

But since the redirect comes from the `OAuthFulfillmentStage` and not the flow executor, this is very easy to add.

**Comment by Sander0542** [comment]
This seems to be broken again starting with 2024.2.0

![image](https://github.com/goauthentik/authentik/assets/11409610/3fac32be-1022-4f55-9823-2b0b62bc768a)
