### ISSUE TITLE
Provides documentation to intergrate Traefik with non Oauth/SAML2 like services.

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#774]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Provides docs to intergrate Authentik with traefik behind non oauth/saml services.

**Describe alternatives you've considered**
The only doc I can find is Nginx, traefik is not avaiable

**Additional context**

See [here](https://github.com/authelia/authelia/blob/master/docs/deployment/supported-proxies/traefik2.x.md) for refference. Authelia is an example for this.

**Comment by BeryJu** [comment]
closed by https://github.com/goauthentik/authentik/commit/2a409215d3005f0a0efc3313e23957a118b2d05f
