### ISSUE TITLE
Broken styles when Authentik theme is set to Light but OS theme is Dark

### ISSUE THREAD

**Issue by corvis** [goauthentik/authentik#7754]
**Describe the bug**
When user has dark theme preference of a Operation system value AND authentik is configured to use Light theme (e.g. via tenant setting) the dark theme will be partially applied together with light theme.

**To Reproduce**

1. Make sure you have dark theme configured in your OS.
2. In Authentik tenant settings (Admin UI -> System -> Tenants) set theme to Light. See config example below:
![image](https://github.com/goauthentik/authentik/assets/5593615/bd89e0ac-5011-4cac-8f77-8e144af449a0)

4. Navigate to the admin panel or user interface. You will see the mixture of the light and dark themes, so it is mostly light but icons and headers are white on a light background.

**Expected behavior**
Expected to see proper light theme. 

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/5593615/84f7f02d-c254-4e46-8a3a-221b2b30d784)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.4
-   Deployment: docker-compose, helm

**Additional context**
I believe the problem is that it loads `theme-dark.css` with `media="(prefers-color-scheme: dark)"` regardless of the theme selected in authentik. So if user prefers dark theme on OS level the file will be loaded no matter want. An file itself doesn't have any selectors checking actual theme attribute. Possible solution might be to add theme attribute on the `<html>` tag level and then wrap all selector in `theme-dark.css` into `[theme=dark]`.

**Comment by adigh** [comment]
I'm facing the same issue. Is there an eta for the fix of this bug?

**Comment by corvis** [comment]
@adigh if this helps - my temporary workaround was to remove the following line 
```html
<link rel="stylesheet" type="text/css" href="{% static 'dist/theme-dark.css' %}" media="(prefers-color-scheme: dark)">
```
from `authentik/core/templates/base/skeleton.html`.

In combination with the theme set to `light` explicitly in settings this disables dark theme completely.
