### ISSUE TITLE
Any advice on LDAP with MFA?

### ISSUE THREAD

**Issue by HsunGong** [goauthentik/authentik#7775]
**Describe the bug**

I've setup following the recipe
0. https://goauthentik.io/docs/providers/ldap/
1. setup LDAP: https://www.youtube.com/watch?v=RtPKMMKRT_E
2. setup MFA: https://github.com/goauthentik/authentik/issues/6291

However, the LDAP does not require MFA code to login (I setup static/TOTP for ldapservice).

**To Reproduce**

<img width="351" alt="image" src="https://github.com/goauthentik/authentik/assets/32933986/4f7da789-4621-4e91-b6df-5c94dfbddb90">

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2023.8]
-   Deployment: [docker-compose]

**Comment by HsunGong** [comment]
Help wanted

**Comment by rissson** [comment]
We do provide an example flow that checks MFA here: https://docs.goauthentik.io/docs/flow/examples/flows#two-factor-login
Be sure to check notes about MFA in LDAP: https://docs.goauthentik.io/docs/providers/ldap/#bind-modes
