### ISSUE TITLE
LDAP Property Mapping does not work

### ISSUE THREAD

**Issue by HsunGong** [goauthentik/authentik#7776]
**Describe the bug**

LDAP Property Mapping does not work.

Follow [blueprint/examples/](https://github.com/goauthentik/authentik/blob/893b8376cff66a90880b550c65d07b9354150cd7/blueprints/example/sources-google-ldap-mappings.yaml) but no exclude properties exists.

The construct recipe follows https://www.youtube.com/watch?v=RtPKMMKRT_E and https://goauthentik.io/docs/providers/ldap/

**Comment by tograss** [comment]
Hi HsunGong, can you describe a bit more what you are trying to archive ?
The video you posted describes creating a ldap outpost, which provides the authentik users via ldap, with the attributes the users have in authentik. 
The ldap property mappings are used (as far as I know) when you pull your authentik users from an existing ldap server, via the federation feature. 
So at least for me it is unclear what you are trying to do.
