### ISSUE TITLE
Not synced yet. Freeipa

### ISSUE THREAD

**Issue by kocik799** [goauthentik/authentik#7838]
Hello, I'm trying to configure freeipa ldap, but the connection attempt is not happening
![изображение](https://github.com/goauthentik/authentik/assets/36620182/3fd57cf4-35aa-4a6e-93f2-2038a6841e37)

**Logs**
docker-compose run --rm worker ldap_sync freeipa-srv01
`99@auth:~/docker/auth$ docker compose run --rm worker ldap_sync  freeipa-srv01
[+] Creating 2/0
 ✔ Container auth-redis-1       Running                                                                                                                  0.0s
 ✔ Container auth-postgresql-1  Running                                                                                                                  0.0s
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201109.6436687, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201109.6448781, "count": 15}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.8309448, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.8327198, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.8338895, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.836353, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.8401737, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.843984, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.84638, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.847528, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.8486278, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.852321, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.8603413, "path": "authentik.blueprints.settings"}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1702201114.8607113, "version": "2023.10.4"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1702201114.8626175}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201114.8632908, "path": "authentik.enterprise.settings"}
{"event": "Loaded GeoIP database", "last_write": 1700595417.0, "level": "info", "logger": "authentik.events.geo", "pid": 7, "timestamp": "2023-12-10T09:38:36.687159"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 7, "task_id": "c867dc62313a410397da1b0222d28f06", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2023-12-10T09:38:38.543787"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 7, "task_id": "f245ed31a1074ee683d67a32f548cdf3", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2023-12-10T09:38:38.554315"}
{"app_name": "authentik.stages.authenticator", "event": "Could not import app's URLs", "exc": "ModuleNotFoundError(\"No module named 'authentik.stages.authenticator.urls'\")", "level": "warning", "logger": "authentik.api.v3.urls", "pid": 7, "timestamp": "2023-12-10T09:38:39.103196"}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ak-root/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/management/commands/ldap_sync.py", line 28, in handle
    + ldap_sync_paginator(source, GroupLDAPSynchronizer)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/tasks.py", line 78, in ldap_sync_paginator
    for page in sync_inst.get_objects():
  File "/authentik/sources/ldap/sync/base.py", line 102, in search_paginator
    self._connection.search(
  File "/ak-root/venv/lib/python3.11/site-packages/ldap3/core/connection.py", line 838, in search
    request = search_operation(search_base,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/ldap3/operation/search.py", line 371, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/ldap3/operation/search.py", line 205, in parse_filter
    current_node.append(evaluate_match(search_filter[start_pos:end_pos], schema, auto_escape, auto_encode, validator, check_names))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/ldap3/operation/search.py", line 165, in evaluate_match
    assertion = {'attr': left_part, 'value': validate_assertion_value(schema, left_part, right_part, auto_escape, auto_encode, validator, check_names)}
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/ldap3/protocol/convert.py", line 159, in validate_assertion_value
    value = validate_attribute_value(schema, name, value, auto_encode, validator=validator, check_names=check_names)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.11/site-packages/ldap3/protocol/convert.py", line 173, in validate_attribute_value
    raise LDAPObjectClassError('invalid class in objectClass attribute: ' + str(value))
ldap3.core.exceptions.LDAPObjectClassError: invalid class in objectClass attribute: group
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit`

`799@auth:~/docker/auth$ docker compose run --rm worker ldap_check_connection freeipa-srv01
[+] Creating 2/0
 ✔ Container auth-postgresql-1  Running                                                                                                                  0.0s
 ✔ Container auth-redis-1       Running                                                                                                                  0.0s
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201743.9828544, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201743.9845645, "count": 15}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.644672, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.6466668, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.6480541, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.6507516, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.6547065, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.6587505, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.661208, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.6623907, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.663575, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.6674652, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.6758163, "path": "authentik.blueprints.settings"}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1702201748.6761017, "version": "2023.10.4"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1702201748.6783144}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1702201748.679091, "path": "authentik.enterprise.settings"}
{"event": "Loaded GeoIP database", "last_write": 1700595417.0, "level": "info", "logger": "authentik.events.geo", "pid": 7, "timestamp": "2023-12-10T09:49:10.483496"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 7, "task_id": "bb3b8deb20f44aa7a4687cba802b5756", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2023-12-10T09:49:13.327425"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 7, "task_id": "4b66636917e24bf18e25aec1faf5d100", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2023-12-10T09:49:13.340372"}
Unknown command: 'ldap_check_connection'
Type 'manage.py help' for usage.`

-   authentik version:  2023.10.4
-   Deployment: docker compose

**Comment by boesr** [comment]
I can relate to that bug. Strangely after a while clicking in the ui 

`docker compose run --rm worker ldap_sync  slug` start to sync. But I cannot see the "normal" workers starting the sync process

**Comment by kocik799** [comment]
> Я могу понять эту ошибку. Как ни странно, через некоторое время щелчок в пользовательском интерфейсе
> 
> `docker compose run --rm worker ldap_sync slug`начать синхронизировать. Но я не вижу, чтобы «обычные» работники запускали процесс синхронизации.

`799@auth:~/docker/auth$ docker compose run --rm worker ldap_sync  slug
[+] Creating 2/0
 ✔ Container auth-postgresql-1  Running                                                                                                                  0.0s
 ✔ Container auth-redis-1       Running                                                                                                                  0.0s
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187090.6773486, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187090.6782765, "count": 15}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.4787962, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.4804869, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.4816377, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.4840171, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.4880154, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.4922729, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.4947984, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.495916, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.496998, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.5007298, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.5093477, "path": "authentik.blueprints.settings"}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1703187095.5095966, "version": "2023.10.5"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1703187095.5117733}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1703187095.5124733, "path": "authentik.enterprise.settings"}
{"event": "Loaded GeoIP database", "last_write": 1703165606.0, "level": "info", "logger": "authentik.events.geo", "pid": 6, "timestamp": "2023-12-21T19:31:37.397320"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 6, "task_id": "7be85ea52ae54d2d925fb5fe35925414", "task_name": "authentik.blueprints.v1.tasks.blueprints_discovery", "timestamp": "2023-12-21T19:31:40.089078"}
{"event": "Task published", "level": "info", "logger": "authentik.root.celery", "pid": 6, "task_id": "e8922492d4554f9b8226570e81958ce9", "task_name": "authentik.blueprints.v1.tasks.clear_failed_blueprints", "timestamp": "2023-12-21T19:31:40.092365"}
{"event": "Source does not exist", "level": "warning", "logger": "authentik.sources.ldap.management.commands.ldap_sync", "pid": 6, "slug": "slug", "timestamp": "2023-12-21T19:31:41.307561"}
`
