### ISSUE TITLE
Crowdfund Security Audit

### ISSUE THREAD

**Issue by typkrft** [goauthentik/authentik#7875]
**Describe your question/**
I know some people, particularly in the corporate and selfhosted space who won't use it for production because of a lack of security audits. As someone who is not a security expert, I also tend to side with very "corporate" conventional logic when I implement software into the servers and networks I administer. I'd love to use Authentik. I think the project is popular enough to try and crowd fund either completely or at least supplement a security audit. Consider making an a transparent fundraising account so that we can make this happen as well as getting some estimates on the amount needing to be funded. 

**Additional context**
All the best! Happy Holidays.

**Comment by BeryJu** [comment]
We've actually done a security audit earlier this year: https://goauthentik.io/docs/security/2023-06-cure53

Our plan is to do these audits on a semi-regular basis in addition with our own internal red-teaming effort, and ideally also by different companies to get different people's viewpoints

**Comment by typkrft** [comment]
This is amazing news! I guess I just need to spread the word and familiarize myself with your docs a little more. Happy Holidays!
