### ISSUE TITLE
SCIM: Sync not run yet. Atlassian Access

### ISSUE THREAD

**Issue by segro21** [goauthentik/authentik#7884]
**Describe your question/**
I try to setup SAML (working) and SCIM to Atlassian Cloud (vi Atalssian Access). 
I copied the generated URL (https://api.atlassian.com/scim/directory/8dda6d0f-.....) + API key to authentik under provider -> SCIM and saved it. When I press "Run sync again" nothing happens and status tells me: Sync not run yet.

shouldt this work? 

**Relevant infos**
https://support.atlassian.com/provisioning-users/docs/configure-user-provisioning-with-an-identity-provider/

**Version and Deployment (please complete the following information):**

-   authentik version: [2023.10.4](https://goauthentik.io/docs/releases/2023.10)
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
The were some bugs with regards to scheduled tasks and locking, does this issue still occur?

**Comment by Loapu** [comment]
For me, it does not. 
Here's the error: 
https://pastebin.com/3QwmQ2e8
