### ISSUE TITLE
Authentik passing the authentication credential to my service that im logging into

### ISSUE THREAD

**Issue by wedowhateverwewant** [goauthentik/authentik#7886]
Everything works fine, my issue when I try to login to a service that is protected by authentik SSO, the authentik login works but then when it gets to my services login screen authentik passes the SSO  credntials to the service and it breaks things, anyway I can disable this ?

**Comment by BeryJu** [comment]
Not entirely sure what the exact issue is, but https://docs.goauthentik.io/docs/providers/proxy/header_authentication#send-http-basic-authentication disabling the option `Send HTTP-Basic Authentication` should fix the issue.
