### ISSUE TITLE
"stay signed in offset" can not be reset to 0

### ISSUE THREAD

**Issue by cfoellmann** [goauthentik/authentik#7891]
I can not set the "stay signed in offset" = 0

**To Reproduce**

1. Go to `if/admin/#/flow/stages`
2. Click on edit for `default-authentication-login`
3. try to set "stay signed in offset" to `0`
4. onSave: `0 is not in the correct format of 'hours=3;minutes=1'.`
5. try: `hours=0;minutes=0` -> dialog for staying logged is still in the login flow

**Expected behavior**
Setting `stay signed in offset` = 0 should be legit and deactivate the dialog in the login flow

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.4
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
you should be able to set it to `seconds=0` which should have the same outcome

**Comment by cfoellmann** [comment]
I tried but it makes no difference.
The dialog still pops up

**Comment by cfoellmann** [comment]
Correction: It works for our federated AD users but for the AzureAD/EntraID users it still pops up. Must be a different stage, right?

**Comment by madduck** [comment]
Can this issue please be reopened, as the problem/bug persists?
