### ISSUE TITLE
Unable to retrieve JWT token with OIDC

### ISSUE THREAD

**Issue by j007bond007** [goauthentik/authentik#7907]
**Describe the bug**
After installing Netbird, I was able to successfully use OIDC as per their configuration document (after selecting a signing certificate). After trying to enable groups (seems like it's a coincidence perhaps) I started receiving the error

 "Request failed with status code 401. Please refresh the page if the issue continues.
invalid jwt"

I re-created everything in Authentik for Netbird... Provider, Application, Service Account and was unable to get it functioning again. I worked with one of their support people in their Slack channel and he has mentioned multiple times it looks to be an issue with Authentik. We even tried eliminating Netbird by using the following curl commands to talk to authentik:

```
curl --insecure --request POST \
  --url https://<authentikURL>/application/o/token/ \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data username=Netbird \
  --data password=uXZo<Passwordforaccount> \
  --data scope=goauthentik.io/api \
  --data client_id=QppR<clientID>
```

of course with the proper client_id, password, and username (yes I tried with the uppercase N and even created users with other names to test if it held a memory/cache of it). Running this command returns the following:

`{"error": "invalid_grant", "error_description": "The provided authorization grant or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client"}`

Based on what Netbird is saying and from what I've seen, it appears it's related to the service account. One thing we noticed is even in a working install, if you change the service account password and try to update Netbird to use the new one - it will fail authenticating... but the original password still works (Even though the password is now different).

Other notes: When it was working I saw login events in Authentik's user dashboard for the Netbird service account, but it's broken I do not see any login events or entries in the event logs within the Authentik GUI

**To Reproduce**

1. Install Netbird self hosted behind HAProxy, Authentik docker install, all latest versions
2. Configure HAProxy as per documentation (I'm using vpn.domain.com for dashboard, vpnmgmt.domain.com for management/API and signal.domain.com for signal) and have HTTP/2 enabled for back and frontends as needed
3. Configure Netbird to use Authentik as the IDP using OIDC following this documentation: https://docs.netbird.io/selfhosted/selfhosted-guide
4. It may work at first but if you play around with the group syncing options (set the value to be 'groups' and check both boxes) and restart the instance, wait a day it eventually fails.

**Expected behavior**
For Netbird to continue working, for the curl command to return a positive result.

**Logs**
Netbird relevant log entries:
```
management_1  | 2023-12-18T21:18:18Z ERRO management/server/telemetry/http_api_metrics.go:181: HTTP response 4261207433: GET /api/groups status 401
management_1  | 2023-12-18T21:18:18Z ERRO management/server/http/middleware/access_control.go:46: failed to get user from claims: failed to get account with token claims unable to get authentik token, statusCode 400
management_1  | 2023-12-18T21:18:18Z ERRO management/server/http/util/util.go:80: got a handler error: invalid JWT
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.4
-   Deployment: docker-compose

**Additional context**
The devs have seen my screens and confirmed the issue appears to be either with Authentik or HAProxy - however we tried running curl to the internal IP of Authentik and faced the same issue (same network).

**Comment by TSJasonH** [comment]
I can confirm your findings here. I wasn't using HAProxy specifically but had authentik behind an F5 loadbalancer. I get the same message returned from the curl command as well when this was working just a couple days ago. This makes me think it's actually a problem on authentik's side. 

I also found this https://github.com/nextauthjs/next-auth/issues/9305 and subsequently this https://github.com/nextauthjs/next-auth/issues/8034 as they seem to correspond to the same behavior.

**Comment by j007bond007** [comment]
Thanks for confirming @TSJasonH. This is a very difficult issue to nail down the details on (for me at least) so I've tried to provide anything relevant and am up for more testing/debugging as needed, hoping the developers look into this especially if it's affecting other software using JWT tokens. I tried restoring previous versions of Authentik and rebuilding the NetBird VM from scratch and had it working again for a day or so but the same issue came back.

**Comment by j007bond007** [comment]
So I solved the issue. Turns out if you assign a group binding to the application for NetBird inside Authentik, having the NetBird service account be in the Authentik admins group is NOT enough, you need to add the Netbird service account user to the application's binding group as well. This did not seem intuitive but it worked!

**Comment by Welleee** [comment]
@j007bond007 Thank you for clarifications. Do you know if this is possible with a normal user (internal o external) instead of a service account user? I need to relate the authenticated user information.

With this endpoint:
```
curl  --request POST \
  --url https://<authentikURL>/application/o/token/ \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data username=internal_username \
  --data password=user_password \
  --data scope=openid profile email \
  --data client_id=<clientID> \
 --data client_secret=<clientSecret>
```

And i'm getting:
```
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client"
}
```
