### ISSUE TITLE
Authentik sending email to nobody

### ISSUE THREAD

**Issue by PythonCoderAS** [goauthentik/authentik#7967]
**Describe the bug**
Authentik attempted to send email to zero email addresses (To field is blank)

**To Reproduce**
These aren't 100% confirmed but this is what my situation was:

1. Turn off worker
2. Capture oauth authorization URL and change the redirect URL to something invalid
3. Use new invalid URL
4. Turn worker back on

**Expected behavior**
Emails should have a valid target

**Screenshots**
<img width="1739" alt="Screenshot 2023-12-21 at 2 12 08 PM" src="https://github.com/goauthentik/authentik/assets/13932583/fa277323-d245-4de0-8400-b6c308c1071d">

**Logs**
Log files are too large.

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5] 2023.10.5
-   Deployment: [e.g. docker-compose, helm] docker-compose

**Additional context**
What's really bizarre is that the user who "initiated" the authorization is a service user for Jellyfin's LDAP service, which shouldn't be possible either.

**Comment by PythonCoderAS** [comment]
My thinking is that since the Jellyfin user is also an Authentik admin, that it could be causing some weird configuration issue.

**Comment by rissson** [comment]
If the receivers of the "configuration errors" emails do not have email addresses configured, this is expected.

**Comment by PythonCoderAS** [comment]
I feel like Authentik should still have a check saying "If user does not have an email, do not send email"
