### ISSUE TITLE
Multiple authenticators does not display correctly (blank windows)

### ISSUE THREAD

**Issue by jamesngob** [goauthentik/authentik#7990]
**Describe the bug**
If I select to include multiple authentication methods for a new user to choose from, such as TOTP and DUO, the newly created user will be presented with a blank windows at login page. The TOTP and DUO authentications options are still in the windows (the mouse cursor change to hand icon when I move over)

**To Reproduce**

0. Setup the Flow to enable TOTP and DUO authentication methods. Force the new user to select one at log-in page
1. Go to Directory > Users and create a new User called Test. Set the password for the User
2. Go to login page and login the new user with the credentials created in step 1
3. The windows showing 2 methods for the user to select is blank
4. Move your mouse to upper part: TOTP/ Lower part: DUO

**Expected behavior**
The two authentication options should be displayed correctly instead of a blank windows

**Screenshots**
Refer to the attached screenshot where the cursor show a hand icon, indicate that the options are still there, it was just not displayed properly

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5
-   Deployment: docker compose

**Additional context**
If I select only 1 authentication method, either TOTP or DUO, it will show correctly

![blank-auth-windows](https://github.com/goauthentik/authentik/assets/73611762/4470d81b-6ac7-4b34-a424-bd18f32f3982)

**Comment by xNinjaKittyx** [comment]
This is the same problem here, but since that one is closed, I think we should keep this one? https://github.com/goauthentik/authentik/issues/4973

The text is not blank, it's actually just black and **very** difficult to read

**Comment by jamesngob** [comment]
> This is the same problem here, but since that one is closed, I think we should keep this one? #4973
> 
> The text is not blank, it's actually just black and **very** difficult to read

If I just select 1 method, it will display correctly e.g. text is dark but visible and you can see it's properly displayed. If you select 2 methods, then it is completely black-out, even if you try to "high-light" it (press-n-hold the mouse then move over it)... There is "nothing" in that area
Tested on Chrome (latest) and Safari (latest) on Jan 4, 2024
Cheers
