### ISSUE TITLE
Bitwarden Autofill not working when enabling password stage

### ISSUE THREAD

**Issue by modem7** [goauthentik/authentik#7993]
**Describe the bug**
When enabling password stage in the authentication flow, it breaks bitwarden autofill. 

**To Reproduce**

![image](https://github.com/goauthentik/authentik/assets/4349962/2d9a1696-f49d-4dc5-beab-aed3dddb4e5d)

If I disable the password stage, it works again. 

**Expected behavior**
Autofill to keep working

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/4349962/ea39c3bd-e958-402a-bc69-3d2f6c707b26)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5
-   Deployment: docker-compose

I was unsure if this was an Authentik problem or Bitwarden one, so I've also got a ticket over at https://github.com/bitwarden/clients/issues/7358 - happy to close either depending on where the problem lies.

**Comment by rissson** [comment]
Hi! This is a known issue. Can you try turning on Compatibility mode in the flow?
![image](https://github.com/goauthentik/authentik/assets/18313093/7e929aa1-6a40-4e22-92ab-742eddbb8980)

**Comment by modem7** [comment]
> Hi! This is a known issue. Can you try turning on Compatibility mode in the flow?
> ![image](https://github.com/goauthentik/authentik/assets/18313093/7e929aa1-6a40-4e22-92ab-742eddbb8980)
> 

That did it! Thanks!!

**Comment by septatrix** [comment]
> Hi! This is a known issue. Can you try turning on Compatibility mode in the flow?

May I ask why the mode "Broken with many password managers" even exists - and more so why it is the default?
