### ISSUE TITLE
Signed and Encrypted SAML request?

### ISSUE THREAD

**Issue by nicolas-semaphor** [goauthentik/authentik#7999]
~~I'm attempting to setup a SAML source which requires the request from Authentik to be both signed and encrypted, but it seems that encryption is not supported currently - or maybe I'm missing something?~~

I've later learned that It's not an encrypted Request i need, but rather the ability to decrypt the SAMLResponse \<EncryptedAssertion\> element. Example below.

Cheers,
Nicolas

**Comment by Janfred** [comment]
My related Ticket #7873
The SAML implementation seems very basic.
I would love to also have encrypted SAML.

**Comment by nicolas-semaphor** [comment]
I'm still in the testing phase, but I've modified the ResponseProcessor class in the the source/saml/processors/response.py and added the following:

```python
    def _decrypt_response(self):
        """Decrypt SAMLResponse EncryptedAssertion Element"""

        manager = xmlsec.KeysManager()
        key = xmlsec.Key.from_memory(
            self._source.signing_kp.key_data,
            xmlsec.constants.KeyDataFormatPem,
        )

        manager.add_key(key)
        encryption_context = xmlsec.EncryptionContext(manager)

        encrypted_assertion = self._root.find(".//{urn:oasis:names:tc:SAML:2.0:assertion}EncryptedAssertion")
        encrypted_data = xmlsec.tree.find_child(encrypted_assertion, "EncryptedData", xmlsec.constants.EncNs)
        decrypted_assertion = encryption_context.decrypt(encrypted_data)


        index_of = self._root.index(encrypted_assertion)
        self._root.remove(encrypted_assertion)
        self._root.insert(
                index_of,
                decrypted_assertion,
        )
```
Which decrypts the <EncryptedAssertion> elemenet using the Private key of the your SAML Source service provider.
It's not near ready for a PR, but maybe it can help you on the right direction. I had to make some modifications to the metadata.py processor as well, for the IdP to trust Authentik.

**Comment by nicolas-semaphor** [comment]
@Janfred your ticket might help me out with some Signature Validation errors I'm facing :-)
