### ISSUE TITLE
Bookmarked Applications: Add the ability to add applications without providers 

### ISSUE THREAD

**Issue by itristenx** [goauthentik/authentik#8018]
**Describe the solution you'd like**
I would like the ability to add applications to my end-user dashboard without a provider. This would behave similarly to a bookmark, this would be able to be assigned to policies to show specific users or hide from others.

**Additional context**
Similar to Okta - Admins can add applications to their users dashboard and assign them based on group policy’s.

**Comment by BeryJu** [comment]
you can do that, you can create an application, not assign a provider to it, and as long as the user has access and the app has a launch URL set, it will show up

**Comment by itristenx** [comment]
Thank you for answering! Keep up the great work.
