### ISSUE TITLE
Force TOTP for all users

### ISSUE THREAD

**Issue by 12nick12** [goauthentik/authentik#802]
Is there a way to force all users for TOTP? Also how do I go about setting up non admin users for TOTP?

**Comment by BeryJu** [comment]
> Is there a way to force all users for TOTP?

You can force users to TOTP by adding an Authenticator Validation Stage to the authentication flow and setting this option:
![image](https://user-images.githubusercontent.com/1932513/116618440-5c35de00-a93f-11eb-94a2-a9f1c396b255.png)

When you select that, you also have to specify a configuration flow, which the user is redirected to when they don't have any Authenticators setup.

> Also how do I go about setting up non admin users for TOTP?
Not quite sure what you mean, the configuration for TOTP is the same for admins and endusers, by clicking on the avatar in the bottom right corner and selecting the relevant stage (TOTP/static/webauthn)

**Comment by 12nick12** [comment]
I try to force default-authentication-flow-totp in the Default Authentication Flow and when I change it to force the user to configure an authenticator it says it's saved, but when I go back it still shows as continue.

**Comment by BeryJu** [comment]
@12nick12 true, the field didn't save correctly, will be fixed in the next version
