### ISSUE TITLE
dumb-init not found in $PATH error on 2023.10

### ISSUE THREAD

**Issue by Bojan023** [goauthentik/authentik#8037]
**Describe the bug**
Worker and server container fail to start. Currently having a 2023.8.3 stack working fine without errors.

**To Reproduce**

change image tag from 2023.8 to 2023.10
docker compose up

**Logs**
`✔ Container auth-redis-1                 Running                                                                                                                                        0.0s 
 ✔ Container auth-postgresql-1            Started                                                                                                                                        0.5s 
 ✔ Container auth-server-1                Recreated                                                                                                                                      0.7s 
 ✔ Container auth-worker-1                Recreated                                                                                                                                      2.3s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dumb-init": executable file not found in $PATH: unknown
`

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5
-   Deployment: docker-compose

**Additional context**
I noticed there have been some changes lately (e.g. https://github.com/goauthentik/authentik/commit/6b5200fead1169fd41b8d9ff9e8ade58f67258f0) regarding the $PATH variable and Entrypoint in the Dockerfile. Might be related?

**Comment by maskalix** [comment]
Have you solved that?

**Comment by Bojan023** [comment]
Upgrading to a later version (idk which specific version) solved the issue.

**Comment by maskalix** [comment]
Tried that tho no chance (tried the next after mine, tried any after mine and still same issue) :((

But thanks for trying to help me
