### ISSUE TITLE
Lack of documentation on /application/o/introspect

### ISSUE THREAD

**Issue by thechubbypanda** [goauthentik/authentik#8091]
**Describe the bug**
(I may be blind but) I can't seem to find much documentation on the `/application/o/introspect` endpoint for OAuth2.0.

**To Reproduce**

1. Search introspect on wiki
2. Search introspect on api browser
3. Open any Oauth2/OIDC provider in an Authentik instance

**Expected behavior**
Some idea of what the endpoint does/is used for

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
While we don't have specific documentation for that yet, the introspection endpoint conforms to the OAuth2 standard for introspection: https://datatracker.ietf.org/doc/html/rfc7662

**Comment by thechubbypanda** [comment]
Point being, there's no mention of it even existing.
