### ISSUE TITLE
How to predict the `sub` value when using hashed ID

### ISSUE THREAD

**Issue by k8ieone** [goauthentik/authentik#8123]
**Describe your question**
I'd like to connect an existing user in a few OIDC applications to an Authentik user. To do this, I need to know the value of `sub`. With some applications, I can easily do this, because I set the *Subject mode* to "Based on the User's UUID". For some OIDC applications, I left the *Subject mode* on the default "Based on the User's hashed ID".

I'd like to know how I can calculate the hash, which will be used as `sub`. I assume the hashing algorithm is sha256, but I had no luck with that. I tried hashing the user ID (25 in my case), the username, email and UUID.

But none of the hashes I made matched the one from Authentik.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/28711937/1fdf5b6d-78a2-4293-bc44-1c6c0be90e44)
The *Subject mode* option in OAuth2 provider settings

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5
-   Deployment: helm

**Comment by BeryJu** [comment]
it's a hash of the user's pk (int) and the install id: https://github.com/goauthentik/authentik/blob/main/authentik/core/models.py#L254

**Comment by k8ieone** [comment]
Is there any way to obtain that user PK? I think I found the install ID in the `authentik_core_user` table (the `id` column). I couldn't find the PK tho.

**Comment by BeryJu** [comment]
The install ID is global and can be retrieved with `/api/v3/enterprise/license/get_install_id/` for example

The PK is part of the users api `/api/v3/core/users/`
