### ISSUE TITLE
2023.10.6 - "Please select a username" after Azure AD login

### ISSUE THREAD

**Issue by pgodzwa** [goauthentik/authentik#8131]
**Describe your question/**

Is it now a expected behavior in 2023.10.6 version to ask every user for username input after logging in with azure ad?
![image](https://github.com/goauthentik/authentik/assets/7706996/7c35f530-62a2-4afd-92aa-c290ad221c5f)

In previous versions it was simply authenticating without any prompt, using email address from Azure AD as username.

Now it expects user to input username (and it leads to duplicated accounts, because users with mail as username already exist), and if you enter already existing mail as username it shows error:
![image](https://github.com/goauthentik/authentik/assets/7706996/a8aaaf90-b309-425c-92a1-174739d01fc6)

I think it can be related to this fix:
https://github.com/goauthentik/authentik/pull/7970

Is it possible somehow to set this username automatically, or revert back to using email address so old user accounts will work again?

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.6
-   Deployment: helm

**Comment by CyB0rgg** [comment]
This is unfortunately due to the bug that still exists in .6, see https://github.com/goauthentik/authentik/issues/7972#issuecomment-1886863709
After successful AD login it redirects to the enrolment flow for some reason.

**Comment by CyB0rgg** [comment]
This does not fix anything, I am afraid. It is now back to the:
<img width="614" alt="Screenshot 2024-01-12 at 18 00 38" src="https://github.com/goauthentik/authentik/assets/83865615/65afc0f7-09df-411a-9b11-529eda67ef21">

When can we have a real fix for it please ?

**Comment by CyB0rgg** [comment]
Just to add a bit of the background. With the latest cherry-picked 2023-10 , when adding AzureAD social login it is still saving in DB the new profile URL - https://login.microsoftonline.com/common/openid/userinfo - despite the initial URL being different after the reversing PR was merged. The only way to be able to control what is saved into the DB is to use the generic openid (which used to work as a workaround for some a couple of versions ago when filled with the Azure URLs). When using the new profile URL it authenticates and then goes back to the enrollment flow, when using old url it shows "could not determine id". Each and every time the Azure ID log shows succesful authentication.

**Comment by CyB0rgg** [comment]
Close, but still no cigar. After latest patches it can now retrieve the ID but still fails with the same error immediately:
<img width="554" alt="Screenshot 2024-01-14 at 09 49 33" src="https://github.com/goauthentik/authentik/assets/83865615/f56c4245-50ce-4a99-8ab5-1dd8a648d348">

@BeryJu if you don't have the access to the AzureAD (Entra) for testing I can help with testing of a fix branch before you merge. Super keen on getting this to work again as soon as possible.

Also worth mentioning - after filling in the well-know field it does not automatically populate / overwrite the auth/access/profile fields. Despite JWKS URL being left empty it still automatically fills it in and pulls the raw key.

**Comment by pgodzwa** [comment]
@BeryJu unfortunately it's still not fixed in the latest release - it still asks for username after Azure AD login.

**Comment by tograss** [comment]
I found a working solution. See BeryJu's tipp in https://github.com/goauthentik/authentik/issues/8342 . Key idea is to build a custom enrollment / login flow, with a policy that assigns user information from oauth_data to prompt data. If you than ask for missing information or error out is a matter of preference.
