### ISSUE TITLE
I lost all my icons with the update from 2023.10.5 to 2023.10.6 media folder empty

### ISSUE THREAD

**Issue by pbvdven** [goauthentik/authentik#8162]
**Describe the bug**
I lost all my icons with the update from 2023.10.5 to 2023.10.6 media folder empty

**To Reproduce**
update to the latest version

**Expected behavior**
not te lose my icons

**Screenshots**
media folder is empty after update

**Logs**
no relevant output

**Version and Deployment (please complete the following information):**

-   authentik version: 2022.10.6
-   Deployment: docker-compose

**Comment by jamesngob** [comment]
How did you update the Authentik?
For me, I edit the docker-compose.yml and .env file (change 2022.10.5 to 2022.10.6), save, exit and bring the docker up again
No issue. But it might be bug in your case....
