### ISSUE TITLE
LDAP Source API Patch

### ISSUE THREAD

**Issue by boesr** [goauthentik/authentik#8176]
**Describe the bug**
When executing Patch on the LDAP source slug via the API browser

`PATCH /sources/ldap/{slug}/`

I receive an error. It seems like the API browser sets some default values for parameters. The error message is 

```
{
  "slug": [
    "Enter a valid \"slug\" consisting of letters, numbers, underscores or hyphens."
  ],
  "authentication_flow": [
    "Invalid pk \"18d0d054-bb80-4000-809b-62d25e2f0d01\" - object does not exist."
  ],
  "enrollment_flow": [
    "Invalid pk \"18d0d054-bb80-4000-8f8b-fe561af29201\" - object does not exist."
  ],
  "peer_certificate": [
    "Invalid pk \"18d0d054-bb80-4000-8137-bfd323204f01\" - object does not exist."
  ],
  "client_certificate": [
    "Invalid pk \"18d0d054-bb80-4000-8427-ef847b0d5401\" - object does not exist."
  ],
  "sync_parent_group": [
    "Invalid pk \"18d0d054-bb80-4000-8b9e-823d1da1c601\" - object does not exist."
  ],
  "property_mappings": [
    "Invalid pk \"18d0d054-bb80-4000-8dea-35a4a6bf8701\" - object does not exist."
  ],
  "property_mappings_group": [
    "Invalid pk \"18d0d054-bb80-4000-8f70-9d1208536501\" - object does not exist."
  ]
}
```

**To Reproduce**

1. Open API Browser
2. Set valid token
3. Open `PATCH /sources/ldap/{slug}/`
4. Enter valid slug
5. Hit try

**Expected behavior**
A ldap sync is started

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/88541074/5b3096d4-d71f-435c-9217-cad5de03f07c)

**Logs**
```
authentik-server-1  | {"auth_via": "api_token", "event": "/api/v3/sources/ldap/myad/", "host": "auth.mydomain.de", "level": "info", "logger": "authentik.asgi", "method": "PATCH", "pid": 37, "remote": "172.22.119.73", "request_id": "ed45ec387cf342619dda7f90c6f34a2e", "runtime": 59, "scheme": "https", "status": 400, "timestamp": "2024-01-15T13:26:30.836150", "user": "akadmin", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.6
-   Deployment: docker-compose

**Additional context**
Wanted to use Patch to debug https://github.com/goauthentik/authentik/issues/7838#issuecomment-1867863185

**Comment by BeryJu** [comment]
patch allows you to do a partial update, so in theory you could send it an empty request body (the API browser doesn't really have a concept of partial updates hence it suggests every field in the body)

**Comment by boesr** [comment]
Thanks for clearing that up. I could send the request now. Unfortunately the LDAP source does not sync. 

In the log I see:

```
authentik-worker-1  | {"event": "LDAP sync locked, skipping task", "level": "debug", "logger": "authentik.sources.ldap.tasks", "pid": 53, "source": "myad", "task_id": "task-73d8409f4bd04200b61aa9fbb5080bb0", "timestamp": "2024-01-16T06:54:09.030163"}
```

Seems like the sync is locked by another task? But then again I can confirm that there is no syncing happening. But that is maybe another issue

**Comment by boesr** [comment]
Nevermind, the above error seems to be rooted in a broken LDAP source. I removed it, deleted all users and created a new source with a different name. Now it works again. Going to close this one.
