### ISSUE TITLE
How to Automatically Add Users to Groups During Enrollment?

### ISSUE THREAD

**Issue by gitayam** [goauthentik/authentik#8181]
## Objective:
I want to ensure that once a user completes the enrollment flow,
they are automatically added to predefined groups within Authentik without manual intervention.

## Current Setup:

I have set up the standard stages of an enrollment flow: Invitation, Prompt, User Write, and User Login.
After the "User Write Stage," where the user account is created, I would like to insert a stage for group assignment.
Issue:

I do not see an existing stage type allowing automatic group assignment in the Authentik admin interface.
The available stages (e.g., User Write Stage, SMS/TOTP Authenticator Setup, etc.) do not seem to cover group assignments.

## Questions:

1. Is there a built-in stage that I might have missed that can be used to add users to groups automatically during the enrollment process?
2. If such a stage does not exist, could you guide us on using an API call or a custom script within the enrollment flow to add users to groups?
3. Can any community-contributed stages or plugins be recommended for this purpose?
4. If this feature is not currently available, could you suggest any workarounds or the possibility of this feature being added in a future release?

**Comment by gitayam** [comment]
@sjthiessen I love you bro. This is it!!

**Comment by benji78** [comment]
@partofthething I agree it is not clear. I believe it is an `Expression Policy` that needs to be created. You then need to bind it to the user-write stage (in the flow's `Stage bindings`, click the small arrow to the left of that stage).

In my case, I wanted to set groups for new user's invitations, directly in the `Custom attributes`. This is exactly what I wanted to do : https://unhexium.net/authentik/authentik-group-assignment-on-invitation-usage/

**Comment by SylvainSeb** [comment]
@benji78 I just tried the script from the website you gave, thanks for that, but it didn't work, did you change something in the script? Thanks
Sylvain

**Comment by benji78** [comment]
@SylvainSeb Yes it works for me, the only thing I did is renaming `groups_to_add` to `groups` (which is not needed) and now I just have to set these `Custom Attributes` to create a new user:

```yaml
username: test
groups: [authentik Admins, Family]
```

What do you mean by "it did not work"? Do you have any `General system exception` or similar in `Events` > `Logs`?

**Comment by SylvainSeb** [comment]
@benji78 Thanks, it is maybe because I use this script as well to send automatic invitation email https://github.com/goauthentik/authentik/discussions/13305
