### ISSUE TITLE
MFA authenticator selection does not use the stage's "Authenticator type name" (Authenticator display name)

### ISSUE THREAD

**Issue by motey** [goauthentik/authentik#8194]
**Describe the bug**

When having a forced MFA Stage in your authentication flow with multiple MFA Options you can select which MFA Type you want to enroll, if there is none enrolled yet.

Also there is an option for each mfa setup stage to define a display name. The field is named "Authenticator type name"
![grafik](https://github.com/goauthentik/authentik/assets/1006417/cec1826b-da88-48d8-b8c4-bc71bbc22776)

This display name is never used as far as i can see.

It is not used in the "Which existing authenticator you want to use for login today?"-dialog
![grafik](https://github.com/goauthentik/authentik/assets/1006417/f846fdfe-51bd-49cc-8f91-fdd8b7a6a7cd)

Nore is it used in the "Which authenticator you want to setup?"-dialog
![grafik](https://github.com/goauthentik/authentik/assets/1006417/cca824c0-8cc7-4199-a541-eac14d3ec801)

The second case is particular unfavorable because it shows the stage name, which is something a normal user barely can interpret. 

Is there something i missed or is it a bug?

Thanks for any information.

**To Reproduce**

1. Setup a authentication flow with forced MFA. 
2. Set multiple MFA method to choose from
3. Use the flow with a user with no MFA yet
4. Look at the "Select an authentication method." Dialog on login.

**Expected behavior**
The text shown for each authenicator should match the one defined in the stage configuratior field "Authenticator type name"

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.6
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
partially closed by #8255
