### ISSUE TITLE
Feature Request: Per invitation "single-use" setting

### ISSUE THREAD

**Issue by robobenklein** [goauthentik/authentik#821]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to give users a link to register their account and have the invitation code only used once.

**Describe the solution you'd like**
At invitation creation I'd like to be able to check a box for "Single Use" where the invitation code would be removed automatically when a flow completes using that token.

**Describe alternatives you've considered**
Alternatively it could be an option within the Invitation stage that is default off, check box to "Consume invitation token on usage"

**Comment by Akruidenberg** [comment]
Same for me!
