### ISSUE TITLE
Palo alto  global protect Saml 2.0 - getting not found error when i am trying to access it using global protect client .

### ISSUE THREAD

**Issue by anburhce** [goauthentik/authentik#8223]
I have exported the Palo alto global protect meat data under providers.
Same way  have uploaded the metedata from Authentik to palo alto 

    authentik version: [e.g. 2024.10.6]
    Deployment: [e.g. docker-compose ]
     PaloAlto  firewall 11.1.0 
     Global protect Agent - 6.2.2 

![not found authntik palo alto](https://github.com/goauthentik/authentik/assets/23453745/86c5739f-059d-4336-8fc9-064ebe3406fb)

Kindly help  me to rectify this issue.
Also if you have any document how to implement saml for palo alto kindly share it

**Comment by J5andi5n0t** [comment]
Not sure if this is still an issue for you but we had a similar experience today just not involving docker.

There are 2 github posts that may be of some help: 

https://github.com/goauthentik/authentik/issues/8223

https://github.com/goauthentik/authentik/issues/8396

Below is my colleague's post to Github issue 8396

> Hello,
> 
> I am not sure if you are still having this problem, but I wanted to chime in that we were also having problems with the embedded browser and found a post on Reddit which recommended upgrading to GP 6.2.3 and it fixed the issues we were having.
> 
> Reference to Reddit post is here: https://www.reddit.com/r/paloaltonetworks/comments/swcnm0/globalprotect_and_the_embedded_browser_in_a/
> 
> Look for the comment from "Fearless_Garlic_3054" regarding new features for GP " Embedded Browser Framework Upgrade " as part of GP 6.2.3. (Released on 2024-04-10)

I was going to post this for others to see after our testing today but you beat me to it. Have verified this along with @AngelFonseca88 on various devices, both corporate and personal, with various credentials, on various portals. 

At this time 6.2.2 is still the "preferred" release directly from Palo for Windows x64, so YMMV if you use 6.2.3 as it was only released 4/10/24, but it seems to have solved our "White Screen of Frustration" problem where you wouldn't be passed along for authentication ...just as an FYI to the referenced Reddit post @AngelFonseca88 posted earlier, we do not have Prisma in our environment but it still seemed to solve our GP/SAML issue.  

Hope this helps someone!

**Comment by BeryJu** [comment]
Support for older, outdated browser engines was added with #10296
