### ISSUE TITLE
Azure SSO not working

### ISSUE THREAD

**Issue by cdmx1** [goauthentik/authentik#8236]
As referenced in other issues that have been closed without a clear solution would like to highlight in this issue that the bug with Oauth still exists. 

![image](https://github.com/goauthentik/authentik/assets/137166088/606f05bd-67ed-4e43-bc38-e243b272b71e)

Above page is observed on clicking with Azure SSO

**Comment by roney492** [comment]
PR Raised with fix for same:

https://github.com/goauthentik/authentik/pull/8244
