### ISSUE TITLE
Unable to switch user after WebAuthn failed

### ISSUE THREAD

**Issue by septatrix** [goauthentik/authentik#8237]
**Describe the bug**
When the WebAuthn stage fails there is no possibility to go change the user or go back to another stage.

**To Reproduce**

1. Enroll WebAuthn device for a user.
2. Try to log in with that user, enter username and password.
3. Purposefully fail/reject the WebAuthn prompt by your browser.
4. Try to go back to e.g. log in as a different user
5. This won't be possible

**Expected behavior**
Similar to failing at the password prompt stage, a "Not you?" link or similar method to go back should be shown.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/24257556/2d308170-7c5d-49d8-941d-6f69bfe31f60)
![image](https://github.com/goauthentik/authentik/assets/24257556/58d5acbd-8a39-4b95-8c99-d08864325320)

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.3
-   Deployment: docker-compose

**Comment by septatrix** [comment]
Still relevant

**Comment by BeryJu** [comment]
This should be fixed with 2024.2.2, which version are you on?

**Comment by septatrix** [comment]
Ah we are still on 2023.10, I will close this then. I plan to update by next week and will reopen if it turns out to not be fixed
