### ISSUE TITLE
Some question about user isolation?

### ISSUE THREAD

**Issue by Yaya48** [goauthentik/authentik#8257]
**Describe your question/**
A clear and concise description of what you're trying to do.

Hello, i wanted to know if i  could achieve user isolation like keycloack basically so like i have an ldap authentification flow that only allow ldap users because actually if i dont use Groups non ldap user can also login, also i wanted to know if i could hide username/password input when using oauth2 federation so only login with discord is displayed.

**Relevant infos**
i.e. Version of other software you're using, specifics of your setup
Latest version

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
-   Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by BeryJu** [comment]
See https://docs.goauthentik.io/docs/flow/stages/identification/#source-settings and for the LDAP flow you can set the flow's `authentication` setting to `require outpost` which will only make the flow executable from outposts
