### ISSUE TITLE
Proxy Outpost Boot Loop

### ISSUE THREAD

**Issue by PKizzle** [goauthentik/authentik#8260]
**Describe the bug**
With the addition of geo-ip ASN the `CapabilitiesEnum` was altered to include `can_asn`. However the go api shipped with proxy version `2023.10.6` does not include these changes.

**To Reproduce**

1. Launch an Authentik instance that includes Geo-IP's ASN
2. Create a proxy outpost
3. Wait for the proxy to try to startup

**Expected behavior**
The proxy can successfully boot without an error

**Logs**
```
{"event":"Loaded config","level":"debug","path":"inbuilt-default","timestamp":"2024-01-23T02:29:11Z"}
{"event":"Loaded config from environment","level":"debug","timestamp":"2024-01-23T02:29:11Z"}
{"event":"not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it.","level":"info","logger":"authentik.go_debugger","timestamp":"2024-01-23T02:29:11Z"}
{"error":"can_asn is not a valid CapabilitiesEnum","event":"Failed to fetch global configuration","level":"error","logger":"authentik.outpost.ak-api-controller","timestamp":"2024-01-23T02:29:12Z"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.6
-   Deployment: helm

**Comment by PKizzle** [comment]
This has been fixed with version 2023.10.7. A note regarding this issue within the documentation targeted at users of the previous version is still appreciated.

**Comment by sskokorin** [comment]
Version 2024.2.1. The problem still exists
```
{"event":"Loaded config","level":"debug","path":"inbuilt-default","timestamp":"2024-02-23T09:44:43Z"}
{"event":"Loaded config from environment","level":"debug","timestamp":"2024-02-23T09:44:43Z"}
{"event":"not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it.","level":"info","logger":"authentik.go_debugger","timestamp":"2024-02-23T09:44:43Z"}
{"error":"can_asn is not a valid CapabilitiesEnum","event":"Failed to fetch global configuration","level":"error","logger":"authentik.outpost.ak-api-controller","timestamp":"2024-02-23T09:44:43Z"}
```

**Comment by geokvant** [comment]
I see exact same behavior with authentik-proxy again after upgrade from 2023.10.7 to 2024.2.1

**Comment by sskokorin** [comment]
> I see exact same behavior with authentik-proxy again after upgrade from 2023.10.7 to 2024.2.1

I think you should stop Authentik, delete the existing LDAP Outpost Docker image and start Authentik again. The new latest image of the LDAP outpost will be downloaded and launched. These steps helped me after upgrade to 2024.2.1.

**Comment by geokvant** [comment]
Thank you!
In my case problem was with Proxy outpost, but only deletion of authentik proxy image (_ghcr.io/goauthentik/proxy:latest_) and redownload of it solved the problem.
