### ISSUE TITLE
SAML Source Doesn't allow login

### ISSUE THREAD

**Issue by amanzella** [goauthentik/authentik#8279]
**Describe the bug**
I've added a new SAML source and when I select the source it redirects me to the source's login page. I enter the creds, wait for the MFA, accept it and then it redirects me to authentik where I get an error.

Permission denied
 Request has been denied.

Request to authenticate with SAML-APP has been denied. Please authenticate with the source you've previously signed up with.

Am I missing something?

**Comment by LM1LC3N7** [comment]
@amanzella did you find a solution? I have seen multiple bug reports or questions on GitHub about this subject and never found a solution or an answer yet.
