### ISSUE TITLE
Authentik + Roundcube + Dovecot - 404 page on webmail after successful authentication on Authentik 

### ISSUE THREAD

**Issue by LeftoversTodayAppAdmin** [goauthentik/authentik#8306]
**Describe the bug**

I am using Authentik  to build SSO with Roundcube + Dovecot but I get a 404 page on webmail after successful authentication on Authentik. Direct authentication to the web server has no issues. Authentik is also working really well with Rocket.chat

**To Reproduce**

- I have setup Authentik and want OAUTH2/OpenID for SSO to iRedmail instance running Roundcube and Dovecot.
- When I go through the login flow and go to mail.mydomain.com I see the button for Authentik and when I click it and enter username and password its a success, the Authentik logs show success.
- It redirects back to my mailserver and it shows a 404, the URL looks like this: 
https://mail.mydomain.com/index.php/login/oauth?code=31e7ce7051194543906e6fe2ebda58c8&state=G3qhnBAQz7sT

I can provide access to my test setup.

**Expected behavior**
After auth the redirect opens the inbox on iRedmail

**Screenshots**
Its just a nginx 404 page with this URL: https://mail.mydomain.com/index.php/login/oauth?code=31e7ce7051194543906e6fe2ebda58c8&state=G3qhnBAQz7sT

**Logs**
Roundcube logs:
Jan 25 07:23:13 mail roundcube: <83b3gt0f> IMAP Error: Login failed for support@leftovers.today against 127.0.0.1 from 97.126.115.237. AUTHENTICATE LOGIN: A0002 NO [AUTHENTICATIONFAILED] Authentication failed. in /opt/www/roundcubemail-1.6.5/program/lib/Roundcube/rcube_imap.php on line 211 (POST /?_task=login&_action=login)
Jan 25 07:23:14 mail roundcube: <83b3gt0f> Failed login for support@leftovers.today from 97.126.115.237 in session 83b3gt0f8leaq23f (error: 0)

Nothing in the dovecot logs

**Version and Deployment (please complete the following information):**

-   authentik version: latest 
-   Deployment: docker

**Additional context**

**Comment by MaximalCats** [comment]
Having the same issue - any fix for it yet?

**Comment by Atomique** [comment]
Also having an issue that seems like this one. I get an error while authenticating to gitlab and seafile. Worked before my update.

**Comment by MaximalCats** [comment]
I seemed to have found a fix for this; i forgot where or what i did however. It had something to do with the way how nginx finds php files. Here is my nginx config:
`server {
        listen *:80 ;
        listen [::]:80 ;
        server_name xxx ;
        root /var/www/xxx;
        access_log /var/log/nginx/xxx.access.log;
        error_log /var/log/nginx/xxx.error.log;
        proxy_read_timeout 180s;
        add_header X-Powered-By "TinyCP";
        index  index.php default.php index.html index.htm default.html default.htm;

        # Lets Encrypt exception
        location /.well-known/acme-challenge/ {
                default_type "text/plain";
                rewrite /.well-known/acme-challenge/(.*) /$1 break;
                root /opt/tinycp/domains/xxx/letsencrypt/challenges;
        }

        # Security
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        # Include .nginx config file in document root directory
include /var/www/xxx/.ngin*;


        # Autodiscoveries for email accounts
        location ^~ /autodiscover {
                gzip off;
                root /opt/tinycp/bin;
                fastcgi_param SCRIPT_FILENAME /opt/tinycp/bin/email-autodiscover.sh;
                fastcgi_pass unix:/var/run/fcgiwrap.socket;
        }
        location ^~ /.well-known/autoconfig/mail {
                gzip off;
                root /opt/tinycp/bin;
                fastcgi_param SCRIPT_FILENAME /opt/tinycp/bin/email-autodiscover.sh;
                fastcgi_param QUERY_STRING $query_string;
                fastcgi_pass unix:/var/run/fcgiwrap.socket;
        }

        # PHP-FPM
        location ~ \.php$ {

                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                try_files $fastcgi_script_name = 404;
                set $path_info $fastcgi_path_info;

                fastcgi_param PATH_INFO          $path_info;
                fastcgi_param SCRIPT_FILENAME    $document_root$fastcgi_script_name;
                fastcgi_param QUERY_STRING       $query_string;
                fastcgi_param REQUEST_METHOD     $request_method;
                fastcgi_param CONTENT_TYPE       $content_type;
                fastcgi_param CONTENT_LENGTH     $content_length;

                fastcgi_param SCRIPT_NAME        $fastcgi_script_name;
                fastcgi_param REQUEST_URI        $request_uri;
                fastcgi_param DOCUMENT_URI       $document_uri;
                fastcgi_param DOCUMENT_ROOT      $document_root;
                fastcgi_param SERVER_PROTOCOL    $server_protocol;
                fastcgi_param REQUEST_SCHEME     $scheme;
                fastcgi_param HTTPS              $https if_not_empty;

                fastcgi_param GATEWAY_INTERFACE  CGI/1.1;
                fastcgi_param SERVER_SOFTWARE    nginx/$nginx_version;

                fastcgi_param REMOTE_ADDR        $remote_addr;
                fastcgi_param REMOTE_PORT        $remote_port;
                fastcgi_param SERVER_ADDR        $server_addr;
                fastcgi_param SERVER_PORT        $server_port;
                fastcgi_param SERVER_NAME        $server_name;
                fastcgi_param REDIRECT_STATUS    200;


                fastcgi_pass unix:/run/php/php8.3-fpm.sock;
                fastcgi_index index.php;
                fastcgi_buffers 8 16k;
                fastcgi_buffer_size 32k;

        }

}

server {
        listen *:443 ssl http2;
        listen [::]:443 ssl http2;
        server_name xxx ;
        root /var/www/xxx;
        access_log /var/log/nginx/xxx.access.log;
        error_log /var/log/nginx/xxx.error.log;
        proxy_read_timeout 180s;
        add_header X-Powered-By "TinyCP";
        index  index.php default.php index.html index.htm default.html default.htm;
        # HSTS
        add_header Strict-Transport-Security "max-age=600; preload";

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256;
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:NginxCache123:50m;
        ssl_stapling on;
        ssl_stapling_verify on;

        ssl_certificate /opt/tinycp/domains/xxx/ssl/ssl-letsencrypt.crt;
        ssl_certificate_key /opt/tinycp/domains/xxx/ssl/ssl-letsencrypt.key;
        ssl_trusted_certificate /opt/tinycp/domains/xxx/ssl/ssl-letsencrypt.ca;


        # Lets Encrypt exception
        location /.well-known/acme-challenge/ {
                default_type "text/plain";
                rewrite /.well-known/acme-challenge/(.*) /$1 break;
                root /opt/tinycp/domains/xxx/letsencrypt/challenges;
        }

        # Security
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        # Include .nginx config file in document root directory
include /var/www/xxx/.ngin*;


        # Autodiscoveries for email accounts
        location ^~ /autodiscover {
                gzip off;
                root /opt/tinycp/bin;
                fastcgi_param SCRIPT_FILENAME /opt/tinycp/bin/email-autodiscover.sh;
                fastcgi_pass unix:/var/run/fcgiwrap.socket;
        }
        location ^~ /.well-known/autoconfig/mail {
                gzip off;
                root /opt/tinycp/bin;
                fastcgi_param SCRIPT_FILENAME /opt/tinycp/bin/email-autodiscover.sh;
                fastcgi_param QUERY_STRING $query_string;
                fastcgi_pass unix:/var/run/fcgiwrap.socket;
        }

        # PHP-FPM
        location ~ [^/]\.php(/|$) {

                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                try_files $fastcgi_script_name = 404;
                set $path_info $fastcgi_path_info;

                fastcgi_param PATH_INFO          $path_info;
                fastcgi_param SCRIPT_FILENAME    $document_root$fastcgi_script_name;
                fastcgi_param QUERY_STRING       $query_string;
                fastcgi_param REQUEST_METHOD     $request_method;
                fastcgi_param CONTENT_TYPE       $content_type;
                fastcgi_param CONTENT_LENGTH     $content_length;

                fastcgi_param SCRIPT_NAME        $fastcgi_script_name;
                fastcgi_param REQUEST_URI        $request_uri;
                fastcgi_param DOCUMENT_URI       $document_uri;
                fastcgi_param DOCUMENT_ROOT      $document_root;
                fastcgi_param SERVER_PROTOCOL    $server_protocol;
                fastcgi_param REQUEST_SCHEME     $scheme;
                fastcgi_param HTTPS              $https if_not_empty;

                fastcgi_param GATEWAY_INTERFACE  CGI/1.1;
                fastcgi_param SERVER_SOFTWARE    nginx/$nginx_version;

                fastcgi_param REMOTE_ADDR        $remote_addr;
                fastcgi_param REMOTE_PORT        $remote_port;
                fastcgi_param SERVER_ADDR        $server_addr;
                fastcgi_param SERVER_PORT        $server_port;
                fastcgi_param SERVER_NAME        $server_name;
                fastcgi_param REDIRECT_STATUS    200;


                fastcgi_pass unix:/run/php/php8.3-fpm.sock;
                fastcgi_index index.php;
                fastcgi_buffers 8 16k;
                fastcgi_buffer_size 32k;

        }

}`.
If i remember correctly, i think i changed the regex value which nginx uses to find php files to: `[^/]\.php(/|$)`.
If any issues arise, i unfortunately can't help. I have switched to Caddy, and my knowledge of nginx is very limited.

**Comment by Leatherface75** [comment]
For me the problem seems to be in dovecot.
Have tried everything can't get this to work.

`Mar 23 20:32:48 auth-worker(65471): Info: conn unix:auth-worker (pid=59652,uid=302): auth-worker<4>: pam(xxxxxxxx,::1,<em8AzkVUkcoAAAAAAAAAAAAAAAAAAAAB>): pam_authenticate() failed: Authentication failure (Password mismatch?)
Mar 23 20:32:48 auth: Info: oauth2(xxxxxx,::1,<em8AzkVUkcoAAAAAAAAAAAAAAAAAAAAB>): oauth2 failed: Introspection failed: Username 'xxxxxxx' did not match 'xxxxxxx@xxxxxxx.xxx'`

**Comment by Leatherface75** [comment]
Anyone?

**Comment by Leatherface75** [comment]
Any news? Still can't get this working?

**Comment by LeftoversTodayAppAdmin** [comment]
@Leatherface75  Im moving over to using this instead: https://docs.postalserver.io/

**Comment by xpufx** [comment]
Hello peoples. I am having a similar but different issues. My initial login works fine. It also works fine if I log out and log back in or go to the Authentik portal and click the link there.  What doesn't work is, after a certain amount of time the connection is lost (authentication fails probably) and if I refresh the page it does not log in again successfully. I get an authentication error from roundcube via imap xoauth. 

I need to also add that if you followed the roundcube/authentik documentation, you might have the same issues as I because I wrote the documentation on the site. Will let you know if I find the reason and a solution. 

@Leatherface75 Your issue sounds different. You have a mismatch btw username vs username@domain.com .   Be more than happy to compare configs with you.

**Comment by Leatherface75** [comment]
> Hello peoples. I am having a similar but different issues. My initial login works fine. It also works fine if I log out and log back in or go to the Authentik portal and click the link there. What doesn't work is, after a certain amount of time the connection is lost (authentication fails probably) and if I refresh the page it does not log in again successfully. I get an authentication error from roundcube via imap xoauth.
> 
> I need to also add that if you followed the roundcube/authentik documentation, you might have the same issues as I because I wrote the documentation on the site. Will let you know if I find the reason and a solution.
> 
> @Leatherface75 Your issue sounds different. You have a mismatch btw username vs [username@domain.com](mailto:username@domain.com) . Be more than happy to compare configs with you.

I have done as it says here and also tried to change to use username without luck.
I am using usernames as login in Dovecot.
