### ISSUE TITLE
wrong application wekan env var properties

### ISSUE THREAD

**Issue by falkheiland** [goauthentik/authentik#8308]
https://github.com/goauthentik/authentik/blob/45a33103206c07a9b38a6d371104a413348fea8a/website/integrations/services/wekan/index.mdx#L52-L53

should be:

```
      - OAUTH2_ID_MAP=sub
      - OAUTH2_USERNAME_MAP=email
```

as to: https://github.com/wekan/wekan/issues/5250#issuecomment-1872112972

**Comment by falkheiland** [comment]
still relevant

**Comment by rissson** [comment]
Feel free to submit a PR

**Comment by falkheiland** [comment]
https://github.com/goauthentik/authentik/pull/9047
