### ISSUE TITLE
Unhealthy LDAP Outpost / no connection

### ISSUE THREAD

**Issue by boesr** [goauthentik/authentik#8310]
**Describe the bug**
I created an LDAP outpost like described at https://goauthentik.io/docs/providers/ldap/generic_setup with the default flow. The outpost container only gets created when I restart the Authentik-Stack (docker compose down && docker compose up -d). It is directly shown as unhealthy and does not allow any connection. Below you find the log of that container.

**To Reproduce**

1. Create LDAP Outpost / Provider according to documentation

**Expected behavior**
Healthy outpost container and able to connect e.g. via ldapsearch

**Screenshots**
/

**Logs**

Log of the ldap outpost container. 

```
{"event":"Loaded config","level":"debug","path":"inbuilt-default","timestamp":"2024-01-25T13:16:45Z"}
{"event":"Loaded config from environment","level":"debug","timestamp":"2024-01-25T13:16:45Z"}
{"event":"not enabling debug server, set `AUTHENTIK_DEBUG` to `true` to enable it.","level":"info","logger":"authentik.go_debugger","timestamp":"2024-01-25T13:16:45Z"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.6]
-   Deployment: docker-compose

**Comment by boesr** [comment]
The container not being created seems to be connected to LDAP sync. As soon as I deactivate the LDAP source sync (close to 100k users, 10 workers active), the container gets created. It is still unhealthy though.

**Comment by dginhoux** [comment]
Hi, 

I've the same behavior. I'm trying authentik and have following the same guide for ldap in the docs.
I use and add a custom ldap-client+nc service to test it.

It appear there no listen on bot 6636 or 3389 opened on the server/or worker service.
Logs in trace mode don't return any 6636 or 3389 in logs, like for 9000 or 9443.
And no error seen in logs when grep for ldap pattern.

I specify ldap listen related vars described in https://goauthentik.io/docs/installation/configuration#listen-settings

**Comment by boesr** [comment]
> Hi,
> 
> I've the same behavior. I'm trying authentik and have following the same guide for ldap in the docs. I use and add a custom ldap-client+nc service to test it.
> 
> It appear there no listen on bot 6636 or 3389 opened on the server/or worker service. Logs in trace mode don't return any 6636 or 3389 in logs, like for 9000 or 9443. And no error seen in logs when grep for ldap pattern.
> 
> I specify ldap listen related vars described in https://goauthentik.io/docs/installation/configuration#listen-settings
> 
> EDIT : ldapsearch return error and nc "Connection refused"

@dginhoux The ldap port won't open on the server/worker. It will instead create a new container with the ldap server. The ports in the configuration will be applied to the container. See https://goauthentik.io/docs/providers/ldap/generic_setup

**Comment by boesr** [comment]
After starting a separate ldap outpost container in an interactive session it seems like the ldap container first tries to fetch every existing user. The first few ones went relatively fast. But at the moment (around page 247 with each page having 100 users) ist takes 5 to 10 seconds per page. Since we have close to 100k users that's why it takes hours for the ldap provider to load, I assume. Is there a way to speed up the process?

**Comment by boesr** [comment]
> Hi, thank for yours answers.
> 
> So if i understand, server will take the decision to create new container alone for ldap ? How to handle this in a docker env "user-remaps" and "socketless"... ?

Not sure about that. You can create the container manually and it should be able to communicate with the Authentik server (since it uses the Rest API)

`docker run -e AUTHENTIK_TOKEN=your-token -e AUTHENTIK_HOST=https://your-host.com -d -p 636:6636 --name=ak-outpost-ldap ghcr.io/goauthentik/ldap:2023.10.7`

But not sure if you can further manage the container through the Web UI since the server probably cannot see the container (since you use socketless environment).

**Comment by boesr** [comment]
Unfortunately, setting search mode to direct querying does not solve it completely. The ldap container continuously queries the user pages (like in cached mode) which leads to a 100% cpu usage of the authentik server. I will try to increase the cores it can use (at the moment 8, but went up to 20 when tested before). 

Is there a way to stop the ldap server continuously requesting the user data and only request it a specific user, if a request is sent to the ldap server? 

logs of server:

```
{"auth_via": "api_token", "event": "/api/v3/core/users/?page=785&page_size=100", "host": "auth.mydomain.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 232923, "remote": "10.10.26.1", "request_id": "0013076b2e1243969ce61dd633847a14", "runtime": 53599, "scheme": "https", "status": 200, "timestamp": "2024-02-01T08:01:55.918403", "user": "ak-outpost-2191069e1a3549808c5456eec3758afd", "user_agent": "goauthentik.io/outpost/2023.10.7"}
```

Provider search and bind mode are both set to direct querying.

**Comment by dginhoux** [comment]
> > Hi, thank for yours answers.
> > So if i understand, server will take the decision to create new container alone for ldap ? How to handle this in a docker env "user-remaps" and "socketless"... ?
> 
> Not sure about that. You can create the container manually and it should be able to communicate with the Authentik server (since it uses the Rest API)
> 
> `docker run -e AUTHENTIK_TOKEN=your-token -e AUTHENTIK_HOST=https://your-host.com -d -p 636:6636 --name=ak-outpost-ldap ghcr.io/goauthentik/ldap:2023.10.7`
> 
> But not sure if you can further manage the container through the Web UI since the server probably cannot see the container (since you use socketless environment).

Hi, 

Thank you for your answer ! 
You help me a lot.

I also discover and understand the button on the right of outpost "view deploy info" and this doc: https://version-2023-10.goauthentik.io/docs/outposts#deploy

Architecture and container used are now easier to undertsand for me.
LDAP work fine now.

Now my next step will to integrate authentike in traefik like authelia.

Have a good day
