### ISSUE TITLE
Port for connection

### ISSUE THREAD

**Issue by 12nick12** [goauthentik/authentik#832]
I'm trying to run behind reverse proxy. I just downloaded the new docker-compose.yml and I can't seem to connect on 9443/9000 with and without the reverse proxy. Which port should I be connecting to?

**Comment by BeryJu** [comment]
Please download the latest docker-compose file https://github.com/goauthentik/authentik/blob/version-2021.4/docker-compose.yml, as the version on master is for the upcoming release. I just noticed the docs directly refer you to the compose file on master, I'll change that in a second.

**Comment by 12nick12** [comment]
Ah ok, thank you. I was curious what was going on.
