### ISSUE TITLE
How to change user/library background image for tenant

### ISSUE THREAD

**Issue by Foxy1a** [goauthentik/authentik#8382]
I have been trying to change the background image of the user/library. I have been able to add the custom background that was given in the example but I want to add a local image from the computer authentik resides on. 

I have tried but failed miserably. Any help would be great. 

This works

<img width="558" alt="Screenshot 2024-02-01 153353" src="https://github.com/goauthentik/authentik/assets/110882434/9a3baf78-e9f2-45d7-b7e4-ab570c14a902">

but this doesnt

<img width="532" alt="image" src="https://github.com/goauthentik/authentik/assets/110882434/c6301a18-e70a-4b64-9c71-21df4e948238">

**Comment by BeryJu** [comment]
The second screenshot posted contains invalid CSS and as such will not be honoured by the browser. Aside from that, as long the URL works in the browser it will work in this CSS snippet
