### ISSUE TITLE
TOTP device auth sometimes gives "No compatible device class allowed"

### ISSUE THREAD

**Issue by tobias-urdin** [goauthentik/authentik#8412]
**Describe the bug**
We have users with TOTP devices and when authenticating for an OAuth2 application they sometimes get: "No compatible device class allowed".

I'm out of ideas on how to troubleshoot it, we recently upgraded from 2023.10.4 -> 2023.10.7 and has had this issue on both.

**To Reproduce**

I don't have a reliable way of reproducing it.

1. Entering TOTP when authenticating an application and clicking Continue

**Expected behavior**
Expected the TOTP to be successful or give a better error message.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/14872193/4a8cbab4-9588-4331-a05a-d7521b42dcab)

**Logs**

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.7
-   Deployment: docker-compose

**Additional context**

**Comment by jackhric** [comment]
Just got this bug as well. Selecting "Not You?" and re-signing in seemed to fix this.
