### ISSUE TITLE
HSM   Support 

### ISSUE THREAD

**Issue by HilkopterBob** [goauthentik/authentik#8432]
**Is your feature request related to a problem? Please describe.**
We currently need a  _FIPS 140-2 Level 2_  or  _Common Criteria EAL 4+_ compatible way to store code signing certificates. 
Currently there are only these options:
- A pricy Hardwarekey:
    - single point of failure or extremely pricy (Yubico starting at 650€)
- SoftHSM from the OpenDNSSEC project:
    - lib only
    - need to develop own software solution
- Cloud Services:
    - hard to integrate (eg. AWS)
    - not viable for all businesses

**Describe the solution you'd like**
It would be great to generate and store certs in Authentik and make them usable and attributable via the api to eg. a devops chain. 

**Describe alternatives you've considered**
[Yubico](https://www.yubico.com/de/product/yubihsm-2-series/yubihsm-2-fips/)
[Hardware Appliance](https://www.entrust.com/digital-security/hsm/products/nshield-hsms/nshield-issuance-hsm)
[OpenDNSSEC Lib](https://github.com/opendnssec/SoftHSMv2) for self made soultion
[AWS](https://aws.amazon.com/cloudhsm/)

**Additional context**
I know this feature would generally be against what an HSM was intended for - but it would be the first real self-hostable and open source solution for that class of problems.

**Comment by BeryJu** [comment]
This is not something authentik will do anytime soon as the current certificate management options in authentik are primarily there due to being required by other protocols. Something like https://www.vaultproject.io/ would be a better solution for this use-case.
