### ISSUE TITLE
503 error on initial setup

### ISSUE THREAD

**Issue by davidjmorin** [goauthentik/authentik#847]
**Describe the bug**
I just installed the docker on an AWS instance.  
I put in my email and password and then I get an error.

![image](https://user-images.githubusercontent.com/9400895/117559971-c04f5500-b057-11eb-8ab1-26ff3c5bffe1.png)

**To Reproduce**
1. Go to /if/flow/initial-setup/

**Version and Deployment (please complete the following information):**
 - authentik version: Latest docker version.
 - Deployment: docker-compose

![image](https://user-images.githubusercontent.com/9400895/117560298-9a777f80-b05a-11eb-9587-af900a3cb0f0.png)

**Comment by BeryJu** [comment]
Hi, did you take the docker-compose from the master branch? 

Please use this one instead, as the master one points to two different versions:
https://github.com/goauthentik/authentik/blob/version-2021.4/docker-compose.yml

**Comment by davidjmorin** [comment]
> Hi, did you take the docker-compose from the master branch?
> 
> Please use this one instead, as the master one points to two different versions:
> https://github.com/goauthentik/authentik/blob/version-2021.4/docker-compose.yml

I took the docker compose from the instructions for docker compose on your main website.  I will try the one you linked.  I am also going to try a different environment as AWS i believe may be the issue as well.

**Comment by davidjmorin** [comment]
Ok so using your version of the yml file i get the following error:

```
root@DietPi:~# sudo docker-compose run --rm server migrate
Creating root_server_run ... done
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by BeryJu** [comment]
The current version doesn't support ARM yet, that'll be part of 2021.5

**Comment by davidjmorin** [comment]
> The current version doesn't support ARM yet, that'll be part of 2021.5

Ok perfect.  Thank you sir.  Great work
