### ISSUE TITLE
newest rc docker image already tagged 2024.2

### ISSUE THREAD

**Issue by caspre24** [goauthentik/authentik#8547]
**Describe the bug**
The newest docker image is already tagged with version 2024.2 although this version ist not yet fully released (still on beta, current version is 2024.2.0-rc1).
This breaks automatic version checks like renovate bot since they try to update to the pre release version as if it was a release version.

**To Reproduce**
1. Run docker pull ghcr.io/goauthentik/server:2024.2
2. Docker loads the rc1 pre release image

**Expected behavior**
Only release versions are available under their major.minor version tag

**Screenshots**

**Logs**

**Version and Deployment (please complete the following information):**

-   authentik: 2023.10

**Additional context**
Renovate PR excerpt:
```
This PR contains the following updates:

Package	Update	Change
ghcr.io/goauthentik/server (source)	major	2023.10 -> 2024.2
```

**Comment by BeryJu** [comment]
We're aware of this, sadly github doesn't allow deletion of a single tag so we can't fix this for the time being, it'll be fixed when the full 2024.2 release comes out
