### ISSUE TITLE
No permission for /users/${id}/set_password available

### ISSUE THREAD

**Issue by DrZoidberg09** [goauthentik/authentik#8554]
First of all, great that RBAC is now available.

I can assign all the important permissions incl. create or change user. However, I cannot find a permission that allows set_password. This only works if the user is full super user.

Is this intentionally? Otherwise, it would be super nice to have this as an option.

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/blob/aa87695f3ca8a354b5ca832c4b77879fcd572916/authentik/core/api/users.py#L523 The permission `reset_user_password` should allow for this; possibly `view_user` is also required

**Comment by DrZoidberg09** [comment]
Unfortunately, this did not work for me. I have set these two rules, but not working. Only with full admin. All the others work fine.
