### ISSUE TITLE
LDAP search seems to only return the user performing the search

### ISSUE THREAD

**Issue by kaylee-98** [goauthentik/authentik#8556]
**Describe your question/**
I want to use Authentik as an LDAP provider. I followed to the letter the instructions provided in the documentation. However while testing this, I ran

`ldapsearch -x -H ldap://localhost -D "cn=bind-user,ou=users,DC=ldap,DC=authentik,DC=company" -b "DC=ldap,DC=authentik,DC=company" '(objectClass=user)' -W`

Which I expected would give me information about all the users on the system. However, it returns only the user information for `bind-user` itself. (Yes, `bind-user` is a member of the search group).

**Relevant infos**
I'm using the latest version.
It's also probably pertinent to point out that authentication for other users appears to work fine. It just won't provide a listing. I've tried various things, but to be honest I only vaguely understand LDAP so I didn't get far.
My assumption is that this is something I am doing wrong, rather than some kind of bug, and I'm only posting here in the hope that someone might be able to help me find the right track.

**Logs**
Nothing appears in the logs at all actually.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10
-   Deployment: docker-compose

Thank you :)

**Comment by MaximalCats** [comment]
+1 having the same issue here, anybody figure this out?

**Comment by 0xNIEI** [comment]
Yep, also have the same issue when trying to integrate LDAP with CheckMK. only seeing LDAP Bind User and Group. nothing else.

**Comment by kusold** [comment]
I don't understand why, but your LDAP Service User needs to be added to group `authentik Users`.

**Comment by 0xNIEI** [comment]
I added the ldapservice user to my 'users' (i rename the group from authentik Users to users) group. still doesn't work

**Comment by aep** [comment]
> I just ran into this too, you need edit your LDAP Provider to add a search group of users who can do searches.
> 
> ![image](https://private-user-images.githubusercontent.com/1383438/348347583-be8f3e38-6ea5-42ad-8327-b7c83b119caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTc1OTcsIm5iZiI6MTcyMDgxNzI5NywicGF0aCI6Ii8xMzgzNDM4LzM0ODM0NzU4My1iZThmM2UzOC02ZWE1LTQyYWQtODMyNy1iN2M4M2IxMTljYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMjA0ODE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZhNGM0Y2M4MDVkOGMwZDBkZWFlNjlkMjQ2NGYzMmMyNDliYzI5MWQ2YjkxODEzMzgzYzI0NjFmZjUyNGY0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Kw9HfUbpLq2UT7U5Z7ISlIAjeA-3-wCHx8I40QjlLV4)

Exactly that's what I was missing. I think that should be a screenshot in the docs. Someone care for a PR?

**Comment by BeryJu** [comment]
As said above, the search group is required for a user to be able to view all users in LDAP. I thought we had mentioned this in the docs more clearly but we did not
