### ISSUE TITLE
Proton Pass not recognizing login form with compatibility mode enabled

### ISSUE THREAD

**Issue by mike-lloyd03** [goauthentik/authentik#8568]
**Describe the bug**
While using compatibility mode on the default auth flow, Proton Pass does not recognize either the username or password fields.

**To Reproduce**

1. Enable compatibility mode for `default-authentication-flow`
2. Try to log into an app using that flow
3. Proton Pass does not recognize either of the form fields

**Expected behavior**
Proton Pass recommends the fields

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.7
-   Deployment: docker-compose

**Additional context**
Tried in both Firefox and Chromium on Linux

**Comment by mike-lloyd03** [comment]
Wonderful.

**Comment by hot22shot** [comment]
It is annoying as hell, as of now Authentik form is the only one I have trouble with.

**Comment by JFPCreations** [comment]
+1

**Comment by angerZen** [comment]
Still an issue

**Comment by marpisco** [comment]
Still an issue.

**Comment by dewi-tik** [comment]
This has been raised with the Proton Pass team and they're investigating: https://github.com/goauthentik/authentik/issues/13716#issuecomment-2774996420

**Comment by VULGA01** [comment]
Still an issue and it's really annoying.

**Comment by masterit-dev** [comment]
+1

**Comment by dewi-tik** [comment]
https://github.com/goauthentik/authentik/issues/13716#issuecomment-2968927971

**Comment by TheDeFreeze** [comment]
Still an issue on firefox it seems with proton pass

**Comment by karharry** [comment]
Still an issue regardless of what browser I use.

**Comment by carlos-otero** [comment]
Still an issue for me as well.

**Comment by arwin-swapna** [comment]
Issue for on the password page.
