### ISSUE TITLE
Authentik Outpost Logging Driver

### ISSUE THREAD

**Issue by bioszombie** [goauthentik/authentik#8601]
**Describe your question/**
How can I set the default logging mechanism to fluentd for ak-outpost-ldap? Log format denotes some items as log level info but syslog shows them as error or debug.

Would like to use fluentd to format the logs correctly.

**Relevant infos**
i.e. Version of other software you're using, specifics of your setup
docker
grafana
loki

**Screenshots**

** logs
Example log (no issues with format)

{"attributes":["objectClass","cn","ipServicePort","ipServiceProtocol","modifyTimestamp"],"baseDN":"dc=REDACTED,dc=REDACTED,dc=REDACTED","bindDN":"cn=REDACTED,ou=users,dc=ldap,dc=REDACTED,dc=REDACTED","client":"REDACTED","event":"Search request","filter":"(&(objectclass=ipService)(cn=*)(ipServicePort=*)(ipServiceProtocol=*))","level":"info","requestId":"e9dfe7e6-393a-476a-b66c-910842e7ffa9","scope":"Whole Subtree","timestamp":"2024-02-20T19:30:43Z","took-ms":0}

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.7
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
It is recommended to use a docker logging driver https://docs.docker.com/config/containers/logging/plugins/ to forward the logs to the storage solution of choice
