### ISSUE TITLE
Release notes on website link to rc-1 of helm chart

### ISSUE THREAD

**Issue by macmoritz** [goauthentik/authentik#8620]
**Describe the bug**
Helm 'chart release notes' on website is linked to release candidate 1 (github).

**To Reproduce**
1. Go to the [2024.02 release notes (web)](https://goauthentik.io/docs/releases/2024.2)
2. Click on 'chart release notes'
3. See redirection to goauthentik/authentik release authentik-2024.2.0-rc1

**Expected behavior**
'chart release notes' is linked to (release)[https://github.com/goauthentik/helm/releases/tag/authentik-2024.2.0].

**Comment by BeryJu** [comment]
The release nodes are identical from 2024.2.0-rc1 and 2024.2.0, but #8624 fixes this link anyways
