### ISSUE TITLE
WARNING Memory overcommit must be enabled! 

### ISSUE THREAD

**Issue by bioszombie** [goauthentik/authentik#8627]
**Describe the bug**

After update to AUTHENTIK_TAG=2024.2.0 error for authentik-redis-1 container reads:

1:C 21 Feb 2024 16:01:02.326 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

**To Reproduce**
docker compose up -d

**Expected behavior**
No error to appear

**Screenshots**
log provided. 

**Logs**
log provided

**Version and Deployment (please complete the following information):**

-   authentik version:2024.2.0 
-   Deployment: docker-compose

**Comment by rlowevoiply** [comment]
I am having this same issue, is there a temporary workaround you figured out?

**Comment by teambvd** [comment]
@bioszombie / @rlowevoiply this is a redis requirement ([from their documentation](https://redis.io/docs/management/admin/)), wasn't sure if you were aware - to remedy this, you'll just log in to the shell of your hypervisor (debian/proxmox/ubuntu, unraid, RHEL, etc) and run the command noted:
`sysctl vm.overcommit_memory=1`

To make it permanent, just append to the end of the `sysctl.conf` file:
```echo "sysctl vm.overcommit_memory=1" >> /etc/sysctl.conf```

Or ifyou're running unraid and want to make it permanent, you might have to work around the lack of system permanence by adding the `sysctl vm.overcommit_memory=1` as a line to your `/boot/config/go` file.

More information on [what this does](https://man7.org/linux/man-pages/man5/proc.5.html#:~:text=set%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20to%20zero.-,/proc/sys/vm/overcommit_memory,-This%20file%20contains) from the manpages in case you're curious 👍

**Comment by bioszombie** [comment]
@teambvd This is excellent. Thank you. I was not aware of this. Issue has been resolved.
