### ISSUE TITLE
Broken "New provider" window when using DarkReader plugin

### ISSUE THREAD

**Issue by Mase3206** [goauthentik/authentik#8639]
**Describe the bug**
When trying to create a Provider using Firefox in macOS Sonoma, the setup window only shows "Select type" on the left, nothing in the middle, and the "finish" and "cancel" buttons hanging out the bottom-right side. The options appear to still be clickable, but not being able to see them makes it unusable. Using a different browser (Safari, in my case) works and is a suitable workaround.

**To Reproduce**

1. Using Firefox, log into your Authentik instance with an admin account.
2. Open the admin interface.
3. Open the Applications accordion and click on Providers.
4. Click Create.
5. See error.

**Expected behavior**
The window should open to the "Select type" step in the left pane with a list of protocols to choose from with a radio button beside each one in the right pane. The "finish" and "cancel" buttons should be in the bottom-left corner of the right pane.

**Screenshots**
![Screenshot 2024-02-21 at 10 11 49 PM](https://github.com/goauthentik/authentik/assets/35052448/1a134c60-ec00-456e-835c-95b7f492fbc8)

**Logs**
[auth.log](https://github.com/goauthentik/authentik/files/14369228/auth.log)
(heads up, it's a big file.)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.02
-   Deployment: docker-compose

**Additional context**
I also happened to attempt creating a Provider while in Linux using Firefox, and the same error happened, so it's probably related to the browser.

***Edit** - 17 June, 16:54 UTC:* added platform information in original bug report. Original bug was discovered in macOS. Not sure if the platform has an effect on this bug.

**Comment by Mase3206** [comment]
I'm not entirely sure what happened in a week, but the window works now. I'm still on 2024.02.
 
<img width="1680" alt="image" src="https://github.com/goauthentik/authentik/assets/35052448/fa7594de-b54f-4495-88d3-6a7f4cc3fe02">

I'll try to do some investigating this weekend.

**Comment by Mase3206** [comment]
I bet you're right. I'm now having a different but similar issue where I can't edit the 2-factor authentication methods for myself in Safari, but it works fine in Firefox. I don't think this is an issue with Authentik, so I think I'll close this issue.

**Comment by Aetherinox** [comment]
Did you happen to do anything in particular? I am getting this now. I cannot make it display any providers at all. My screen looks exactly like yours.

Wasn't sure if I should create a new issue, or poke here.

**Comment by Mase3206** [comment]
Very weird. Were you able to see any log entries in the web console?

**Comment by rissson** [comment]
authentik 2024.6.0-rc1, firefox 126.0.1, still can't reproduce

**Comment by Aetherinox** [comment]
> Very weird. Were you able to see any log entries in the web console?

That was the weird thing, no logs out of the normal. Just typical debug / prints.

It has to be something stupid small. And I've got a shovel right now trying to figure out what that might be, because now it's bugging me not knowing.

**Comment by Mase3206** [comment]
I'll try to reproduce it this afternoon. What version of Firefox are you using? I'm assuming you're on Windows, since you tried it using Edge, too.

I have the DarkReader plugin installed, which might be affecting the UI layout (though that would be really weird), but I'm pretty sure it's disabled for my Authentik instance. I'll have to look into that as well.

**Comment by Aetherinox** [comment]
| App | Version |
| --- | --- |
| Firefox | 124.0.2 (64-bit) |
| Edge | 126.0.2592.56 |
| Chrome | 126.0.6478.61 & 126.0.6478.62 |
| Authentik | 2024.4.2 | 
| Docker | 26.1.4, build 5650f9b |

I ensured I killed all plugins for all my browsers, even my youtube plugins, thinking maybe it could have been a conflict. It's just weird.

I tried today after giving it some time, still shows that way for Firefox.

Also, when I tried Firefox on my other system, I'm running Ubuntu 22 LTS, and Firefox v127.0 (snap pack installed). No plugins used over there other than adblock. That's strictly a dev server, and I hardly use the browser. Mostly it's just terminal work.

I might have to check, I think the other day, my main desktop Firefox complained of an update. So I'll have to check it out and try.

**Comment by Mase3206** [comment]
I think I found something! I use DarkReader in Firefox for a lot of websites, but I have it disabled for my Authentik instance, as I just use Authentik's dark theme. However, I just briefly turned it on while the "New provider" window was open, and poof! the interface broke. Here's a [link to a screen capture](https://files.noahsroberts.com/s/YEb46z9kK5aFJHJ) of what's happening. 

Briefly looking at the HTML source as DarkReader changes it doesn't reveal an explanation.

**Comment by Aetherinox** [comment]
So, this is interesting.

I had DarkReader. By had, I mean that it was turned off, but still installed. I have my DarkReader set up to only darken a website when I have toggled that website, I don't make every website dark because certain websites just look bad, and I like to know what the site originally looks like.

I had suspicions that it was DarkReader because on the browser that worked, I installed DarkReader, and everything broke. However, it looked like that by default on Firefox, with DarkReader off.

After investigating, somehow, DarkReader was visually disabled, but in the browser settings that are stored in the filesystem, DarkReader was still enabled, it was not toggled off in the stored settings.

I completely uninstalled DarkReader and cleared the files, and Firefox started working properly.

So it was DarkReader, but it was an odd thing I've never seen before. The plugin looked visually disabled, but the browser didn't fully set the plugin to be disabled. Because when I inspected the Authentik webpage, I found darkreader css injection, even though the plugin was disabled.

**Comment by Mase3206** [comment]
That warning about DarkReader potentially breaking websites doesn't just go for Authentik: it goes for **all** websites. It's usually pretty compatible, but anything that modifies the styling and/or structure of a website can lead to a multitude of issues. By all means, use DarkReader if you want to (which I do), but just be aware of it.

Thanks for joining me on this little adventure, Aetherinox! I think I can call this resolved.

**Comment by Aetherinox** [comment]
Sure thing. I can honestly say this is the first time Dark Reader has ever given me problems, especially this major. Once in awhile it may not color an element, but I've never seen it just flat out break an interface. So it wasn't at the top of my list to check. But it's good to know for future reference if I ever have anything else weird happen.

Thanks again! Problem solved and Authentik works good in Firefox now.
