### ISSUE TITLE
Fortigate SSO SAML Provider Error

### ISSUE THREAD

**Issue by dierkgrossfeld** [goauthentik/authentik#8670]
**Describe the bug**
When I try to connect the fortigate to authentik via SAML the response seems invalid.
Tried with different Firmwares on the Fortigate (7.0.14 and 7.2.7) as well as different authentik versions starting from 2023.10.7 up to 2024.2.1.

Tested different Certificate Chains (valid certs from digicerts as well as self signed) and different digests and encryptions.

Tried also different SAML Attribute mappings afterwards with the same effect

Last tried another SAML IdP which was working instantly out of the box with same settings and config.

**Logs**
Response when settings are matching is :
`
__samld_sp_login_resp [874]: Invalid assertion with 'coin'.
samld_send_common_reply [114]: Code: 5, id: 55122, data_len: 45
samld_send_common_reply [122]:     Attr: 21, 8, ����
samld_send_common_reply [122]:     Attr: 22, 21, Undefined error.
`

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.1
-   Deployment: helm

**Comment by dierkgrossfeld** [comment]
fixed. audience has to be set.

**Comment by nicedevil007** [comment]
maybe someone else finds this later => https://github.com/goauthentik/authentik/pull/9105

**Comment by luis15pt** [comment]
> audience has to be set.

Can you exapand on this, getting same error, was it something in authentil or fortigate ?

**Comment by luis15pt** [comment]
@dierkgrossfeld
