### ISSUE TITLE
Android WebAuthn broken - Unable to login 

### ISSUE THREAD

**Issue by indomitorum** [goauthentik/authentik#8676]
**Describe the bug**
2024 versions break android Webauthn. Failed every single time.  Impossible to login

Had to roll back to [release: 2023.10.2](https://github.com/goauthentik/authentik/commit/8e72fcab59a65e900a35a0faa21fe0bfef4c63c3)

it works flawlessly when rolled back to the above

**To Reproduce**

**Expected behavior**
painless authentication and log in

**Comment by dierkgrossfeld** [comment]
We have the same issue.
If webauthn device is already registered authentication works without any issue.

But as long as no webauthn device is configured one can neither enforce it in the validation flow nor manually in the user profile.

error out of authentik log is:
`Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 291, in get
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 95, in get
    challenge = self._get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 172, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/authenticator_webauthn/stage.py", line 114, in get_challenge
    "registration": loads(options_to_json(registration_options)),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/webauthn/helpers/options_to_json.py", line 71, in options_to_json
    ] = _selection.authenticator_attachment.value
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builtins.AttributeError: 'str' object has no attribute 'value'`

**Comment by BeryJu** [comment]
@dierkgrossfeld That issue is fixed with 2024.2.2
@indomitorum Could you post the logs of the authentik server container?

**Comment by dierkgrossfeld** [comment]
In 2024.2.2 it works for me indeed.
