### ISSUE TITLE
Extending the user Library Page

### ISSUE THREAD

**Issue by masterdot** [goauthentik/authentik#8739]
**Describe your question/**
Is there an easy way to extend/ modify the user library page?
I did find this here: web/src/user/LibraryPage/LibraryPage.ts and it looks like the page im looking for.
I want to extend the ui a bit, add a footer with status information etc. 

Is there a easy way for that? I didnt anything regarding this topic. 

**Relevant info**
docker compose install

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

**Additional context**

**Comment by kensternberg-authentik** [comment]
Hi, @masterdot!  There are two different places where you could make this change.  The first is in `web/src/user/UserInterface.ts:UserInterfacePresentation.render()`; anything added to that will appear on the bottom of _all_ pages that the User can see, including the settings.  The other is `web/src/user/LibraryPage/LibraryPageImpl.ts:LibraryPage.render()`; adding to that will provide information on the page with the Applications list, but not on any of the settings.

The pages are pretty robust and can withstand changes, but you might want to keep them as patches so you can apply your changes to any future updates.  Do recall that we use Lit and ShadowDOM heavily; importing CSS into the ShadowDOM is, frankly, a bit tricky now and then.

**Comment by macmoritz** [comment]
What do you think of the option to add custom (dynamic) tiles? 
The first step could be displaying attributes of an user, which we can change on event or periodically. Later (roughly speaking) allow displaying results of policies.

**Comment by kensternberg-authentik** [comment]
@masterdot I'm afraid that if you want to make these modifications, you'll have to start from the developer edition; it's not something you could modify once it's bundled into the Docker container.

**Comment by macmoritz** [comment]
From my point this is forth a feature request. Would be great if we could configure custom tiles in the deployment / in the admin interfact.

**Comment by BeryJu** [comment]
See https://docs.goauthentik.io/developer-docs/setup/frontend-dev-environment to setup a local authentik development setup, with which you can modify the source of the frontend and make any adjustments.
