### ISSUE TITLE
Users created using Normal enrolment not able to login using OAuth

### ISSUE THREAD

**Issue by roney492** [goauthentik/authentik#8748]
**Expected behavior**
User should be allowed to login using any methods provided email/username matches and vise versa.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/116948023/8435eb63-4074-419b-a1b9-27e7c781fa66)

**Version and Deployment:**

-   authentik version: 2024.2.1
-   Deployment: docker-compose

**Comment by rissson** [comment]
In the source, you can select the appropriate way of matching users if you don't want to match by unique ID:
![image](https://github.com/goauthentik/authentik/assets/18313093/63d90f70-6e1c-461c-b36d-fbeca2d2555e)
