### ISSUE TITLE
NTLM Hash Attribute in LDAP Outpost?

### ISSUE THREAD

**Issue by jcrapuchettes** [goauthentik/authentik#8768]
**Describe your question**
I’m going down the path of figuring out WPA Enterprise WiFi Security. As I have been reviewing posts online and github issues, I’ve been trying to figure out why I wouldn’t be able to use the following setup:  Authentik -> LDAP Outpost -> FreeRADIUS -> UniFi. After setting it all up, the FreeRADIUS server reported "mschap: FAILED: No NT-Password." I noticed that the LDAP settings in FreeRADIUS included `control:NT-Password := 'ipaNTHash'`. I tried adding an attribute to my user in Authentik called `ipaNTHash` and set its value to the NTLM hash of my password. I then tested my setup with `eapol_test` and got a SUCCESS! I've also tested connecting through two different computers and it worked!

My question: Is there a way for me to add a calculation of the NTLM Hash to user attributes when the password is changed? Could I make use of a property mapping?

**Relevant info**
- UniFi Network Application 8.0.24
- FreeRADIUS 3

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.7
-   Deployment: Helm through TrueCharts
-   LDAP Outpost on Docker Swarm

**Additional context**
WPA Enterprise through PEAP-MSCHAPv2 is pretty standard and having to setup FreeRADIUS and FreeIPA seems like a lot given the competition offers their own RADIUS server that supports PEAP-MSCHAPv2. I know that it is possible to setup FreeRADIUS to communicate to Authentik via OAuth2, but that required EAP-TTLS/PAP. I'm not opposed to that with the exception that we have a number of iOS users and from my research, it will be a pain to set them up.

**Comment by jcrapuchettes** [comment]
I would be happy to contribute code or code up my own solution. I just need some direction.

**Comment by rissson** [comment]
> Is there a way for me to add a calculation of the NTLM Hash to user attributes when the password is changed?
Yeah you can do so in the password change flow.

Other question though: why not use the Radius provider directly instead of using the LDAP one?

**Comment by jcrapuchettes** [comment]
Can you help me unpack how I might do that in the password change flow? I didn't see any way to inject arbitrary code.

The RADIUS provider doesn't support PEAP-MSCHAPv2.

**Comment by rissson** [comment]
In the flow `default-password-change` (to adapt if you have a custom one), you'd go to "Stage Bindings", expand the `default-password-change-write` binding, click "Create and bind Policy", select "Expression Policy", give it a meaningful name, and then have an expression that looks like:
```python
user.attributes["ipaNTHash"] = ntlm_hash(context['flow_plan'].context["prompt_data"]["password"])
```
I might be wrong about the code itself, I'm not 100% fluent in authentik policy yet, but it should be this. Also, you'll need to get an ntlm_hash function somehow.

**Comment by jcrapuchettes** [comment]
@rissson your help got me to the point that my testing with `eapol_test` works! The final policy code looks like this:
```python
from Crypto.Hash import MD4
request.user.attributes["ipaNTHash"] = MD4.new(context["prompt_data"]["password"].encode('utf-16-le')).digest().hex()
return True
```

**Comment by rissson** [comment]
Perfect! Would you be willing to contribute to https://docs.goauthentik.io/integrations/?

**Comment by ZUCCzwp** [comment]
how to set the policy in version 2024.2 ? i get the error
![image](https://github.com/goauthentik/authentik/assets/26847647/9cbda07a-61ab-42ec-a9bc-c52726685963)

**Comment by jcrapuchettes** [comment]
@ZUCCzwp you will have to translate that error for us. I haven't upgraded to 2024.2 yet.

**Comment by CppBunny** [comment]
@jcrapuchettes Could you share the freeradius config you used to get it to work with authentik ldap?

**Comment by jcrapuchettes** [comment]
> @ZUCCzwp you will have to translate that error for us. I haven't upgraded to 2024.2 yet.

I configured FreeRADIUS via the pfSense GUI, but attached are the eap and ldap config files.
[eap.txt](https://github.com/goauthentik/authentik/files/15194459/eap.txt)
[ldap.txt](https://github.com/goauthentik/authentik/files/15194460/ldap.txt)

**Comment by jcrapuchettes** [comment]
After upgrading to 2024.4.2, I found (like @ZUCCzwp did) that the Crypto package no longer is included in the shipped docker container. I will post when I find a solution.

**Comment by jcrapuchettes** [comment]
Here is the solution: https://gist.github.com/jcrapuchettes/830c99982e391c858f5b7eb066c02749

**Comment by showier-drastic** [comment]
Hi,

Is it possible to update `ipaNTHash` when user's password is changed by an administrator via admin panel?

**Comment by PopcornPanda** [comment]
@jcrapuchettes I noticed that this policy didn't work if You're reseting password

**Comment by PopcornPanda** [comment]
@showier-drastic 
Admin's set password calls an endpoint that directly sets a new password. It's bypass every policy, so unfortunately not, it's not possible.

The best workaround so far is to generate recovery links or send recovery emails to the user.

**Comment by Arzaroth** [comment]
I didn't want to ask every user to change their passwords in order to populate new hash fields, so I tried to incorporate this into a authentication flow.
I've duplicated the default one and swapped the password stage by a prompt stage.
The prompt stage should have a password field, and a custom validation policy.
Then, I've created the policy as follows :
```python
import os
import base64
import hashlib

from django.contrib.auth import _clean_credentials

from sentry_sdk import start_span

from authentik.core.signals import login_failed
from authentik.lib.utils.reflection import path_to_class

def authenticate(
    request, **credentials
):
    backends = [
        'authentik.core.auth.InbuiltBackend',
        'authentik.core.auth.TokenBackend',
        'authentik.sources.ldap.auth.LDAPBackend',
    ]
    for backend_path in backends:
        try:
            backend = path_to_class(backend_path)()
        except ImportError:
            ak_logger.warning("Failed to import backend", path=backend_path)
            continue
        ak_logger.debug("Attempting authentication...", backend=backend_path)
        with start_span(
            op="authentik.stages.password.authenticate",
            description=backend_path,
        ):
            user = backend.authenticate(request, **credentials)
        if user is None:
            ak_logger.debug("Backend returned nothing, continuing", backend=backend_path)
            continue
        # Annotate the user object with the path of the backend.
        user.backend = backend_path
        ak_logger.info("Successful authentication", user=user.username, backend=backend_path)
        return user

    # The credentials supplied are invalid to all backends, fire signal
    login_failed.send(
        sender=__name__,
        credentials=_clean_credentials(credentials),
        request=request,
    )

def extract_ldap_hash(ldap_hash, salt_size=4):
    if not ldap_hash:
        return None, os.urandom(salt_size)
    try:
        ssha_password = base64.b64decode(ldap_hash).decode('utf-8')
    except Exception:
        return None, os.urandom(salt_size)
    if not ssha_password.startswith('{SSHA}'):
        return None, os.urandom(salt_size)
    cleaned_ssha_password = ssha_password[6:]
    ssha_dec = base64.b64decode(cleaned_ssha_password)
    payload = ssha_dec[:-salt_size]
    salt = ssha_dec[-salt_size:]

    return payload, salt

def generate_ldap_hash(user, password):
    ldap_hash = user.attributes.get("userPassword")
    payload, salt = extract_ldap_hash(ldap_hash)
    check_hash = hashlib.sha1(password.encode('utf-8') + salt).digest()
    return (b'{SSHA}' + base64.b64encode(check_hash + salt)).decode('utf-8')

def generate_ntlm_hash(user, password):
    password_unicode = password.encode('utf-16le')
    return hashlib.new('md4', password_unicode).hexdigest()

def store_user_hash(user, password):
    if not user.attributes:
        user.attributes = {}
    user.attributes["userPassword"] = generate_ldap_hash(user, password)
    user.attributes["ipaNTHash"] = generate_ntlm_hash(user, password)
    return user.save()

user = request.user if request.user and not request.user.is_anonymous else context.get("pending_user")

if user:
    password = context.get("prompt_data", {}).get("password") or context.get("password")
    
    if password:
        if authenticate(request.http_request, username=user.username, password=password):
            store_user_hash(user, password)
            return True
        else:
            ak_message("Invalid password")
            return False
    else:
        ak_message("There is no new password value in context")
        return False
else:
    ak_message("There is no user context")
    return False
```
As you can see in this, I use this policy to populate two fields, for LDAP and RADIUS logins (although I haven't tested it yet).
I don't think doing this is a particularly good idea, as it relies on authentik internals and could break with an update. The flow works nonetheless.

**Comment by QuantumCorral** [comment]
Hi @Junto026 

First of all, thank you for your tutorial! It has been incredibly helpful, and I’ve successfully implemented the expression policy in both the enrollment flow and user settings flow.

However, I’m running into an issue when using the password recovery flow. I get the following error:
Error Details
During the password recovery process, I receive the following traceback:
`
Traceback (most recent call last):  
  File "default-PW-Hash", line 32, in <module>  
  File "default-PW-Hash", line 30, in handler  
  builtins.KeyError: 'prompt_data'  
`

It seems like the password recovery flow does not provide prompt_data, which is available in the other flows. I’m not sure if this is expected behavior or if I’m missing something in my configuration.

Would you happen to know why this is happening? Is there a way to work around it or retrieve the necessary data differently in the password recovery flow?

I really appreciate any guidance you can provide. Thanks in advance for your help!

**Comment by Junto026** [comment]
@QuantumCorral I'm not sure.  The original version PopcornPanda posted worked for the recovery flow for me.  Perhaps share a screenshot of the stages in your password recovery flow, and an exact copy-paste of the expression policy you're using.  

Assuming your password recovery flow has a prompt stage in it, also share a screenshot of the details of that prompt stage's configuration.

Finally, verify the expression policy is binded to the 'user write' stage (the very last stage) in the password recovery flow.  Not an earlier stage in the flow.

**Comment by QuantumCorral** [comment]
@Junto026 I appreciate your input. Here’s what I’ve checked so far:

1. Password Recovery Flow Stages

- I've verified that my password recovery flow has a prompt stage included.
- Attached is a screenshot showing the full sequence of stages in my password recovery flow.

![Image](https://github.com/user-attachments/assets/323823d2-114a-4026-bdd7-bf019c060610)
![Image](https://github.com/user-attachments/assets/0cc035a3-e365-4fa6-a82e-b872a152dbee)

2. Expression Policy

- Below is an exact copy-paste of the expression policy I'm using:
`
import hashlib

def generate_ntlm_hash(password):
    """Generate an NTLM hash from the given password."""
    password_unicode = password.encode('utf-16le')
    return hashlib.new('md4', password_unicode).hexdigest()

def store_ntlm_hash(user, password):
    """Store the NTLM hash in the user's attributes."""
    if not user.attributes:
        user.attributes = {}
    user.attributes["ipaNTHash"] = generate_ntlm_hash(password)
    return user.save()

# Determine if the user is authenticated or pending
user = request.user if request.user and not request.user.is_anonymous else context.get("pending_user")

if user:
    # Extract the password from the context
    password = context.get("prompt_data", {}).get("password") or context.get("password")
    
    if password:
        store_ntlm_hash(user, password)
        return True
    else:
        ak_message("There is no new password value in context")
        return False
else:
    request.context["prompt_data"]["attributes.ipaNTHash"] = generate_ntlm_hash(request.context["prompt_data"]["password"])
    return True
`

3. Prompt Stage Details

- I’ve also attached a screenshot of the prompt stage's configuration to ensure it aligns with how it's supposed to work.

![Image](https://github.com/user-attachments/assets/df86b644-de59-42e3-908f-0239357ae951)
![Image](https://github.com/user-attachments/assets/1996857e-038d-4c09-9e76-32db8c9a088e)

Despite these checks, I'm still encountering the error. Could you take a look and see if there's anything I'm missing? Any insights would be greatly appreciated!

Thanks in advance! 🚀
