### ISSUE TITLE
Proxy provider HTTP basic auth not working

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#880]
**Describe the bug**
I am attempting to create a proxy provider which sends an HTTP basic auth header to the upstream server, similar to the [tautilli example](https://goauthentik.io/docs/integrations/services/tautulli/index). I followed all the steps of the tutorial, but it doesn't seem to work, instead I get the basic auth popup in the browser.

**To Reproduce**
1. Create a group
2. Add group attributes:
```
valetudo_user: foo
valetudo_pass: "b[a}r"
```
3. Add user to group
4. Create proxy provider with:
```
HTTP-Basic Username Key: valetudo_user
HTTP-Basic Password Key: valetudo_pass
```
5. Create Application for provider
6. Create Group Membership Policy for the application
6. Add provider to outpost
7. Access the application
8. A basic auth popup appears. Entering the correct username & password does not work.

**Expected behavior**
The stored credentials should be sent upstream.

**Screenshots**

**Logs**
No relevant logs.

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.5.1
 - Deployment: docker-compose

**Additional context**

**Comment by BeryJu** [comment]
Could you try clearing your cookies on the domain that the outpost application is running on? If you have authenticated on the same domain with the outpost before, you'll have a session which won't contain those HTTP Basic attributes.

**Comment by eglia** [comment]
Thanks for the tip, that indeed fixed the problem.
