### ISSUE TITLE
Add support for docker secrets

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#885]
**Is your feature request related to a problem? Please describe.**

The environment variables in the docker images don´t support docker secrets.
I would like to add `_File` after it, and fill in a path. Something like `/run/secrets/*`
From a security standpoint, please add secrets for this env´s:

`AUTHENTIK_POSTGRESQL__PASSWORD:`
`AUTHENTIK_SECRET_KEY`
`AUTHENTIK_EMAIL__PASSWORD:`

I´ve tried doing it myself, but Authentik, wont find any password.

**Describe the solution you'd like**
Add support for docker secret 

Thanks in advance!

**Comment by BeryJu** [comment]
You can set all of these values to `file:///run/secrets/foo`, see https://goauthentik.io/docs/installation/configuration

**Comment by tpansino** [comment]
@BeryJu I've been playing with this functionality too for the last hour or so, and it looks to be currently broken. I just opened a PR to fix it.

It looks like there aren't any tests for the `config.py` file, is that correct? That might be a good addition to catch issues like this, but I don't have the time to contribute that today.

**Comment by BeryJu** [comment]
@tpansino Cheers, Just merged your PR! There aren't loo many tests for config.py, and no explicit ones currently, that is correct.

**Comment by Akruidenberg** [comment]
thanks! I will try when a new version is out. first setting up traefik forward auth, which is little bit difficult to set up......
