### ISSUE TITLE
Typo at Volume Path on Docker-Compose.yml

### ISSUE THREAD

**Issue by mostdcoa** [goauthentik/authentik#8864]
The Postgresql and redis volumes are missing a "." prior to the local directory location.

This caused me quite the headache until I noticed it.

1. Download the latest docker compose file from using `wget https://goauthentik.io/docker-compose.yml`
2. Observe:
```
postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
>      - database:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
 >     - redis:/data
```

3. See the `>` at the volume paths at the end of each service.

**Expected behavior**
- ./database:/var/lib/postgresql/data
- ./redis:/data

All the other local paths are fine for server and worker

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/47325711/e6419e56-ccaa-4605-a7e4-6021fd8f1a87)

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2024.2.2
-   Deployment: docker compose

**Comment by rissson** [comment]
Those are actually correct and reference the volumes defined below in the `volumes` key.
