### ISSUE TITLE
How to show displayname instead user username in web UI?

### ISSUE THREAD

**Issue by septatrix** [goauthentik/authentik#8877]
**Describe your question**
Is it possible to configure authentik to use the `name` property instead of `username` for the UI?

**Relevant info**
Our users have numerical usernames, i.e. user IDs, instead of their full name or an email address.
In the docs the `name` property is even described as the *display* name so it is very confusing that it is not used to display the users name!

For the login stage it is similarly confusing as users do not know their ID and log in with their email which then gets converted to their ID in the next step. This, however, we were able to get around by adjusting the identification stage.

The expected behavior is to use the name if available and otherwise fall back to the username.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/24257556/73431028-e11a-4956-a853-9d57d529a90b)

**Logs**
-

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.2
-   Deployment: docker-compose

**Additional context**
The email is not the username as we allow users to change it.

**Comment by ifeulner** [comment]
You can change this via the user settings, see the docs here: https://docs.goauthentik.io/docs/interfaces/user/customization#settingsnavbaruserdisplay

**Comment by septatrix** [comment]
Is there a way to set this globally (e.g. via `AUTHENTIK_...`)?

**Comment by BeryJu** [comment]
you can set the same attribute on a group to apply to all users within or you can set it on a Brand which will make it apply to everyone within that.
