### ISSUE TITLE
set container_image to a custom value in outposts,but it does not seem to work

### ISSUE THREAD

**Issue by dalamudx** [goauthentik/authentik#8899]
**Describe the bug**
set container_image to a custom value in outposts,but it does not seem to work

**To Reproduce**

1. Go to 'outposts' under 'advanced settings',edit config and update
```
log_level: info
docker_labels: null
authentik_host: https://auth.xxx.com
docker_network: traefik
container_image: reg.xxx.com/goauthentik/%(type)s:%(version)s
docker_map_ports: true
kubernetes_replicas: 1
kubernetes_namespace: default
authentik_host_browser: https://auth.xxx.com
object_naming_template: ak-outpost-%(name)s
authentik_host_insecure: true
kubernetes_json_patches: null
kubernetes_service_type: ClusterIP
kubernetes_image_pull_secrets: []
kubernetes_ingress_class_name: null
kubernetes_disabled_components: []
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls
```
2. the container 'ak-outpost-xxx' still using ghcr.io as container registry,i want to replace it to my jfrog cr.

**Expected behavior**
can custom cr domain

**Screenshots**

![image](https://github.com/goauthentik/authentik/assets/88395653/defc6908-281d-4ed1-b550-70bc12f4ce0f)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.2
-   Deployment: docker-compose

**Additional context**

**Comment by rissson** [comment]
If you want to template the container image, you're probably looking for `AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE` (https://docs.goauthentik.io/docs/installation/configuration#authentik_outposts), which is a global configuration option.

**Comment by dalamudx** [comment]
> If you want to template the container image, you're probably looking for `AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE` (https://docs.goauthentik.io/docs/installation/configuration#authentik_outposts), which is a global configuration option.
still not work

1. set the custom value to server and worker
![image](https://github.com/goauthentik/authentik/assets/88395653/79862835-ddf8-4d19-a233-9d7a776e6991)
3. delete 'ak-outpost-xxx' container
4. update outposts
```
log_level: info
docker_labels: null
authentik_host: https://auth.xxx.com
docker_network: traefik
container_image: null
docker_map_ports: true
kubernetes_replicas: 1
kubernetes_namespace: default
authentik_host_browser: https://auth.xxx.com
object_naming_template: ak-outpost-%(name)s
authentik_host_insecure: true
kubernetes_json_patches: null
kubernetes_service_type: ClusterIP
kubernetes_image_pull_secrets: []
kubernetes_ingress_class_name: null
kubernetes_disabled_components: []
kubernetes_ingress_annotations: {}
kubernetes_ingress_secret_name: authentik-outpost-tls

```
6. ak-outpost-xxx image is ghcr.io/goauthentik/proxy:latest,and i think version is wrong too,should be 2024.2.2
![image](https://github.com/goauthentik/authentik/assets/88395653/ce698b09-1c11-444e-96ac-e7c7938f8bac)

**Comment by BeryJu** [comment]
Either option to change the outpost image should work, but I haven't been able to reproduce this issue. I'll look into it.

**Comment by dalamudx** [comment]
just want you to know,if i replace the value of container_image to reg.xxx.com/goauthentik/proxy:2024.2.2,it works,still no luck with reg.xxx.com/goauthentik/%(type)s:%(version)s

**Comment by katrinm86** [comment]
same thing here: 
- setting the default for worker/server via AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE
- setting it via terraform or UI in config of the outpost using "container_image"

both just produce "ghcr.io/goauthentik/ldap:latest" - regardless if i directly specify an url or if i use variables ...
