### ISSUE TITLE
Input fields don't have focus during login flow

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#894]
**Is your feature request related to a problem? Please describe.**
When logging in (and presumably during any flow), if an input is requested from the user (e.g. username, password, totp), the text box does not have focus. You first have to click the text box before entering the text.

**Describe the solution you'd like**
The first input text box of each page should automatically get focus.

**Describe alternatives you've considered**

**Additional context**

**Comment by BeryJu** [comment]
I am aware that this is an issue, however I haven't found a way to fix this yet. I am not 100% sure why this happens, I think the combination of lit-html recycling HTML elements and using ShadyDOM to improve compatibility.

**Comment by BeryJu** [comment]
So @eglia I haven't found a possibility to have both improved compatibility and a fixed focus, so I've added a compatibility mode in the flow settings to let the admin decide.
