### ISSUE TITLE
Additional HTTP-Auth? reqired from nextcloud after using SAML login

### ISSUE THREAD

**Issue by mwLabs-eu** [goauthentik/authentik#8958]
**Describe the bug**
After logging in via SAML to Nextcloud, sometimes all my folders are empty. Then, after some time, a HTTP-Auth? windows is coming up. After logging in here, all files are visible again. 

**To Reproduce**
No Idea

**Expected behavior**
SAML login is enough, no additional login is required.

**Screenshots**

![0HEOS1PdKp](https://github.com/goauthentik/authentik/assets/38314677/2941aac4-e667-430b-9cd3-e1991e792b03)
![grafik](https://github.com/goauthentik/authentik/assets/38314677/bbdcae3d-a4d8-465f-9631-3453f4a85a46)
![grafik](https://github.com/goauthentik/authentik/assets/38314677/4715fd71-f8af-4053-853e-ce17fd666b54)
![grafik](https://github.com/goauthentik/authentik/assets/38314677/f0e75bce-02eb-4b1a-bc4e-9e20c110dc41)
![grafik](https://github.com/goauthentik/authentik/assets/38314677/e8260bb1-7231-4611-a7b5-f757841983c4)

**Logs**

**Version and Deployment (please complete the following information):**

-   authentik version: [2024.2.2]
-   Deployment: [docker, unraid]

**Additional context**

**Comment by CryPt00n** [comment]
Moved to OIDC now, which is working without problems.
