### ISSUE TITLE
Can you force local MFA when logging in via Social Login?

### ISSUE THREAD

**Issue by jrdwiz** [goauthentik/authentik#8973]
I'm using Plex as a social login, but I still want users to be prompted for MFA configured in Authentik. 

Non-social-logins are forced to use MFA if configured. This does not appear to work with the Plex login. 

Any input would be appreciated. 

-   authentik version: [2024.2.2]
-   Deployment: Docker

**Comment by BeryJu** [comment]
You can bind the authenticator validation stage to the default-source-authentication and the MFA prompt will happen after the plex login (you can also bind it to the enrollment flow to force users to configure MFA devices)

**Comment by jrdwiz** [comment]
That worked perfectly. I was attempting to resolve it by editing the default-authentication-flow; obviously I was going down the wrong rabbit hole.

Thanks so much for the help.
