### ISSUE TITLE
How to map social login users (discord) to directory groups ?

### ISSUE THREAD

**Issue by ednxzu** [goauthentik/authentik#9008]
**Describe your question/**
I'm trying to map discord users from the discord social login to group within the builtin authentik directory

**Additional context**
I have two sources of authentication, either local using the builtin directory, or via discord auth. I'm trying to figure out how to map discord users to groups (based ideally on their discord role) so that I don't have to manually add them everytime someone new logs in. 

I couldn't find any documentation on this so any help is welcome.

**Comment by los93sol** [comment]
Please post it here if you get this figured out, currently trying to do something similar

**Comment by ednxzu** [comment]
> #5760 might help you

This looks exactly like what I need, thanks, I'll give it a shot !

**Comment by los93sol** [comment]
I got it working for my scenario with this, happy to share the policy expressions I used if you need them

**Comment by rissson** [comment]
> I got it working for my scenario with this, happy to share the policy expressions I used if you need them

Feel free to open a PR (that hopefully doesn't conflict with #5760) or to comment on that PR!

**Comment by rissson** [comment]
I'll close as this appears to be resolved.

**Comment by mamichini** [comment]
> I got it working for my scenario with this, happy to share the policy expressions I used if you need them

@los93sol How do you managed it to work?
