### ISSUE TITLE
ak_call_policy calls always error

### ISSUE THREAD

**Issue by devSparkle** [goauthentik/authentik#9010]
**Describe the bug**
Any attempts to call another policy through `ak_call_policy` throw the following error:
```
 'NoneType' object has no attribute 'pk'
```

**To Reproduce**

1. Create a policy named `test-policy` with the following expression:
```py
return True
```
2. Create a second policy with the following expression:
```py
result = ak_call_policy("test-policy")

return True
```
3. Run the policy on any object, through the "Test" action button.

**Expected behavior**
The `test-policy` should be called, and return a `PolicyResult` object as described [here](https://docs.goauthentik.io/docs/property-mappings/expression#ak_call_policyname-str-kwargs---policyresult).

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.2
-   Deployment: docker-compose

**Comment by devSparkle** [comment]
This is still in issue, as of the latest release.

**Comment by BeryJu** [comment]
@devSparkle do you have the full stacktrace of the error? I wasn't able to reproduce this but I think it could happen if you use `ak_call_policy` with execution logging enabled

**Comment by devSparkle** [comment]
@BeryJu curiously, I can only reproduce this in the "Test Policy" window. Because that failed, we never tried it in the actual policy.

The issue can then be better phrased as "ak_call_policy always error when called through the Test Policy window".

**Comment by BeryJu** [comment]
ok that context already helps, let me test with that
