### ISSUE TITLE
Federation OIDC Groups

### ISSUE THREAD

**Issue by los93sol** [goauthentik/authentik#9011]
I'm attempting to set Authentik up to log in using OIDC federation to another instance of Authentik.  It does actually work, but because the groups don't seem to come across this way there's not much I can actually do with it in my applications.  

I also tried doing this over LDAP, but I can only get it to sync users that way, enabling group sync breaks the sync.  I'd prefer to avoid this route anyway because I don't want it to actually sync since I have a huge number of users and groups and only a few of them will actually be needed so I'd rather do this on demand instead of all up front.

If anyone has any other ideas on how to set this up please let me know, I see several existing issues that appear similar, but am unable to determine if this exact scenario is covered by them.

**Comment by BeryJu** [comment]
This will be supported with 2024.8, see https://docs.goauthentik.io/docs/releases/2024.8#new-features
