### ISSUE TITLE
TF updates don't refresh current user

### ISSUE THREAD

**Issue by szinn** [goauthentik/authentik#9013]
**Describe the bug**
I'm using Terraform to populate my config. If I am logged in to Authentik and am at the main user interface screen and update the config, say meta_icon for an application, the UI doesn't get updated, even with a browser page reload.

I think this applies to user groups, properties etc.

It appears that information from the database is cached and, in my experience, that is a bug waiting to happen.

**To Reproduce**

Description is sufficient

**Expected behavior**
Icon / information gets refreshed.

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively
authentik: 2024.2.0
deployment: helm

-   authentik version: [e.g. 2021.8.5]
-   Deployment: [e.g. docker-compose, helm]

**Additional context**

**Comment by BeryJu** [comment]
This is a special case for applications and especially for the user interface's application list, that list is cached quite heavily due to listing applications like that otherwise needing to run all policies
However any other API endpoint is not cached like that.
