### ISSUE TITLE
Sync more AD/LDAP attributes like displayName

### ISSUE THREAD

**Issue by mgasche** [goauthentik/authentik#9040]
**Is your feature request related to a problem? Please describe.**
We have some apps in our company that we want to connect via Authentik. We have an AD in operation in the company. Now for the apps we need the diplayName in addition to the existing attributes, which are synchronized via Authentik. Because currently only the cn/sAMAccountName (which is identical for us) is displayed in the applications, which makes it difficult to simply associate the accounts with a person.

**Describe the solution you'd like**
Add more attributes such as the displayName, which are synchronized via LDAP in Authentik.

**Describe alternatives you've considered**
There is no real alternative, because there would only be the option to customize the displayNames in each application for each user, which in turn is very time-consuming and sometimes not even feasible.

**Comment by septatrix** [comment]
You can define [property mappings](https://docs.goauthentik.io/docs/property-mappings/) to influence which attributes are synced.

**Comment by mgasche** [comment]
How do I create the property mapping? Because I simply want to query/import the displayName from the AD via LDAP and then use it in a SAML application. <br>
<img width="1123" alt="screenshot authentik" src="https://github.com/goauthentik/authentik/assets/94894860/5b69cc71-e4ac-4700-803f-32ed85f60131">

**Comment by ChenWenBrian** [comment]
i searched many threads, but not find any useful doc which shows how to create a custom ldap property mapping. so bad😂

**Comment by ChenWenBrian** [comment]
I read the code and got the answer finally. And I made a [PR#9524](https://github.com/goauthentik/authentik/pull/9524) just now, which updated the detailed steps on how to write a custom property mapping.

**Comment by BeryJu** [comment]
We've added more documentation for LDAP property mappings since: https://docs.goauthentik.io/docs/sources/ldap/#ldap-source-property-mappings
