### ISSUE TITLE
Custom Captcha is at the bottom of the page

### ISSUE THREAD

**Issue by deadlysnek** [goauthentik/authentik#9045]
**Describe the bug**
Cloudflare Turnstile is at the bottom of the page, requiring the user to scroll down.

**To Reproduce**

1. Add a Captcha stage to the login flow
2. Attempt to login

**Expected behavior**
The Captcha should be displayed in the same location as the username / password fields.

**Screenshots**
![image-4](https://github.com/goauthentik/authentik/assets/47015714/997c3ba3-ad66-4a78-ae60-7c3194448272)

**Logs**
N/A

**Version and Deployment:**

-   authentik version: 2024.2
-   Deployment: docker compose

**Comment by franciscomfcmaia** [comment]
Did you find a solution for this?

**Comment by BeryJu** [comment]
While looking into fixing this, there's an issue with the Turnstile script not support shadow dom, which is what we're using for our frontend. Hence it's not possible to render the challenge within the login box.

For other captchas this can be worked around by rendering them with the "invisible" option, which can be passed as a rendering option for other captchas, however for turnstile this has to be configured in the cloudflare admin dashboard

**Comment by platnub** [comment]
There seems to be solutions out there on using slots to get Turnstile to work when using shadow dom

https://kentonvizdos.com/blog/how-to-use-cloudflare-turnstile-with-lit-components-shadow-dom/

**Comment by platnub** [comment]
Disregard my previous comment. Already seems to be working
