### ISSUE TITLE
Logging into redis with a password but no username is broken

### ISSUE THREAD

**Issue by fullykubed** [goauthentik/authentik#9118]
**Describe the bug**

The constructed connection string contains ` :` even if no username is supported. The redis connection fails.

**To Reproduce**

Set `AUTHENTIK_REDIS__PASSWORD` but not `AUTHENTIK_REDIS__USERNAME`. 

The ser

**Expected behavior**

No `:`

**Logs**

```
{"event": "Redis Connection failed, retrying... (Error while reading from redis-1f0f-master.authentik:6379 : (104, 'Connection reset by peer'))", "level": "info", "logger": "authentik.lib.config", "timestamp": 1712160102.2918358, "redis_url": "redis://:rC31F9HFEOUth9ob3fdBszKUlTlaGa9BtHmq1yJ1z0yGTgBlFNOIi8ZEkhSWJ5Rl@redis-1f0f-master.authentik:6379/0"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.2
-   Deployment: helm

**Additional context**
Seems to be caused by this [commit](https://github.com/goauthentik/authentik/pull/8935) merged a couple weeks ago.

**Comment by BeryJu** [comment]
The commit linked above has not been released yet FYI

**Comment by fullykubed** [comment]
You are right. This was a red-herring. Thanks!
