### ISSUE TITLE
Support for LXCs

### ISSUE THREAD

**Issue by kokomo123** [goauthentik/authentik#915]
**Is your feature request related to a problem? Please describe.**
Linux containers are not a good place for authentik apparently. Whenever i try to use the docker.sock, it reports it as unhealthy and won't give a green checkmark. It will not create it on first install either, it's very odd. Could be do to the systemcalls, or something as i've already enabled the proper flags for docker to operate on my LXC. 
**Describe the solution you'd like**
Perhaps letting linux containers function on this with proper flags, else it's alright, i could make a dedicated vm for this or squeeze it in another virtual machine. 
**Describe alternatives you've considered**
Perhaps trying to tell you what's wrong and why it won't bind to this socket. Logs show nothing whatsoever. 
**Additional context**
I've set up this on Proxmox, the latest version and the latest kernel that is available to me, which as of right now is 5.4. Not sure if you'll be able to do this, but it's worth a shot.

**Comment by kokomo123** [comment]
Nevermind, probably would be pointless since lxc wouldn't work great with docker.

**Comment by BeryJu** [comment]
The issue with the docker service connection showing as red should be solved in 2021.5.4.

Keep in mind this is a fully optional feature. The only extra functionality offered by the docker integration, is that outposts are deployed and managed for you. You can manually deploy and manage them just as easily, see https://goauthentik.io/docs/outposts/manual-deploy-docker-compose

You also only need outposts to support applications that don't support SSO protocols natively.
