### ISSUE TITLE
basic auth creds are not passed 

### ISSUE THREAD

**Issue by ankycooper** [goauthentik/authentik#9189]
**Describe the bug**
basic auth creds are not passed and you get a basic auth login pop-up post authentik login 

**To Reproduce**

1. Deploy any basic auth app or even an whoami container
2. enable proxy for the app (I'm using Nginx Proxy manager with TLS)
3. Use app wizard to set an app and aprovider using forward auth (with proxied URL of the above container), default authN and authZ implicit flows
4. set basic auth keys myapp_user, myapp_pass in the authentication section
5. map this app to the embedded outpost
6. create a new group and add your user to it.
7. Map the keys myapp_user, myapp_pass in the group to real credentials

**Expected behavior**
Login without second prompt

**Screenshots**

**Logs**
Ap per app logs 

192.168.65.1 - - [09/Apr/2024:05:34:45 +0000] "GET / HTTP/1.1" 401 581 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 05:34:45 [error] 10#10: *29 user "myuser@gmail.com" was not found in "/etc/nginx/auth.htpasswd", client: 192.168.65.1, server: , request: "GET / HTTP/1.1", host: "10.0.100.155:8080"
192.168.65.1 - myuser@gmail.com [09/Apr/2024:05:34:45 +0000] "GET / HTTP/1.1" 401 581 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
192.168.65.1 - - [09/Apr/2024:05:35:19 +0000] "GET / HTTP/1.1" 401 581 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
192.168.65.1 - - [09/Apr/2024:05:35:20 +0000] "GET /favicon.ico HTTP/1.1" 401 581 "https://ba.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.2
-   Deployment: docker-compose, helm

**Additional context**
even tried to add the myapp_user, myapp_pass to a user directly with no luck

**Comment by yunylz** [comment]
bump
