### ISSUE TITLE
A rookie proposes SAML user attribute mapping

### ISSUE THREAD

**Issue by biliblihuorong** [goauthentik/authentik#9191]
I'm trying to configure SAML and I'm finding that the CF test results in nothing.
![image](https://github.com/goauthentik/authentik/assets/40906916/8e0940b5-a198-417b-845b-c8d82a3c4dce)

I tried clicking on the preview, but it didn't let me see some fields unlike OIDC.
![image](https://github.com/goauthentik/authentik/assets/40906916/3dc862ce-deda-42b3-a57e-1282ee78b3ef)

I then tried to create a new Property Mappings but I looked up the documentation and I don't know how to get the user's group and the user's nickname username variable name, I read the [documentation](https://version-2024-2.goauthentik.io/docs/property-mappings/expression) but I didn't find the appropriate values, I configured a variable for email and it works fine though.
![image](https://github.com/goauthentik/authentik/assets/40906916/982253d2-75f7-4ee9-84b8-6062a412fa4d)
![image](https://github.com/goauthentik/authentik/assets/40906916/efaf96a4-b258-4136-96b6-a77fc6e6b37e)

**Comment by BeryJu** [comment]
As a reference, you can look at the Property mappings which are created by default by navigating to "Customization -> Property mappings" and unchecking the "Hide managed mappings" option, or checking here: https://github.com/goauthentik/authentik/blob/main/blueprints/system/providers-saml.yaml
