### ISSUE TITLE
Zabbix Integration Issue USername schema not avalilable

### ISSUE THREAD

**Issue by marcolino7** [goauthentik/authentik#9331]
Hi,
I am following this guide to configure Zabbix SAML authentication: https://docs.goauthentik.io/integrations/services/zabbix/
At step to setup Username Attribute I should use this URL: http://schemas.goauthentik.io/2021/02/saml/username that is not a vald URL anymore.
I don't know if this could be the issue, when I try to login i got this issue:
![image](https://github.com/goauthentik/authentik/assets/11460036/5a19084a-2e66-4921-935b-a5b06c549d4e)

I setup https everywhere, but it try to use http as ACS URL.

Thanks in advance for help

**Relevant info**
Version 2024.2.3 on Docker

**Comment by BeryJu** [comment]
http://schemas.goauthentik.io/2021/02/saml/username is not a URL to be accessed but rather a unique identifier, and as such is working as intended

For your error, it looks like zabbix is not aware it is behind a reverse proxy being served as HTTPS, which is a problem not related to authentik

**Comment by marcolino7** [comment]
> http://schemas.goauthentik.io/2021/02/saml/username is not a URL to be accessed but rather a unique identifier, and as such is working as intended
> 
> For your error, it looks like zabbix is not aware it is behind a reverse proxy being served as HTTPS, which is a problem not related to authentik

Thanks a lot, I will ask to zabbix community.

Marco

**Comment by LM1LC3N7** [comment]
@BeryJu , where can I found schemas Authentik uses for external SAML source?
I also tried http://schemas.goauthentik.io/2021/02/saml/username 😅

I would like to configure my external source to send an answer authentik will correctly understand out of the box, but I can't find documentation on this (or miss it?).

(context: I log in on Authentik using a SAML source, which is an existing SSO solution only providing SAML and I need OpenID for an app, which Authentik provide)
