### ISSUE TITLE
Example email template in docs causing error

### ISSUE THREAD

**Issue by CliveTran** [goauthentik/authentik#9332]
**Describe the bug**
Example email template in docs causing error, as I'm new to Authentik & have no experience with Django, it might be hard to figure out why it's behaving this way

**To Reproduce**

1. Go to https://docs.goauthentik.io/docs/flow/stages/email/#example-template
2. Copy example template to Authentik
3. Trigger email stage with example template

**Expected behavior**
Example email template in docs should not cause any error

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/55139389/4382c854-ae29-4435-8324-09f384bdfeac)
(Sorry for the over-exposed screenshot)

**Logs**
`TemplateSyntaxError(\ndjango.template.exceptions.TemplateSyntaxError: 'blocktrans' doesn't allow other block tags (seen \"trans 'You recently requested to change your password for you authentik account. Use the button below to set a new password.'\") inside it"`

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.2.3
-   Deployment: docker-compose

Thanks team

**Comment by BeryJu** [comment]
fixed by #9330
