### ISSUE TITLE
no radius provider defined

### ISSUE THREAD

**Issue by ZUCCzwp** [goauthentik/authentik#9375]
**Describe the bug**
Error reported when running raduis outpost。but actually i have setted radius provider and application.

**To Reproduce**
i have setted radius stage as ldap.
go to "cmd/radius" build and run 

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/26847647/075c66b3-27d6-49b0-ab20-bd7a3d295eb0)
![image](https://github.com/goauthentik/authentik/assets/26847647/ef3936a0-f6a8-4545-a68c-05bbf20b5c27)
![image](https://github.com/goauthentik/authentik/assets/26847647/aa5cc5d6-1f2c-42ff-94b3-38fb0fc10fc3)
![image](https://github.com/goauthentik/authentik/assets/26847647/1c629b62-13b5-4e69-9999-32bf4da367ef)
![image](https://github.com/goauthentik/authentik/assets/26847647/0e754fa1-6cf2-4074-a1f5-13348a946f5a)

**Version and Deployment**

-   authentik version: 2024.2
-   Deployment: Binary deploy

**Comment by zuth-admin** [comment]
Have you figured out what the issue was? I'm running into the exact same problem, where the outpost fails with "no radius provider defined", however there is clearly one defined and attached to the outpost in the UI.
