### ISSUE TITLE
web: Locale setting not respected

### ISSUE THREAD

**Issue by macmoritz** [goauthentik/authentik#9433]
**Describe the bug**
The UI gets translated partly to the system language.

**To Reproduce**
1. Set the locale of the current account to 'automatic via browser'   
2. Change locale to 'EN - English'
3. Open any authentik page

**Expected behavior**
Language setting is used and consistent.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/49832924/12913585-c91e-4d39-8c93-ea7cfe12ee74)

**Version and Deployment (please complete the following information):**
-   authentik version: 2024.4.0
-   Deployment: helm

**Additional context**
German is my browser language.

**Comment by macmoritz** [comment]
I've investigated further: The useragent/request locale is used, the setting in authentik is ignored.  
Tested with chrome devtools, `Ctrl+Shift+P` -> `Show Sensors` -> `Location`.

Location London: everything is english, as expected
Location Berlin: english and german mixed, not expected

**Comment by macmoritz** [comment]
The setting is respect until the next (re-)load of the authentik interface.

**Comment by macmoritz** [comment]
Still not fixed in 2024.4.2.
@BeryJu

**Comment by DenisKevljanin** [comment]
> Still not fixed in 2024.4.2. Friendly reminder @BeryJu

Experiencing the same behavior. Doesn't seem to be fixed. 

Locales in DevTools show de.ts and en.ts. Seems like browser/system locale has priority over the application localization.
It wouldn't bother me too much, if not every single translation would be a literal one e.g. "Client Secret" -> "Client Geheimnis". It hurts to read this :)

**Comment by benedikt-bartscher** [comment]
this is still an issue

**Comment by FloTheSysadmin** [comment]
Same issue

**Comment by schumi2004** [comment]
Present for me in version 2024.8.1
A mixture of NL and EN

**Comment by macmoritz** [comment]
Still an issue in 2024.10.1 @BeryJu  @kensternberg-authentik

**Comment by lfnt3** [comment]
Still an issue in 2024.12.1

**Comment by Skeeve** [comment]
Still not fixed in 2025.10.1
