### ISSUE TITLE
No page showing while accessing from iOS 15 (iPhone 7)

### ISSUE THREAD

**Issue by tugdualenligne** [goauthentik/authentik#9440]
**Describe the bug**
No page showing while accessing from iOS 15 (iPhone 7)

**To Reproduce**
Simply launch your Authentik login page (blank screen appears without any error message)

**Expected behavior**
The login screen should appear

**Screenshots**
Blank screen

**Logs**
N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4
-   Deployment: docker-compose

**Additional context**
Work perfectly well on other devices

**Comment by BeryJu** [comment]
Can you post the logs from the developer logs of the safari window? I don't have a device running iOS 15 to test with

**Comment by tugdualenligne** [comment]
It is the very first time I do this, so I hope this is what you're looking for.
Here's what I believe is the console log from that specific iPhone:
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (default-authentication-flow, line 18)
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (default-authentication-flow, line 23)
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (default-authentication-flow, line 37)
[Error] SyntaxError: Unexpected token '{'
	promiseReactionJob

**Comment by Yaya48** [comment]
Same issues here

**Comment by ykram** [comment]
Can report the same issue on iPadOS 16.3.

**Comment by BeryJu** [comment]
I can't reproduce this on iOS 17.4.1 nor on an iPad. I don't have any earlier devices and while I can't guarantee it work on iOS 15 it should definitely work on iOS 16. I'd recommend clearing the cache in safari and also clearing the cache in cloudflare if you're using that.

**Comment by imholte** [comment]
Same issues here ios 15.0 on iphone 13 Pro Max


> turning off asset minify(and purging cache) seems to fix the issue

how to do that?

**Comment by krim404** [comment]
i can confirm this bug, doesnt appear on newer ios versions.
@4d62 how does your workaround get applied? never heard of asset minify features on the iphone.

**Comment by HarshadkCon** [comment]
i faced same issue in safari, chrome, eventually worked via brave browser.

**Comment by tugdualenligne** [comment]
Hi there, any idea from anyone to solve this?
I’ve tried on my iOS 15 device with Brave: it doesn’t work either

**Comment by imholte** [comment]
> Hi there, any idea from anyone to solve this? I’ve tried on my iOS 15 device with Brave: it doesn’t work either

on iphone all Browsers use the Webkit Engine. It doesn't matter which Browser u use. It's always Webkit. 
If you are below ios 15 you maybe could use https://github.com/UInt2048/CyberKit an backport of modern webkit bundeled with firefox.

**Comment by jorishaenseler15** [comment]
i had the same issue using safari and chrome

Iphone Xs, IOS 16.3.1 

Installed Authentik version is 2024.4.2

**Comment by tugdualenligne** [comment]
This is solved with 2024.6.0-rc1

Very, very cool!

**Comment by HarshadkCon** [comment]
Just tested this with 2024.6.0-rc1 @tugdualenligne - super thank you.

**Comment by BenK885** [comment]
I’m experiencing the same black screen behaviour on multiple iPhone SE (1st generation) running iOS 15.8.6 with Safari.

Environment:

* Authentik 2026.2.1 → 2026.5.3
* Docker deployment

The page loads, but only displays a black screen and never renders the login UI.

I have reproduced this on multiple iPhone SE (1st generation) devices.

Newer iPhones and desktop browsers work as expected.

Upgrading to 2026.2.1 and 2026.5.3 did not change the behaviour. I was experiencing the same black screen on the previous Authentik version as well.
