### ISSUE TITLE
Unable to log into anything after upgrade 2024.2.2 -> 2024.4.0

### ISSUE THREAD

**Issue by mist0706** [goauthentik/authentik#9455]
**Describe the bug**
Unable to browse or authenticate to authentic at all from incognito mode

**To Reproduce**
1. Update from 2024.2.2 -> 2024.4.0
2. Try to visit authentiks main page or any page that requires authentication from authentic

**Expected behavior**
Login page to show

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/10143260/2fb8b028-2c1d-40b1-b710-ac007f78eb17)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 290, in get
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 95, in get
    challenge = self._get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/flows/stage.py", line 172, in _get_challenge
    challenge = self.get_challenge(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/identification/stage.py", line 243, in get_challenge
    source_challenge.is_valid()
  File "/ak-root/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 220, in is_valid
    assert hasattr(self, 'initial_data'), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
builtins.AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2024.4.0
- Deployment: docker-compose through portainer

**Additional context**
nginx proxy manager is used as a reverse proxy

**Comment by BeryJu** [comment]
See https://github.com/goauthentik/authentik/issues/9408 and https://github.com/goauthentik/authentik/issues/9432
