### ISSUE TITLE
Cannot create SAML provider from metadata

### ISSUE THREAD

**Issue by unixfy** [goauthentik/authentik#948]
**Describe the bug**

It seems like it's not possible to create a SAML provider using metadata from the provider. Specifically, the issue seems to relate to the "authorization flow" selection - when any flow is chosen, an error like "Object with slug=a9f1f70d-6788-421d-826a-4dbe523e3e4e does not exist." appears below the dropdown. It should be noted that this does NOT occur when creating a regular SAML provider without metadata.

**To Reproduce**
1. Open Resources > Providers
2. Click Create > SAML Provider from Metadata
3. Upload a metadata file and give the provider a name
4. Click Create
5. Error appears.

**Expected behavior**

I would expect that the SAML provider is created successfully using the flow I select.

**Screenshots**

![screenshot 1](https://share.unixfy.net/direct/dp92m5yq.png)

**Logs**

This event appears consistently when I click "Create":
```
{"event": "Bad Request: /api/v2beta/providers/saml/import_metadata/", "level": "warning", "logger": "django.request", "timestamp": 1622491653.373808}
{"event": "/api/v2beta/providers/saml/import_metadata/", "host": "1.2.3.4", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 17, "request_id": "ee57653dbdcb4000bc37bdd292e35c44", "runtime": 96, "scheme": "https", "size": 0.047, "status": 400, "timestamp": "2021-05-31T20:07:33.374429"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.5.4
 - Deployment: docker-compose

**Comment by lvlts** [comment]
@BeryJu I am having this exact issue with 2023.8.1

Could you reopen this? The description and all steps are identical to the original.
