### ISSUE TITLE
Expression policy error `builtins.KeyError: 'flow_plan'`

### ISSUE THREAD

**Issue by ToshY** [goauthentik/authentik#9486]
**Problem**

_Originally posted by @ToshY in https://github.com/goauthentik/authentik/issues/9477#issuecomment-2080707784_

Using an expression policy in `default-enrollment-flow` fails with error <code>Expression policy error builtins.KeyError: 'flow_plan'</code>.

**Reproduction**

Following-up from #9477, I've continued testing with with `ghcr.io/goauthentik/dev-server:gh-bfc340df160328e1aa0f7dfa4f1592729923ae9c`, and if I add another expression policy (e.g. `custom-enrollment-group`; example taken from [docs](https://docs.goauthentik.io/docs/flow/stages/user_write)) with execution logging disabled, and bind the policy to the `default-source-enrollment` as well, I get both the policy message that user is not allowed to login (from the previous `google-email-expression` policy), but also an additonal message containing `flow_plan`.

`default-source-enrollment`

![image](https://github.com/goauthentik/authentik/assets/31921460/dccc262c-0eff-4935-a882-97b1ae604aa4)

`default-source-enrollment` policies:

![image](https://github.com/goauthentik/authentik/assets/31921460/5a32e6ad-8b8a-4ce5-8210-86bc4ad21c95)

`custom-enrollment-group`

![image](https://github.com/goauthentik/authentik/assets/31921460/a2f38126-d523-4ef0-b55b-62b9b7033408)

**Response**

Response for `user1@gmail.com` (allowed)

![image](https://github.com/goauthentik/authentik/assets/31921460/f0008bcf-2e61-4794-b6e7-e75942088227)

Response for `user3@gmail.com` (not allowed)

![image](https://github.com/goauthentik/authentik/assets/31921460/474227b8-e3c5-420a-ab71-aea02ae96469)

So it shows `flow_plan` in the message as well. Looking in the UI notification the following message is shown:

```text
Traceback (most recent call last):\n  File \"custom-enrollment-group\", line 6, in &lt;module&gt;\n  File \"custom-enrollment-group\", line 4, in handler\nbuiltins.KeyError: 'flow_plan'"
```

So apparently now my second expression policy is broken due to the usage of `request.context["flow_plan"]`. The example was taken from the docs, so what am I doing wrong here?

**Comment by BeryJu** [comment]
The docs should be clearer on this, but the error happens due to the fact that the policies bound directly to a flow are evaluated before the flow planner starts - and as such there's no flow_plan available yet and it can't be accessed in policies

**Comment by ToshY** [comment]
Hey @BeryJu ,

> the policies bound directly to a flow are evaluated before the flow planner starts

Does this correspond with the "pre-flow policies" as denoted by the flow diagram?

> and as such there's no flow_plan available yet and it can't be accessed in policies

Would you then have any suggestions or alternatives on how should I proceed? My objective is to add the users to one (or mulitple) groups automatically.

**Comment by ToshY** [comment]
Hey @BeryJu 

I'll close this as I figured out what I was doing wrong, which was that I added the policy to the "Policy / Group / User Bindings" tab (which are apparently "pre-flow policies"), but what I needed was to add the policy inside the "Stage bindings" tab under the `default-source-enrollment-write`.

![image](https://github.com/goauthentik/authentik/assets/31921460/2bfb3bfb-7a31-42ce-a3c3-e66e7c0ff1b0)

I totally not notice or just overlooked the dropdown arrow icon there, so I had no idea I could open it to add policies to it🤦‍♂️ Makes a lot more sense now, as I see the policy in my flow diagram before the user write stage (which the docs _do_ point out correctly).

![image](https://github.com/goauthentik/authentik/assets/31921460/ae885bf3-af8f-4dd6-91c6-83f34fe71a2b)
