### ISSUE TITLE
Remove flow inspector

### ISSUE THREAD

**Issue by twist3dimages** [goauthentik/authentik#9493]
**Describe your question/**
I would like to remove the Flow Inspector, I am not sure how it got there

**Relevant info**
Using Unraid,  version 2024.4.1. Strangely I am using the latest tag but it says I'm on the Dev version. It displays on every website I have, for example, radarr.domain.com 
![image](https://github.com/goauthentik/authentik/assets/33134502/49dd4dac-febf-46e1-a326-a1a7e69fb5c5)

**Screenshots**

![image](https://github.com/goauthentik/authentik/assets/33134502/838d25ee-eaa2-4e57-a96c-2d495d9ea800)

**Logs**

[authentik.txt](https://github.com/goauthentik/authentik/files/15143656/authentik.txt)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.1
-   Deployment: Unraid / docker

**Additional context**

**Comment by BeryJu** [comment]
Your instance has debug enabled, which should never be enabled for production instances. Make sure there are no environment variables like `AUTHENTIK_DEBUG=true` set anywhere

**Comment by twist3dimages** [comment]
Thanks!
