### ISSUE TITLE
LDAP Property Mapping not working

### ISSUE THREAD

**Issue by FlashIvano** [goauthentik/authentik#9506]
**Describe the bug**

LDAP Property Mapping not working.
In 2024.2.3, it works.

**To Reproduce**

create a LDAP Property Mapping.

**Expected behavior**

**Screenshots**

Property Mappings: 
![image](https://github.com/goauthentik/authentik/assets/60494468/9dc30885-70b4-4096-aa64-69f22e2c94b1)

 Federation and Social login:
![image](https://github.com/goauthentik/authentik/assets/60494468/9fb2a601-dbfa-48d0-a346-4ccaee07475a)

User example:
![image](https://github.com/goauthentik/authentik/assets/60494468/7fd3a6c6-5a11-49e9-a0c3-714e4b51ff71)

user info in AD:
![image](https://github.com/goauthentik/authentik/assets/60494468/21d10db8-f9f3-434f-b757-eed01a56e361)

**Logs**

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.1
-   Deployment: docker-compose

**Additional context**

**Comment by ChenWenBrian** [comment]
Please avoid selecting the ‘cn’ mapping; it conflicts with your custom mapping. Simply remove it, and you’ll be good.
