### ISSUE TITLE
Nextcloud OpenID Connect exception: Object of type UUID is not JSON serializable

### ISSUE THREAD

**Issue by ollioddi** [goauthentik/authentik#9565]
**Describe the bug**
I have setup Nextcloud and Authentik using the official guide and the "OpenID Connect user backend" app.

I can successfully login using Authentik to an existing Nextcloud user, using the "nextcloud_user_id" attribute.to bind the user. However, when creating a new user in Authentik, adding Nextcloud as a provider and application, binding the application to a group and then adding this user to the group, i cannot login.

The logs show that this user is successfully authenticated against the internal application within Nextcloud, However, subsequently the log throws an exception by "anonymous user" with the IP of the Nextcloud host. Reading the logs, it seems to be a serialization issue when Nextcloud queries Authentik.

When logging in as this user, a HTTP status of 403 unauthorized is returned by Nextcloud, presumably because Nextcloud failed to authorize using Authentik.

I am new to SSO and Authentik so any pointers is greatly appreciated.

EDIT: The stacktrace at the bottom shows the exception occuring in Authentik and therefore i've created the issue here.

**Expected behaviour**
A successful provisioned login since the user does not already exist within nextcloud.

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/7466744/bb02b0b3-0695-4d13-8f13-c670e38adfb9)
![image](https://github.com/goauthentik/authentik/assets/7466744/1c621abb-00c5-42ab-be03-3ce66acbadc3)
![image](https://github.com/goauthentik/authentik/assets/7466744/9211cc0a-0a50-49d0-a710-484e596f6c9a)
![image](https://github.com/goauthentik/authentik/assets/7466744/aceeb236-1f21-41ae-b488-b9da3dd66d51)
![image](https://github.com/goauthentik/authentik/assets/7466744/c71f4ac0-2772-4a99-a166-a1e1c872610b)
![image](https://github.com/goauthentik/authentik/assets/7466744/ed79c097-348e-40b1-83d6-09d7ae741f6f)

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/ak-root/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/views/token.py", line 498, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/views/token.py", line 527, in post
    return TokenResponse(self.create_code_response())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/views/token.py", line 562, in create_code_response
    access_token.id_token = access_id_token
    ^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/models.py", line 369, in id_token
    self.token = value.to_access_token(self.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/id_token.py", line 163, in to_access_token
    return provider.encode(final)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/providers/oauth2/models.py", line 284, in encode
    return encode(payload, key, algorithm=alg, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/jwt/api_jwt.py", line 67, in encode
    json_payload = self._encode_payload(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/jwt/api_jwt.py", line 94, in _encode_payload
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
builtins.TypeError: Object of type UUID is not JSON serializable

"http_request": {
        "args": {},
        "path": "/application/o/token/",
        "method": "POST",
        "user_agent": "Nextcloud Server Crawler"
    }
}
User
{
    "pk": 1,
    "email": "",
    "username": "AnonymousUser",
    "is_anonymous": true
}

```
</details>

**Version and Deployment:**
- authentik version: 2024.4.0
- Deployment: Docker Compose on Ubuntu 22.04 VM using Docker version  26.1.0
- Nextcloud AIO 28.0.5
-  OpenID Connect user backend 5.0.2

**Comment by BeryJu** [comment]
What's the expression in the Nextcloud Profile mapping? At first it would seem that this is caused by setting the subject mode to user UUID but that does not raise an error like this. Also I would recommend including the `openid` scope both in authentik and Nextcloud as it's part of the OIDC spec and required to be fully compatible

**Comment by ollioddi** [comment]
Thanks for the quick reply @BeryJu .

The expression for the mapping is the exact same found in the [docs](https://docs.goauthentik.io/integrations/services/nextcloud/#openid-connect-auth)

```
# Extract all groups the user is a member of
groups = [group.name for group in user.ak_groups.all()]

# Nextcloud admins must be members of a group called "admin".
# This is static and cannot be changed.
# We append a fictional "admin" group to the user's groups if they are an admin in authentik.
# This group would only be visible in Nextcloud and does not exist in authentik.
if user.is_superuser and "admin" not in groups:
    groups.append("admin")

return {
    "name": request.user.name,
    "groups": groups,
    # To set a quota set the "nextcloud_quota" property in the user's attributes
    "quota": user.group_attributes().get("nextcloud_quota", None),
    # To connect an already existing user, set the "nextcloud_user_id" property in the
    # user's attributes to the username of the corresponding user on Nextcloud.
    "user_id": user.attributes.get("nextcloud_user_id", user.uuid),
}
```

I've actually fixed part of the issue after your reply by messing around it more, but I'd like to fix it properly and update the docs for anyone else in the same situation.

For good measure, i added `openid` to the scope, but this did not seem to cause any changes other than being proper :-)

I can provision new accounts and login (The scenario which failed) if i:

- Change "User ID mapping" in Nextcloud from  "user_id" to "sub" (The default)
  - Docs: "User ID mapping: sub (or user_id if you need to connect to an already existing Nextcloud user)"
- Use either the custom profile or Authentiks built-in.

Now this works for provisioning users, but it does not allow for a mix of existing users and provisioned users since the only real difference is the Nextcloud mapping of the user id. My guess is the lack of this property for provisioned users, is why the serialization fails, but still allowed myself to login since my account already existed in Nextcloud.

Therefore i cannot currently have it both ways, since if i change to `sub` instead of `user_id`, the existing Nextcloud accounts do not work, and with my own Authentik login, it just provisions a new account.

Do you know how i could configure this to allow for both ways? I'd like to find a permanent fix so that anyone replicating doesn't need to migrate all their existing users if they wish to centralize user management in Authentik in the future.

Thanks for a great product btw. I really do like Authentik and how feature rich it is.

**Comment by BeryJu** [comment]
The issue comes from the line `"user_id": user.attributes.get("nextcloud_user_id", user.uuid),`, as you're falling back to using the UUID, you'll have to convert it to a string with either `str(user.uuid)` or `user.uuid.hex`

**Comment by ollioddi** [comment]
I see. I added the modification of converting it to a string, and can confirm that both scenarios now work as expected. I saw your PR for the docs, so i am just closing this issue. Thanks for the help.
