### ISSUE TITLE
Now it generates the code, but still not working.

### ISSUE THREAD

**Issue by psychedelicu** [goauthentik/authentik#9568]
Now it generates the code, but still not working.

![image](https://github.com/goauthentik/authentik/assets/35727400/142e2c6b-27e9-4e2c-841a-3c12ce826363)

That's the code. Shouldn't Authentik change some things?
https://codefile.io/f/m8RapXVCrC

_Originally posted by @psychedelicu in https://github.com/goauthentik/authentik/issues/9438#issuecomment-2090095683_

**Comment by oblom86** [comment]
The same problem. 
Сode diff in the first block
```php
 # Upgrade WebSocket if requested, otherwise use keepalive
 map $http_upgrade $connection_upgrade_keepalive {
     default upgrade;
     ''      '';
 }
``` 
and in 2 string in location / block
```php
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection $connection_upgrade_keepalive;
``` 
If you need to start the app just del that parts

**Comment by psychedelicu** [comment]
> The same problem. Сode diff in the first block
> 
> ```
>  # Upgrade WebSocket if requested, otherwise use keepalive
>  map $http_upgrade $connection_upgrade_keepalive {
>      default upgrade;
>      ''      '';
>  }
> ```
> 
> and two lines in the location block
> 
> ```
>      proxy_set_header Upgrade $http_upgrade;
>      proxy_set_header Connection $connection_upgrade_keepalive;
> ```
> 
> If you need to start the app just del that parts

still not working.
