### ISSUE TITLE
Initial setup link not working

### ISSUE THREAD

**Issue by melvinotieno** [goauthentik/authentik#9584]
**Describe the bug**

I am using the instructions on this link https://docs.goauthentik.io/docs/installation/docker-compose locally but when visiting the link http://localhost:9000//if/flow/initial-setup/ I get the error not found

**To Reproduce**

Followed the instructions exactly as indicated in the installation page using docker-compose without any modification. 

**Expected behavior**

Expect to see a setup page

**Screenshots**

Docker compose file as downloaded

![image](https://github.com/goauthentik/authentik/assets/46104684/3522c5df-d2da-4330-80a9-2374e430567e)

Screenshot of the setup link not working

![image](https://github.com/goauthentik/authentik/assets/46104684/24f662a1-d28e-4f8c-b936-287404be4902)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.1
-   Deployment: docker-compose

**Additional context**

**Comment by taoyx** [comment]
I also came into this issue with the latest release on Kubernetes (installed with helm)

Also, even I use this command:

kubectl exec -it deployment/authentik-worker  -- ak create_recovery_key 10 akadmin

and gained the accesss to authentik, I cannot add application and provider. 

and either worker and server pod don't report a error:(refer attached file)

The UI of administration area also looks strange

 it was reported worker is NOT connected, even though from kubernets, the worker pod is running properly. 
![image](https://github.com/goauthentik/authentik/assets/23740365/ebe4fec0-2e09-44fe-a77c-84c19378ebc9)

![image](https://github.com/goauthentik/authentik/assets/23740365/488af929-1eaa-43a8-9ef3-9de7650bad8b)

[server.log](https://github.com/goauthentik/authentik/files/15224508/server.log)
[worker.log](https://github.com/goauthentik/authentik/files/15224509/worker.log)

**Comment by taoyx** [comment]
the issue about worker does NOT always occur:

![image](https://github.com/goauthentik/authentik/assets/23740365/a4ba0894-d1f7-4361-9618-0b67046734dc)

but I did encount a error when resetting akadmin password:

```
tyx@prod-k8s-master0:~$ k exec authentik-worker-6f98f5c69-dqsd4 -- ak create_recovery_key 10 akadmin
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018737.915451, "file": "/authentik/lib/default.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018737.9164197, "count": 31}
{"event": "Starting authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1715018738.277128}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1715018738.3010955}
{"event": "Redis Connection successful", "level": "info", "logger": "authentik.lib.config", "timestamp": 1715018738.3064187}
{"event": "Finished authentik bootstrap", "level": "info", "logger": "authentik.lib.config", "timestamp": 1715018738.3072946}
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1715018740.7064164, "version": "2024.4.1"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1715018740.7116814}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7140284, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7154827, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7177207, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.72222, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7266343, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7288077, "path": "authentik.blueprints.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7318976, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7337625, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7361283, "path": "authentik.crypto.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.742469, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7455878, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7490914, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1715018740.7519333, "path": "authentik.admin.settings"}
/ak-root/venv/lib/python3.12/site-packages/opencontainers/distribution/reggie/defaults.py:17: SyntaxWarning: invalid escape sequence '\('
  "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
/ak-root/venv/lib/python3.12/site-packages/facebook/__init__.py:99: SyntaxWarning: invalid escape sequence '\d'
  version_regex = re.compile("^\d\.\d{1,2}$")
Switching to schema 'public'
Store this link safely, as it will allow anyone to access authentik as akadmin.

```

**Comment by cicku** [comment]
The issue went away after a server reboot, I wonder if certain service was not ready.

**Comment by taoyx** [comment]
> I also came into this issue with the latest release on Kubernetes (installed with helm)
> 
> Also, even I use this command:
> 
> kubectl exec -it deployment/authentik-worker -- ak create_recovery_key 10 akadmin
> 
> and gained the accesss to authentik, I cannot add application and provider.
> 
> and either worker and server pod don't report a error:(refer attached file)
> 
> The UI of administration area also looks strange
> 
> it was reported worker is NOT connected, even though from kubernets, the worker pod is running properly. ![image](https://private-user-images.githubusercontent.com/23740365/328269877-ebe4fec0-2e09-44fe-a77c-84c19378ebc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDM2NDQsIm5iZiI6MTcxNTEwMzM0NCwicGF0aCI6Ii8yMzc0MDM2NS8zMjgyNjk4NzctZWJlNGZlYzAtMmUwOS00NGZlLWE3N2MtODRjMTkzNzhlYmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE3MzU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZWIyMzBkOTQyNDNhNDZjNjZiMGYyNTZlYTY4ZGRhYjAzYTcwNDE5NzY0NTAyYzFkNWY3YzkyZTRhODc4NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2COvfT1ZwjaLwSttIMSBu-hysDiiAc-olNz0d0vdYNs)
> 
> ![image](https://private-user-images.githubusercontent.com/23740365/328269904-488af929-1eaa-43a8-9ef3-9de7650bad8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDM2NDQsIm5iZiI6MTcxNTEwMzM0NCwicGF0aCI6Ii8yMzc0MDM2NS8zMjgyNjk5MDQtNDg4YWY5MjktMWVhYS00M2E4LTllZjMtOWRlNzY1MGJhZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE3MzU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3OWMyZDNiZTc0ZDk3ZDI5NjAwMTlkMTcyMWI1MTRkYmVhM2U1YzdkMzY0ZjliM2VjNjI3ZjAzNGIyNjk0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sl5rIumTk9yb-R5CYFLEwe8Y6ONJTsqam8FtPV3AsQs)
> 
> [server.log](https://github.com/goauthentik/authentik/files/15224508/server.log) [worker.log](https://github.com/goauthentik/authentik/files/15224509/worker.log)

On my side, this issue went away after I added the subPath (in Helm Values.yaml file) part for the custom.css. Without 'subPath' clause, the whole dist folder will be overwrite with the only custom file.

hint: you could use browser to check whether error is there.

It was my fault...

but the left part is still with dark color... I don't know why...

`
global:
  volumeMounts:  
    - name: volume-media
      mountPath: /media
    - name: custom-css
      mountPath: /web/dist/custom.css
      subPath: custom.css


  # volumes: []
  volumes: 
    - name: volume-media # tyx
      persistentVolumeClaim:
        claimName: pvc-authentik-media
    - name: custom-css
      configMap:
        name: configmap-css`

**Comment by depuits** [comment]
I'm having a similar issue when upgrading from 2024.4.1 to 2024.4.2.

Following is a snippit from the worker log:

```
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1715538755.9956036 path=authentik.sources.plex.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1715538755.9970844 path=authentik.providers.scim.settings
DBG event=Loaded app settings logger=authentik.lib.config timestamp=1715538755.999732 path=authentik.crypto.settings
/ak-root/venv/lib/python3.12/site-packages/opencontainers/distribution/reggie/defaults.py:17: SyntaxWarning: invalid escape sequence '\('"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
_runit-log:x:998:authentik
```

**Comment by excaliburzarau** [comment]
Hello guys. 

I am having the same issue. I have been trying to deploy authentik with Docker Swarm behind Caddy but for i am having the same issue as reported on this thread. I don't belive i am doing something wrong but i do have to ask if you know that when passing through a folder to the container, should the container or folder be run with a specific user because currently it is the only thing i suspect.

Best Regards

**Comment by taoyx** [comment]
Did you tried the solution I provided above? 

In my case, it was because I mount a volume, which overwrite the original files, after using "-subPath' in K8s, it is working file (Docker has similiar solution.)

**Comment by excaliburzarau** [comment]
> Did you tried the solution I provided above?
> 
> In my case, it was because I mount a volume, which overwrite the original files, after using "-subPath' in K8s, it is working file (Docker has similiar solution.)

Hi,

I did try something similar. described my workaround on the post below.

[https://github.com/goauthentik/authentik/issues/9766](url)

Unfortunately i has to go back to the version 2023.1.1 to got it to work without any change on the docker compose file. I performed some upgrades through versions and i was able to get it work and update it to the latest version.

Best Regards

**Comment by thcrt** [comment]
I was able to work around this by going to `https://auth.my.domain/if/flow/initial-setup/` -- note the trailing slash. 

`... initial-setup/` works, `... initial-setup` doesn't.

Obviously this should be fixed, but this workaround should help in the meantime.

**Comment by excaliburzarau** [comment]
> I was able to work around this by going to `https://auth.my.domain/if/flow/initial-setup/` -- note the trailing slash.
> 
> `... initial-setup/` works, `... initial-setup` doesn't.
> 
> Obviously this should be fixed, but this workaround should help in the meantime.

In my case this solution did not work for me. I had to recreate everything and saddly it did not work. It did work for me but thank you anyways. We now have some ways of bypassing this issue for the time being :)

Best Regards

**Comment by Luci404** [comment]
This is still an issue...

**Comment by cristiansoto** [comment]
I had this issue and the problem was that the worker requires the AUTHENTIK_SECRET_KEY environment variable and has to match with the server's but is not defined in the docker-compose.yml provided in the documentation.

**Comment by pwaldon** [comment]
Hours later, for me the fix was just to restart containers... No single idea what the hell is happening with this 404 crap.

**Comment by che0one** [comment]
Still an issue only works after restart tries multiple times same thing...

**Comment by Jeszee** [comment]
> I was able to work around this by going to `https://auth.my.domain/if/flow/initial-setup/` -- note the trailing slash.
> 
> `... initial-setup/` works, `... initial-setup` doesn't.
> 
> Obviously this should be fixed, but this workaround should help in the meantime.

Dude after my 20th install and 100th time scanning this thread i almost give up. How could i have missed this post... thx man!
