### ISSUE TITLE
authentik as ldap providers  no ou attribute under cn

### ISSUE THREAD

**Issue by itdsee** [goauthentik/authentik#9654]
**Describe the bug**
authentik as ldap providers; When we use a third-party system to connect or use the ldap client to view the LDAP structure, we find that there is no ou attribute under cn; the ou attribute content under the organization ou is also empty, causing the third-party program to be unable to connect.I tried updating the LDAP Property Mapping, but it didn’t work either. Did I set it incorrectly?

**To Reproduce**

**Screenshots**

![auth-1](https://github.com/goauthentik/authentik/assets/132738773/f79f5443-5720-4614-aec1-7a17aa8db9b6)
![auth-2](https://github.com/goauthentik/authentik/assets/132738773/efcccf53-2c7a-4148-9ff0-c74c83e5645b)

**Comment by MaBauMeBad** [comment]
Interessting, i can confirm your issue, but also not.

Let me explain. The OU Attribute is also empty for me, but the attribute is showing up.
![image](https://github.com/goauthentik/authentik/assets/32883466/f1649992-4040-4940-94e0-25e9fe40ef83)

Maybe depending on the LDAP Client ? Used JXplorer for this test
