### ISSUE TITLE
Can't connect Social Logins from user settings in 2024.4.2

### ISSUE THREAD

**Issue by Gunsmithy** [goauthentik/authentik#9657]
**Describe the bug**
There appears to be a regression when upgrading from 2024.4.2 from 2024.4.1. Attempting to add a new social login (only tested with Apple) on the user settings page will say that it was successful, but it is not connected and the connect button remains. Reverting to 2024.4.1 I was able to connect Apple successfully.

**To Reproduce**
1. Have authentik 2024.4.2 installed
2. Have a Social Login Source configured such as Apple
3. Login as a user without any social login connections
4. Go to '/if/user/#/settings;%7B"page"%3A"page-sources"%7D'
5. Click "Connect" for Apple or other source.
6. Follow the external flow back to a success screen on user settings
7. Visually verify that the Social source was not in fact connected

**Expected behavior**
Expected the social login to be connected to the user as it was with 2024.4.1

**Screenshots**
N/A, can provide on request.

**Logs**
Can provide as needed.

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: helm

**Additional context**
Not sure if Enrollment/Auth flows are relevant from the user settings context, if so I can provide those as needed. They should mostly match the defaults and worked on 2024.4.1 at least!

**Comment by BeryJu** [comment]
I'm assuming this is a regression from https://github.com/goauthentik/authentik/pull/9559, although this should've been caught by e2e tests

**Comment by quentinmit** [comment]
I tried using the `version-2024.4` branch which includes 9240fa103715188df6fa05cddb0d49c313c1f049 (the cherrypick of this fix) and it still exhibits the same problem. Is there maybe some kind of state that needs to be cleared after applying the patch?

I get the same behavior as the OP (clicking "Connect" goes through the OAuth flow and shows a "Successfully linked Discord!" message, but the Connect button is still there and no `UserOAuthSourceConnection` was saved to the database).

**Comment by mrskizzex** [comment]
2024.6 also exhibits this issue.

**Comment by TDX44** [comment]
Any updates on this issue? Experiencing it on 4.2.
