### ISSUE TITLE
Can not create App Passwords after update to 2024.4.2

### ISSUE THREAD

**Issue by barnes-c** [goauthentik/authentik#9665]
**Bug description**
When creating a App Password on version 2024.4.2 an empty error appears and no App password is created. 
In the network tab of the browser you can see the reason for this error is that expire of the App password must be in less than a year which it was (see screenshot).

Creating App passwords that have their expiry date in the past works though.

**To Reproduce**

1. Go to 'Tokens and App passwords'
2. Click on 'Create'
3. Fill the form correctly with a date which is in the future but still less than a year away
4. Click Create

**Expected behavior**
A token to be created 

**Screenshots**
<img width="1711" alt="SCR-20240509-rtzp" src="https://github.com/goauthentik/authentik/assets/68067715/db616ad1-b480-4041-9acb-882063a80492">
**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: docker-compose

**Comment by BeryJu** [comment]
Probably a side effect of https://github.com/goauthentik/authentik/pull/9426, are you able to create app passwords through the user interface?

**Comment by barnes-c** [comment]
No, its also not possible to do it via the UI

**Comment by barnes-c** [comment]
This bug still exists in the 2024.6.0 version

**Comment by barnes-c** [comment]
Bug is fixed in 2024.6.1. Thanks guys :)

**Comment by barnes-c** [comment]
This bug still exists in the 2024.6.2 version. 
Easy to recreate if you set the expiry of an token to the future that is nearer than one year

**Comment by barnes-c** [comment]
Thats the same that happens to me @BeryJu . Also still exists in 2024.8.0
