### ISSUE TITLE
I am new user, all seems to be setup, but no idea about the initial admin credentials

### ISSUE THREAD

**Issue by miguelgargallo** [goauthentik/authentik#9680]
I am new user, all seems to be setup, but no idea about the initial admin credentials

**Comment by miguelgargallo** [comment]
![image](https://github.com/goauthentik/authentik/assets/5947268/6b591c94-e3a4-4308-927b-9f84645d06bd)

**Comment by krim404** [comment]
can confirm - i have the same issue on a rollout with docker, http://10.0.1.10:9000/if/flow/initial-setup/ triggers "not found", but the login mask works and i see no errors in the docker logs.
