### ISSUE TITLE
UI bug with file uploads

### ISSUE THREAD

**Issue by controlaltnerd** [goauthentik/authentik#9686]
I've encountered an issue with a fresh Authentik instance (v. 2023.10.7) where the file picker button and clear background toggle are missing entirely from the flow editor (see screenshot). I've spun this instance up in Docker via a docker-compose file copied from another machine running a known good instance of Authentik.

![authentik-screenshot](https://github.com/goauthentik/authentik/assets/112291773/5ada6288-2b68-4966-968e-00448bb975fc)

I've destroyed the container, wiped all data, and rebuilt from scratch several times, but the issue persists across multiple browsers, computers, and IP addresses. My gut says it's a file permissions issue, but the worker container has root access so that shouldn't be an issue.

**Comment by controlaltnerd** [comment]
This is still an issue - has anyone else encountered this?

**Comment by shawnhwei** [comment]
You need to have a Docker or K8s volume mounted to /media, somehow it enables the file picker.

**Comment by controlaltnerd** [comment]
I did have a volume mounted to /media on that install, so it must have been something else. The problem did not persist when I cloned the install, so it must have been something else, perhaps a permissions issue. Closing now, thanks!
