### ISSUE TITLE
Username Validation

### ISSUE THREAD

**Issue by scheibling** [goauthentik/authentik#970]
**Is your feature request related to a problem? Please describe.**
To strengthen security, maybe it could be a good idea to not validate the username ahead of the password stage in the authentication flow. Doing so would prohibit username enumeration in order to determine valid accounts in the environment. 

**Describe the solution you'd like**
Either the possibility to choose whether you'd like to validate usernames ahead of password entry, or making it the default.

**Describe alternatives you've considered**
None currently

**Additional context**
https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_and_Guessable_User_Account
https://www.virtuesecurity.com/kb/username-enumeration/
https://www.hacksplaining.com/prevention/user-enumeration

This is a minor detail in an overall brilliant piece of software, fantastic work so far! I'm really eager to integrate this into my home environment.

**Comment by BeryJu** [comment]
Hi,

the main reason I designed it the way it currently is, is because you might want to only dynamically show the password field, depending on Source IP or GeoIP or Duo push or any other factor. However I do agree with the potential issues of this setup.
