### ISSUE TITLE
Unable to set Authenticator Validation Stage not_configured_action 

### ISSUE THREAD

**Issue by MarkMckessock** [goauthentik/authentik#972]
**Describe the bug**
When updating or creating a new stage, I am unable to choose the "Force the user to configure an authenticator" option as the not configured action even when selecting a configuration flow. Upon closer investigation, it appears that the frontend is only including the 'name' and 'not_configured_action' parameters in the requests to the api. For example, given the following configuration results in this payload being generated: `{name: "default-authentication-flow-totp", not_configured_action: "configure"}`.
![image](https://user-images.githubusercontent.com/14773841/120908798-3d142580-c63c-11eb-8744-90d8565d5b86.png)
Neither the deviceClasses or configurationStage properties are set and sent to the API.

**To Reproduce**
1. Update or create an Authenticator Validation Stage
2. Set 'Not Configured Action' to "Force user to configure an authenticator"
3. For 'Configuration Flow' select "default-authenticator-totp-setup"
4. Click 'Create' or 'Update' and an error is returned

**Expected behavior**
Selecting the "Configuration Flow" should allow the user to choose the "Force user to configure an authenticator" option

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.5.4
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
Both of those issues are already fixed in master, see https://github.com/goauthentik/authentik/commit/3ad1c3f212b732c0705c115165ff427e41ff4735 and https://github.com/goauthentik/authentik/commit/3b41c662ed350ebcffdbe945233f618fcf211560#diff-3b04582de78d498f4ee2d0efbe49a16147b946216625f8d8455494e5746d52cc

Since 2021.6 is pretty close to being done, I don't think its worth the effort to backport the fixes without the features

**Comment by Akruidenberg** [comment]
Tested with version 2021.6.1-RC1, still got an error.

![image](https://user-images.githubusercontent.com/18529293/121506561-1e1ee600-c9e4-11eb-9ba7-d4fac071f1cf.png)

Will try to get some logs later today.
