### ISSUE TITLE
Overriding trusted proxy CIDRs does not work 

### ISSUE THREAD

**Issue by Samppady** [goauthentik/authentik#9720]
Describe the bug
Overriding trusted proxy CIDRs via the configuration flag AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS does not work.

To Reproduce

1. Configure trusted proxy CIDRs in AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS with the syntax AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS='["127.0.0.0/8","::1/128"]'.
2. Restart Authentik
3. Configured trusted proxies does not work (i.e. Authentik does not trust headers from the configured CIDRs).

Expected behavior
Authentik should configure it's trusted proxy CIDR list based on the configured values in AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS.

Same problem #7712 

Additional context
Current workaround (described in https://github.com/goauthentik/authentik/issues/6749) is to mount a custom defaults.yaml file with the CIDRs added (which is confirmed to be working).

Last tested version: 2024.4.1
Deployment: docker-compose

**Comment by rissson** [comment]
The format you're using is wrong. Quoting from https://docs.goauthentik.io/docs/installation/configuration#listen-settings

> List of comma-separated CIDRs that proxy headers should be accepted from

So `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS=127.0.0.0/8,::1/128`

**Comment by Samppady** [comment]
> The format you're using is wrong. Quoting from https://docs.goauthentik.io/docs/installation/configuration#listen-settings
> 
> > List of comma-separated CIDRs that proxy headers should be accepted from
> 
> So `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS=127.0.0.0/8,::1/128`

I did try .env file:  AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fe80::/10,::1/128,192.168.0.0/24

Result: 
  trusted_proxy_cidrs:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - fe80::/10
    - ::1/128

Or 

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.4.2}
    container_name: authentik_server
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fe80::/10,::1/128,192.168.0.0/24

Result: 
  trusted_proxy_cidrs:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - fe80::/10
    - ::1/128
