### ISSUE TITLE
Logout URL for nextcloud?

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#973]
**Is your feature request related to a problem? Please describe.**

I´m in the process of mirgrating nextcloud to an SAML configuration. However, an logout button is missing. I dont´ know the URL for this.

**Describe the solution you'd like**
I would like to add an Logout button to Nextcloud with SAML

**Additional context**
Authentik-version: 2021.5.4
Running with Docker-compose

**Comment by BeryJu** [comment]
So authentik doesn't currently support SLO, however you can set your logout URL to `https://authentik.tld/application/o/<application-slug>/end-session/`, which will show a generic end-session screen.

**Comment by Akruidenberg** [comment]
> So authentik doesn't currently support SLO, however you can set your logout URL to `https://authentik.tld/application/o/<application-slug>/end-session/`, which will show a generic end-session screen.

Thanks! Works very well.
