### ISSUE TITLE
Broken macOS/Safari support

### ISSUE THREAD

**Issue by kriszman** [goauthentik/authentik#9761]
**Describe the bug**
Trying to open Authentik via macOS Safari (v16.2) yields a white screen only as a result of the JS error (ES incompatibility?) mentioned in the screenshot below.

**Screenshots**
![Bildschirmfoto 2024-05-17 um 14 49 19](https://github.com/goauthentik/authentik/assets/77211649/ca261fd1-d72d-4fd5-b60c-811ac0cdff66)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: docker-compose

**Comment by tram98** [comment]
This seems to still occur in Authentik [2026.5.3](https://docs.goauthentik.io/releases/2026.5) with Safari 15.6.1 on MacOS Catalina 10.15.8.
