### ISSUE TITLE
Missing Space in Login Screen for Applications

### ISSUE THREAD

**Issue by flippy1345** [goauthentik/authentik#9769]
**Describe the bug**
The Application name and end of the probably templated "to continue" writing is missing a space.
It is missing for all my applications.

**Expected behavior**
There should be a space in the login screen between "Nightchicken" and "fortzufahren" (to continue)

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/26430962/146a2c3a-9a3e-421e-8674-64a3242bd4cd)

**Version and Deployment**
-   authentik version: 2024.4.2

**Comment by BeryJu** [comment]
This seems to be an issue with the translation which can be fixed here: https://app.transifex.com/authentik/authentik/dashboard/ (you can request access to the language and I'll add you)

**Comment by flippy1345** [comment]
@BeryJu,
I created a join request for german as flippy1345.
