### ISSUE TITLE
Automatic Outpost Deployment via Docker Integration prodouces invalid Traefik Labels

### ISSUE THREAD

**Issue by Hypercookie** [goauthentik/authentik#9786]
**Describe the bug**
When deploying a proxy outpost labels are added automatically which add the outpost to Traefik. For each `single-forward` provider a `Host(<host>)` label has to be used. Authentik generates these as `Host(<host>, <host>, ...)` which is **not possible** anymore since Traefik v3.0 (See [here](https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/?ref=containous.ghost.io#new-v3-syntax-notable-changes) and [here](https://community.traefik.io/t/host-rule-does-not-support-multiple-hostnames-anymore/21518)). This leads to an invalid deployment of the outpost which makes it defacto unusable for users with Traefik >v3.0 since the label can not be disabled as far as I can tell.

**To Reproduce**
Deploy a proxy outpost with multilple providers on a system with Traefik > v3.0 which uses the docker label integration

**Expected behavior**
Authentik should generate a valid label.

**Logs**
```"error while adding rule Host(`<redacted>`,`<redacted>`,`<redacted>`) && PathPrefix(`/outpost.goauthentik.io`): error while adding rule and: error while adding rule Host: unexpected number of parameters; got 3, expected one of [1]"```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: docker-compose

**Comment by LeonMusCoden** [comment]
Experiencing the same issue when switching to traefik v3.

**Comment by DriftDevil** [comment]
I'm also getting the same issue. 
One inconvenient workaround (FYI, I am using Portainer to manage my docker containers/stacks), is to go to the container that was automatically created via outposts, duplicate/edit the container, click on Labels, and then edit the router rule.
![image](https://github.com/goauthentik/authentik/assets/3876331/e8d132d3-3fd3-4120-a4c8-44e0f944f76a)
![image](https://github.com/goauthentik/authentik/assets/3876331/3c14b3af-c571-4eab-89a7-043538ba6204)
![image](https://github.com/goauthentik/authentik/assets/3876331/dbde4436-c4c9-497d-b45d-47af602d8a25)

![image](https://github.com/goauthentik/authentik/assets/3876331/f749e679-ec02-4583-a626-688026c8fbd9)
e.g.
(Host(`a.domain.tld`) || Host(`b.domain.tld`)) && PathPrefix(`/outpost.goauthentik.io`)

**Comment by DriftDevil** [comment]
Found the code in the repo that would need to be updated: 

authentik/providers/proxy/controllers/docker.py:get_labels:Line:~31

        labels[f"traefik.http.routers.{traefik_name}-router.rule"] = (
            f"Host({','.join(hosts)}) && PathPrefix(`/outpost.goauthentik.io`)"
        )


it would need to be updated as (Host(\`host0\`) || Host(\`host1\`) || Host(...)) && PathPrefix(\`/outpost.goauthentik.io\`)"

**Comment by Aetherinox** [comment]
> I'm also getting the same issue. One inconvenient workaround (FYI, I am using Portainer to manage my docker containers/stacks), is to go to the container that was automatically created via outposts, duplicate/edit the container, click on Labels, and then edit the router rule. ![image](https://private-user-images.githubusercontent.com/3876331/338048546-e8d132d3-3fd3-4120-a4c8-44e0f944f76a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzA2OTAsIm5iZiI6MTcxOTYzMDM5MCwicGF0aCI6Ii8zODc2MzMxLzMzODA0ODU0Ni1lOGQxMzJkMy0zZmQzLTQxMjAtYTRjOC00NGUwZjk0NGY3NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDMwNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ViMjMzYTY4MWY5NjVmNmFhOTM5MjFkMTBiYzkxMzMzN2JjNDMzYjhmMWJhMGIyODE1ODEwNDAxMDRhMDlkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.reYlh9x_x4k1IWhrOCw_YHYkh_l3Igo1fj31j2DI8qM) ![image](https://private-user-images.githubusercontent.com/3876331/338048590-3c14b3af-c571-4eab-89a7-043538ba6204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzA2OTAsIm5iZiI6MTcxOTYzMDM5MCwicGF0aCI6Ii8zODc2MzMxLzMzODA0ODU5MC0zYzE0YjNhZi1jNTcxLTRlYWItODlhNy0wNDM1MzhiYTYyMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDMwNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTIxNGQwMTcxNDRjOGZiMzI4ZjE0N2U2NjVjZTY3YmYyYTJmMmQ4Mzg2ZDg5ZjA4ODU4ZTZkNWUxNThiNDFjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._tT66KfZETcDGs11-edJbVjWbXguYff147fVNcKthOQ) ![image](https://private-user-images.githubusercontent.com/3876331/338048630-dbde4436-c4c9-497d-b45d-47af602d8a25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzA2OTAsIm5iZiI6MTcxOTYzMDM5MCwicGF0aCI6Ii8zODc2MzMxLzMzODA0ODYzMC1kYmRlNDQzNi1jNGM5LTQ5N2QtYjQ1ZC00N2FmNjAyZDhhMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDMwNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmEyMWU1ZTQ1Y2E4YmYzNTgxZWU1ZmEyOWVhODdiY2JiYThiMGVlMDJmMTE1NjhmM2VjMzNhZWY1MGY0YzlmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0-KeKNgRmBe96azRerUuSgZ23jFY1fPJa-yINSBupIY)
> 
> ![image](https://private-user-images.githubusercontent.com/3876331/338048790-f749e679-ec02-4583-a626-688026c8fbd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzA2OTAsIm5iZiI6MTcxOTYzMDM5MCwicGF0aCI6Ii8zODc2MzMxLzMzODA0ODc5MC1mNzQ5ZTY3OS1lYzAyLTQ1ODMtYTYyNi02ODgwMjZjOGZiZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDMwNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg3YzA0M2IxMDgzNjlkYzRjNmUyMzg1MTg0ODI2YjUzMDgwMDBjNGFjYjM3Mzk3MGFiZTc0ZWFlZTg0OWI0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.88xgujUPPNeKD_ATMmxp4HPqX0MDoQaVqDoPBFc3Ei0) e.g. (Host(`a.domain.tld`) || Host(`b.domain.tld`)) && PathPrefix(`/outpost.goauthentik.io`)

Thanks for this. That worked good.

Wondering if I can just add the authentik/proxy image to my docker-compose and set it up manually myself so that I can bring it up / down without needing to edit the label in portainer.

**Comment by rissson** [comment]
Would you be willing to open a PR for this?

**Comment by DriftDevil** [comment]
I'll try and see if I can. I'll have to set an environment up. Thanks.

**Comment by dandrade-wave** [comment]
Hi, you have a bug there:
```python
labels[f"traefik.http.routers.{traefik_name}-router.rule"] = (
  f"({' || '.join([f'Host(`{host}`)' for host in hosts])}) && PathPrefix(`/outpost.goauthentik.io`)"
)
```
should be:
```python
labels[f"traefik.http.routers.{traefik_name}-router.rule"] = (
  f"({' || '.join([f'Host({host})' for host in hosts])}) && PathPrefix(`/outpost.goauthentik.io`)"
)
```
with the current version is generating something like this
```python
(Host(``whoami.wavesys.localhost``)) && PathPrefix(`/outpost.goauthentik.io`)
```
the double quote gives a error on traefik.

Can you fixed!

**Comment by rissson** [comment]
Feel free to open a PR
