### ISSUE TITLE
German login message misses a blank

### ISSUE THREAD

**Issue by robertoschwald** [goauthentik/authentik#9797]
**Describe the bug**
The german login message misses a blank.

**To Reproduce**
Switch to german, then login in one of the connected applications. The Authentik login screen message misses a blank.

**Screenshots**
<img width="581" alt="missing_blank_de" src="https://github.com/goauthentik/authentik/assets/1519879/500e16b1-498c-4c90-ab5b-6d36b178e085">

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: K8S

**Comment by BeryJu** [comment]
duplicate of #9769

**Comment by robertoschwald** [comment]
Imho it is in web, not translation. Should
I place the PR against #9797?

**Comment by BeryJu** [comment]
the translation files need to be updated in transifex as that's where all the translation is done, the files are then pulled into the authentik repo automatically
