### ISSUE TITLE
Can’t log in : showing [objet] [object] instead user login field

### ISSUE THREAD

**Issue by AceDenghar** [goauthentik/authentik#9799]
**Describe the bug**
I can not log in authentik, it’s showing [objet] [object] instead user login (see screenshot)

**To Reproduce**

I’m only trying to log in authentik or managed apps

**Expected behavior**

Should see a username field

**Screenshots**

![Screenshot_20240521_173440_Brave.jpg](https://github.com/goauthentik/authentik/assets/69914581/950ad38a-0ef9-4d55-9fce-d7154ab58bcc)

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2

**Additional context**
Don’t know why it happens suddenly

Sorry for my english

**Comment by BeryJu** [comment]
Fixed by https://github.com/goauthentik/authentik/commit/347746cbcd040ce7484710424067ce7c74d94e44#diff-906b2f6e437b7ee5fa1c7aedef1ee74c52d6a5617d8c6e00c75fb8c03b3296f0

**Comment by AceDenghar** [comment]
Thank you 👍

Will wait the update.
