### ISSUE TITLE
Check password policy against a custom service

### ISSUE THREAD

**Issue by badcrc** [goauthentik/authentik#9854]
Hi, 

We would like to have the passwords checks against an internal service, like the option for checking against haveibeenpwned, but local.

What we're trying to achieve is that the users cannot reuse the same password, so we would store the hashes of the old passwords and check against that.

Is it possible to do now?

Thanks!

**Comment by BeryJu** [comment]
This can be done using an expression policy:

create an expression policy, use it either as a validation policy for a prompt stage or before a user_write stage, and you can access `request.context["prompt_data"]["password"]` and can do whatever validation you want with it.

**Comment by HQidea** [comment]
@BeryJu 
But how to check if `request.context["prompt_data"]["password"]` matches the user's password?

**Comment by badcrc** [comment]
What I end doing is storing a hashed version of said password and check against it.

I made a small microservice with flask and send the username and hashed password to it from an expression policy as BeryJu explained.

The microservice is running in the same machine as authentik and is not exposed outside docker and it never has the clear passwords.

**Comment by ruzqat** [comment]
#Here is what worked for me:

I created an expression policy with the following code:
```
# Get the old password hash from the user
from django.contrib.auth.hashers import check_password

# Access the new password from the prompt stage data
new_password = request.context["prompt_data"].get("password", None)

if new_password and check_password(new_password, request.user.password):
    ak_message("New password cannot be the same as the old password.")
    return False

# If passwords do not match, allow the change
return True
```

Now this only worked when i added this as a validation policy to a default-password-change-prompt Stage in default-password-change-prompt. I tried a few approaches with binding policy to various stages, but I'm not sure i did it right, so only the above way worked for me. 

Hope this helps someone!
