### ISSUE TITLE
Authentik keeps requesting to login after successful login

### ISSUE THREAD

**Issue by excaliburzarau** [goauthentik/authentik#9865]
Hello guys,

I have been trying to setup the Authentik on docker swarm behing the Caddy Reverse Proxy but i am now stuck on an issue that i don't fully understand of what is wrong.

First i was having and issue while creating the admin user (initial-setup page not found) on a clean install but by gradually upgrading from the 2023.1.1 version to the current 2024.4.2 i was able to create the admin user.

I then was starting to configure the Authentik but, when i login, it redirects me to the home page and refreshes back to the login page.
Sometimes i was able to get to the admin page where reports that there is an error Fetching object, i was able to see that the session status is unauthenticated and, redirects to the login page.

When i get to the logs i got what is think is the issue as seen below.

```
authentik_server.0.3oh90agwck5h@dockerserver    |  {"event":"tracing request to backend","headers":{"Accept":["*/*"],"Accept-Language":["pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7"],"Cookie":["authentik_csrf=LLoD9SskaTPgw4uocRstcRB0V04lpIWf"],"Priority":["u=1, i"],"Referer":["https://authentik.mydomain.com/if/user/"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Site":["same-origin"],"Sentry-Trace":["5977ec98cdf446bfb6cc7e415c09c970-af0141ce53fe7b69-0"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"],"X-Authentik-Csrf":["LLoD9SskaTPgw4uocRstcRB0V04lpIWf"],"X-Forwarded-For":["10.0.0.38"],"X-Forwarded-Host":["authentik.mydomain.com"],"X-Forwarded-Proto":["https"]},"level":"trace","logger":"authentik.router","timestamp":"2024-05-25T17:12:46+01:00","url":"http://localhost:8000/api/v3/core/applications/?ordering=name&page=1&page_size=100"}
authentik_server.0.3oh90agwck5h@dockerserver    |  {"auth_via": "unauthenticated", "domain_url": "authentik.mydomain.com", "event": "/api/v3/root/config/", "host": "authentik.mydomain.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 70, "remote": "10.0.0.38", "request_id": "68df437e1e0649b28cabd8f5ab7b60d8", "runtime": 180, "schema_name": "public", "scheme": "https", "status": 200, "timestamp": "2024-05-25T16:12:46.296933", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"}
```

I can attach my docker compose file i use on my docker swarm instance and the Caddyfile.

Is there anyone able to provide me some guidance on the issue i am having?

Best Regards

**Comment by excaliburzarau** [comment]
Hi guys, i think i might have found the issue.

On docker swarm, to ensure that the containers talk to each other without exposing the door, a network has to be created with overlay type and has to be then declared as an external network on the compose.

I am not sure if authentik is currently supporting this.

I automatically created an internal network when deploying the stack and it is now working without any issue.

The implications of this is that i have to declare the ports of the containers which internally would mess up the Single Sign On concept on some basic http authentication but at least, at the moment, on the services i have running, only 2 applications are affected which work with Auth0 so it will still redirect to Authentik.

At the moment it does seem that the Docker Swarm is not fully supported.

Thank you
Best Regards

**Comment by cwirz** [comment]
Thanks a lot @excaliburzarau that saved me!

**Comment by excaliburzarau** [comment]
> Thanks a lot @excaliburzarau that saved me!

No worries. I got it working after a few tries but it does seem to be working fine for the moment. The Authentik team is doing an awesome job developing this IDP system. 

Best Regards

**Comment by francescor** [comment]
> On docker swarm, to ensure that the containers talk to each other without exposing the door, a network has to be created with overlay type and has to be then declared as an external network on the compose.

yes, that's kind of the basic of docker swarm isn't it? 

btw: rkokkelk user was so nice to share his swarm configuration with traefik: I had it up and running on my swarm too

https://gist.github.com/rkokkelk/3f2e195dd9f657e99fe77b60cd22fc6c

**Comment by hycday** [comment]
hi @excaliburzarau 
i have the exact same issue (the redirect loop after login, sometimes logging in but with fetch error, etc). I also have Caddy (as caddy-docker-proxy).
can you share how did you fix it exactly in terms of lines of code that you added/changed ? 

that would be super helpful.
maybe @cwirz you know as well as you said it helped you.

Thanks a lot !

**Comment by excaliburzarau** [comment]
> hi @excaliburzarau i have the exact same issue (the redirect loop after login, sometimes logging in but with fetch error, etc). I also have Caddy (as caddy-docker-proxy). can you share how did you fix it exactly in terms of lines of code that you added/changed ?
> 
> that would be super helpful. maybe @cwirz you know as well as you said it helped you.
> 
> Thanks a lot !

Hello. 

What i had to do was create an external overlay network manually and use it on the docker composes. 

docker network create demo-network -d overlay

I believe this command should create it. You then have to deploy the stacks that you want with the created network.

**Comment by hycday** [comment]
@excaliburzarau PERFECT !
it works well :)
BUT, this is the command i had to do: 

`docker network create -d overlay --attachable my-attachable-overlay`

<html><body>
<li>

</li><li class="pl-4 sidebar-hover rounded"><a class="py-2 w-full truncate block" href="https://docs.docker.com/engine/deprecated/" title="Deprecated features" data-ss1721548765="1"><span class="flex items-center gap-2">Deprecated features</span></a></li><li>

</li><li><ul class="ml-3"><li></li></ul></li><li>

</li><li></li><li>

</li><li></li><li>

</li><li></li><li>

</li><li></li><li class="pl-4 sidebar-hover rounded"><a class="py-2 w-full truncate block" href="https://docs.docker.com/copilot/" title="Docker for GitHub Copilot 

Early Access" data-ss1721548765="1"><span class="flex items-center gap-2">Docker for GitHub Copilot
<span class="not-prose px-1 rounded-sm bg-violet-light dark:bg-violet-dark text-white text-xs">Early Access</span></span></a></li><li>

</li><li></li><li>

</li><li></li><li>

</li><li></li><li>

</li><li></li><li>

</li><li></li><li>

</li><div class="hidden md:block bg-background-light dark:bg-gray-dark-100 overflow-y-scroll" x-data="" @togglesidebar.window="
           if ($store.showSidebar == false) {
             document.body.classList.add('overflow-hidden');
             $el.classList.remove('hidden');
             $el.classList.add('fixed', 'z-20', 'left-0', 'top-16', 'w-full', 'flex', 'h-lvh');
             $store.showSidebar = true;
             return;
           }
           document.body.classList.remove('overflow-hidden');
           $el.classList.add('hidden');
           $el.classList.remove('fixed', 'z-20', 'left-0', 'top-16', 'w-full', 'flex', 'h-lvh');
           $store.showSidebar = false;
         "><div class="w-full max-w-none lg:max-w-[300px] ml-auto p-2"><nav id="sectiontree" class="text-sm flex flex-col"><ul><li></li><li class="pl-4 sidebar-hover rounded"><a class="py-2 w-full truncate block" href="https://docs.docker.com/support/" title="Get support" data-ss1721548765="1"><span class="flex items-center gap-2">Get support</span></a></li><li class="pl-4 sidebar-hover rounded"><a class="py-2 w-full truncate block" href="https://docs.docker.com/release-lifecycle/" title="Product release lifecycle" data-ss1721548765="1"><span class="flex items-center gap-2">Product release lifecycle</span></a></li></ul></nav></div></div><div data-pagefind-body="" class="min-w-0 px-4 pb-32"><nav id="breadcrumbs" data-pagefind-ignore="" class="py-4 gap-4 flex items-center text-gray-light dark:text-gray-dark max-w-full min-w-0"><a href="https://docs.docker.com/manuals/" class="link truncate" data-ss1721548765="1">Manuals</a><span>/</span><a href="https://docs.docker.com/engine/" class="link truncate" data-ss1721548765="1">Docker Engine</a><span>/</span><a href="https://docs.docker.com/network/" class="link truncate" data-ss1721548765="1">Networking</a><span>/</span><a href="https://docs.docker.com/network/drivers/" class="link truncate" data-ss1721548765="1">Network drivers</a><span>/</span>
<span class="truncate">Overlay</span></nav><article class="prose max-w-none dark:prose-invert"><h1 data-pagefind-weight="10" class="scroll-mt-36">Overlay network driver</h1><p>The <code>overlay</code> network driver creates a distributed network among multiple
Docker daemon hosts. This network sits on top of (overlays) the host-specific
networks, allowing containers connected to it to communicate securely when
encryption is enabled. Docker transparently handles routing of each packet to
and from the correct Docker daemon host and the correct destination container.</p><p>You can create user-defined <code>overlay</code> networks using <code>docker network create</code>,
in the same way that you can create user-defined <code>bridge</code> networks. Services
or containers can be connected to more than one network at a time. Services or
containers can only communicate across networks they're each connected to.</p><p>Overlay networks are often used to create a connection between Swarm services,
but you can also use it to connect standalone containers running on different
hosts. When using standalone containers, it's still required that you use
Swarm mode to establish a connection between the hosts.</p><p>This page describes overlay networks in general, and when used with standalone
containers. For information about overlay for Swarm services, see
<a class="link" href="https://docs.docker.com/engine/swarm/networking/" data-ss1721548765="1">Manage Swarm service networks</a>.</p><h2 class="scroll-mt-20" id="create-an-overlay-network"><a class="text-black dark:text-white no-underline hover:underline" href="https://docs.docker.com/network/drivers/overlay/#create-an-overlay-network" data-ss1721548765="1">Create an overlay network</a></h2><p>Before you start, you must ensure that participating nodes can communicate over the network.
The following table lists ports that need to be open to each host participating in an overlay network:</p>
Ports | Description
-- | --
2377/tcp | The default Swarm control plane port, is configurable with docker swarm join --listen-addr
4789/udp | The default overlay traffic port, configurable with docker swarm init --data-path-addr
7946/tcp, 7946/udp | Used for communication among nodes, not configurable

<p>To create an overlay network that containers on other Docker hosts can connect to,
run the following command:</p><div data-pagefind-ignore="" class="scroll-mt-20" x-data="" x-ref="root"><div class="group relative">
</div></div></article></div><div class="highlight"><pre tabindex="0" class="chroma"><code class="language-console" data-lang="console"><span class="line"><span class="cl"></span></span></code></pre></div><div data-pagefind-ignore="" class="scroll-mt-20" x-data="" x-ref="root"><div class="group relative"><div class="syntax-light dark:syntax-dark"><div class="highlight"><pre tabindex="0" class="chroma"><code class="language-console" data-lang="console"><span class="line"><span class="cl"> docker network create -d overlay --attachable my-attachable-overlay
</span></span></code></pre></div></div></div></div><p>The <code>--attachable</code> option enables both standalone containers
and Swarm services to connect to the overlay network.
Without <code>--attachable</code>, only Swarm services can connect to the network.</p>
</body>
</html>[Deprecated features](https://docs.docker.com/engine/deprecated/)

[Docker for GitHub Copilot Early Access](https://docs.docker.com/copilot/)

    [Get support](https://docs.docker.com/support/)
    [Product release lifecycle](https://docs.docker.com/release-lifecycle/)

[Manuals](https://docs.docker.com/manuals/)
/
[Docker Engine](https://docs.docker.com/engine/)
/
[Networking](https://docs.docker.com/network/)
/
[Network drivers](https://docs.docker.com/network/drivers/)
/ Overlay
Overlay network driver

The overlay network driver creates a distributed network among multiple Docker daemon hosts. This network sits on top of (overlays) the host-specific networks, allowing containers connected to it to communicate securely when encryption is enabled. Docker transparently handles routing of each packet to and from the correct Docker daemon host and the correct destination container.

You can create user-defined overlay networks using docker network create, in the same way that you can create user-defined bridge networks. Services or containers can be connected to more than one network at a time. Services or containers can only communicate across networks they're each connected to.

Overlay networks are often used to create a connection between Swarm services, but you can also use it to connect standalone containers running on different hosts. When using standalone containers, it's still required that you use Swarm mode to establish a connection between the hosts.

This page describes overlay networks in general, and when used with standalone containers. For information about overlay for Swarm services, see [Manage Swarm service networks](https://docs.docker.com/engine/swarm/networking/).
[Create an overlay network](https://docs.docker.com/network/drivers/overlay/#create-an-overlay-network)

Before you start, you must ensure that participating nodes can communicate over the network. The following table lists ports that need to be open to each host participating in an overlay network:
Ports	Description
2377/tcp	The default Swarm control plane port, is configurable with [docker swarm join --listen-addr](https://docs.docker.com/reference/cli/docker/swarm/join/#--listen-addr-value)
4789/udp	The default overlay traffic port, configurable with [docker swarm init --data-path-addr](https://docs.docker.com/reference/cli/docker/swarm/init/#data-path-port)
7946/tcp, 7946/udp	Used for communication among nodes, not configurable

To create an overlay network that containers on other Docker hosts can connect to, run the following command:

 docker network create -d overlay --attachable my-attachable-overlay

The `--attachable` option enables both standalone containers and Swarm services to connect to the overlay network. Without --attachable, only Swarm services can connect to the network.

Then I added the network in docker-compose like normally

by having at the end: 

```
networks:
  network-overlay:
    external: true
```

and in each service : 
```
    networks:
      - network-overlay
```
and no more loop and setup was complete and all works well #9312 
thanks again !

**Comment by excaliburzarau** [comment]
> @excaliburzarau PERFECT ! it works well :) BUT, this is the command i had to do:
> 
> `docker network create -d overlay --attachable network-overlay`
> 
> The `--attachable` option enables both standalone containers and Swarm services to connect to the overlay network. Without --attachable, only Swarm services can connect to the network.
> 
> Then I added the network in docker-compose like normally
> 
> by having at the end:
> 
> ```
> networks:
>   network-overlay:
>     external: true
> ```
> 
> and in each service :
> 
> ```
>     networks:
>       - network-overlay
> ```
> 
> and no more loop and setup was complete and all works well thanks again !

On my case was swarm which is a litle bit different. Sorry about that.
I AM glad it worked for you also.

Best Regards

**Comment by hycday** [comment]
@excaliburzarau just in case : on the app that i want to protect `https://testapp.domain.ltd` i can see the authentik login screen and can login fine, however, the app itself is giving me 502 (the app calls /api/query?=abc for example and i get a 502 to this and sometimes to the favicon, and sometimes to the root of the app).
Do you have any idea if it is linked or if that is a totally new issue ? 
I dont see any issues in logs :/

**Comment by excaliburzarau** [comment]
> @excaliburzarau just in case : on the app that i want to protect `https://testapp.domain.ltd` i can see the authentik login screen and can login fine, however, the app itself is giving me 502 (the app calls /api/query?=abc for example and i get a 502 to this and sometimes to the favicon, and sometimes to the root of the app). Do you have any idea if it is linked or if that is a totally new issue ? I dont see any issues in logs :/

I believe it my be a different issue. Maybe with the redirects or headers passes on the snippet but i AM unsure. 

But it would Be a good place to start the troubleshooting. 

Best Regards

**Comment by excaliburzarau** [comment]
> @excaliburzarau just in case : on the app that i want to protect `https://testapp.domain.ltd` i can see the authentik login screen and can login fine, however, the app itself is giving me 502 (the app calls /api/query?=abc for example and i get a 502 to this and sometimes to the favicon, and sometimes to the root of the app). Do you have any idea if it is linked or if that is a totally new issue ? I dont see any issues in logs :/

I was also thinking about this and confirm that the type of network is correct and the config on the inspect of the network is correct. I had to manually set the subnet and gateway on my case. Best Regards.

**Comment by hycday** [comment]
all good now :) i did a clean reinstall, i believe there was some issue in some file and all worked out now, thanks a lot for the follow up @excaliburzarau i appreciate your help and time !

**Comment by hycday** [comment]
I am getting a CORS issue ("strict-origin-when-cross-origin") on the subpage, so unsure if it's on authentik side, or caddy side, or else :/

**Comment by excaliburzarau** [comment]
> I am getting a CORS issue ("strict-origin-when-cross-origin") on the subpage, so unsure if it's on authentik side, or caddy side, or else :/ without authentik it works perfectly well btw i created this issue to not hijack your thread : #10557

It might not be related but i set the custom headers on the snippet like this:

(authentik) {
        # always forward outpost path to actual outpost
        reverse_proxy /outpost.goauthentik.io/* http://authentik_ip:9900

        # forward authentication to outpost
        forward_auth http://authentik_ip:9900 {
                uri /outpost.goauthentik.io/auth/caddy

        	# capitalization of the headers is important, otherwise they will be empty
                copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version X-Forwarded-Host Authorization

		# optional, in this config trust all private ranges, should probably be set to the outposts IP
                #trusted_proxies private_ranges
        }
}

Again, it might not be related but it did some changes on the headers because it sometimes gave me errors while loading the page.

Best Regards

**Comment by hycday** [comment]
works :) thank you !!

**Comment by excaliburzarau** [comment]
I AM glad it helped. Best Regards
