### ISSUE TITLE
Traefik 3 has been released, API change and old api removal.

### ISSUE THREAD

**Issue by J-eremy** [goauthentik/authentik#9869]
**Describe the bug**

The middlewares that the outpost is creating is still using the old API for traefik of traefik.containo.us/v1alpha1. That API has been depricated in t he current version of traefik and the CRD's for the entire API have been removed and no longer function. The name has changed to traefik.io/v1alpha1.  This is a breaking change as anything trying to use the old naming does not function.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
-   Deployment: [e.g. docker-compose, helm]

**Additional context**
![image](https://github.com/goauthentik/authentik/assets/934651/b8a25e5d-401c-4df4-9321-161f35a07233)
![image](https://github.com/goauthentik/authentik/assets/934651/a98b5f88-3b64-420b-92a0-fbf0a6c52e8f)
https://traefik.io/blog/announcing-traefik-proxy-2-10/
![image](https://github.com/goauthentik/authentik/assets/934651/b411728c-ed92-4ebd-9786-733423505033)

**Comment by rissson** [comment]
Pretty sure we're supporting that since #5801 and 2023.6.

Could you provide your authentik version?

**Comment by J-eremy** [comment]
> Pretty sure we're supporting that since #5801 and 2023.6.
> 
> Could you provide your authentik version?

I am going to close this because it was completely my fault. I installed Authentik via helm template because I manage it with argocd and I am a difficult person that makes everything completely declarative.  In me doing that it is my responsibility to make sure it works.  Sorry for wasting your time.
