### ISSUE TITLE
Theme: authentik theme is affected by the os/browser theme

### ISSUE THREAD

**Issue by Adrian-DKFZ** [goauthentik/authentik#9896]
**Describe the bug**
Despite setting the theme to "light" in the brand settings, it acts weird and is affected by a dark os/browser theme, remaining dark or mixing light and dark color schemes.

**Expected behavior**
Setting the theme to light actually sets it to light.

**Screenshots**
![grafik](https://github.com/goauthentik/authentik/assets/145431101/5abc0b2c-a5fd-41e0-8090-c10f4d690fde)
![grafik](https://github.com/goauthentik/authentik/assets/145431101/0121e19a-71c5-450b-8892-3f8689de6b34)
![grafik](https://github.com/goauthentik/authentik/assets/145431101/b1ea1f4b-f4f5-463b-93db-5341361c314a)
![grafik](https://github.com/goauthentik/authentik/assets/145431101/c481752a-1f9b-43b0-bec3-80fec42af071)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: docker-compose

**Comment by hsilva-keep** [comment]
I have the same issue...

**Comment by jmaferreira** [comment]
I also have the same issue. Is there a fix on the way?

**Comment by BeryJu** [comment]
Most of these issues should be fixed with 2024.8, there were a bunch of theme fixes especially related to auto theme switching
