### ISSUE TITLE
MFA Fails the first request but is successful on the second

### ISSUE THREAD

**Issue by hanley-development** [goauthentik/authentik#9934]
**Describe the bug**
After password authentication, MFA TOTP and Duo Push fails the first time, but if click return to device picker and request again it succeeds. 

**To Reproduce**

1. Go to app.company
2. Enter username
3. Enter password
4. Select TOTP or Duo Push
5. Enter TOTP or Allow Duo auth request on phone
6. FAILED TO AUTHENTICATE
7. Select Return to Device Picker
8. Select TOTP or Duo Push
9. Enter New TOTP or Allow New Duo auth request
10. Success

**Expected behavior**
1. Go to app.company
2. Enter username
3. Enter password
4. Select TOTP or Duo Push
5. Enter TOTP or Allow Duo auth request on phone
6. Success

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/99109069/80c0963c-2f8f-4918-802b-8100e9bc0cbc)

**Logs**
[authentik_server-2024-05-31T19-00-01-MFA2.log](https://github.com/user-attachments/files/15518145/authentik_server-2024-05-31T19-00-01-MFA2.log)
[authentik_server-2024-05-31T18-52-43-MFA1.log](https://github.com/user-attachments/files/15518146/authentik_server-2024-05-31T18-52-43-MFA1.log)

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: docker-compose

**Additional context**

**Comment by psilantropy** [comment]
Did you ever solve this? I get this problem too, it's pretty annoying having to wait 30 seconds every time if the timing is _wrong._

**Comment by ehellman** [comment]
I also have this problem. Passing TZ to the containers do not help sadly. Mapping /etc/localtime and /etc/timezone to the containers did nothing either. Seems like a bug? I am using 2024.6

**Comment by travisaustin** [comment]
Same problem here.

**Comment by travisaustin** [comment]
Check out https://github.com/goauthentik/authentik/issues/5972#issuecomment-2075631779. There are 2 MFA steps in the default auth flow!
