### ISSUE TITLE
authentik/ADFS: Authentication failed: Could not retrieve profile.

### ISSUE THREAD

**Issue by Adrian-DKFZ** [goauthentik/authentik#9973]
**Describe the bug**
After setting up ADFS for use with OIDC and setting it up in authentik, we now receive the error message "Authentication failed: Could not retrieve profile." when trying to login.

**To Reproduce**

1. Setup in ADFS:
Follow the guide under https://support.just.social/hc/de/articles/12713877575186-SSO-mit-ADFS-und-OpenID-Connect-OIDC (also works for other OIDC applications, in our case we also added the profile an email scope, translation might be required as it is written in german)
2. Add ADFS as an external OIDC IdP to authentik
3. Try to log in

**Expected behavior**
Authentik logs in through ADFS.

**Logs**

    {
      "auth_via": "unauthenticated",
      "domain_url": "[REDACTED]",
      "event": "Unable to fetch user profile",
      "exc": "HTTPError('401 Client Error: Unauthorized for url: https://[REDACTED]/adfs/userinfo')",
      "host": "[REDACTED]",
      "level": "warning",
      "logger": "authentik.sources.oauth.clients.oauth2",
      "pid": 42, "request_id": "0ed6d9c8079a4a859817b6efc43f38ff",
      "response": "401 Client Error: Unauthorized for url: https://[REDACTED]/adfs/userinfo",
      "schema_name": "public",
      "timestamp": "2024-06-04T14:38:11.313910"
    }

**Version and Deployment:**

-   authentik version: 2024.4.2
-   Deployment: docker-compose

**Comment by bligneri** [comment]
I have the same issue. It looks like Authentik can only send `basic auth` or `Include the client ID & secret as request parameters` but Zoho wants a bearer token ?

https://accounts.zoho.com/.well-known/openid-configuration

I added the well-known but it does not work either.

```
1) Successfull auth
 {"auth_via": "session", "domain_url": "bla.com", "event": "/source/oauth/login/zoho/", "host": "bla.com", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 2616, "remote": "10.244.2.52", "request_id": "desada98e783f5793ab069b", "runtime": 272, "schema_n │
│ ame": "public", "scheme": "https", "status": 302, "timestamp": "2025-06-29T03:26:43.935347", "user": "benadmin", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"}                                                                                     │

2) Not able to retrieve profile => fails the authentication
│ {"auth_via": "session", "domain_url": "bla.com", "event": "Unable to fetch user profile", "exc": "HTTPError('401 Client Error:  for url: https://accounts.zoho.com/oauth/user/info')", "host": "blas.monitoresa.com", "level": "warning", "logger": "authentik.sources.oauth.clients.oauth2", "pid": 2616 │
│ , "request_id": "dasdasdaswqerqwerc0b06e8f09bf9", "response": "401 Client Error:  for url: https://accounts.zoho.com/oauth/user/info", "schema_name": "public", "timestamp": "2025-06-29T03:26:45.118466"}                  
```

**Comment by NicoJDE** [comment]
Has anyone managed to do it?
