### ISSUE TITLE
Healthcheck endpoints returning 404

### ISSUE THREAD

**Issue by wuast94** [goauthentik/authentik#9975]
**Describe the bug**
```
wget http://proxy_authentik-server:9000/-/health/live/
Connecting to proxy_authentik-server:9000 (10.0.17.8:9000)
wget: server returned error: HTTP/1.1 404 Not Found
```

**Expected behavior**
get the 204 response

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: swarm

**Additional context**
When i query the full https domain through my proxy i get the 204.

i want to monitor authentik using uptimekuma and dont want to have the proxy in beetween for healthchecks

**Comment by rpoovey** [comment]
+1

**Comment by wuast94** [comment]
not stale

**Comment by wuast94** [comment]
not stale

**Comment by BeryJu** [comment]
The only cause for this I can imagine is that your internal hostname contains an underscore, which docker compose v1 did (and I assume swarm inherits from that), which is not actually a valid DNS character and as such django throws an error. However that should result in a 500 or similar response.

**Comment by wuast94** [comment]
that sounds logical but nothing i can do about sadly
